/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/__adb.c File Reference
#include <adb.h>
*
#include <interrupt.c>
*
#include <delay.c>
*
Macros
#define __ADB__
#define ADBBUFFERLENGTH 1024
Enumerations
enum MAIN_STATE { MAIN_STATE_WAIT_CONNECT,
MAIN_STATE_WAIT_OPEN,
MAIN_STATE_RECV
 }
Functions
void ADBreceive (ADB_CHANNEL_HANDLE h, const void *data, unsigned int data_len)
unsigned char _ADBInit ()
unsigned char _ADBOpen ()
unsigned char ADBAvailable ()
u16 ADBRead (u8 *buffer)
void ADBSend (u8 *buffer, u16 data_len)
Variables
ADB_CHANNEL_HANDLE h
u16 adbwpointer
u16 adbrpointer
char adbrx [ADBBUFFERLENGTH]
Macro Definition Documentation
#define __ADB__
Definition at line 30 of file __adb.c.
#define ADBBUFFERLENGTH 1024
Definition at line 37 of file __adb.c.
Referenced by ADBreceive().
Enumeration Type Documentation
enum MAIN_STATE
Enumerator
MAIN_STATE_WAIT_CONNECT
MAIN_STATE_WAIT_OPEN
MAIN_STATE_RECV
Definition at line 40 of file __adb.c.
             {
  MAIN_STATE_WAIT_CONNECT,
  MAIN_STATE_WAIT_OPEN,
  MAIN_STATE_RECV
} MAIN_STATE;
Function Documentation
unsigned char _ADBInit ()
Definition at line 94 of file __adb.c.
References ADBInit(), INT_SYSTEM_CONFIG_MULT_VECTOR, and IntConfigureSystem().
{
    IntConfigureSystem(INT_SYSTEM_CONFIG_MULT_VECTOR);
    ADBInit();
}
unsigned char _ADBOpen ()
Definition at line 100 of file __adb.c.
References ADBChannelReady(), ADBOpen(), ADBreceive(), ADBTasks(), Delayms(), FALSE, h, and TRUE.
{
    u32 wait=0;
    
    h = ADBOpen("tcp:2000", &ADBreceive);
    while ((wait<1000)&&(!ADBChannelReady(h)))
        {
            ADBTasks();
            Delayms(1);
            wait++;
        }
    if (wait<1000) return TRUE;
    else return FALSE;
}
unsigned char ADBAvailable ()
Definition at line 115 of file __adb.c.
References adbrpointer, and adbwpointer.
Referenced by ADBRead().
{
    return(adbwpointer!=adbrpointer);
}
u16 ADBRead (u8 * buffer)
Definition at line 120 of file __adb.c.
References ADBAvailable(), adbrpointer, and adbrx.
{
    u16 data_len;
    u16 i;
    
    if (ADBAvailable())
        {
            data_len=adbrx[adbrpointer++];
            data_len+=(adbrx[adbrpointer++]>>8);
            for (i=0;i<data_len;i++)
                buffer[i]=adbrx[adbrpointer++];
            return(data_len);
        }
}
void ADBreceive (ADB_CHANNEL_HANDLE h, const void * data, unsigned int data_len)
Definition at line 55 of file __adb.c.
References ADBBUFFERLENGTH, adbrpointer, adbrx, and adbwpointer.
Referenced by _ADBOpen().
{
    unsigned char caractere;
    unsigned char length;
    u16 newwp;
    u16 i;
    
    for (i=0;i<2;i++) // first store in buffer frame length
        {
            length=(data_len>>(i*8)); // LSB first then MSB of frame length
                    
            if (adbwpointer!=ADBBUFFERLENGTH-1) // if not last place in
       buffer
                newwp=adbwpointer+1; // place=place+1
            else
                newwp=1; // else place=1
            if (adbrpointer!=newwp) // if read pointer!=write pointer
                adbrx[adbwpointer++]=length; // store received char
                    
            if (adbwpointer==ADBBUFFERLENGTH) // if write pointer=length
       buffer
            adbwpointer=1; // write pointer = 1
        }
    
    for (i=0;i<data_len;i++) // then store received byte
        {
            caractere=((const unsigned char *) data)[i];
            
            if (adbwpointer!=ADBBUFFERLENGTH-1) // if not last place in
       buffer
                newwp=adbwpointer+1; // place=place+1
            else
                newwp=1; // else place=1
            if (adbrpointer!=newwp) // if read pointer!=write pointer
                adbrx[adbwpointer++]=caractere; // store received char
                    
            if (adbwpointer==ADBBUFFERLENGTH) // if write pointer=length
       buffer
            adbwpointer=1; // write pointer = 1
        }
            
}
void ADBSend (u8 * buffer, u16 data_len)
Definition at line 135 of file __adb.c.
References ADBWrite(), and h.
{
    ADBWrite(h,buffer,data_len);
}
Variable Documentation
u16 adbrpointer
Definition at line 48 of file __adb.c.
Referenced by ADBAvailable(), ADBRead(), and ADBreceive().
char adbrx[ADBBUFFERLENGTH]
Definition at line 50 of file __adb.c.
Referenced by ADBRead(), and ADBreceive().
u16 adbwpointer
Definition at line 48 of file __adb.c.
Referenced by ADBAvailable(), and ADBreceive().
ADB_CHANNEL_HANDLE h
Definition at line 46 of file __adb.c.
Referenced by _ADBOpen(), ADBSend(), drawBitmap(), FillRect(), InvertRect(), ST7565_drawBitmap(), ST7565_drawRect(), and ST7565_fillRect().