/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/__zigbee.c File Reference
#include <typedef.h>
*
#include <macro.h>
*
#include <zigbee/mrf24j40.c>
*
Macros
#define __ZIGBEE
Functions
void init_zigbee (u8 _channel, u16 pan_id, u16 short_address)
void ZIGinterrupt (void)
void mrf24j40_transmit_callback (uns8 status, uns8 retries, uns8 channel_busy)
Callback is actioned when mrf24j40 has finished transmitting a packet, or failed to do so.
void mrf24j40_receive_callback ()
Callback is actioned when mrf24j40 has a packet received off air.
void ZIGputs (u16 short_address, u8 *zigstr, u8 length)
int ZIGavailable ()
u8 ZIGgets (u8 *zigstr)
Variables
unsigned char ZIGrx [128]
unsigned char zwpointer
unsigned char zrpointer
u16 ZIGdestpan
u16 ZIGsrcpan
u16 ZIGdestadd
u16 ZIGsrcadd
Macro Definition Documentation
#define __ZIGBEE
Definition at line 25 of file __zigbee.c.
Function Documentation
void init_zigbee (u8 _channel, u16 pan_id, u16 short_address)
Definition at line 41 of file __zigbee.c.
References mrf24j40_init(), mrf24j40_set_channel(), mrf24j40_set_pan_id(), mrf24j40_set_short_address(), and mrf24j40_setup_io().
{
    mrf24j40_setup_io();
    mrf24j40_init();
    // RB : 30-08-2013 - Uncommented following lines
    mrf24j40_set_pan_id(pan_id);
    mrf24j40_set_short_address(short_address);
    mrf24j40_set_channel(_channel);
}
void mrf24j40_receive_callback ()
Callback is actioned when mrf24j40 has a packet received off air.
Callback indicating the mrf24j40 has a packet ready.
Definition at line 67 of file __zigbee.c.
References mrf24j40_flush_receive_buffer(), mrf24j40_long_addr_read(), and ZIGrx.
Referenced by mrf24j40_handle_isr().
{
    unsigned char length,i,character;
    unsigned char znewwp;
    unsigned char data[128];
        length=mrf24j40_long_addr_read(0x300);
        for (i=0;i<length;i++)
            ZIGrx[i]=mrf24j40_long_addr_read(0x301+i);
        mrf24j40_flush_receive_buffer();
/*
    length=mrf24j40_receive(data, 128);
    if (length>0)
        for (i=0;i<length;i++)
            {
                    if (zwpointer!=127) // if not last place in buffer
                        znewwp=zwpointer+1; // place=place+1
                    else
                        znewwp=1; // else place=1
                    if (zrpointer!=znewwp) // if read pointer!=write pointer
                        ZIGrx[zwpointer++]=data[i]; // store received char
                    if (zwpointer==128) // if write pointer=length buffer
                        zwpointer=1; // write pointer = 1
            }
*/
}
void mrf24j40_transmit_callback (uns8 status, uns8 retries, uns8 channel_busy)
Callback is actioned when mrf24j40 has finished transmitting a packet, or failed to do so.
Callback indicating the mrf24j40 has finished the transmission sequence.
Parameters
status Set to 0 for success or 1 for failure
retries Set to the number of retries
channel_busy Set to 1 if failure was due to the channel being busy.
Definition at line 60 of file __zigbee.c.
Referenced by mrf24j40_handle_isr().
{
    Nop();
}
int ZIGavailable ()
Definition at line 106 of file __zigbee.c.
References zrpointer, and zwpointer.
{
    #ifdef INTZIG
    return(zwpointer!=zrpointer);
    #else
    return(-1);
    #endif
}
u8 ZIGgets (u8 * zigstr)
Definition at line 115 of file __zigbee.c.
References INTSTAT, INTSTAT_RXIF, mrf24j40_receive(), mrf24j40_short_addr_read(), ZIGdestadd, ZIGdestpan, ZIGsrcadd, and ZIGsrcpan.
{
    unsigned char length,i;
    unsigned char intstat;
    
    #ifndef INTZIG // Zigbee not interrupt managed
    // read INSTAT Register
    intstat = mrf24j40_short_addr_read(INTSTAT);
    // test if we received something
    if (test_bit(intstat, INTSTAT_RXIF))
    {
        length=mrf24j40_receive(zigstr,128);
        ZIGdestpan=(zigstr[4]<<8)+zigstr[3];
        ZIGsrcpan=(zigstr[8]<<8)+zigstr[7];
        ZIGsrcadd=(zigstr[10]<<8)+zigstr[9];
        ZIGdestadd=(zigstr[6]<<8)+zigstr[5];
        for (i=0;i<(length-15);i++)
            zigstr[i]=zigstr[i+11];
        zigstr[i]=0;
        return(length-15);
    }
    else return(0);
    #else
    Nop(); // todo interrupt managed
    #endif
}
void ZIGinterrupt (void)
Definition at line 53 of file __zigbee.c.
{
    Nop();
}
void ZIGputs (u16 short_address, u8 * zigstr, u8 length)
Definition at line 98 of file __zigbee.c.
References FTDATA, mrf24j40_transmit_to_short_address(), and pan_id.
{
    mrf24j40_transmit_to_short_address(FTDATA,
      pan_id, short_address, zigstr, length, 1);
}
Variable Documentation
u16 ZIGdestadd
Definition at line 36 of file __zigbee.c.
Referenced by ZIGgets().
u16 ZIGdestpan
Definition at line 34 of file __zigbee.c.
Referenced by ZIGgets().
unsigned char ZIGrx[128]
Definition at line 31 of file __zigbee.c.
Referenced by mrf24j40_receive_callback().
u16 ZIGsrcadd
Definition at line 37 of file __zigbee.c.
Referenced by ZIGgets().
u16 ZIGsrcpan
Definition at line 35 of file __zigbee.c.
Referenced by ZIGgets().
unsigned char zrpointer
Definition at line 32 of file __zigbee.c.
Referenced by ZIGavailable().
unsigned char zwpointer
Definition at line 32 of file __zigbee.c.
Referenced by ZIGavailable().