/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/IRremote.h File Reference
#include <typedef.h>
*
Data Structures
struct decode_results
struct irparams_t
Macros
#define DIGITALWRITE
#define DIGITALREAD
#define NEC 1
#define SONY 2
#define RC5 3
#define RC6 4
#define DISH 5
#define SHARP 6
#define PANASONIC 7
#define JVC 8
#define SANYO 9
#define MITSUBISHI 10
#define UNKNOWN -1
#define REPEAT 0xffffffff
#define USECPERTICK 50
#define RAWBUF 100
#define MARK_EXCESS 100
#define ERR 0
#define DECODED 1
#define NEC_HDR_MARK 9000
#define NEC_HDR_SPACE 4500
#define NEC_BIT_MARK 560
#define NEC_ONE_SPACE 1600
#define NEC_ZERO_SPACE 560
#define NEC_RPT_SPACE 2250
#define SONY_HDR_MARK 2400
#define SONY_HDR_SPACE 600
#define SONY_ONE_MARK 1200
#define SONY_ZERO_MARK 600
#define SONY_RPT_LENGTH 45000
#define SONY_DOUBLE_SPACE_USECS 500
#define SANYO_HDR_MARK 3500
#define SANYO_HDR_SPACE 950
#define SANYO_ONE_MARK 2400
#define SANYO_ZERO_MARK 700
#define SANYO_DOUBLE_SPACE_USECS 800
#define SANYO_RPT_LENGTH 45000
#define MITSUBISHI_HDR_SPACE 350
#define MITSUBISHI_ONE_MARK 1950
#define MITSUBISHI_ZERO_MARK 750
#define RC5_T1 889
#define RC5_RPT_LENGTH 46000
#define RC6_HDR_MARK 2666
#define RC6_HDR_SPACE 889
#define RC6_T1 444
#define RC6_RPT_LENGTH 46000
#define SHARP_BIT_MARK 245
#define SHARP_ONE_SPACE 1805
#define SHARP_ZERO_SPACE 795
#define SHARP_GAP 600000
#define SHARP_TOGGLE_MASK 0x3FF
#define SHARP_RPT_SPACE 3000
#define DISH_HDR_MARK 400
#define DISH_HDR_SPACE 6100
#define DISH_BIT_MARK 400
#define DISH_ONE_SPACE 1700
#define DISH_ZERO_SPACE 2800
#define DISH_RPT_SPACE 6200
#define DISH_TOP_BIT 0x8000
#define PANASONIC_HDR_MARK 3502
#define PANASONIC_HDR_SPACE 1750
#define PANASONIC_BIT_MARK 502
#define PANASONIC_ONE_SPACE 1244
#define PANASONIC_ZERO_SPACE 400
#define JVC_HDR_MARK 8000
#define JVC_HDR_SPACE 4000
#define JVC_BIT_MARK 600
#define JVC_ONE_SPACE 1600
#define JVC_ZERO_SPACE 550
#define JVC_RPT_LENGTH 60000
#define SHARP_BITS 15
#define DISH_BITS 16
#define STATE_IDLE 2
#define STATE_MARK 3
#define STATE_SPACE 4
#define STATE_STOP 5
#define MARK 0
#define SPACE 1
#define TOPBIT 0x80000000
#define NEC_BITS 32
#define SONY_BITS 12
#define SANYO_BITS 12
#define MITSUBISHI_BITS 16
#define MIN_RC5_SAMPLES 11
#define MIN_RC6_SAMPLES 1
#define PANASONIC_BITS 48
#define JVC_BITS 16
#define _GAP 5000
#define GAP_TICKS (_GAP/USECPERTICK)
#define TOLERANCE 25
#define LTOL (1.0 - TOLERANCE/100.)
#define UTOL (1.0 + TOLERANCE/100.)
#define TICKS_LOW(us) (u16) (((us)*LTOL/USECPERTICK))
#define TICKS_HIGH(us) (u16) (((us)*UTOL/USECPERTICK + 1))
Functions
u16 MATCH (u16 measured, u16 desired)
u16 MATCH_MARK (u16 measured_ticks, u16 desired_us)
u16 MATCH_SPACE (u16 measured_ticks, u16 desired_us)
void IRrecv_blink13 (u8 blinkflag)
u16 IRrecv_decode (decode_results *results)
void IRrecv_enableIRIn (u8 recvpin)
void IRrecv_resume ()
u16 IRrecv_getRClevel (decode_results *results, u16 *offset, u16 *used, u16 t1)
u32 IRrecv_decodeNEC (decode_results *results)
u32 IRrecv_decodeSony (decode_results *results)
u32 IRrecv_decodeSanyo (decode_results *results)
u32 IRrecv_decodeMitsubishi (decode_results *results)
u32 IRrecv_decodeRC5 (decode_results *results)
u32 IRrecv_decodeRC6 (decode_results *results)
u32 IRrecv_decodePanasonic (decode_results *results)
u32 IRrecv_decodeJVC (decode_results *results)
u32 IRrecv_decodeHash (decode_results *results)
u16 IRrecv_compare (u16 oldval, u16 newval)
void IRsend_enableIROut (u8 outpin)
void IRsend_mark (u16 usec)
void IRsend_space (u16 usec)
void IRsend_IRsend ()
void IRsend_sendNEC (u32 data, u16 nbits)
void IRsend_sendSony (u32 data, u16 nbits)
void IRsend_sendRaw (u16 buf[], u16 len, u16 hz)
void IRsend_sendRC5 (u32 data, u16 nbits)
void IRsend_sendRC6 (u32 data, u16 nbits)
void IRsend_sendDISH (u32 data, u16 nbits)
void IRsend_sendSharp (u32 data, u16 nbits)
void IRsend_sendPanasonic (u16 address, u32 data)
void IRsend_sendJVC (u32 data, u16 nbits, u16 repeat)
Variables
volatile irparams_t irparams
Macro Definition Documentation
#define _GAP 5000
Definition at line 171 of file IRremote.h.
#define DECODED 1
Definition at line 63 of file IRremote.h.
#define DIGITALREAD
Definition at line 23 of file IRremote.h.
#define DIGITALWRITE
Definition at line 19 of file IRremote.h.
#define DISH 5
Definition at line 45 of file IRremote.h.
#define DISH_BIT_MARK 400
Definition at line 128 of file IRremote.h.
#define DISH_BITS 16
Definition at line 148 of file IRremote.h.
#define DISH_HDR_MARK 400
Definition at line 126 of file IRremote.h.
#define DISH_HDR_SPACE 6100
Definition at line 127 of file IRremote.h.
#define DISH_ONE_SPACE 1700
Definition at line 129 of file IRremote.h.
#define DISH_RPT_SPACE 6200
Definition at line 131 of file IRremote.h.
#define DISH_TOP_BIT 0x8000
Definition at line 132 of file IRremote.h.
#define DISH_ZERO_SPACE 2800
Definition at line 130 of file IRremote.h.
#define ERR 0
Definition at line 62 of file IRremote.h.
#define GAP_TICKS (_GAP/USECPERTICK)
Definition at line 172 of file IRremote.h.
#define JVC 8
Definition at line 48 of file IRremote.h.
#define JVC_BIT_MARK 600
Definition at line 142 of file IRremote.h.
#define JVC_BITS 16
Definition at line 169 of file IRremote.h.
#define JVC_HDR_MARK 8000
Definition at line 140 of file IRremote.h.
#define JVC_HDR_SPACE 4000
Definition at line 141 of file IRremote.h.
#define JVC_ONE_SPACE 1600
Definition at line 143 of file IRremote.h.
#define JVC_RPT_LENGTH 60000
Definition at line 145 of file IRremote.h.
#define JVC_ZERO_SPACE 550
Definition at line 144 of file IRremote.h.
#define LTOL (1.0 - TOLERANCE/100.)
Definition at line 180 of file IRremote.h.
#define MARK 0
Definition at line 157 of file IRremote.h.
#define MARK_EXCESS 100
Definition at line 61 of file IRremote.h.
Referenced by MATCH_MARK(), and MATCH_SPACE().
#define MIN_RC5_SAMPLES 11
Definition at line 166 of file IRremote.h.
#define MIN_RC6_SAMPLES 1
Definition at line 167 of file IRremote.h.
#define MITSUBISHI 10
Definition at line 50 of file IRremote.h.
#define MITSUBISHI_BITS 16
Definition at line 165 of file IRremote.h.
#define MITSUBISHI_HDR_SPACE 350
Definition at line 104 of file IRremote.h.
#define MITSUBISHI_ONE_MARK 1950
Definition at line 105 of file IRremote.h.
#define MITSUBISHI_ZERO_MARK 750
Definition at line 106 of file IRremote.h.
#define NEC 1
Definition at line 41 of file IRremote.h.
#define NEC_BIT_MARK 560
Definition at line 80 of file IRremote.h.
#define NEC_BITS 32
Definition at line 162 of file IRremote.h.
#define NEC_HDR_MARK 9000
Definition at line 78 of file IRremote.h.
#define NEC_HDR_SPACE 4500
Definition at line 79 of file IRremote.h.
#define NEC_ONE_SPACE 1600
Definition at line 81 of file IRremote.h.
#define NEC_RPT_SPACE 2250
Definition at line 83 of file IRremote.h.
#define NEC_ZERO_SPACE 560
Definition at line 82 of file IRremote.h.
#define PANASONIC 7
Definition at line 47 of file IRremote.h.
#define PANASONIC_BIT_MARK 502
Definition at line 136 of file IRremote.h.
#define PANASONIC_BITS 48
Definition at line 168 of file IRremote.h.
#define PANASONIC_HDR_MARK 3502
Definition at line 134 of file IRremote.h.
#define PANASONIC_HDR_SPACE 1750
Definition at line 135 of file IRremote.h.
#define PANASONIC_ONE_SPACE 1244
Definition at line 137 of file IRremote.h.
#define PANASONIC_ZERO_SPACE 400
Definition at line 138 of file IRremote.h.
#define RAWBUF 100
Definition at line 57 of file IRremote.h.
#define RC5 3
Definition at line 43 of file IRremote.h.
#define RC5_RPT_LENGTH 46000
Definition at line 112 of file IRremote.h.
#define RC5_T1 889
Definition at line 111 of file IRremote.h.
#define RC6 4
Definition at line 44 of file IRremote.h.
#define RC6_HDR_MARK 2666
Definition at line 114 of file IRremote.h.
#define RC6_HDR_SPACE 889
Definition at line 115 of file IRremote.h.
#define RC6_RPT_LENGTH 46000
Definition at line 117 of file IRremote.h.
#define RC6_T1 444
Definition at line 116 of file IRremote.h.
#define REPEAT 0xffffffff
Definition at line 54 of file IRremote.h.
#define SANYO 9
Definition at line 49 of file IRremote.h.
#define SANYO_BITS 12
Definition at line 164 of file IRremote.h.
#define SANYO_DOUBLE_SPACE_USECS 800
Definition at line 97 of file IRremote.h.
#define SANYO_HDR_MARK 3500
Definition at line 93 of file IRremote.h.
#define SANYO_HDR_SPACE 950
Definition at line 94 of file IRremote.h.
#define SANYO_ONE_MARK 2400
Definition at line 95 of file IRremote.h.
#define SANYO_RPT_LENGTH 45000
Definition at line 98 of file IRremote.h.
#define SANYO_ZERO_MARK 700
Definition at line 96 of file IRremote.h.
#define SHARP 6
Definition at line 46 of file IRremote.h.
#define SHARP_BIT_MARK 245
Definition at line 119 of file IRremote.h.
#define SHARP_BITS 15
Definition at line 147 of file IRremote.h.
#define SHARP_GAP 600000
Definition at line 122 of file IRremote.h.
#define SHARP_ONE_SPACE 1805
Definition at line 120 of file IRremote.h.
#define SHARP_RPT_SPACE 3000
Definition at line 124 of file IRremote.h.
#define SHARP_TOGGLE_MASK 0x3FF
Definition at line 123 of file IRremote.h.
#define SHARP_ZERO_SPACE 795
Definition at line 121 of file IRremote.h.
#define SONY 2
Definition at line 42 of file IRremote.h.
#define SONY_BITS 12
Definition at line 163 of file IRremote.h.
#define SONY_DOUBLE_SPACE_USECS 500
Definition at line 90 of file IRremote.h.
#define SONY_HDR_MARK 2400
Definition at line 85 of file IRremote.h.
#define SONY_HDR_SPACE 600
Definition at line 86 of file IRremote.h.
#define SONY_ONE_MARK 1200
Definition at line 87 of file IRremote.h.
#define SONY_RPT_LENGTH 45000
Definition at line 89 of file IRremote.h.
#define SONY_ZERO_MARK 600
Definition at line 88 of file IRremote.h.
#define SPACE 1
Definition at line 158 of file IRremote.h.
#define STATE_IDLE 2
Definition at line 151 of file IRremote.h.
#define STATE_MARK 3
Definition at line 152 of file IRremote.h.
#define STATE_SPACE 4
Definition at line 153 of file IRremote.h.
#define STATE_STOP 5
Definition at line 154 of file IRremote.h.
#define TICKS_HIGH(us) (u16) (((us)*UTOL/USECPERTICK + 1))
Definition at line 183 of file IRremote.h.
Referenced by MATCH().
#define TICKS_LOW(us) (u16) (((us)*LTOL/USECPERTICK))
Definition at line 182 of file IRremote.h.
Referenced by MATCH().
#define TOLERANCE 25
Definition at line 174 of file IRremote.h.
#define TOPBIT 0x80000000
Definition at line 160 of file IRremote.h.
#define UNKNOWN -1
Definition at line 51 of file IRremote.h.
#define USECPERTICK 50
Definition at line 56 of file IRremote.h.
#define UTOL (1.0 + TOLERANCE/100.)
Definition at line 181 of file IRremote.h.
Function Documentation
void IRrecv_blink13 (u8 blinkflag)
u16 IRrecv_compare (u16 oldval, u16 newval)
u16 IRrecv_decode (decode_results * results)
u32 IRrecv_decodeHash (decode_results * results)
u32 IRrecv_decodeJVC (decode_results * results)
u32 IRrecv_decodeMitsubishi (decode_results * results)
u32 IRrecv_decodeNEC (decode_results * results)
u32 IRrecv_decodePanasonic (decode_results * results)
u32 IRrecv_decodeRC5 (decode_results * results)
u32 IRrecv_decodeRC6 (decode_results * results)
u32 IRrecv_decodeSanyo (decode_results * results)
u32 IRrecv_decodeSony (decode_results * results)
void IRrecv_enableIRIn (u8 recvpin)
u16 IRrecv_getRClevel (decode_results * results, u16 * offset, u16 * used, u16 t1)
void IRrecv_resume ()
void IRsend_enableIROut (u8 outpin)
void IRsend_IRsend ()
void IRsend_mark (u16 usec)
Definition at line 289 of file IRremote.c.
References _1us_, irparams_t::outpin, and PWM_setPercentDutyCycle().
{
    u16 i;
    // Sends an IR mark for the specified number of microseconds.
    // The mark output is modulated at the PWM frequency.
    // duty cycle = 50% = Enable PWM output
    PWM_setPercentDutyCycle(irparams.outpin, 50);
    
    // loopcounter i = time - correction factor
    // Without the NOPs the loop has an execution time of ~13 microseconds
    i = time-13;
    
    // while () {} needs much less time than for (;;) {}
    // for loop without NOPs : ~ 1,3 ms (889 iterations on 18f26j50)
    // while loop without NOPs: ~ 712 s (889 Iterations on 18f26j50)
    while (i) {
      _1us_
      i--;
    }
    
/*
    for (i=0; i<time; i++)
    {
; _1us_
    }
*/
}
void IRsend_sendDISH (u32 data, u16 nbits)
void IRsend_sendJVC (u32 data, u16 nbits, u16 repeat)
void IRsend_sendNEC (u32 data, u16 nbits)
void IRsend_sendPanasonic (u16 address, u32 data)
void IRsend_sendRaw (u16 buf[], u16 len, u16 hz)
void IRsend_sendRC5 (u32 data, u16 nbits)
void IRsend_sendRC6 (u32 data, u16 nbits)
void IRsend_sendSharp (u32 data, u16 nbits)
void IRsend_sendSony (u32 data, u16 nbits)
void IRsend_space (u16 usec)
Definition at line 319 of file IRremote.c.
References _1us_, irparams_t::outpin, and PWM_setPercentDutyCycle().
{
    u16 i;
    // Sends an IR space for the specified number of microseconds.
    // A space is no output, so the PWM output is disabled.
    // duty cycle = 0% = Disable PWM output
    PWM_setPercentDutyCycle(irparams.outpin, 0);
    // loopcounter i = time - correction factor
    // without the NOPs the loop has an execution time of ~70 microseconds
  
    i = time - 70; // correction factor: 13 microseconds
    while (i) {
      _1us_
      i--;
    }
/*
    for (i=0; i<time; i++)
    {
        _1us_
    }
*/
}
u16 MATCH (u16 measured, u16 desired)
Definition at line 186 of file IRremote.h.
References TICKS_HIGH, and TICKS_LOW.
Referenced by MATCH_MARK(), and MATCH_SPACE().
{return measured >= TICKS_LOW(desired) && measured <= TICKS_HIGH(desired);}
u16 MATCH_MARK (u16 measured_ticks, u16 desired_us)
Definition at line 187 of file IRremote.h.
References MARK_EXCESS, and MATCH().
{return MATCH(measured_ticks, (desired_us + MARK_EXCESS));}
u16 MATCH_SPACE (u16 measured_ticks, u16 desired_us)
Definition at line 188 of file IRremote.h.
References MARK_EXCESS, and MATCH().
{return MATCH(measured_ticks, (desired_us - MARK_EXCESS));}
Variable Documentation
volatile irparams_t irparams
Definition at line 43 of file IRremote.c.