/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/MCP23017.c File Reference
#include <pinguinoi2c1.c>
*
Data Structures
union tagMCP23017U
struct tagMCP23017
Macros
#define _MCP23017_H_
#define MCP23017_ADDRESS 0x20
#define MCP23017_IODIRA 0x00
#define MCP23017_IPOLA 0x02
#define MCP23017_GPINTENA 0x04
#define MCP23017_DEFVALA 0x06
#define MCP23017_INTCONA 0x08
#define MCP23017_IOCONA 0x0A
#define MCP23017_GPPUA 0x0C
#define MCP23017_INTFA 0x0E
#define MCP23017_INTCAPA 0x10
#define MCP23017_GPIOA 0x12
#define MCP23017_OLATA 0x14
#define MCP23017_IODIRB 0x01
#define MCP23017_IPOLB 0x03
#define MCP23017_GPINTENB 0x05
#define MCP23017_DEFVALB 0x07
#define MCP23017_INTCONB 0x09
#define MCP23017_IOCONB 0x0B
#define MCP23017_GPPUB 0x0D
#define MCP23017_INTFB 0x0F
#define MCP23017_INTCAPB 0x11
#define MCP23017_GPIOB 0x13
#define MCP23017_OLATB 0x15
#define MCP23017_B_NotUse 1
#define MCP23017_B_INTPOL 2
#define MCP23017_B_ODR 4
#define MCP23017_B_HAEN 8
#define MCP23017_B_DISSLW 16
#define MCP23017_B_SEQOP 32
#define MCP23017_B_MIRROR 64
#define MCP23017_B_BANK 128
Typedefs
typedef union tagMCP23017U MCP23017U
typedef struct tagMCP23017 MCP23017
Functions
BOOL MCP23017_Fault (u16 Valo)
BOOL MCP23017_write_B (MCP23017 *Mcp, u8 Addr, u8 Val)
BOOL MCP23017_write_W (MCP23017 *Mcp, u8 Addr, u16 Val)
BOOL MCP23017_write_A (MCP23017 *Mcp, u8 Addr, u16 Len, char *Val)
BOOL MCP23017_read_B (MCP23017 *Mcp, u8 Addr, u8 *Val)
BOOL MCP23017_read_W (MCP23017 *Mcp, u8 Addr, u16 *Val)
BOOL MCP23017_read_A (MCP23017 *Mcp, u8 Addr, u8 Len, char *Val)
BOOL MCP23017_init (MCP23017 *Mcp, u8 I2CAddr)
BOOL MCP23017_readGPIO_A (u8 *Val, MCP23017 *Mcp)
BOOL MCP23017_readGPIO_B (u8 *Val, MCP23017 *Mcp)
BOOL MCP23017_readGPIO_AB (u16 *Val, MCP23017 *Mcp)
BOOL MCP23017_writeGPIO_A (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeGPIO_B (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeGPIO_AB (u16 Val, MCP23017 *Mcp)
BOOL MCP23017_writeIODIR_A (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeIODIR_B (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeIODIR_AB (u16 Val, MCP23017 *Mcp)
BOOL MCP23017_writeGPPU_A (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeGPPU_B (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeGPPU_AB (u16 Val, MCP23017 *Mcp)
BOOL MCP23017_writeIPOL_A (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeIPOL_B (u8 Val, MCP23017 *Mcp)
BOOL MCP23017_writeIPOL_AB (u16 Val, MCP23017 *Mcp)
u8 MCP23017_digitalRead (u8 Pin, MCP23017 *Mcp)
BOOL MCP23017_pinMode (u8 Pin, u8 OutIn, MCP23017 *Mcp)
BOOL MCP23017_pullUp (u8 Pin, u8 SPull, MCP23017 *Mcp)
BOOL MCP23017_inputPol (u8 Pin, u8 SInPol, MCP23017 *Mcp)
BOOL MCP23017_digitalWrite (u8 Pin, u8 SOut, MCP23017 *Mcp)
Variables
u16 MCP23017_Fault_V
Macro Definition Documentation
#define _MCP23017_H_
Definition at line 19 of file MCP23017.c.
#define MCP23017_ADDRESS 0x20
Definition at line 22 of file MCP23017.c.
Referenced by MCP23017_read_A(), MCP23017_read_B(), MCP23017_read_W(), MCP23017_write_A(), MCP23017_write_B(), and MCP23017_write_W().
#define MCP23017_B_BANK 128
Definition at line 82 of file MCP23017.c.
#define MCP23017_B_DISSLW 16
Definition at line 70 of file MCP23017.c.
#define MCP23017_B_HAEN 8
Definition at line 66 of file MCP23017.c.
#define MCP23017_B_INTPOL 2
Definition at line 57 of file MCP23017.c.
#define MCP23017_B_MIRROR 64
Definition at line 78 of file MCP23017.c.
#define MCP23017_B_NotUse 1
Definition at line 53 of file MCP23017.c.
#define MCP23017_B_ODR 4
Definition at line 61 of file MCP23017.c.
#define MCP23017_B_SEQOP 32
Definition at line 74 of file MCP23017.c.
#define MCP23017_DEFVALA 0x06
Definition at line 27 of file MCP23017.c.
#define MCP23017_DEFVALB 0x07
Definition at line 40 of file MCP23017.c.
#define MCP23017_GPINTENA 0x04
Definition at line 26 of file MCP23017.c.
#define MCP23017_GPINTENB 0x05
Definition at line 39 of file MCP23017.c.
#define MCP23017_GPIOA 0x12
Definition at line 33 of file MCP23017.c.
Referenced by MCP23017_digitalRead(), MCP23017_digitalWrite(), MCP23017_readGPIO_A(), MCP23017_readGPIO_AB(), MCP23017_writeGPIO_A(), and MCP23017_writeGPIO_AB().
#define MCP23017_GPIOB 0x13
Definition at line 46 of file MCP23017.c.
Referenced by MCP23017_digitalRead(), MCP23017_digitalWrite(), MCP23017_readGPIO_B(), and MCP23017_writeGPIO_B().
#define MCP23017_GPPUA 0x0C
Definition at line 30 of file MCP23017.c.
Referenced by MCP23017_pullUp(), MCP23017_writeGPPU_A(), and MCP23017_writeGPPU_AB().
#define MCP23017_GPPUB 0x0D
Definition at line 43 of file MCP23017.c.
Referenced by MCP23017_pullUp(), and MCP23017_writeGPPU_B().
#define MCP23017_INTCAPA 0x10
Definition at line 32 of file MCP23017.c.
#define MCP23017_INTCAPB 0x11
Definition at line 45 of file MCP23017.c.
#define MCP23017_INTCONA 0x08
Definition at line 28 of file MCP23017.c.
#define MCP23017_INTCONB 0x09
Definition at line 41 of file MCP23017.c.
#define MCP23017_INTFA 0x0E
Definition at line 31 of file MCP23017.c.
#define MCP23017_INTFB 0x0F
Definition at line 44 of file MCP23017.c.
#define MCP23017_IOCONA 0x0A
Definition at line 29 of file MCP23017.c.
#define MCP23017_IOCONB 0x0B
Definition at line 42 of file MCP23017.c.
#define MCP23017_IODIRA 0x00
Definition at line 24 of file MCP23017.c.
Referenced by MCP23017_init(), MCP23017_pinMode(), MCP23017_writeIODIR_A(), and MCP23017_writeIODIR_AB().
#define MCP23017_IODIRB 0x01
Definition at line 37 of file MCP23017.c.
Referenced by MCP23017_pinMode(), and MCP23017_writeIODIR_B().
#define MCP23017_IPOLA 0x02
Definition at line 25 of file MCP23017.c.
Referenced by MCP23017_inputPol(), MCP23017_writeIPOL_A(), and MCP23017_writeIPOL_AB().
#define MCP23017_IPOLB 0x03
Definition at line 38 of file MCP23017.c.
Referenced by MCP23017_inputPol(), and MCP23017_writeIPOL_B().
#define MCP23017_OLATA 0x14
Definition at line 34 of file MCP23017.c.
#define MCP23017_OLATB 0x15
Definition at line 47 of file MCP23017.c.
Typedef Documentation
typedef struct tagMCP23017 MCP23017
typedef union tagMCP23017U MCP23017U
Function Documentation
u8 MCP23017_digitalRead (u8 Pin, MCP23017 * Mcp)
Definition at line 608 of file MCP23017.c.
References tagMCP23017U::B, FALSE, tagMCP23017::GINP, MCP23017_GPIOA, MCP23017_GPIOB, and MCP23017_read_B().
{
 Pin--;
 if (Pin > 15)
  return(0xFF);
 if (Pin < 8)
  {
   if (MCP23017_read_B(Mcp,MCP23017_GPIOA,&(Mcp->
      GINP.B[0])) == FALSE)
    return(0xFF);
   return ((Mcp->GINP.B[0] >> Pin) & 0x1);
  }
 else
  {
   Pin -= 8;
   if (MCP23017_read_B(Mcp,MCP23017_GPIOB,&(Mcp->
      GINP.B[1])) == FALSE)
    return(0xFF);
   return ((Mcp->GINP.B[1] >> Pin) & 0x1);
  }
}
BOOL MCP23017_digitalWrite (u8 Pin, u8 SOut, MCP23017 * Mcp)
Definition at line 767 of file MCP23017.c.
References tagMCP23017U::B, FALSE, tagMCP23017::GPIO, HIGH, MCP23017_GPIOA, MCP23017_GPIOB, MCP23017_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (SOut == HIGH)
    Mcp->GPIO.B[0] |= 1 << Pin;
   else
    Mcp->GPIO.B[0] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_GPIOA,Mcp->
      GPIO.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (SOut == HIGH)
    Mcp->GPIO.B[1] |= 1 << Pin;
   else
    Mcp->GPIO.B[1] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_GPIOB,Mcp->
      GPIO.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
BOOL MCP23017_Fault (u16 Valo)
Definition at line 108 of file MCP23017.c.
References FALSE, I2C1_stop(), and MCP23017_Fault_V.
Referenced by MCP23017_read_A(), MCP23017_read_B(), MCP23017_read_W(), MCP23017_write_A(), MCP23017_write_B(), and MCP23017_write_W().
{
 MCP23017_Fault_V = Valo;
 I2C1_stop();
 return(FALSE);
}
BOOL MCP23017_init (MCP23017 * Mcp, u8 I2CAddr)
Definition at line 315 of file MCP23017.c.
References FALSE, tagMCP23017::GPIO, tagMCP23017::GPPU, I2C1_init(), tagMCP23017::I2CAddr, tagMCP23017::IODIR, tagMCP23017::IPOL, MCP23017_IODIRA, MCP23017_write_W(), TRUE, and tagMCP23017U::W.
{
 Mcp->I2CAddr = I2CAddr;
 Mcp->IODIR.W = 0xFFFF;
 Mcp->GPIO.W = 0;
 Mcp->GPPU.W = 0;
 Mcp->IPOL.W = 0;
 I2C1_init();
 if(MCP23017_write_W(Mcp,MCP23017_IODIRA,0xFFFF) ==
      FALSE)
  return(FALSE);
 return(TRUE);
}
BOOL MCP23017_inputPol (u8 Pin, u8 SInPol, MCP23017 * Mcp)
Definition at line 727 of file MCP23017.c.
References tagMCP23017U::B, FALSE, HIGH, tagMCP23017::IPOL, MCP23017_IPOLA, MCP23017_IPOLB, MCP23017_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (SInPol == HIGH)
    Mcp->IPOL.B[0] |= 1 << Pin;
   else
    Mcp->IPOL.B[0] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_IPOLA,Mcp->
      IPOL.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (SInPol == HIGH)
    Mcp->IPOL.B[1] |= 1 << Pin;
   else
    Mcp->IPOL.B[1] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_IPOLB,Mcp->
      IPOL.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
BOOL MCP23017_pinMode (u8 Pin, u8 OutIn, MCP23017 * Mcp)
Definition at line 647 of file MCP23017.c.
References tagMCP23017U::B, FALSE, INPUT, tagMCP23017::IODIR, MCP23017_IODIRA, MCP23017_IODIRB, MCP23017_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (OutIn == INPUT)
    Mcp->IODIR.B[0] |= 1 << Pin;
   else
    Mcp->IODIR.B[0] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_IODIRA,Mcp->
      IODIR.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (OutIn == INPUT)
    Mcp->IODIR.B[1] |= 1 << Pin;
   else
    Mcp->IODIR.B[1] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_IODIRB,Mcp->
      IODIR.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
BOOL MCP23017_pullUp (u8 Pin, u8 SPull, MCP23017 * Mcp)
Definition at line 687 of file MCP23017.c.
References tagMCP23017U::B, FALSE, tagMCP23017::GPPU, HIGH, MCP23017_GPPUA, MCP23017_GPPUB, MCP23017_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (SPull == HIGH)
    Mcp->GPPU.B[0] |= 1 << Pin;
   else
    Mcp->GPPU.B[0] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_GPPUA,Mcp->
      GPPU.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (SPull == HIGH)
    Mcp->GPPU.B[1] |= 1 << Pin;
   else
    Mcp->GPPU.B[1] &= ~(1 << Pin);
   if (MCP23017_write_B(Mcp,MCP23017_GPPUB,Mcp->
      GPPU.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
BOOL MCP23017_read_A (MCP23017 * Mcp, u8 Addr, u8 Len, char * Val)
Definition at line 274 of file MCP23017.c.
References FALSE, I2C1_readchar(), I2C1_readcharAck(), I2C1_restart(), I2C1_start(), I2C1_stop(), I2C1_writechar(), tagMCP23017::I2CAddr, MCP23017_ADDRESS, MCP23017_Fault(), NULL, and TRUE.
{
 u16 Ctn;
 if ((Len == 0) || (Val == NULL))
  return(FALSE);
 // read the current IODIR
 I2C1_start();
 if (I2C1_writechar(((MCP23017_ADDRESS | (Mcp->
      I2CAddr&7))<<1)&~1) == FALSE) //Write Into Device
  return(MCP23017_Fault(1));
 if (I2C1_writechar(Addr) == FALSE)
  return(MCP23017_Fault(2));
 I2C1_restart();
 I2C1_writechar(((MCP23017_ADDRESS | (Mcp->I2CAddr&7))<<1)|1); //
      Read From Device
 for (Ctn = 0 ; Ctn < Len ; Ctn++)
  {
   if (Ctn == Len-1)
    Val[Ctn] = I2C1_readchar();
   else
    Val[Ctn] = I2C1_readcharAck();
  }
 I2C1_stop();
 return(TRUE);
}
BOOL MCP23017_read_B (MCP23017 * Mcp, u8 Addr, u8 * Val)
Definition at line 210 of file MCP23017.c.
References FALSE, I2C1_readchar(), I2C1_restart(), I2C1_start(), I2C1_stop(), I2C1_writechar(), tagMCP23017::I2CAddr, MCP23017_ADDRESS, MCP23017_Fault(), NULL, and TRUE.
Referenced by MCP23017_digitalRead(), MCP23017_readGPIO_A(), and MCP23017_readGPIO_B().
{
 if (Val == NULL)
  return(FALSE);
 I2C1_start();
 if (I2C1_writechar(((MCP23017_ADDRESS | (Mcp->
      I2CAddr&7))<<1)&~1) == FALSE) //Write Into Device
  return(MCP23017_Fault(1));
 if (I2C1_writechar(Addr) == FALSE)
  return(MCP23017_Fault(2));
 I2C1_restart();
 I2C1_writechar(((MCP23017_ADDRESS | (Mcp->I2CAddr&7))<<1)|1); //
      Read From Device
 *Val = I2C1_readchar();
 I2C1_stop();
 return(TRUE);
}
BOOL MCP23017_read_W (MCP23017 * Mcp, u8 Addr, u16 * Val)
Definition at line 238 of file MCP23017.c.
References FALSE, I2C1_readchar(), I2C1_readcharAck(), I2C1_restart(), I2C1_start(), I2C1_stop(), I2C1_writechar(), tagMCP23017::I2CAddr, MCP23017_ADDRESS, MCP23017_Fault(), NULL, and TRUE.
Referenced by MCP23017_readGPIO_AB().
{
 u16 TVal;
 u8 BVal;
 if (Val == NULL)
  return(FALSE);
 I2C1_start();
 if (I2C1_writechar(((MCP23017_ADDRESS | (Mcp->
      I2CAddr&7))<<1)&~1) == FALSE) //Write Into Device
  return(MCP23017_Fault(1));
 if (I2C1_writechar(Addr) == FALSE)
  return(MCP23017_Fault(2));
 I2C1_restart();
 I2C1_writechar(((MCP23017_ADDRESS | (Mcp->I2CAddr&7))<<1)|1); //
      Read From Device
 BVal = I2C1_readcharAck();
 TVal = I2C1_readchar();
 I2C1_stop();
 TVal <<= 8;
 TVal |= BVal;
 *Val = TVal;
 return(TRUE);
}
BOOL MCP23017_readGPIO_A (u8 * Val, MCP23017 * Mcp)
Definition at line 342 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::GINP, MCP23017_GPIOA, and MCP23017_read_B().
{
 BOOL Risu;
 Risu = MCP23017_read_B(Mcp,MCP23017_GPIOA,Val);
 Mcp->GINP.B[0] = Val;
 return (Risu);
}
BOOL MCP23017_readGPIO_AB (u16 * Val, MCP23017 * Mcp)
Definition at line 378 of file MCP23017.c.
References tagMCP23017::GINP, MCP23017_GPIOA, MCP23017_read_W(), and tagMCP23017U::W.
{
 BOOL Risu;
 Risu = MCP23017_read_W(Mcp,MCP23017_GPIOA,Val);
 Mcp->GINP.W = Val;
 return (Risu);
}
BOOL MCP23017_readGPIO_B (u8 * Val, MCP23017 * Mcp)
Definition at line 360 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::GINP, MCP23017_GPIOB, and MCP23017_read_B().
{
 BOOL Risu;
 Risu = MCP23017_read_B(Mcp,MCP23017_GPIOB,Val);
 Mcp->GINP.B[1] = Val;
 return (Risu);
}
BOOL MCP23017_write_A (MCP23017 * Mcp, u8 Addr, u16 Len, char * Val)
Definition at line 180 of file MCP23017.c.
References FALSE, I2C1_start(), I2C1_stop(), I2C1_writechar(), tagMCP23017::I2CAddr, MCP23017_ADDRESS, MCP23017_Fault(), NULL, and TRUE.
{
 u16 Ctn;
 if ((Len == 0) || (Val == NULL))
  return(FALSE);
 I2C1_start();
 if (I2C1_writechar(((MCP23017_ADDRESS | (Mcp->
      I2CAddr&7))<<1)&~1) == FALSE) //Write Into Device
  return(MCP23017_Fault(1));
 if (I2C1_writechar(Addr) == FALSE)
  return(MCP23017_Fault(2));
 for (Ctn = 0 ; Ctn < Len ; Ctn++)
  if (I2C1_writechar((u8) Val[Ctn]) == FALSE)
   return(MCP23017_Fault(3));
 I2C1_stop();
 return(TRUE);
}
BOOL MCP23017_write_B (MCP23017 * Mcp, u8 Addr, u8 Val)
Definition at line 127 of file MCP23017.c.
References FALSE, I2C1_start(), I2C1_stop(), I2C1_writechar(), tagMCP23017::I2CAddr, MCP23017_ADDRESS, MCP23017_Fault(), and TRUE.
Referenced by MCP23017_digitalWrite(), MCP23017_inputPol(), MCP23017_pinMode(), MCP23017_pullUp(), MCP23017_writeGPIO_A(), MCP23017_writeGPIO_B(), MCP23017_writeGPPU_A(), MCP23017_writeGPPU_B(), MCP23017_writeIODIR_A(), MCP23017_writeIODIR_B(), MCP23017_writeIPOL_A(), and MCP23017_writeIPOL_B().
{
 I2C1_start();
 if (I2C1_writechar(((MCP23017_ADDRESS | (Mcp->
      I2CAddr&7))<<1)&~1) == FALSE) //Write Into Device
  return(MCP23017_Fault(1));
 if (I2C1_writechar(Addr) == FALSE)
  return(MCP23017_Fault(2));
 if (I2C1_writechar(Val) == FALSE)
  return(MCP23017_Fault(3));
 I2C1_stop();
 return(TRUE);
}
BOOL MCP23017_write_W (MCP23017 * Mcp, u8 Addr, u16 Val)
Definition at line 152 of file MCP23017.c.
References FALSE, I2C1_start(), I2C1_stop(), I2C1_writechar(), tagMCP23017::I2CAddr, MCP23017_ADDRESS, MCP23017_Fault(), and TRUE.
Referenced by MCP23017_init(), MCP23017_writeGPIO_AB(), MCP23017_writeGPPU_AB(), MCP23017_writeIODIR_AB(), and MCP23017_writeIPOL_AB().
{
 I2C1_start();
 if (I2C1_writechar(((MCP23017_ADDRESS | (Mcp->
      I2CAddr&7))<<1)&~1) == FALSE) //Write Into Device
  return(MCP23017_Fault(1));
 if (I2C1_writechar(Addr) == FALSE)
  return(MCP23017_Fault(2));
 if (I2C1_writechar(Val & 0xFF) == FALSE)
  return(MCP23017_Fault(3));
 if (I2C1_writechar(Val >> 8) == FALSE)
  return(MCP23017_Fault(4));
 I2C1_stop();
 return(TRUE);
}
BOOL MCP23017_writeGPIO_A (u8 Val, MCP23017 * Mcp)
Definition at line 400 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::GPIO, MCP23017_GPIOA, and MCP23017_write_B().
{
 Mcp->GPIO.B[0] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_GPIOA,Val));
}
BOOL MCP23017_writeGPIO_AB (u16 Val, MCP23017 * Mcp)
Definition at line 432 of file MCP23017.c.
References tagMCP23017::GPIO, MCP23017_GPIOA, MCP23017_write_W(), and tagMCP23017U::W.
{
 Mcp->GPIO.W = Val;
 return (MCP23017_write_W(Mcp,MCP23017_GPIOA,Val));
}
BOOL MCP23017_writeGPIO_B (u8 Val, MCP23017 * Mcp)
Definition at line 416 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::GPIO, MCP23017_GPIOB, and MCP23017_write_B().
{
 Mcp->GPIO.B[1] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_GPIOB,Val));
}
BOOL MCP23017_writeGPPU_A (u8 Val, MCP23017 * Mcp)
Definition at line 504 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::GPPU, MCP23017_GPPUA, and MCP23017_write_B().
{
 Mcp->GPPU.B[0] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_GPPUA,Val));
}
BOOL MCP23017_writeGPPU_AB (u16 Val, MCP23017 * Mcp)
Definition at line 536 of file MCP23017.c.
References tagMCP23017::GPPU, MCP23017_GPPUA, MCP23017_write_W(), and tagMCP23017U::W.
{
 Mcp->GPPU.W = Val;
 return (MCP23017_write_W(Mcp,MCP23017_GPPUA,Val));
}
BOOL MCP23017_writeGPPU_B (u8 Val, MCP23017 * Mcp)
Definition at line 520 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::GPPU, MCP23017_GPPUB, and MCP23017_write_B().
{
 Mcp->GPPU.B[1] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_GPPUB,Val));
}
BOOL MCP23017_writeIODIR_A (u8 Val, MCP23017 * Mcp)
Definition at line 452 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::IODIR, MCP23017_IODIRA, and MCP23017_write_B().
{
 Mcp->IODIR.B[0] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_IODIRA,Val));
}
BOOL MCP23017_writeIODIR_AB (u16 Val, MCP23017 * Mcp)
Definition at line 484 of file MCP23017.c.
References tagMCP23017::IODIR, MCP23017_IODIRA, MCP23017_write_W(), and tagMCP23017U::W.
{
 Mcp->IODIR.W = Val;
 return (MCP23017_write_W(Mcp,MCP23017_IODIRA,Val));
}
BOOL MCP23017_writeIODIR_B (u8 Val, MCP23017 * Mcp)
Definition at line 468 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::IODIR, MCP23017_IODIRB, and MCP23017_write_B().
{
 Mcp->IODIR.B[1] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_IODIRB,Val));
}
BOOL MCP23017_writeIPOL_A (u8 Val, MCP23017 * Mcp)
Definition at line 555 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::IPOL, MCP23017_IPOLA, and MCP23017_write_B().
{
 Mcp->IPOL.B[0] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_IPOLA,Val));
}
BOOL MCP23017_writeIPOL_AB (u16 Val, MCP23017 * Mcp)
Definition at line 587 of file MCP23017.c.
References tagMCP23017::IPOL, MCP23017_IPOLA, MCP23017_write_W(), and tagMCP23017U::W.
{
 Mcp->IPOL.W = Val;
 return (MCP23017_write_W(Mcp,MCP23017_IPOLA,Val));
}
BOOL MCP23017_writeIPOL_B (u8 Val, MCP23017 * Mcp)
Definition at line 571 of file MCP23017.c.
References tagMCP23017U::B, tagMCP23017::IPOL, MCP23017_IPOLB, and MCP23017_write_B().
{
 Mcp->IPOL.B[1] = Val;
 return (MCP23017_write_B(Mcp,MCP23017_IPOLB,Val));
}
Variable Documentation
u16 MCP23017_Fault_V
Definition at line 105 of file MCP23017.c.
Referenced by MCP23017_Fault().