/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/MCP23S17.c File Reference
#include <digitalw.c>
*
#include <spi.c>
*
#include <SpiLoc.c>
*
Data Structures
union tagMCP23S17U
struct tagMCP23S17
Macros
#define _MCP23S17_H_
#define MCP23S17_ADDRESS 0x20
#define MCP23S17_IODIRA 0x00
#define MCP23S17_IPOLA 0x02
#define MCP23S17_GPINTENA 0x04
#define MCP23S17_DEFVALA 0x06
#define MCP23S17_INTCONA 0x08
#define MCP23S17_IOCONA 0x0A
#define MCP23S17_GPPUA 0x0C
#define MCP23S17_INTFA 0x0E
#define MCP23S17_INTCAPA 0x10
#define MCP23S17_GPIOA 0x12
#define MCP23S17_OLATA 0x14
#define MCP23S17_IODIRB 0x01
#define MCP23S17_IPOLB 0x03
#define MCP23S17_GPINTENB 0x05
#define MCP23S17_DEFVALB 0x07
#define MCP23S17_INTCONB 0x09
#define MCP23S17_IOCONB 0x0B
#define MCP23S17_GPPUB 0x0D
#define MCP23S17_INTFB 0x0F
#define MCP23S17_INTCAPB 0x11
#define MCP23S17_GPIOB 0x13
#define MCP23S17_OLATB 0x15
#define MCP23S17_B_NotUse 1
#define MCP23S17_B_INTPOL 2
#define MCP23S17_B_ODR 4
#define MCP23S17_B_HAEN 8
#define MCP23S17_B_DISSLW 16
#define MCP23S17_B_SEQOP 32
#define MCP23S17_B_MIRROR 64
#define MCP23S17_B_BANK 128
Typedefs
typedef union tagMCP23S17U MCP23S17U
typedef struct tagMCP23S17 MCP23S17
Functions
BOOL MCP23S17_write_B (MCP23S17 *Mcp, u8 Addr, u8 Val)
BOOL MCP23S17_write_W (MCP23S17 *Mcp, u8 Addr, u16 Val)
BOOL MCP23S17_write_A (MCP23S17 *Mcp, u8 Addr, u16 Len, char *Val)
BOOL MCP23S17_read_B (MCP23S17 *Mcp, u8 Addr, u8 *Val)
BOOL MCP23S17_read_W (MCP23S17 *Mcp, u8 Addr, u16 *Val)
void MCP23S17_read_A (MCP23S17 *Mcp, u8 Addr, u8 Len, char *Val)
BOOL MCP23S17_init (MCP23S17 *Mcp, u8 SPIAddr, u8 CSPin, BOOL UseIntAdd, u8 SPIChannel, u8 LoSCK, u8 LoSDO, u8 LoSDI)
BOOL MCP23S17_readGPIO_A (u8 *Val, MCP23S17 *Mcp)
BOOL MCP23S17_readGPIO_B (u8 *Val, MCP23S17 *Mcp)
BOOL MCP23S17_readGPIO_AB (u16 *Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeGPIO_A (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeGPIO_B (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeGPIO_AB (u16 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeIODIR_A (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeIODIR_B (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeIODIR_AB (u16 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeGPPU_A (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeGPPU_B (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeGPPU_AB (u16 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeIPOL_A (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeIPOL_B (u8 Val, MCP23S17 *Mcp)
BOOL MCP23S17_writeIPOL_AB (u16 Val, MCP23S17 *Mcp)
u8 MCP23S17_digitalRead (u8 Pin, MCP23S17 *Mcp)
BOOL MCP23S17_pinMode (u8 Pin, u8 OutIn, MCP23S17 *Mcp)
BOOL MCP23S17_pullUp (u8 Pin, u8 SPull, MCP23S17 *Mcp)
BOOL MCP23S17_inputPol (u8 Pin, u8 SInPol, MCP23S17 *Mcp)
BOOL MCP23S17_digitalWrite (u8 Pin, u8 SOut, MCP23S17 *Mcp)
Macro Definition Documentation
#define _MCP23S17_H_
Definition at line 18 of file MCP23S17.c.
#define MCP23S17_ADDRESS 0x20
Definition at line 25 of file MCP23S17.c.
Referenced by MCP23S17_read_A(), MCP23S17_read_B(), MCP23S17_read_W(), MCP23S17_write_A(), MCP23S17_write_B(), and MCP23S17_write_W().
#define MCP23S17_B_BANK 128
Definition at line 84 of file MCP23S17.c.
#define MCP23S17_B_DISSLW 16
Definition at line 72 of file MCP23S17.c.
#define MCP23S17_B_HAEN 8
Definition at line 68 of file MCP23S17.c.
Referenced by MCP23S17_init().
#define MCP23S17_B_INTPOL 2
Definition at line 60 of file MCP23S17.c.
#define MCP23S17_B_MIRROR 64
Definition at line 80 of file MCP23S17.c.
#define MCP23S17_B_NotUse 1
Definition at line 56 of file MCP23S17.c.
#define MCP23S17_B_ODR 4
Definition at line 64 of file MCP23S17.c.
#define MCP23S17_B_SEQOP 32
Definition at line 76 of file MCP23S17.c.
#define MCP23S17_DEFVALA 0x06
Definition at line 30 of file MCP23S17.c.
#define MCP23S17_DEFVALB 0x07
Definition at line 43 of file MCP23S17.c.
#define MCP23S17_GPINTENA 0x04
Definition at line 29 of file MCP23S17.c.
#define MCP23S17_GPINTENB 0x05
Definition at line 42 of file MCP23S17.c.
#define MCP23S17_GPIOA 0x12
Definition at line 36 of file MCP23S17.c.
Referenced by MCP23S17_digitalRead(), MCP23S17_digitalWrite(), MCP23S17_readGPIO_A(), MCP23S17_readGPIO_AB(), MCP23S17_writeGPIO_A(), and MCP23S17_writeGPIO_AB().
#define MCP23S17_GPIOB 0x13
Definition at line 49 of file MCP23S17.c.
Referenced by MCP23S17_digitalRead(), MCP23S17_digitalWrite(), MCP23S17_readGPIO_B(), and MCP23S17_writeGPIO_B().
#define MCP23S17_GPPUA 0x0C
Definition at line 33 of file MCP23S17.c.
Referenced by MCP23S17_pullUp(), MCP23S17_writeGPPU_A(), and MCP23S17_writeGPPU_AB().
#define MCP23S17_GPPUB 0x0D
Definition at line 46 of file MCP23S17.c.
Referenced by MCP23S17_pullUp(), and MCP23S17_writeGPPU_B().
#define MCP23S17_INTCAPA 0x10
Definition at line 35 of file MCP23S17.c.
#define MCP23S17_INTCAPB 0x11
Definition at line 48 of file MCP23S17.c.
#define MCP23S17_INTCONA 0x08
Definition at line 31 of file MCP23S17.c.
Referenced by MCP23S17_init().
#define MCP23S17_INTCONB 0x09
Definition at line 44 of file MCP23S17.c.
#define MCP23S17_INTFA 0x0E
Definition at line 34 of file MCP23S17.c.
#define MCP23S17_INTFB 0x0F
Definition at line 47 of file MCP23S17.c.
#define MCP23S17_IOCONA 0x0A
Definition at line 32 of file MCP23S17.c.
#define MCP23S17_IOCONB 0x0B
Definition at line 45 of file MCP23S17.c.
#define MCP23S17_IODIRA 0x00
Definition at line 27 of file MCP23S17.c.
Referenced by MCP23S17_init(), MCP23S17_pinMode(), MCP23S17_writeIODIR_A(), and MCP23S17_writeIODIR_AB().
#define MCP23S17_IODIRB 0x01
Definition at line 40 of file MCP23S17.c.
Referenced by MCP23S17_pinMode(), and MCP23S17_writeIODIR_B().
#define MCP23S17_IPOLA 0x02
Definition at line 28 of file MCP23S17.c.
Referenced by MCP23S17_inputPol(), MCP23S17_writeIPOL_A(), and MCP23S17_writeIPOL_AB().
#define MCP23S17_IPOLB 0x03
Definition at line 41 of file MCP23S17.c.
Referenced by MCP23S17_inputPol(), and MCP23S17_writeIPOL_B().
#define MCP23S17_OLATA 0x14
Definition at line 37 of file MCP23S17.c.
#define MCP23S17_OLATB 0x15
Definition at line 50 of file MCP23S17.c.
Typedef Documentation
typedef struct tagMCP23S17 MCP23S17
typedef union tagMCP23S17U MCP23S17U
Function Documentation
u8 MCP23S17_digitalRead (u8 Pin, MCP23S17 * Mcp)
Definition at line 682 of file MCP23S17.c.
References tagMCP23S17U::B, FALSE, tagMCP23S17::GINP, MCP23S17_GPIOA, MCP23S17_GPIOB, and MCP23S17_read_B().
{
 Pin--;
 if (Pin > 15)
  return(0xFF);
 if (Pin < 8)
  {
   if (MCP23S17_read_B(Mcp,MCP23S17_GPIOA,&(Mcp->
      GINP.B[0])) == FALSE)
    return(0xFF);
   return ((Mcp->GINP.B[0] >> Pin) & 0x1);
  }
 else
  {
   Pin -= 8;
   if (MCP23S17_read_B(Mcp,MCP23S17_GPIOB,&(Mcp->
      GINP.B[1])) == FALSE)
    return(0xFF);
   return ((Mcp->GINP.B[1] >> Pin) & 0x1);
  }
}
BOOL MCP23S17_digitalWrite (u8 Pin, u8 SOut, MCP23S17 * Mcp)
Definition at line 840 of file MCP23S17.c.
References tagMCP23S17U::B, FALSE, tagMCP23S17::GPIO, HIGH, MCP23S17_GPIOA, MCP23S17_GPIOB, MCP23S17_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (SOut == HIGH)
    Mcp->GPIO.B[0] |= 1 << Pin;
   else
    Mcp->GPIO.B[0] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_GPIOA,Mcp->
      GPIO.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (SOut == HIGH)
    Mcp->GPIO.B[1] |= 1 << Pin;
   else
    Mcp->GPIO.B[1] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_GPIOB,Mcp->
      GPIO.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
BOOL MCP23S17_init (MCP23S17 * Mcp, u8 SPIAddr, u8 CSPin, BOOL UseIntAdd, u8 SPIChannel, u8 LoSCK, u8 LoSDO, u8 LoSDI)
Definition at line 360 of file MCP23S17.c.
References SPI_Loc_Conf::CPHA, SPI_Loc_Conf::CPOL, tagMCP23S17::CSPin, SPI_Loc_Conf::DelayuS, digitalwrite(), FALSE, tagMCP23S17::GPIO, tagMCP23S17::GPPU, HIGH, tagMCP23S17::IODIR, tagMCP23S17::IPOL, SPI_Loc_Conf::LoSCK, SPI_Loc_Conf::LoSDI, SPI_Loc_Conf::LoSDO, MCP23S17_B_HAEN, MCP23S17_INTCONA, MCP23S17_IODIRA, MCP23S17_write_B(), MCP23S17_write_W(), OUTPUT, pinmode(), SPI_init(), tagMCP23S17::SPIAddr, tagMCP23S17::SPIChannel, tagMCP23S17::SPILoc, SPILoc_Init(), TRUE, tagMCP23S17::UseIntAdd, and tagMCP23S17U::W.
{
 u8 Val;
 Mcp->SPIAddr = SPIAddr;
 Mcp->CSPin = CSPin;
 Mcp->UseIntAdd = UseIntAdd;
 Mcp->SPIChannel = SPIChannel;
 // Initialize the chip enable, HIGH
 digitalwrite(Mcp->CSPin, HIGH);
 pinmode(Mcp->CSPin, OUTPUT);
 switch (Mcp->SPIChannel)
  {
   case 0:
    Mcp->SPILoc.CPOL = FALSE; // Clock Polarity
    Mcp->SPILoc.CPHA = TRUE; // Sample position
    Mcp->SPILoc.DelayuS = 0; // Delay Clock uS
    Mcp->SPILoc.LoSCK = LoSCK;
    Mcp->SPILoc.LoSDO = LoSDO;
    Mcp->SPILoc.LoSDI = LoSDI;
    SPILoc_Init (&Mcp->SPILoc);
    break;
   case 1:
   case 2:
    SPI_init();
    break;
  }
 Mcp->IODIR.W = 0xFFFF;
 Mcp->GPIO.W = 0;
 Mcp->GPPU.W = 0;
 Mcp->IPOL.W = 0;
 Val = 0;
 if (UseIntAdd == TRUE)
  Val |= MCP23S17_B_HAEN;
 if(MCP23S17_write_B(Mcp,MCP23S17_INTCONA,Val) ==
      FALSE)
  return(FALSE);
 if(MCP23S17_write_W(Mcp,MCP23S17_IODIRA,0xFFFF) ==
      FALSE)
  return(FALSE);
 return(TRUE);
}
BOOL MCP23S17_inputPol (u8 Pin, u8 SInPol, MCP23S17 * Mcp)
Definition at line 800 of file MCP23S17.c.
References tagMCP23S17U::B, FALSE, HIGH, tagMCP23S17::IPOL, MCP23S17_IPOLA, MCP23S17_IPOLB, MCP23S17_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (SInPol == HIGH)
    Mcp->IPOL.B[0] |= 1 << Pin;
   else
    Mcp->IPOL.B[0] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_IPOLA,Mcp->
      IPOL.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (SInPol == HIGH)
    Mcp->IPOL.B[1] |= 1 << Pin;
   else
    Mcp->IPOL.B[1] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_IPOLB,Mcp->
      IPOL.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
BOOL MCP23S17_pinMode (u8 Pin, u8 OutIn, MCP23S17 * Mcp)
Definition at line 720 of file MCP23S17.c.
References tagMCP23S17U::B, FALSE, INPUT, tagMCP23S17::IODIR, MCP23S17_IODIRA, MCP23S17_IODIRB, MCP23S17_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (OutIn == INPUT)
    Mcp->IODIR.B[0] |= 1 << Pin;
   else
    Mcp->IODIR.B[0] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_IODIRA,Mcp->
      IODIR.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (OutIn == INPUT)
    Mcp->IODIR.B[1] |= 1 << Pin;
   else
    Mcp->IODIR.B[1] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_IODIRB,Mcp->
      IODIR.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
BOOL MCP23S17_pullUp (u8 Pin, u8 SPull, MCP23S17 * Mcp)
Definition at line 760 of file MCP23S17.c.
References tagMCP23S17U::B, FALSE, tagMCP23S17::GPPU, HIGH, MCP23S17_GPPUA, MCP23S17_GPPUB, MCP23S17_write_B(), and TRUE.
{
 Pin--;
 if (Pin > 15)
  return(FALSE);
 if (Pin < 8)
  {
   if (SPull == HIGH)
    Mcp->GPPU.B[0] |= 1 << Pin;
   else
    Mcp->GPPU.B[0] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_GPPUA,Mcp->
      GPPU.B[0]) == FALSE)
    return(FALSE);
  }
 else
  {
   Pin -= 8;
   if (SPull == HIGH)
    Mcp->GPPU.B[1] |= 1 << Pin;
   else
    Mcp->GPPU.B[1] &= ~(1 << Pin);
   if (MCP23S17_write_B(Mcp,MCP23S17_GPPUB,Mcp->
      GPPU.B[1]) == FALSE)
    return(FALSE);
  }
 return (TRUE);
}
void MCP23S17_read_A (MCP23S17 * Mcp, u8 Addr, u8 Len, char * Val)
Definition at line 311 of file MCP23S17.c.
References tagMCP23S17::CSPin, digitalwrite(), FALSE, HIGH, LOW, MCP23S17_ADDRESS, NULL, SPI_read(), SPI_write(), tagMCP23S17::SPIAddr, tagMCP23S17::SPIChannel, tagMCP23S17::SPILoc, SPILoc_Read(), SPILoc_Write(), and TRUE.
{
 u16 Ctn;
 if ((Len == 0) || (Val == NULL))
  return(FALSE);
 digitalwrite(Mcp->CSPin, LOW);
 switch (Mcp->SPIChannel)
  {
   case 0:
    SPILoc_Write(&Mcp->SPILoc,((MCP23S17_ADDRESS | (Mcp->
      SPIAddr&7))<<1)|1); //Write Into Device
    SPILoc_Write(&Mcp->SPILoc,Addr);
    for (Ctn = 0 ; Ctn < Len ; Ctn++)
     Val[Ctn] = SPILoc_Read(&Mcp->SPILoc);
    break;
   case 1:
   case 2:
    SPI_write(((MCP23S17_ADDRESS | (Mcp->SPIAddr&7))<<1)|1); //Write
       Into Device
    SPI_write(Addr);
    for (Ctn = 0 ; Ctn < Len ; Ctn++)
     Val[Ctn] = SPI_read();
    break;
  }
 digitalwrite(Mcp->CSPin, HIGH);
 return(TRUE);
}
BOOL MCP23S17_read_B (MCP23S17 * Mcp, u8 Addr, u8 * Val)
Definition at line 230 of file MCP23S17.c.
References tagMCP23S17::CSPin, digitalwrite(), FALSE, HIGH, LOW, MCP23S17_ADDRESS, NULL, SPI_read(), SPI_write(), tagMCP23S17::SPIAddr, tagMCP23S17::SPIChannel, tagMCP23S17::SPILoc, SPILoc_Read(), SPILoc_Write(), and TRUE.
Referenced by MCP23S17_digitalRead(), MCP23S17_readGPIO_A(), and MCP23S17_readGPIO_B().
{
 if (Val == NULL)
  return(FALSE);
 digitalwrite(Mcp->CSPin, LOW);
 switch (Mcp->SPIChannel)
  {
   case 0:
    SPILoc_Write(&Mcp->SPILoc,((MCP23S17_ADDRESS | (Mcp->
      SPIAddr&7))<<1)|1); //Write Into Device
    SPILoc_Write(&Mcp->SPILoc,Addr);
    *Val = SPILoc_Read(&Mcp->SPILoc);
    break;
   case 1:
   case 2:
    SPI_write(((MCP23S17_ADDRESS | (Mcp->SPIAddr&7))<<1)|1); //Write
       Into Device
    SPI_write(Addr);
    *Val = SPI_read();
    break;
  }
 digitalwrite(Mcp->CSPin, HIGH);
 return(TRUE);
}
BOOL MCP23S17_read_W (MCP23S17 * Mcp, u8 Addr, u16 * Val)
Definition at line 265 of file MCP23S17.c.
References tagMCP23S17::CSPin, digitalwrite(), FALSE, HIGH, LOW, MCP23S17_ADDRESS, NULL, SPI_read(), SPI_write(), tagMCP23S17::SPIAddr, tagMCP23S17::SPIChannel, tagMCP23S17::SPILoc, SPILoc_Read(), SPILoc_Write(), and TRUE.
Referenced by MCP23S17_readGPIO_AB().
{
 u16 TVal;
 u8 BVal;
char Str[20];
 if (Val == NULL)
  return(FALSE);
 digitalwrite(Mcp->CSPin, LOW);
 switch (Mcp->SPIChannel)
  {
   case 0:
    SPILoc_Write(&Mcp->SPILoc,((MCP23S17_ADDRESS | (Mcp->
      SPIAddr&7))<<1)|1); //Write Into Device
    SPILoc_Write(&Mcp->SPILoc,Addr);
    BVal = SPILoc_Read(&Mcp->SPILoc);
    TVal = SPILoc_Read(&Mcp->SPILoc);
    break;
   case 1:
   case 2:
    SPI_write(((MCP23S17_ADDRESS | (Mcp->SPIAddr&7))<<1)|1); //Write
       Into Device
    SPI_write(Addr);
    BVal = SPI_read();
    TVal = SPI_read();
    break;
  }
 digitalwrite(Mcp->CSPin, HIGH);
 TVal <<= 8;
 TVal |= BVal;
 *Val = TVal;
 return(TRUE);
}
BOOL MCP23S17_readGPIO_A (u8 * Val, MCP23S17 * Mcp)
Definition at line 416 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::GINP, MCP23S17_GPIOA, and MCP23S17_read_B().
{
 BOOL Risu;
 Risu = MCP23S17_read_B(Mcp,MCP23S17_GPIOA,Val);
 Mcp->GINP.B[0] = Val;
 return (Risu);
}
BOOL MCP23S17_readGPIO_AB (u16 * Val, MCP23S17 * Mcp)
Definition at line 452 of file MCP23S17.c.
References tagMCP23S17::GINP, MCP23S17_GPIOA, MCP23S17_read_W(), and tagMCP23S17U::W.
{
 BOOL Risu;
 Risu = MCP23S17_read_W(Mcp,MCP23S17_GPIOA,Val);
 Mcp->GINP.W = Val;
 return (Risu);
}
BOOL MCP23S17_readGPIO_B (u8 * Val, MCP23S17 * Mcp)
Definition at line 434 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::GINP, MCP23S17_GPIOB, and MCP23S17_read_B().
{
 BOOL Risu;
 Risu = MCP23S17_read_B(Mcp,MCP23S17_GPIOB,Val);
 Mcp->GINP.B[1] = Val;
 return (Risu);
}
BOOL MCP23S17_write_A (MCP23S17 * Mcp, u8 Addr, u16 Len, char * Val)
Definition at line 191 of file MCP23S17.c.
References tagMCP23S17::CSPin, digitalwrite(), FALSE, HIGH, LOW, MCP23S17_ADDRESS, NULL, SPI_write(), tagMCP23S17::SPIAddr, tagMCP23S17::SPIChannel, tagMCP23S17::SPILoc, SPILoc_Write(), and TRUE.
{
 u16 Ctn;
 if ((Len == 0) || (Val == NULL))
  return(FALSE);
 digitalwrite(Mcp->CSPin, LOW);
 switch (Mcp->SPIChannel)
  {
   case 0:
    SPILoc_Write(&Mcp->SPILoc,((MCP23S17_ADDRESS | (Mcp->
      SPIAddr&7))<<1)&~1); //Write Into Device
    SPILoc_Write(&Mcp->SPILoc,Addr);
    for (Ctn = 0 ; Ctn < Len ; Ctn++)
    SPILoc_Write(&Mcp->SPILoc,Val[Ctn]);
    break;
   case 1:
   case 2:
    SPI_write(((MCP23S17_ADDRESS | (Mcp->SPIAddr&7))<<1)&~1); //Write
       Into Device
    SPI_write(Addr);
    for (Ctn = 0 ; Ctn < Len ; Ctn++)
    SPI_write(Val[Ctn]);
    break;
  }
 digitalwrite(Mcp->CSPin, HIGH);
 return(TRUE);
}
BOOL MCP23S17_write_B (MCP23S17 * Mcp, u8 Addr, u8 Val)
Definition at line 122 of file MCP23S17.c.
References tagMCP23S17::CSPin, digitalwrite(), HIGH, LOW, MCP23S17_ADDRESS, SPI_write(), tagMCP23S17::SPIAddr, tagMCP23S17::SPIChannel, tagMCP23S17::SPILoc, SPILoc_Write(), and TRUE.
Referenced by MCP23S17_digitalWrite(), MCP23S17_init(), MCP23S17_inputPol(), MCP23S17_pinMode(), MCP23S17_pullUp(), MCP23S17_writeGPIO_A(), MCP23S17_writeGPIO_B(), MCP23S17_writeGPPU_A(), MCP23S17_writeGPPU_B(), MCP23S17_writeIODIR_A(), MCP23S17_writeIODIR_B(), MCP23S17_writeIPOL_A(), and MCP23S17_writeIPOL_B().
{
 digitalwrite(Mcp->CSPin, LOW);
 switch (Mcp->SPIChannel)
  {
   case 0:
    SPILoc_Write(&Mcp->SPILoc,((MCP23S17_ADDRESS | (Mcp->
      SPIAddr&7))<<1)&~1); //Write Into Device
    SPILoc_Write(&Mcp->SPILoc,Addr);
    SPILoc_Write(&Mcp->SPILoc,Val);
    break;
   case 1:
   case 2:
    SPI_write(((MCP23S17_ADDRESS | (Mcp->SPIAddr&7))<<1)&~1); //Write
       Into Device
    SPI_write(Addr);
    SPI_write(Val);
    break;
  }
 digitalwrite(Mcp->CSPin, HIGH);
 return(TRUE);
}
BOOL MCP23S17_write_W (MCP23S17 * Mcp, u8 Addr, u16 Val)
Definition at line 155 of file MCP23S17.c.
References tagMCP23S17::CSPin, digitalwrite(), HIGH, LOW, MCP23S17_ADDRESS, SPI_write(), tagMCP23S17::SPIAddr, tagMCP23S17::SPIChannel, tagMCP23S17::SPILoc, SPILoc_Write(), and TRUE.
Referenced by MCP23S17_init(), MCP23S17_writeGPIO_AB(), MCP23S17_writeGPPU_AB(), MCP23S17_writeIODIR_AB(), and MCP23S17_writeIPOL_AB().
{
 digitalwrite(Mcp->CSPin, LOW);
 switch (Mcp->SPIChannel)
  {
   case 0:
    SPILoc_Write(&Mcp->SPILoc,((MCP23S17_ADDRESS | (Mcp->
      SPIAddr&7))<<1)&~1); //Write Into Device
    SPILoc_Write(&Mcp->SPILoc,Addr);
    SPILoc_Write(&Mcp->SPILoc,Val & 0xFF);
    SPILoc_Write(&Mcp->SPILoc,Val >> 8);
    break;
   case 1:
   case 2:
    SPI_write(((MCP23S17_ADDRESS | (Mcp->SPIAddr&7))<<1)&~1); //Write
       Into Device
    SPI_write(Addr);
    SPI_write(Val & 0xFF);
    SPI_write(Val >> 8);
    break;
  }
 digitalwrite(Mcp->CSPin, HIGH);
 return(TRUE);
}
BOOL MCP23S17_writeGPIO_A (u8 Val, MCP23S17 * Mcp)
Definition at line 474 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::GPIO, MCP23S17_GPIOA, and MCP23S17_write_B().
{
 Mcp->GPIO.B[0] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_GPIOA,Val));
}
BOOL MCP23S17_writeGPIO_AB (u16 Val, MCP23S17 * Mcp)
Definition at line 506 of file MCP23S17.c.
References tagMCP23S17::GPIO, MCP23S17_GPIOA, MCP23S17_write_W(), and tagMCP23S17U::W.
{
 Mcp->GPIO.W = Val;
 return (MCP23S17_write_W(Mcp,MCP23S17_GPIOA,Val));
}
BOOL MCP23S17_writeGPIO_B (u8 Val, MCP23S17 * Mcp)
Definition at line 490 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::GPIO, MCP23S17_GPIOB, and MCP23S17_write_B().
{
 Mcp->GPIO.B[1] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_GPIOB,Val));
}
BOOL MCP23S17_writeGPPU_A (u8 Val, MCP23S17 * Mcp)
Definition at line 578 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::GPPU, MCP23S17_GPPUA, and MCP23S17_write_B().
{
 Mcp->GPPU.B[0] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_GPPUA,Val));
}
BOOL MCP23S17_writeGPPU_AB (u16 Val, MCP23S17 * Mcp)
Definition at line 610 of file MCP23S17.c.
References tagMCP23S17::GPPU, MCP23S17_GPPUA, MCP23S17_write_W(), and tagMCP23S17U::W.
{
 Mcp->GPPU.W = Val;
 return (MCP23S17_write_W(Mcp,MCP23S17_GPPUA,Val));
}
BOOL MCP23S17_writeGPPU_B (u8 Val, MCP23S17 * Mcp)
Definition at line 594 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::GPPU, MCP23S17_GPPUB, and MCP23S17_write_B().
{
 Mcp->GPPU.B[1] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_GPPUB,Val));
}
BOOL MCP23S17_writeIODIR_A (u8 Val, MCP23S17 * Mcp)
Definition at line 526 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::IODIR, MCP23S17_IODIRA, and MCP23S17_write_B().
{
 Mcp->IODIR.B[0] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_IODIRA,Val));
}
BOOL MCP23S17_writeIODIR_AB (u16 Val, MCP23S17 * Mcp)
Definition at line 558 of file MCP23S17.c.
References tagMCP23S17::IODIR, MCP23S17_IODIRA, MCP23S17_write_W(), and tagMCP23S17U::W.
{
 Mcp->IODIR.W = Val;
 return (MCP23S17_write_W(Mcp,MCP23S17_IODIRA,Val));
}
BOOL MCP23S17_writeIODIR_B (u8 Val, MCP23S17 * Mcp)
Definition at line 542 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::IODIR, MCP23S17_IODIRB, and MCP23S17_write_B().
{
 Mcp->IODIR.B[1] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_IODIRB,Val));
}
BOOL MCP23S17_writeIPOL_A (u8 Val, MCP23S17 * Mcp)
Definition at line 629 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::IPOL, MCP23S17_IPOLA, and MCP23S17_write_B().
{
 Mcp->IPOL.B[0] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_IPOLA,Val));
}
BOOL MCP23S17_writeIPOL_AB (u16 Val, MCP23S17 * Mcp)
Definition at line 661 of file MCP23S17.c.
References tagMCP23S17::IPOL, MCP23S17_IPOLA, MCP23S17_write_W(), and tagMCP23S17U::W.
{
 Mcp->IPOL.W = Val;
 return (MCP23S17_write_W(Mcp,MCP23S17_IPOLA,Val));
}
BOOL MCP23S17_writeIPOL_B (u8 Val, MCP23S17 * Mcp)
Definition at line 645 of file MCP23S17.c.
References tagMCP23S17U::B, tagMCP23S17::IPOL, MCP23S17_IPOLB, and MCP23S17_write_B().
{
 Mcp->IPOL.B[1] = Val;
 return (MCP23S17_write_B(Mcp,MCP23S17_IPOLB,Val));
}