/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/ST7565.h File Reference
#include <typedef.h>
*
Macros
#define BLACK 1
#define WHITE 0
#define LCDWIDTH 128
#define LCDHEIGHT 64
#define CMD_DISPLAY_OFF 0xAE
#define CMD_DISPLAY_ON 0xAF
#define CMD_SET_DISP_START_LINE 0x40
#define CMD_SET_PAGE 0xB0
#define CMD_SET_COLUMN_UPPER 0x10
#define CMD_SET_COLUMN_LOWER 0x00
#define CMD_SET_ADC_NORMAL 0xA0
#define CMD_SET_ADC_REVERSE 0xA1
#define CMD_SET_DISP_NORMAL 0xA6
#define CMD_SET_DISP_REVERSE 0xA7
#define CMD_SET_ALLPTS_NORMAL 0xA4
#define CMD_SET_ALLPTS_ON 0xA5
#define CMD_SET_BIAS_9 0xA2
#define CMD_SET_BIAS_7 0xA3
#define CMD_RMW 0xE0
#define CMD_RMW_CLEAR 0xEE
#define CMD_INTERNAL_RESET 0xE2
#define CMD_SET_COM_NORMAL 0xC0
#define CMD_SET_COM_REVERSE 0xC8
#define CMD_SET_POWER_CONTROL 0x28
#define CMD_SET_RESISTOR_RATIO 0x20
#define CMD_SET_VOLUME_FIRST 0x81
#define CMD_SET_VOLUME_SECOND 0
#define CMD_SET_STATIC_OFF 0xAC
#define CMD_SET_STATIC_ON 0xAD
#define CMD_SET_STATIC_REG 0x0
#define CMD_SET_BOOSTER_FIRST 0xF8
#define CMD_SET_BOOSTER_234 0
#define CMD_SET_BOOSTER_5 1
#define CMD_SET_BOOSTER_6 3
#define CMD_NOP 0xE3
#define CMD_TEST 0xF0
Functions
void ST7565_command (u8 c)
void ST7565_data (u8 c)
void ST7565_init (u8 SID, u8 SCLK, u8 A0, u8 RST, u8 CS)
void ST7565_setBrightness (u8 val)
void ST7565_clearDisplay (void)
void ST7565_clear ()
void ST7565_refresh ()
void ST7565_setPixel (u8 x, u8 y, u8 color)
u8 ST7565_getPixel (u8 x, u8 y)
void ST7565_fillCircle (u8 x0, u8 y0, u8 r, u8 color)
void ST7565_drawCircle (u8 x0, u8 y0, u8 r, u8 color)
void ST7565_drawRect (u8 x, u8 y, u8 w, u8 h, u8 color)
void ST7565_fillRect (u8 x, u8 y, u8 w, u8 h, u8 color)
void ST7565_drawLine (u8 x0, u8 y0, u8 x1, u8 y1, u8 color)
void ST7565_drawChar (u8 x, u8 line, unsigned char c)
void ST7565_drawString (u8 x, u8 line, unsigned char *c)
void ST7565_drawString_P (u8 x, u8 line, const unsigned char *c)
void ST7565_drawBitmap (u8 x, u8 y, const u8 *bitmap, u8 w, u8 h, u8 color)
void ST7565_shiftOut (u8 dataPin, u8 clockPin, u8 bitOrder, u8 val)
void ST7565_my_setPixel (u8 x, u8 y, u8 color)
Macro Definition Documentation
#define BLACK 1
Definition at line 30 of file ST7565.h.
#define CMD_DISPLAY_OFF 0xAE
Definition at line 36 of file ST7565.h.
#define CMD_DISPLAY_ON 0xAF
Definition at line 37 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_INTERNAL_RESET 0xE2
Definition at line 58 of file ST7565.h.
#define CMD_NOP 0xE3
Definition at line 72 of file ST7565.h.
#define CMD_RMW 0xE0
Definition at line 56 of file ST7565.h.
Referenced by ST7565_refresh().
#define CMD_RMW_CLEAR 0xEE
Definition at line 57 of file ST7565.h.
#define CMD_SET_ADC_NORMAL 0xA0
Definition at line 45 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_SET_ADC_REVERSE 0xA1
Definition at line 46 of file ST7565.h.
#define CMD_SET_ALLPTS_NORMAL 0xA4
Definition at line 51 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_SET_ALLPTS_ON 0xA5
Definition at line 52 of file ST7565.h.
#define CMD_SET_BIAS_7 0xA3
Definition at line 54 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_SET_BIAS_9 0xA2
Definition at line 53 of file ST7565.h.
#define CMD_SET_BOOSTER_234 0
Definition at line 69 of file ST7565.h.
#define CMD_SET_BOOSTER_5 1
Definition at line 70 of file ST7565.h.
#define CMD_SET_BOOSTER_6 3
Definition at line 71 of file ST7565.h.
#define CMD_SET_BOOSTER_FIRST 0xF8
Definition at line 68 of file ST7565.h.
#define CMD_SET_COLUMN_LOWER 0x00
Definition at line 43 of file ST7565.h.
Referenced by ST7565_clearDisplay(), and ST7565_refresh().
#define CMD_SET_COLUMN_UPPER 0x10
Definition at line 42 of file ST7565.h.
Referenced by ST7565_clearDisplay(), and ST7565_refresh().
#define CMD_SET_COM_NORMAL 0xC0
Definition at line 59 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_SET_COM_REVERSE 0xC8
Definition at line 60 of file ST7565.h.
#define CMD_SET_DISP_NORMAL 0xA6
Definition at line 48 of file ST7565.h.
#define CMD_SET_DISP_REVERSE 0xA7
Definition at line 49 of file ST7565.h.
#define CMD_SET_DISP_START_LINE 0x40
Definition at line 39 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_SET_PAGE 0xB0
Definition at line 40 of file ST7565.h.
Referenced by ST7565_clearDisplay(), and ST7565_refresh().
#define CMD_SET_POWER_CONTROL 0x28
Definition at line 61 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_SET_RESISTOR_RATIO 0x20
Definition at line 62 of file ST7565.h.
Referenced by ST7565_init().
#define CMD_SET_STATIC_OFF 0xAC
Definition at line 65 of file ST7565.h.
#define CMD_SET_STATIC_ON 0xAD
Definition at line 66 of file ST7565.h.
#define CMD_SET_STATIC_REG 0x0
Definition at line 67 of file ST7565.h.
#define CMD_SET_VOLUME_FIRST 0x81
Definition at line 63 of file ST7565.h.
Referenced by ST7565_setBrightness().
#define CMD_SET_VOLUME_SECOND 0
Definition at line 64 of file ST7565.h.
Referenced by ST7565_setBrightness().
#define CMD_TEST 0xF0
Definition at line 73 of file ST7565.h.
#define LCDHEIGHT 64
Definition at line 34 of file ST7565.h.
Referenced by ST7565_clear(), ST7565_drawString(), ST7565_drawString_P(), ST7565_getPixel(), ST7565_init(), ST7565_my_setPixel(), ST7565_refresh(), and ST7565_setPixel().
#define LCDWIDTH 128
Definition at line 33 of file ST7565.h.
Referenced by ST7565_clear(), ST7565_drawString(), ST7565_drawString_P(), ST7565_getPixel(), ST7565_init(), ST7565_my_setPixel(), ST7565_refresh(), and ST7565_setPixel().
#define WHITE 0
Definition at line 31 of file ST7565.h.
Function Documentation
void ST7565_clear ()
Definition at line 889 of file ST7565.c.
References LCDHEIGHT, LCDWIDTH, and ST7565_buffer.
{
  memset(ST7565_buffer, 0, 1024);
  updateBoundingBox(0, 0, LCDWIDTH-1, LCDHEIGHT-1);
}
void ST7565_clearDisplay (void)
Definition at line 897 of file ST7565.c.
References c, CMD_SET_COLUMN_LOWER, CMD_SET_COLUMN_UPPER, CMD_SET_PAGE, ST7565_command(), and ST7565_data().
{
  u8 p, c;
  
  for(p = 0; p < 8; p++) {
    /*
      putstring("new page! ");
      uart_putw_dec(p);
      putstring_nl("");
    */
    ST7565_command(CMD_SET_PAGE | p);
    for(c = 0; c < 129; c++) {
      //uart_putw_dec(c);
      //uart_putchar(' ');
      ST7565_command(CMD_SET_COLUMN_LOWER | (c & 0xf));
      ST7565_command(CMD_SET_COLUMN_UPPER | ((c >> 4) & 0xf));
      ST7565_data(0x0);
    }
  }
}
void ST7565_command (u8 c)
Definition at line 811 of file ST7565.c.
References dc, digitalwrite(), LOW, MSBFIRST, sclk, sid, and ST7565_shiftOut().
Referenced by ST7565_clearDisplay(), ST7565_init(), ST7565_refresh(), and ST7565_setBrightness().
{
  digitalwrite(dc, LOW);
  ST7565_shiftOut(sid, sclk, MSBFIRST, c);
}
void ST7565_data (u8 c)
Definition at line 817 of file ST7565.c.
References dc, digitalwrite(), HIGH, MSBFIRST, sclk, sid, and ST7565_shiftOut().
Referenced by ST7565_clearDisplay(), and ST7565_refresh().
{
  digitalwrite(dc, HIGH);
  ST7565_shiftOut(sid, sclk, MSBFIRST, c);
}
void ST7565_drawBitmap (u8 x, u8 y, const u8 * bitmap, u8 w, u8 h, u8 color)
Definition at line 439 of file ST7565.c.
References _BV, h, pgm_read_byte, and ST7565_my_setPixel().
{
    u8 j, i;
  for (j=0; j<h; j++)
  {
    for (i=0; i<w; i++)
    {
      if (pgm_read_byte(bitmap + i + (j/8)*w) & _BV(j%8))
      {
        ST7565_my_setPixel(x+i, y+j, color);
      }
    }
  }
  updateBoundingBox(x, y, x+w, y+h);
}
void ST7565_drawChar (u8 x, u8 line, unsigned char c)
Definition at line 513 of file ST7565.c.
References font, and ST7565_buffer.
Referenced by ST7565_drawString(), and ST7565_drawString_P().
{
    u8 i;
  for (i =0; i<5; i++)
  {
    ST7565_buffer[x + (line*128) ] = font[(c*5)+i];
    x++;
  }
  updateBoundingBox(x, line*8, x+5, line*8 + 8);
}
void ST7565_drawCircle (u8 x0, u8 y0, u8 r, u8 color)
Definition at line 610 of file ST7565.c.
References ST7565_my_setPixel(), x, and y.
{
  u8 f, ddF_x, ddF_y, x, y;
  
  updateBoundingBox(x0-r, y0-r, x0+r, y0+r);
  f = 1 - r;
  ddF_x = 1;
  ddF_y = -2 * r;
  x = 0;
  y = r;
  ST7565_my_setPixel(x0, y0+r, color);
  ST7565_my_setPixel(x0, y0-r, color);
  ST7565_my_setPixel(x0+r, y0, color);
  ST7565_my_setPixel(x0-r, y0, color);
  while (x<y)
  {
    if (f >= 0) {
      y--;
      ddF_y += 2;
      f += ddF_y;
    }
    x++;
    ddF_x += 2;
    f += ddF_x;
  
    ST7565_my_setPixel(x0 + x, y0 + y, color);
    ST7565_my_setPixel(x0 - x, y0 + y, color);
    ST7565_my_setPixel(x0 + x, y0 - y, color);
    ST7565_my_setPixel(x0 - x, y0 - y, color);
    
    ST7565_my_setPixel(x0 + y, y0 + x, color);
    ST7565_my_setPixel(x0 - y, y0 + x, color);
    ST7565_my_setPixel(x0 + y, y0 - x, color);
    ST7565_my_setPixel(x0 - y, y0 - x, color);
    
  }
}
void ST7565_drawLine (u8 x0, u8 y0, u8 x1, u8 y1, u8 color)
Definition at line 527 of file ST7565.c.
References abs, ST7565_my_setPixel(), and swap.
{
  u8 dx, dy, steep = abs(y1 - y0) > abs(x1 - x0);
  u8 err, ystep;
  if (steep)
  {
    swap(x0, y0);
    swap(x1, y1);
  }
  if (x0 > x1)
  {
    swap(x0, x1);
    swap(y0, y1);
  }
  // much faster to put the test here, since we've already sorted the points
  updateBoundingBox(x0, y0, x1, y1);
  dx = x1 - x0;
  dy = abs(y1 - y0);
  err = dx / 2;
  if (y0 < y1)
  {
    ystep = 1;
  } else {
    ystep = -1;}
  for (; x0<=x1; x0++)
  {
    if (steep)
    {
      ST7565_my_setPixel(y0, x0, color);
    } else {
      ST7565_my_setPixel(x0, y0, color);
    }
    err -= dy;
    if (err < 0)
    {
      y0 += ystep;
      err += dx;
    }
  }
}
void ST7565_drawRect (u8 x, u8 y, u8 w, u8 h, u8 color)
Definition at line 591 of file ST7565.c.
References h, and ST7565_my_setPixel().
{
    u8 i;
  // stupidest version - just pixels - but fast with internal buffer!
  for (i=x; i<x+w; i++)
  {
    ST7565_my_setPixel(i, y, color);
    ST7565_my_setPixel(i, y+h-1, color);
  }
  for (i=y; i<y+h; i++)
  {
    ST7565_my_setPixel(x, i, color);
    ST7565_my_setPixel(x+w-1, i, color);
  }
  updateBoundingBox(x, y, x+w, y+h);
}
void ST7565_drawString (u8 x, u8 line, unsigned char * c)
Definition at line 456 of file ST7565.c.
References LCDHEIGHT, LCDWIDTH, and ST7565_drawChar().
{
  while (c[0] != 0)
  {
    if(c[0] == 10)
    {
        x = 0; // ran out of this line
        line++;
        c++;
    }
    else if((c[0]>127)&&(c[1]>127))
    {
        ST7565_drawChar(x, line, c[1]+c[0]);
        x += 6; // 6 pixels wide
        if (x + 6 >= LCDWIDTH)
        {
        x = 0; // ran out of this line
        line++;
        }
        c+=2;
    }
    else
    {
        ST7565_drawChar(x, line, c[0]);
        x += 6; // 6 pixels wide
        if (x + 6 >= LCDWIDTH)
        {
        x = 0; // ran out of this line
        line++;
        }
        c++;
    }
    if (line >= (LCDHEIGHT/8))
      return; // ran out of space :(
  }
}
void ST7565_drawString_P (u8 x, u8 line, const unsigned char * c)
Definition at line 494 of file ST7565.c.
References c, LCDHEIGHT, LCDWIDTH, pgm_read_byte, and ST7565_drawChar().
{
    u8 c;
  while (1)
  {
    c = (u8)pgm_read_byte(str++);
    if (! c)
      return;
    ST7565_drawChar(x, line, c);
    x += 6; // 6 pixels wide
    if (x + 6 >= LCDWIDTH) {
      x = 0; // ran out of this line
      line++;
    }
    if (line >= (LCDHEIGHT/8))
      return; // ran out of space :(
  }
}
void ST7565_fillCircle (u8 x0, u8 y0, u8 r, u8 color)
Definition at line 654 of file ST7565.c.
References ST7565_my_setPixel(), x, and y.
{
  u8 f, ddF_x, ddF_y, x, y;
  u8 i;
  updateBoundingBox(x0-r, y0-r, x0+r, y0+r);
  f = 1 - r;
  ddF_x = 1;
  ddF_y = -2 * r;
  x = 0;
  y = r;
  for (i=y0-r; i<=y0+r; i++)
  {
    ST7565_my_setPixel(x0, i, color);
  }
  while (x<y)
  {
    if (f >= 0)
    {
      y--;
      ddF_y += 2;
      f += ddF_y;
    }
    x++;
    ddF_x += 2;
    f += ddF_x;
  
    for (i=y0-y; i<=y0+y; i++)
    {
      ST7565_my_setPixel(x0+x, i, color);
      ST7565_my_setPixel(x0-x, i, color);
    }
    for (i=y0-x; i<=y0+x; i++)
    {
      ST7565_my_setPixel(x0+y, i, color);
      ST7565_my_setPixel(x0-y, i, color);
    }
  }
}
void ST7565_fillRect (u8 x, u8 y, u8 w, u8 h, u8 color)
Definition at line 575 of file ST7565.c.
References h, and ST7565_my_setPixel().
{
    u8 i, j;
  // stupidest version - just pixels - but fast with internal buffer!
  for (i=x; i<x+w; i++)
  {
    for (j=y; j<y+h; j++)
    {
      ST7565_my_setPixel(i, j, color);
    }
  }
  updateBoundingBox(x, y, x+w, y+h);
}
u8 ST7565_getPixel (u8 x, u8 y)
Definition at line 725 of file ST7565.c.
References LCDHEIGHT, LCDWIDTH, and ST7565_buffer.
{
  if ((x >= LCDWIDTH) || (y >= LCDHEIGHT))
    return 0;
  return (ST7565_buffer[x+ (y/8)*128] >> (7-(y%8))) & 0x1;
}
void ST7565_init (u8 SID, u8 SCLK, u8 A0, u8 RST, u8 CS)
Definition at line 733 of file ST7565.c.
References CMD_DISPLAY_ON, CMD_SET_ADC_NORMAL, CMD_SET_ALLPTS_NORMAL, CMD_SET_BIAS_7, CMD_SET_COM_NORMAL, CMD_SET_DISP_START_LINE, CMD_SET_POWER_CONTROL, CMD_SET_RESISTOR_RATIO, cs, dc, Delayms(), digitalwrite(), HIGH, LCDHEIGHT, LCDWIDTH, LOW, OUTPUT, pinmode(), rst, sclk, sid, ST7565_command(), and ST7565_setBrightness().
{
    sid = SID;
    sclk = SCLK;
    dc = DC;
    rst = RST;
    cs = CS;
  // set pin directions
  pinmode(sid, OUTPUT);
  pinmode(sclk, OUTPUT);
  pinmode(dc, OUTPUT);
  pinmode(rst, OUTPUT);
  pinmode(cs, OUTPUT);
  // toggle RST low to reset; CS low so it'll listen to us
  if (cs > 0)
    digitalwrite(cs, LOW);
  digitalwrite(rst, LOW);
  Delayms(500);
  digitalwrite(rst, HIGH);
  // LCD bias select
  ST7565_command(CMD_SET_BIAS_7);
  // ADC select
  ST7565_command(CMD_SET_ADC_NORMAL);
  // SHL select
  ST7565_command(CMD_SET_COM_NORMAL);
  // Initial display line
  ST7565_command(CMD_SET_DISP_START_LINE);
  // turn on voltage converter (VC=1, VR=0, VF=0)
  ST7565_command(CMD_SET_POWER_CONTROL | 0x4);
  // wait for 50% rising
  Delayms(50);
  // turn on voltage regulator (VC=1, VR=1, VF=0)
  ST7565_command(CMD_SET_POWER_CONTROL | 0x6);
  // wait >=50ms
  Delayms(50);
  // turn on voltage follower (VC=1, VR=1, VF=1)
  ST7565_command(CMD_SET_POWER_CONTROL | 0x7);
  // wait
  Delayms(10);
  // set lcd operating voltage (regulator resistor, ref voltage resistor)
  ST7565_command(CMD_SET_RESISTOR_RATIO | 0x6);
  // initial display line
  // set page address
  // set column address
  // write display data
  // set up a bounding box for screen updates
  updateBoundingBox(0, 0, LCDWIDTH-1, LCDHEIGHT-1);
  ST7565_command(CMD_DISPLAY_ON);
  ST7565_command(CMD_SET_ALLPTS_NORMAL);
  ST7565_setBrightness(0x18);
}
void ST7565_my_setPixel (u8 x, u8 y, u8 color)
Definition at line 696 of file ST7565.c.
References _BV, LCDHEIGHT, LCDWIDTH, and ST7565_buffer.
Referenced by ST7565_drawBitmap(), ST7565_drawCircle(), ST7565_drawLine(), ST7565_drawRect(), ST7565_fillCircle(), and ST7565_fillRect().
{
  if ((x >= LCDWIDTH) || (y >= LCDHEIGHT))
    return;
  // x is which column
  if (color)
    ST7565_buffer[x+ (y/8)*128] |= _BV(7-(y%8));
  else
    ST7565_buffer[x+ (y/8)*128] &= ~_BV(7-(y%8));
}
void ST7565_refresh ()
Definition at line 830 of file ST7565.c.
References CMD_RMW, CMD_SET_COLUMN_LOWER, CMD_SET_COLUMN_UPPER, CMD_SET_PAGE, LCDHEIGHT, LCDWIDTH, pagemap, ST7565_buffer, ST7565_command(), ST7565_data(), and ST7565_STARTBYTES.
{
  u8 col, maxcol, p;
  /*
  Serial.print("Refresh ("); Serial.print(xUpdateMin, DEC);
  Serial.print(", "); Serial.print(xUpdateMax, DEC);
  Serial.print(","); Serial.print(yUpdateMin, DEC);
  Serial.print(", "); Serial.print(yUpdateMax, DEC); Serial.println(")");
  */
  for(p = 0; p < 8; p++) {
    /*
      putstring("new page! ");
      uart_putw_dec(p);
      putstring_nl("");
    */
#ifdef enablePartialUpdate
    // check if this page is part of update
    if (yUpdateMin >= ((p+1)*8)) {
      continue; // nope, skip it!
    }
    if (yUpdateMax < p*8) {
      break;
    }
#endif
    ST7565_command(CMD_SET_PAGE | pagemap[p]);
#ifdef enablePartialUpdate
    col = xUpdateMin;
    maxcol = xUpdateMax;
#else
    // start at the beginning of the row
    col = 0;
    maxcol = LCDWIDTH-1;
#endif
    ST7565_command(CMD_SET_COLUMN_LOWER | ((col+
      ST7565_STARTBYTES) & 0xf));
    ST7565_command(CMD_SET_COLUMN_UPPER | (((col+
      ST7565_STARTBYTES) >> 4) & 0x0F));
    ST7565_command(CMD_RMW);
    
    for(; col <= maxcol; col++) {
      //uart_putw_dec(col);
      //uart_putchar(' ');
      ST7565_data(ST7565_buffer[(128*p)+col]);
    }
  }
#ifdef enablePartialUpdate
  xUpdateMin = LCDWIDTH - 1;
  xUpdateMax = 0;
  yUpdateMin = LCDHEIGHT-1;
  yUpdateMax = 0;
#endif
}
void ST7565_setBrightness (u8 val)
Definition at line 823 of file ST7565.c.
References CMD_SET_VOLUME_FIRST, CMD_SET_VOLUME_SECOND, and ST7565_command().
Referenced by ST7565_init().
{
    ST7565_command(CMD_SET_VOLUME_FIRST);
    ST7565_command(CMD_SET_VOLUME_SECOND | (val & 0x3f));
}
void ST7565_setPixel (u8 x, u8 y, u8 color)
Definition at line 709 of file ST7565.c.
References _BV, LCDHEIGHT, LCDWIDTH, and ST7565_buffer.
{
  if ((x >= LCDWIDTH) || (y >= LCDHEIGHT))
    return;
  // x is which column
  if (color)
    ST7565_buffer[x+ (y/8)*128] |= _BV(7-(y%8));
  else
    ST7565_buffer[x+ (y/8)*128] &= ~_BV(7-(y%8));
  updateBoundingBox(x,y,x,y);
}
void ST7565_shiftOut (u8 dataPin, u8 clockPin, u8 bitOrder, u8 val)
Definition at line 797 of file ST7565.c.
References digitalwrite(), HIGH, LOW, and LSBFIRST.
Referenced by ST7565_command(), and ST7565_data().
{
        u8 i;
        for (i = 0; i < 8; i++) {
                if (bitOrder == LSBFIRST)
                        digitalwrite(dataPin, !!(val & (1 << i)));
                else
                        digitalwrite(dataPin, !!(val & (1 << (7 - i))));
                        
                digitalwrite(clockPin, HIGH);
                digitalwrite(clockPin, LOW);
        }
}