/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/SimpleModbusSlave.c File Reference
#include <macro.h>
*
#include <typedef.h>
*
#include <delay.c>
*
#include <digitalw.c>
*
Data Structures
struct MODBUSS_DATA
Macros
#define __MODBUSS_C
#define MODBUSS_BUFFER_SIZE 128
#define MODBUSS_SER1 1
#define MODBUSS_SER2 2
#define MODBUSS_SER3 3
Functions
void modbuss_exceptionResponse (MODBUSS_DATA *ModBusS_Data, unsigned char exception)
u16 modbuss_calculateCRC (MODBUSS_DATA *ModBusS_Data, unsigned char bufferSize)
void modbuss_sendPacket (MODBUSS_DATA *ModBusS_Data, unsigned char bufferSize)
BOOL modbuss_SerialClearRxError (MODBUSS_DATA *ModBusS_Data)
char modbuss_SerialAvailable (MODBUSS_DATA *ModBusS_Data)
char modbuss_SerialRead (MODBUSS_DATA *ModBusS_Data)
int modbuss_SerialBegin (MODBUSS_DATA *ModBusS_Data, u32 speed)
void modbuss_SerialWrite (MODBUSS_DATA *ModBusS_Data, char c)
void modbuss_SerialFlush (MODBUSS_DATA *ModBusS_Data)
u16 modbuss_update (MODBUSS_DATA *ModBusS_Data)
void modbuss_configure (MODBUSS_DATA *ModBusS_Data, char port, long baud, unsigned char _slaveID, unsigned char _TxEnablePin, u16 _holdingRegsSize, u16 *_regs)
Macro Definition Documentation
#define __MODBUSS_C
Definition at line 71 of file SimpleModbusSlave.c.
#define MODBUSS_BUFFER_SIZE 128
Definition at line 78 of file SimpleModbusSlave.c.
Referenced by modbuss_update().
#define MODBUSS_SER1 1
Definition at line 80 of file SimpleModbusSlave.c.
Referenced by modbuss_SerialAvailable(), modbuss_SerialBegin(), modbuss_SerialClearRxError(), modbuss_SerialFlush(), modbuss_SerialRead(), and modbuss_SerialWrite().
#define MODBUSS_SER2 2
Definition at line 81 of file SimpleModbusSlave.c.
Referenced by modbuss_SerialAvailable(), modbuss_SerialBegin(), modbuss_SerialClearRxError(), modbuss_SerialFlush(), modbuss_SerialRead(), and modbuss_SerialWrite().
#define MODBUSS_SER3 3
Definition at line 82 of file SimpleModbusSlave.c.
Referenced by modbuss_SerialAvailable(), modbuss_SerialBegin(), modbuss_SerialClearRxError(), modbuss_SerialFlush(), modbuss_SerialRead(), and modbuss_SerialWrite().
Function Documentation
u16 modbuss_calculateCRC (MODBUSS_DATA * ModBusS_Data, unsigned char bufferSize)
Definition at line 496 of file SimpleModbusSlave.c.
References MODBUSS_DATA::frame.
Referenced by modbuss_exceptionResponse(), and modbuss_update().
{
 u16 temp, temp2, flag;
 unsigned char i;
 unsigned char j;
 temp = 0xFFFF;
 for (i = 0; i < bufferSize; i++)
  {
   temp = temp ^ ModBusS_Data->frame[i];
   for (j = 1; j <= 8; j++)
    {
     flag = temp & 0x0001;
     temp >>= 1;
     if (flag)
      temp ^= 0xA001;
    }
  }
 // Reverse byte order.
 temp2 = temp >> 8;
 temp = (temp << 8) | temp2;
 temp &= 0xFFFF;
 // the returned value is already swapped
 // crcLo byte is first & crcHi byte is last
 return temp;
}
void modbuss_configure (MODBUSS_DATA * ModBusS_Data, char port, long baud, unsigned char _slaveID, unsigned char _TxEnablePin, u16 _holdingRegsSize, u16 * _regs)
Definition at line 458 of file SimpleModbusSlave.c.
References digitalwrite(), MODBUSS_DATA::errorCount, MODBUSS_DATA::holdingRegsSize, LOW, modbuss_SerialBegin(), OUTPUT, pinmode(), MODBUSS_DATA::port, MODBUSS_DATA::regs, MODBUSS_DATA::slaveID, MODBUSS_DATA::T1_5, MODBUSS_DATA::T3_5, and MODBUSS_DATA::TxEnablePin.
{
 ModBusS_Data->port = port;
 ModBusS_Data->slaveID = _slaveID;
 modbuss_SerialBegin(ModBusS_Data,baud);
 ModBusS_Data->holdingRegsSize = _holdingRegsSize;
 ModBusS_Data->regs = _regs;
 ModBusS_Data->TxEnablePin = _TxEnablePin;
 if (ModBusS_Data->TxEnablePin > 0)
  {
   pinmode(ModBusS_Data->TxEnablePin, OUTPUT);
   digitalwrite(ModBusS_Data->TxEnablePin, LOW);
  }
 ModBusS_Data->errorCount = 0; // initialize errorCount
    
 // Modbus states that a baud rate higher than 19200 must use a fixed 750 us
 // for inter character time out and 1.75 ms for a ModBusS_Data->frame delay for baud rates
 // below 19200 the timing is more critical and has to be calculated.
 // E.g. 9600 baud in a 10 bit packet is 960 characters per second
 // In milliseconds this will be 960characters per 1000ms. So for 1 character
 // 1000ms/960characters is 1.04167ms per character and finally modbus states
 // an inter-character must be 1.5T or 1.5 times longer than a character. Thus
 // 1.5T = 1.04167ms * 1.5 = 1.5625ms. A ModBusS_Data->frame delay is 3.5T.
    
 if (baud > 19200)
  {
   ModBusS_Data->T1_5 = 750;
   ModBusS_Data->T3_5 = 1750;
  }
 else
  {
   ModBusS_Data->T1_5 = 15000000/baud; // 1T * 1.5 = T1.5
   ModBusS_Data->T3_5 = 35000000/baud; // 1T * 3.5 = T3.5
  }
}
void modbuss_exceptionResponse (MODBUSS_DATA * ModBusS_Data, unsigned char exception)
Definition at line 438 of file SimpleModbusSlave.c.
References MODBUSS_DATA::broadcastFlag, MODBUSS_DATA::errorCount, MODBUSS_DATA::frame, MODBUSS_DATA::function, modbuss_calculateCRC(), modbuss_sendPacket(), and MODBUSS_DATA::slaveID.
Referenced by modbuss_update().
{
 u16 crc16;
 // each call to modbuss_exceptionResponse() will increment the errorCount
 ModBusS_Data->errorCount++;
 if (!ModBusS_Data->broadcastFlag) // don't respond if its a broadcast message
  {
   ModBusS_Data->frame[0] = ModBusS_Data->slaveID;
   ModBusS_Data->frame[1] = (ModBusS_Data->function | 0x80); // set MSB bit high, informs the
       master of an exception
   ModBusS_Data->frame[2] = exception;
   crc16 = modbuss_calculateCRC(ModBusS_Data,3); // ID, function|0x80, exception code
   ModBusS_Data->frame[3] = crc16 >> 8;
   ModBusS_Data->frame[4] = crc16 & 0xFF;
   // exception response is always 5 bytes
   // ID, function + 0x80, exception code, 2 bytes crc
   modbuss_sendPacket(ModBusS_Data,5);
  }
}
void modbuss_sendPacket (MODBUSS_DATA * ModBusS_Data, unsigned char bufferSize)
Definition at line 522 of file SimpleModbusSlave.c.
References Delayus(), digitalwrite(), MODBUSS_DATA::frame, HIGH, LOW, modbuss_SerialFlush(), modbuss_SerialWrite(), MODBUSS_DATA::T3_5, and MODBUSS_DATA::TxEnablePin.
Referenced by modbuss_exceptionResponse(), and modbuss_update().
{
 unsigned char i;
 if (ModBusS_Data->TxEnablePin > 0)
  digitalwrite(ModBusS_Data->TxEnablePin, HIGH);
        
 for (i = 0; i < bufferSize; i++)
 modbuss_SerialWrite(ModBusS_Data,ModBusS_Data->frame[i]);
        
 modbuss_SerialFlush(ModBusS_Data);
    
 // allow a frame delay to indicate end of transmission
 Delayus(ModBusS_Data->T3_5);
    
 if (ModBusS_Data->TxEnablePin > 0)
  digitalwrite(ModBusS_Data->TxEnablePin, LOW);
}
char modbuss_SerialAvailable (MODBUSS_DATA * ModBusS_Data)
Definition at line 148 of file SimpleModbusSlave.c.
References MODBUSS_SER1, MODBUSS_SER2, MODBUSS_SER3, MODBUSS_DATA::port, serial1available(), serial2available(), and serial3available().
Referenced by modbuss_update().
{
 switch (ModBusS_Data->port)
  {
#ifdef MODBUSS_SER1_OK
   case MODBUSS_SER1:
    return(serial1available());
    break;
#endif
#ifdef MODBUSS_SER2_OK
   case MODBUSS_SER2:
    return(serial2available());
    break;
#endif
#ifdef MODBUSS_SER3_OK
   case MODBUSS_SER3:
    return(serial3available());
    break;
#endif
   default:
    return(0);
    break;
  }
}
int modbuss_SerialBegin (MODBUSS_DATA * ModBusS_Data, u32 speed)
Definition at line 200 of file SimpleModbusSlave.c.
References MODBUSS_SER1, MODBUSS_SER2, MODBUSS_SER3, MODBUSS_DATA::port, serial1init(), serial2init(), and serial3init().
Referenced by modbuss_configure().
{
 switch (ModBusS_Data->port)
  {
#ifdef MODBUSS_SER1_OK
   case MODBUSS_SER1:
    serial1init(speed);
    return (1);
    break;
#endif
#ifdef MODBUSS_SER2_OK
   case MODBUSS_SER2:
    serial2init(speed);
    return (1);
    break;
#endif
#ifdef MODBUSS_SER3_OK
   case MODBUSS_SER3:
    serial3init(speed);
    return (1);
    break;
#endif
   default:
    return (-1);
    break;
  }
}
BOOL modbuss_SerialClearRxError (MODBUSS_DATA * ModBusS_Data)
Definition at line 122 of file SimpleModbusSlave.c.
References FALSE, MODBUSS_SER1, MODBUSS_SER2, MODBUSS_SER3, MODBUSS_DATA::port, serial1clearrxerror(), serial2clearrxerror(), and serial3clearrxerror().
Referenced by modbuss_update().
{
 switch (ModBusS_Data->port)
  {
#ifdef MODBUSS_SER1_OK
   case MODBUSS_SER1:
    return(serial1clearrxerror());
    break;
#endif
#ifdef MODBUSS_SER2_OK
   case MODBUSS_SER2:
    return(serial2clearrxerror());
    break;
#endif
#ifdef MODBUSS_SER3_OK
   case MODBUSS_SER3:
    return(serial3clearrxerror());
    break;
#endif
   default:
    return(FALSE);
    break;
  }
}
void modbuss_SerialFlush (MODBUSS_DATA * ModBusS_Data)
Definition at line 254 of file SimpleModbusSlave.c.
References MODBUSS_SER1, MODBUSS_SER2, MODBUSS_SER3, MODBUSS_DATA::port, serial1flush(), serial2flush(), and serial3flush().
Referenced by modbuss_sendPacket().
{
 switch (ModBusS_Data->port)
  {
#ifdef MODBUSS_SER1_OK
   case MODBUSS_SER1:
    serial1flush();
    break;
#endif
#ifdef MODBUSS_SER2_OK
   case MODBUSS_SER2:
    serial2flush();
    break;
#endif
#ifdef MODBUSS_SER3_OK
   case MODBUSS_SER3:
    serial3flush();
    break;
#endif
   default:
    break;
  }
}
char modbuss_SerialRead (MODBUSS_DATA * ModBusS_Data)
Definition at line 174 of file SimpleModbusSlave.c.
References MODBUSS_SER1, MODBUSS_SER2, MODBUSS_SER3, MODBUSS_DATA::port, serial1read(), serial2read(), and serial3read().
Referenced by modbuss_update().
{
 switch (ModBusS_Data->port)
  {
#ifdef MODBUSS_SER1_OK
   case MODBUSS_SER1:
    return(serial1read());
    break;
#endif
#ifdef MODBUSS_SER2_OK
   case MODBUSS_SER2:
    return(serial2read());
    break;
#endif
#ifdef MODBUSS_SER3_OK
   case MODBUSS_SER3:
    return(serial3read());
    break;
#endif
   default:
    return(0);
    break;
  }
}
void modbuss_SerialWrite (MODBUSS_DATA * ModBusS_Data, char c)
Definition at line 229 of file SimpleModbusSlave.c.
References MODBUSS_SER1, MODBUSS_SER2, MODBUSS_SER3, MODBUSS_DATA::port, serial1write(), serial2write(), and serial3write().
Referenced by modbuss_sendPacket().
{
 switch (ModBusS_Data->port)
  {
#ifdef MODBUSS_SER1_OK
   case MODBUSS_SER1:
    serial1write(c);
    break;
#endif
#ifdef MODBUSS_SER2_OK
   case MODBUSS_SER2:
    serial2write(c);
    break;
#endif
#ifdef MODBUSS_SER3_OK
   case MODBUSS_SER3:
    serial3write(c);
    break;
#endif
   default:
    break;
  }
}
u16 modbuss_update (MODBUSS_DATA * ModBusS_Data)
Definition at line 280 of file SimpleModbusSlave.c.
References MODBUSS_DATA::broadcastFlag, Delayus(), MODBUSS_DATA::errorCount, FALSE, MODBUSS_DATA::frame, MODBUSS_DATA::function, MODBUSS_BUFFER_SIZE, modbuss_calculateCRC(), modbuss_exceptionResponse(), modbuss_sendPacket(), modbuss_SerialAvailable(), modbuss_SerialClearRxError(), modbuss_SerialRead(), MODBUSS_DATA::regs, MODBUSS_DATA::slaveID, and MODBUSS_DATA::T1_5.
{
 char caract;
 unsigned char buffer;
 unsigned char overflow;
 unsigned char id;
 u16 crc;
 u16 startingAddress;
 u16 no_of_registers;
 u16 maxData;
 unsigned char index;
 unsigned char address;
 u16 crc16;
 unsigned char noOfBytes;
 unsigned char responseFrameSize;
 u16 temp;
 if (modbuss_SerialClearRxError(ModBusS_Data) == FALSE)
   return;
 if (modbuss_SerialAvailable(ModBusS_Data))
  {
   buffer = 0;
   overflow = 0;
    
   while (modbuss_SerialAvailable(ModBusS_Data))
    {
     // The maximum number of bytes is limited to the serial buffer size of 128 bytes
     // If more bytes is received than the MODBUSS_BUFFER_SIZE the overflow flag will be set and the
     // serial buffer will be red untill all the data is cleared from the receive buffer.
     if (overflow)
      modbuss_SerialRead(ModBusS_Data);
     else
      {
       caract = modbuss_SerialRead(ModBusS_Data);
       if (buffer == MODBUSS_BUFFER_SIZE)
        overflow = 1;
       else
        {
         ModBusS_Data->frame[buffer] = caract;
         buffer++;
        }
      }
     Delayus(ModBusS_Data->T1_5); // inter character time out
    }
    
   // If an overflow occurred increment the errorCount
   // variable and return to the main sketch without
   // responding to the request i.e. force a timeout
   if (overflow)
    return ModBusS_Data->errorCount++;
    
   // The minimum request packet is 8 bytes for function 3 & 16
   if (buffer > 7)
    {
     id = ModBusS_Data->frame[0];
     ModBusS_Data->broadcastFlag = 0;
     if (id == 0)
      ModBusS_Data->broadcastFlag = 1;
        
     if (id == ModBusS_Data->slaveID || ModBusS_Data->broadcastFlag) // if the recieved
       ID matches the ModBusS_Data->slaveID or broadcasting id (0), continue
      {
       crc = ((ModBusS_Data->frame[buffer - 2] << 8) | ModBusS_Data->frame[buffer - 1]); //
       combine the crc Low & High bytes
       if (modbuss_calculateCRC(ModBusS_Data,buffer - 2) == crc) // if the calculated
       crc matches the recieved crc continue
        {
         ModBusS_Data->function = ModBusS_Data->frame[1];
         startingAddress = ((ModBusS_Data->frame[2] << 8) | ModBusS_Data->
      frame[3]); // combine the starting address bytes
         no_of_registers = ((ModBusS_Data->frame[4] << 8) | ModBusS_Data->
      frame[5]); // combine the number of register bytes
         maxData = startingAddress + no_of_registers;
                
         // broadcasting is not supported for function 3
         if (!ModBusS_Data->broadcastFlag && (ModBusS_Data->
      function == 3))
          {
           if (startingAddress < ModBusS_Data->holdingRegsSize) // check exception 2 ILLEGAL DATA ADDRESS
            {
             if (maxData <= ModBusS_Data->holdingRegsSize) // check exception 3 ILLEGAL DATA VALUE
              {
               noOfBytes = no_of_registers * 2;
               // ID, function, noOfBytes, (dataLo + dataHi)*number of registers,
               // crcLo, crcHi
               responseFrameSize = 5 + noOfBytes;
               ModBusS_Data->frame[0] = ModBusS_Data->slaveID;
               ModBusS_Data->frame[1] = ModBusS_Data->function;
               ModBusS_Data->frame[2] = noOfBytes;
               address = 3; // PDU starts at the 4th byte
                            
               for (index = startingAddress; index < maxData; index++)
                {
                 temp = ModBusS_Data->regs[index];
                 ModBusS_Data->frame[address] = temp >> 8; // split the register into 2 bytes
                 address++;
                 ModBusS_Data->frame[address] = temp & 0xFF;
                 address++;
                }
                            
               crc16 = modbuss_calculateCRC(ModBusS_Data,responseFrameSize - 2);
               ModBusS_Data->frame[responseFrameSize - 2] = crc16 >> 8; // split crc into 2 bytes
               ModBusS_Data->frame[responseFrameSize - 1] = crc16 & 0xFF;
               modbuss_sendPacket(ModBusS_Data,responseFrameSize);
              }
             else
              modbuss_exceptionResponse(ModBusS_Data,3); // exception 3 ILLEGAL
       DATA VALUE
            }
           else
            modbuss_exceptionResponse(ModBusS_Data,2); // exception 2 ILLEGAL DATA
       ADDRESS
          }
         else if (ModBusS_Data->function == 16)
          {
           // Check if the recieved number of bytes matches the calculated bytes
           // minus the request bytes.
       // id + function + (2 * address bytes) + (2 * no of register bytes) +
           // byte count + (2 * CRC bytes) = 9 bytes
           if (ModBusS_Data->frame[6] == (buffer - 9))
            {
             if (startingAddress < ModBusS_Data->holdingRegsSize) // check exception 2 ILLEGAL DATA ADDRESS
              {
               if (maxData <= ModBusS_Data->holdingRegsSize) // check exception 3 ILLEGAL DATA VALUE
                {
                 address = 7; // start at the 8th byte in the ModBusS_Data->frame
                 for (index = startingAddress; index < maxData; index++)
                  {
                   ModBusS_Data->regs[index] = ((ModBusS_Data->frame[address] << 8) | ModBusS_Data
      ->frame[address + 1]);
                   address += 2;
                  }
                 // only the first 6 bytes are used for CRC calculation
                 crc16 = modbuss_calculateCRC(ModBusS_Data,6);
                 ModBusS_Data->frame[6] = crc16 >> 8; // split crc into 2 bytes
                 ModBusS_Data->frame[7] = crc16 & 0xFF;
                                
                 // a function 16 response is an echo of the first 6 bytes from
                 // the request + 2 crc bytes
                 if (!ModBusS_Data->broadcastFlag) // don't respond if it's a broadcast
       message
                 modbuss_sendPacket(ModBusS_Data,8);
                }
               else
                modbuss_exceptionResponse(ModBusS_Data,3); // exception 3 ILLEGAL
       DATA VALUE
              }
             else
              modbuss_exceptionResponse(ModBusS_Data,2); // exception 2 ILLEGAL
       DATA ADDRESS
            }
           else
            ModBusS_Data->errorCount++; // corrupted packet
          }
         else
          modbuss_exceptionResponse(ModBusS_Data,1); // exception 1 ILLEGAL
       FUNCTION
        }
       else // checksum failed
        ModBusS_Data->errorCount++;
      } // incorrect id
    }
   else
    if (buffer > 0 && buffer < 8)
     ModBusS_Data->errorCount++; // corrupted packet
  }
 return ModBusS_Data->errorCount;
}