/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/adb.h File Reference
Macros
#define ADB_INVALID_CHANNEL_HANDLE (-1)
#define ADB_MAX_CHANNELS 8
#define ADB_CHANNEL_NAME_MAX_LENGTH 16
Typedefs
typedef int ADB_CHANNEL_HANDLE
typedef void(* ADBChannelRecvFunc)(ADB_CHANNEL_HANDLE h, const void *data, unsigned int data_len)
Functions
void ADBInit ()
unsigned char ADBConnected ()
ADB_CHANNEL_HANDLE ADBOpen (const char *name, ADBChannelRecvFunc recv_func)
void ADBClose (ADB_CHANNEL_HANDLE handle)
unsigned char ADBChannelReady (ADB_CHANNEL_HANDLE handle)
void ADBWrite (ADB_CHANNEL_HANDLE handle, const void *data, unsigned int data_len)
unsigned char ADBTasks ()
Macro Definition Documentation
#define ADB_CHANNEL_NAME_MAX_LENGTH 16
Definition at line 77 of file adb.h.
#define ADB_INVALID_CHANNEL_HANDLE (-1)
Definition at line 71 of file adb.h.
#define ADB_MAX_CHANNELS 8
Definition at line 74 of file adb.h.
Typedef Documentation
typedef int ADB_CHANNEL_HANDLE
Definition at line 67 of file adb.h.
typedef void(* ADBChannelRecvFunc)(ADB_CHANNEL_HANDLE h, const void *data, unsigned int data_len)
Definition at line 86 of file adb.h.
Function Documentation
unsigned char ADBChannelReady (ADB_CHANNEL_HANDLE handle)
Referenced by _ADBOpen().
void ADBClose (ADB_CHANNEL_HANDLE handle)
unsigned char ADBConnected ()
void ADBInit ()
Referenced by _ADBInit().
ADB_CHANNEL_HANDLE ADBOpen (const char * name, ADBChannelRecvFunc recv_func)
Referenced by _ADBOpen().
unsigned char ADBTasks ()
Referenced by _ADBOpen().
void ADBWrite (ADB_CHANNEL_HANDLE handle, const void * data, unsigned int data_len)
Referenced by ADBSend().