/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/bt/bluetooth.c File Reference
#include <stdlib.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <typedef.h>
*
#include <digitalw.c>
*
#include <serial.c>
*
#include <delay.c>
*
#include <itoa.c>
*
#include <__cdc.c>
*
Data Structures
struct BT_RESPONSE
Macros
#define __BLUETOOTH_C
#define BT_DELAY 10
#define CRLF `/r/n`
Enumerations
enum BT_STATUS { BT_OK = 111,
BT_ERROR,
BT_COMPLETE
 }
Functions
u8 * BT_getBuffer (u8 uart_port, u8 *buffer)
BT_STATUS BT_getStatusCode (u8 *status)
BT_RESPONSE BT_getResponse (u8 uart_port, BT_RESPONSE response)
BT_RESPONSE BT_getExtendedResponse (u8 uart_port)
BT_RESPONSE BT_sendCommand (u8 uart_port, u8 *fmt,...)
BT_RESPONSE BT_setCommandMode (u8 uart_port)
BT_RESPONSE BT_echoOff (u8 uart_port)
BT_RESPONSE BT_echoOn (u8 uart_port)
BT_RESPONSE BT_restore (u8 uart_port)
BT_RESPONSE BT_reset (u8 uart_port)
BT_RESPONSE BT_getFirmware (u8 uart_port)
BT_RESPONSE BT_setDeviceName (u8 uart_port, u8 *name)
BT_RESPONSE BT_getDeviceName (u8 uart_port)
BT_RESPONSE BT_setDeviceAddress (u8 uart_port, u8 *bdaddr)
BT_RESPONSE BT_getDeviceAddress (u8 uart_port)
BT_RESPONSE BT_setAutoConnection (u8 uart_port)
BT_RESPONSE BT_setUARTSpeed (u8 uart_port, u32 baud_rate)
BT_RESPONSE BT_disableSecurity (u8 uart_port)
BT_RESPONSE BT_writeFlash (u8 uart_port)
BT_RESPONSE BT_start (u8 uart_port)
BT_RESPONSE BT_sleep (u8 uart_port)
BT_RESPONSE BT_search (u8 uart_port, u8 s)
BT_RESPONSE BT_init (u8 uart_port, u32 baud_rate)
BT_RESPONSE BT_connect (u8 uart_port, u8 *bdaddr)
Macro Definition Documentation
#define __BLUETOOTH_C
Definition at line 25 of file bluetooth.c.
#define BT_DELAY 10
Definition at line 37 of file bluetooth.c.
Referenced by BT_sendCommand().
#define CRLF `/r/n`
Definition at line 38 of file bluetooth.c.
Referenced by BT_getResponse().
Enumeration Type Documentation
enum BT_STATUS
Enumerator
BT_OK
BT_ERROR
BT_COMPLETE
Definition at line 41 of file bluetooth.c.
{
    BT_OK = 111,
    BT_ERROR,
    BT_COMPLETE
} BT_STATUS;
Function Documentation
BT_RESPONSE BT_connect (u8 uart_port, u8 * bdaddr)
Definition at line 386 of file bluetooth.c.
References BT_ERROR, BT_getExtendedResponse(), BT_sendCommand(), and BT_RESPONSE::code.
{
    BT_RESPONSE response;
    
    BT_sendCommand(uart_port,"AT+BTPAR=1,%s\r", bdaddr); // Pair with remote device
    response = BT_getExtendedResponse(uart_port);
    if (response.code == BT_ERROR) return response;
    BT_sendCommand(uart_port,"AT+BTCLT=%s,1\r", bdaddr); // on Port 1
    response = BT_getExtendedResponse(uart_port);
    // the device will enter data mode if OK
    return response;
}
BT_RESPONSE BT_disableSecurity (u8 uart_port)
Definition at line 296 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTSEC=0\r");
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_echoOff (u8 uart_port)
Definition at line 180 of file bluetooth.c.
References BT_sendCommand().
{
    BT_sendCommand(uart_port,"ATE0\r");
    //return BT_getResponse(uart_port);
}
BT_RESPONSE BT_echoOn (u8 uart_port)
Definition at line 190 of file bluetooth.c.
References BT_sendCommand().
{
    BT_sendCommand(uart_port,"ATE1\r");
    //return BT_getResponse(uart_port);
}
u8* BT_getBuffer (u8 uart_port, u8 * buffer)
Definition at line 61 of file bluetooth.c.
References c, SerialAvailable(), and SerialRead().
Referenced by BT_getResponse().
{
    u8 c, i = 0;
    
    // wait until something is received
    while (!SerialAvailable(uart_port));
    do {
        c = SerialRead(uart_port); // return 255 (-1) if no reception
        if (c != 255) buffer[i++] = c;
    } while (c != 255);// && (i < 80));
    // C string must be null-terminated
    //BT_BUFFER[i] = '\0';
    buffer[i] = '\0';
    //CDCprintf("buffer = [%s]\r\n", BT_BUFFER);
    //return BT_BUFFER;
    return buffer;
}
BT_RESPONSE BT_getDeviceAddress (u8 uart_port)
Definition at line 262 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTBDA?\r");
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_getDeviceName (u8 uart_port)
Definition at line 242 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTLNM?\r");
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_getExtendedResponse (u8 uart_port)
Definition at line 130 of file bluetooth.c.
Referenced by BT_connect(), BT_disableSecurity(), BT_getDeviceAddress(), BT_getDeviceName(), BT_search(), BT_setAutoConnection(), BT_setDeviceAddress(), BT_setDeviceName(), BT_setUARTSpeed(), BT_sleep(), BT_start(), and BT_writeFlash().
{
    u8 length;
    u8 *buffer;
    BT_RESPONSE response;
    
    // get a complete response from the module
    //buffer = BT_getBuffer(uart_port, buffer);
    // response's format is :
    // <CR><LF><status><CR><LF> with status = OK or ERROR
/*
    response.command = strtok(buffer, CRLF); // to remove the first CRLF
    response.command = strtok(buffer, CRLF);
    response.data = strtok(NULL, CRLF);
    response.status = strtok(NULL, CRLF);
    response.code = BT_getStatusCode(response.status);
    return response;
*/
}
BT_RESPONSE BT_getFirmware (u8 uart_port)
Definition at line 222 of file bluetooth.c.
References BT_sendCommand().
{
    BT_sendCommand(uart_port,"ATI\r");
    //return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_getResponse (u8 uart_port, BT_RESPONSE response)
Definition at line 107 of file bluetooth.c.
References BT_getBuffer(), BT_getStatusCode(), BT_RESPONSE::code, BT_RESPONSE::command, CRLF, BT_RESPONSE::data, NULL, and BT_RESPONSE::status.
{
    //u8 *buffer;
    u8 *buffer = (u8*) malloc(128);
    // get a complete response from the module
    buffer = BT_getBuffer(uart_port, buffer);
    //CDCprintf("buffer=[%s]", buffer);
    response.command = NULL;
    response.data = strtok(buffer, CRLF); // to remove the first CRLF
    response.data = strtok(NULL, CRLF);
    response.status = strtok(NULL, CRLF);
    response.code = BT_getStatusCode(response.status);
    return response;
}
BT_STATUS BT_getStatusCode (u8 * status)
Definition at line 85 of file bluetooth.c.
References BT_COMPLETE, BT_ERROR, and BT_OK.
Referenced by BT_getResponse().
{
    u8 length;
    BT_STATUS code;
    
    length = strlen(status);
    
    // check last char if status is OK, ERROR or COMPLETE
    switch (status[length-1])
    {
        case 'K': return BT_OK;
        case 'R': return BT_ERROR;
        case 'E': return BT_COMPLETE;
    }
}
BT_RESPONSE BT_init (u8 uart_port, u32 baud_rate)
Definition at line 349 of file bluetooth.c.
References BT_setCommandMode().
{
    BT_RESPONSE response;
    // 115200 bauds is the default configuration value
    //SerialConfigure(uart_port, UART_ENABLE, UART_RX_TX_ENABLED, 115200);
    response = BT_setCommandMode(uart_port);
    //BT_getFirmware(uart_port);
    //BT_echoOff(uart_port);
    //BT_restore(uart_port);
    //BT_setDeviceName(uart_port, "Pinguino");
    // Pass through, DCE, enable escape sequence, disable entering in command mode with DTR/DSR, enable LED
    //BT_sendCommand(uart_port,"AT+BTCFG=33");
    //BT_setAutoConnection(uart_port);
/*
    if (baud_rate != 115200)
    {
        BT_setUARTSpeed(uart_port, baud_rate);
        // new UART speed
        SerialConfigure(uart_port, UART_ENABLE, UART_RX_TX_ENABLED, baud_rate);
    }
*/
    //BT_disableSecurity(uart_port);
    //BT_writeFlash(uart_port);
    //BT_start(uart_port);
    return response;
}
BT_RESPONSE BT_reset (u8 uart_port)
Definition at line 212 of file bluetooth.c.
References BT_sendCommand().
{
    BT_sendCommand(uart_port,"ATZ\r");
    //return BT_getResponse(uart_port);
}
BT_RESPONSE BT_restore (u8 uart_port)
Definition at line 202 of file bluetooth.c.
References BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT&F\r");
    //return BT_getResponse(uart_port);
}
BT_RESPONSE BT_search (u8 uart_port, u8 s)
Definition at line 336 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    // cancels any current commands
    BT_sendCommand(uart_port,"AT+BTCAN\r");
    BT_sendCommand(uart_port,"AT+BTINQ=%d\r", s);
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_sendCommand (u8 uart_port, u8 * fmt, ...)
Definition at line 156 of file bluetooth.c.
References BT_DELAY, Delayms(), and SerialFlush().
Referenced by BT_connect(), BT_disableSecurity(), BT_echoOff(), BT_echoOn(), BT_getDeviceAddress(), BT_getDeviceName(), BT_getFirmware(), BT_reset(), BT_restore(), BT_search(), BT_setAutoConnection(), BT_setCommandMode(), BT_setDeviceAddress(), BT_setDeviceName(), BT_setUARTSpeed(), BT_sleep(), BT_start(), and BT_writeFlash().
{
    SerialFlush(uart_port);
    SerialPrintf(uart_port, fmt);
    //CDCprintf(fmt);
    Delayms(BT_DELAY);
}
BT_RESPONSE BT_setAutoConnection (u8 uart_port)
Definition at line 272 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTAUT=1,0\r");
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_setCommandMode (u8 uart_port)
Definition at line 168 of file bluetooth.c.
References BT_sendCommand().
Referenced by BT_init().
{
    BT_sendCommand(uart_port,"+++\r");
    BT_sendCommand(uart_port,"+++\r");
    BT_sendCommand(uart_port,"+++\r");
    //return BT_getResponse(uart_port);
}
BT_RESPONSE BT_setDeviceAddress (u8 uart_port, u8 * bdaddr)
Definition at line 252 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTSET=1,%s\r", bdaddr);
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_setDeviceName (u8 uart_port, u8 * name)
Definition at line 232 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTLNM=\"%s\"\r", name);
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_setUARTSpeed (u8 uart_port, u32 baud_rate)
Definition at line 282 of file bluetooth.c.
References BT_getExtendedResponse(), BT_sendCommand(), and ultoa().
{
    char *string;
    // Change UART settings (baud rate, data bits, stop bits, parity, stop bits, flow control)
    // Enable RTS/CTS, DTR/DSR Flow control
    BT_sendCommand(uart_port,"AT+BTURT=%s,8,0,1,3\r", ultoa(baud_rate, string, 10));
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_sleep (u8 uart_port)
Definition at line 326 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTSLP\r");
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_start (u8 uart_port)
Definition at line 316 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTSRV=1\r");
    return BT_getExtendedResponse(uart_port);
}
BT_RESPONSE BT_writeFlash (u8 uart_port)
Definition at line 306 of file bluetooth.c.
References BT_getExtendedResponse(), and BT_sendCommand().
{
    BT_sendCommand(uart_port,"AT+BTFLS\r");
    return BT_getExtendedResponse(uart_port);
}