/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/bt/bluetooth_mx220.c File Reference
#include <stdarg.h>
*
#include <typedef.h>
*
#include <serial.c>
*
#include <itoa.c>
*
Macros
#define __BLUETOOTH_C
#define BT_OK 111
#define BT_ERROR 112
#define BT_COMPLETE 113
Functions
u8 BT_ok (u8 uart_port)
void BT_send (u8 uart_port, char *fmt,...)
void BT_restore (u8 uart_port)
void BT_reset (u8 uart_port)
void BT_setDeviceName (u8 uart_port, u8 *name)
u8 * BT_getDeviceName (u8 uart_port)
void BT_setDeviceAddress (u8 uart_port, u8 *bdaddr)
u8 * BT_getDeviceAddress (u8 uart_port)
void BT_setAutoConnection (u8 uart_port)
void BT_setUARTSpeed (u8 uart_port, u32 baud_rate)
void BT_disableSecurity (u8 uart_port)
void BT_writeFlash (u8 uart_port)
void BT_start (u8 uart_port)
void BT_setCommandMode (u8 uart_port)
void BT_echoOff (u8 uart_port)
void BT_echoOn (u8 uart_port)
void BT_sleep (u8 uart_port)
u8 BT_init (u8 uart_port, u32 baud_rate)
u8 BT_connect (u8 uart_port, u8 *bdaddr)
Macro Definition Documentation
#define __BLUETOOTH_C
Definition at line 31 of file bluetooth_mx220.c.
#define BT_COMPLETE 113
Definition at line 45 of file bluetooth_mx220.c.
Referenced by BT_ok().
#define BT_ERROR 112
Definition at line 44 of file bluetooth_mx220.c.
Referenced by BT_ok().
#define BT_OK 111
Definition at line 43 of file bluetooth_mx220.c.
Referenced by BT_ok(), and BT_send().
Function Documentation
u8 BT_connect (u8 uart_port, u8 * bdaddr)
Definition at line 204 of file bluetooth_mx220.c.
References BT_ok(), and BT_send().
{
    BT_send(uart_port,"AT+BTPAR=1,%s\r\n", bdaddr); // Pair with remote device
    BT_send(uart_port,"AT+BTCLT=%s,1\r\n", bdaddr); // on Port 1
    // the device will enter data mode if OK
    return (BT_ok(uart_port));
}
void BT_disableSecurity (u8 uart_port)
Definition at line 140 of file bluetooth_mx220.c.
References BT_send().
Referenced by BT_init().
{
    BT_send(uart_port,"AT+BTSEC=0\r\n");
}
void BT_echoOff (u8 uart_port)
Definition at line 164 of file bluetooth_mx220.c.
References BT_send().
{
    BT_send(uart_port,"ATE0\r\n");
}
void BT_echoOn (u8 uart_port)
Definition at line 170 of file bluetooth_mx220.c.
References BT_send().
{
    BT_send(uart_port,"ATE1\r\n");
}
u8* BT_getDeviceAddress (u8 uart_port)
Definition at line 115 of file bluetooth_mx220.c.
References BT_send().
{
    BT_send(uart_port,"AT+BTBDA?\r\n");
/*
    while (!UART2SerialBuffer);
    return UART2SerialBuffer;
*/
}
u8* BT_getDeviceName (u8 uart_port)
Definition at line 99 of file bluetooth_mx220.c.
References BT_send().
{
    BT_send(uart_port,"AT+BTLNM?\r\n");
/*
    while (!UART2SerialBuffer);
    return UART2SerialBuffer;
*/
}
u8 BT_init (u8 uart_port, u32 baud_rate)
Definition at line 181 of file bluetooth_mx220.c.
References BT_disableSecurity(), BT_ok(), BT_restore(), BT_setAutoConnection(), BT_setCommandMode(), BT_setDeviceName(), BT_setUARTSpeed(), BT_start(), BT_writeFlash(), SerialConfigure(), UART_ENABLE, and UART_RX_TX_ENABLED.
{
    SerialConfigure(uart_port, UART_ENABLE,
      UART_RX_TX_ENABLED, baud_rate);
//BT_echoOff(uart_port);
    BT_setCommandMode(uart_port);
    BT_restore(uart_port);
    BT_setDeviceName(uart_port, "Pinguino");
// Pass through, DCE, enable escape sequence, disable entering in command moode with DTR/DSR, enable LED
//BT_send(uart_port,"AT+BTCFG=33\r\n");
    BT_setAutoConnection(uart_port);
    BT_setUARTSpeed(uart_port, baud_rate);
    BT_disableSecurity(uart_port);
    BT_writeFlash(uart_port);
    BT_start(uart_port);
    return (BT_ok(uart_port));
}
u8 BT_ok (u8 uart_port)
Definition at line 47 of file bluetooth_mx220.c.
References BT_COMPLETE, BT_ERROR, BT_OK, and SerialRead().
Referenced by BT_connect(), BT_init(), and BT_send().
{
    u8 i, ret;
    while (!(ret = SerialRead(uart_port)));
    switch(ret)
    {
        case 'O':// "OK"
            /*for (i=0; i<10; i++)
            {
                toggle(13);
                Delayms(100);
            }*/
            return BT_OK;
        case 'C':// "COMPLETE"
            return BT_COMPLETE;
        case 'E':// "ERROR"
            return BT_ERROR;
        default:
            return BT_ERROR;
    }
}
void BT_reset (u8 uart_port)
Definition at line 87 of file bluetooth_mx220.c.
References BT_send().
{
    BT_send(uart_port,"ATZ\r\n");
}
void BT_restore (u8 uart_port)
Definition at line 81 of file bluetooth_mx220.c.
References BT_send().
Referenced by BT_init().
{
    BT_send(uart_port,"AT&F\r\n");
}
void BT_send (u8 uart_port, char * fmt, ...)
Definition at line 70 of file bluetooth_mx220.c.
References BT_OK, and BT_ok().
Referenced by BT_connect(), BT_disableSecurity(), BT_echoOff(), BT_echoOn(), BT_getDeviceAddress(), BT_getDeviceName(), BT_reset(), BT_restore(), BT_setAutoConnection(), BT_setCommandMode(), BT_setDeviceAddress(), BT_setDeviceName(), BT_setUARTSpeed(), BT_sleep(), BT_start(), and BT_writeFlash().
{
    do {
        SerialPrintf(uart_port, fmt);
        //Delayms(BT_DELAY);
    } while (BT_ok(uart_port) != BT_OK);
}
void BT_setAutoConnection (u8 uart_port)
Definition at line 125 of file bluetooth_mx220.c.
References BT_send().
Referenced by BT_init().
{
    BT_send(uart_port,"AT+BTAUT=1,0\r\n");
}
void BT_setCommandMode (u8 uart_port)
Definition at line 158 of file bluetooth_mx220.c.
References BT_send().
Referenced by BT_init().
{
    BT_send(uart_port,"+++");
}
void BT_setDeviceAddress (u8 uart_port, u8 * bdaddr)
Definition at line 109 of file bluetooth_mx220.c.
References BT_send().
{
    BT_send(uart_port,"AT+BTSET=1,%s\r\n", bdaddr);
}
void BT_setDeviceName (u8 uart_port, u8 * name)
Definition at line 93 of file bluetooth_mx220.c.
References BT_send().
Referenced by BT_init().
{
    BT_send(uart_port,"AT+BTLNM=\"%s\"\r\n", name);
}
void BT_setUARTSpeed (u8 uart_port, u32 baud_rate)
Definition at line 130 of file bluetooth_mx220.c.
References BT_send(), and ultoa().
Referenced by BT_init().
{
    char *string;
    // Change UART settings (baud rate, data bits, stop bits, parity, stop bits, flow control)
    // Enable RTS/CTS, DTR/DSR Flow control
    BT_send(uart_port,"AT+BTURT=%s,8,0,1,3\r\n", ultoa(baud_rate, string, 10));
}
void BT_sleep (u8 uart_port)
Definition at line 176 of file bluetooth_mx220.c.
References BT_send().
{
    BT_send(uart_port,"AT+BTSLP\r\n");
}
void BT_start (u8 uart_port)
Definition at line 152 of file bluetooth_mx220.c.
References BT_send().
Referenced by BT_init().
{
    BT_send(uart_port,"AT+BTSRV=1\r\n\r\n");
}
void BT_writeFlash (u8 uart_port)
Definition at line 146 of file bluetooth_mx220.c.
References BT_send().
Referenced by BT_init().
{
    BT_send(uart_port,"AT+BTFLS\r\n");
}