Led Class Reference
#include <led.h>
Public Member Functions
Led (u8)
void on ()
void off ()
void toggle ()
Detailed Description
Definition at line 6 of file led.h.
Constructor & Destructor Documentation
Led (u8 pin)
Definition at line 10 of file led.c.
References OUTPUT, and pinmode().
{
    _pin = pin;
    pinmode(_pin, OUTPUT);
}
Member Function Documentation
void off ()
Definition at line 21 of file led.c.
References digitalwrite(), and OFF.
{
    digitalwrite(_pin, OFF);
}
void on ()
Definition at line 16 of file led.c.
References digitalwrite(), and ON.
{
    digitalwrite(_pin, ON);
}
void toggle ()
Definition at line 26 of file led.c.
References digitalread(), and digitalwrite().
{
    digitalwrite(_pin, digitalread(_pin) ^ 1);
}
The documentation for this class was generated from the following files:
/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/led.h
/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/led.c