/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/ctype.c File Reference
#include <typedef.h>
*
Macros
#define __CTYPE_C
Functions
u8 isalnum (u8)
u8 isalpha (u8)
u8 iscntrl (u8)
u8 isdigit (u8)
u8 isgraph (u8)
u8 islower (u8)
u8 isprint (u8)
u8 ispunct (u8)
u8 isspace (u8)
u8 isupper (u8)
u8 isxdigit (u8)
u8 tolower (u8)
u8 toupper (u8)
u8 isblank (u8)
u8 isascii (u8)
u8 toascii (u8)
Macro Definition Documentation
#define __CTYPE_C
Definition at line 27 of file ctype.c.
Function Documentation
u8 isalnum (u8 c)
Definition at line 48 of file ctype.c.
References isalpha(), and isdigit().
Referenced by ispunct().
{
    if ((isalpha(c)) || (isdigit(c)))
        return 1;
    return 0;
}
u8 isalpha (u8 c)
Definition at line 55 of file ctype.c.
References islower(), and isupper().
Referenced by isalnum().
{
    if ((isupper(c)) || (islower(c)))
      return 1;
    return 0;
}
u8 isascii (u8 c)
Definition at line 154 of file ctype.c.
{
    return c >= 0 && c< 128;
}
u8 isblank (u8 c)
Definition at line 148 of file ctype.c.
{
    //return ((__ctype_ptr__[c+1] & _B) || (c == '\t')); ???
    return (c == '\t');
}
u8 iscntrl (u8 c)
Definition at line 63 of file ctype.c.
{
    if ((c >= 0) && (c <= 31))
        return 1;
    return 0;
}
u8 isdigit (u8 c)
Definition at line 70 of file ctype.c.
Referenced by isalnum().
{
    if ((c >= 48) && (c <= 57))
        return 1;
    return 0;
}
u8 isgraph (u8 c)
Definition at line 78 of file ctype.c.
{
    if ((c >= 33) && (c <= 255))
      return 1;
    return 0;
}
u8 islower (u8 c)
Definition at line 86 of file ctype.c.
Referenced by isalpha(), tolower(), and toupper().
{
    if ((c >= 97) && (c <= 122))
        return 1;
    return 0;
}
u8 isprint (u8 c)
Definition at line 94 of file ctype.c.
Referenced by ispunct().
{
    if ((c >= 32) && (c < 126))
      return 1;
    return 0;
}
u8 ispunct (u8 c)
Definition at line 102 of file ctype.c.
References isalnum(), isprint(), and isspace().
{
    if ((!isalnum(c)) && (!isspace(c)) && (isprint(c)))
        return 1;
    return 0;
}
u8 isspace (u8 c)
Definition at line 109 of file ctype.c.
Referenced by ispunct().
{
    if (c == 32)
        return 1;
    return 0;
}
u8 isupper (u8 c)
Definition at line 116 of file ctype.c.
Referenced by isalpha().
{
    if ((c >= 65) && (c <= 90))
        return 1;
    return 0;
}
u8 isxdigit (u8 c)
Definition at line 124 of file ctype.c.
{
    if (((c >= 48) && (c<=57)) || ((c >= 65) && (c <= 70)) || ((c >= 97) && (
      c <= 102)))
        return 1;
    return 0;
}
u8 toascii (u8 c)
Definition at line 159 of file ctype.c.
{
    return (c)&0177;
}
u8 tolower (u8 c)
Definition at line 131 of file ctype.c.
References c, and islower().
{
    if (!islower(c))
        return c + ('a' - 'A');
    else
        return c;
}
u8 toupper (u8 c)
Definition at line 139 of file ctype.c.
References c, and islower().
Referenced by fopenM().
{
    if (islower(c))
        return c - ('a' - 'A');
    else
        return c;
}