/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/delayms.c File Reference
#include <typedef.h>
*
#include <delay.h>
*
Macros
#define __DELAYMS_C__
Functions
void Delayms (unsigned int milliseconds)
Macro Definition Documentation
#define __DELAYMS_C__
Definition at line 30 of file delayms.c.
Function Documentation
void Delayms (unsigned int milliseconds)
the delayNNtcy family of functions performs a delay of NN cycles. Possible values for NN are: 10 10*n cycles delay 100 100*n cycles delay 1k 1000*n cycles delay 10k 10000*n cycles delay 100k 100000*n cycles delay 1m 1000000*n cycles delay
3100 Hz < PIC18F Clock < 64MHz 7750 < Cycles per second = Clock / 4 < 16.000.000 8 < Cycles per millisecond < 16.000 0 < Cycles per microsecond < 16
Definition at line 71 of file delayms.c.
Referenced by _ADBOpen(), BT_sendCommand(), CDC_init(), enc28j60Init(), if(), ILI9325_enterSleep(), ILI9325_exitSleep(), ILI9325_init(), init_CDC(), InitLCD(), Keyboard_get(), lcd_begin(), lcdi2c_clear(), lcdi2c_home(), lcdi2c_init(), mrf24j40_setup_io(), PMP_init(), SPI_begin(), ST7565_init(), SwitchDebounce(), and Tone().
{
    unsigned int i;
    
    for (i=0; i<milliseconds; i++)
        delay1ktcy(12);
}