/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/delayus.c File Reference
#include <typedef.h>
*
#include <delay.h>
*
Macros
#define __DELAYUS_C__
Functions
void Delayus (unsigned int microseconds)
Macro Definition Documentation
#define __DELAYUS_C__
Definition at line 30 of file delayus.c.
Function Documentation
void Delayus (unsigned int microseconds)
Definition at line 63 of file delayus.c.
Referenced by _lcd_begin(), _lcd_clear(), _lcd_home(), _lcd_pulseEnable(), enc28j60PhyReadH(), enc28j60PhyWrite(), lcd_begin(), lcdi2c_init(), modbuss_sendPacket(), modbuss_update(), mrf24j40_init(), mrf24j40_init_coordinator(), mrf24j40_set_channel(), OneWireReadBit(), OneWireReset(), OneWireWriteBit(), SPILoc_Read(), and SPILoc_Write().
{
    unsigned int i;
    
    for (i=0; i<microseconds; i++)
        ;
}