/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/delay.c File Reference
#include <typedef.h>
*
#include <system.c>
*
Macros
#define __DELAY_C
Functions
void Delayus (u16 us)
void Delayms (u16 ms)
Macro Definition Documentation
#define __DELAY_C
Definition at line 16 of file delay.c.
Function Documentation
void Delayms (u16 ms)
Definition at line 48 of file delay.c.
References Delayus().
{
    do
    {
        Delayus(1000); // 1 ms
    }
    while(--ms);
}
void Delayus (u16 us)
Definition at line 26 of file delay.c.
References GetCP0Count(), and GetSystemClock().
Referenced by Delayms().
{
    // CP0Count counts at half the CPU rate
    u8 Fcp0 = GetSystemClock() / 1000000 / 2; // max = 40 for 80MHz
    // get start ticks
    u32 start = GetCP0Count();
    // calculate last tick number for the given number of microseconds
    u32 stop = start + us * Fcp0;
    // wait till count reaches the stop value
    if (stop > start)
        while (GetCP0Count() < stop);
    else
        while (GetCP0Count() > start || GetCP0Count() < stop);
}