/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/digitalr.c File Reference
#include <pic18fregs.h>
*
#include <pin.h>
*
#include <digital.h>
*
Macros
#define __DIGITALR__
Functions
unsigned char digitalread (unsigned char pin)
Macro Definition Documentation
#define __DIGITALR__
Definition at line 38 of file digitalr.c.
Function Documentation
unsigned char digitalread (unsigned char pin)
Definition at line 48 of file digitalr.c.
References pA, pB, pC, pD, pE, and PWM_close().
Referenced by DCF77_scanSignal(), Keyboard_get(), Keypad_getKey(), OneWireReadBit(), OneWireReset(), pulseIn(), SPILoc_Read(), SwitchDebounce(), Led::toggle(), toggle(), touch_dataAvailable(), and touch_readData().
{
    #if defined(ANALOGWRITE) || defined(__PWM__)
    PWM_close(pin);
    #endif
    switch (port[pin])
    {
        case pA:
            if ((PORTA & mask[pin])!=0) return (1);
            else return (0);
            break;
        case pB:
            if ((PORTB & mask[pin])!=0) return (1);
            else return (0);
            break;
        case pC:
            if ((PORTC & mask[pin])!=0) return (1);
            else return (0);
            break;
        #if defined(PINGUINO4455) || defined(PINGUINO4550) || \
            defined(PINGUINO45K50) || defined(PINGUINO46J50) || \
            defined(PINGUINO47J53A) || defined(PICUNO_EQUO)
        case pD:
            if ((PORTD & mask[pin])!=0) return (1);
            else return (0);
            break;
        case pE:
            if ((PORTE & mask[pin])!=0) return (1);
            else return (0);
            break;
        #endif
    }
    return (0);
}