/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/digitalp.c File Reference
#include <pic18fregs.h>
*
#include <digital.h>
*
Macros
#define __DIGITALP__
Functions
void pinmode (unsigned char pin, unsigned char state)
Macro Definition Documentation
#define __DIGITALP__
Definition at line 38 of file digitalp.c.
Function Documentation
void pinmode (unsigned char pin, unsigned char state)
Definition at line 45 of file digitalp.c.
References pA, pB, pC, pD, and pE.
Referenced by _lcd_init(), analogwrite(), DCF77_start(), DS1306_init(), DS1306_Init(), enc28j60Init(), initSD(), Keypad_initializePins(), lcd_init(), Led::Led(), LedControl_init(), MCP23S17_init(), modbuss_configure(), PWM_setDutyCycle(), SPILoc_Init(), ST7565_init(), Stepper_init(), and touch_initTouch().
{
    switch (port[pin])
    {
        case pA:
            if (state) TRISA=TRISA | mask[pin];
            else TRISA=TRISA & (255-mask[pin]);
            break;
        case pB:
            if (state) TRISB=TRISB | mask[pin];
            else TRISB=TRISB & (255-mask[pin]);
            break;
        case pC:
            if (state) TRISC=TRISC | mask[pin];
            else TRISC=TRISC & (255-mask[pin]);
            break;
        #if defined(PINGUINO4455) || defined(PINGUINO4550) || \
            defined(PINGUINO45K50) || defined(PINGUINO46J50) || \
            defined(PINGUINO47J53A) || defined(PICUNO_EQUO)
        case pD:
            if (state) TRISD=TRISD | mask[pin];
            else TRISD=TRISD & (255-mask[pin]);
            break;
        case pE:
            if (state) TRISE=TRISE | mask[pin];
            else TRISE=TRISE & (255-mask[pin]);
            break;
        #endif
    }
}