/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/ethernet/ecn28j60.c File Reference
#include `enc28j60.h`
*
#include <digitalw.c>
*
#include <spi.c>
*
#include <delay.c>
*
Macros
#define ENC28J60_C
#define CSACTIVE digitalwrite(ENC28J60_CONTROL_CS, LOW)
#define CSPASSIVE digitalwrite(ENC28J60_CONTROL_CS, HIGH)
Functions
uint8_t enc28j60ReadOp (uint8_t op, uint8_t address)
void enc28j60WriteOp (uint8_t op, uint8_t address, uint8_t data)
void enc28j60ReadBuffer (uint16_t len, uint8_t *data)
void enc28j60WriteBuffer (uint16_t len, uint8_t *data)
void enc28j60SetBank (uint8_t address)
uint8_t enc28j60Read (uint8_t address)
void enc28j60Write (uint8_t address, uint8_t data)
void enc28j60PhyWrite (uint8_t address, uint16_t data)
uint16_t enc28j60PhyReadH (uint8_t address)
void enc28j60clkout (uint8_t clk)
void enc28j60Init (u8 *macaddr)
uint8_t enc28j60getrev (void)
uint8_t enc28j60linkup (void)
void enc28j60PacketSend (uint16_t len, uint8_t *packet)
uint8_t enc28j60hasRxPkt (void)
uint16_t enc28j60PacketReceive (uint16_t maxlen, uint8_t *packet)
Macro Definition Documentation
#define CSACTIVE digitalwrite(ENC28J60_CONTROL_CS, LOW)
Definition at line 29 of file ecn28j60.c.
Referenced by enc28j60ReadBuffer(), enc28j60ReadOp(), enc28j60WriteBuffer(), and enc28j60WriteOp().
#define CSPASSIVE digitalwrite(ENC28J60_CONTROL_CS, HIGH)
Definition at line 30 of file ecn28j60.c.
Referenced by enc28j60Init(), enc28j60ReadBuffer(), enc28j60ReadOp(), enc28j60WriteBuffer(), and enc28j60WriteOp().
#define ENC28J60_C
Definition at line 18 of file ecn28j60.c.
Function Documentation
void enc28j60clkout (uint8_t clk)
Definition at line 154 of file ecn28j60.c.
References ECOCON, and enc28j60Write().
{
        //setup clkout: 2 is 12.5MHz:
    enc28j60Write(ECOCON, clk & 0x7);
}
uint8_t enc28j60getrev (void)
Definition at line 250 of file ecn28j60.c.
References enc28j60Read(), and EREVID.
{
    return(enc28j60Read(EREVID));
}
uint8_t enc28j60hasRxPkt (void)
Definition at line 290 of file ecn28j60.c.
References enc28j60Read(), and EPKTCNT.
{
    if(enc28j60Read(EPKTCNT) ==0){
        return(0);
        }
        return(1);
}
void enc28j60Init (u8 * macaddr)
Definition at line 159 of file ecn28j60.c.
References CSPASSIVE, Delayms(), ECON1, ECON1_RXEN, EIE, ENC28J60_BIT_FIELD_SET, ENC28J60_SOFT_RESET, enc28j60PhyWrite(), enc28j60SetBank(), enc28j60Write(), enc28j60WriteOp(), EPMCSH, EPMCSL, EPMM0, EPMM1, ERXFCON, ERXFCON_CRCEN, ERXNDH, ERXNDL, ERXRDPTH, ERXRDPTL, ERXSTH, ERXSTL, ETXNDH, ETXNDL, ETXSTH, ETXSTL, MAADR0, MAADR1, MAADR2, MAADR3, MAADR4, MAADR5, MABBIPG, MACON1, MACON1_MARXEN, MACON1_RXPAUS, MACON1_TXPAUS, MACON2, MACON3, MACON3_FRMLNEN, MACON3_PADCFG0, MACON3_TXCRCEN, MAIPGH, MAIPGL, MAMXFLH, MAMXFLL, MAX_FRAMELEN, OUTPUT, PHCON2, PHCON2_HDLDIS, pinmode(), RXSTART_INIT, RXSTOP_INIT, SPI_init(), TXSTART_INIT, and TXSTOP_INIT.
{
    // initialize I/O
    // ss as output:
    pinmode(ENC28J60_CONTROL_CS, OUTPUT);
    CSPASSIVE; // ss=0
    // init SPI module
    SPI_init();
    
    // perform system reset
    enc28j60WriteOp(ENC28J60_SOFT_RESET, 0,
      ENC28J60_SOFT_RESET);
    Delayms(50);
    // check CLKRDY bit to see if reset is complete
    // The CLKRDY does not work. See Rev. B4 Silicon Errata point. Just wait.
    //while(!(enc28j60Read(ESTAT) & ESTAT_CLKRDY));
    // do bank 0 stuff
    // initialize receive buffer
    // 16-bit transfers, must write low byte first
    // set receive buffer start address
    NextPacketPtr = RXSTART_INIT;
    // Rx start
    enc28j60Write(ERXSTL, RXSTART_INIT&0xFF);
    enc28j60Write(ERXSTH, RXSTART_INIT>>8);
    // set receive pointer address
    enc28j60Write(ERXRDPTL, RXSTART_INIT&0xFF);
    enc28j60Write(ERXRDPTH, RXSTART_INIT>>8);
    // RX end
    enc28j60Write(ERXNDL, RXSTOP_INIT&0xFF);
    enc28j60Write(ERXNDH, RXSTOP_INIT>>8);
    // TX start
    enc28j60Write(ETXSTL, TXSTART_INIT&0xFF);
    enc28j60Write(ETXSTH, TXSTART_INIT>>8);
    // TX end
    enc28j60Write(ETXNDL, TXSTOP_INIT&0xFF);
    enc28j60Write(ETXNDH, TXSTOP_INIT>>8);
    // do bank 1 stuff, packet filter:
        // For broadcast packets we allow only ARP packtets
        // All other packets should be unicast only for our mac (MAADR)
        //
        // The pattern to match on is therefore
        // Type ETH.DST
        // ARP BROADCAST
        // 06 08 -- ff ff ff ff ff ff -> ip checksum for theses bytes=f7f9
        // in binary these poitions are:11 0000 0011 1111
        // This is hex 303F->EPMM0=0x3f,EPMM1=0x30
    //enc28j60Write(ERXFCON, ERXFCON_UCEN|ERXFCON_CRCEN|ERXFCON_PMEN);
    enc28j60Write(ERXFCON, ERXFCON_CRCEN);
    enc28j60Write(EPMM0, 0x3f);
    enc28j60Write(EPMM1, 0x30);
    enc28j60Write(EPMCSL, 0xf9);
    enc28j60Write(EPMCSH, 0xf7);
        //
        //
    // do bank 2 stuff
    // enable MAC receive
    enc28j60Write(MACON1, MACON1_MARXEN|
      MACON1_TXPAUS|MACON1_RXPAUS);
    // bring MAC out of reset
    enc28j60Write(MACON2, 0x00);
    // enable automatic padding to 60bytes and CRC operations
    enc28j60WriteOp(ENC28J60_BIT_FIELD_SET,
      MACON3, MACON3_PADCFG0|MACON3_TXCRCEN|
      MACON3_FRMLNEN);
    // set inter-frame gap (non-back-to-back)
    enc28j60Write(MAIPGL, 0x12);
    enc28j60Write(MAIPGH, 0x0C);
    // set inter-frame gap (back-to-back)
    enc28j60Write(MABBIPG, 0x12);
    // Set the maximum packet size which the controller will accept
        // Do not send packets longer than MAX_FRAMELEN:
    enc28j60Write(MAMXFLL, MAX_FRAMELEN&0xFF);
    enc28j60Write(MAMXFLH, MAX_FRAMELEN>>8);
    // do bank 3 stuff
        // write MAC address
        // NOTE: MAC address in ENC28J60 is byte-backward
        enc28j60Write(MAADR5, macaddr[0]);
        enc28j60Write(MAADR4, macaddr[1]);
        enc28j60Write(MAADR3, macaddr[2]);
        enc28j60Write(MAADR2, macaddr[3]);
        enc28j60Write(MAADR1, macaddr[4]);
        enc28j60Write(MAADR0, macaddr[5]);
    // no loopback of transmitted frames
    enc28j60PhyWrite(PHCON2, PHCON2_HDLDIS);
    // switch to bank 0
    enc28j60SetBank(ECON1);
    // enable interrutps
    enc28j60WriteOp(ENC28J60_BIT_FIELD_SET,
      EIE, 0);
    //enc28j60WriteOp(ENC28J60_BIT_FIELD_SET, EIE, EIE_INTIE|EIE_PKTIE);
    // enable packet reception
    enc28j60WriteOp(ENC28J60_BIT_FIELD_SET,
      ECON1, ECON1_RXEN);
}
uint8_t enc28j60linkup (void)
Definition at line 256 of file ecn28j60.c.
References enc28j60PhyReadH(), and PHSTAT2.
{
        // bit 10 (= bit 3 in upper reg)
    return(enc28j60PhyReadH(PHSTAT2) && 4);
}
uint16_t enc28j60PacketReceive (uint16_t maxlen, uint8_t * packet)
Definition at line 303 of file ecn28j60.c.
References ECON2, ECON2_PKTDEC, ENC28J60_BIT_FIELD_SET, ENC28J60_READ_BUF_MEM, enc28j60Read(), enc28j60ReadBuffer(), enc28j60ReadOp(), enc28j60Write(), enc28j60WriteOp(), EPKTCNT, ERDPTH, ERDPTL, ERXRDPTH, ERXRDPTL, RXSTART_INIT, and RXSTOP_INIT.
{
    uint16_t rxstat;
    uint16_t len;
    // check if a packet has been received and buffered
    //if(!(enc28j60Read(EIR) & EIR_PKTIF)){
        // The above does not work. See Rev. B4 Silicon Errata point 6.
    if(enc28j60Read(EPKTCNT) ==0){
        return(0);
        }
    // Set the read pointer to the start of the received packet
    enc28j60Write(ERDPTL, (NextPacketPtr &0xFF));
    enc28j60Write(ERDPTH, (NextPacketPtr)>>8);
    // read the next packet pointer
    NextPacketPtr = enc28j60ReadOp(ENC28J60_READ_BUF_MEM, 0);
    NextPacketPtr |= enc28j60ReadOp(ENC28J60_READ_BUF_MEM, 0)<<8;
    // read the packet length (see datasheet page 43)
    len = enc28j60ReadOp(ENC28J60_READ_BUF_MEM, 0);
    len |= enc28j60ReadOp(ENC28J60_READ_BUF_MEM, 0)<<8;
        len-=4; //remove the CRC count
    // read the receive status (see datasheet page 43)
    rxstat = enc28j60ReadOp(ENC28J60_READ_BUF_MEM, 0);
    rxstat |= ((uint16_t)enc28j60ReadOp(
      ENC28J60_READ_BUF_MEM, 0))<<8;
    // limit retrieve length
        if (len>maxlen-1){
                len=maxlen-1;
        }
        // check CRC and symbol errors (see datasheet page 44, table 7-3):
        // The ERXFCON.CRCEN is set by default. Normally we should not
        // need to check this.
        if ((rxstat & 0x80)==0){
                // invalid
                len=0;
        }else{
                // copy the packet from the receive buffer
                enc28j60ReadBuffer(len, packet);
        }
    // Move the RX read pointer to the start of the next received packet
    // This frees the memory we just read out
    enc28j60Write(ERXRDPTL, (NextPacketPtr &0xFF));
    enc28j60Write(ERXRDPTH, (NextPacketPtr)>>8);
        // Move the RX read pointer to the start of the next received packet
        // This frees the memory we just read out.
        // However, compensate for the errata point 13, rev B4: enver write an even address!
        if ((NextPacketPtr - 1 < RXSTART_INIT)
                || (NextPacketPtr -1 > RXSTOP_INIT)) {
                enc28j60Write(ERXRDPTL, (RXSTOP_INIT)&0xFF);
                enc28j60Write(ERXRDPTH, (RXSTOP_INIT)>>8);
        } else {
                enc28j60Write(ERXRDPTL, (NextPacketPtr-1)&0xFF);
                enc28j60Write(ERXRDPTH, (NextPacketPtr-1)>>8);
        }
    // decrement the packet counter indicate we are done with this packet
    enc28j60WriteOp(ENC28J60_BIT_FIELD_SET,
      ECON2, ECON2_PKTDEC);
    return(len);
}
void enc28j60PacketSend (uint16_t len, uint8_t * packet)
Definition at line 262 of file ecn28j60.c.
References ECON1, ECON1_TXRST, ECON1_TXRTS, ENC28J60_BIT_FIELD_CLR, ENC28J60_BIT_FIELD_SET, ENC28J60_READ_CTRL_REG, ENC28J60_WRITE_BUF_MEM, enc28j60ReadOp(), enc28j60Write(), enc28j60WriteBuffer(), enc28j60WriteOp(), ETXNDH, ETXNDL, EWRPTH, EWRPTL, and TXSTART_INIT.
Referenced by make_arp_answer_from_request(), make_echo_reply_from_request(), and make_udp_reply_from_request().
{
        // Check no transmit in progress
        while (enc28j60ReadOp(ENC28J60_READ_CTRL_REG,
      ECON1) & ECON1_TXRTS)
        {
                // Reset the transmit logic problem. See Rev. B4 Silicon Errata point 12.
                //if((enc28j60Read(EIR) & EIR_TXERIF))
                {
                        enc28j60WriteOp(ENC28J60_BIT_FIELD_SET,
      ECON1, ECON1_TXRST);
                        enc28j60WriteOp(ENC28J60_BIT_FIELD_CLR,
      ECON1, ECON1_TXRST);
                }
        }
    // Set the write pointer to start of transmit buffer area
    enc28j60Write(EWRPTL, TXSTART_INIT&0xFF);
    enc28j60Write(EWRPTH, TXSTART_INIT>>8);
    // Set the TXND pointer to correspond to the packet size given
    enc28j60Write(ETXNDL, (TXSTART_INIT+len)&0xFF);
    enc28j60Write(ETXNDH, (TXSTART_INIT+len)>>8);
    // write per-packet control byte (0x00 means use macon3 settings)
    enc28j60WriteOp(ENC28J60_WRITE_BUF_MEM, 0, 0x00);
    // copy the packet into the transmit buffer
    enc28j60WriteBuffer(len, packet);
    // send the contents of the transmit buffer onto the network
    enc28j60WriteOp(ENC28J60_BIT_FIELD_SET,
      ECON1, ECON1_TXRTS);
}
uint16_t enc28j60PhyReadH (uint8_t address)
Definition at line 136 of file ecn28j60.c.
References Delayus(), enc28j60Read(), enc28j60Write(), MICMD, MICMD_MIIRD, MIRDH, MIREGADR, MISTAT, and MISTAT_BUSY.
Referenced by enc28j60linkup().
{
    // Set the right address and start the register read operation
    enc28j60Write(MIREGADR, address);
    enc28j60Write(MICMD, MICMD_MIIRD);
        //_delay_loop_1(40); // 10us
        Delayus(15);
    // wait until the PHY read completes
    while(enc28j60Read(MISTAT) & MISTAT_BUSY);
    // reset reading bit
    enc28j60Write(MICMD, 0x00);
    
    return (enc28j60Read(MIRDH));
}
void enc28j60PhyWrite (uint8_t address, uint16_t data)
Definition at line 122 of file ecn28j60.c.
References Delayus(), enc28j60Read(), enc28j60Write(), MIREGADR, MISTAT, MISTAT_BUSY, MIWRH, and MIWRL.
Referenced by enc28j60Init().
{
        // set the PHY register address
        enc28j60Write(MIREGADR, address);
        // write the PHY data
        enc28j60Write(MIWRL, data);
        enc28j60Write(MIWRH, data>>8);
        // wait until the PHY write completes
        while(enc28j60Read(MISTAT) & MISTAT_BUSY){
                Delayus(15);
        }
}
uint8_t enc28j60Read (uint8_t address)
Definition at line 106 of file ecn28j60.c.
References ENC28J60_READ_CTRL_REG, enc28j60ReadOp(), and enc28j60SetBank().
Referenced by enc28j60getrev(), enc28j60hasRxPkt(), enc28j60PacketReceive(), enc28j60PhyReadH(), and enc28j60PhyWrite().
{
        // set the bank
        enc28j60SetBank(address);
        // do the read
        return enc28j60ReadOp(ENC28J60_READ_CTRL_REG, address);
}
void enc28j60ReadBuffer (uint16_t len, uint8_t * data)
Definition at line 61 of file ecn28j60.c.
References CSACTIVE, CSPASSIVE, ENC28J60_READ_BUF_MEM, SPI_read(), and SPI_write().
Referenced by enc28j60PacketReceive().
{
uint8_t received_byte;
        CSACTIVE;
        // issue read command
        SPI_write(ENC28J60_READ_BUF_MEM);
        while(len)
        {
                len--;
                // read data
                received_byte=SPI_read();
                *data = received_byte;
                data++;
        }
        *data='\0';
        CSPASSIVE;
}
uint8_t enc28j60ReadOp (uint8_t op, uint8_t address)
Definition at line 32 of file ecn28j60.c.
References ADDR_MASK, CSACTIVE, CSPASSIVE, SPI_read(), and SPI_write().
Referenced by enc28j60PacketReceive(), enc28j60PacketSend(), and enc28j60Read().
{
uint8_t received_byte;
        CSACTIVE;
        // issue read command
        SPI_write(op | (address & ADDR_MASK));
        // read data
        received_byte=SPI_read();
        // do dummy read if needed (for mac and mii, see datasheet page 29)
        if(address & 0x80)
        {
            received_byte=SPI_read();
        }
        // release CS
        CSPASSIVE;
        return(received_byte);
}
void enc28j60SetBank (uint8_t address)
Definition at line 94 of file ecn28j60.c.
References BANK_MASK, ECON1, ECON1_BSEL0, ECON1_BSEL1, ENC28J60_BIT_FIELD_CLR, ENC28J60_BIT_FIELD_SET, and enc28j60WriteOp().
Referenced by enc28j60Init(), enc28j60Read(), and enc28j60Write().
{
        // set the bank (if needed)
        if((address & BANK_MASK) != Enc28j60Bank)
        {
                // set the bank
                enc28j60WriteOp(ENC28J60_BIT_FIELD_CLR,
      ECON1, (ECON1_BSEL1|ECON1_BSEL0));
                enc28j60WriteOp(ENC28J60_BIT_FIELD_SET,
      ECON1, (address & BANK_MASK)>>5);
                Enc28j60Bank = (address & BANK_MASK);
        }
}
void enc28j60Write (uint8_t address, uint8_t data)
Definition at line 114 of file ecn28j60.c.
References ENC28J60_WRITE_CTRL_REG, enc28j60SetBank(), and enc28j60WriteOp().
Referenced by enc28j60clkout(), enc28j60Init(), enc28j60PacketReceive(), enc28j60PacketSend(), enc28j60PhyReadH(), and enc28j60PhyWrite().
{
        // set the bank
        enc28j60SetBank(address);
        // do the write
        enc28j60WriteOp(ENC28J60_WRITE_CTRL_REG, address, data);
}
void enc28j60WriteBuffer (uint16_t len, uint8_t * data)
Definition at line 79 of file ecn28j60.c.
References CSACTIVE, CSPASSIVE, ENC28J60_WRITE_BUF_MEM, and SPI_write().
Referenced by enc28j60PacketSend().
{
        CSACTIVE;
        // issue write command
        SPI_write(ENC28J60_WRITE_BUF_MEM);
        while(len)
        {
                len--;
                // write data
                SPI_write(*data);
                data++;
        }
        CSPASSIVE;
}
void enc28j60WriteOp (uint8_t op, uint8_t address, uint8_t data)
Definition at line 51 of file ecn28j60.c.
References ADDR_MASK, CSACTIVE, CSPASSIVE, and SPI_write().
Referenced by enc28j60Init(), enc28j60PacketReceive(), enc28j60PacketSend(), enc28j60SetBank(), and enc28j60Write().
{
        CSACTIVE;
        // issue write command
        SPI_write(op | (address & ADDR_MASK));
        // write data
        SPI_write(data);
        CSPASSIVE;
}