/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/eeprom.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <macro.h>
*
Macros
#define __EEPROM_C
Functions
u8 EEPROM_read8 (u8 address)
u16 EEPROM_read16 (u8 address)
void EEPROM_write8 (u8 address, u8 mydata)
void EEPROM_write16 (u8 address, u16 mydata)
Macro Definition Documentation
#define __EEPROM_C
Definition at line 29 of file eeprom.c.
Function Documentation
u16 EEPROM_read16 (u8 address)
---------- myEEPROM_read16()
---------- Routine de lecture d'un 16-bit en eeprom
Definition at line 62 of file eeprom.c.
References EEPROM_read8().
{
    u8 hibyte;
    u8 lobyte;
    u16 mydata;
    hibyte = EEPROM_read8(address);
    lobyte = EEPROM_read8(address+1);
    mydata = (hibyte << 8) | lobyte;
    return mydata;
}
u8 EEPROM_read8 (u8 address)
---------- myEEPROM_read8()
---------- Routine de lecture en eeprom
---------- (c) Raphael Wimmer. Licensed under GNU GPL v2 or higher
Definition at line 47 of file eeprom.c.
Referenced by EEPROM_read16().
{
    EEADR = address;
    EECON1bits.EEPGD = 0;
    EECON1bits.CFGS = 0;
    EECON1bits.RD = 1;
    return EEDATA;
}
void EEPROM_write16 (u8 address, u16 mydata)
---------- myEEPROM_write16()
---------- Routine d'écriture d'un 16-bit en eeprom
Definition at line 113 of file eeprom.c.
References EEPROM_write8(), high8, and low8.
{
    //u8 hibyte;
    //u8 lobyte;
    //lobyte = (u8)mydata;
    //hibyte = (u8)(mydata >> 8);
    EEPROM_write8(address, high8(mydata));
    EEPROM_write8(address+1, low8(mydata));
}
void EEPROM_write8 (u8 address, u8 mydata)
---------- myEEPROM_write8()
---------- Routine d'écriture d'un 8-bit en eeprom
---------- (c) Raphael Wimmer. Licensed under GNU GPL v2 or higher
Definition at line 81 of file eeprom.c.
Referenced by EEPROM_write16().
{
    EEADR = address;
    EEDATA = mydata;
    // start write sequence as described in datasheet, page 91
    EECON1bits.EEPGD = 0;
    EECON1bits.CFGS = 0;
    EECON1bits.WREN = 1; // enable writes to data EEPROM
    INTCONbits.GIE = 0; // disable interrupts
    EECON2 = 0x55;
    EECON2 = 0x0AA;
    EECON1bits.WR = 1; // start writing
    while (EECON1bits.WR)
    {
        Nop();
    }
    if (EECON1bits.WRERR)
    {
    #ifdef DEBUG
        serial_printf("Writing Error !");
    #endif
    }
    EECON1bits.WREN = 0;
    INTCONbits.GIE = 1; // enable interrupts
}