/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/sd/ff.h File Reference
#include `integer.h`
*
#include `ffconf.h`
*
Data Structures
struct FATFS
struct FIL
struct DIR
struct FILINFO
Macros
#define _FATFS 6502	/* Revision ID */
#define LD2PD(vol) (vol)	/* Each logical drive is bound to the same physical drive number */
#define LD2PT(vol) 0		/* Always mounts the 1st partition or in SFD */
#define _T(x) x
#define _TEXT(x) x
#define f_eof(fp) (((fp)->fptr == (fp)->fsize) ? 1 : 0)
#define f_error(fp) (((fp)->flag & FA__ERROR) ? 1 : 0)
#define f_tell(fp) ((fp)->fptr)
#define f_size(fp) ((fp)->fsize)
#define EOF (-1)
#define FA_READ 0x01
#define FA_OPEN_EXISTING 0x00
#define FA__ERROR 0x80
#define FA_WRITE 0x02
#define FA_CREATE_NEW 0x04
#define FA_CREATE_ALWAYS 0x08
#define FA_OPEN_ALWAYS 0x10
#define FA__WRITTEN 0x20
#define FA__DIRTY 0x40
#define FS_FAT12 1
#define FS_FAT16 2
#define FS_FAT32 3
#define AM_RDO 0x01	/* Read only */
#define AM_HID 0x02	/* Hidden */
#define AM_SYS 0x04	/* System */
#define AM_VOL 0x08	/* Volume label */
#define AM_LFN 0x0F	/* LFN entry */
#define AM_DIR 0x10	/* Directory */
#define AM_ARC 0x20	/* Archive */
#define AM_MASK 0x3F	/* Mask of defined bits */
#define CREATE_LINKMAP 0xFFFFFFFF
#define LD_WORD(ptr) (PF_WORD)(((PF_WORD)*((PF_BYTE*)(ptr)+1)<<8)|(PF_WORD)*(PF_BYTE*)(ptr))
#define LD_DWORD(ptr) (DWORD)(((DWORD)*((PF_BYTE*)(ptr)+3)<<24)|((DWORD)*((PF_BYTE*)(ptr)+2)<<16)|((PF_WORD)*((PF_BYTE*)(ptr)+1)<<8)|*(PF_BYTE*)(ptr))
#define ST_WORD(ptr, val) *(PF_BYTE*)(ptr)=(PF_BYTE)(val); *((PF_BYTE*)(ptr)+1)=(PF_BYTE)((PF_WORD)(val)>>8)
#define ST_DWORD(ptr, val) *(PF_BYTE*)(ptr)=(PF_BYTE)(val); *((PF_BYTE*)(ptr)+1)=(PF_BYTE)((PF_WORD)(val)>>8); *((PF_BYTE*)(ptr)+2)=(PF_BYTE)((DWORD)(val)>>16); *((PF_BYTE*)(ptr)+3)=(PF_BYTE)((DWORD)(val)>>24)
Typedefs
typedef char TCHAR
Enumerations
enum FRESULT {
*
FR_OK = 0,
FR_DISK_ERR,
FR_NOT_READY,
FR_NO_FILE,
*
FR_NO_PATH,
FR_NOT_OPENED,
FR_NOT_ENABLED,
FR_NO_FILESYSTEM,
*
FR_OK = 0,
FR_NOT_READY,
FR_NO_FILE,
FR_NO_PATH,
*
FR_INVALID_NAME,
FR_INVALID_DRIVE,
FR_DENIED,
FR_EXIST,
*
FR_RW_ERROR,
FR_WRITE_PROTECTED,
FR_NOT_ENABLED,
FR_NO_FILESYSTEM,
*
FR_INVALID_OBJECT,
FR_MKFS_ABORTED,
FR_OK = 0,
FR_DISK_ERR,
*
FR_INT_ERR,
FR_NOT_READY,
FR_NO_FILE,
FR_NO_PATH,
*
FR_INVALID_NAME,
FR_DENIED,
FR_EXIST,
FR_INVALID_OBJECT,
*
FR_WRITE_PROTECTED,
FR_INVALID_DRIVE,
FR_NOT_ENABLED,
FR_NO_FILESYSTEM,
*
FR_MKFS_ABORTED,
FR_TIMEOUT,
FR_LOCKED,
FR_NOT_ENOUGH_CORE,
*
FR_TOO_MANY_OPEN_FILES,
FR_INVALID_PARAMETER
 }
Functions
FRESULT f_mount (PF_BYTE, FATFS *)
FRESULT f_open (FIL *, const TCHAR *, PF_BYTE)
FRESULT f_read (FIL *, void *, UINT, UINT *)
FRESULT f_lseek (FIL *, DWORD)
FRESULT f_close (FIL *)
FRESULT f_opendir (DIR *, const TCHAR *)
FRESULT f_readdir (DIR *, FILINFO *)
FRESULT f_stat (const TCHAR *, FILINFO *)
FRESULT f_write (FIL *, const void *, UINT, UINT *)
FRESULT f_getfree (const TCHAR *, DWORD *, FATFS **)
FRESULT f_truncate (FIL *)
FRESULT f_sync (FIL *)
FRESULT f_unlink (const TCHAR *)
FRESULT f_mkdir (const TCHAR *)
FRESULT f_chmod (const TCHAR *, PF_BYTE, PF_BYTE)
FRESULT f_utime (const TCHAR *, const FILINFO *)
FRESULT f_rename (const TCHAR *, const TCHAR *)
FRESULT f_chdrive (PF_BYTE)
FRESULT f_chdir (const TCHAR *)
FRESULT f_getcwd (TCHAR *, UINT)
FRESULT f_forward (FIL *, UINT(*)(const PF_BYTE *, UINT), UINT, UINT *)
FRESULT f_mkfs (PF_BYTE, PF_BYTE, UINT)
FRESULT f_fdisk (PF_BYTE, const DWORD[], void *)
int f_putc (TCHAR, FIL *)
int f_puts (const TCHAR *, FIL *)
int f_printf (FIL *, const TCHAR *,...)
TCHAR * f_gets (TCHAR *, int, FIL *)
DWORD get_fattime (void)
Macro Definition Documentation
#define _FATFS 6502	/* Revision ID */
Definition at line 18 of file ff.h.
#define _T(x) x
Definition at line 67 of file ff.h.
#define _TEXT(x) x
Definition at line 68 of file ff.h.
#define AM_ARC 0x20	/* Archive */
Definition at line 309 of file ff.h.
#define AM_DIR 0x10	/* Directory */
Definition at line 308 of file ff.h.
#define AM_HID 0x02	/* Hidden */
Definition at line 304 of file ff.h.
#define AM_LFN 0x0F	/* LFN entry */
Definition at line 307 of file ff.h.
#define AM_MASK 0x3F	/* Mask of defined bits */
Definition at line 310 of file ff.h.
#define AM_RDO 0x01	/* Read only */
Definition at line 303 of file ff.h.
#define AM_SYS 0x04	/* System */
Definition at line 305 of file ff.h.
#define AM_VOL 0x08	/* Volume label */
Definition at line 306 of file ff.h.
#define CREATE_LINKMAP 0xFFFFFFFF
Definition at line 314 of file ff.h.
Referenced by f_lseek().
#define EOF (-1)
Definition at line 239 of file ff.h.
#define f_eof(fp) (((fp)->fptr == (fp)->fsize) ? 1 : 0)
Definition at line 233 of file ff.h.
#define f_error(fp) (((fp)->flag & FA__ERROR) ? 1 : 0)
Definition at line 234 of file ff.h.
#define f_size(fp) ((fp)->fsize)
Definition at line 236 of file ff.h.
#define f_tell(fp) ((fp)->fptr)
Definition at line 235 of file ff.h.
#define FA__DIRTY 0x40
Definition at line 290 of file ff.h.
Referenced by f_lseek(), f_read(), f_sync(), and f_write().
#define FA__ERROR 0x80
Definition at line 282 of file ff.h.
#define FA__WRITTEN 0x20
Definition at line 289 of file ff.h.
#define FA_CREATE_ALWAYS 0x08
Definition at line 287 of file ff.h.
#define FA_CREATE_NEW 0x04
Definition at line 286 of file ff.h.
#define FA_OPEN_ALWAYS 0x10
Definition at line 288 of file ff.h.
#define FA_OPEN_EXISTING 0x00
Definition at line 281 of file ff.h.
#define FA_READ 0x01
Definition at line 280 of file ff.h.
#define FA_WRITE 0x02
Definition at line 285 of file ff.h.
#define FS_FAT12 1
Definition at line 296 of file ff.h.
#define FS_FAT16 2
Definition at line 297 of file ff.h.
#define FS_FAT32 3
Definition at line 298 of file ff.h.
#define LD2PD(vol) (vol)	/* Each logical drive is bound to the same physical drive number */
Definition at line 45 of file ff.h.
#define LD2PT(vol) 0		/* Always mounts the 1st partition or in SFD */
Definition at line 46 of file ff.h.
#define LD_DWORD(ptr) (DWORD)(((DWORD)*((PF_BYTE*)(ptr)+3)<<24)|((DWORD)*((PF_BYTE*)(ptr)+2)<<16)|((PF_WORD)*((PF_BYTE*)(ptr)+1)<<8)|*(PF_BYTE*)(ptr))
Definition at line 328 of file ff.h.
#define LD_WORD(ptr) (PF_WORD)(((PF_WORD)*((PF_BYTE*)(ptr)+1)<<8)|(PF_WORD)*(PF_BYTE*)(ptr))
Definition at line 327 of file ff.h.
#define ST_DWORD(ptr, val) *(PF_BYTE*)(ptr)=(PF_BYTE)(val); *((PF_BYTE*)(ptr)+1)=(PF_BYTE)((PF_WORD)(val)>>8); *((PF_BYTE*)(ptr)+2)=(PF_BYTE)((DWORD)(val)>>16); *((PF_BYTE*)(ptr)+3)=(PF_BYTE)((DWORD)(val)>>24)
Definition at line 330 of file ff.h.
#define ST_WORD(ptr, val) *(PF_BYTE*)(ptr)=(PF_BYTE)(val); *((PF_BYTE*)(ptr)+1)=(PF_BYTE)((PF_WORD)(val)>>8)
Definition at line 329 of file ff.h.
Typedef Documentation
typedef char TCHAR
Definition at line 66 of file ff.h.
Enumeration Type Documentation
enum FRESULT
Enumerator
FR_OK
FR_DISK_ERR
FR_NOT_READY
FR_NO_FILE
FR_NO_PATH
FR_NOT_OPENED
FR_NOT_ENABLED
FR_NO_FILESYSTEM
FR_OK
FR_NOT_READY
FR_NO_FILE
FR_NO_PATH
FR_INVALID_NAME
FR_INVALID_DRIVE
FR_DENIED
FR_EXIST
FR_RW_ERROR
FR_WRITE_PROTECTED
FR_NOT_ENABLED
FR_NO_FILESYSTEM
FR_INVALID_OBJECT
FR_MKFS_ABORTED
FR_OK
FR_DISK_ERR
FR_INT_ERR
FR_NOT_READY
FR_NO_FILE
FR_NO_PATH
FR_INVALID_NAME
FR_DENIED
FR_EXIST
FR_INVALID_OBJECT
FR_WRITE_PROTECTED
FR_INVALID_DRIVE
FR_NOT_ENABLED
FR_NO_FILESYSTEM
FR_MKFS_ABORTED
FR_TIMEOUT
FR_LOCKED
FR_NOT_ENOUGH_CORE
FR_TOO_MANY_OPEN_FILES
FR_INVALID_PARAMETER
Definition at line 177 of file ff.h.
             {
    FR_OK = 0, /* (0) Succeeded */
    FR_DISK_ERR, /* (1) A hard error occured in the low level disk I/O layer */
    FR_INT_ERR, /* (2) Assertion failed */
    FR_NOT_READY, /* (3) The physical drive cannot work */
    FR_NO_FILE, /* (4) Could not find the file */
    FR_NO_PATH, /* (5) Could not find the path */
    FR_INVALID_NAME, /* (6) The path name format is invalid */
    FR_DENIED, /* (7) Acces denied due to prohibited access or directory full */
    FR_EXIST, /* (8) Acces denied due to prohibited access */
    FR_INVALID_OBJECT, /* (9) The file/directory object is invalid */
    FR_WRITE_PROTECTED, /* (10) The physical drive is write protected */
    FR_INVALID_DRIVE, /* (11) The logical drive number is invalid */
    FR_NOT_ENABLED, /* (12) The volume has no work area */
    FR_NO_FILESYSTEM, /* (13) There is no valid FAT volume */
    FR_MKFS_ABORTED, /* (14) The f_mkfs() aborted due to any parameter error */
    FR_TIMEOUT, /* (15) Could not get a grant to access the volume within defined
       period */
    FR_LOCKED, /* (16) The operation is rejected according to the file shareing policy
       */
    FR_NOT_ENOUGH_CORE, /* (17) LFN working buffer could not be allocated */
    FR_TOO_MANY_OPEN_FILES, /* (18) Number of open files > _FS_SHARE */
    FR_INVALID_PARAMETER /* (19) Given parameter is invalid */
} FRESULT;
Function Documentation
FRESULT f_chdir (const TCHAR *)
FRESULT f_chdrive (PF_BYTE)
FRESULT f_chmod (const TCHAR * , PF_BYTE , PF_BYTE)
Definition at line 1550 of file tff.c.
References _FS_RPATH, AM_ARC, AM_HID, AM_RDO, AM_SYS, DEF_NAMEBUF, dir, DIR::dir, DIR_Attr, dj, DIR::fn, FR_INVALID_NAME, FR_OK, FREE_BUF, DIR::fs, INIT_BUF, LEAVE_FF, NS, res, and FATFS::wflag.
{
// FRESULT res;
// DIR dj;
// byte *dir;
// char fn[8+3+1];
    res = auto_mount(&path, 1);
    if (res == FR_OK) {
        res = trace_path(&dj, fn, path, &dir); /* Trace the file path */
        if (res == FR_OK) { /* Trace completed */
            if (!dir) {
                res = FR_INVALID_NAME; /* Root directory */
            } else {
                mask &= AM_RDO|AM_HID|AM_SYS|AM_ARC; /* Valid attribute mask */
                dir[DIR_Attr] = (value & mask) | (dir[DIR_Attr] & (
      byte)~mask); /* Apply attribute change */
                res = sync();
            }
        }
    }
    return res;
}
FRESULT f_close (FIL *)
Definition at line 1098 of file tff.c.
References f_sync(), FR_OK, FIL::fs, FIL::id, LEAVE_FF, NULL, and res.
{
// FRESULT res;
#if !_FS_READONLY
    res = f_sync(fp);
#else
    res = validate(fp->fs, fp->id);
#endif
    if (res == FR_OK) fp->fs = NULL;
    return res;
}
FRESULT f_fdisk (PF_BYTE , const DWORD [], void *)
FRESULT f_forward (FIL * , UINT(*)(const PF_BYTE *, UINT) , UINT , UINT *)
FRESULT f_getcwd (TCHAR * , UINT)
FRESULT f_getfree (const TCHAR * , DWORD * , FATFS **)
Definition at line 1359 of file tff.c.
References _FAT32, FATFS::fatbase, FR_DISK_ERR, FR_INT_ERR, FR_OK, FR_RW_ERROR, FATFS::free_clust, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, FATFS::fsi_flag, get_fat(), LD_DWORD, LD_WORD, LEAVE_FF, FATFS::max_clust, res, SS, and FATFS::win.
Referenced by sd_status().
{
// FRESULT res;
    FATFS *fs;
    dword n, sect;
    CLUST clust;
    byte fat, f, *p;
    /* Get drive number */
    res = auto_mount(&drv, 0);
    if (res != FR_OK) return res;
    *fatfs = fs = FatFs;
    /* If number of free cluster is valid, return it without cluster scan. */
    if (fs->free_clust <= fs->max_clust - 2) {
        *nclust = fs->free_clust;
        return FR_OK;
    }
    /* Get number of free clusters */
    fat = fs->fs_type;
    n = 0;
    if (fat == FS_FAT12) {
        clust = 2;
        do {
            if ((word)get_cluster(clust) == 0) n++;
        } while (++clust < fs->max_clust);
    } else {
        clust = fs->max_clust;
        sect = fs->fatbase;
        f = 0; p = 0;
        do {
            if (!f) {
                if (!move_window(sect++)) return FR_RW_ERROR;
                p = fs->win;
            }
            if (!_FAT32 || fat == FS_FAT16) {
                if (LD_WORD(p) == 0) n++;
                p += 2; f += 1;
            } else {
                if (LD_DWORD(p) == 0) n++;
                p += 4; f += 2;
            }
        } while (--clust);
    }
    fs->free_clust = n;
#if _USE_FSINFO
    if (fat == FS_FAT32) fs->fsi_flag = 1;
#endif
    *nclust = n;
    return FR_OK;
}
TCHAR* f_gets (TCHAR * , int , FIL *)
FRESULT f_lseek (FIL * , DWORD)
Definition at line 1122 of file tff.c.
References _FS_READONLY, ABORT, FIL::buf, FIL::cltbl, FIL::clust, clust2sect(), CREATE_LINKMAP, FIL::csect, FATFS::csize, FIL::curr_clust, disk_read(), disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__ERROR, FA__WRITTEN, FA_WRITE, FIL::flag, FIL::fptr, FR_DISK_ERR, FR_INT_ERR, FR_NOT_ENOUGH_CORE, FR_OK, FR_RW_ERROR, FIL::fs, FIL::fsize, get_fat(), FIL::id, if(), LEAVE_FF, FATFS::max_clust, FATFS::n_fatent, FIL::org_clust, res, RES_OK, FIL::sclust, and SS.
{
// FRESULT res;
    CLUST clust;
    dword csize, ifptr;
    res = validate(fp->fs, fp->id); /* Check validity of the object */
    if (res != FR_OK) return res;
    if (fp->flag & FA__ERROR) return FR_RW_ERROR;
    if (ofs > fp->fsize /* In read-only mode, clip offset with the file size */
#if !_FS_READONLY
         && !(fp->flag & FA_WRITE)
#endif
        ) ofs = fp->fsize;
    ifptr = fp->fptr;
    fp->fptr = 0; fp->csect = 255;
    if (ofs > 0) {
        csize = (dword)fp->fs->csize * 512U; /* Cluster size (byte) */
        if (ifptr > 0 &&
            (ofs - 1) / csize >= (ifptr - 1) / csize) {/* When seek to same or following cluster, */
            fp->fptr = (ifptr - 1) & ~(csize - 1); /* start from the current cluster */
            ofs -= fp->fptr;
            clust = fp->curr_clust;
        } else { /* When seek to back cluster, */
            clust = fp->org_clust; /* start from the first cluster */
#if !_FS_READONLY
            if (clust == 0) { /* If no cluster chain, create a new chain */
                clust = create_chain(0);
                if (clust == 1) goto fk_error;
                fp->org_clust = clust;
            }
#endif
            fp->curr_clust = clust;
        }
        if (clust != 0) {
            while (ofs > csize) { /* Cluster following loop */
#if !_FS_READONLY
                if (fp->flag & FA_WRITE) { /* Check if in write mode or not */
                    clust = create_chain(clust); /* Force streached if in write mode */
                    if (clust == 0) { /* When disk gets full, clip file size */
                        ofs = csize; break;
                    }
                } else
#endif
                    clust = get_cluster(clust); /* Follow cluster chain if not in write mode */
                if (clust < 2 || clust >= fp->fs->max_clust) goto fk_error;
                fp->curr_clust = clust;
                fp->fptr += csize;
                ofs -= csize;
            }
            fp->fptr += ofs;
            fp->csect = (byte)(ofs / 512U); /* Sector offset in the cluster */
            if (ofs % 512U) fp->csect++;
        }
    }
#if !_FS_READONLY
    if (fp->fptr > fp->fsize) { /* Set changed flag if the file was extended */
        fp->fsize = fp->fptr;
        fp->flag |= FA__WRITTEN;
    }
#endif
    return FR_OK;
fk_error: /* Abort this file due to an unrecoverable error */
    fp->flag |= FA__ERROR;
    return FR_RW_ERROR;
}
FRESULT f_mkdir (const TCHAR *)
Definition at line 1478 of file tff.c.
References _FS_RPATH, AM_DIR, clust2sect(), FATFS::csize, DEF_NAMEBUF, dir, DIR::dir, DIR_Attr, DIR_FstClusHI, DIR_FstClusLO, DIR_Name, DIR_NTres, DIR_WrtTime, FATFS::dirbase, disk_write(), dj, DIR::fn, FR_DENIED, FR_DISK_ERR, FR_EXIST, FR_INT_ERR, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FR_RW_ERROR, FREE_BUF, DIR::fs, FS_FAT32, FATFS::fs_type, get_fattime(), INIT_BUF, LEAVE_FF, NS, res, RES_OK, DIR::sclust, SS, ST_CLUST, ST_DWORD, ST_WORD, SZ_DIR, FATFS::wflag, FATFS::win, FATFS::winflag, and FATFS::winsect.
{
// FRESULT res;
// DIR dj;
// byte *dir;
    byte *fw, n;
// char fn[8+3+1];
    dword sect, dsect, tim;
    CLUST dclust, pclust;
    res = auto_mount(&path, 1);
    if (res != FR_OK) return res;
    res = trace_path(&dj, fn, path, &dir); /* Trace the file path */
    if (res == FR_OK) return FR_EXIST; /* Any file or directory is already existing */
    if (res != FR_NO_FILE) return res;
    res = reserve_direntry(&dj, &dir); /* Reserve a directory entry */
    if (res != FR_OK) return res;
    sect = dj.fs->winsect;
    dclust = create_chain(0); /* Allocate a cluster for new directory table */
    if (dclust == 1) return FR_RW_ERROR;
    dsect = clust2sect(dclust);
    if (!dsect) return FR_DENIED;
    if (!move_window(dsect)) return FR_RW_ERROR;
    fw = dj.fs->win;
    memset((void *)fw, 0, 512U); /* Clear the directory table */
    for (n = 1; n < dj.fs->csize; n++) {
        if (disk_write(fw, ++dsect, 1) != RES_OK)
            return FR_RW_ERROR;
    }
    memset(&fw[DIR_Name], ' ', 8+3); /* Create "." entry */
    fw[DIR_Name] = '.';
    fw[DIR_Attr] = AM_DIR;
    tim = get_fattime();
    ST_DWORD(&fw[DIR_WrtTime], tim);
    memcpy(&fw[32], &fw[0], 32); fw[33] = '.'; /* Create ".." entry */
    pclust = dj.sclust;
#if _FAT32
    ST_WORD(&fw[ DIR_FstClusHI], dclust >> 16);
    if (dj.fs->fs_type == FS_FAT32 && pclust == dj.fs->
      dirbase) pclust = 0;
    ST_WORD(&fw[32+DIR_FstClusHI], pclust >> 16);
#endif
    ST_WORD(&fw[ DIR_FstClusLO], dclust);
    ST_WORD(&fw[32+DIR_FstClusLO], pclust);
    dj.fs->winflag = 1;
    if (!move_window(sect)) return FR_RW_ERROR;
    memset(&dir[0], 0, 32); /* Clean-up the new entry */
    memcpy(&dir[DIR_Name], fn, 8+3); /* Name */
    dir[DIR_NTres] = fn[11];
    dir[DIR_Attr] = AM_DIR; /* Attribute */
    ST_DWORD(&dir[DIR_WrtTime], tim); /* Crated time */
    ST_WORD(&dir[DIR_FstClusLO], dclust); /* Table start cluster */
#if _FAT32
    ST_WORD(&dir[DIR_FstClusHI], dclust >> 16);
#endif
    return sync();
}
FRESULT f_mkfs (PF_BYTE , PF_BYTE , UINT)
FRESULT f_mount (PF_BYTE , FATFS *)
Definition at line 796 of file tff.c.
References _VOLUMES, FR_INT_ERR, FR_INVALID_DRIVE, FR_OK, and FATFS::fs_type.
Referenced by mount(), and unmount().
{
    if (drv) return FR_INVALID_DRIVE;
    if (FatFs) FatFs->fs_type = 0; /* Clear old object */
    FatFs = fs; /* Register and clear new object */
    if (fs) fs->fs_type = 0;
    return FR_OK;
}
FRESULT f_open (FIL * , const TCHAR * , PF_BYTE)
Definition at line 818 of file tff.c.
References AM_DIR, AM_RDO, FIL::cltbl, FIL::csect, DEF_NAMEBUF, dir, DIR::dir, DIR_Attr, DIR_CrtTime, DIR_FileSize, DIR_FstClusHI, DIR_FstClusLO, DIR_Name, DIR_NTres, FIL::dir_ptr, FIL::dir_sect, dj, FIL::dsect, FA__WRITTEN, FA_CREATE_ALWAYS, FA_CREATE_NEW, FA_OPEN_ALWAYS, FA_READ, FA_WRITE, FIL::flag, FIL::fptr, FR_DENIED, FR_EXIST, FR_INT_ERR, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FR_RW_ERROR, FR_TOO_MANY_OPEN_FILES, FREE_BUF, DIR::fs, FIL::fs, FIL::fsize, get_fattime(), FATFS::id, FIL::id, INIT_BUF, FATFS::last_clust, LD_CLUST, LD_DWORD, LD_WORD, LEAVE_FF, NULL, FIL::org_clust, res, FIL::sclust, ST_CLUST, ST_DWORD, ST_WORD, FATFS::wflag, FATFS::winflag, and FATFS::winsect.
{
// FRESULT res;
// DIR dj;
// byte *dir;
// char fn[8+3+1];
    fp->fs = NULL; /* Clear file object */
#if !_FS_READONLY
    mode &= (FA_READ|FA_WRITE|FA_CREATE_ALWAYS|
      FA_OPEN_ALWAYS|FA_CREATE_NEW);
    res = auto_mount(&path, (byte)(mode & (FA_WRITE|
      FA_CREATE_ALWAYS|FA_OPEN_ALWAYS|FA_CREATE_NEW)));
#else
    mode &= FA_READ;
    res = auto_mount(&path, 0);
#endif
    if (res != FR_OK) return res;
    res = trace_path(&dj, fn, path, &dir); /* Trace the file path */
#if !_FS_READONLY
    /* Create or Open a File */
    if (mode & (FA_CREATE_ALWAYS|FA_OPEN_ALWAYS|
      FA_CREATE_NEW)) {
        CLUST rs;
        dword dw;
        if (res != FR_OK) { /* No file, create new */
            if (res != FR_NO_FILE) return res;
            res = reserve_direntry(&dj, &dir);
            if (res != FR_OK) return res;
            memset((void *)dir, 0, 32); /* Initialize the new entry with open name */
            memcpy(&dir[DIR_Name], fn, 8+3);
            dir[DIR_NTres] = fn[11];
            mode |= FA_CREATE_ALWAYS;
        }
        else { /* Any object is already existing */
            if (mode & FA_CREATE_NEW) /* Cannot create new */
                return FR_EXIST;
            if (!dir || (dir[DIR_Attr] & (AM_RDO|AM_DIR))) /* Cannot overwrite
       (R/O or DIR) */
                return FR_DENIED;
            if (mode & FA_CREATE_ALWAYS) { /* Resize it to zero */
#if _FAT32
                rs = ((dword)LD_WORD(&dir[DIR_FstClusHI]) << 16) |
      LD_WORD(&dir[DIR_FstClusLO]);
                ST_WORD(&dir[DIR_FstClusHI], 0);
#else
                rs = LD_WORD(&dir[DIR_FstClusLO]);
#endif
                ST_WORD(&dir[DIR_FstClusLO], 0); /* cluster = 0 */
                ST_DWORD(&dir[DIR_FileSize], 0); /* size = 0 */
                dj.fs->winflag = 1;
                dw = dj.fs->winsect; /* Remove the cluster chain */
                if (!remove_chain(rs) || !move_window(dw))
                    return FR_RW_ERROR;
                dj.fs->last_clust = rs - 1; /* Reuse the cluster hole */
            }
        }
        if (mode & FA_CREATE_ALWAYS) {
            dir[DIR_Attr] = 0; /* Reset attribute */
            dw = get_fattime();
            ST_DWORD(&dir[DIR_CrtTime], dw); /* Created time */
            dj.fs->winflag = 1;
            mode |= FA__WRITTEN; /* Set file changed flag */
        }
    }
    /* Open an existing file */
    else {
#endif /* !_FS_READONLY */
        if (res != FR_OK) return res; /* Trace failed */
        if (!dir || (dir[DIR_Attr] & AM_DIR)) /* It is a directory */
            return FR_NO_FILE;
#if !_FS_READONLY
        if ((mode & FA_WRITE) && (dir[DIR_Attr] & AM_RDO)) /* R/O violation */
            return FR_DENIED;
    }
    fp->dir_sect = dj.fs->winsect; /* Pointer to the directory entry */
    fp->dir_ptr = dir;
#endif
    fp->flag = mode; /* File access mode */
    fp->org_clust = /* File start cluster */
#if _FAT32
        ((dword)LD_WORD(&dir[DIR_FstClusHI]) << 16) |
#endif
        LD_WORD(&dir[DIR_FstClusLO]);
    fp->fsize = LD_DWORD(&dir[DIR_FileSize]); /* File size */
    fp->fptr = 0; fp->csect = 255; /* File pointer */
    fp->fs = dj.fs; fp->id = dj.fs->id; /* Owner file system object of the file */
    return FR_OK;
}
FRESULT f_opendir (DIR * , const TCHAR *)
Definition at line 1205 of file tff.c.
References AM_DIR, DIR::clust, clust2sect(), DEF_NAMEBUF, DIR::dir, DIR_Attr, DIR_FstClusHI, DIR_FstClusLO, FR_NO_FILE, FR_NO_PATH, FR_OK, FREE_BUF, DIR::fs, FATFS::id, DIR::id, DIR::index, INIT_BUF, LD_CLUST, LD_WORD, LEAVE_FF, res, DIR::sclust, and DIR::sect.
Referenced by listDir(), and scan_files().
{
// FRESULT res;
// byte *dir;
// char fn[8+3+1];
    res = auto_mount(&path, 0);
    if (res == FR_OK) {
        res = trace_path(dj, fn, path, &dir); /* Trace the directory path */
        if (res == FR_OK) { /* Trace completed */
            if (dir) { /* It is not the root dir */
                if (dir[DIR_Attr] & AM_DIR) { /* The entry is a directory */
                    dj->clust =
#if _FAT32
                        ((dword)LD_WORD(&dir[DIR_FstClusHI]) << 16) |
#endif
                            LD_WORD(&dir[DIR_FstClusLO]);
                    dj->sect = clust2sect(dj->clust);
                    dj->index = 2;
                } else { /* The entry is not a directory */
                    res = FR_NO_FILE;
                }
            }
            dj->id = dj->fs->id;
        }
    }
    return res;
}
int f_printf (FIL * , const TCHAR * , ...)
int f_putc (TCHAR , FIL *)
int f_puts (const TCHAR * , FIL *)
FRESULT f_read (FIL * , void * , UINT , UINT *)
Definition at line 916 of file tff.c.
References ABORT, FIL::buf, FIL::cltbl, FIL::clust, clust2sect(), FIL::csect, FATFS::csize, FIL::curr_clust, disk_read(), disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__ERROR, FA_READ, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, FR_RW_ERROR, FIL::fs, FIL::fsize, get_fat(), FIL::id, LEAVE_FF, FATFS::max_clust, FIL::org_clust, res, RES_OK, FIL::sclust, SS, FATFS::wflag, FATFS::win, and FATFS::winsect.
{
// FRESULT res;
    dword sect, remain;
    word rcnt, cc;
    CLUST clust;
    byte *rbuff = buff;
    *br = 0;
    res = validate(fp->fs, fp->id); /* Check validity of the object */
    if (res != FR_OK) return res;
    if (fp->flag & FA__ERROR) return FR_RW_ERROR; /* Check error flag */
    if (!(fp->flag & FA_READ)) return FR_DENIED; /* Check access mode */
    remain = fp->fsize - fp->fptr;
    if (btr > remain) btr = (word)remain; /* Truncate btr by remaining bytes */
    for (; btr; /* Repeat until all data transferred */
        rbuff += rcnt, fp->fptr += rcnt, *br += rcnt, btr -= rcnt) {
        if ((fp->fptr % 512U) == 0) { /* On the sector boundary? */
            if (fp->csect >= fp->fs->csize) { /* On the cluster boundary? */
                clust = (fp->fptr == 0) ? /* On the top of the file? */
                    fp->org_clust : get_cluster(fp->curr_clust);
                if (clust < 2 || clust >= fp->fs->max_clust) goto fr_error;
                fp->curr_clust = clust; /* Update current cluster */
                fp->csect = 0; /* Reset sector address in the cluster */
            }
            sect = clust2sect(fp->curr_clust) + fp->csect; /* Get current sector */
            cc = btr / 512U; /* When remaining bytes >= sector size, */
            if (cc) { /* Read maximum contiguous sectors directly */
                if (fp->csect + cc > fp->fs->csize) /* Clip at cluster boundary */
                    cc = fp->fs->csize - fp->csect;
                if (disk_read(rbuff, sect, (byte)cc) != RES_OK)
                    goto fr_error;
                fp->csect += (byte)cc; /* Next sector address in the cluster */
                rcnt = 512U * cc; /* Number of bytes transferred */
                continue;
            }
            fp->csect++; /* Next sector address in the cluster */
        }
        sect = clust2sect(fp->curr_clust) + fp->csect - 1; /* Get current sector */
        if (!move_window(sect)) goto fr_error; /* Move sector window */
        rcnt = 512U - (fp->fptr % 512U); /* Get partial sector from sector window */
        if (rcnt > btr) rcnt = btr;
        memcpy(rbuff, &fp->fs->win[fp->fptr % 512U], rcnt);
    }
    return FR_OK;
fr_error: /* Abort this file due to an unrecoverable error */
    fp->flag |= FA__ERROR;
    return FR_RW_ERROR;
}
FRESULT f_readdir (DIR * , FILINFO *)
Definition at line 1246 of file tff.c.
References c, DEF_NAMEBUF, DIR_Attr, DIR_Name, FILINFO::fname, FR_NO_FILE, FR_OK, FR_RW_ERROR, FREE_BUF, DIR::fs, DIR::id, if(), DIR::index, INIT_BUF, LEAVE_FF, res, DIR::sect, and FATFS::win.
Referenced by listDir(), and scan_files().
{
// FRESULT res;
// byte *dir;
    byte c;
    res = validate(dj->fs, dj->id); /* Check validity of the object */
    if (res != FR_OK) return res;
    finfo->fname[0] = 0;
    while (dj->sect) {
        if (!move_window(dj->sect))
            return FR_RW_ERROR;
        dir = &dj->fs->win[(dj->index & 15) * 32]; /* pointer to the directory entry */
        c = dir[DIR_Name];
        if (c == 0) break; /* Has it reached to end of dir? */
        if (c != 0xE5 && !(dir[DIR_Attr] & AM_VOL)) /* Is it a valid entry? */
            get_fileinfo(finfo, dir);
        if (!next_dir_entry(dj)) dj->sect = 0; /* Next entry */
        if (finfo->fname[0]) break; /* Found valid entry */
    }
    return FR_OK;
}
FRESULT f_rename (const TCHAR * , const TCHAR *)
Definition at line 1619 of file tff.c.
References _FS_RPATH, AM_ARC, AM_DIR, clust2sect(), DEF_NAMEBUF, dir, DIR::dir, DIR_Attr, DIR_Name, DIR_NTres, FATFS::dirbase, DIR::fn, FR_EXIST, FR_INT_ERR, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FR_RW_ERROR, FREE_BUF, DIR::fs, FS_FAT32, FATFS::fs_type, INIT_BUF, LD_CLUST, LEAVE_FF, NS, res, DIR::sclust, ST_CLUST, SZ_DIR, FATFS::wflag, FATFS::win, FATFS::winflag, and FATFS::winsect.
{
    FRESULT res;
    dword sect_old;
    byte *dir_old, *dir_new, direntry[32-11];
// DIR dj;
// char fn[8+3+1];
    res = auto_mount(&path_old, 1);
    if (res != FR_OK) return res;
    res = trace_path(&dj, fn, path_old, &dir_old); /* Check old object */
    if (res != FR_OK) return res; /* The old object is not found */
    if (!dir_old) return FR_NO_FILE;
    sect_old = dj.fs->winsect; /* Save the object information */
    memcpy(direntry, &dir_old[DIR_Attr], 32-11);
    res = trace_path(&dj, fn, path_new, &dir_new); /* Check new object */
    if (res == FR_OK) return FR_EXIST; /* The new object name is already existing */
    if (res != FR_NO_FILE) return res; /* Is there no old name? */
    res = reserve_direntry(&dj, &dir_new); /* Reserve a directory entry */
    if (res != FR_OK) return res;
    memcpy(&dir_new[DIR_Attr], direntry, 32-11); /* Create new entry */
    memcpy(&dir_new[DIR_Name], fn, 8+3);
    dir_new[DIR_NTres] = fn[11];
    dj.fs->winflag = 1;
    if (!move_window(sect_old)) return FR_RW_ERROR; /* Delete old entry */
    dir_old[DIR_Name] = 0xE5;
    return sync();
}
FRESULT f_stat (const TCHAR * , FILINFO *)
Definition at line 1283 of file tff.c.
References DEF_NAMEBUF, DIR::dir, dj, FR_INVALID_NAME, FR_OK, FREE_BUF, DIR::fs, INIT_BUF, LEAVE_FF, and res.
{
// FRESULT res;
// DIR dj;
// byte *dir;
// char fn[8+3+1];
    res = auto_mount(&path, 0);
    if (res == FR_OK) {
        res = trace_path(&dj, fn, path, &dir); /* Trace the file path */
        if (res == FR_OK) { /* Trace completed */
            if (dir) /* Found an object */
                get_fileinfo(finfo, dir);
            else /* It is root dir */
                res = FR_INVALID_NAME;
        }
    }
    return res;
}
FRESULT f_sync (FIL *)
Definition at line 1061 of file tff.c.
References AM_ARC, FIL::buf, dir, DIR_Attr, DIR_FileSize, DIR_FstClusHI, DIR_FstClusLO, FIL::dir_ptr, FIL::dir_sect, DIR_WrtTime, disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__WRITTEN, FIL::flag, FR_DISK_ERR, FR_OK, FR_RW_ERROR, FIL::fs, FIL::fsize, get_fattime(), FIL::id, LEAVE_FF, FIL::org_clust, res, RES_OK, FIL::sclust, ST_CLUST, ST_DWORD, ST_WORD, and FATFS::wflag.
Referenced by f_close().
{
// FRESULT res;
    dword tim;
// byte *dir;
    res = validate(fp->fs, fp->id); /* Check validity of the object */
    if (res == FR_OK) {
        if (fp->flag & FA__WRITTEN) { /* Has the file been written? */
            /* Update the directory entry */
            if (!move_window(fp->dir_sect)) return FR_RW_ERROR;
            dir = fp->dir_ptr;
            dir[DIR_Attr] |= AM_ARC; /* Set archive bit */
            ST_DWORD(&dir[DIR_FileSize], fp->fsize); /* Update file size */
            ST_WORD(&dir[DIR_FstClusLO], fp->org_clust); /* Update start cluster */
#if _FAT32
            ST_WORD(&dir[DIR_FstClusHI], fp->org_clust >> 16);
#endif
            tim = get_fattime(); /* Updated time */
            ST_DWORD(&dir[DIR_WrtTime], tim);
            fp->flag &= (byte)~FA__WRITTEN;
            res = sync();
        }
    }
    return res;
}
FRESULT f_truncate (FIL *)
Definition at line 1316 of file tff.c.
References FIL::clust, FIL::curr_clust, FA__ERROR, FA__WRITTEN, FA_WRITE, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, FR_RW_ERROR, FIL::fs, FIL::fsize, get_fat(), FIL::id, LEAVE_FF, FATFS::max_clust, FATFS::n_fatent, FIL::org_clust, put_fat(), res, and FIL::sclust.
{
// FRESULT res;
    CLUST ncl;
    res = validate(fp->fs, fp->id); /* Check validity of the object */
    if (res != FR_OK) return res;
    if (fp->flag & FA__ERROR) return FR_RW_ERROR; /* Check error flag */
    if (!(fp->flag & FA_WRITE)) return FR_DENIED; /* Check access mode */
    if (fp->fsize > fp->fptr) {
        fp->fsize = fp->fptr; /* Set file size to current R/W point */
        fp->flag |= FA__WRITTEN;
        if (fp->fptr == 0) { /* When set file size to zero, remove entire cluster chain */
            if (!remove_chain(fp->org_clust)) goto ft_error;
            fp->org_clust = 0;
        } else { /* When truncate a part of the file, remove remaining clusters */
            ncl = get_cluster(fp->curr_clust);
            if (ncl < 2) goto ft_error;
            if (ncl < fp->fs->max_clust) {
                if (!put_cluster(fp->curr_clust, (CLUST)0x0FFFFFFF)) goto ft_error;
                if (!remove_chain(ncl)) goto ft_error;
            }
        }
    }
    return FR_OK;
ft_error: /* Abort this file due to an unrecoverable error */
    fp->flag |= FA__ERROR;
    return FR_RW_ERROR;
}
FRESULT f_unlink (const TCHAR *)
Definition at line 1425 of file tff.c.
References _FS_RPATH, AM_DIR, AM_RDO, DIR::clust, clust2sect(), DEF_NAMEBUF, dir, DIR::dir, DIR_Attr, DIR_FstClusHI, DIR_FstClusLO, DIR_Name, dj, DIR::fn, FR_DENIED, FR_INT_ERR, FR_INVALID_NAME, FR_NO_FILE, FR_OK, FR_RW_ERROR, FREE_BUF, DIR::fs, DIR::index, INIT_BUF, LD_CLUST, LD_WORD, LEAVE_FF, NS, res, DIR::sclust, DIR::sect, FATFS::win, FATFS::winflag, and FATFS::winsect.
{
// FRESULT res;
// DIR dj;
// byte *dir;
    byte *sdir;
    dword dsect;
// char fn[8+3+1];
    CLUST dclust;
    res = auto_mount(&path, 1);
    if (res != FR_OK) return res;
    res = trace_path(&dj, fn, path, &dir); /* Trace the file path */
    if (res != FR_OK) return res; /* Trace failed */
    if (!dir) return FR_INVALID_NAME; /* It is the root directory */
    if (dir[DIR_Attr] & AM_RDO) return FR_DENIED; /* It is a R/O object */
    dsect = dj.fs->winsect;
    dclust =
#if _FAT32
        ((dword)LD_WORD(&dir[DIR_FstClusHI]) << 16) |
#endif
        LD_WORD(&dir[DIR_FstClusLO]);
    if (dir[DIR_Attr] & AM_DIR) { /* It is a sub-directory */
        dj.clust = dclust; /* Check if the sub-dir is empty or not */
        dj.sect = clust2sect(dclust);
        dj.index = 2;
        do {
            if (!move_window(dj.sect)) return FR_RW_ERROR;
            sdir = &dj.fs->win[(dj.index & 15) * 32];
            if (sdir[DIR_Name] == 0) break;
            if (sdir[DIR_Name] != 0xE5 && !(sdir[DIR_Attr] &
      AM_VOL))
                return FR_DENIED; /* The directory is not empty */
        } while (next_dir_entry(&dj));
    }
    if (!move_window(dsect)) return FR_RW_ERROR; /* Mark the directory entry 'deleted' */
    dir[DIR_Name] = 0xE5;
    dj.fs->winflag = 1;
    if (!remove_chain(dclust)) return FR_RW_ERROR; /* Remove the cluster chain */
    return sync();
}
FRESULT f_utime (const TCHAR * , const FILINFO *)
Definition at line 1585 of file tff.c.
References _FS_RPATH, DEF_NAMEBUF, dir, DIR::dir, DIR_WrtDate, DIR_WrtTime, dj, FILINFO::fdate, DIR::fn, FR_INVALID_NAME, FR_OK, FREE_BUF, DIR::fs, FILINFO::ftime, INIT_BUF, LEAVE_FF, NS, res, ST_WORD, and FATFS::wflag.
{
// FRESULT res;
// DIR dj;
// byte *dir;
// char fn[8+3+1];
    res = auto_mount(&path, 1);
    if (res == FR_OK) {
        res = trace_path(&dj, fn, path, &dir); /* Trace the file path */
        if (res == FR_OK) { /* Trace completed */
            if (!dir) {
                res = FR_INVALID_NAME; /* Root directory */
            } else {
                ST_WORD(&dir[DIR_WrtTime], finfo->ftime);
                ST_WORD(&dir[DIR_WrtDate], finfo->fdate);
                res = sync();
            }
        }
    }
    return res;
}
FRESULT f_write (FIL * , const void * , UINT , UINT *)
Definition at line 983 of file tff.c.
References ABORT, FIL::buf, FIL::cltbl, FIL::clust, clust2sect(), FIL::csect, FATFS::csize, FIL::curr_clust, disk_read(), disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__ERROR, FA__WRITTEN, FA_WRITE, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, FR_RW_ERROR, FIL::fs, FIL::fsize, fsize, FIL::id, LEAVE_FF, FATFS::max_clust, FIL::org_clust, res, RES_OK, FIL::sclust, SS, FATFS::wflag, FATFS::win, FATFS::winflag, and FATFS::winsect.
{
// FRESULT res;
    dword sect;
    word wcnt, cc;
    CLUST clust;
    const byte *wbuff = buff;
    *bw = 0;
    res = validate(fp->fs, fp->id); /* Check validity of the object */
    if (res != FR_OK) return res;
    if (fp->flag & FA__ERROR) return FR_RW_ERROR; /* Check error flag */
    if (!(fp->flag & FA_WRITE)) return FR_DENIED; /* Check access mode */
    if (fp->fsize + btw < fp->fsize) return FR_OK; /* File size cannot reach 4GB */
    for (; btw; /* Repeat until all data transferred */
        wbuff += wcnt, fp->fptr += wcnt, *bw += wcnt, btw -= wcnt) {
        if ((fp->fptr % 512U) == 0) { /* On the sector boundary? */
            if (fp->csect >= fp->fs->csize) { /* On the cluster boundary? */
                if (fp->fptr == 0) { /* On the top of the file? */
                    clust = fp->org_clust; /* Follow from the origin */
                    if (clust == 0) /* When there is no cluster chain, */
                        fp->org_clust = clust = create_chain(0); /* Create a new cluster chain */
                } else { /* Middle or end of the file */
                    clust = create_chain(fp->curr_clust); /* Trace or streach cluster chain */
                }
                if (clust == 0) break; /* Could not allocate a new cluster (disk full) */
                if (clust == 1 || clust >= fp->fs->max_clust) goto fw_error;
                fp->curr_clust = clust; /* Update current cluster */
                fp->csect = 0; /* Reset sector address in the cluster */
            }
            sect = clust2sect(fp->curr_clust) + fp->csect; /* Get current sector */
            cc = btw / 512U; /* When remaining bytes >= sector size, */
            if (cc) { /* Write maximum contiguous sectors directly */
                if (fp->csect + cc > fp->fs->csize) /* Clip at cluster boundary */
                    cc = fp->fs->csize - fp->csect;
                if (disk_write(wbuff, sect, (byte)cc) != RES_OK)
                    goto fw_error;
                fp->csect += (byte)cc; /* Next sector address in the cluster */
                wcnt = 512U * cc; /* Number of bytes transferred */
                continue;
            }
            if (fp->fptr >= fp->fsize) { /* Flush R/W window without reading if needed */
                if (!move_window(0)) goto fw_error;
                fp->fs->winsect = sect;
            }
            fp->csect++; /* Next sector address in the cluster */
        }
        sect = clust2sect(fp->curr_clust) + fp->csect - 1; /* Get current sector */
        if (!move_window(sect)) goto fw_error; /* Move sector window */
        wcnt = 512U - (fp->fptr % 512U); /* Put partial sector into sector window */
        if (wcnt > btw) wcnt = btw;
        memcpy(&fp->fs->win[fp->fptr % 512U], wbuff, wcnt);
        fp->fs->winflag = 1;
    }
    if (fp->fptr > fp->fsize) {fp->fsize = fp->fptr;} /* Update file size if needed */
    fp->flag |= FA__WRITTEN; /* Set file changed flag */
    return res;
fw_error: /* Abort this file due to an unrecoverable error */
    fp->flag |= FA__ERROR;
    return FR_RW_ERROR;
}
DWORD get_fattime (void)
Definition at line 583 of file diskio.c.
References rtccDate::dayofmonth, rtccTime::hours, rtccTime::minutes, rtccDate::month, RTCC_ConvertDate(), RTCC_ConvertTime(), RTCC_GetTimeDate(), rtccTime::seconds, and rtccDate::year.
                        {
    DWORD tmr = 0;
// Pre-processor commands added so only use RTCC if the board is known
// to support the RTCC ** Added 07 May 2012
// For boards known to support the RTCC library
#if defined (PIC32_PINGUINO) || defined (PIC32_PINGUINO_OTG)
    rtccTime pTm, cTm;
    rtccDate pDt, cDt;
    RTCC_GetTimeDate(&pTm, &pDt); // get time and date from RTC
                                            // assumes RTC has been set and is running
                                            // OK - could be expanded to check that RTC
                                            // is running and that a valid value is
                                            // being returned by the RTC
    cTm = RTCC_ConvertTime(&pTm); // convert time from bcd to decimal format
    cDt = RTCC_ConvertDate(&pDt); // convert date from bcd to decimal format
    /* Pack date and time into a DWORD variable */
// tmr = (((DWORD) pDt.year - 80)) | ((DWORD) pDt.mon) | ((DWORD) pDt.mday)
// | (WORD) (pTm.hour) | (WORD) (pTm.min) | (WORD) (pTm.sec);
    tmr = cDt.year + 20;
   
  // Correction according to a newer rtcc library, with diff struct members.
  
     tmr = (tmr << 4) | cDt.month; // shifts left 4 bits and adds monthth
    tmr = (tmr << 5) | cDt.dayofmonth; // shifts left 5 bits and adds m.day
    tmr = (tmr << 5) | cTm.hours; // shifts left 5 bits and adds hour
    tmr = (tmr << 6) | cTm.minutes; // shift left 6 bits and adds minutes
    tmr = (tmr << 5) | (cTm.seconds/2); // shifts left 5 bits and adds seconds/2
// For other boards use a fixed date and time of 01 Jan 2012 12:00:00
#else
     tmr = 12 + 20;
     tmr = (tmr << 4) | 1; // shifts left 4 bits and adds month
     tmr = (tmr << 5) | 1; // shifts left 5 bits and adds m.day
     tmr = (tmr << 5) | 12; // shifts left 5 bits and adds hour
     tmr = (tmr << 6) | 0; // shift left 6 bits and adds minutes
     tmr = (tmr << 5) | (0/2); // shifts left 5 bits and adds seconds/2
#endif
    return tmr;
}