/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/flashmem.c File Reference
#include <typedef.h>
*
Macros
#define __FLASHMEM__
Functions
u32 TotalMem ()
u32 FlashOperation (u16 operation)
u32 FlashClearError ()
u32 PageErase (void *address)
u32 WordWrite (void *address, u32 data)
u32 RowWrite (void *address, u32 *data)
Macro Definition Documentation
#define __FLASHMEM__
Definition at line 25 of file flashmem.c.
Function Documentation
u32 FlashClearError ()
Definition at line 72 of file flashmem.c.
References FlashOperation().
Referenced by PageErase(), RowWrite(), and WordWrite().
{
    return(FlashOperation(0x4000));
}
u32 FlashOperation (u16 operation)
Definition at line 39 of file flashmem.c.
Referenced by FlashClearError(), PageErase(), RowWrite(), and WordWrite().
{
    unsigned long t0;
    
    // disable interrupt
    asm("di");
    NVMCON=operation;
    
    // wait for LVD to start up (at least 6 µS)
    t0 = _CP0_GET_COUNT();
    while (_CP0_GET_COUNT() - t0 < (80/2)*6);
    
    // unlock system
    NVMKEY=0xAA996655;
    NVMKEY=0x556699AA;
    
    NVMCONSET=NVMCON_WR;
    
    // Wait for WR bit to clear
    while(NVMCON & NVMCON_WR);
    // Disable Flash Write/Erase operations
    NVMCONCLR = NVMCON_WREN;
        
    // enable interrupt
    asm("ei");
        
    return(NVMCON & (_NVMCON_WRERR_MASK | _NVMCON_LVDERR_MASK)); // error if != 0
}
u32 PageErase (void * address)
Definition at line 77 of file flashmem.c.
References FlashClearError(), and FlashOperation().
{
    // check for error in the NVMCON register
    if (NVMCON & (_NVMCON_WRERR_MASK | _NVMCON_LVDERR_MASK)) FlashClearError();
    // set Address to erase and Non Volatile Memory instruction ERASE PAGE
    NVMADDR = (u32)address & 0x1fffffff ;
    return(FlashOperation(0x4004));
}
u32 RowWrite (void * address, u32 * data)
Definition at line 99 of file flashmem.c.
References FlashClearError(), and FlashOperation().
{
    // check for error in the NVMCON register
    if (NVMCON & (_NVMCON_WRERR_MASK | _NVMCON_LVDERR_MASK)) FlashClearError();
    // set Address to erase and Non Volatile Memory instruction ERASE PAGE
    NVMADDR = (u32) address & 0x1fffffff;
    NVMDATA = (u32) data & 0x1fffffff;
    return(FlashOperation(0x4003));
}
u32 TotalMem ()
Definition at line 31 of file flashmem.c.
{
    return(BMXPFMSZ+0x9D000000);
}
u32 WordWrite (void * address, u32 data)
Definition at line 89 of file flashmem.c.
References FlashClearError(), and FlashOperation().
{
    // check for error in the NVMCON register
    if (NVMCON & (_NVMCON_WRERR_MASK | _NVMCON_LVDERR_MASK)) FlashClearError();
    // set Address to erase and Non Volatile Memory instruction ERASE PAGE
    NVMADDR = (u32) address & 0x1fffffff ;
    NVMDATA = (u32) data ;
    return(FlashOperation(0x4001));
}