/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/i2cmaster.c File Reference
#include <stdlib.h>
*
Macros
#define _I2CBUFFERLENGTH_ 32
#define I2C_WRITE 0
#define I2C_READ 1
#define I2C_MASTER_MODE 0
#define I2C_SLAVE_MODE 1
#define I2C_SLEW_OFF 0
#define I2C_SLEW_ON 1
#define I2C_100KHZ 100
#define I2C_400KHZ 400
#define I2C_1MHZ 1000
#define I2C_READY 0
#define I2C_MRX 1
#define I2C_MTX 2
#define I2C_SRX 3
#define I2C_STX 4
Functions
void I2C_master (u16)
PROTOTYPES.
void I2C_slave (u16)
void I2C_init (u8, u16)
u8 I2C_write (u8)
u8 I2C_read ()
void I2C_idle ()
void I2C_start ()
void I2C_stop ()
void I2C_restart ()
void I2C_sendNack ()
void I2C_sendAck ()
u8 I2C_transmit (const u8 *, u8)
u8 I2C_writeTo (u8, u8 *, u8, u8, u8)
u8 I2C_readFrom (u8, u8 *, u8, u8)
void I2C_begin (u8 address, u16 speed)
u8 I2C_requestFrom (u8 address, u8 quantity)
void I2C_beginTransmission (u8 address)
u8 I2C_endTransmission (u8 sendStop)
u8 I2C_inBuffer (u8 data)
u8 I2C_inBufferS (u8 *data, u8 quantity)
u8 I2C_inBufferStr (u8 *data)
u8 I2C_available ()
u8 I2C_outBuffer ()
int peek (void)
Macro Definition Documentation
#define _I2CBUFFERLENGTH_ 32
Definition at line 20 of file i2cmaster.c.
Referenced by i2c_hw_slave_init(), i2c_hw_slave_on_state_4(), I2C_inBuffer(), I2C_readFrom(), I2C_requestFrom(), and I2C_writeTo().
#define I2C_100KHZ 100
Definition at line 31 of file i2cmaster.c.
#define I2C_1MHZ 1000
Definition at line 33 of file i2cmaster.c.
#define I2C_400KHZ 400
Definition at line 32 of file i2cmaster.c.
#define I2C_MASTER_MODE 0
Definition at line 25 of file i2cmaster.c.
#define I2C_MRX 1
Definition at line 41 of file i2cmaster.c.
Referenced by I2C_readFrom().
#define I2C_MTX 2
Definition at line 42 of file i2cmaster.c.
Referenced by I2C_writeTo().
#define I2C_READ 1
Definition at line 24 of file i2cmaster.c.
Referenced by I2C_readFrom().
#define I2C_READY 0
Definition at line 40 of file i2cmaster.c.
Referenced by I2C_begin(), I2C_readFrom(), and I2C_writeTo().
#define I2C_SLAVE_MODE 1
Definition at line 26 of file i2cmaster.c.
#define I2C_SLEW_OFF 0
Definition at line 27 of file i2cmaster.c.
#define I2C_SLEW_ON 1
Definition at line 28 of file i2cmaster.c.
#define I2C_SRX 3
Definition at line 43 of file i2cmaster.c.
#define I2C_STX 4
Definition at line 44 of file i2cmaster.c.
#define I2C_WRITE 0
Definition at line 23 of file i2cmaster.c.
Function Documentation
u8 I2C_available ()
Definition at line 484 of file i2cmaster.c.
{
  return _i2c_rxBufferLength - _i2c_rxBufferIndex;
}
void I2C_begin (u8 address, u16 speed)
Definition at line 306 of file i2cmaster.c.
References i2c_hw_slave_init(), I2C_master(), and I2C_READY.
{
    if (address !=0) {
        // SSPADD = address; done in I2C_init
        // I2C_slave((u16)address);
        #ifdef I2CINT
        i2c_hw_slave_init(address);
        #endif
    }
    
    _i2c_rxBufferIndex = 0;
    _i2c_rxBufferLength = 0;
    _i2c_txBufferIndex = 0;
    _i2c_txBufferLength = 0;
    // initialize state
    i2c_state = I2C_READY;
    i2c_sendStop = true; // default value
    i2c_inRepStart = false;
    if (address ==0) {
        I2C_master(speed);
    }
}
void I2C_beginTransmission (u8 address)
Definition at line 364 of file i2cmaster.c.
{
    // indicate that we are transmitting
    _i2c_transmitting = 1;
    // set address of targeted slave
    _i2c_txAddress = address;
    // reset tx buffer iterator vars
    _i2c_txBufferIndex = 0;
    _i2c_txBufferLength = 0;
}
u8 I2C_endTransmission (u8 sendStop)
Definition at line 381 of file i2cmaster.c.
References I2C_writeTo().
{
 // u8 sendStop = true;
    u8 ret;
    // transmit buffer (blocking)
    ret = I2C_writeTo(_i2c_txAddress, _i2c_txBuffer, _i2c_txBufferLength, 1, sendStop);
    // reset tx buffer iterator vars
    _i2c_txBufferIndex = 0;
    _i2c_txBufferLength = 0;
    // indicate that we are done transmitting
    _i2c_transmitting = 0;
    return ret;
}
void I2C_idle ()
u8 I2C_inBuffer (u8 data)
Definition at line 400 of file i2cmaster.c.
References _I2CBUFFERLENGTH_, and I2C_transmit().
Referenced by I2C_inBufferS(), and I2C_inBufferStr().
{
  if(_i2c_transmitting){
  // in master transmitter mode
    // don't bother if buffer is full
    if(_i2c_txBufferLength >= _I2CBUFFERLENGTH_){
// setWriteError();
      return 0;
    }
    // put byte in tx buffer
    _i2c_txBuffer[_i2c_txBufferIndex] = data;
    ++_i2c_txBufferIndex;
    // update amount in buffer
//serial_printf("\r\n%2X",data);
    _i2c_txBufferLength = _i2c_txBufferIndex;
  }
#ifdef I2CINT
  else{
  // in slave send mode
    // reply to master
    I2C_transmit(&data, 1);
  }
#endif
  return 1;
}
u8 I2C_inBufferS (u8 * data, u8 quantity)
Definition at line 431 of file i2cmaster.c.
References I2C_inBuffer(), and I2C_transmit().
{
  u8 i;
  if(_i2c_transmitting){
  // in master transmitter mode
    for(i = 0; i < quantity; ++i){
      I2C_inBuffer(data[i]);
    }
  }
#ifdef I2CINT
  else{
  // in slave send mode
    // reply to master
    I2C_transmit(data, quantity);
  }
#endif
  return quantity;
}
u8 I2C_inBufferStr (u8 * data)
Definition at line 451 of file i2cmaster.c.
References I2C_inBuffer(), and I2C_transmit().
{
  u8 i;
  if(_i2c_transmitting){
  // in master transmitter mode
    i = 0;
    while (data[i] != '\0')
    {
      I2C_inBuffer(data[i]);
      ++i;
    }
  }
#ifdef I2CINT
  else{
  i=0;
  while (data[i] != '\0') i++;
  // in slave send mode
    // reply to master
    I2C_transmit(data,i);
  }
#endif
  return i;
}
void I2C_init (u8 , u16)
Definition at line 167 of file i2c.c.
References I2C_100KHZ, I2C_1MHZ, I2C_400KHZ, I2C_MASTER_MODE, I2C_SLAVE_MODE, and INPUT.
Referenced by I2C1_init(), I2C2_init(), I2C_master(), I2C_slave(), lcdi2c_init(), and PCF8574_init().
{
    // In Slave mode, the SCL and SDA pins must be configured as inputs
    #if defined(__18f26j50) || defined(__18f46j50) || \
        defined(__18f27j53) || defined(__18f47j53)
    TRISBbits.TRISB5 = INPUT; // SDA = INPUT
    TRISBbits.TRISB4 = INPUT; // SCL = INPUT
    #else
    TRISBbits.TRISB0 = INPUT; // SDA = INPUT
    TRISBbits.TRISB1 = INPUT; // SCL = INPUT
    #endif
    switch (mode)
    {
        case I2C_SLAVE_MODE:
            //intUsed[INT_SSP] = INT_USED;
            // Enabling interrupts (peripheral & general)
            //INTCONbits.PEIE=1;
            //INTCONbits.GIE=1;
            if (sora > 0x80)
                SSPCON1= 0b00101111; // Slave mode, 10-bit address with Start and Stop bit interrupts
       enabled
            else
                SSPCON1= 0b00101110; // 00101110Slave mode, 7-bit address with Start and Stop bit
       interrupts enabled
    /*------------------------------------------------------------------------*/
            SSPADD= sora; // Slave 7-bit address
            // TODO // Slave 10-bit address
    /*------------------------------------------------------------------------*/
            break;
        case I2C_MASTER_MODE:
        default:// I2C_MASTER_MODE
            SSPCON1= 0b00101000; // Master Mode, clock = FOSC/(4 * (SSPADD + 1))
            // datasheet p208
            switch (sora)
            {
                case I2C_1MHZ:
                    // SMP = 1 = Slew rate control disabled for Standard Speed mode (100 kHz and 1 MHz)
                    SSPSTATbits.SMP = 1; // Slew Mode Off
                    SSPADD= 11; // 1MHz = FOSC/(4 * (SSPADD + 1))
                    break; // SSPADD = 48 000 / (4*1000) - 1
                    
                case I2C_400KHZ:
                    // SMP = 0 = Slew rate control enabled for High-Speed mode (400 kHz)
                    SSPSTATbits.SMP = 0; // Slew Mode On
                    SSPADD= 29; // 400kHz = FOSC/(4 * (SSPADD + 1))
                    break; // SSPADD = 48 000 / (4*400) - 1
                case I2C_100KHZ:
                default:
                    // SMP = 1 = Slew rate control disabled for Standard Speed mode (100 kHz and 1 MHz)
                    SSPSTATbits.SMP = 1; // Slew Mode Off
                    SSPADD= 119; // 100kHz = FOSC/(4 * (SSPADD + 1))
                    break; // SSPADD = 48 000 / (4*100) - 1
            }
            break;
    }
    SSPCON2= 0;
    PIR1bits.SSPIF = 0; // MSSP Interrupt Flag
    PIR2bits.BCLIF = 0; // Bus Collision Interrupt Flag
    //Delayms(1000);
}
void I2C_master (u16)
PROTOTYPES.
Definition at line 144 of file i2c.c.
References I2C_init(), and I2C_MASTER_MODE.
Referenced by I2C_begin().
{
    I2C_init(I2C_MASTER_MODE, speed);
}
u8 I2C_outBuffer ()
Definition at line 505 of file i2cmaster.c.
{
    // default to returning null char
    // for people using with char strings
    u8 value = '\0';
    // get each successive byte on each call
    if (_i2c_rxBufferIndex < _i2c_rxBufferLength)
    {
        value = _i2c_rxBuffer[_i2c_rxBufferIndex];
        ++_i2c_rxBufferIndex;
    }
    return value;
}
u8 I2C_read ()
Definition at line 290 of file i2c.c.
References I2C_idle.
Referenced by I2C_readFrom().
{
//rz u8 r;
    
    I2C_idle(); // Wait the MSSP module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.RCEN = 1; // Initiate reception of byte
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
    PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    
//rz r = SSPBUF;
    
    while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
    PIR1bits.SSPIF=0; // ROlf clear SSPIF
//rz r = SSPBUF;
    PIR1bits.SSPIF=0; // ROlf clear SSPIF
    //while (!SSPSTATbits.BF); // Wait until buffer is full
    //while (SSPCON2bits.RCEN); // Wait until RCEN is cleared
//rz return r;
    return SSPBUF;
}
u8 I2C_readFrom (u8 address, u8 * data, u8 length, u8 sendStop)
Definition at line 101 of file i2cmaster.c.
References _I2CBUFFERLENGTH_, I2C_MRX, I2C_READ, I2C_read(), I2C_READY, I2C_restart(), I2C_sendAck(), I2C_sendNack(), I2C_start(), I2C_stop(), and I2C_write().
Referenced by I2C_requestFrom().
{
  u8 i;
  u8 resp_sla;
  // ensure data will fit into buffer
  if(length > _I2CBUFFERLENGTH_){
    return 0;
  }
  // wait until twi is ready, become master receiver
  while(i2c_state != I2C_READY){
     continue;
  }
  i2c_state = I2C_MRX;// Master Receiver
  i2c_sendStop = sendStop;
  // reset error state (0xFF.. no error occured)
  i2c_error = 0xFF;
  // initialize buffer iteration vars
  _i2c_masterBufferIndex = 0;
  _i2c_masterBufferLength = length; // This is not intuitive, read on...
  // On receive, the previously configured ACK/NACK setting is transmitted in
  // response to the received byte before the interrupt is signalled.
  // Therefor we must actually set NACK when the _next_ to last byte is
  // received, causing that NACK to be sent in response to receiving the last
  // expected byte of data.
  // build sla+w, slave device address + w bit
  i2c_slarw = (address) |I2C_READ;
  if (i2c_inRepStart) {
    // if we're in the repeated start state, then we've already sent the start,
    // (@@@ we hope), and the TWI statemachine is just waiting for the address byte.
    // We need to remove ourselves from the repeated start state before we enable interrupts,
    // since the ISR is ASYNC, and we could get confused if we hit the ISR before cleaning
    // up. Also, don't enable the START interrupt. There may be one pending from the
    // repeated start that we sent outselves, and that would really confuse things.
    i2c_inRepStart = false;// remember, we're dealing with an ASYNC ISR
    I2C_restart();
    resp_sla = I2C_write(i2c_slarw);
  }
  else {
    // send start condition
    I2C_start();
    resp_sla = I2C_write(i2c_slarw);
  }
       //address sent, ack received
      // put byte into buffer
    if (resp_sla) {
    while (_i2c_masterBufferIndex < _i2c_masterBufferLength)
      {
       _i2c_masterBuffer[_i2c_masterBufferIndex++] = I2C_read();
       // data received, ack sent
       // ack if more bytes are expected, otherwise nack
      if(_i2c_masterBufferIndex == _i2c_masterBufferLength){
          I2C_sendNack();
        }else{
          I2C_sendAck();
        }
      }
    }
    
  if (_i2c_masterBufferIndex < length)
    length = _i2c_masterBufferIndex;
  // copy i2c buffer to data
  for(i = 0; i < length; ++i){
    data[i] = _i2c_masterBuffer[i];
  }
  if (i2c_sendStop)
    I2C_stop();
  else {
    i2c_inRepStart = true;
  }
  i2c_state = I2C_READY;
  return length;
}
u8 I2C_requestFrom (u8 address, u8 quantity)
Definition at line 338 of file i2cmaster.c.
References _I2CBUFFERLENGTH_, I2C_readFrom(), and read().
{
    u8 read;
    u8 sendStop;
    
    // clamp to buffer length
    if (quantity > _I2CBUFFERLENGTH_)
        quantity = _I2CBUFFERLENGTH_;
    // perform blocking read into buffer
    sendStop = true;
    read = I2C_readFrom(address, _i2c_rxBuffer, quantity, sendStop);
    // set rx buffer iterator vars
    _i2c_rxBufferIndex = 0;
    _i2c_rxBufferLength = read;
    return read;
}
void I2C_restart ()
Definition at line 418 of file i2c.c.
References I2C_idle.
Referenced by I2C1_restart(), I2C2_restart(), I2C_get(), I2C_readFrom(), and I2C_sendID().
{
    I2C_idle(); // Wait module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.RSEN = 1; // Send restart bit
    while (SSPCON2bits.RSEN); // Wait until RSEN is cleared
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_sendAck ()
Definition at line 434 of file i2c.c.
References I2C_idle.
Referenced by I2C1_sendAck(), I2C2_sendAck(), and I2C_readFrom().
{
    I2C_idle(); // Wait module is inactive
    SSPCON2bits.ACKDT = 0; // We want an Ack
    PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.ACKEN = 1; // Send it now
    while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_sendNack ()
Definition at line 450 of file i2c.c.
References I2C_idle.
Referenced by I2C1_sendNack(), I2C2_sendNack(), I2C_get(), and I2C_readFrom().
{
    I2C_idle(); // Wait module is inactive
    SSPCON2bits.ACKDT = 1; // We want a No Ack
    PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.ACKEN = 1; // Send it now
    while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_slave (u16)
Definition at line 149 of file i2c.c.
References I2C_init(), and I2C_SLAVE_MODE.
{
    I2C_init(I2C_SLAVE_MODE, DeviceID);
}
void I2C_start ()
Definition at line 386 of file i2c.c.
References I2C_idle.
Referenced by I2C1_start(), I2C2_start(), I2C_readFrom(), I2C_send(), I2C_sendID(), I2C_writeTo(), and PCF8574_write().
{
    I2C_idle(); // Wait module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.SEN = 1; // Send start bit
    while (SSPCON2bits.SEN); // Wait until SEN is cleared
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_stop ()
Definition at line 403 of file i2c.c.
References I2C_idle.
Referenced by I2C1_stop(), I2C2_stop(), I2C_get(), I2C_readFrom(), I2C_send(), I2C_writeTo(), and PCF8574_write().
{
    I2C_idle(); // Wait module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.PEN = 1; // Send stop bit
    while (SSPCON2bits.PEN); // Wait until PEN is cleared
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
u8 I2C_transmit (const u8 * , u8)
Referenced by I2C_inBuffer(), I2C_inBufferS(), and I2C_inBufferStr().
u8 I2C_write (u8)
Definition at line 256 of file i2c.c.
References I2C_idle.
Referenced by I2C1_write(), I2C2_write(), I2C_readFrom(), I2C_writeTo(), and PCF8574_write().
{
    I2C_idle(); // Wait the MSSP module is inactive
    SSPBUF = value; // Write byte to SSPBUF (BF is set to 1)
    I2C_idle(); // Wait the MSSP module is inactive
/*
    while (SSPCON1bits.WCOL) // Send again if write collision occurred
    {
        LATCbits.LATC2 = 1;
        SSPCON1bits.WCOL = 0; // Must be cleared by software
        SSPBUF = value; // Write byte to SSPBUF (BF is set to 1)
    }
*/
// while (SSPSTATbits.BF); // Wait until buffer is empty (BF set to 0)
    // ACKSTAT can be returned now because it was loaded before BF was cleared
    return (!SSPCON2bits.ACKSTAT); // 1 if Ack, 0 if NAck
}
u8 I2C_writeTo (u8 address, u8 * data, u8 length, u8 wait, u8 sendStop)
Definition at line 195 of file i2cmaster.c.
References _I2CBUFFERLENGTH_, I2C_MTX, I2C_READY, I2C_start(), I2C_stop(), and I2C_write().
Referenced by I2C_endTransmission().
{
  u8 i;
  u8 resp_sla;
  u8 resp_dat;
  // ensure data will fit into buffer
  if(length > _I2CBUFFERLENGTH_){
    return 1;
  }
  // wait until twi is ready, become master transmitter
  while(i2c_state != I2C_READY){
    continue;
  }
  i2c_state = I2C_MTX;
  i2c_sendStop = sendStop;
  // reset error state (0xFF.. no error occured)
  i2c_error = 0xFF;
  // initialize buffer iteration vars
  _i2c_masterBufferIndex = 0;
  _i2c_masterBufferLength = length;
  
  // copy data to twi buffer
  for(i = 0; i < length; ++i){
    _i2c_masterBuffer[i] = data[i];
  }
  
  // build sla+w, slave device address + w bit
  i2c_slarw = address;
  // if we're in a repeated start, then we've already sent the START
  // in the ISR. Don't do it again.
  //
  if (i2c_inRepStart == true) {
    // if we're in the repeated start state, then we've already sent the start,
    // (@@@ we hope), and the TWI statemachine is just waiting for the address byte.
    // We need to remove ourselves from the repeated start state before we enable interrupts,
    // since the ISR is ASYNC, and we could get confused if we hit the ISR before cleaning
    // up. Also, don't enable the START interrupt. There may be one pending from the
    // repeated start that we sent outselves, and that would really confuse things.
    i2c_inRepStart = false; // remember, we're dealing with an ASYNC ISR
    resp_sla = I2C_write(i2c_slarw);
  }
  else {
    // send start condition
    I2C_start();
    resp_sla = I2C_write(i2c_slarw);
 }
if(resp_sla) {
//addr ack
    while(_i2c_masterBufferIndex < _i2c_masterBufferLength){
        // copy data to output register and ack
        resp_dat= I2C_write(_i2c_masterBuffer[_i2c_masterBufferIndex++]);
        if (!resp_dat) {
          break;
        }
    }
    
    if (i2c_sendStop)
          I2C_stop();
    else {
      i2c_inRepStart = true; // we're gonna send the START
      // don't enable the interrupt. We'll generate the start, but we
      // avoid handling the interrupt until we're in the next transaction,
      // at the point where we would normally issue the start.
    }
    i2c_state = I2C_READY;
}
  if (i2c_error == 0xFF)
    return 0; // success
  else
    return 4; // i2c error
}
int peek (void)
Definition at line 522 of file i2cmaster.c.
{
  int value = -1;
  
  if(_i2c_rxBufferIndex < _i2c_rxBufferLength){
    value = _i2c_rxBuffer[_i2c_rxBufferIndex];
  }
  return value;
}