/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/i2cslave.c File Reference
#include <delay.h>
*
Macros
#define I2C_BUFFER_SIZE 32
#define LA7 LATBbits.LATB7
Functions
void receiveEvent (u8)
void requestEvent (void)
void i2c_hw_slave_init (u8 height_bits_icaddress)
u8 i2c_hw_slave_read_i2c ()
void i2c_hw_slave_write_i2c (u8 what)
void i2c_call_process_message ()
void i2c_call_process_message2 ()
void i2c_hw_slave_on_error ()
void i2c_hw_slave_on_start ()
void i2c_hw_slave_on_stop ()
void i2c_hw_slave_on_state_1 (u8 _trash)
void i2c_hw_slave_on_state_2 (u8 rcv)
void i2c_hw_slave_on_state_3 ()
void i2c_hw_slave_on_state_4 ()
void i2c_hw_slave_on_state_5 ()
Variables
u8 i2c_datapresent
Macro Definition Documentation
#define I2C_BUFFER_SIZE 32
Definition at line 16 of file i2cslave.c.
Referenced by i2c_hw_slave_on_state_2().
#define LA7 LATBbits.LATB7
Definition at line 17 of file i2cslave.c.
Referenced by i2c_hw_slave_on_error().
Function Documentation
void i2c_call_process_message ()
Definition at line 83 of file i2cslave.c.
References i2c_datapresent.
Referenced by i2c_hw_slave_on_state_1(), and i2c_hw_slave_on_stop().
{
   // let user process buffer
   if (i2c_datapresent)
   {
      _i2c_rxBufferIndex=0;
      _i2c_onReceive_function(_i2c_rxBufferLength);
      i2c_datapresent = 0;
      _i2c_rxBufferLength = 0;
      _i2c_rxBufferIndex=0;
  }
}
void i2c_call_process_message2 ()
Definition at line 97 of file i2cslave.c.
Referenced by i2c_hw_slave_on_state_3().
{
//when master requests data
    _i2c_txBufferIndex = 0;
    _i2c_txBufferLength = 0;
    _i2c_onRequest_function(); // call to slave to get data
   while (!_i2c_txBufferLength);
}
void i2c_hw_slave_init (u8 height_bits_icaddress)
Definition at line 29 of file i2cslave.c.
References _I2CBUFFERLENGTH_, and i2c_datapresent.
Referenced by I2C_begin().
{
u8 i;
   // only slave 7bit address
   SSPCON1 = 0b00110110;
   SSPCON1 = SSPCON1 | 0b00001000; // enable start/stop interrupts
    // I2C slave hardware
    // This address must not be one bit left-shifted when used for R/W operations
    SSPADD = height_bits_icaddress;
    // init SSPSTAT
    SSPSTATbits.BF = 0;
    SSPCON1bits.WCOL = 0;
    SSPCON1bits.SSPOV = 0;
    PIR1bits.SSPIF = 0;
    // enable interrupts
    PIE1bits.SSPIE = 1;
    INTCONbits.GIE = 1;
    INTCONbits.PEIE = 1;
    
    _i2c_rxBufferIndex = 0;
    _i2c_txBufferIndex = 0;
    _i2c_rxBufferLength = 0;
    i2c_datapresent=0; //received data
    _i2c_txBufferLength = 0;
   for (i=0;i< _I2CBUFFERLENGTH_;i++) {_i2c_rxBuffer[i]=0; _i2c_txBuffer[i]=0;}
}
void i2c_hw_slave_on_error ()
Definition at line 109 of file i2cslave.c.
References LA7.
{
while(1) {LA7=!LA7; delay10ktcy(500);}
   // Just tell user user something's got wrong
}
void i2c_hw_slave_on_start ()
Definition at line 114 of file i2cslave.c.
{
}
void i2c_hw_slave_on_state_1 (u8 _trash)
Definition at line 124 of file i2cslave.c.
References i2c_call_process_message().
{
   // let user process buffer (there should not be one if the proper procedure is executed)
   i2c_call_process_message();
}
void i2c_hw_slave_on_state_2 (u8 rcv)
Definition at line 131 of file i2cslave.c.
References I2C_BUFFER_SIZE, and i2c_datapresent.
{
   i2c_datapresent = 1; // Indicate we received data
   // store data
   _i2c_rxBuffer[_i2c_rxBufferIndex] = rcv;
   if (_i2c_rxBufferIndex < I2C_BUFFER_SIZE)
      _i2c_rxBufferIndex++; // point to next position
   _i2c_rxBufferLength = _i2c_rxBufferIndex;
}
void i2c_hw_slave_on_state_3 ()
Definition at line 145 of file i2cslave.c.
References i2c_call_process_message2(), and i2c_hw_slave_write_i2c().
{ // let user process buffer
     i2c_call_process_message2();
   // send first byte to master
   i2c_hw_slave_write_i2c(_i2c_txBuffer[0]); // send first databyte
   _i2c_txBufferIndex = 1; // point to next position
}
void i2c_hw_slave_on_state_4 ()
Definition at line 156 of file i2cslave.c.
References _I2CBUFFERLENGTH_, and i2c_hw_slave_write_i2c().
{
   i2c_hw_slave_write_i2c(_i2c_txBuffer[_i2c_txBufferIndex]); // send data
   if (_i2c_txBufferIndex < _I2CBUFFERLENGTH_)
      _i2c_txBufferIndex++; // point to next position
}
void i2c_hw_slave_on_state_5 ()
Definition at line 169 of file i2cslave.c.
{ // data = 0
}
void i2c_hw_slave_on_stop ()
Definition at line 118 of file i2cslave.c.
References i2c_call_process_message().
{ // let user process buffer
   i2c_call_process_message();
}
u8 i2c_hw_slave_read_i2c ()
Definition at line 60 of file i2cslave.c.
{ u8 tmpbuf;
    tmpbuf = SSPBUF;
    return tmpbuf;
}
void i2c_hw_slave_write_i2c (u8 what)
Definition at line 68 of file i2cslave.c.
Referenced by i2c_hw_slave_on_state_3(), and i2c_hw_slave_on_state_4().
{ u8 dosend;
   while (SSPSTATbits.BF);
    dosend = 1;
    while (dosend) {
        SSPCON1bits.WCOL = 0;
        // try to write into buffer, checking collision
        SSPBUF = what;
        if (! SSPCON1bits.WCOL)
            dosend = 0;
    }
    SSPCON1bits.CKP = 1;
}
void receiveEvent (u8)
void requestEvent (void)
Variable Documentation
u8 i2c_datapresent
Definition at line 23 of file i2cslave.c.
Referenced by i2c_call_process_message(), i2c_hw_slave_init(), and i2c_hw_slave_on_state_2().