/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/ili9325.h File Reference
#include <digitalw.c>
*
#include <macro.h>
*
Data Structures
struct coord_t
struct font_t
struct color_t
struct rect_t
union word_t
struct lcd_t
Macros
#define DriverCodeRead 0x00
#define DriverOutputControl 0x01
#define LCDDrivingWaveControl 0x02
#define EntryMode 0x03
#define ResizingControlRegister 0x04
#define DisplayControl1 0x07
#define DisplayControl2 0x08
#define DisplayControl3 0x09
#define DisplayControl4 0x0A
#define RGBDisplayInterfaceControl1 0x0C
#define FrameMarkerPosition 0x0D
#define RGBDisplayInterfaceControl2 0x0F
#define PowerControl1 0x10
#define PowerControl2 0x11
#define PowerControl3 0x12
#define PowerControl4 0x13
#define GRAMHorizontalAddressSet 0x20
#define GRAMVerticalAddressSet 0x21
#define WriteDatatoGRAM 0x22
#define ReadDatatoGRAM 0x22
#define PowerControl7 0x29
#define FrameRateandColorControl 0x2B
#define GammaControl1 0x30
#define GammaControl2 0x31
#define GammaControl3 0x32
#define GammaControl4 0x35
#define GammaControl5 0x36
#define GammaControl6 0x37
#define GammaControl7 0x38
#define GammaControl8 0x39
#define GammaControl9 0x3C
#define GammaControl10 0x3D
#define HorizontalRAMStartAddressPosition 0x50
#define HorizontalRAMEndAddressPosition 0x51
#define VerticalRAMStartAddressPosition 0x52
#define VerticalRAMEndAddressPosition 0x53
#define DriverOutputControl2 0x60
#define BaseImageDisplayControl 0x61
#define VerticalScrollControl 0x6A
#define PartialImage1DisplayPosition 0x80
#define PartialImage1RAMStartAddress 0x81
#define PartialImage1RAMEndAddress 0x82
#define PartialImage2DisplayPosition 0x83
#define PartialImage2RAMStartAddress 0x84
#define PartialImage2RAMEndAddress 0x85
#define PanelInterfaceControl1 0x90
#define PanelInterfaceControl2 0x92
#define PanelInterfaceControl3 0x93
#define PanelInterfaceControl4 0x95
#define PanelInterfaceControl5 0x97
#define PanelInterfaceControl6 0x98
#define OTPVCMProgrammingControl 0xA1
#define OTPVCMStatusandEnable 0xA2
#define OTPProgrammingIDKey 0xA5
#define PORTRAIT 100
#define LANDSCAPE 101
#define White 0xFFFF
#define Black 0x0000
#define Grey 0xF7DE
#define Blue 0x001F
#define Blue2 0x051F
#define Red 0xF800
#define Magenta 0xF81F
#define Green 0x07E0
#define Cyan 0x7FFF
#define Yellow 0xFFE0
#define BLACK 0b0000000000000000
#define BRIGHTBLUE 0b0000000000011111
#define BRIGHTGREEN 0b0000011111100000
#define BRIGHTCYAN 0b0000011111111111
#define BRIGHTRED 0b1111100000000000
#define BRIGHTMAGENTA 0b1111100000011111
#define BRIGHTYELLOW 0b1111111111100000
#define BLUE 0b0000000000010000
#define GREEN 0b0000010000000000
#define CYAN 0b0000010000010000
#define RED 0b1000000000000000
#define MAGENTA 0b1000000000010000
#define BROWN 0b1111110000000000
#define LIGHTGRAY 0b1000010000010000
#define DARKGRAY 0b0100001000001000
#define LIGHTBLUE 0b1000010000011111
#define LIGHTGREEN 0b1000011111110000
#define LIGHTCYAN 0b1000011111111111
#define LIGHTRED 0b1111110000010000
#define LIGHTMAGENTA 0b1111110000011111
#define YELLOW 0b1111111111110000
#define ORANGE 0b1111101111100000
#define WHITE 0b1111111111111111
#define GRAY0 0b1110011100011100
#define GRAY1 0b1100011000011000
#define GRAY2 0b1010010100010100
#define GRAY3 0b1000010000010000
#define GRAY4 0b0110001100001100
#define GRAY5 0b0100001000001000
#define GRAY6 0b0010000100000100
Functions
void ILI9325_writeRegister (u8)
void ILI9325_writeData (u16)
void ILI9325_write (u8, u16)
u16 ILI9325_readData ()
u16 ILI9325_read (u8)
u16 ILI9325_getDevice ()
u16 ILI9325_color565 (u8, u8, u8)
void ILI9325_setColor (u16)
void ILI9325_setBackgroundColor (u16)
void ILI9325_setCursor (u16, u16)
void ILI9325_setWindow (u16, u16, u16, u16)
void ILI9325_setPortrait ()
void ILI9325_setLandscape ()
u16 ILI9325_getScreenWidth ()
u16 ILI9325_getScreenHeight ()
const u8 ILI9325_getFontWidth ()
const u8 ILI9325_getFontHeight ()
void ILI9325_drawPixel (u16, u16)
u16 ILI9325_readPixel (u16, u16)
void ILI9325_clearScreen ()
void ILI9325_scroll (u16)
void ILI9325_init ()
void ILI9325_enterSleep ()
void ILI9325_exitSleep ()
Variables
lcd_t ILI9325
Macro Definition Documentation
#define BaseImageDisplayControl 0x61
Definition at line 81 of file ili9325.h.
Referenced by ILI9325_init().
#define Black 0x0000
Definition at line 110 of file ili9325.h.
#define BLACK 0b0000000000000000
Definition at line 120 of file ili9325.h.
Referenced by DrawBitmap(), FillRect(), Init(), PutChar(), and SetDot().
#define Blue 0x001F
Definition at line 112 of file ili9325.h.
Referenced by ILI9325_init(), and ILI9325_test().
#define BLUE 0b0000000000010000
Definition at line 127 of file ili9325.h.
#define Blue2 0x051F
Definition at line 113 of file ili9325.h.
#define BRIGHTBLUE 0b0000000000011111
Definition at line 121 of file ili9325.h.
#define BRIGHTCYAN 0b0000011111111111
Definition at line 123 of file ili9325.h.
#define BRIGHTGREEN 0b0000011111100000
Definition at line 122 of file ili9325.h.
#define BRIGHTMAGENTA 0b1111100000011111
Definition at line 125 of file ili9325.h.
#define BRIGHTRED 0b1111100000000000
Definition at line 124 of file ili9325.h.
#define BRIGHTYELLOW 0b1111111111100000
Definition at line 126 of file ili9325.h.
#define BROWN 0b1111110000000000
Definition at line 132 of file ili9325.h.
#define Cyan 0x7FFF
Definition at line 117 of file ili9325.h.
#define CYAN 0b0000010000010000
Definition at line 129 of file ili9325.h.
#define DARKGRAY 0b0100001000001000
Definition at line 134 of file ili9325.h.
#define DisplayControl1 0x07
Definition at line 44 of file ili9325.h.
Referenced by ILI9325_enterSleep(), ILI9325_exitSleep(), and ILI9325_init().
#define DisplayControl2 0x08
Definition at line 45 of file ili9325.h.
Referenced by ILI9325_init().
#define DisplayControl3 0x09
Definition at line 46 of file ili9325.h.
Referenced by ILI9325_init().
#define DisplayControl4 0x0A
Definition at line 47 of file ili9325.h.
Referenced by ILI9325_init().
#define DriverCodeRead 0x00
Registers
Definition at line 39 of file ili9325.h.
Referenced by ILI9325_getDeviceID(), and ILI9325_init().
#define DriverOutputControl 0x01
Definition at line 40 of file ili9325.h.
Referenced by ILI9325_init(), ILI9325_setLandscape(), and ILI9325_setPortrait().
#define DriverOutputControl2 0x60
Definition at line 80 of file ili9325.h.
Referenced by ILI9325_init().
#define EntryMode 0x03
Definition at line 42 of file ili9325.h.
Referenced by ILI9325_init(), ILI9325_setLandscape(), and ILI9325_setPortrait().
#define FrameMarkerPosition 0x0D
Definition at line 49 of file ili9325.h.
Referenced by ILI9325_init().
#define FrameRateandColorControl 0x2B
Definition at line 62 of file ili9325.h.
#define GammaControl1 0x30
Definition at line 64 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl10 0x3D
Definition at line 73 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl2 0x31
Definition at line 65 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl3 0x32
Definition at line 66 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl4 0x35
Definition at line 67 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl5 0x36
Definition at line 68 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl6 0x37
Definition at line 69 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl7 0x38
Definition at line 70 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl8 0x39
Definition at line 71 of file ili9325.h.
Referenced by ILI9325_init().
#define GammaControl9 0x3C
Definition at line 72 of file ili9325.h.
Referenced by ILI9325_init().
#define GRAMHorizontalAddressSet 0x20
Definition at line 57 of file ili9325.h.
Referenced by ILI9325_init(), ILI9325_printChar(), and ILI9325_setCursor().
#define GRAMVerticalAddressSet 0x21
Definition at line 58 of file ili9325.h.
Referenced by ILI9325_init(), ILI9325_printChar(), and ILI9325_setCursor().
#define GRAY0 0b1110011100011100
Definition at line 144 of file ili9325.h.
#define GRAY1 0b1100011000011000
Definition at line 145 of file ili9325.h.
#define GRAY2 0b1010010100010100
Definition at line 146 of file ili9325.h.
#define GRAY3 0b1000010000010000
Definition at line 147 of file ili9325.h.
#define GRAY4 0b0110001100001100
Definition at line 148 of file ili9325.h.
#define GRAY5 0b0100001000001000
Definition at line 149 of file ili9325.h.
#define GRAY6 0b0010000100000100
Definition at line 150 of file ili9325.h.
#define Green 0x07E0
Definition at line 116 of file ili9325.h.
#define GREEN 0b0000010000000000
Definition at line 128 of file ili9325.h.
#define Grey 0xF7DE
Definition at line 111 of file ili9325.h.
#define HorizontalRAMEndAddressPosition 0x51
Definition at line 76 of file ili9325.h.
Referenced by ILI9325_init(), and ILI9325_setWindow().
#define HorizontalRAMStartAddressPosition 0x50
Definition at line 75 of file ili9325.h.
Referenced by ILI9325_init(), and ILI9325_setWindow().
#define LANDSCAPE 101
Definition at line 107 of file ili9325.h.
Referenced by ILI9325_setCursor(), ILI9325_setLandscape(), and setXY().
#define LCDDrivingWaveControl 0x02
Definition at line 41 of file ili9325.h.
Referenced by ILI9325_init().
#define LIGHTBLUE 0b1000010000011111
Definition at line 135 of file ili9325.h.
#define LIGHTCYAN 0b1000011111111111
Definition at line 137 of file ili9325.h.
#define LIGHTGRAY 0b1000010000010000
Definition at line 133 of file ili9325.h.
#define LIGHTGREEN 0b1000011111110000
Definition at line 136 of file ili9325.h.
#define LIGHTMAGENTA 0b1111110000011111
Definition at line 139 of file ili9325.h.
#define LIGHTRED 0b1111110000010000
Definition at line 138 of file ili9325.h.
#define Magenta 0xF81F
Definition at line 115 of file ili9325.h.
#define MAGENTA 0b1000000000010000
Definition at line 131 of file ili9325.h.
#define ORANGE 0b1111101111100000
Definition at line 141 of file ili9325.h.
#define OTPProgrammingIDKey 0xA5
Definition at line 100 of file ili9325.h.
#define OTPVCMProgrammingControl 0xA1
Definition at line 98 of file ili9325.h.
#define OTPVCMStatusandEnable 0xA2
Definition at line 99 of file ili9325.h.
#define PanelInterfaceControl1 0x90
Definition at line 91 of file ili9325.h.
Referenced by ILI9325_init().
#define PanelInterfaceControl2 0x92
Definition at line 92 of file ili9325.h.
#define PanelInterfaceControl3 0x93
Definition at line 93 of file ili9325.h.
#define PanelInterfaceControl4 0x95
Definition at line 94 of file ili9325.h.
#define PanelInterfaceControl5 0x97
Definition at line 95 of file ili9325.h.
#define PanelInterfaceControl6 0x98
Definition at line 96 of file ili9325.h.
#define PartialImage1DisplayPosition 0x80
Definition at line 84 of file ili9325.h.
Referenced by ILI9325_init().
#define PartialImage1RAMEndAddress 0x82
Definition at line 86 of file ili9325.h.
Referenced by ILI9325_init().
#define PartialImage1RAMStartAddress 0x81
Definition at line 85 of file ili9325.h.
Referenced by ILI9325_init().
#define PartialImage2DisplayPosition 0x83
Definition at line 87 of file ili9325.h.
Referenced by ILI9325_init().
#define PartialImage2RAMEndAddress 0x85
Definition at line 89 of file ili9325.h.
Referenced by ILI9325_init().
#define PartialImage2RAMStartAddress 0x84
Definition at line 88 of file ili9325.h.
Referenced by ILI9325_init().
#define PORTRAIT 100
Constants
Definition at line 106 of file ili9325.h.
Referenced by clrScr(), drawBitmap(), drawLine(), drawPixel(), fillRect(), fillScr(), ILI9325_getScreenHeight(), ILI9325_getScreenWidth(), ILI9325_init(), ILI9325_setPortrait(), myGLCD16_print(), myGLCD16w_print(), myGLCD_print(), printChar(), touch_getX(), and touch_getY().
#define PowerControl1 0x10
Definition at line 52 of file ili9325.h.
Referenced by ILI9325_enterSleep(), ILI9325_exitSleep(), and ILI9325_init().
#define PowerControl2 0x11
Definition at line 53 of file ili9325.h.
Referenced by ILI9325_enterSleep(), ILI9325_exitSleep(), and ILI9325_init().
#define PowerControl3 0x12
Definition at line 54 of file ili9325.h.
Referenced by ILI9325_enterSleep(), ILI9325_exitSleep(), and ILI9325_init().
#define PowerControl4 0x13
Definition at line 55 of file ili9325.h.
Referenced by ILI9325_enterSleep(), ILI9325_exitSleep(), and ILI9325_init().
#define PowerControl7 0x29
Definition at line 61 of file ili9325.h.
Referenced by ILI9325_exitSleep(), and ILI9325_init().
#define ReadDatatoGRAM 0x22
Definition at line 60 of file ili9325.h.
Referenced by ILI9325_readPixel().
#define Red 0xF800
Definition at line 114 of file ili9325.h.
Referenced by ILI9325_test().
#define RED 0b1000000000000000
Definition at line 130 of file ili9325.h.
#define ResizingControlRegister 0x04
Definition at line 43 of file ili9325.h.
Referenced by ILI9325_init().
#define RGBDisplayInterfaceControl1 0x0C
Definition at line 48 of file ili9325.h.
Referenced by ILI9325_init().
#define RGBDisplayInterfaceControl2 0x0F
Definition at line 50 of file ili9325.h.
Referenced by ILI9325_init().
#define VerticalRAMEndAddressPosition 0x53
Definition at line 78 of file ili9325.h.
Referenced by ILI9325_init(), and ILI9325_setWindow().
#define VerticalRAMStartAddressPosition 0x52
Definition at line 77 of file ili9325.h.
Referenced by ILI9325_init(), and ILI9325_setWindow().
#define VerticalScrollControl 0x6A
Definition at line 82 of file ili9325.h.
Referenced by ILI9325_printString(), and ILI9325_scroll().
#define White 0xFFFF
Definition at line 109 of file ili9325.h.
Referenced by ILI9325_init(), and ILI9325_test().
#define WHITE 0b1111111111111111
Definition at line 142 of file ili9325.h.
Referenced by Init().
#define WriteDatatoGRAM 0x22
Definition at line 59 of file ili9325.h.
Referenced by ILI9325_clearScreen(), ILI9325_clearWindow(), ILI9325_delPixel(), ILI9325_drawPixel(), ILI9325_printChar(), and ILI9325_test().
#define Yellow 0xFFE0
Definition at line 118 of file ili9325.h.
#define YELLOW 0b1111111111110000
Definition at line 140 of file ili9325.h.
Function Documentation
void ILI9325_clearScreen ()
Definition at line 601 of file ili9325.c.
References lcd_t::bcolor, color_t::c, c, word_t::h8, ILI9325, ILI9325_setCursor(), ILI9325_writeRegister(), word_t::l8, word_t::w, and WriteDatatoGRAM.
Referenced by ILI9325_init(), ILI9325_setLandscape(), and ILI9325_setPortrait().
{
    word_t c;
    u32 j=76800; // 240*320
    
    c.w = ILI9325.bcolor.c; // current background color
    ILI9325_setCursor(0, 0);
    /*
    if (ILI9325.orientation == PORTRAIT)
        ILI9325_setWindow(0, 0, 239, 319);
    else // if (ILI9325.orientation == LANDSCAPE)
        ILI9325_setWindow(0, 0, 319, 239);
    */
    ILI9325_writeRegister(WriteDatatoGRAM); // write GRAM
     //LowCS; // Enable LCD
    HighRS; // Disable Register Selection Signal
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    while (j--)
    {
        DATA = c.h8;
        LowWR; // Enable Write
        HighWR; // Disable Write
        
        DATA = c.l8;
        LowWR; // Enable Write
        HighWR; // Disable Write
    }
    //HighCS; // Disable LCD
}
u16 ILI9325_color565 (u8 r, u8 g, u8 b)
Color functions
Definition at line 386 of file ili9325.c.
{
/*
    u16 c;
    c = r >> 3;
    c <<= 6;
    c |= g >> 2;
    c <<= 5;
    c |= b >> 3;
    return c;
*/
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}
void ILI9325_drawPixel (u16 , u16)
Definition at line 510 of file ili9325.c.
References color_t::c, lcd_t::color, rect_t::endx, rect_t::endy, ILI9325, ILI9325_setCursor(), ILI9325_write(), lcd_t::screen, and WriteDatatoGRAM.
Referenced by drawPixel().
{
    if ((x > ILI9325.screen.endx) || (y > ILI9325.
      screen.endy)) return;
    ILI9325_setCursor(x, y);
    //LowCS; // Enable LCD
    ILI9325_write(WriteDatatoGRAM, ILI9325.
      color.c);// write color to GRAM
    //HighCS; // Disable LCD
}
void ILI9325_enterSleep ()
Definition at line 909 of file ili9325.c.
References Delayms(), DisplayControl1, ILI9325_write(), PowerControl1, PowerControl2, PowerControl3, and PowerControl4.
{
    ILI9325_write(DisplayControl1,0x0131);//setD1=0,D0=1
    Delayms(10);//Wait for 2 frames or more
    ILI9325_write(DisplayControl1,0x0130);//setD1=0,D0=0
    Delayms(10);//Wait for 2 frames or more
    ILI9325_write(DisplayControl1,0x0000);//displayoff
    //---------- Power off sequence
    ILI9325_write(PowerControl1,0x0000);//SAP,BT[3:0],AP,DSTB,SLP,STB
    ILI9325_write(PowerControl2,0x0000);//DC1[2:0],DC0[2:0],VC[2:0]
    ILI9325_write(PowerControl3,0x0000);//VREG1OUTvoltage
    ILI9325_write(PowerControl4,0x0000);//VDV[4:0]forVCOMamplitude
    Delayms(200);//dis-chargecapacitorpowervoltage
    ILI9325_write(PowerControl1,0x0002);//SAP,BT[3:0],APE,AP,DSTB,SLP
}
void ILI9325_exitSleep ()
Definition at line 933 of file ili9325.c.
References Delayms(), DisplayControl1, ILI9325_write(), PowerControl1, PowerControl2, PowerControl3, PowerControl4, and PowerControl7.
{
    //---------- Power On sequence
    ILI9325_write(PowerControl1,0x0000);// SAP, BT[3:0], AP, DSTB, SLP, STB
    ILI9325_write(PowerControl2,0x0007);//DC1[2:0], DC0[2:0], VC[2:0]
    ILI9325_write(PowerControl3,0x0000);//VREG1OUT voltage
    ILI9325_write(PowerControl4,0x0000); //VDV[4:0] for VCOM amplitude
    Delayms(200);
    ILI9325_write(PowerControl1,0x1490);//SAP, BT[3:0], AP, DSTB, SLP, STB
    ILI9325_write(PowerControl2,0x0227);//DC1[2:0], DC0[2:0], VC[2:0]
    Delayms(50);
    ILI9325_write(PowerControl3,0x001C);//External reference voltage=Vci
    Delayms(50);
    ILI9325_write(PowerControl4,0x1800);//VDV[4:0] for VCOM amplitude
    ILI9325_write(PowerControl7,0x001C);//VCM[4:0] for VCOMH
    Delayms(50);
    ILI9325_write(DisplayControl1,0x0133);//
}
u16 ILI9325_getDevice ()
const u8 ILI9325_getFontHeight ()
Definition at line 789 of file ili9325.c.
Referenced by ILI9325_init(), and ILI9325_setPortrait().
{
    return Display_getFontHeight();
}
const u8 ILI9325_getFontWidth ()
Print functions
Definition at line 784 of file ili9325.c.
Referenced by ILI9325_init(), and ILI9325_setPortrait().
{
    return Display_getFontWidth();
}
u16 ILI9325_getScreenHeight ()
Definition at line 748 of file ili9325.c.
References rect_t::height, ILI9325, lcd_t::orientation, PORTRAIT, lcd_t::screen, and rect_t::width.
{
    if (ILI9325.orientation == PORTRAIT)
        return ILI9325.screen.height;
    else // if (ILI9325.orientation == LANDSCAPE)
        return ILI9325.screen.width;
}
u16 ILI9325_getScreenWidth ()
Definition at line 740 of file ili9325.c.
References rect_t::height, ILI9325, lcd_t::orientation, PORTRAIT, lcd_t::screen, and rect_t::width.
{
    if (ILI9325.orientation == PORTRAIT)
        return ILI9325.screen.width;
    else // if (ILI9325.orientation == LANDSCAPE)
        return ILI9325.screen.height;
}
void ILI9325_init ()
---------- Default Screen Values
---------- IO's Output by default
---------- Clear Command lines
---------- Idle
---------- Reset LCD Driver
---------- Start Initial Sequence
---------- Power On sequence
---------- Adjust the Gamma Curve
---------- Set GRAM area
---------- Partial Display Control
---------- Panel Control
---------- Default settings
Definition at line 217 of file ili9325.c.
References BaseImageDisplayControl, Blue, lcd_t::cursor, Delayms(), DisplayControl1, DisplayControl2, DisplayControl3, DisplayControl4, DriverCodeRead, DriverOutputControl, DriverOutputControl2, rect_t::endx, rect_t::endy, EntryMode, lcd_t::font, FrameMarkerPosition, GammaControl1, GammaControl10, GammaControl2, GammaControl3, GammaControl4, GammaControl5, GammaControl6, GammaControl7, GammaControl8, GammaControl9, GRAMHorizontalAddressSet, GRAMVerticalAddressSet, font_t::height, rect_t::height, HorizontalRAMEndAddressPosition, HorizontalRAMStartAddressPosition, ILI9325, ILI9325_clearScreen(), ILI9325_getFontHeight(), ILI9325_getFontWidth(), ILI9325_setBackgroundColor(), ILI9325_setColor(), ILI9325_setPortrait(), ILI9325_write(), LCDDrivingWaveControl, lcd_t::orientation, OUTPUT, PanelInterfaceControl1, PartialImage1DisplayPosition, PartialImage1RAMEndAddress, PartialImage1RAMStartAddress, PartialImage2DisplayPosition, PartialImage2RAMEndAddress, PartialImage2RAMStartAddress, PORTRAIT, PowerControl1, PowerControl2, PowerControl3, PowerControl4, PowerControl7, ResizingControlRegister, RGBDisplayInterfaceControl1, RGBDisplayInterfaceControl2, lcd_t::screen, rect_t::startx, rect_t::starty, VerticalRAMEndAddressPosition, VerticalRAMStartAddressPosition, White, font_t::width, rect_t::width, coord_t::x, and coord_t::y.
{
    ILI9325.orientation = PORTRAIT;
    ILI9325.cursor.x = 0;
    ILI9325.cursor.y = 0;
    ILI9325.screen.startx = 0;
    ILI9325.screen.starty = 0;
    ILI9325.screen.endx = 239;
    ILI9325.screen.endy = 319;
    ILI9325.screen.width = 240;
    ILI9325.screen.height = 320;
    ILI9325.font.width = ILI9325_getFontWidth();
    ILI9325.font.height = ILI9325_getFontHeight();
    dDATA = OUTPUT;
    dCMD1 = OUTPUT;
    dCMD2 = OUTPUT;
    DATA = 0x00;
    HighCS;
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    HighRST;
    Delayms(5); // 1ms min.
    LowRST;
    Delayms(2); // no min.
    HighRST;
    Delayms(100); // 50ms min.
    LowCS; // Enable LCD -> not needed if CS is connected to GND
    //---------- Start internal oscillator
    ILI9325_write(DriverCodeRead, 0x0001);
    Delayms(50);
    // SS = 1 (shift dir. to the right)
    ILI9325_write(DriverOutputControl, 0x0100);
    // B/C = 1
    // EOR = 1
    ILI9325_write(LCDDrivingWaveControl, 0x0700); // set the line
       inversion
    // AM = 0
    // I/D = 11 (H and V increment)
    // BGR = 1 (Swap the RGB data to BGR in writing into GRAM)
    ILI9325_write(EntryMode, 0x1030); //set GRAM write direction and BGR=1
       PORTRAIT MODE
    ILI9325_write(ResizingControlRegister, 0x0000);
    ILI9325_write(DisplayControl2, 0x0202); // set the back and front porch to
       4 lines
    ILI9325_write(DisplayControl3, 0x0000); // set non-display area refresh
       cycle ISC[3:0]
    ILI9325_write(DisplayControl4, 0x0000); // FMARK function
    ILI9325_write(RGBDisplayInterfaceControl1, 0x0000); // RGB
       interface setting
    ILI9325_write(FrameMarkerPosition, 0x0000); // Frame marker Position
    ILI9325_write(RGBDisplayInterfaceControl2, 0x0000); // RGB
       interface polarity
    ILI9325_write(PowerControl1, 0x0000); // SAP, BT[3:0], AP, DSTB, SLP, STB
    ILI9325_write(PowerControl2, 0x0007); // DC1[2:0], DC0[2:0], VC[2:0]
    ILI9325_write(PowerControl3, 0x0000); // VREG1OUT voltage
    ILI9325_write(PowerControl4, 0x0000); // VDV[4:0] for VCOM amplitude
    //ILI9325_write(DisplayControl1, 0x0001);
    Delayms(200); // Discharge capacitor power voltage
    ILI9325_write(PowerControl1, 0x14B0); // SAP=1, BT[3:0]=110, APE=1, AP=001,
       DSTB=0, SLP=0, STB=0
    ILI9325_write(PowerControl2, 0x0007); // DC1[2:0]=010, DC0[2:0]=010,
       VC[2:0]=000
    Delayms(50);
    ILI9325_write(PowerControl3, 0x008E); // External reference voltage= Vci;
    Delayms(50);
    ILI9325_write(PowerControl4, 0x0C00); // R13=1200 when R12=009D;VDV[4:0] for
       VCOM amplitude
    ILI9325_write(PowerControl7, 0x0015); // R29=000C when R12=009D;VCM[5:0] for
       VCOMH
    //ILI9325_write(FrameRateandColorControl, 0x000D); // Set Frame Rate
    Delayms(50);
    ILI9325_write(GammaControl1, 0x0000);
    ILI9325_write(GammaControl2, 0x0502);
    ILI9325_write(GammaControl3, 0x0307);
    ILI9325_write(GammaControl4, 0x0305);
    ILI9325_write(GammaControl5, 0x0004);
    ILI9325_write(GammaControl6, 0x0402);
    ILI9325_write(GammaControl7, 0x0707);
    ILI9325_write(GammaControl8, 0x0503);
    ILI9325_write(GammaControl9, 0x1505);
    ILI9325_write(GammaControl10, 0x1505);
    ILI9325_write(GRAMHorizontalAddressSet, 0x0000); // GRAM
       horizontal Address
    ILI9325_write(GRAMVerticalAddressSet, 0x0000); // GRAM
       Vertical Address
    ILI9325_write(HorizontalRAMStartAddressPosition, 0); //
       Horizontal GRAM Start Address
    ILI9325_write(HorizontalRAMEndAddressPosition, 239); //
       Horizontal GRAM End Address
    ILI9325_write(VerticalRAMStartAddressPosition, 0); //
       Vertical GRAM Start Address
    ILI9325_write(VerticalRAMEndAddressPosition, 319); //
       Vertical GRAM Start Address
    ILI9325_write(DriverOutputControl2, 0xA700); // Gate Scan Line
    ILI9325_write(BaseImageDisplayControl, 0x0003);//b111); // NDL,
       VLE, REV
    //ILI9325_write(VerticalScrollControl, 0x0000);
    
    ILI9325_write(PartialImage1DisplayPosition, 0x0000);
    ILI9325_write(PartialImage1RAMStartAddress, 0x0000);
    ILI9325_write(PartialImage1RAMEndAddress, 0x0000);
    ILI9325_write(PartialImage2DisplayPosition, 0x0000);
    ILI9325_write(PartialImage2RAMStartAddress, 0x0000);
    ILI9325_write(PartialImage2RAMEndAddress, 0x0000);
    ILI9325_write(PanelInterfaceControl1, 0x0010); // sync with fosc/1 -
       16 clocks/line
    //ILI9325_write(PanelInterfaceControl2, 0x0600); // 0 clock overlap period
// ILI9325_write(PanelInterfaceControl3, 0x0001);
// ILI9325_write(PanelInterfaceControl4, 0x0110); // 16 clocks/line - min. div. ratio
// ILI9325_write(PanelInterfaceControl5, 0x0000);
// ILI9325_write(PanelInterfaceControl6, 0x0000);
// Delayms(50);
    //---------- Display ON
    // D[1:0] = 11, display ON (00 = display OFF)
    // CL = 0, 262K color
    // GON & DET = 11, normal display
    // BASEE = 1, the base image is displayed
    // PTDE[1:0] = 00, only base image is displayed
    ILI9325_write(DisplayControl1, 0x0133);
    //Delayms(50);
    //I9325_writeRegister(WriteDatatoGRAM); // write GRAM
    //HighCS; // Disable LCD
    ILI9325_setColor(White);
    ILI9325_setBackgroundColor(Blue);
    ILI9325_setPortrait();
    ILI9325_clearScreen();
}
u16 ILI9325_read (u8)
Definition at line 187 of file ili9325.c.
References ILI9325_readData(), and ILI9325_writeRegister().
Referenced by ILI9325_getDeviceID(), and ILI9325_readPixel().
{
    ILI9325_writeRegister(index);
    return ILI9325_readData();
}
u16 ILI9325_readData ()
Read functions
Definition at line 147 of file ili9325.c.
References word_t::h8, word_t::l8, and word_t::w.
Referenced by ILI9325_read().
{
    word_t d;
    
    //LowCS; // Select LCD
    HighRS; // Disable Register Selection Signal
    HighWR; // Disable Write Mode
    HighRD; // Disable Read (Write Mode)
    // Data line as input
    dDATA = 0xFF;
    LowRD; // Enable Read Mode
    HighRD; // Disable Read Mode
    
    d.h8 = DATA; // Read High Byte Data
    LowRD; // Enable Read Mode
    HighRD; // Disable Read Mode
    d.l8 = DATA; // Read Low Byte Data
    // Data line as output
    dDATA = 0x00;
    //HighCS; // Release LCD
    return d.w;
}
u16 ILI9325_readPixel (u16 , u16)
Definition at line 547 of file ili9325.c.
References c, rect_t::endx, rect_t::endy, ILI9325, ILI9325_read(), ILI9325_setCursor(), ReadDatatoGRAM, and lcd_t::screen.
{
    u16 c;
    
    if ((x > ILI9325.screen.endx) || (y > ILI9325.
      screen.endy)) return 0;
    ILI9325_setCursor(x, y);
    //LowCS;
    c = ILI9325_read(ReadDatatoGRAM);
    //HighCS;
    
    return c;
}
void ILI9325_scroll (u16)
Definition at line 765 of file ili9325.c.
References ILI9325_write(), VerticalScrollControl, and y.
{
    u16 y = pixels;
    while (y < 0)
        y += 320;
    while (y >= 320)
        y -= 320;
    //LowCS; // Enable LCD
    ILI9325_write(VerticalScrollControl, y);
    //HighCS; // Disable LCD
}
void ILI9325_setBackgroundColor (u16)
Definition at line 428 of file ili9325.c.
References color_t::b, lcd_t::bcolor, color_t::c, color_t::g, ILI9325, and color_t::r.
Referenced by ILI9325_init().
{
    ILI9325.bcolor.r = (color >> 11) & 0x1f;
    ILI9325.bcolor.g = (color >> 5) & 0x3f;
    ILI9325.bcolor.b = (color >> 0) & 0x1f;
    ILI9325.bcolor.c = color; // ILI9325_color565(r,g,b);
}
void ILI9325_setColor (u16)
Definition at line 411 of file ili9325.c.
References color_t::b, color_t::c, lcd_t::color, color_t::g, ILI9325, and color_t::r.
Referenced by ILI9325_init().
{
    ILI9325.color.r = (color >> 11) & 0x1f;
    ILI9325.color.g = (color >> 5) & 0x3f;
    ILI9325.color.b = (color >> 0) & 0x1f;
    ILI9325.color.c = color; // ILI9325_color565(r,g,b);
}
void ILI9325_setCursor (u16 x, u16 y)
Graphic functions
Definition at line 482 of file ili9325.c.
References lcd_t::cursor, GRAMHorizontalAddressSet, GRAMVerticalAddressSet, ILI9325, ILI9325_write(), LANDSCAPE, lcd_t::orientation, coord_t::x, x, coord_t::y, and y.
Referenced by ILI9325_clearScreen(), ILI9325_clearWindow(), ILI9325_delPixel(), ILI9325_drawPixel(), ILI9325_readPixel(), ILI9325_setWindow(), and ILI9325_test().
{
    if (ILI9325.orientation == LANDSCAPE)
    {
        ILI9325.cursor.x = y; // save current position
        ILI9325.cursor.y = x;
    }
    else
    {
        ILI9325.cursor.x = x; // save current position
        ILI9325.cursor.y = y;
    }
    
    //LowCS; // Enable LCD
    ILI9325_write(GRAMHorizontalAddressSet,
      ILI9325.cursor.x);
    ILI9325_write(GRAMVerticalAddressSet,
      ILI9325.cursor.y);
    //HighCS; // Disable LCD
}
void ILI9325_setLandscape ()
Definition at line 718 of file ili9325.c.
References DriverOutputControl, EntryMode, ILI9325, ILI9325_clearScreen(), ILI9325_setWindow(), ILI9325_write(), LANDSCAPE, and lcd_t::orientation.
{
    ILI9325.orientation = LANDSCAPE;
    //ILI9325.font.width = ILI9325_getFontHeight();
    //ILI9325.font.height= ILI9325_getFontWidth();
    //LowCS;
    ILI9325_write(EntryMode, 0x1028); // 0x28 = 0b00101000;
    // shift dir. to the right (SM=0, SS=0)
    ILI9325_write(DriverOutputControl, 0x0000);
    //HighCS;
    
    //ILI9325_setCursor(0, 0);
    ILI9325_setWindow(0, 0, 319, 239);
    ILI9325_clearScreen();
}
void ILI9325_setPortrait ()
Definition at line 700 of file ili9325.c.
References DriverOutputControl, EntryMode, lcd_t::font, font_t::height, ILI9325, ILI9325_clearScreen(), ILI9325_getFontHeight(), ILI9325_getFontWidth(), ILI9325_setWindow(), ILI9325_write(), lcd_t::orientation, PORTRAIT, and font_t::width.
Referenced by ILI9325_init().
{
    ILI9325.orientation = PORTRAIT;
    ILI9325.font.width = ILI9325_getFontWidth();
    ILI9325.font.height= ILI9325_getFontHeight();
    //LowCS;
    // set GRAM write direction to PORTRAIT MODE
    ILI9325_write(EntryMode, 0x1030); // 0x30 = 0b00110000;
    // shift dir. to the right (SM=0, SS=1)
    ILI9325_write(DriverOutputControl, 0x0100);
    //HighCS;
    
    //ILI9325_setCursor(0, 0);
    ILI9325_setWindow(0, 0, 239, 319);
    ILI9325_clearScreen();
}
void ILI9325_setWindow (u16 , u16 , u16 , u16)
Definition at line 572 of file ili9325.c.
References rect_t::endx, rect_t::endy, rect_t::height, HorizontalRAMEndAddressPosition, HorizontalRAMStartAddressPosition, ILI9325, ILI9325_setCursor(), ILI9325_write(), lcd_t::screen, rect_t::startx, rect_t::starty, VerticalRAMEndAddressPosition, VerticalRAMStartAddressPosition, and rect_t::width.
Referenced by ILI9325_setLandscape(), and ILI9325_setPortrait().
{
    ILI9325.screen.startx = x1;
    ILI9325.screen.starty = y1;
    ILI9325.screen.endx = x2;
    ILI9325.screen.endy = y2;
    ILI9325.screen.width = x2 - x1;
    ILI9325.screen.height = y2 - y1;
    
    //LowCS; // Enable LCD
    ILI9325_write(HorizontalRAMStartAddressPosition, x1);
    ILI9325_write(HorizontalRAMEndAddressPosition, x2);
    ILI9325_write(VerticalRAMStartAddressPosition, y1);
    ILI9325_write(VerticalRAMEndAddressPosition, y2);
    //HighCS; // Disable LCD
    ILI9325_setCursor(x1, y1);
}
void ILI9325_write (u8 , u16)
Definition at line 126 of file ili9325.c.
References ILI9325_writeData(), and ILI9325_writeRegister().
Referenced by ILI9325_delPixel(), ILI9325_drawPixel(), ILI9325_enterSleep(), ILI9325_exitSleep(), ILI9325_init(), ILI9325_printChar(), ILI9325_printString(), ILI9325_scroll(), ILI9325_setCursor(), ILI9325_setLandscape(), ILI9325_setPortrait(), and ILI9325_setWindow().
{
    ILI9325_writeRegister(index);
    ILI9325_writeData(data15);
}
void ILI9325_writeData (u16)
Definition at line 92 of file ili9325.c.
References word_t::h8, word_t::l8, and word_t::w.
Referenced by ILI9325_test(), and ILI9325_write().
{
    word_t d;
    d.w = data15;
    //LowCS;
    HighRS; // Disable Register Selection Signal
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    DATA = d.h8;
    LowWR; // Enable Write
    HighWR; // Disable Write
    DATA = d.l8;
    LowWR; // Enable Write
    HighWR; // Disable Write
    //HighCS;
}
void ILI9325_writeRegister (u8 index)
PIC 26J50 47J53A 32MX250 EMPEROR LCD pin
VSS GND GND GND GND GND +5V 5V VIN VDD 5V 5V
- - - - - nc
PMA0 8 5 26 RS Register Selection PMWR 9 14 64 RW Write: Low=Enable, High=Disable
PMRD 10 13 63 RD Read: Low=Enable, High=Disable
PMD0 0 24 54 D0 Display data, LSB PMD1 1 25 53 D1 Display data PMD2 2 26 49 D2 Display data PMD3 3 27 48 D3 Display data PMD4 4 28 47 D4 Display data PMD5 5 29 45 D5 Display data PMD6 6 30 44 D6 Display data
PMD7 7 31 43 D7 Display data, MSB
PMA1 11 4 74 CS Low=Select, High=Deselect
- - - nc PMA2 12 4 RST Low=Reset, High=no Reset
- - - - nc
Prototypes
Write functions
Definition at line 59 of file ili9325.c.
Referenced by ILI9325_clearScreen(), ILI9325_clearWindow(), ILI9325_read(), ILI9325_test(), and ILI9325_write().
{
    //LowCS;
    LowRS; // Enable Register Selection Signal
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    DATA = 0;
    
    LowWR; // Enable Write
    HighWR; // Disable Write
    DATA = index;
    LowWR; // Enable Write
    HighWR; // Disable Write
    //HighCS;
}
Variable Documentation
lcd_t ILI9325
Globals
Definition at line 404 of file ili9325.h.
Referenced by ILI9325_clearScreen(), ILI9325_clearWindow(), ILI9325_delPixel(), ILI9325_drawPixel(), ILI9325_getOrientation(), ILI9325_getScreenHeight(), ILI9325_getScreenWidth(), ILI9325_init(), ILI9325_printChar(), ILI9325_printString(), ILI9325_readPixel(), ILI9325_setBackgroundColor(), ILI9325_setColor(), ILI9325_setCursor(), ILI9325_setLandscape(), ILI9325_setPortrait(), ILI9325_setWindow(), and ILI9325_test().