/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/ili9325.c File Reference
#include <stdarg.h>
*
#include <typedef.h>
*
#include <macro.h>
*
#include <ili9325.h>
*
#include <fonts/font12x8.h>
*
#include <delayms.c>
*
#include <graphics.c>
*
#include <digitalw.c>
*
#include <stdio.c>
*
Macros
#define __ILI9325_C
Functions
void ILI9325_writeRegister (u8 index)
void ILI9325_writeData (u16 data15)
void ILI9325_write (u8 index, u16 data15)
u16 ILI9325_readData ()
u16 ILI9325_read (u8 index)
u16 ILI9325_getDeviceID ()
void ILI9325_init ()
u16 ILI9325_color565 (u8 r, u8 g, u8 b)
void ILI9325_setColor (u16 color)
void ILI9325_setBackgroundColor (u16 color)
void ILI9325_test (void)
void ILI9325_setCursor (u16 x, u16 y)
void ILI9325_drawPixel (u16 x, u16 y)
void ILI9325_delPixel (u16 x, u16 y)
u16 ILI9325_readPixel (u16 x, u16 y)
void ILI9325_setWindow (u16 x1, u16 y1, u16 x2, u16 y2)
void ILI9325_clearScreen ()
void ILI9325_clearWindow (u16 x1, u16 y1, u16 x2, u16 y2)
void ILI9325_setPortrait ()
void ILI9325_setLandscape ()
u8 ILI9325_getOrientation ()
u16 ILI9325_getScreenWidth ()
u16 ILI9325_getScreenHeight ()
void ILI9325_scroll (u16 pixels)
const u8 ILI9325_getFontWidth ()
const u8 ILI9325_getFontHeight ()
void ILI9325_printChar (u8 c, u16 x, u16 y)
void ILI9325_printString (u8 *s)
void ILI9325_printf (const u8 *fmt,...)
void ILI9325_enterSleep ()
void ILI9325_exitSleep ()
void drawPixel (u16 x, u16 y)
void ILI9325_drawCircle (u16 x, u16 y, u16 radius)
void ILI9325_fillCircle (u16 x, u16 y, u16 radius)
void ILI9325_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
void ILI9325_drawBitmap (u16 x, u16 y, u16 w, u16 h, u16 *bitmap)
Macro Definition Documentation
#define __ILI9325_C
Definition at line 27 of file ili9325.c.
Function Documentation
void drawPixel (u16 x, u16 y)
Definition at line 960 of file ili9325.c.
{
    ILI9325_drawPixel(x, y);
}
void ILI9325_clearScreen ()
Definition at line 601 of file ili9325.c.
References lcd_t::bcolor, color_t::c, c, word_t::h8, ILI9325, ILI9325_setCursor(), ILI9325_writeRegister(), word_t::l8, word_t::w, and WriteDatatoGRAM.
Referenced by ILI9325_init(), ILI9325_setLandscape(), and ILI9325_setPortrait().
{
    word_t c;
    u32 j=76800; // 240*320
    
    c.w = ILI9325.bcolor.c; // current background color
    ILI9325_setCursor(0, 0);
    /*
    if (ILI9325.orientation == PORTRAIT)
        ILI9325_setWindow(0, 0, 239, 319);
    else // if (ILI9325.orientation == LANDSCAPE)
        ILI9325_setWindow(0, 0, 319, 239);
    */
    ILI9325_writeRegister(WriteDatatoGRAM); // write GRAM
     //LowCS; // Enable LCD
    HighRS; // Disable Register Selection Signal
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    while (j--)
    {
        DATA = c.h8;
        LowWR; // Enable Write
        HighWR; // Disable Write
        
        DATA = c.l8;
        LowWR; // Enable Write
        HighWR; // Disable Write
    }
    //HighCS; // Disable LCD
}
void ILI9325_clearWindow (u16 x1, u16 y1, u16 x2, u16 y2)
Definition at line 647 of file ili9325.c.
References lcd_t::bcolor, color_t::c, c, word_t::h8, ILI9325, ILI9325_setCursor(), ILI9325_writeRegister(), word_t::l8, word_t::w, and WriteDatatoGRAM.
{
    word_t c;
    u32 j=((x2-x1+1)*(y2-y1+1)); // height * width
    
    c.w = ILI9325.bcolor.c; // current background color
    ILI9325_setCursor(x1, y1);
    ILI9325_writeRegister(WriteDatatoGRAM); // write GRAM
    //LowCS; // Enable LCD
    HighRS; // Disable Register Selection Signal
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    while (j--)
    {
        DATA = c.h8;
        LowWR; // Enable Write
        HighWR; // Disable Write
        DATA = c.l8;
        LowWR; // Enable Write
        HighWR; // Disable Write
    }
    //HighCS; // Disable LCD
}
u16 ILI9325_color565 (u8 r, u8 g, u8 b)
Color functions
Definition at line 386 of file ili9325.c.
{
/*
    u16 c;
    c = r >> 3;
    c <<= 6;
    c |= g >> 2;
    c <<= 5;
    c |= b >> 3;
    return c;
*/
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}
void ILI9325_delPixel (u16 x, u16 y)
Definition at line 528 of file ili9325.c.
References lcd_t::bcolor, color_t::c, rect_t::endx, rect_t::endy, ILI9325, ILI9325_setCursor(), ILI9325_write(), lcd_t::screen, and WriteDatatoGRAM.
{
    if ((x > ILI9325.screen.endx) || (y > ILI9325.
      screen.endy)) return;
    ILI9325_setCursor(x, y);
    //LowCS; // Enable LCD
    ILI9325_write(WriteDatatoGRAM, ILI9325.
      bcolor.c);// write color to GRAM
    //HighCS; // Disable LCD
}
void ILI9325_drawBitmap (u16 x, u16 y, u16 w, u16 h, u16 * bitmap)
Definition at line 980 of file ili9325.c.
References drawBitmap().
{
    drawBitmap(x, y, w, h, bitmap);
}
void ILI9325_drawCircle (u16 x, u16 y, u16 radius)
Definition at line 965 of file ili9325.c.
References drawCircle().
{
    drawCircle(x, y, radius);
}
void ILI9325_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Definition at line 975 of file ili9325.c.
References drawLine().
{
    drawLine(x0, y0, x1, y1);
}
void ILI9325_drawPixel (u16 x, u16 y)
Definition at line 510 of file ili9325.c.
References color_t::c, lcd_t::color, rect_t::endx, rect_t::endy, ILI9325, ILI9325_setCursor(), ILI9325_write(), lcd_t::screen, and WriteDatatoGRAM.
Referenced by drawPixel().
{
    if ((x > ILI9325.screen.endx) || (y > ILI9325.
      screen.endy)) return;
    ILI9325_setCursor(x, y);
    //LowCS; // Enable LCD
    ILI9325_write(WriteDatatoGRAM, ILI9325.
      color.c);// write color to GRAM
    //HighCS; // Disable LCD
}
void ILI9325_enterSleep ()
Definition at line 909 of file ili9325.c.
References Delayms(), DisplayControl1, ILI9325_write(), PowerControl1, PowerControl2, PowerControl3, and PowerControl4.
{
    ILI9325_write(DisplayControl1,0x0131);//setD1=0,D0=1
    Delayms(10);//Wait for 2 frames or more
    ILI9325_write(DisplayControl1,0x0130);//setD1=0,D0=0
    Delayms(10);//Wait for 2 frames or more
    ILI9325_write(DisplayControl1,0x0000);//displayoff
    //---------- Power off sequence
    ILI9325_write(PowerControl1,0x0000);//SAP,BT[3:0],AP,DSTB,SLP,STB
    ILI9325_write(PowerControl2,0x0000);//DC1[2:0],DC0[2:0],VC[2:0]
    ILI9325_write(PowerControl3,0x0000);//VREG1OUTvoltage
    ILI9325_write(PowerControl4,0x0000);//VDV[4:0]forVCOMamplitude
    Delayms(200);//dis-chargecapacitorpowervoltage
    ILI9325_write(PowerControl1,0x0002);//SAP,BT[3:0],APE,AP,DSTB,SLP
}
void ILI9325_exitSleep ()
Definition at line 933 of file ili9325.c.
References Delayms(), DisplayControl1, ILI9325_write(), PowerControl1, PowerControl2, PowerControl3, PowerControl4, and PowerControl7.
{
    //---------- Power On sequence
    ILI9325_write(PowerControl1,0x0000);// SAP, BT[3:0], AP, DSTB, SLP, STB
    ILI9325_write(PowerControl2,0x0007);//DC1[2:0], DC0[2:0], VC[2:0]
    ILI9325_write(PowerControl3,0x0000);//VREG1OUT voltage
    ILI9325_write(PowerControl4,0x0000); //VDV[4:0] for VCOM amplitude
    Delayms(200);
    ILI9325_write(PowerControl1,0x1490);//SAP, BT[3:0], AP, DSTB, SLP, STB
    ILI9325_write(PowerControl2,0x0227);//DC1[2:0], DC0[2:0], VC[2:0]
    Delayms(50);
    ILI9325_write(PowerControl3,0x001C);//External reference voltage=Vci
    Delayms(50);
    ILI9325_write(PowerControl4,0x1800);//VDV[4:0] for VCOM amplitude
    ILI9325_write(PowerControl7,0x001C);//VCM[4:0] for VCOMH
    Delayms(50);
    ILI9325_write(DisplayControl1,0x0133);//
}
void ILI9325_fillCircle (u16 x, u16 y, u16 radius)
Definition at line 970 of file ili9325.c.
References fillCircle().
{
    fillCircle(x, y, radius);
}
u16 ILI9325_getDeviceID ()
Definition at line 203 of file ili9325.c.
References DriverCodeRead, and ILI9325_read().
{
    return ILI9325_read(DriverCodeRead);
}
const u8 ILI9325_getFontHeight ()
Definition at line 789 of file ili9325.c.
Referenced by ILI9325_init(), and ILI9325_setPortrait().
{
    return Display_getFontHeight();
}
const u8 ILI9325_getFontWidth ()
Print functions
Definition at line 784 of file ili9325.c.
Referenced by ILI9325_init(), and ILI9325_setPortrait().
{
    return Display_getFontWidth();
}
u8 ILI9325_getOrientation ()
Definition at line 735 of file ili9325.c.
References ILI9325, and lcd_t::orientation.
{
    return ILI9325.orientation;
}
u16 ILI9325_getScreenHeight ()
Definition at line 748 of file ili9325.c.
References rect_t::height, ILI9325, lcd_t::orientation, PORTRAIT, lcd_t::screen, and rect_t::width.
{
    if (ILI9325.orientation == PORTRAIT)
        return ILI9325.screen.height;
    else // if (ILI9325.orientation == LANDSCAPE)
        return ILI9325.screen.width;
}
u16 ILI9325_getScreenWidth ()
Definition at line 740 of file ili9325.c.
References rect_t::height, ILI9325, lcd_t::orientation, PORTRAIT, lcd_t::screen, and rect_t::width.
{
    if (ILI9325.orientation == PORTRAIT)
        return ILI9325.screen.width;
    else // if (ILI9325.orientation == LANDSCAPE)
        return ILI9325.screen.height;
}
void ILI9325_init ()
---------- Default Screen Values
---------- IO's Output by default
---------- Clear Command lines
---------- Idle
---------- Reset LCD Driver
---------- Start Initial Sequence
---------- Power On sequence
---------- Adjust the Gamma Curve
---------- Set GRAM area
---------- Partial Display Control
---------- Panel Control
---------- Default settings
Definition at line 217 of file ili9325.c.
References BaseImageDisplayControl, Blue, lcd_t::cursor, Delayms(), DisplayControl1, DisplayControl2, DisplayControl3, DisplayControl4, DriverCodeRead, DriverOutputControl, DriverOutputControl2, rect_t::endx, rect_t::endy, EntryMode, lcd_t::font, FrameMarkerPosition, GammaControl1, GammaControl10, GammaControl2, GammaControl3, GammaControl4, GammaControl5, GammaControl6, GammaControl7, GammaControl8, GammaControl9, GRAMHorizontalAddressSet, GRAMVerticalAddressSet, font_t::height, rect_t::height, HorizontalRAMEndAddressPosition, HorizontalRAMStartAddressPosition, ILI9325, ILI9325_clearScreen(), ILI9325_getFontHeight(), ILI9325_getFontWidth(), ILI9325_setBackgroundColor(), ILI9325_setColor(), ILI9325_setPortrait(), ILI9325_write(), LCDDrivingWaveControl, lcd_t::orientation, OUTPUT, PanelInterfaceControl1, PartialImage1DisplayPosition, PartialImage1RAMEndAddress, PartialImage1RAMStartAddress, PartialImage2DisplayPosition, PartialImage2RAMEndAddress, PartialImage2RAMStartAddress, PORTRAIT, PowerControl1, PowerControl2, PowerControl3, PowerControl4, PowerControl7, ResizingControlRegister, RGBDisplayInterfaceControl1, RGBDisplayInterfaceControl2, lcd_t::screen, rect_t::startx, rect_t::starty, VerticalRAMEndAddressPosition, VerticalRAMStartAddressPosition, White, font_t::width, rect_t::width, coord_t::x, and coord_t::y.
{
    ILI9325.orientation = PORTRAIT;
    ILI9325.cursor.x = 0;
    ILI9325.cursor.y = 0;
    ILI9325.screen.startx = 0;
    ILI9325.screen.starty = 0;
    ILI9325.screen.endx = 239;
    ILI9325.screen.endy = 319;
    ILI9325.screen.width = 240;
    ILI9325.screen.height = 320;
    ILI9325.font.width = ILI9325_getFontWidth();
    ILI9325.font.height = ILI9325_getFontHeight();
    dDATA = OUTPUT;
    dCMD1 = OUTPUT;
    dCMD2 = OUTPUT;
    DATA = 0x00;
    HighCS;
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    HighRST;
    Delayms(5); // 1ms min.
    LowRST;
    Delayms(2); // no min.
    HighRST;
    Delayms(100); // 50ms min.
    LowCS; // Enable LCD -> not needed if CS is connected to GND
    //---------- Start internal oscillator
    ILI9325_write(DriverCodeRead, 0x0001);
    Delayms(50);
    // SS = 1 (shift dir. to the right)
    ILI9325_write(DriverOutputControl, 0x0100);
    // B/C = 1
    // EOR = 1
    ILI9325_write(LCDDrivingWaveControl, 0x0700); // set the line
       inversion
    // AM = 0
    // I/D = 11 (H and V increment)
    // BGR = 1 (Swap the RGB data to BGR in writing into GRAM)
    ILI9325_write(EntryMode, 0x1030); //set GRAM write direction and BGR=1
       PORTRAIT MODE
    ILI9325_write(ResizingControlRegister, 0x0000);
    ILI9325_write(DisplayControl2, 0x0202); // set the back and front porch to
       4 lines
    ILI9325_write(DisplayControl3, 0x0000); // set non-display area refresh
       cycle ISC[3:0]
    ILI9325_write(DisplayControl4, 0x0000); // FMARK function
    ILI9325_write(RGBDisplayInterfaceControl1, 0x0000); // RGB
       interface setting
    ILI9325_write(FrameMarkerPosition, 0x0000); // Frame marker Position
    ILI9325_write(RGBDisplayInterfaceControl2, 0x0000); // RGB
       interface polarity
    ILI9325_write(PowerControl1, 0x0000); // SAP, BT[3:0], AP, DSTB, SLP, STB
    ILI9325_write(PowerControl2, 0x0007); // DC1[2:0], DC0[2:0], VC[2:0]
    ILI9325_write(PowerControl3, 0x0000); // VREG1OUT voltage
    ILI9325_write(PowerControl4, 0x0000); // VDV[4:0] for VCOM amplitude
    //ILI9325_write(DisplayControl1, 0x0001);
    Delayms(200); // Discharge capacitor power voltage
    ILI9325_write(PowerControl1, 0x14B0); // SAP=1, BT[3:0]=110, APE=1, AP=001,
       DSTB=0, SLP=0, STB=0
    ILI9325_write(PowerControl2, 0x0007); // DC1[2:0]=010, DC0[2:0]=010,
       VC[2:0]=000
    Delayms(50);
    ILI9325_write(PowerControl3, 0x008E); // External reference voltage= Vci;
    Delayms(50);
    ILI9325_write(PowerControl4, 0x0C00); // R13=1200 when R12=009D;VDV[4:0] for
       VCOM amplitude
    ILI9325_write(PowerControl7, 0x0015); // R29=000C when R12=009D;VCM[5:0] for
       VCOMH
    //ILI9325_write(FrameRateandColorControl, 0x000D); // Set Frame Rate
    Delayms(50);
    ILI9325_write(GammaControl1, 0x0000);
    ILI9325_write(GammaControl2, 0x0502);
    ILI9325_write(GammaControl3, 0x0307);
    ILI9325_write(GammaControl4, 0x0305);
    ILI9325_write(GammaControl5, 0x0004);
    ILI9325_write(GammaControl6, 0x0402);
    ILI9325_write(GammaControl7, 0x0707);
    ILI9325_write(GammaControl8, 0x0503);
    ILI9325_write(GammaControl9, 0x1505);
    ILI9325_write(GammaControl10, 0x1505);
    ILI9325_write(GRAMHorizontalAddressSet, 0x0000); // GRAM
       horizontal Address
    ILI9325_write(GRAMVerticalAddressSet, 0x0000); // GRAM
       Vertical Address
    ILI9325_write(HorizontalRAMStartAddressPosition, 0); //
       Horizontal GRAM Start Address
    ILI9325_write(HorizontalRAMEndAddressPosition, 239); //
       Horizontal GRAM End Address
    ILI9325_write(VerticalRAMStartAddressPosition, 0); //
       Vertical GRAM Start Address
    ILI9325_write(VerticalRAMEndAddressPosition, 319); //
       Vertical GRAM Start Address
    ILI9325_write(DriverOutputControl2, 0xA700); // Gate Scan Line
    ILI9325_write(BaseImageDisplayControl, 0x0003);//b111); // NDL,
       VLE, REV
    //ILI9325_write(VerticalScrollControl, 0x0000);
    
    ILI9325_write(PartialImage1DisplayPosition, 0x0000);
    ILI9325_write(PartialImage1RAMStartAddress, 0x0000);
    ILI9325_write(PartialImage1RAMEndAddress, 0x0000);
    ILI9325_write(PartialImage2DisplayPosition, 0x0000);
    ILI9325_write(PartialImage2RAMStartAddress, 0x0000);
    ILI9325_write(PartialImage2RAMEndAddress, 0x0000);
    ILI9325_write(PanelInterfaceControl1, 0x0010); // sync with fosc/1 -
       16 clocks/line
    //ILI9325_write(PanelInterfaceControl2, 0x0600); // 0 clock overlap period
// ILI9325_write(PanelInterfaceControl3, 0x0001);
// ILI9325_write(PanelInterfaceControl4, 0x0110); // 16 clocks/line - min. div. ratio
// ILI9325_write(PanelInterfaceControl5, 0x0000);
// ILI9325_write(PanelInterfaceControl6, 0x0000);
// Delayms(50);
    //---------- Display ON
    // D[1:0] = 11, display ON (00 = display OFF)
    // CL = 0, 262K color
    // GON & DET = 11, normal display
    // BASEE = 1, the base image is displayed
    // PTDE[1:0] = 00, only base image is displayed
    ILI9325_write(DisplayControl1, 0x0133);
    //Delayms(50);
    //I9325_writeRegister(WriteDatatoGRAM); // write GRAM
    //HighCS; // Disable LCD
    ILI9325_setColor(White);
    ILI9325_setBackgroundColor(Blue);
    ILI9325_setPortrait();
    ILI9325_clearScreen();
}
void ILI9325_printChar (u8 c, u16 x, u16 y)
Definition at line 804 of file ili9325.c.
References lcd_t::bcolor, color_t::c, lcd_t::color, font, lcd_t::font, GRAMHorizontalAddressSet, GRAMVerticalAddressSet, font_t::height, ILI9325, ILI9325_write(), and WriteDatatoGRAM.
Referenced by ILI9325_printString().
{
    u8 i, j, by;
    u16 offset;
    //LowCS; // Enable LCD
    offset = ((c-32) * ILI9325.font.height); // 32 first characters are not included
       in the font
    ILI9325_write(GRAMHorizontalAddressSet,
      x); // setCursor
    for (j = 0; j < ILI9325.font.height; j++)
    {
        ILI9325_write(GRAMVerticalAddressSet,
      y + j);
        by = font[offset++];
        for (i = 0; i < ILI9325.font.height; i++)
        {
            // Test if foreground color is set
            //if BitTest(by, ILI9325.font.height - 1)
            if (by&0x80)
                ILI9325_write(WriteDatatoGRAM,
      ILI9325.color.c);
            else
                ILI9325_write(WriteDatatoGRAM,
      ILI9325.bcolor.c);
            by <<= 1; // Shift out bits right
        }
    }
    //HighCS; // Disable LCD
}
void ILI9325_printf (const u8 * fmt, ...)
Definition at line 886 of file ili9325.c.
References ILI9325_printString(), and psprintf2().
{
    u8 buffer[80];
    //char *buffer;
    u8 length;
    va_list args;
    va_start(args, fmt);
    //length = strlen(fmt);
    //buffer = (char *) malloc(1 + length * sizeof(char));
    length = psprintf2(buffer, fmt, args);
    ILI9325_printString(buffer);
    va_end(args);
}
void ILI9325_printString (u8 * s)
Definition at line 839 of file ili9325.c.
References c, lcd_t::cursor, rect_t::endx, rect_t::endy, lcd_t::font, font_t::height, ILI9325, ILI9325_printChar(), ILI9325_write(), lcd_t::screen, VerticalScrollControl, font_t::width, coord_t::x, and coord_t::y.
Referenced by ILI9325_printf().
{
    u8 c;
    
    while (c = *s++)
    {
        switch (c)
        {
            case '\r':
                if (ILI9325.cursor.y > (ILI9325.screen.
      endy - ILI9325.font.height))
                {
                    //ILI9325.cursor.y = 0;
                    //ILI9325_scroll(ILI9325.screen.endy - ILI9325.font.height);
                    //ILI9325_scroll(ILI9325.font.height);
                    //LowCS; // Enable LCD
                    ILI9325_write(VerticalScrollControl,
      ILI9325.font.height);
                    //HighCS; // Disable LCD
                }
                else
                {
                    ILI9325.cursor.y += ILI9325.font.
      height;
                }
                break;
            case '\n':
                ILI9325.cursor.x = 0;
                break;
            default:
                ILI9325_printChar(c, ILI9325.cursor.
      x, ILI9325.cursor.y);
                ILI9325.cursor.x += ILI9325.font.width;
                if (ILI9325.cursor.x > ILI9325.screen.
      endx)
                {
                    ILI9325.cursor.x = 0;
                    ILI9325.cursor.y += ILI9325.font.
      height;
                }
        }
    }
}
u16 ILI9325_read (u8 index)
Definition at line 187 of file ili9325.c.
References ILI9325_readData(), and ILI9325_writeRegister().
Referenced by ILI9325_getDeviceID(), and ILI9325_readPixel().
{
    ILI9325_writeRegister(index);
    return ILI9325_readData();
}
u16 ILI9325_readData ()
Read functions
Definition at line 147 of file ili9325.c.
References word_t::h8, word_t::l8, and word_t::w.
Referenced by ILI9325_read().
{
    word_t d;
    
    //LowCS; // Select LCD
    HighRS; // Disable Register Selection Signal
    HighWR; // Disable Write Mode
    HighRD; // Disable Read (Write Mode)
    // Data line as input
    dDATA = 0xFF;
    LowRD; // Enable Read Mode
    HighRD; // Disable Read Mode
    
    d.h8 = DATA; // Read High Byte Data
    LowRD; // Enable Read Mode
    HighRD; // Disable Read Mode
    d.l8 = DATA; // Read Low Byte Data
    // Data line as output
    dDATA = 0x00;
    //HighCS; // Release LCD
    return d.w;
}
u16 ILI9325_readPixel (u16 x, u16 y)
Definition at line 547 of file ili9325.c.
References c, rect_t::endx, rect_t::endy, ILI9325, ILI9325_read(), ILI9325_setCursor(), ReadDatatoGRAM, and lcd_t::screen.
{
    u16 c;
    
    if ((x > ILI9325.screen.endx) || (y > ILI9325.
      screen.endy)) return 0;
    ILI9325_setCursor(x, y);
    //LowCS;
    c = ILI9325_read(ReadDatatoGRAM);
    //HighCS;
    
    return c;
}
void ILI9325_scroll (u16 pixels)
Definition at line 765 of file ili9325.c.
References ILI9325_write(), VerticalScrollControl, and y.
{
    u16 y = pixels;
    while (y < 0)
        y += 320;
    while (y >= 320)
        y -= 320;
    //LowCS; // Enable LCD
    ILI9325_write(VerticalScrollControl, y);
    //HighCS; // Disable LCD
}
void ILI9325_setBackgroundColor (u16 color)
Definition at line 428 of file ili9325.c.
References color_t::b, lcd_t::bcolor, color_t::c, color_t::g, ILI9325, and color_t::r.
Referenced by ILI9325_init().
{
    ILI9325.bcolor.r = (color >> 11) & 0x1f;
    ILI9325.bcolor.g = (color >> 5) & 0x3f;
    ILI9325.bcolor.b = (color >> 0) & 0x1f;
    ILI9325.bcolor.c = color; // ILI9325_color565(r,g,b);
}
void ILI9325_setColor (u16 color)
Definition at line 411 of file ili9325.c.
References color_t::b, color_t::c, lcd_t::color, color_t::g, ILI9325, and color_t::r.
Referenced by ILI9325_init().
{
    ILI9325.color.r = (color >> 11) & 0x1f;
    ILI9325.color.g = (color >> 5) & 0x3f;
    ILI9325.color.b = (color >> 0) & 0x1f;
    ILI9325.color.c = color; // ILI9325_color565(r,g,b);
}
void ILI9325_setCursor (u16 x, u16 y)
Graphic functions
Definition at line 482 of file ili9325.c.
References lcd_t::cursor, GRAMHorizontalAddressSet, GRAMVerticalAddressSet, ILI9325, ILI9325_write(), LANDSCAPE, lcd_t::orientation, coord_t::x, x, coord_t::y, and y.
Referenced by ILI9325_clearScreen(), ILI9325_clearWindow(), ILI9325_delPixel(), ILI9325_drawPixel(), ILI9325_readPixel(), ILI9325_setWindow(), and ILI9325_test().
{
    if (ILI9325.orientation == LANDSCAPE)
    {
        ILI9325.cursor.x = y; // save current position
        ILI9325.cursor.y = x;
    }
    else
    {
        ILI9325.cursor.x = x; // save current position
        ILI9325.cursor.y = y;
    }
    
    //LowCS; // Enable LCD
    ILI9325_write(GRAMHorizontalAddressSet,
      ILI9325.cursor.x);
    ILI9325_write(GRAMVerticalAddressSet,
      ILI9325.cursor.y);
    //HighCS; // Disable LCD
}
void ILI9325_setLandscape ()
Definition at line 718 of file ili9325.c.
References DriverOutputControl, EntryMode, ILI9325, ILI9325_clearScreen(), ILI9325_setWindow(), ILI9325_write(), LANDSCAPE, and lcd_t::orientation.
{
    ILI9325.orientation = LANDSCAPE;
    //ILI9325.font.width = ILI9325_getFontHeight();
    //ILI9325.font.height= ILI9325_getFontWidth();
    //LowCS;
    ILI9325_write(EntryMode, 0x1028); // 0x28 = 0b00101000;
    // shift dir. to the right (SM=0, SS=0)
    ILI9325_write(DriverOutputControl, 0x0000);
    //HighCS;
    
    //ILI9325_setCursor(0, 0);
    ILI9325_setWindow(0, 0, 319, 239);
    ILI9325_clearScreen();
}
void ILI9325_setPortrait ()
Definition at line 700 of file ili9325.c.
References DriverOutputControl, EntryMode, lcd_t::font, font_t::height, ILI9325, ILI9325_clearScreen(), ILI9325_getFontHeight(), ILI9325_getFontWidth(), ILI9325_setWindow(), ILI9325_write(), lcd_t::orientation, PORTRAIT, and font_t::width.
Referenced by ILI9325_init().
{
    ILI9325.orientation = PORTRAIT;
    ILI9325.font.width = ILI9325_getFontWidth();
    ILI9325.font.height= ILI9325_getFontHeight();
    //LowCS;
    // set GRAM write direction to PORTRAIT MODE
    ILI9325_write(EntryMode, 0x1030); // 0x30 = 0b00110000;
    // shift dir. to the right (SM=0, SS=1)
    ILI9325_write(DriverOutputControl, 0x0100);
    //HighCS;
    
    //ILI9325_setCursor(0, 0);
    ILI9325_setWindow(0, 0, 239, 319);
    ILI9325_clearScreen();
}
void ILI9325_setWindow (u16 x1, u16 y1, u16 x2, u16 y2)
Definition at line 572 of file ili9325.c.
References rect_t::endx, rect_t::endy, rect_t::height, HorizontalRAMEndAddressPosition, HorizontalRAMStartAddressPosition, ILI9325, ILI9325_setCursor(), ILI9325_write(), lcd_t::screen, rect_t::startx, rect_t::starty, VerticalRAMEndAddressPosition, VerticalRAMStartAddressPosition, and rect_t::width.
Referenced by ILI9325_setLandscape(), and ILI9325_setPortrait().
{
    ILI9325.screen.startx = x1;
    ILI9325.screen.starty = y1;
    ILI9325.screen.endx = x2;
    ILI9325.screen.endy = y2;
    ILI9325.screen.width = x2 - x1;
    ILI9325.screen.height = y2 - y1;
    
    //LowCS; // Enable LCD
    ILI9325_write(HorizontalRAMStartAddressPosition, x1);
    ILI9325_write(HorizontalRAMEndAddressPosition, x2);
    ILI9325_write(VerticalRAMStartAddressPosition, y1);
    ILI9325_write(VerticalRAMEndAddressPosition, y2);
    //HighCS; // Disable LCD
    ILI9325_setCursor(x1, y1);
}
void ILI9325_test (void)
Definition at line 444 of file ili9325.c.
References Blue, rect_t::endx, rect_t::endy, ILI9325, ILI9325_setCursor(), ILI9325_writeData(), ILI9325_writeRegister(), Red, lcd_t::screen, rect_t::startx, rect_t::starty, White, WriteDatatoGRAM, x, and y.
{
    u16 x,y;
    ILI9325_setCursor(0,0); // set cursor home
    //LowCS; // Enable LCD
    ILI9325_writeRegister(WriteDatatoGRAM); // write GRAM
    for (y=ILI9325.screen.starty; y<ILI9325.screen.
      endy; y++)
    {
        for (x=ILI9325.screen.startx; x<ILI9325.screen.
      endx; x++)
        {
            if (y>213) ILI9325_writeData(Red);
            else if (y>106) ILI9325_writeData(White);
            else ILI9325_writeData(Blue);
        }
    }
    //HighCS; // Disable LCD
}
void ILI9325_write (u8 index, u16 data15)
Definition at line 126 of file ili9325.c.
References ILI9325_writeData(), and ILI9325_writeRegister().
Referenced by ILI9325_delPixel(), ILI9325_drawPixel(), ILI9325_enterSleep(), ILI9325_exitSleep(), ILI9325_init(), ILI9325_printChar(), ILI9325_printString(), ILI9325_scroll(), ILI9325_setCursor(), ILI9325_setLandscape(), ILI9325_setPortrait(), and ILI9325_setWindow().
{
    ILI9325_writeRegister(index);
    ILI9325_writeData(data15);
}
void ILI9325_writeData (u16 data15)
Definition at line 92 of file ili9325.c.
References word_t::h8, word_t::l8, and word_t::w.
Referenced by ILI9325_test(), and ILI9325_write().
{
    word_t d;
    d.w = data15;
    //LowCS;
    HighRS; // Disable Register Selection Signal
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    DATA = d.h8;
    LowWR; // Enable Write
    HighWR; // Disable Write
    DATA = d.l8;
    LowWR; // Enable Write
    HighWR; // Disable Write
    //HighCS;
}
void ILI9325_writeRegister (u8 index)
Write functions
Definition at line 59 of file ili9325.c.
Referenced by ILI9325_clearScreen(), ILI9325_clearWindow(), ILI9325_read(), ILI9325_test(), and ILI9325_write().
{
    //LowCS;
    LowRS; // Enable Register Selection Signal
    HighRD; // Disable Read Mode
    HighWR; // Disable Write Mode
    DATA = 0;
    
    LowWR; // Enable Write
    HighWR; // Disable Write
    DATA = index;
    LowWR; // Enable Write
    HighWR; // Disable Write
    //HighCS;
}