/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/integer_math.h File Reference
Typedefs
typedef float returntype
Functions
returntype sini (unsigned int x)
returntype cosi (unsigned int x)
returntype tani (unsigned int x)
returntype powi (int base, int num)
Variables
const float sins []
Typedef Documentation
typedef float returntype
Definition at line 14 of file integer_math.h.
Function Documentation
returntype cosi (unsigned int x)
Definition at line 34 of file integer_math.c.
References sins.
Referenced by drawBitmapR(), rotateChar(), and tani().
                               {
    x = x - 360*((int)(x/360));
    
    if(x<=90){
        return(sins[90-x]);
    }
    if(x<180){
        return(-sins[x-90]);
    }
    if(x<=270){
        return(-sins[270-x]);
    }
    //x<60
    return(sins[x-270]);
}
returntype powi (int base, int num)
Definition at line 54 of file integer_math.c.
References res.
Referenced by printNumF().
                                  {
    int i, to;
    float res = 1;
    
    to = num > 0? num: num * (-1);
    for(i = 0; i<to; i++){
        res *= base;
    }
    
    return (num>0?res:(1/res));
    
}
returntype sini (unsigned int x)
Definition at line 17 of file integer_math.c.
References sins.
Referenced by drawBitmapR(), rotateChar(), and tani().
                               {
    x = x - 360*((int)(x/360));
    
    if(x<=90){
        return(sins[x]);
    }
    if(x<180){
        return(sins[180-x]);
    }
    if(x<270){
        return(-sins[x-180]);
    }
    //x<360
    return(-sins[360-x]);
}
returntype tani (unsigned int x)
Definition at line 50 of file integer_math.c.
References cosi(), and sini().
                               {
    return (sini(x)/cosi(x));
}
Variable Documentation
const float sins[]
Initial value:
= { 0,0.0174524064,0.0348994967,0.0523359562,0.0697564737,
.0871557427,0.1045284633,0.1218693434,0.139173101,0.156434465,0.1736481777,
.1908089954,0.2079116908,0.2249510543,0.2419218956,0.2588190451,0.2756373558,
.2923717047,0.3090169944,0.3255681545,0.3420201433,0.3583679495,0.3746065934,
.3907311285,0.4067366431,0.4226182617,0.4383711468,0.4539904997,0.4694715628,
.4848096202,0.5,0.5150380749,0.5299192642,0.544639035,0.5591929035,0.5735764364,
.5877852523,0.6018150232,0.6156614753,0.629320391,0.6427876097,0.656059029,
.6691306064,0.6819983601,0.6946583705,0.7071067812,0.7193398003,0.7313537016,
.7431448255,0.7547095802,0.7660444431,0.7771459615,0.7880107536,0.79863551,
.8090169944,0.8191520443,0.8290375726,0.8386705679,0.8480480962,0.8571673007,
.8660254038,0.8746197071,0.8829475929,0.8910065242,0.8987940463,0.906307787,
.9135454576,0.9205048535,0.9271838546,0.9335804265,0.9396926208,0.9455185756,
.9510565163,0.956304756,0.9612616959,0.9659258263,0.9702957263,0.9743700648,
.9781476007,0.9816271834,0.984807753,0.9876883406,0.9902680687,0.9925461516,
.9945218954,0.9961946981,0.9975640503,0.9986295348,0.999390827,0.9998476952,
}
Definition at line 16 of file integer_math.h.
Referenced by cosi(), and sini().