/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/integer_math.c File Reference
#include `integer_math.h`
*
Macros
#define INTEGER_MATH_c
Functions
returntype sini (unsigned int x)
returntype cosi (unsigned int x)
returntype tani (unsigned int x)
returntype powi (int base, int num)
Macro Definition Documentation
#define INTEGER_MATH_c
Definition at line 12 of file integer_math.c.
Function Documentation
returntype cosi (unsigned int x)
Definition at line 34 of file integer_math.c.
References sins.
Referenced by drawBitmapR(), rotateChar(), and tani().
                               {
    x = x - 360*((int)(x/360));
    
    if(x<=90){
        return(sins[90-x]);
    }
    if(x<180){
        return(-sins[x-90]);
    }
    if(x<=270){
        return(-sins[270-x]);
    }
    //x<60
    return(sins[x-270]);
}
returntype powi (int base, int num)
Definition at line 54 of file integer_math.c.
References res.
Referenced by printNumF().
                                  {
    int i, to;
    float res = 1;
    
    to = num > 0? num: num * (-1);
    for(i = 0; i<to; i++){
        res *= base;
    }
    
    return (num>0?res:(1/res));
    
}
returntype sini (unsigned int x)
Definition at line 17 of file integer_math.c.
References sins.
Referenced by drawBitmapR(), rotateChar(), and tani().
                               {
    x = x - 360*((int)(x/360));
    
    if(x<=90){
        return(sins[x]);
    }
    if(x<180){
        return(sins[180-x]);
    }
    if(x<270){
        return(-sins[x-180]);
    }
    //x<360
    return(-sins[360-x]);
}
returntype tani (unsigned int x)
Definition at line 50 of file integer_math.c.
References cosi(), and sini().
                               {
    return (sini(x)/cosi(x));
}