/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/ethernet/ip_arp_udp.h File Reference
Functions
void init_ip_arp_udp (uint8_t *mymac, uint8_t *myip)
uint8_t eth_type_is_arp_and_my_ip (uint8_t *buf, uint8_t len)
uint8_t eth_type_is_ip_and_my_ip (uint8_t *buf, uint8_t len)
void make_arp_answer_from_request (uint8_t *buf, uint8_t len)
void make_echo_reply_from_request (uint8_t *buf, uint8_t len)
void make_udp_reply_from_request (uint8_t *buf, char *data, uint8_t datalen, uint16_t port)
Function Documentation
uint8_t eth_type_is_arp_and_my_ip (uint8_t * buf, uint8_t len)
Definition at line 89 of file ip_arp_udp.c.
References ETH_ARP_DST_IP_P, ETH_TYPE_H_P, ETH_TYPE_L_P, ETHTYPE_ARP_H_V, and ETHTYPE_ARP_L_V.
                                                           {
        uint8_t i=0;
        //
        if (len<41){
                return(0);
        }
        if(buf[ETH_TYPE_H_P] != ETHTYPE_ARP_H_V ||
           buf[ETH_TYPE_L_P] != ETHTYPE_ARP_L_V){
                return(0);
        }
        while(i<4){
                if(buf[ETH_ARP_DST_IP_P+i] != ipaddr[i]){
                        return(0);
                }
                i++;
        }
        return(1);
}
uint8_t eth_type_is_ip_and_my_ip (uint8_t * buf, uint8_t len)
Definition at line 108 of file ip_arp_udp.c.
References ETH_TYPE_H_P, ETH_TYPE_L_P, ETHTYPE_IP_H_V, ETHTYPE_IP_L_V, and IP_DST_P.
                                                          {
        uint8_t i=0;
        //eth+ip+udp header is 42
        if (len<42){
                return(0);
        }
        if(buf[ETH_TYPE_H_P]!=ETHTYPE_IP_H_V ||
           buf[ETH_TYPE_L_P]!=ETHTYPE_IP_L_V){
                return(0);
        }
        while(i<4){
                if(buf[IP_DST_P+i]!=ipaddr[i]){
                        return(0);
                }
                i++;
        }
        return(1);
}
void init_ip_arp_udp (uint8_t * mymac, uint8_t * myip)
Definition at line 76 of file ip_arp_udp.c.
                                                  {
        uint8_t i=0;
        while(i<4){
                ipaddr[i]=myip[i];
                i++;
        }
        i=0;
        while(i<6){
                macaddr[i]=mymac[i];
                i++;
        }
}
void make_arp_answer_from_request (uint8_t * buf, uint8_t len)
Definition at line 161 of file ip_arp_udp.c.
References enc28j60PacketSend(), ETH_ARP_DST_IP_P, ETH_ARP_DST_MAC_P, ETH_ARP_OPCODE_H_P, ETH_ARP_OPCODE_L_P, ETH_ARP_OPCODE_REPLY_H_V, ETH_ARP_OPCODE_REPLY_L_V, ETH_ARP_SRC_IP_P, ETH_ARP_SRC_MAC_P, and make_eth().
{
        uint8_t i=0;
        //
        make_eth(buf);
        buf[ETH_ARP_OPCODE_H_P]=ETH_ARP_OPCODE_REPLY_H_V;
        buf[ETH_ARP_OPCODE_L_P]=ETH_ARP_OPCODE_REPLY_L_V;
        // fill the mac addresses:
        while(i<6){
                buf[ETH_ARP_DST_MAC_P+i]=buf[ETH_ARP_SRC_MAC_P+i];
                buf[ETH_ARP_SRC_MAC_P+i]=macaddr[i];
                i++;
        }
        i=0;
        while(i<4){
                buf[ETH_ARP_DST_IP_P+i]=buf[ETH_ARP_SRC_IP_P+i];
                buf[ETH_ARP_SRC_IP_P+i]=ipaddr[i];
                i++;
        }
        // eth+arp is 42 bytes:
        enc28j60PacketSend(42,buf);
}
void make_echo_reply_from_request (uint8_t * buf, uint8_t len)
Definition at line 184 of file ip_arp_udp.c.
References enc28j60PacketSend(), ICMP_CHECKSUM_P, ICMP_TYPE_ECHOREPLY_V, ICMP_TYPE_P, make_eth(), and make_ip().
{
        make_eth(buf);
        make_ip(buf);
        buf[ICMP_TYPE_P]=ICMP_TYPE_ECHOREPLY_V;
        // we changed only the icmp.type field from request(=8) to reply(=0).
        // we can therefore easily correct the checksum:
        if (buf[ICMP_CHECKSUM_P] > (0xff-0x08)){
                buf[ICMP_CHECKSUM_P+1]++;
        }
        buf[ICMP_CHECKSUM_P]+=0x08;
        //
        enc28j60PacketSend(len,buf);
}
void make_udp_reply_from_request (uint8_t * buf, char * data, uint8_t datalen, uint16_t port)
Definition at line 200 of file ip_arp_udp.c.
References checksum(), enc28j60PacketSend(), ETH_HEADER_LEN, IP_HEADER_LEN, IP_SRC_P, IP_TOTLEN_H_P, IP_TOTLEN_L_P, make_eth(), make_ip(), UDP_CHECKSUM_H_P, UDP_CHECKSUM_L_P, UDP_DATA_P, UDP_DST_PORT_H_P, UDP_DST_PORT_L_P, UDP_HEADER_LEN, UDP_LEN_H_P, UDP_LEN_L_P, UDP_SRC_PORT_H_P, and UDP_SRC_PORT_L_P.
{
        uint8_t i=0;
        uint16_t ck;
        make_eth(buf);
        if (datalen>220){
                datalen=220;
        }
        // total length field in the IP header must be set:
        buf[IP_TOTLEN_H_P]=0;
        buf[IP_TOTLEN_L_P]=IP_HEADER_LEN+
      UDP_HEADER_LEN+datalen;
        make_ip(buf);
        // send to port:
        //buf[UDP_DST_PORT_H_P]=port>>8;
        //buf[UDP_DST_PORT_L_P]=port & 0xff;
        // sent to port of sender and use "port" as own source:
        buf[UDP_DST_PORT_H_P]=buf[UDP_SRC_PORT_H_P];
        buf[UDP_DST_PORT_L_P]= buf[UDP_SRC_PORT_L_P];
        buf[UDP_SRC_PORT_H_P]=port>>8;
        buf[UDP_SRC_PORT_L_P]=port & 0xff;
        // source port does not matter and is what the sender used.
        // calculte the udp length:
        buf[UDP_LEN_H_P]=0;
        buf[UDP_LEN_L_P]=UDP_HEADER_LEN+datalen;
        // zero the checksum
        buf[UDP_CHECKSUM_H_P]=0;
        buf[UDP_CHECKSUM_L_P]=0;
        // copy the data:
        while(i<datalen){
                buf[UDP_DATA_P+i]=data[i];
                i++;
        }
        ck=checksum(&buf[IP_SRC_P], 16 + datalen,1);
        buf[UDP_CHECKSUM_H_P]=ck>>8;
        buf[UDP_CHECKSUM_L_P]=ck& 0xff;
        enc28j60PacketSend(UDP_HEADER_LEN+
      IP_HEADER_LEN+ETH_HEADER_LEN+datalen,buf);
}