/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/ethernet/ip_arp_udp.c File Reference
#include `net.h`
*
#include `enc28j60.h`
*
Functions
uint16_t checksum (uint8_t *buf, uint16_t len, uint8_t type)
void init_ip_arp_udp (uint8_t *mymac, uint8_t *myip)
uint8_t eth_type_is_arp_and_my_ip (uint8_t *buf, uint8_t len)
uint8_t eth_type_is_ip_and_my_ip (uint8_t *buf, uint8_t len)
void make_eth (uint8_t *buf)
void make_ip (uint8_t *buf)
void make_arp_answer_from_request (uint8_t *buf, uint8_t len)
void make_echo_reply_from_request (uint8_t *buf, uint8_t len)
void make_udp_reply_from_request (uint8_t *buf, char *data, uint8_t datalen, uint16_t port)
Function Documentation
uint16_t checksum (uint8_t * buf, uint16_t len, uint8_t type)
Definition at line 38 of file ip_arp_udp.c.
References IP_PROTO_TCP_V, and IP_PROTO_UDP_V.
Referenced by make_ip(), and make_udp_reply_from_request().
                                                          {
        // type 0=ip
        // 1=udp
        // 2=tcp
        uint32_t sum = 0;
        if(type==1){
                sum+=IP_PROTO_UDP_V; // protocol udp
                // the length here is the length of udp (data+header len)
                // =length - IP addr length
                sum+=len-8; // = real udp len
        }
        if(type==2){
                sum+=IP_PROTO_TCP_V;
                // the length here is the length of tcp (data+header len)
                // =length - IP addr length
                sum+=len-8; // = real tcp len
        }
        // build the sum of 16bit words
        while(len >1){
                sum += 0xFFFF & (*buf<<8|*(buf+1));
                buf+=2;
                len-=2;
        }
        // if there is a byte left then add it (padded with zero)
        if (len){
                sum += (0xFF & *buf)<<8;
        }
        // now calculate the sum over the bytes in the sum
        // until the result is only 16bit long
        while (sum>>16){
                sum = (sum & 0xFFFF)+(sum >> 16);
        }
        // build 1's complement:
        return((uint16_t) sum ^ 0xFFFF);
}
uint8_t eth_type_is_arp_and_my_ip (uint8_t * buf, uint8_t len)
Definition at line 89 of file ip_arp_udp.c.
References ETH_ARP_DST_IP_P, ETH_TYPE_H_P, ETH_TYPE_L_P, ETHTYPE_ARP_H_V, and ETHTYPE_ARP_L_V.
                                                           {
        uint8_t i=0;
        //
        if (len<41){
                return(0);
        }
        if(buf[ETH_TYPE_H_P] != ETHTYPE_ARP_H_V ||
           buf[ETH_TYPE_L_P] != ETHTYPE_ARP_L_V){
                return(0);
        }
        while(i<4){
                if(buf[ETH_ARP_DST_IP_P+i] != ipaddr[i]){
                        return(0);
                }
                i++;
        }
        return(1);
}
uint8_t eth_type_is_ip_and_my_ip (uint8_t * buf, uint8_t len)
Definition at line 108 of file ip_arp_udp.c.
References ETH_TYPE_H_P, ETH_TYPE_L_P, ETHTYPE_IP_H_V, ETHTYPE_IP_L_V, and IP_DST_P.
                                                          {
        uint8_t i=0;
        //eth+ip+udp header is 42
        if (len<42){
                return(0);
        }
        if(buf[ETH_TYPE_H_P]!=ETHTYPE_IP_H_V ||
           buf[ETH_TYPE_L_P]!=ETHTYPE_IP_L_V){
                return(0);
        }
        while(i<4){
                if(buf[IP_DST_P+i]!=ipaddr[i]){
                        return(0);
                }
                i++;
        }
        return(1);
}
void init_ip_arp_udp (uint8_t * mymac, uint8_t * myip)
Definition at line 76 of file ip_arp_udp.c.
                                                  {
        uint8_t i=0;
        while(i<4){
                ipaddr[i]=myip[i];
                i++;
        }
        i=0;
        while(i<6){
                macaddr[i]=mymac[i];
                i++;
        }
}
void make_arp_answer_from_request (uint8_t * buf, uint8_t len)
Definition at line 161 of file ip_arp_udp.c.
References enc28j60PacketSend(), ETH_ARP_DST_IP_P, ETH_ARP_DST_MAC_P, ETH_ARP_OPCODE_H_P, ETH_ARP_OPCODE_L_P, ETH_ARP_OPCODE_REPLY_H_V, ETH_ARP_OPCODE_REPLY_L_V, ETH_ARP_SRC_IP_P, ETH_ARP_SRC_MAC_P, and make_eth().
{
        uint8_t i=0;
        //
        make_eth(buf);
        buf[ETH_ARP_OPCODE_H_P]=ETH_ARP_OPCODE_REPLY_H_V;
        buf[ETH_ARP_OPCODE_L_P]=ETH_ARP_OPCODE_REPLY_L_V;
        // fill the mac addresses:
        while(i<6){
                buf[ETH_ARP_DST_MAC_P+i]=buf[ETH_ARP_SRC_MAC_P+i];
                buf[ETH_ARP_SRC_MAC_P+i]=macaddr[i];
                i++;
        }
        i=0;
        while(i<4){
                buf[ETH_ARP_DST_IP_P+i]=buf[ETH_ARP_SRC_IP_P+i];
                buf[ETH_ARP_SRC_IP_P+i]=ipaddr[i];
                i++;
        }
        // eth+arp is 42 bytes:
        enc28j60PacketSend(42,buf);
}
void make_echo_reply_from_request (uint8_t * buf, uint8_t len)
Definition at line 184 of file ip_arp_udp.c.
References enc28j60PacketSend(), ICMP_CHECKSUM_P, ICMP_TYPE_ECHOREPLY_V, ICMP_TYPE_P, make_eth(), and make_ip().
{
        make_eth(buf);
        make_ip(buf);
        buf[ICMP_TYPE_P]=ICMP_TYPE_ECHOREPLY_V;
        // we changed only the icmp.type field from request(=8) to reply(=0).
        // we can therefore easily correct the checksum:
        if (buf[ICMP_CHECKSUM_P] > (0xff-0x08)){
                buf[ICMP_CHECKSUM_P+1]++;
        }
        buf[ICMP_CHECKSUM_P]+=0x08;
        //
        enc28j60PacketSend(len,buf);
}
void make_eth (uint8_t * buf)
Definition at line 127 of file ip_arp_udp.c.
References ETH_DST_MAC, and ETH_SRC_MAC.
Referenced by make_arp_answer_from_request(), make_echo_reply_from_request(), and make_udp_reply_from_request().
{
        uint8_t i=0;
        //
        //copy the destination mac from the source and fill my mac into src
        while(i<6){
                buf[ETH_DST_MAC +i]=buf[ETH_SRC_MAC +i];
                buf[ETH_SRC_MAC +i]=macaddr[i];
                i++;
        }
}
void make_ip (uint8_t * buf)
Definition at line 140 of file ip_arp_udp.c.
References checksum(), IP_CHECKSUM_P, IP_DST_P, IP_FLAGS_P, IP_HEADER_LEN, IP_P, IP_SRC_P, and IP_TTL_P.
Referenced by make_echo_reply_from_request(), and make_udp_reply_from_request().
{
        uint8_t i=0;
        uint16_t ck;
        while(i<4){
                buf[IP_DST_P+i]=buf[IP_SRC_P+i];
                buf[IP_SRC_P+i]=ipaddr[i];
                i++;
        }
        // clear the 2 byte checksum
        buf[IP_CHECKSUM_P]=0;
        buf[IP_CHECKSUM_P+1]=0;
        buf[IP_FLAGS_P]=0x40; // don't fragment
        buf[IP_FLAGS_P+1]=0; // fragement offset
        buf[IP_TTL_P]=64; // ttl
        // calculate the checksum:
        ck=checksum(&buf[IP_P], IP_HEADER_LEN,0);
        buf[IP_CHECKSUM_P]=ck>>8;
        buf[IP_CHECKSUM_P+1]=ck& 0xff;
}
void make_udp_reply_from_request (uint8_t * buf, char * data, uint8_t datalen, uint16_t port)
Definition at line 200 of file ip_arp_udp.c.
References checksum(), enc28j60PacketSend(), ETH_HEADER_LEN, IP_HEADER_LEN, IP_SRC_P, IP_TOTLEN_H_P, IP_TOTLEN_L_P, make_eth(), make_ip(), UDP_CHECKSUM_H_P, UDP_CHECKSUM_L_P, UDP_DATA_P, UDP_DST_PORT_H_P, UDP_DST_PORT_L_P, UDP_HEADER_LEN, UDP_LEN_H_P, UDP_LEN_L_P, UDP_SRC_PORT_H_P, and UDP_SRC_PORT_L_P.
{
        uint8_t i=0;
        uint16_t ck;
        make_eth(buf);
        if (datalen>220){
                datalen=220;
        }
        // total length field in the IP header must be set:
        buf[IP_TOTLEN_H_P]=0;
        buf[IP_TOTLEN_L_P]=IP_HEADER_LEN+
      UDP_HEADER_LEN+datalen;
        make_ip(buf);
        // send to port:
        //buf[UDP_DST_PORT_H_P]=port>>8;
        //buf[UDP_DST_PORT_L_P]=port & 0xff;
        // sent to port of sender and use "port" as own source:
        buf[UDP_DST_PORT_H_P]=buf[UDP_SRC_PORT_H_P];
        buf[UDP_DST_PORT_L_P]= buf[UDP_SRC_PORT_L_P];
        buf[UDP_SRC_PORT_H_P]=port>>8;
        buf[UDP_SRC_PORT_L_P]=port & 0xff;
        // source port does not matter and is what the sender used.
        // calculte the udp length:
        buf[UDP_LEN_H_P]=0;
        buf[UDP_LEN_L_P]=UDP_HEADER_LEN+datalen;
        // zero the checksum
        buf[UDP_CHECKSUM_H_P]=0;
        buf[UDP_CHECKSUM_L_P]=0;
        // copy the data:
        while(i<datalen){
                buf[UDP_DATA_P+i]=data[i];
                i++;
        }
        ck=checksum(&buf[IP_SRC_P], 16 + datalen,1);
        buf[UDP_CHECKSUM_H_P]=ck>>8;
        buf[UDP_CHECKSUM_L_P]=ck& 0xff;
        enc28j60PacketSend(UDP_HEADER_LEN+
      IP_HEADER_LEN+ETH_HEADER_LEN+datalen,buf);
}