/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/itdb02/itdb02_graph16w.c File Reference
#include <itdb02/itdb02_graph16w.h>
*
#include <integer_math.c>
*
#include <string.h>
*
#include <delay.c>
*
#include <itdb02/SmallFont.c>
*
#include <itdb02/BigFont.c>
*
Macros
#define ITDB02_Graph16w_c
#define ITDB02_32w
Functions
void LCD_Writ_Bus (int data)
void LCD_Write_COM (int data)
void LCD_Write_DATA (int data)
void InitLCD (char orientation)
void setXY (int x1, int y1, int x2, int y2)
void drawRect (int x1, int y1, int x2, int y2)
void drawRoundRect (int x1, int y1, int x2, int y2)
void fillRect (int x1, int y1, int x2, int y2)
void fillRoundRect (int x1, int y1, int x2, int y2)
void drawCircle (int x, int y, int radius)
void fillCircle (int x, int y, int radius)
void clrScr ()
void fillScr (char r, char g, char b)
void setColor (unsigned char r, unsigned char g, unsigned char b)
void setBackColor (unsigned char r, unsigned char g, unsigned char b)
void setPixel (int r, int g, int b)
void drawPixel (int x, int y)
void drawLine (int x1, int y1, int x2, int y2)
void drawHLine (int x, int y, int l)
void drawVLine (int x, int y, int l)
void printChar (char c, int x, int y)
void rotateChar (char c, int x, int y, int pos, int deg)
void myGLCD16w_print (char *st, int x, int y, int deg)
void printNumI (long num, int x, int y)
void printNumF (double num, char dec, int x, int y)
void fontSize (char size)
void drawBitmap (int x, int y, int sx, int sy, unsigned int *data, int scale)
void drawBitmapR (int x, int y, int sx, int sy, unsigned int *data, int deg, int rox, int roy)
Macro Definition Documentation
#define ITDB02_32w
Definition at line 61 of file itdb02_graph16w.c.
#define ITDB02_Graph16w_c
Definition at line 58 of file itdb02_graph16w.c.
Function Documentation
void clrScr ()
Definition at line 457 of file itdb02_graph16w.c.
References fastWriteHigh, fastWriteLow, LCD_RS, LCD_Writ_Bus(), orient, PORTRAIT, setPixel(), and setXY().
             {
    unsigned long i;
    
    fastWriteLow(LCD_CS);
    if (orient==PORTRAIT)
        setXY(0,0,239,399);
    else
        setXY(0,0,399,239);
    
    fastWriteHigh(LCD_RS);
    for (i=0; i<96000; i++){
        LCD_Writ_Bus(0);
    }
    fastWriteHigh(LCD_CS);
}
void drawBitmap (int x, int y, int sx, int sy, unsigned int * data, int scale)
Definition at line 996 of file itdb02_graph16w.c.
References fastWriteHigh, fastWriteLow, LCD_Write_DATA(), orient, PORTRAIT, and setXY().
Referenced by drawBitmapR().
{
    unsigned int col;
    int tx, ty, tc, tsx, tsy;
    if (scale==1)
    {
        if (orient==PORTRAIT)
        {
            fastWriteLow(LCD_CS);
            setXY(x, y, x+sx-1, y+sy-1);
            for (tc=0; tc<(sx*sy); tc++)
            {
                col=(unsigned int)(data[tc]);
                LCD_Write_DATA(col);
            }
            fastWriteHigh(LCD_CS);
        }
        else
        {
            fastWriteLow(LCD_CS);
            for (ty=0; ty<sy; ty++)
            {
                setXY(x, y+ty, x+sx-1, y+ty);
                for (tx=sx; tx>=0; tx--)
                {
                    col=(unsigned int)(data[(ty*sx)+tx]);
                    LCD_Write_DATA(col);
                }
            }
            fastWriteHigh(LCD_CS);
        }
    }
    else
    {
        if (orient==PORTRAIT)
        {
            fastWriteLow(LCD_CS);
            for (ty=0; ty<sy; ty++)
            {
                setXY(x, y+(ty*scale), x+((sx*scale)-1), y+(ty*scale)+scale);
                for (tsy=0; tsy<scale; tsy++)
                    for (tx=0; tx<sx; tx++)
                    {
                        col=(unsigned int)(data[(ty*sx)+tx]);
                        for (tsx=0; tsx<scale; tsx++)
                            LCD_Write_DATA(col);
                    }
            }
            fastWriteHigh(LCD_CS);
        }
        else
        {
            fastWriteLow(LCD_CS);
            for (ty=0; ty<sy; ty++)
            {
                for (tsy=0; tsy<scale; tsy++)
                {
                    setXY(x, y+(ty*scale)+tsy, x+((sx*scale)-1), y+(ty*scale)+tsy);
                    for (tx=sx; tx>=0; tx--)
                    {
                        col=(unsigned int)(data[(ty*sx)+tx]);
                        for (tsx=0; tsx<scale; tsx++)
                            LCD_Write_DATA(col);
                    }
                }
            }
            fastWriteHigh(LCD_CS);
        }
    }
}
void drawBitmapR (int x, int y, int sx, int sy, unsigned int * data, int deg, int rox, int roy)
Definition at line 1068 of file itdb02_graph16w.c.
References cosi(), drawBitmap(), drawPixel(), fastWriteData, setColor(), setXY(), and sini().
                                                                                             {
    unsigned int col;
    int tx, ty, newx, newy;
    //char r, g, b;
    //float vrad = 0;
    //vrad=deg*0.0174533;
    
    //vals = (int)(100000*sini(deg));
    
    //SerialPrintf(COM, "x: sini(%d)= %d\r\n", deg, vals);
    
    if (deg==0)
        drawBitmap(x, y, sx, sy, data, 1);
    else {
    for (ty=0; ty<sy; ty++){
        for (tx=0; tx<sx; tx++){
        col=(unsigned int)(data[(ty*sx)+tx]);
        newx=x+rox+((tx-rox)*cosi(deg)-(ty-roy)*sini(deg));
        newy=y+roy+((ty-roy)*cosi(deg)+(tx-rox)*sini(deg));
        setXY(newx, newy, newx, newy);
        fastWriteData(col);
        }
    }
    }
}
void drawCircle (int x, int y, int radius)
Definition at line 415 of file itdb02_graph16w.c.
References drawPixel().
                                         {
  int f = 1 - radius;
  int ddF_x = 1;
  int ddF_y = -2 * radius;
  int x1 = 0;
  int y1 = radius;
 
  drawPixel(x, y + radius);
  drawPixel(x, y - radius);
  drawPixel(x + radius, y);
  drawPixel(x - radius, y);
 
  while(x1 < y1)
  {
    if(f >= 0)
    {
      y1--;
      ddF_y += 2;
      f += ddF_y;
    }
    x1++;
    ddF_x += 2;
    f += ddF_x;
    drawPixel(x + x1, y + y1);
    drawPixel(x - x1, y + y1);
    drawPixel(x + x1, y - y1);
    drawPixel(x - x1, y - y1);
    drawPixel(x + y1, y + x1);
    drawPixel(x - y1, y + x1);
    drawPixel(x + y1, y - x1);
    drawPixel(x - y1, y - x1);
  }
}
void drawHLine (int x, int y, int l)
Definition at line 609 of file itdb02_graph16w.c.
References fastSetPixel, fastWriteHigh, fastWriteLow, fcolorb, fcolorg, fcolorr, setPixel(), and setXY().
Referenced by drawLine(), drawRect(), drawRoundRect(), fillRect(), and fillRoundRect().
{
    int i;
    
    fastWriteLow(LCD_CS);
    setXY(x, y, x+l, y);
    for (i=0; i<l+1; i++){
        fastSetPixel(fcolorr, fcolorg, fcolorb);
    }
    fastWriteHigh(LCD_CS);
}
void drawLine (int x1, int y1, int x2, int y2)
Definition at line 519 of file itdb02_graph16w.c.
References abs(), drawHLine(), drawPixel(), drawVLine(), fastWriteHigh, fastWriteLow, fcolorb, fcolorg, fcolorr, LCD_Write_DATA(), orient, PORTRAIT, and setXY().
{
    int tmp, i;
    double delta, tx, ty;
    double m, b, dx, dy;
    if (((x2-x1)<0)){
        tmp=x1;
        x1=x2;
        x2=tmp;
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if (((y2-y1)<0)){
        tmp=x1;
        x1=x2;
        x2=tmp;
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if (y1==y2){
        if (x1>x2){
            tmp=x1;
            x1=x2;
            x2=tmp;
        }
        drawHLine(x1, y1, x2-x1);
    }
    else if (x1==x2){
        if (y1>y2){
            tmp=y1;
            y1=y2;
            y2=tmp;
        }
        drawVLine(x1, y1, y2-y1);
    }
    else if (abs(x2-x1)>abs(y2-y1)){
        
        fastWriteLow(LCD_CS);
        
        delta=(double)(y2-y1)/(double)(x2-x1);
        ty=(double)y1;
        
        if (x1>x2){
            for (i=x1; i>=x2; i--){
                setXY(i, (int)(ty+0.5), i, (int)(ty+0.5));
                LCD_Write_DATA(((fcolorr & 0xF8)<<8) + ((
      fcolorg & 0xFC)<<3) + ((fcolorb & 0xF8)>>3));
                ty=ty-delta;
            }
        }
        else{
            for (i=x1; i<=x2; i++){
                setXY(i, (int)(ty+0.5), i, (int)(ty+0.5));
                LCD_Write_DATA(((fcolorr & 0xF8)<<8) + ((
      fcolorg & 0xFC)<<3) + ((fcolorb & 0xF8)>>3));
                ty=ty+delta;
            }
        }
        fastWriteHigh(LCD_CS);
    }
    else{
        fastWriteLow(LCD_CS);
        
        delta=(double)(x2-x1)/(double)(y2-y1);
        tx=(double)x1;
        if (y1>y2) {
            for (i=y2+1; i>y1; i--){
                setXY((int)(tx+0.5), i, (int)(tx+0.5), i);
                LCD_Write_DATA(((fcolorr & 0xF8)<<8) + ((
      fcolorg & 0xFC)<<3) + ((fcolorb & 0xF8)>>3));
                tx=tx+delta;
            }
        }
        else{
            for (i=y1; i<y2+1; i++){
                setXY((int)(tx+0.5), i, (int)(tx+0.5), i);
                LCD_Write_DATA(((fcolorr & 0xF8)<<8) + ((
      fcolorg & 0xFC)<<3) + ((fcolorb & 0xF8)>>3));
                tx=tx+delta;
            }
        }
        fastWriteHigh(LCD_CS);
    }
    if (orient==PORTRAIT)
        setXY(0,0,239,399);
    else
        setXY(0,0,399,239);
}
void drawPixel (int x, int y)
Definition at line 506 of file itdb02_graph16w.c.
References fastWriteHigh, fastWriteLow, fcolorb, fcolorg, fcolorr, LCD_Write_DATA(), orient, PORTRAIT, setPixel(), and setXY().
Referenced by drawCircle(), drawRoundRect(), and fillCircle().
{
    fastWriteLow(LCD_CS);
    setXY(x, y, x, y);
    //setPixel(fcolorr, fcolorg, fcolorb);
    LCD_Write_DATA(((fcolorr & 0xF8)<<8) + ((fcolorg & 0xFC)<<3) + ((
      fcolorb & 0xF8)>>3));
    if (orient==PORTRAIT)
        setXY(0,0,239,399);
    else
        setXY(0,0,399,239);
    fastWriteHigh(LCD_CS);
}
void drawRect (int x1, int y1, int x2, int y2)
Definition at line 290 of file itdb02_graph16w.c.
References drawHLine(), and drawVLine().
{
    int tmp;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    drawHLine(x1, y1, x2-x1);
    drawHLine(x1, y2, x2-x1);
    drawVLine(x1, y1, y2-y1);
    drawVLine(x2, y1, y2-y1);
}
void drawRoundRect (int x1, int y1, int x2, int y2)
Definition at line 313 of file itdb02_graph16w.c.
References drawHLine(), drawPixel(), and drawVLine().
{
    int tmp;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if ((x2-x1)>4 && (y2-y1)>4)
    {
        drawPixel(x1+1,y1+1);
        drawPixel(x2-1,y1+1);
        drawPixel(x1+1,y2-1);
        drawPixel(x2-1,y2-1);
        drawHLine(x1+2, y1, x2-x1-4);
        drawHLine(x1+2, y2, x2-x1-4);
        drawVLine(x1, y1+2, y2-y1-4);
        drawVLine(x2, y1+2, y2-y1-4);
    }
}
void drawVLine (int x, int y, int l)
Definition at line 621 of file itdb02_graph16w.c.
References fastSetPixel, fastWriteHigh, fastWriteLow, fcolorb, fcolorg, fcolorr, setPixel(), and setXY().
Referenced by drawLine(), drawRect(), drawRoundRect(), and fillRect().
{
    int i;
    fastWriteLow(LCD_CS);
    setXY(x, y, x, y+l);
    for (i=0; i<l; i++) {
        fastSetPixel(fcolorr, fcolorg, fcolorb);
    }
    fastWriteHigh(LCD_CS);
}
void fillCircle (int x, int y, int radius)
Definition at line 449 of file itdb02_graph16w.c.
References drawPixel().
                                         {
    int x1, y1;
    for(y1=-radius; y1<=radius; y1++)
        for(x1=-radius; x1<=radius; x1++)
            if(x1*x1+y1*y1 <= radius*radius)
                drawPixel(x+x1, y+y1);
}
void fillRect (int x1, int y1, int x2, int y2)
Definition at line 342 of file itdb02_graph16w.c.
References drawHLine(), drawVLine(), orient, and PORTRAIT.
{
    int tmp, i;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if (orient==PORTRAIT)
    {
        for (i=0; i<((y2-y1)/2)+1; i++)
        {
            drawHLine(x1, y1+i, x2-x1);
            drawHLine(x1, y2-i, x2-x1);
        }
    }
    else
    {
        for (i=0; i<((x2-x1)/2)+1; i++)
        {
            drawVLine(x1+i, y1, y2-y1);
            drawVLine(x2-i, y1, y2-y1);
        }
    }
}
void fillRoundRect (int x1, int y1, int x2, int y2)
Definition at line 377 of file itdb02_graph16w.c.
References drawHLine().
                                                  {
    int tmp, i;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if ((x2-x1)>4 && (y2-y1)>4)
    {
        for (i=0; i<=((y2-y1)/2)+1; i++)
        {
            switch(i)
            {
            case 0:
                drawHLine(x1+2, y1+i, x2-x1-4);
                drawHLine(x1+2, y2-i, x2-x1-4);
                break;
            case 1:
                drawHLine(x1+1, y1+i, x2-x1-2);
                drawHLine(x1+1, y2-i, x2-x1-2);
                break;
            default:
                drawHLine(x1, y1+i, x2-x1);
                drawHLine(x1, y2-i, x2-x1);
            }
        }
    }
}
void fillScr (char r, char g, char b)
Definition at line 473 of file itdb02_graph16w.c.
References fastWriteHigh, fastWriteLow, LCD_RS, LCD_Writ_Bus(), orient, PORTRAIT, setPixel(), and setXY().
                                    {
    long i;
    
    fastWriteLow(LCD_CS);
    if (orient==PORTRAIT)
        setXY(0,0,239,399);
    else
        setXY(0,0,399,239);
        
    fastWriteHigh(LCD_RS);
    for (i=0; i<96000; i++) {
        //setPixel(r, g, b);
        LCD_Writ_Bus(((r & 0xF8)<<8) + ((g & 0xFC)<<3) + ((b & 0xF8)>>3));
    }
    fastWriteHigh(LCD_CS);
}
void fontSize (char size)
Definition at line 987 of file itdb02_graph16w.c.
References FONT_SMALL, and fsize.
{
#ifdef _NO_BIG_FONT_
    fsize = FONT_SMALL;
#else
    fsize = size;
#endif
}
void InitLCD (char orientation)
Definition at line 141 of file itdb02_graph16w.c.
References Delayms(), fastSetOutputMode, fastWriteHigh, fastWriteLow, FONT_SMALL, fsize, LCD_DATA_DIR, LCD_RS, LCD_Write_COM(), LCD_Write_DATA(), orient, orientation, setBackColor(), and setColor().
                              {
  orient=orientation;
  
//Pin Mode for Control Pins!
//OLIMEX BOARDS (Arduino Like Boards, using SHIELDs)
#if defined(PIC32_PINGUINO) || defined(PIC32_PINGUINO_OTG)
  LCD_DATA_DIR = 0x00; //Output for All pins on DATA BUS
  LCD_DATA_BUS = 0x00;
  //LCD DB0 to DB7
  //0x4000,0x8000,0x200,0x100,0x80,0x40,0x02,0x04 (pins 8 - 15)
  //1,1,6,6,6,6,1,1,
  TRISBbits.TRISB14 = 0;
  TRISBbits.TRISB15 = 0;
  TRISGbits.TRISG9 = 0;
  TRISGbits.TRISG8 = 0;
  TRISGbits.TRISG7 = 0;
  TRISGbits.TRISG6 = 0;
  TRISBbits.TRISB1 = 0;
  TRISBbits.TRISB2 = 0;
  fastSetOutputMode(dLCD_RS);
  fastSetOutputMode(dLCD_WR);
  fastSetOutputMode(dLCD_CS);
  fastSetOutputMode(dLCD_REST);
  
  TRISDbits.TRISD4 = 1; //RD4 is connected to D2, don't know why! :-P
  PORTDbits.RD4 = 0;
#else
  //TODO: Maybe it cause some wrong signal on SERIAL?
  LCD_DATA_DIR = 0x0000; //Output for All pins on DATA BUS
  LCD_DATA_BUS = 0x0000;
  //Pin Mode for Control Pins!
  fastSetOutputMode(LCD_RS);
  fastSetOutputMode(LCD_WR);
  fastSetOutputMode(LCD_CS);
  fastSetOutputMode(LCD_REST);
#endif
  fastWriteHigh(LCD_REST);
  Delayms(5);
  fastWriteLow(LCD_REST);
  Delayms(5);
  fastWriteHigh(LCD_REST);
  Delayms(5);
  fastWriteLow(LCD_CS);
  
  //************* Start Initial Sequence *********/
  //16x9 Aspect Display Size 399
  LCD_Write_COM(0x00E9);
  LCD_Write_DATA(0x0020);
  LCD_Write_COM(0x0011); //Exit Sleep
  Delayms(100);
  LCD_Write_COM(0x00D1); //VCOM Control
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0071);
  LCD_Write_DATA(0x0019);
  LCD_Write_COM(0x00D0); //Power_Setting
  LCD_Write_DATA(0x0007);
  LCD_Write_DATA(0x0001);
  LCD_Write_DATA(0x0008);
  LCD_Write_COM(0x0036); //Set_address_mode
  LCD_Write_DATA(0x0048);
  LCD_Write_COM(0x003A); //Set_pixel_format
  LCD_Write_DATA(0x0005);
  LCD_Write_COM(0x00C1); //Display_Timing_Setting for Normal/Partial Mode
  LCD_Write_DATA(0x0010);
  LCD_Write_DATA(0x0010);
  LCD_Write_DATA(0x0002);
  LCD_Write_DATA(0x0002);
  LCD_Write_COM(0x00C0); //Set Default Gamma
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0035);
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0001);
  LCD_Write_DATA(0x0002);
  LCD_Write_COM(0x00C5); //Set frame rate
  LCD_Write_DATA(0x0004);//4 => 72Hz (Default)
  LCD_Write_COM(0x00D2); //power setting
  LCD_Write_DATA(0x0001);
  LCD_Write_DATA(0x0044);
  LCD_Write_COM(0x00C8); //Set Gamma
  LCD_Write_DATA(0x0004);
  LCD_Write_DATA(0x0067);
  LCD_Write_DATA(0x0035);
  LCD_Write_DATA(0x0004);
  LCD_Write_DATA(0x0008);
  LCD_Write_DATA(0x0006);
  LCD_Write_DATA(0x0024);
  LCD_Write_DATA(0x0001);
  LCD_Write_DATA(0x0037);
  LCD_Write_DATA(0x0040);
  LCD_Write_DATA(0x0003);
  LCD_Write_DATA(0x0010);
  LCD_Write_DATA(0x0008);
  LCD_Write_DATA(0x0080);
  LCD_Write_DATA(0x0000);
  LCD_Write_COM(0x002A); //Set_column_address
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x00eF);
  LCD_Write_COM(0x002B); //Set_page_address
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0000);
  LCD_Write_DATA(0x0001);
  LCD_Write_DATA(0x008F);
  LCD_Write_COM(0x0029); //display on
  LCD_Write_COM(0x002C); //display on
  
  fastWriteHigh(LCD_CS);
  setColor(255, 255, 255);
  setBackColor(0, 0, 0);
  fsize = FONT_SMALL;
}
void LCD_Writ_Bus (int data)
Definition at line 111 of file itdb02_graph16w.c.
References fastDelay, fastWriteHigh, and fastWriteLow.
Referenced by clrScr(), fillScr(), LCD_Write_COM(), and LCD_Write_DATA().
                           {
  LCD_DATA_BUS = data;
  fastDelay();
  fastWriteLow(LCD_WR);
  fastDelay();
  fastWriteHigh(LCD_WR);
  fastDelay();
  fastDelay();
  /*LCD_DATA_BUS = VL;
  fastWriteLow(LCD_WR);
  fastWriteHigh(LCD_WR);*/
}
void LCD_Write_COM (int data)
Definition at line 125 of file itdb02_graph16w.c.
References fastDelay, fastWriteLow, LCD_RS, and LCD_Writ_Bus().
Referenced by InitLCD(), and setXY().
                            {
  fastWriteLow(LCD_RS);
  fastDelay();
  LCD_Writ_Bus(data);
  fastDelay();
  fastDelay();
}
void LCD_Write_DATA (int data)
Definition at line 133 of file itdb02_graph16w.c.
References fastDelay, fastWriteHigh, LCD_RS, and LCD_Writ_Bus().
Referenced by drawBitmap(), drawLine(), drawPixel(), InitLCD(), setPixel(), and setXY().
                             {
  fastWriteHigh(LCD_RS);
  fastDelay();
  LCD_Writ_Bus(data);
  fastDelay();
  fastDelay();
}
void myGLCD16w_print (char * st, int x, int y, int deg)
Definition at line 830 of file itdb02_graph16w.c.
References CENTER, FONT_SMALL, fsize, orient, PORTRAIT, printChar(), RIGHT, and rotateChar().
Referenced by printNumF(), and printNumI().
{
    int stl, i;
    stl = strlen(st);
    if (fsize==FONT_SMALL)
    {
        if (orient==PORTRAIT)
        {
        if (x==RIGHT)
            x=240-(stl*8);
        if (x==CENTER)
            x=(240-(stl*8))/2;
        }
        else
        {
        if (x==RIGHT)
            x=400-(stl*8);
        if (x==CENTER)
            x=(400-(stl*8))/2;
        }
    }
    else
    {
        if (orient==PORTRAIT)
        {
        if (x==RIGHT)
            x=240-(stl*16);
        if (x==CENTER)
            x=(240-(stl*16))/2;
        }
        else
        {
        if (x==RIGHT)
            x=400-(stl*16);
        if (x==CENTER)
            x=(400-(stl*16))/2;
        }
    }
    for (i=0; i<stl; i++)
        if (deg==0)
            printChar(*st++, x + (i*(fsize*8)), y);
        else
            rotateChar(*st++, x, y, i, deg);
}
void printChar (char c, int x, int y)
Definition at line 632 of file itdb02_graph16w.c.
References bcolorb, bcolorg, bcolorr, BigFont, fastSetPixel, fastWriteHigh, fastWriteLow, fcolorb, fcolorg, fcolorr, FONT_SMALL, fsize, orient, PORTRAIT, setPixel(), setXY(), and SmallFont.
Referenced by myGLCD16w_print().
                                    {
    unsigned char i,j,ch;
    unsigned int temp;
    fastWriteLow(LCD_CS);
  
    if (fsize==FONT_SMALL)
    {
        if (orient==PORTRAIT)
        {
            setXY(x,y,x+7,y+11);
          
            temp=((c-32)*12);
            for(j=0;j<12;j++)
            {
                ch=(SmallFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<(7-i)))!=0)
                    {
                        fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                    }
                    else
                    {
                        fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                    }
                }
                temp++;
            }
        }
        else
        {
          
            temp=((c-32)*12);
            for(j=0;j<12;j++)
            {
                setXY(x,y+j,x+7,y+j);
                ch=(SmallFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<i))!=0)
                    {
                        fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                    }
                    else
                    {
                        fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                    }
                }
                temp++;
            }
        }
    }
#ifndef _NO_BIG_FONT_
    else
    {
        if (orient==PORTRAIT)
        {
            setXY(x,y,x+15,y+15);
          
            temp=((c-32)*32);
            for(j=0;j<32;j++)
            {
                ch=(BigFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<(7-i)))!=0)
                    {
                        fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                    }
                    else
                    {
                        fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                    }
                }
                temp++;
            }
        }
        else
        {
            temp=((c-32)*32);
            for(j=0;j<32;j+=2)
            {
                setXY(x,y+(j/2),x+15,y+(j/2));
                ch=(BigFont[temp+1]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<i))!=0)
                    {
                        fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                    }
                    else
                    {
                        fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                    }
                }
                ch=(BigFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<i))!=0)
                    {
                        fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                    }
                    else
                    {
                        fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                    }
                }
                temp+=2;
            }
        }
    }
#endif
    fastWriteHigh(LCD_CS);
}
void printNumF (double num, char dec, int x, int y)
Definition at line 921 of file itdb02_graph16w.c.
References c, myGLCD16w_print(), myGLCD_print(), and powi().
{
  char buf[25];
  char st[27];
  unsigned char neg=0;
  int i,c=0;
  int c2;
  unsigned long inum;
  
  if (num==0)
  {
      st[0]=48;
      st[1]=46;
      for (i=0; i<dec; i++)
          st[2+i]=48;
      st[2+dec]=0;
  }
  else
  {
      if (num<0)
      {
        neg=1;
        num=-num;
      }
      
      if (dec<1)
        dec=1;
      if (dec>5)
        dec=5;
      
      inum=(long)(num*powi(10,dec));
      
      while (inum>0) {
        buf[c]=48+(inum % 10);
        c++;
        inum=(inum-(inum % 10))/10;
      }
      if ((num<1) && (num>0))
      {
          buf[c]=48;
          c++;
      }
      buf[c]=0;
      
      if (neg)
      {
        st[0]=45;
      }
      
      c2=neg;
      for (i=0; i<c; i++)
      {
        st[c2]=buf[c-i-1];
        c2++;
        if ((c-(c2-neg))==dec)
        {
          st[c2]=46;
          c2++;
        }
      }
      st[c2]=0;
  }
  myGLCD16w_print(st,x,y,0);
}
void printNumI (long num, int x, int y)
Definition at line 878 of file itdb02_graph16w.c.
References c, myGLCD16w_print(), and myGLCD_print().
{
  char buf[25];
  char st[27];
  unsigned char neg=0;
  int i,c=0;
  
  if (num==0)
  {
      st[0]=48;
      st[1]=0;
  }
  else
  {
      if (num<0)
      {
        neg=1;
        num=-num;
      }
      
      while (num>0)
      {
        buf[c]=48+(num % 10);
        c++;
        num=(num-(num % 10))/10;
      }
      buf[c]=0;
      
      if (neg)
      {
        st[0]=45;
      }
      
      for (i=0; i<c; i++)
      {
        st[i+neg]=buf[c-i-1];
      }
      st[c+neg]=0;
  }
  myGLCD16w_print(st,x,y,0);
}
void rotateChar (char c, int x, int y, int pos, int deg)
Definition at line 748 of file itdb02_graph16w.c.
References bcolorb, bcolorg, bcolorr, BigFont, cosi(), fastSetPixel, fastWriteHigh, fastWriteLow, fcolorb, fcolorg, fcolorr, FONT_SMALL, fsize, setPixel(), setXY(), sini(), and SmallFont.
Referenced by myGLCD16w_print().
{
    char i,j,ch;
    unsigned int temp;
    int newx,newy;
    //double radian;
    //radian=deg*0.0175;
    fastWriteLow(LCD_CS);
    if (fsize==FONT_SMALL)
    {
        temp=((c-32)*12);
        for(j=0;j<12;j++)
        {
            ch=(SmallFont[temp]);
            for(i=0;i<8;i++)
            {
                newx=x+(((i+(pos*8))*cosi(deg))-((j)*sini(deg)));
                newy=y+(((j)*cosi(deg))+((i+(pos*8))*sini(deg)));
                setXY(newx,newy,newx+1,newy+1);
                
                if((ch&(1<<(7-i)))!=0)
                {
                    fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                }
                else
                {
                    fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                }
            }
            temp++;
        }
    }
#ifndef _NO_BIG_FONT_
    else
    {
        temp=((c-32)*32);
        for(j=0;j<16;j++)
        {
            ch=(BigFont[temp]);
            for(i=0;i<8;i++)
            {
                newx=x+(((i+(pos*16))*cosi(deg))-((j)*sini(deg)));
                newy=y+(((j)*cosi(deg))+((i+(pos*16))*sini(deg)));
                setXY(newx,newy,newx+1,newy+1);
                
                if((ch&(1<<(7-i)))!=0)
                {
                    fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                }
                else
                {
                    fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                }
            }
            temp++;
            ch=(BigFont[temp]);
            for(i=8;i<16;i++)
            {
                newx=x+(((i+(pos*16))*cosi(deg))-((j)*sini(deg)));
                newy=y+(((j)*cosi(deg))+((i+(pos*16))*sini(deg)));
                setXY(newx,newy,newx+1,newy+1);
                
                if((ch&(1<<(15-i)))!=0)
                {
                    fastSetPixel(fcolorr, fcolorg,
      fcolorb);
                }
                else
                {
                    fastSetPixel(bcolorr, bcolorg,
      bcolorb);
                }
            }
            temp++;
        }
    }
#endif
    fastWriteHigh(LCD_CS);
}
void setBackColor (unsigned char r, unsigned char g, unsigned char b)
Definition at line 496 of file itdb02_graph16w.c.
References bcolorb, bcolorg, and bcolorr.
Referenced by InitLCD().
                                                                    {
    bcolorr=r;
    bcolorg=g;
    bcolorb=b;
}
void setColor (unsigned char r, unsigned char g, unsigned char b)
Definition at line 490 of file itdb02_graph16w.c.
References fcolorb, fcolorg, and fcolorr.
Referenced by InitLCD().
                                                                {
    fcolorr=r;
    fcolorg=g;
    fcolorb=b;
}
void setPixel (int r, int g, int b)
Definition at line 502 of file itdb02_graph16w.c.
References LCD_Write_DATA().
                                {
    LCD_Write_DATA(((r & 0xF8)<<8) + ((g & 0xFC)<<3) + ((b & 0xF8)>>3));
}
void setXY (int x1, int y1, int x2, int y2)
Definition at line 261 of file itdb02_graph16w.c.
References LANDSCAPE, LCD_Write_COM(), LCD_Write_DATA(), and orient.
Referenced by clrScr(), drawBitmap(), drawBitmapR(), drawHLine(), drawLine(), drawPixel(), drawVLine(), fillScr(), printChar(), and rotateChar().
                                          {
    int tmp;
    if (orient==LANDSCAPE) {
        tmp=x1;
        x1=y1;
        y1=399-tmp;
        tmp=x2;
        x2=y2;
        y2=399-tmp;
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
//TO-DO Parei aqui, falta ver no datasheet!
    LCD_Write_COM(0x002a); //Set_column_address
    LCD_Write_DATA(x1>>8);
    LCD_Write_DATA(x1);
    LCD_Write_DATA(x2>>8);
    LCD_Write_DATA(x2);
    LCD_Write_COM(0x002b); //Set_page_address
    LCD_Write_DATA(y1>>8);
    LCD_Write_DATA(y1);
    LCD_Write_DATA(y2>>8);
    LCD_Write_DATA(y2);
    LCD_Write_COM(0x002c); //Write_memory_start
}