/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/itdb02/itdb02_graph.c File Reference
#include <itdb02/itdb02_graph.h>
*
#include <integer_math.c>
*
#include <string.h>
*
#include <delay.c>
*
#include <itdb02/SmallFont.c>
*
#include <itdb02/BigFont.c>
*
Macros
#define ITDB02_Graph_c
#define ITDB02_24
Functions
void LCD_Writ_Bus (int VH, int VL)
void LCD_Write_COM (int VH, int VL)
void LCD_Write_DATA (int VH, int VL)
void InitLCD (char orientation)
void setXY (int x1, int y1, int x2, int y2)
void drawRect (int x1, int y1, int x2, int y2)
void drawRoundRect (int x1, int y1, int x2, int y2)
void fillRect (int x1, int y1, int x2, int y2)
void fillRoundRect (int x1, int y1, int x2, int y2)
void drawCircle (int x, int y, int radius)
void fillCircle (int x, int y, int radius)
void clrScr ()
void fillScr (char r, char g, char b)
void setColor (unsigned char r, unsigned char g, unsigned char b)
void setBackColor (unsigned char r, unsigned char g, unsigned char b)
void setPixel (int r, int g, int b)
void drawPixel (int x, int y)
void drawLine (int x1, int y1, int x2, int y2)
void drawHLine (int x, int y, int l)
void drawVLine (int x, int y, int l)
void printChar (char c, int x, int y)
void rotateChar (char c, int x, int y, int pos, int deg)
void myGLCD_print (char *st, int x, int y, int deg)
void printNumI (long num, int x, int y)
void printNumF (double num, char dec, int x, int y)
void fontSize (char size)
void drawBitmap (int x, int y, int sx, int sy, unsigned int *data, int scale)
void drawBitmapR (int x, int y, int sx, int sy, unsigned int *data, int deg, int rox, int roy)
Macro Definition Documentation
#define ITDB02_24
Definition at line 62 of file itdb02_graph.c.
#define ITDB02_Graph_c
Definition at line 59 of file itdb02_graph.c.
Function Documentation
void clrScr ()
Definition at line 497 of file itdb02_graph.c.
             {
    unsigned long i;
    
    fastWriteLow(LCD_CS);
    if (orient==PORTRAIT)
        setXY(0,0,239,319);
    else
        setXY(0,0,319,239);
    for (i=0; i<76800; i++)
    {
        setPixel(0,0,0);
    }
    fastWriteHigh(LCD_CS);
}
void drawBitmap (int x, int y, int sx, int sy, unsigned int * data, int scale)
Definition at line 1017 of file itdb02_graph.c.
Referenced by drawBitmapR().
                                                                            {
    unsigned int col;
    int tx, ty, tc, tsx, tsy;
    if (scale==1)
    {
        if (orient==PORTRAIT)
        {
            fastWriteLow(LCD_CS);
            setXY(x, y, x+sx-1, y+sy-1);
            for (tc=0; tc<(sx*sy); tc++)
            {
                col=(unsigned int)(data[tc]);
                LCD_Write_DATA(col>>8,col & 0xff);
            }
            fastWriteHigh(LCD_CS);
        }
        else
        {
            fastWriteLow(LCD_CS);
            for (ty=0; ty<sy; ty++)
            {
                setXY(x, y+ty, x+sx-1, y+ty);
                for (tx=sx; tx>=0; tx--)
                {
                    col=(unsigned int)(data[(ty*sx)+tx]);
                    LCD_Write_DATA(col>>8,col & 0xff);
                }
            }
            fastWriteHigh(LCD_CS);
        }
    }
    else
    {
        if (orient==PORTRAIT)
        {
            fastWriteLow(LCD_CS);
            for (ty=0; ty<sy; ty++)
            {
                setXY(x, y+(ty*scale), x+((sx*scale)-1), y+(ty*scale)+scale);
                for (tsy=0; tsy<scale; tsy++)
                    for (tx=0; tx<sx; tx++)
                    {
                        col=(unsigned int)(data[(ty*sx)+tx]);
                        for (tsx=0; tsx<scale; tsx++)
                            LCD_Write_DATA(col>>8,col & 0xff);
                    }
            }
            fastWriteHigh(LCD_CS);
        }
        else
        {
            fastWriteLow(LCD_CS);
            for (ty=0; ty<sy; ty++)
            {
                for (tsy=0; tsy<scale; tsy++)
                {
                    setXY(x, y+(ty*scale)+tsy, x+((sx*scale)-1), y+(ty*scale)+tsy);
                    for (tx=sx; tx>=0; tx--)
                    {
                        col=(unsigned int)(data[(ty*sx)+tx]);
                        for (tsx=0; tsx<scale; tsx++)
                            LCD_Write_DATA(col>>8,col & 0xff);
                    }
                }
            }
            fastWriteHigh(LCD_CS);
        }
    }
}
void drawBitmapR (int x, int y, int sx, int sy, unsigned int * data, int deg, int rox, int roy)
Definition at line 1088 of file itdb02_graph.c.
                                                                                             {
    unsigned int col;
    int tx, ty, newx, newy;
    char r, g, b;
    //double radian;
    //radian=deg*0.0175;
    if (deg==0)
        drawBitmap(x, y, sx, sy, data, 1);
    else
    {
        for (ty=0; ty<sy; ty++)
            for (tx=0; tx<sx; tx++)
            {
                col=(unsigned int)(data[(ty*sx)+tx]);
                r=(col & 0xF800)>>8;
                g=(((col & 0x7e0)>>5)<<2);
                b=(col & 0x1F)<<3;
                setColor(r,g,b);
                newx=x+rox+(((tx-rox)*cosi(deg))-((ty-roy)*sini(deg)));
                newy=y+roy+(((ty-roy)*cosi(deg))+((tx-rox)*sini(deg)));
                drawPixel(newx, newy);
            }
    }
}
void drawCircle (int x, int y, int radius)
Definition at line 455 of file itdb02_graph.c.
                                         {
  int f = 1 - radius;
  int ddF_x = 1;
  int ddF_y = -2 * radius;
  int x1 = 0;
  int y1 = radius;
 
  drawPixel(x, y + radius);
  drawPixel(x, y - radius);
  drawPixel(x + radius, y);
  drawPixel(x - radius, y);
 
  while(x1 < y1)
  {
    if(f >= 0)
    {
      y1--;
      ddF_y += 2;
      f += ddF_y;
    }
    x1++;
    ddF_x += 2;
    f += ddF_x;
    drawPixel(x + x1, y + y1);
    drawPixel(x - x1, y + y1);
    drawPixel(x + x1, y - y1);
    drawPixel(x - x1, y - y1);
    drawPixel(x + y1, y + x1);
    drawPixel(x - y1, y + x1);
    drawPixel(x + y1, y - x1);
    drawPixel(x - y1, y - x1);
  }
}
void drawHLine (int x, int y, int l)
Definition at line 635 of file itdb02_graph.c.
Referenced by drawLine(), drawRect(), drawRoundRect(), fillRect(), and fillRoundRect().
                                   {
    int i;
    
    fastWriteLow(LCD_CS);
    setXY(x, y, x+l, y);
    for (i=0; i<l+1; i++)
    {
        setPixel(fcolorr, fcolorg, fcolorb);
    }
    fastWriteHigh(LCD_CS);
}
void drawLine (int x1, int y1, int x2, int y2)
Definition at line 554 of file itdb02_graph.c.
                                             {
    int tmp, i;
    double delta, tx, ty;
    double m, b, dx, dy;
    if (((x2-x1)<0)){
        tmp=x1;
        x1=x2;
        x2=tmp;
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    
    if (((y2-y1)<0)){
        tmp=x1;
        x1=x2;
        x2=tmp;
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if (y1==y2){
        if (x1>x2)
        {
            tmp=x1;
            x1=x2;
            x2=tmp;
        }
        drawHLine(x1, y1, x2-x1);
    }
    else if (x1==x2){
        if (y1>y2){
            tmp=y1;
            y1=y2;
            y2=tmp;
        }
        drawVLine(x1, y1, y2-y1);
    }
    else if (abs(x2-x1)>abs(y2-y1)){
        delta=(double)(y2-y1)/(x2-x1);
        ty=(double)y1;
        if (x1>x2) {
            for (i=x1; i>=x2; i--){
                drawPixel(i,(int)(ty+0.5));
                ty=ty-delta;
            }
        }
        else{
            for (i=x1; i<=x2; i++){
                drawPixel(i,(int)(ty+0.5));
                ty=ty+delta;
            }
        }
    }
    else{
        delta=(double)(x2-x1)/(y2-y1);
        tx=(double)x1;
        if (y1>y2) {
            for (i=y2+1; i>y1; i--){
                drawPixel((int)(tx+0.5), i);
                tx=tx+delta;
                }
        }
        else {
            for (i=y1; i<y2+1; i++){
                drawPixel((int)(tx+0.5), i);
                tx=tx+delta;
            }
        }
    }
    if (orient==PORTRAIT){
        setXY(0,0,239,319);
    }
    else{
        setXY(0,0,319,239);
    }
}
void drawPixel (int x, int y)
Definition at line 543 of file itdb02_graph.c.
Referenced by drawBitmapR(), drawCircle(), drawLine(), drawRoundRect(), and fillCircle().
                            {
    fastWriteLow(LCD_CS);
    setXY(x, y, x, y);
    setPixel(fcolorr, fcolorg, fcolorb);
    if (orient==PORTRAIT)
        setXY(0,0,239,319);
    else
        setXY(0,0,319,239);
    fastWriteHigh(LCD_CS);
}
void drawRect (int x1, int y1, int x2, int y2)
Definition at line 331 of file itdb02_graph.c.
                                             {
    int tmp;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    drawHLine(x1, y1, x2-x1);
    drawHLine(x1, y2, x2-x1);
    drawVLine(x1, y1, y2-y1);
    drawVLine(x2, y1, y2-y1);
}
void drawRoundRect (int x1, int y1, int x2, int y2)
Definition at line 353 of file itdb02_graph.c.
{
    int tmp;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if ((x2-x1)>4 && (y2-y1)>4)
    {
        drawPixel(x1+1,y1+1);
        drawPixel(x2-1,y1+1);
        drawPixel(x1+1,y2-1);
        drawPixel(x2-1,y2-1);
        drawHLine(x1+2, y1, x2-x1-4);
        drawHLine(x1+2, y2, x2-x1-4);
        drawVLine(x1, y1+2, y2-y1-4);
        drawVLine(x2, y1+2, y2-y1-4);
    }
}
void drawVLine (int x, int y, int l)
Definition at line 647 of file itdb02_graph.c.
Referenced by drawLine(), drawRect(), drawRoundRect(), and fillRect().
                                   {
    int i;
    fastWriteLow(LCD_CS);
    setXY(x, y, x, y+l);
    for (i=0; i<l; i++)
    {
        setPixel(fcolorr, fcolorg, fcolorb);
    }
    fastWriteHigh(LCD_CS);
}
void fillCircle (int x, int y, int radius)
Definition at line 489 of file itdb02_graph.c.
                                         {
    int x1, y1;
    for(y1=-radius; y1<=radius; y1++)
        for(x1=-radius; x1<=radius; x1++)
            if(x1*x1+y1*y1 <= radius*radius)
                drawPixel(x+x1, y+y1);
}
void fillRect (int x1, int y1, int x2, int y2)
Definition at line 382 of file itdb02_graph.c.
{
    int tmp, i;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if (orient==PORTRAIT)
    {
        for (i=0; i<((y2-y1)/2)+1; i++)
        {
            drawHLine(x1, y1+i, x2-x1);
            drawHLine(x1, y2-i, x2-x1);
        }
    }
    else
    {
        for (i=0; i<((x2-x1)/2)+1; i++)
        {
            drawVLine(x1+i, y1, y2-y1);
            drawVLine(x2-i, y1, y2-y1);
        }
    }
}
void fillRoundRect (int x1, int y1, int x2, int y2)
Definition at line 417 of file itdb02_graph.c.
                                                  {
    int tmp, i;
    if (x1>x2)
    {
        tmp=x1;
        x1=x2;
        x2=tmp;
    }
    if (y1>y2)
    {
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    if ((x2-x1)>4 && (y2-y1)>4)
    {
        for (i=0; i<((y2-y1)/2)+1; i++)
        {
            switch(i)
            {
            case 0:
                drawHLine(x1+2, y1+i, x2-x1-4);
                drawHLine(x1+2, y2-i, x2-x1-4);
                break;
            case 1:
                drawHLine(x1+1, y1+i, x2-x1-2);
                drawHLine(x1+1, y2-i, x2-x1-2);
                break;
            default:
                drawHLine(x1, y1+i, x2-x1);
                drawHLine(x1, y2-i, x2-x1);
            }
        }
    }
}
void fillScr (char r, char g, char b)
Definition at line 512 of file itdb02_graph.c.
                                    {
    long i;
    
    fastWriteLow(LCD_CS);
    if (orient==PORTRAIT)
        setXY(0,0,239,319);
    else
        setXY(0,0,319,239);
    for (i=0; i<76800; i++)
    {
        setPixel (r, g, b);
    }
    fastWriteHigh(LCD_CS);
}
void fontSize (char size)
Definition at line 1008 of file itdb02_graph.c.
{
#ifdef _NO_BIG_FONT_
    fsize = FONT_SMALL;
#else
    fsize = size;
#endif
}
void InitLCD (char orientation)
Definition at line 140 of file itdb02_graph.c.
                              {
  orient=orientation;
  
  LCD_DATA_DIR = 0x00; //Output for All pins on DATA BUS
  LCD_DATA_BUS = 0x0000;
//Pin Mode for Control Pins!
//OLIMEX BOARDS (Arduino Like Boards, using SHIELDs)
#if defined(PIC32_PINGUINO) || defined(PIC32_PINGUINO_OTG)
  fastSetOutputMode(dLCD_RS);
  fastSetOutputMode(dLCD_WR);
  fastSetOutputMode(dLCD_CS);
  fastSetOutputMode(dLCD_REST);
  
  TRISDbits.TRISD4 = 1; //RD4 is connected to D2, don't know why! :-P
  PORTDbits.RD4 = 0;
#else
  fastSetOutputMode(LCD_RS);
  fastSetOutputMode(LCD_WR);
  fastSetOutputMode(LCD_CS);
  fastSetOutputMode(LCD_REST);
#endif
  fastWriteHigh(LCD_REST);
  Delayms(5);
  fastWriteLow(LCD_REST);
  Delayms(5);
  fastWriteHigh(LCD_REST);
  Delayms(5);
  fastWriteLow(LCD_CS);
  //************* Start Initial Sequence **********//
  LCD_Write_COM(0x00,0xE5);
  LCD_Write_DATA(0x78,0xF0); // set SRAM internal timing
  LCD_Write_COM(0x00,0x01);
  LCD_Write_DATA(0x01,0x00); // set SS and SM bit
  LCD_Write_COM(0x00,0x02);
  LCD_Write_DATA(0x07,0x00); // set 1 line inversion
  LCD_Write_COM(0x00,0x03);
  LCD_Write_DATA(0x10,0x30); // set GRAM write direction and BGR=1.
  LCD_Write_COM(0x00,0x04);
  LCD_Write_DATA(0x00,0x00); // Resize register
  LCD_Write_COM(0x00,0x08);
  LCD_Write_DATA(0x02,0x07); // set the back porch and front porch
  LCD_Write_COM(0x00,0x09);
  LCD_Write_DATA(0x00,0x00); // set non-display area refresh cycle ISC[3:0]
  LCD_Write_COM(0x00,0x0A);
  LCD_Write_DATA(0x00,0x00); // FMARK function
  LCD_Write_COM(0x00,0x0C);
  LCD_Write_DATA(0x00,0x00); // RGB interface setting
  LCD_Write_COM(0x00,0x0D);
  LCD_Write_DATA(0x00,0x00); // Frame marker Position
  LCD_Write_COM(0x00,0x0F);
  LCD_Write_DATA(0x00,0x00); // RGB interface polarity
  //*************Power On sequence ****************//
  LCD_Write_COM(0x00,0x10);
  LCD_Write_DATA(0x00,0x00); // SAP, BT[3:0], AP, DSTB, SLP, STB
  LCD_Write_COM(0x00,0x11);
  LCD_Write_DATA(0x00,0x07); // DC1[2:0], DC0[2:0], VC[2:0]
  LCD_Write_COM(0x00,0x12);
  LCD_Write_DATA(0x00,0x00); // VREG1OUT voltage
  LCD_Write_COM(0x00,0x13);
  LCD_Write_DATA(0x00,0x00); // VDV[4:0] for VCOM amplitude
  LCD_Write_COM(0x00,0x07);
  LCD_Write_DATA(0x00,0x01);
  Delayms(50); // Dis-charge capacitor power voltage
  LCD_Write_COM(0x00,0x10);
  LCD_Write_DATA(0x10,0x90); // 1490//SAP, BT[3:0], AP, DSTB, SLP, STB
  LCD_Write_COM(0x00,0x11);
  LCD_Write_DATA(0x02,0x27); // DC1[2:0], DC0[2:0], VC[2:0]
  Delayms(50); // Delay 50ms
  LCD_Write_COM(0x00,0x12);
  LCD_Write_DATA(0x00,0x1F); //001C// Internal reference voltage= Vci;
  Delayms(50); // Delay 50ms
  LCD_Write_COM(0x00,0x13);
  LCD_Write_DATA(0x15,0x00); //0x1000//1400 Set VDV[4:0] for VCOM amplitude 1A00
  LCD_Write_COM(0x00,0x29);
  LCD_Write_DATA(0x00,0x27); //0x0012 //001a Set VCM[5:0] for VCOMH //0x0025 0034
  LCD_Write_COM(0x00,0x2B);
  LCD_Write_DATA(0x00,0x0D); // Set Frame Rate 000C
  Delayms(50); // Delay 50ms
  LCD_Write_COM(0x00,0x20);
  LCD_Write_DATA(0x00,0x00); // GRAM horizontal Address
  LCD_Write_COM(0x00,0x21);
  LCD_Write_DATA(0x00,0x00); // GRAM Vertical Address
  // ----------- Adjust the Gamma Curve ----------//
  LCD_Write_COM(0x00,0x30);
  LCD_Write_DATA(0x00,0x00);
  LCD_Write_COM(0x00,0x31);
  LCD_Write_DATA(0x07,0x07);
  LCD_Write_COM(0x00,0x32);
  LCD_Write_DATA(0x03,0x07);
  LCD_Write_COM(0x00,0x35);
  LCD_Write_DATA(0x02,0x00);
  LCD_Write_COM(0x00,0x36);
  LCD_Write_DATA(0x00,0x08);//0207
  LCD_Write_COM(0x00,0x37);
  LCD_Write_DATA(0x00,0x04);//0306
  LCD_Write_COM(0x00,0x38);
  LCD_Write_DATA(0x00,0x00);//0102
  LCD_Write_COM(0x00,0x39);
  LCD_Write_DATA(0x07,0x07);//0707
  LCD_Write_COM(0x00,0x3C);
  LCD_Write_DATA(0x00,0x02);//0702
  LCD_Write_COM(0x00,0x3D);
  LCD_Write_DATA(0x1D,0x04);//1604
    //------------------ Set GRAM area ---------------//
  LCD_Write_COM(0x00,0x50);
  LCD_Write_DATA(0x00,0x00); // Horizontal GRAM Start Address
  LCD_Write_COM(0x00,0x51);
  LCD_Write_DATA(0x00,0xEF); // Horizontal GRAM End Address
  LCD_Write_COM(0x00,0x52);
  LCD_Write_DATA(0x00,0x00); // Vertical GRAM Start Address
  LCD_Write_COM(0x00,0x53);
  LCD_Write_DATA(0x01,0x3F); // Vertical GRAM Start Address
  LCD_Write_COM(0x00,0x60);
  LCD_Write_DATA(0xA7,0x00); // Gate Scan Line
  LCD_Write_COM(0x00,0x61);
  LCD_Write_DATA(0x00,0x01); // NDL,VLE, REV
  LCD_Write_COM(0x00,0x6A);
  LCD_Write_DATA(0x00,0x00); // set scrolling line
  //-------------- Partial Display Control ---------//
  LCD_Write_COM(0x00,0x80);
  LCD_Write_DATA(0x00,0x00);
  LCD_Write_COM(0x00,0x81);
  LCD_Write_DATA(0x00,0x00);
  LCD_Write_COM(0x00,0x82);
  LCD_Write_DATA(0x00,0x00);
  LCD_Write_COM(0x00,0x83);
  LCD_Write_DATA(0x00,0x00);
  LCD_Write_COM(0x00,0x84);
  LCD_Write_DATA(0x00,0x00);
  LCD_Write_COM(0x00,0x85);
  LCD_Write_DATA(0x00,0x00);
  //-------------- Panel Control -------------------//
  LCD_Write_COM(0x00,0x90);
  LCD_Write_DATA(0x00,0x10);
  LCD_Write_COM(0x00,0x92);
  LCD_Write_DATA(0x06,0x00);
  LCD_Write_COM(0x00,0x07);
  LCD_Write_DATA(0x01,0x33);
  fastWriteHigh(LCD_CS);
  setColor(255, 255, 255);
  setBackColor(0, 0, 0);
  fsize = FONT_SMALL;
}
void LCD_Writ_Bus (int VH, int VL)
Definition at line 119 of file itdb02_graph.c.
References fastWriteHigh, and fastWriteLow.
Referenced by LCD_Write_COM(), and LCD_Write_DATA().
                                {
  LCD_DATA_BUS = VH;
  fastWriteLow(LCD_WR);
  fastWriteHigh(LCD_WR);
  LCD_DATA_BUS = VL;
  fastWriteLow(LCD_WR);
  fastWriteHigh(LCD_WR);
}
void LCD_Write_COM (int VH, int VL)
Definition at line 130 of file itdb02_graph.c.
References fastWriteLow, LCD_RS, and LCD_Writ_Bus().
Referenced by InitLCD(), and setXY().
                                  {
  fastWriteLow(LCD_RS);
  LCD_Writ_Bus(VH,VL);
}
void LCD_Write_DATA (int VH, int VL)
Definition at line 135 of file itdb02_graph.c.
References fastWriteHigh, LCD_RS, and LCD_Writ_Bus().
Referenced by drawBitmap(), InitLCD(), setPixel(), and setXY().
                                  {
  fastWriteHigh(LCD_RS);
  LCD_Writ_Bus(VH,VL);
}
void myGLCD_print (char * st, int x, int y, int deg)
Definition at line 853 of file itdb02_graph.c.
References CENTER, FONT_SMALL, fsize, orient, PORTRAIT, printChar(), RIGHT, and rotateChar().
Referenced by printNumF(), and printNumI().
                                                  {
    int stl, i;
    stl = strlen(st);
    if (fsize==FONT_SMALL)
    {
        if (orient==PORTRAIT)
        {
        if (x==RIGHT)
            x=240-(stl*8);
        if (x==CENTER)
            x=(240-(stl*8))/2;
        }
        else
        {
        if (x==RIGHT)
            x=320-(stl*8);
        if (x==CENTER)
            x=(320-(stl*8))/2;
        }
    }
    else
    {
        if (orient==PORTRAIT)
        {
        if (x==RIGHT)
            x=240-(stl*16);
        if (x==CENTER)
            x=(240-(stl*16))/2;
        }
        else
        {
        if (x==RIGHT)
            x=320-(stl*16);
        if (x==CENTER)
            x=(320-(stl*16))/2;
        }
    }
    for (i=0; i<stl; i++)
        if (deg==0)
            printChar(*st++, x + (i*(fsize*8)), y);
        else
            rotateChar(*st++, x, y, i, deg);
}
void printChar (char c, int x, int y)
Definition at line 658 of file itdb02_graph.c.
Referenced by myGLCD_print().
                                    {
    unsigned char i,j,ch;
    unsigned int temp;
    fastWriteLow(LCD_CS);
  
    if (fsize==FONT_SMALL)
    {
        if (orient==PORTRAIT)
        {
            setXY(x,y,x+7,y+11);
          
            temp=((c-32)*12);
            for(j=0;j<12;j++)
            {
                ch=(SmallFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<(7-i)))!=0)
                    {
                        setPixel(fcolorr, fcolorg, fcolorb);
                    }
                    else
                    {
                        setPixel(bcolorr, bcolorg, bcolorb);
                    }
                }
                temp++;
            }
        }
        else
        {
          
            temp=((c-32)*12);
            for(j=0;j<12;j++)
            {
                setXY(x,y+j,x+7,y+j);
                ch=(SmallFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<i))!=0)
                    {
                        setPixel(fcolorr, fcolorg, fcolorb);
                    }
                    else
                    {
                        setPixel(bcolorr, bcolorg, bcolorb);
                    }
                }
                temp++;
            }
        }
    }
#ifndef _NO_BIG_FONT_
    else {
        if (orient==PORTRAIT)
        {
            setXY(x,y,x+15,y+15);
          
            temp=((c-32)*32);
            for(j=0;j<32;j++)
            {
                ch=(BigFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<(7-i)))!=0)
                    {
                        setPixel(fcolorr, fcolorg, fcolorb);
                    }
                    else
                    {
                        setPixel(bcolorr, bcolorg, bcolorb);
                    }
                }
                temp++;
            }
        }
        else
        {
            temp=((c-32)*32);
            for(j=0;j<32;j+=2)
            {
                setXY(x,y+(j/2),x+15,y+(j/2));
                ch=(BigFont[temp+1]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<i))!=0)
                    {
                        setPixel(fcolorr, fcolorg, fcolorb);
                    }
                    else
                    {
                        setPixel(bcolorr, bcolorg, bcolorb);
                    }
                }
                ch=(BigFont[temp]);
                for(i=0;i<8;i++)
                {
                    if((ch&(1<<i))!=0)
                    {
                        setPixel(fcolorr, fcolorg, fcolorb);
                    }
                    else
                    {
                        setPixel(bcolorr, bcolorg, bcolorb);
                    }
                }
                temp+=2;
            }
        }
    }
#endif
    fastWriteHigh(LCD_CS);
}
void printNumF (double num, char dec, int x, int y)
Definition at line 942 of file itdb02_graph.c.
                                                  {
  char buf[25];
  char st[27];
  unsigned char neg=0;
  int i,c=0;
  int c2;
  unsigned long inum;
  
  if (num==0)
  {
      st[0]=48;
      st[1]=46;
      for (i=0; i<dec; i++)
          st[2+i]=48;
      st[2+dec]=0;
  }
  else
  {
      if (num<0)
      {
        neg=1;
        num=-num;
      }
      
      if (dec<1)
        dec=1;
      if (dec>5)
        dec=5;
      
      inum=(long)(num*powi(10,dec));
      
      while (inum>0)
      {
        buf[c]=48+(inum % 10);
        c++;
        inum=(inum-(inum % 10))/10;
      }
      if ((num<1) && (num>0))
      {
          buf[c]=48;
          c++;
      }
      buf[c]=0;
      
      if (neg)
      {
        st[0]=45;
      }
      
      c2=neg;
      for (i=0; i<c; i++)
      {
        st[c2]=buf[c-i-1];
        c2++;
        if ((c-(c2-neg))==dec)
        {
          st[c2]=46;
          c2++;
        }
      }
      st[c2]=0;
  }
  myGLCD_print(st,x,y,0);
}
void printNumI (long num, int x, int y)
Definition at line 900 of file itdb02_graph.c.
                                      {
  char buf[25];
  char st[27];
  unsigned char neg=0;
  int i,c=0;
  
  if (num==0)
  {
      st[0]=48;
      st[1]=0;
  }
  else
  {
      if (num<0)
      {
        neg=1;
        num=-num;
      }
      
      while (num>0)
      {
        buf[c]=48+(num % 10);
        c++;
        num=(num-(num % 10))/10;
      }
      buf[c]=0;
      
      if (neg)
      {
        st[0]=45;
      }
      
      for (i=0; i<c; i++)
      {
        st[i+neg]=buf[c-i-1];
      }
      st[c+neg]=0;
  }
  myGLCD_print(st,x,y,0);
}
void rotateChar (char c, int x, int y, int pos, int deg)
Definition at line 773 of file itdb02_graph.c.
Referenced by myGLCD_print().
                                                       {
    char i,j,ch;
    unsigned int temp;
    int newx,newy;
    //double radian;
    //radian=deg*0.0175;
    fastWriteLow(LCD_CS);
    if (fsize==FONT_SMALL)
    {
        temp=((c-32)*12);
        for(j=0;j<12;j++)
        {
            ch=(SmallFont[temp]);
            for(i=0;i<8;i++)
            {
                newx=x+(((i+(pos*8))*cosi(deg))-((j)*sini(deg)));
                newy=y+(((j)*cosi(deg))+((i+(pos*8))*sini(deg)));
                setXY(newx,newy,newx+1,newy+1);
                
                if((ch&(1<<(7-i)))!=0)
                {
                    setPixel(fcolorr, fcolorg, fcolorb);
                }
                else
                {
                    setPixel(bcolorr, bcolorg, bcolorb);
                }
            }
            temp++;
        }
    }
#ifndef _NO_BIG_FONT_
    else{
        temp=((c-32)*32);
        for(j=0;j<16;j++)
        {
            ch=(BigFont[temp]);
            for(i=0;i<8;i++)
            {
                newx=x+(((i+(pos*16))*cosi(deg))-((j)*sini(deg)));
                newy=y+(((j)*cosi(deg))+((i+(pos*16))*sini(deg)));
                setXY(newx,newy,newx+1,newy+1);
                
                if((ch&(1<<(7-i)))!=0)
                {
                    setPixel(fcolorr, fcolorg, fcolorb);
                }
                else
                {
                    setPixel(bcolorr, bcolorg, bcolorb);
                }
            }
            temp++;
            ch=(BigFont[temp]);
            for(i=8;i<16;i++)
            {
                newx=x+(((i+(pos*16))*cosi(deg))-((j)*sini(deg)));
                newy=y+(((j)*cosi(deg))+((i+(pos*16))*sini(deg)));
                setXY(newx,newy,newx+1,newy+1);
                
                if((ch&(1<<(15-i)))!=0)
                {
                    setPixel(fcolorr, fcolorg, fcolorb);
                }
                else
                {
                    setPixel(bcolorr, bcolorg, bcolorb);
                }
            }
            temp++;
        }
    }
#endif
    fastWriteHigh(LCD_CS);
}
void setBackColor (unsigned char r, unsigned char g, unsigned char b)
Definition at line 533 of file itdb02_graph.c.
Referenced by InitLCD().
                                                                    {
    bcolorr=r;
    bcolorg=g;
    bcolorb=b;
}
void setColor (unsigned char r, unsigned char g, unsigned char b)
Definition at line 527 of file itdb02_graph.c.
Referenced by drawBitmapR(), and InitLCD().
                                                                {
    fcolorr=r;
    fcolorg=g;
    fcolorb=b;
}
void setPixel (int r, int g, int b)
Definition at line 539 of file itdb02_graph.c.
Referenced by clrScr(), drawHLine(), drawPixel(), drawVLine(), fillScr(), printChar(), and rotateChar().
                                {
    LCD_Write_DATA(((r&248)|g>>5),((g&28)<<3|b>>3));
}
void setXY (int x1, int y1, int x2, int y2)
Definition at line 299 of file itdb02_graph.c.
Referenced by clrScr(), drawBitmap(), drawHLine(), drawLine(), drawPixel(), drawVLine(), fillScr(), printChar(), and rotateChar().
                                          {
    int tmp;
    if (orient==LANDSCAPE)
    {
        tmp=x1;
        x1=y1;
        y1=319-tmp;
        tmp=x2;
        x2=y2;
        y2=319-tmp;
        tmp=y1;
        y1=y2;
        y2=tmp;
    }
    LCD_Write_COM(0x00,0x20);
    LCD_Write_DATA(x1>>8,x1);
    LCD_Write_COM(0x00,0x21);
    LCD_Write_DATA(y1>>8,y1);
       
    LCD_Write_COM(0x00,0x50);
    LCD_Write_DATA(x1>>8,x1);
    LCD_Write_COM(0x00,0x52);
    LCD_Write_DATA(y1>>8,y1);
    LCD_Write_COM(0x00,0x51);
    LCD_Write_DATA(x2>>8,x2);
    LCD_Write_COM(0x00,0x53);
    LCD_Write_DATA(y2>>8,y2);
    LCD_Write_COM(0x00,0x22);
}