/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/itdb02/itdb02_touch.c File Reference
#include <itdb02/itdb02_touch.h>
*
#include <digitalw.c>
*
Macros
#define ITDB02_Touch_c
#define PixSizeX 15
#define PixOffsX 220
#define PixSizeY 11
#define PixOffsY 358
Functions
void touch_setTouch (unsigned char tclk, unsigned char tcs, unsigned char din, unsigned char dout, unsigned char irq)
void touch_initTouch (unsigned char orient_tation)
void touch_writeData (unsigned char data)
unsigned int touch_readData ()
void touch_read ()
unsigned char touch_dataAvailable ()
int touch_getX ()
int touch_getY ()
void touch_setPrecision (unsigned char precision)
Macro Definition Documentation
#define ITDB02_Touch_c
Definition at line 41 of file itdb02_touch.c.
#define PixOffsX 220
Definition at line 61 of file itdb02_touch.c.
Referenced by touch_getX(), and touch_getY().
#define PixOffsY 358
Definition at line 63 of file itdb02_touch.c.
Referenced by touch_getX(), and touch_getY().
#define PixSizeX 15
Definition at line 60 of file itdb02_touch.c.
Referenced by touch_getX(), and touch_getY().
#define PixSizeY 11
Definition at line 62 of file itdb02_touch.c.
Referenced by touch_getX(), and touch_getY().
Function Documentation
unsigned char touch_dataAvailable ()
Definition at line 156 of file itdb02_touch.c.
References digitalread(), and T_IRQ.
                                   {
  unsigned char avail;
  avail = !digitalread(T_IRQ);
  return avail;
}
int touch_getX ()
Definition at line 162 of file itdb02_touch.c.
References orient_t, PixOffsX, PixOffsY, PixSizeX, PixSizeY, PORTRAIT, TP_X, and TP_Y.
                {
    int value;
    if (orient_t == PORTRAIT) {
        if (PixSizeX>=0) {
        value = (240-(TP_X-PixOffsX)/PixSizeX);
        }
        else {
        value = ((TP_X-PixOffsX)/-(PixSizeX));
        }
    }
    else {
    if (PixSizeY<0)
        value = (400-(TP_Y-PixOffsY)/-PixSizeY);
    else
        value = ((TP_Y-PixOffsY)/PixSizeY);
    }
    if (value < 0)
    value = 0;
    
    return value;
}
int touch_getY ()
Definition at line 186 of file itdb02_touch.c.
References orient_t, PixOffsX, PixOffsY, PixSizeX, PixSizeY, PORTRAIT, TP_X, and TP_Y.
                {
    int value;
    if (orient_t == PORTRAIT){
        if (PixSizeY<0)
            value = ((TP_Y-PixOffsY)/-PixSizeY);
        else
            value = (320-(TP_Y-PixOffsY)/PixSizeY);
    }
    else{
    if (PixSizeX>=0){
        value = (240-(TP_X-PixOffsX)/PixSizeX);
    }
    else{
        value = ((TP_X-PixOffsX)/-(PixSizeX));
    }
    }
    if (value < 0)
        value = 0;
    return value;
}
void touch_initTouch (unsigned char orient_tation)
Definition at line 78 of file itdb02_touch.c.
References digitalwrite(), HIGH, INPUT, orient_t, OUTPUT, pinmode(), T_CLK, T_CS, T_DIN, T_DOUT, and T_IRQ.
                                                 {
    orient_t = orient_tation;
    pinmode(T_CLK, OUTPUT);
    pinmode(T_CS, OUTPUT);
    pinmode(T_DIN, OUTPUT);
    pinmode(T_DOUT, INPUT);
    pinmode(T_IRQ, INPUT);
    digitalwrite(T_CS, HIGH);
    digitalwrite(T_CLK, HIGH);
    digitalwrite(T_DIN, HIGH);
    digitalwrite(T_CLK, HIGH);
}
void touch_read ()
Definition at line 132 of file itdb02_touch.c.
References digitalwrite(), HIGH, LOW, prec, T_CLK, T_CS, touch_readData(), touch_writeData(), TP_X, and TP_Y.
                  {
    unsigned long tx=0;
    unsigned long ty=0;
    int i;
    
    digitalwrite(T_CS,LOW);
                  
    for (i=0; i<prec; i++){
    touch_writeData(0x90);
    digitalwrite(T_CLK,HIGH);
    digitalwrite(T_CLK,LOW);
    ty+=touch_readData();
    touch_writeData(0xD0);
    digitalwrite(T_CLK,HIGH);
    digitalwrite(T_CLK,LOW);
    tx+=touch_readData();
    }
    digitalwrite(T_CS,HIGH);
    
    TP_X=tx/prec;
    TP_Y=ty/prec;
}
unsigned int touch_readData ()
Definition at line 115 of file itdb02_touch.c.
References digitalread(), digitalwrite(), HIGH, LOW, nop, T_CLK, and T_DOUT.
Referenced by touch_read().
                             {
    unsigned char nop;
    unsigned int data = 0;
    unsigned char count;
    
    for(count=0; count<12; count++) {
    data <<= 1;
    digitalwrite(T_CLK, HIGH);
    nop++;
    digitalwrite(T_CLK, LOW);
    nop++;
    if (digitalread(T_DOUT))
        data++;
    }
    return(data);
}
void touch_setPrecision (unsigned char precision)
Definition at line 209 of file itdb02_touch.c.
References prec, PREC_EXTREME, PREC_HI, PREC_LOW, and PREC_MEDIUM.
                                                {
    switch (precision){
    case PREC_LOW:
        prec=1;
        break;
    case PREC_MEDIUM:
        prec=10;
        break;
    case PREC_HI:
        prec=25;
        break;
    case PREC_EXTREME:
        prec=100;
        break;
    default:
        prec=10;
        break;
    }
}
void touch_setTouch (unsigned char tclk, unsigned char tcs, unsigned char din, unsigned char dout, unsigned char irq)
Definition at line 70 of file itdb02_touch.c.
References T_CLK, T_CS, T_DIN, T_DOUT, and T_IRQ.
                                                                                                           
               {
    T_CLK = tclk;
    T_CS = tcs;
    T_DIN = din;
    T_DOUT= dout;
    T_IRQ = irq;
}
void touch_writeData (unsigned char data)
Definition at line 93 of file itdb02_touch.c.
References digitalwrite(), HIGH, LOW, nop, T_CLK, and T_DIN.
Referenced by touch_read().
                                        {
    unsigned char temp;
    unsigned char nop;
    unsigned char count;
    temp=data;
    digitalwrite(T_CLK,LOW);
    
    for(count=0; count<8; count++) {
    if(temp & 0x80)
        digitalwrite(T_DIN, HIGH);
    else
        digitalwrite(T_DIN, LOW);
    
    temp = temp << 1;
    digitalwrite(T_CLK, LOW);
    nop++;
    digitalwrite(T_CLK, HIGH);
    nop++;
    }
}