/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/keypad32.h File Reference
Macros
#define KEY_RELEASED NO_KEY
#define makeKeymap(x) ((char *)x)
Enumerations
enum KeypadState {
*
IDLE =0,
PRESSED,
RELEASED,
HOLD,
*
IDLE =0,
PRESSED,
RELEASED,
HOLD
 }
Functions
void Keypad_init (char *keypadmap, uchar *rowp, uchar *colp, uchar rows, uchar cols)
char Keypad_getKey ()
KeypadState Keypad_getState ()
void Keypad_setDebounceTime (unsigned int debounce)
void Keypad_setHoldTime (unsigned int hold)
void Keypad_transitionTo (KeypadState newState)
void Keypad_initializePins ()
Variables
const char NO_KEY = '\0'
Macro Definition Documentation
#define KEY_RELEASED NO_KEY
Definition at line 18 of file keypad32.h.
#define makeKeymap(x) ((char *)x)
Definition at line 21 of file keypad32.h.
Enumeration Type Documentation
enum KeypadState
Enumerator
IDLE
PRESSED
RELEASED
HOLD
IDLE
PRESSED
RELEASED
HOLD
Definition at line 9 of file keypad32.h.
             {
    IDLE=0,
    PRESSED,
    RELEASED,
    HOLD
} KeypadState;
Function Documentation
char Keypad_getKey ()
Definition at line 105 of file keypad.c.
References c, columnPins, currentKey, debounceTime, digitalread(), digitalwrite(), HIGH, HOLD, holdTime, keypad_columns, keypad_rows, Keypad_transitionTo(), lastUpdate, LOW, millis(), NO_KEY, PRESSED, RELEASED, rowPins, state, and userKeymap.
                    {
    
    char key = NO_KEY; // Assume that no key is pressed, this is the default return for getKey()
    unsigned char c,r;
    for (c=0; c<keypad_columns; c++){
        digitalwrite(columnPins[c],LOW); // Activate the current column.
        for (r=0; r<keypad_rows; r++){ // Scan all the rows for a key press.
            // The user pressed a button for more then debounceTime microseconds.
            if (currentKey == userKeymap[c+(r*keypad_columns)]){
                // Button hold
                if (((Millis()-lastUpdate) >= holdTime) &&
      digitalread(rowPins[r]) == LOW){
                    Keypad_transitionTo(HOLD);
                }
                // Button release
                if (((Millis()-lastUpdate) >= debounceTime) &&
      digitalread(rowPins[r]) == HIGH){
                    Keypad_transitionTo(RELEASED);
                    currentKey = NO_KEY;
                }
            }
            // Button pressed event. The user pressed a button.
            else if (((Millis()-lastUpdate) >= debounceTime) &&
      digitalread(rowPins[r]) == LOW){
                digitalwrite(columnPins[c],HIGH); // De-activate the current
       column.
                key = userKeymap[c+(r*keypad_columns)];
                lastUpdate = Millis();
                goto EVALUATE_KEY; // Save resources and do not attempt to parse two keys at a
       time
            }
        }
        digitalwrite(columnPins[c],HIGH); // De-activate the current column.
    }
    
    EVALUATE_KEY:
    if (key != NO_KEY && key != currentKey){
        currentKey = key;
        Keypad_transitionTo(PRESSED);
        return currentKey;
    }
    else{
        return NO_KEY;
    }
}
KeypadState Keypad_getState ()
Definition at line 42 of file keypad.c.
References state.
                             {
    return state;
}
void Keypad_init (char * keypadmap, uchar * rowp, uchar * colp, uchar rows, uchar cols)
Definition at line 85 of file keypad.c.
References columnPins, currentKey, debounceTime, holdTime, IDLE, keypad_columns, Keypad_initializePins(), keypad_rows, lastUpdate, NO_KEY, rowPins, state, and userKeymap.
                                                                                   {
        userKeymap = keypadmap;
    rowPins = rowp;
    columnPins = colp;
    keypad_rows = rows;
    keypad_columns = cols;
    lastUpdate = 0;
    debounceTime = 50;
    holdTime = 1000;
// keypadEventListener = 0;
    currentKey = NO_KEY;
    state = IDLE;
    
    Keypad_initializePins();
}
void Keypad_initializePins ()
Definition at line 69 of file keypad.c.
References c, columnPins, digitalwrite(), HIGH, INPUT, keypad_columns, keypad_rows, OUTPUT, pinmode(), and rowPins.
Referenced by Keypad_init().
                            {
    unsigned char c,r;
    for (r=0; r<keypad_rows; r++){
        for (c=0; c<keypad_columns; c++){
            pinmode(columnPins[c],OUTPUT);
            digitalwrite(columnPins[c],HIGH);
        }
        //configure row pin modes and states
        pinmode(rowPins[r],INPUT);
        digitalwrite(rowPins[r],HIGH);
    }
}
void Keypad_setDebounceTime (unsigned int debounce)
Definition at line 46 of file keypad.c.
References debounceTime.
                                                  {
    debounceTime = debounce;
}
void Keypad_setHoldTime (unsigned int hold)
Definition at line 49 of file keypad.c.
References holdTime.
                                          {
    holdTime = hold;
}
void Keypad_transitionTo (KeypadState newState)
Definition at line 59 of file keypad.c.
References state.
Referenced by Keypad_getKey().
                                              {
    if (state!=newState){
        state = newState;
// if (keypadEventListener!=NULL){
// keypadEventListener(currentKey);
// }
    }
}
Variable Documentation
const char NO_KEY = '\0'
Definition at line 17 of file keypad32.h.