/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/list.c File Reference
#include <typedef.h>
*
#include <const.h>
*
#include <stdlib.h>
*
#include <list.h>
*
#include <stdio.h>
*
#include <pinguinoserial1.c>
*
Macros
#define __LIST_C__
Functions
List * list_prepend (List *pList, void *data)
List * list_append (List *pList, void *data)
void list_free (List *pList)
void list_free_full (List *pList, void(*free_func)(void *data))
void list_free_full_simple (List *pList)
u32 list_nb_item (List *pList)
List * list_free_item (List *pList, void *data)
List * list_free_item_with_check (List *pList, void *data, boolean *done)
void * list_item (List *pList, u32 item_nb)
List * list_insert_after_item (List *pList, void *before, void *data)
List * list_concat (List *p1, List *p2)
List * list_pop (List *pList, void **data)
List * list_copy (List *pList)
List * list_copy_full (List *pList, void *(*copy_func)(void *data))
List * list_free_chunk (List *pList, List *pToFree)
List * list_sort (List *pList, int(*cmp_func)(void *p1, void *p2))
List * list_insert_sorted (List *pList, int(*cmp_func)(void *p1, void *p2), void *data)
List * list_invert (List *pList)
List * list_find (List *pList, void *data)
List * list_find_full (List *pList, void *your_data, boolean(*find_func)(void *data, void *your_data))
Macro Definition Documentation
#define __LIST_C__
Definition at line 11 of file list.c.
Function Documentation
List* list_append (List * pList, void * data)
Definition at line 55 of file list.c.
References _List::data, _List::next, NULL, and _List::prev.
Referenced by list_copy(), list_copy_full(), and list_sort().
{ List *vList;
  /* on alloue la memoire pour le nouvelle element */
  if((vList = (List *)malloc(sizeof(List))) == NULL)
  {
    #ifdef DEBUG
    serial1printf("malloc failed\n ");
    #endif
    exit(1);
  }
  if(pList == NULL)
  { /* la liste est vide */
    vList->data = data;
    vList->prev = vList;
    vList->next = vList;
    return(vList);
  } else {
    /* il y a deja au moins un element dans la liste */
    vList->data = data;
    vList->prev = pList->prev;
    vList->next = pList;
    pList->prev->next = vList;
    pList->prev = vList;
    return(pList);
  }
}
List* list_concat (List * p1, List * p2)
Definition at line 321 of file list.c.
References _List::next, NULL, and _List::prev.
{ List *vListPrev;
  if(p1 == NULL) return(p2);
  if(p2 == NULL) return(p1);
  p1->prev->next = p2;
  vListPrev = p1->prev;
  p1->prev = p2->prev;
  p2->prev->next = p1;
  p2->prev = vListPrev;
    
  return(p1);
}
List* list_copy (List * pList)
Definition at line 369 of file list.c.
References _List::data, list_append(), list_is_end, list_move_next, and list_new.
{ List *vListMove, *vCopy;
  vCopy = list_new();
  for(vListMove = pList;!list_is_end(pList,vListMove);list_move_next(pList,
      vListMove))
  {
    vCopy = list_append(vCopy, vListMove->data);
  }
  return(vCopy);
}
List* list_copy_full (List * pList, void *(*)(void *data) copy_func)
Definition at line 385 of file list.c.
References _List::data, list_append(), list_is_end, list_move_next, and list_new.
{ List *vListMove, *vCopy;
  vCopy = list_new();
  for(vListMove = pList;!list_is_end(pList,vListMove);list_move_next(pList,
      vListMove))
  {
    vCopy = list_append(vCopy, copy_func(vListMove->data));
  }
  return(vCopy);
}
List* list_find (List * pList, void * data)
Definition at line 536 of file list.c.
References list_data, list_is_end, and list_move_next.
{ List *vListMove;
  for(vListMove = pList; !list_is_end(pList,vListMove) && (list_data(vListMove) != data
      );
    list_move_next(pList,vListMove));
  return(vListMove);
}
List* list_find_full (List * pList, void * your_data, boolean(*)(void *data, void *your_data) find_func)
Definition at line 552 of file list.c.
References list_data, list_is_end, and list_move_next.
{ List *vListMove;
  for(vListMove = pList;
    !list_is_end(pList,vListMove) && !find_func(list_data(vListMove),your_data);
    list_move_next(pList,vListMove));
  return(vListMove);
}
void list_free (List * pList)
Definition at line 87 of file list.c.
References list_is_end, and list_next.
{ List *vListMove,*vListMoveNext;
  vListMove = pList;
  while(!list_is_end(pList,vListMove))
  {
    vListMoveNext = list_next(pList,vListMove);
    free(vListMove);
    vListMove = vListMoveNext;
  }
}
List* list_free_chunk (List * pList, List * pToFree)
Definition at line 400 of file list.c.
References _List::next, NULL, and _List::prev.
Referenced by list_sort().
{ List *vListNext;
  if(pList == NULL) return(NULL);
  if(pToFree == NULL) return(pList);
  /* si il n'y a que notre element dans la liste */
  if(pToFree->next == pToFree)
  { /* on libere l'element */
    free(pToFree);
    /* on renvoie une liste vide */
    return(NULL);
  } else {
    /* on recupere l'element qui suit celui que l'on veut supprimer */
    vListNext = pToFree->next;
    /* on chaine l'element precedent avec celui qui suit */
    pToFree->prev->next = vListNext;
    vListNext->prev = pToFree->prev;
    /* on libere l'element a liberer */
    free(pToFree);
    if(pList == pToFree)
    {
      /* l'element a supprimer etait le premier, c'est */
      /* donc le suivant qui devient le premier */
      return(vListNext);
    } else {
      /* l'element a supprimer n'etait pas le premier. */
      /* le premiere element de la liste ne change donc pas. */
      return(pList);
    }
  }
}
void list_free_full (List * pList, void(*)(void *data) free_func)
Definition at line 102 of file list.c.
References _List::data, list_is_end, and list_next.
{ List *vListMove,*vListMoveNext;
  vListMove = pList;
  while(!list_is_end(pList,vListMove))
  {
    vListMoveNext = list_next(pList,vListMove);
    free_func(vListMove->data);
    free(vListMove);
    vListMove = vListMoveNext;
  }
}
void list_free_full_simple (List * pList)
Definition at line 118 of file list.c.
References _List::data, list_is_end, list_next, and NULL.
{ List *vListMove,*vListMoveNext;
  vListMove = pList;
  while(!list_is_end(pList,vListMove))
  {
    vListMoveNext = list_next(pList,vListMove);
    if(vListMove->data != NULL) free(vListMove->data);
    free(vListMove);
    vListMove = vListMoveNext;
  }
}
List* list_free_item (List * pList, void * data)
Definition at line 152 of file list.c.
References _List::data, list_is_end, list_move_next, _List::next, NULL, and _List::prev.
{ List *vListMove,*vListMoveNext;
  /* on parcourt la liste pList a la recherche de l'element a supprimer */
  vListMove = pList;
  while(!list_is_end(pList,vListMove) && (vListMove->data != data))
  { list_move_next(pList,vListMove); }
  /* si on a trouve l'element, on le libere */
  if(!list_is_end(pList,vListMove))
  {
    /* si il n'y a que notre element dans la liste */
    if(vListMove->next == vListMove)
    { /* on libere l'element */
      free(vListMove);
      /* on renvoie une liste vide */
      return(NULL);
    } else {
      /* on recupere l'element qui suit celui que l'on veut supprimer */
      vListMoveNext = vListMove->next;
      /* on chaine l'element precedent avec celui qui suit */
      vListMove->prev->next = vListMoveNext;
      vListMoveNext->prev = vListMove->prev;
      /* on libere l'element a liberer */
      free(vListMove);
      if(pList == vListMove)
      {
        /* l'element a supprimer etait le premier, c'est */
        /* donc le suivant qui devient le premier */
        return(vListMoveNext);
      } else {
        /* l'element a supprimer n'etait pas le premier. */
        /* le premiere element de la liste ne change donc pas. */
        return(pList);
      }
    }
  }
  /* si on est ici c'est l'element a supprimer n'existe */
  /* pas dans la liste. on rend donc la liste intacte. */
  return(pList);
}
List* list_free_item_with_check (List * pList, void * data, boolean * done)
Definition at line 198 of file list.c.
References _List::data, FALSE, list_is_end, list_move_next, _List::next, NULL, _List::prev, and TRUE.
{ List *vListMove,*vListMoveNext;
  /* on parcourt la liste pList a la recherche de l'element a supprimer */
  vListMove = pList;
  while(!list_is_end(pList,vListMove) && (vListMove->data != data))
  { list_move_next(pList,vListMove); }
  /* si on a trouve l'element, on le libere */
  if(!list_is_end(pList,vListMove))
  {
    /* on signal que l'element a bien ete trouve */
    *done = TRUE;
    /* si il n'y a que notre element dans la liste */
    if(vListMove->next == vListMove)
    { /* on libere l'element */
      free(vListMove);
      /* on renvoie une liste vide */
      return(NULL);
    } else {
      /* on recupere l'element qui suit celui que l'on veut supprimer */
      vListMoveNext = vListMove->next;
      /* on chaine l'element precedent avec celui qui suit */
      vListMove->prev->next = vListMoveNext;
      vListMoveNext->prev = vListMove->prev;
      /* on libere l'element a liberer */
      free(vListMove);
      if(pList == vListMove)
      {
        /* l'element a supprimer etait le premier, c'est */
        /* donc le suivant qui devient le premier */
        return(vListMoveNext);
      } else {
        /* l'element a supprimer n'etait pas le premier. */
        /* le premiere element de la liste ne change donc pas. */
        return(pList);
      }
    }
  }
  /* si on est ici c'est l'element a supprimer n'existe pas dans la liste.*/
  /* on signal de fait que l'on n'a pas trouve l'element cherche. */
  *done = FALSE;
  /* on rend donc la liste intacte. */
  return(pList);
}
List* list_insert_after_item (List * pList, void * before, void * data)
Definition at line 271 of file list.c.
References _List::data, list_is_end, list_move_next, _List::next, NULL, and _List::prev.
{ List *vList;
  List *vListMove;
  /* on alloue la memoire pour le nouvelle element */
  if((vList = (List *)malloc(sizeof(List))) == NULL)
  {
    #ifdef DEBUG
    serial1printf("malloc failed\n");
    #endif
    exit(1);
  }
  vListMove = pList;
  while(!list_is_end(pList,vListMove) && (vListMove->data != before))
  { list_move_next(pList,vListMove); }
  /* si on a trouve l'element precedent */
  if(!list_is_end(pList,vListMove))
  {
    vList->data = data;
    vList->prev = vListMove;
    vList->next = vListMove->next;
    vListMove->next = vList;
    vList->next->prev = vList;
    return(pList);
  /* si on n'a pas trouve l'element precedent */
  } else {
    if(pList == NULL)
    { /* si la liste est vide */
      vList->data = data;
      vList->prev = vList;
      vList->next = vList;
      return(vList);
    } else {
      /* c'est une insertion en queue d'une liste non vide */
      vList->data = data;
      vList->prev = pList->prev;
      vList->next = pList;
      vList->prev->next = vList;
      pList->prev = vList;
      return(pList);
    }
  }
}
List* list_insert_sorted (List * pList, int(*)(void *p1, void *p2) cmp_func, void * data)
Definition at line 473 of file list.c.
References _List::data, list_data, list_is_empty, list_is_end, list_move_next, _List::next, NULL, and _List::prev.
{ List *vListMove, *vList;
  /* on recherche le premier element superieur ou egale au nouveau */
  for(vListMove = pList; !list_is_end(pList,vListMove) &&
    (cmp_func(list_data(vListMove),data) < 0);
    vListMove = list_move_next(pList,vListMove));
  /* on alloue la memoire pour le nouvelle element */
  if((vList = (List *)malloc(sizeof(List))) == NULL)
  {
    #ifdef DEBUG
    serial1printf("malloc failed\n");
    #endif
    exit(1);
  }
  if(list_is_empty(pList))
  { /* si la liste est vide */
    vList->data = data;
    vList->prev = vList;
    vList->next = vList;
    return(vList);
  } else {
    vList->data = data;
    vList->prev = vListMove->prev;
    vList->next = vListMove;
    vListMove->prev = vList;
    vList->prev->next = vList;
    if(pList == vListMove)
      return(vList);
    else
      return(pList);
  }
}
List* list_invert (List * pList)
Definition at line 516 of file list.c.
References _List::next, NULL, and _List::prev.
{ List *vListMove, *vListMoveNext;
  
  if(pList == NULL) return(NULL);
  
  vListMove = pList;
  do {
    vListMoveNext = vListMove->next;
    vListMove->next = vListMove->prev;
    vListMove->prev = vListMoveNext;
    vListMove = vListMoveNext;
  } while(vListMove != pList);
  /* pList est devenu le dernier element, donc le premier est celui qui suit */
  return(pList->next);
}
void* list_item (List * pList, u32 item_nb)
Definition at line 248 of file list.c.
References _List::data, list_is_end, list_move_next, and NULL.
{ List *vListMove;
  u32 offset=0;
  vListMove = pList;
  while(!list_is_end(pList,vListMove) && (offset<item_nb-1))
  { list_move_next(pList,vListMove); offset++; }
  if(!list_is_end(pList,vListMove))
  { /* si il y a bien un element a la position demande, on le renvoie */
    return(vListMove->data);
  } else {
    /* si on c'est retrouve a la fin de la liste, il n'y a pas d'element */
    /* a la postion demande. On renvoie donc NULL pour le signaler */
    return(NULL);
  }
}
u32 list_nb_item (List * pList)
Definition at line 135 of file list.c.
References list_is_end, and list_move_next.
{ List *vListMove;
  u32 compteur = 0;
  vListMove = pList;
  while(!list_is_end(pList,vListMove))
  {
    compteur++;
    list_move_next(pList,vListMove);
  }
  return(compteur);
}
List* list_pop (List * pList, void ** data)
Definition at line 341 of file list.c.
References _List::data, _List::next, NULL, and _List::prev.
{ List *vListPrev;
  if(pList == NULL) { *data = NULL; return(NULL); }
  
  /* si il n'y a que notre element dans la liste */
  if(pList->next == pList)
  {
    *data = pList->data;
    /* on libere l'element */
    free(pList);
    /* on renvoie une liste vide */
    return(NULL);
  } else {
    *data = pList->prev->data;
    vListPrev = pList->prev->prev;
    vListPrev->next = pList;
    free(pList->prev);
    pList->prev = vListPrev;
    return(pList);
  }
}
List* list_prepend (List * pList, void * data)
Definition at line 23 of file list.c.
References _List::data, _List::next, NULL, and _List::prev.
{ List *vList;
  /* on alloue la memoire pour le nouvel element */
  if((vList = (List *)malloc(sizeof(List))) == NULL)
  {
    #ifdef DEBUG
    serial1printf("malloc failed\n");
    #endif
    exit(1);
  }
  if(pList == NULL)
  { /* la liste est vide */
    vList->data = data;
    vList->prev = vList;
    vList->next = vList;
  } else {
    /* il y a deja au moins un element dans la liste */
    vList->data = data;
    vList->prev = pList->prev;
    vList->next = pList;
    pList->prev->next = vList;
    pList->prev = vList;
  }
  return(vList);
}
List* list_sort (List * pList, int(*)(void *p1, void *p2) cmp_func)
Definition at line 440 of file list.c.
References list_append(), list_data, list_free_chunk(), list_is_empty, list_is_end, list_move_next, list_new, and list_next.
{ List *vListMove;
  List *vListSmallest;
  List *vListRes;
  vListRes = list_new();
  /* l'algorithme de trie utilise est le trie par selection */
  /* cela consiste a chercher le plus petit element le sortir de */
  /* la liste pList et le rajouter a la fin de la liste vListRes */
  /* et de repeter cela jusqu'a ce qu'il n'y ai plus rien dans pList */
  while(!list_is_empty(pList))
  {
    for(vListMove = list_next(pList,pList), vListSmallest = pList;
      !list_is_end(pList,vListMove); list_move_next(pList,vListMove))
    {
      if(cmp_func(list_data(vListMove),list_data(vListSmallest)) < 0)
      { vListSmallest = vListMove; }
    }
    vListRes = list_append(vListRes,list_data(vListSmallest));
    pList = list_free_chunk(pList, vListSmallest);
  }
  return(vListRes);
}