/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/zigbee/mrf24j40.h File Reference
Microchip mrf24j40 IEEE 802.15.4 module routines.
#include `pic_utils.h`
*
#include `config.h`
*
#include `mrf24j40_defines.h`
*
Macros
#define MRF_FIRST_CHANNEL 11
#define MRF_LAST_CHANNEL 26
#define MRF_ACK 1
#define MRF_NO_ACK 0
#define LOC_UNDEFINED 0x00
#define LOC_UNITED_STATES 0x01
#define LOC_CANADA 0x02
#define LOC_EUROPE 0x03
Functions
void mrf24j40_flush_receive_buffer ()
Flush receive buffer of mrf24j40.
uns8 mrf24j40_short_addr_read (uns8 addr)
Read data from short address of memory location in mrf24j40.
void mrf24j40_short_addr_write (uns8 addr, uns8 data)
Write data to short address memory location.
uns8 mrf24j40_long_addr_read (uns16 addr)
Read data from long address of memory location in mrf24j40.
void mrf24j40_long_addr_write (uns16 addr, uns8 data)
Write data to long address memory location.
void mrf24j40_setup_io ()
Setup ports/pins as inputs/outputs ready for use.
void mrf24j40_init ()
Initialises mrf24j40 chip ready for use.
void mrf24j40_transmit (uns8 *data, uns8 bytes_to_transmit)
Transmit raw data.
uns8 mrf24j40_receive (uns8 *data, uns8 bytes_to_receive)
Pull received data from buffer.
void mrf24j40_set_extended_address (uns8 *_extended_address)
Set IEEE 802.15.4 extended address.
void mrf24j40_transmit_to_extended_address (uns8 frame_type, uns16 dest_pan_id, uns8 *dest_extended_address, uns8 *data, uns8 data_length, uns8 ack)
Transmit packet to extended address.
void mrf24j40_transmit_to_short_address (uns8 frame_type, uns16 dest_pan_id, uns16 dest_short_address, uns8 *data, uns8 bytes_to_transmit, uns8 ack)
Transmit packet to short address.
void mrf24j40_set_pan_id (uns16 _pan_id)
Set PAN id.
void mrf24j40_set_short_address (uns16 _short_address)
Set short address.
uns8 mrf24j40_scan_for_lowest_channel_ed ()
Scan all channels for lowest RF energy.
void mrf24j40_set_channel (uns8)
Change channels.
void mrf24j40_handle_isr ()
Interrupt service routine for mrf24j40 chip.
void mrf24j40_receive_callback ()
Callback is actioned when mrf24j40 has a packet received off air.
void mrf24j40_transmit_callback (uns8 status, uns8 retries, uns8 channel_busy)
Callback is actioned when mrf24j40 has finished transmitting a packet, or failed to do so.
Detailed Description
Microchip mrf24j40 IEEE 802.15.4 module routines.
Definition in file mrf24j40.h.
Macro Definition Documentation
#define LOC_CANADA 0x02
Module located in Canada (?? power)
Definition at line 109 of file mrf24j40.h.
#define LOC_EUROPE 0x03
Module located in Europe (-14.9dB power)
Definition at line 111 of file mrf24j40.h.
#define LOC_UNDEFINED 0x00
Module located in undefined location (full power)
Definition at line 105 of file mrf24j40.h.
#define LOC_UNITED_STATES 0x01
Module located in United States (?? power)
Definition at line 107 of file mrf24j40.h.
#define MRF_ACK 1
Send mrf packet and request acknowledgement
Definition at line 100 of file mrf24j40.h.
#define MRF_FIRST_CHANNEL 11
First available mrf channel
Definition at line 95 of file mrf24j40.h.
Referenced by mrf24j40_scan_for_lowest_channel_ed().
#define MRF_LAST_CHANNEL 26
Last availablre mrf channel
Definition at line 97 of file mrf24j40.h.
Referenced by mrf24j40_scan_for_lowest_channel_ed().
#define MRF_NO_ACK 0
Send mrf packet without acknowledgement
Definition at line 102 of file mrf24j40.h.
Function Documentation
void mrf24j40_flush_receive_buffer ()
Flush receive buffer of mrf24j40.
No need to call this routine normally, except according to mrf24j40 errata (promiscuous mode)
Definition at line 89 of file mrf24j40.c.
References mrf24j40_short_addr_read(), mrf24j40_short_addr_write(), RXFLUSH, and RXFLUSH_RXFLUSH.
Referenced by mrf24j40_receive_callback().
                                     {
    
    uns8 rxflush;
    rxflush = mrf24j40_short_addr_read(RXFLUSH); // Get rxflush
    set_bit(rxflush, RXFLUSH_RXFLUSH); // Set flush bit
    mrf24j40_short_addr_write(RXFLUSH, rxflush); // Push it back to the
       mrf
}
void mrf24j40_handle_isr ()
Interrupt service routine for mrf24j40 chip.
Call this routine when the mrf24j40 indicates an interrupt condition, or called regularly.
Definition at line 335 of file mrf24j40.c.
References INTSTAT, INTSTAT_RXIF, INTSTAT_TXNIF, mrf24j40_receive_callback(), mrf24j40_short_addr_read(), mrf24j40_transmit_callback(), TXSTAT, and TXSTAT_CCAFAIL.
                           {
uns8 intstat;
    // first we need to get a copy of intstat to find out what happened
    intstat = mrf24j40_short_addr_read(INTSTAT);
    
    // mrf24j40 intstat register is cleared on read
    if (test_bit(intstat, INTSTAT_RXIF)) {
            #ifndef __PIC32MX__
                serial_print_str("R");
                #endif
        // handle receive
        mrf24j40_receive_callback();
    }
    if (test_bit(intstat, INTSTAT_TXNIF)) {
            #ifndef __PIC32MX__
                serial_print_str("Tx complete txstat=0x");
            #endif
        uns8 stat = mrf24j40_short_addr_read(TXSTAT);
        mrf24j40_transmit_callback(stat & 0b00000001, // success = 0
                                          stat >> 6, // retries
                                          test_bit(stat, TXSTAT_CCAFAIL)); // due to cca
       failure?
            #ifndef __PIC32MX__
                serial_print_int_hex(stat);
                serial_print_nl();
                #endif
    }
}
void mrf24j40_init ()
Initialises mrf24j40 chip ready for use.
Sets int pin as input and cs pin as output.
Definition at line 586 of file mrf24j40.c.
References BBREG2, BBREG6, BBREG6_RSSIMODE2, CCAEDTH, data_sequence_number, Delayus(), mrf24j40_long_addr_read(), mrf24j40_long_addr_write(), mrf24j40_short_addr_read(), mrf24j40_short_addr_write(), MRF_INTCON, MRF_INTCON_RXIE, MRF_INTCON_TXNIE, PACON2, RFCON0, RFCON1, RFCON2, RFCON3, RFCON6, RFCON7, RFCON8, RFCTL, RFSTATE, SLPCON1, SOFTRST, TESTMODE, and TXSTBL.
Referenced by init_zigbee().
{
    uns8 check;
    
    // Example steps to initialize the MRF24J40:
    
    // 1. SOFTRST (0x2A) = 0x07
    // Perform a software Reset.
    // The bits will be automatically cleared to 0 by hardware.
    mrf24j40_short_addr_write(SOFTRST, 0x07);
    
    // Wait for soft reset to complete
    do {
        check = mrf24j40_short_addr_read(SOFTRST);
    } while (check != 0);
    
    #if defined(ENABLE_PA_LNA) && defined(MRF24J40MB)
        // Turn on PA/LNA if we have one
        mrf24j40_long_addr_write(TESTMODE, 0x0f);
    #endif
    // 2. PACON2 (0x18) = 0x98
    // Initialize FIFOEN = 1 and TXONTS = 0x6.
    mrf24j40_short_addr_write(PACON2, 0x98);
    // 3. TXSTBL (0x2E) = 0x95
    // Initialize RFSTBL = 0x9.
    mrf24j40_short_addr_write(TXSTBL, 0x95);
    
    // wait for mrf to be in receive mode
    
    do {
        check = mrf24j40_long_addr_read(RFSTATE);
    } while (check & 0xa0 != 0xa0);
    mrf24j40_long_addr_write(RFCON0, 0x03); // or three?
    // mrf24j40_long_addr_write(RFCON1, 0x02); // VCO control mode (1 or 2?)
    // miwi stack source is at odds with data sheet here
    
    // 4. RFCON1 (0x201) = 0x01 – Initialize VCOOPT = 0x01.
    mrf24j40_long_addr_write(RFCON1, 0x01);
    // 5. RFCON2 (0x202) = 0x80 – Enable PLL (PLLEN = 1).
    mrf24j40_long_addr_write(RFCON2, 0x80);
    // 6. RFCON6 (0x206) = 0x90 – Initialize TXFIL = 1 and 20MRECVR = 1.
    mrf24j40_long_addr_write(RFCON6, 0x90);
    // 7. RFCON7 (0x207) = 0x80 – Initialize SLPCLKSEL = 0x2 (100 kHz Internal oscillator).
    mrf24j40_long_addr_write(RFCON7, 0x08);
    // 8. RFCON8 (0x208) = 0x10 – Initialize RFVCO = 1.
    mrf24j40_long_addr_write(RFCON8, 0x10);
    // 9. SLPCON1 (0x220) = 0x21 – Initialize CLKOUTEN = 1 and SLPCLKDIV = 0x01.
    mrf24j40_long_addr_write(SLPCON1, 0x21);
    
    //Configuration for nonbeacon-enabled devices
    //(see Section MRF datasheet 3.8 “Beacon-Enabled and Nonbeacon-Enabled Networks”):
    //10. BBREG2 (0x3A) = 0x80 – Set CCA mode to ED.
    mrf24j40_short_addr_write(BBREG2, 0x80);
    // 11. RSSITHCCA (0x3F) = 0x60 – Set CCA ED threshold.
    // IH: I think the datasheet is wrong, the mem address is "CCAEDTH", even though
    // it's referred to as RSSITHCCA and CCAMODE in the documentation...
    
    mrf24j40_short_addr_write(CCAEDTH, 0x60);
    // 12. BBREG6 (0x3E) = 0x40 – Set appended RSSI value to RXFIFO.
    mrf24j40_short_addr_write(BBREG6, 1 <<
      BBREG6_RSSIMODE2);
    // 13. Enable interrupts – See Section 3.3 “Interrupts”.
    mrf24j40_short_addr_write(MRF_INTCON, (1 <<
      MRF_INTCON_RXIE) & (1 << MRF_INTCON_TXNIE));
    // 14. Set channel – See Section 3.4 “Channel Selection”.
    mrf24j40_long_addr_write(RFCON0, 11);
        
    #if defined(ENABLE_PA_LNA) && defined(MRF24J40MB)
    // There are special MRF24J40 transceiver output power
    // setting for Microchip MRF24J40MB module.
    // To do: Correct settings for other locations
    
        #if APPLICATION_SITE == EUROPE
            // MRF24J40 output power set to be -14.9dB
            mrf24j40_long_addr_write(RFCON3, 0x70);
        #else
            // MRF24J40 output power set to be -1.9dB - Stock setting
            // mrf24j40_long_addr_writeRFCON3, 0x18);
            // MRF24J40 output power set to be -1.2dB
            // mrf24j40_long_addr_write(RFCON3, 0x10);
            // MRF24J40 output power set to be -0.5dB
            // mrf24j40_long_addr_write(RFCON3, 0x08);
            // MRF24J40 output power set to be -0dB -> 22,5 dBm output power
            mrf24j40_long_addr_write(RFCON3, 0x00);
        #endif
    #else
        // power level to be 0dBms
        mrf24j40_long_addr_write(RFCON3,0x00);
    #endif
    // 15. RFCTL (0x36) = 0x04 – Reset RF state machine.
    mrf24j40_short_addr_write(RFCTL, 0x04);
    
    // 16. RFCTL (0x36) = 0x00.
    mrf24j40_short_addr_write(RFCTL, 0x00);
    // 17. Delay at least 192 ìs.
    #ifndef __PIC32MX__
            delay_us(200);
        #endif
        #ifdef __PIC32MX__
                Delayus(200);
        #endif
    // RXMCR.PANCOORD = 1 if coordinator, 0 is default (not coordinator)
    //mrf24j40_short_addr_write(RXMCR, 0x01); // promiscuous mode, no coord
    data_sequence_number = 0;
}
uns8 mrf24j40_long_addr_read (uns16 addr)
Read data from long address of memory location in mrf24j40.
Returns the value in the memory location specified.
Parameters
addr Long address memory location (see mrf24h40_defines.h)
Definition at line 868 of file mrf24j40.c.
References SPI_read(), and SPI_write().
Referenced by mrf24j40_init(), mrf24j40_receive(), mrf24j40_receive_callback(), and mrf24j40_scan_for_lowest_channel_ed().
                                        {
    uns8 result;
        #ifndef __PIC32MX__
            clear_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
            addr = addr & 0b0000001111111111; // <9:0> bits
            addr = addr << 5;
            set_bit(addr, 15); // long addresss
            spi_hw_transmit(addr >> 8);
            spi_hw_transmit(addr & 0x00ff);
            result = spi_hw_receive();
            set_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
        #endif
        #ifdef __PIC32MX__
            ZIGCS=0;
            addr=((addr<<1)&0x7FE)|0x800;
            addr<<=4;
            SPI_write(addr>>8);
            SPI_write(addr);
            result=SPI_read();
            ZIGCS=1;
        #endif
    return result;
}
void mrf24j40_long_addr_write (uns16 addr, uns8 data)
Write data to long address memory location.
Sets the memory location to the value specified
Parameters
addr Long address memory location (see mrf24h40_defines.h)
data Value that the memory location should be set to
Definition at line 895 of file mrf24j40.c.
References SPI_write().
Referenced by mrf24j40_init(), mrf24j40_init_coordinator(), mrf24j40_scan_for_lowest_channel_ed(), mrf24j40_set_channel(), mrf24j40_transmit(), mrf24j40_transmit_to_extended_address(), and mrf24j40_transmit_to_short_address().
                                                    {
        #ifndef __PIC32MX__
            clear_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
            addr = addr & 0b0000001111111111; // <9:0> bits
            addr = addr << 5;
            set_bit(addr, 15); // long addresss
            set_bit(addr, 4); // set for write
            spi_hw_transmit(addr >> 8);
            spi_hw_transmit(addr & 0x00ff);
            spi_hw_transmit(data);
    
            set_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
        #endif
        #ifdef __PIC32MX__
            ZIGCS=0;
            addr=((addr<<1)&0x7FF)|0x801;
            addr<<=4;
            SPI_write(addr>>8);
            SPI_write(addr);
            SPI_write(data);
            ZIGCS=1;
        #endif
}
uns8 mrf24j40_receive (uns8 * data, uns8 bytes_to_receive)
Pull received data from buffer.
Once an interrupt has occured and we know it is because a packet has been received, this routine will pull the data from the mrf receive buffer. This needs to be done quickly so that the next packet is not lost.
Definition at line 366 of file mrf24j40.c.
References BBREG1, BBREG1_RXDECINV, mrf24j40_long_addr_read(), and mrf24j40_short_addr_write().
Referenced by ZIGgets().
                                                         {
uns8 frame_length;
uns16 frame_pos;
uns8 buffer_count;
/*
1. Receive RXIF interrupt.
2. Disable host microcontroller interrupts.
3. Set RXDECINV = 1; disable receiving packets off air.
4. Read address, 0x300; get RXFIFO frame length value.
5. Read RXFIFO addresses, 0x301 through (0x300 + Frame Length + 2); read packet data plus LQI and RSSI.
6. Clear RXDECINV = 0; enable receiving packets.
7. Enable host microcontroller interrupts.
*/
        #ifndef __PIC32MX__
            serial_putc('a');
        #endif
    // Disable reading packets off air
    mrf24j40_short_addr_write(BBREG1, 1 <<
      BBREG1_RXDECINV);
        #ifndef __PIC32MX__
            serial_putc('b');
        #endif
    frame_pos = 0x300;
    frame_length = mrf24j40_long_addr_read(frame_pos++);
    buffer_count = 0;
        #ifndef __PIC32MX__
            serial_putc('c');
        #endif
    while ((buffer_count <= bytes_to_receive) && (buffer_count <= frame_length + 2)) {
        //0x301 through (0x300 + Frame Length + 2); read packet data plus LQI and RSSI.
        data[buffer_count++] = mrf24j40_long_addr_read(frame_pos++);
    }
        #ifndef __PIC32MX__
            serial_putc('d');
        #endif
    // Re-enable reading packets off air
    mrf24j40_short_addr_write(BBREG1, 0);
        #ifndef __PIC32MX__
            serial_putc('e');
        #endif
    return buffer_count - 1;
    
}
void mrf24j40_receive_callback ()
Callback is actioned when mrf24j40 has a packet received off air.
Callback indicating the mrf24j40 has a packet ready.
Definition at line 67 of file __zigbee.c.
References mrf24j40_flush_receive_buffer(), mrf24j40_long_addr_read(), and ZIGrx.
Referenced by mrf24j40_handle_isr().
{
    unsigned char length,i,character;
    unsigned char znewwp;
    unsigned char data[128];
        length=mrf24j40_long_addr_read(0x300);
        for (i=0;i<length;i++)
            ZIGrx[i]=mrf24j40_long_addr_read(0x301+i);
        mrf24j40_flush_receive_buffer();
/*
    length=mrf24j40_receive(data, 128);
    if (length>0)
        for (i=0;i<length;i++)
            {
                    if (zwpointer!=127) // if not last place in buffer
                        znewwp=zwpointer+1; // place=place+1
                    else
                        znewwp=1; // else place=1
                    if (zrpointer!=znewwp) // if read pointer!=write pointer
                        ZIGrx[zwpointer++]=data[i]; // store received char
                    if (zwpointer==128) // if write pointer=length buffer
                        zwpointer=1; // write pointer = 1
            }
*/
}
uns8 mrf24j40_scan_for_lowest_channel_ed ()
Scan all channels for lowest RF energy.
Scans through all channels and reports the channel with the lowest Energy Detection level.
Definition at line 119 of file mrf24j40.c.
References BBREG6, BBREG6_RSSIMODE1, BBREG6_RSSIMODE2, BBREG6_RSSIRDY, GPIO, mrf24j40_long_addr_read(), mrf24j40_long_addr_write(), mrf24j40_set_channel(), mrf24j40_short_addr_read(), mrf24j40_short_addr_write(), MRF_FIRST_CHANNEL, MRF_LAST_CHANNEL, RSSI, TESTMODE, and TRISGPIO.
                                           {
uns8 rssi;
uns8 _channel;
uns16 scan_count;
uns8 highest_on_channel;
uns8 lowest_channel = MRF_LAST_CHANNEL;
uns8 lowest_ed = 0xff;
uns8 bbreg6;
    // We should really ignore all packets here (do to)
    
    #if defined(ENABLE_PA_LNA)
        mrf24j40_long_addr_write(TESTMODE, 0x08); // Disable
       automatic switch on PA/LNA
        mrf24j40_short_addr_write(TRISGPIO, 0x0F); // Set GPIO
       direction
        mrf24j40_short_addr_write(GPIO, 0x0C); // Enable LNA
    #endif
    
    for (_channel = MRF_FIRST_CHANNEL; _channel <=
      MRF_LAST_CHANNEL; _channel++) {
        
        // switch channel
        mrf24j40_set_channel(_channel);
        
        highest_on_channel = 0;
        for (scan_count = 0; scan_count < 1000; scan_count++) {
            mrf24j40_short_addr_write(BBREG6, 1 <<
      BBREG6_RSSIMODE1);
            do {
                bbreg6 = mrf24j40_short_addr_read(BBREG6);
            } while (!test_bit(bbreg6, BBREG6_RSSIRDY));
            rssi = mrf24j40_long_addr_read(RSSI);
            if (rssi > highest_on_channel) {
                highest_on_channel = rssi;
            }
        }
        
        if (highest_on_channel < lowest_ed) {
            lowest_ed = highest_on_channel;
            lowest_channel = _channel;
        }
    }
    mrf24j40_short_addr_write(BBREG6, 1 <<
      BBREG6_RSSIMODE2); // Back to mode 2 (rssi in pkt)
    
    // Should stop ignoring all packets now if we started ignoring them earlier
    // (to do)
    
    #if defined(ENABLE_PA_LNA)
        mrf24j40_short_addr_write(GPIO, 0);
        mrf24j40_short_addr_write(TRISGPIO, 0x00);
        mrf24j40_long_addr_write(TESTMODE, 0x0F);
    #endif
    
    return lowest_channel;
}
void mrf24j40_set_channel (uns8)
Change channels.
Change to the specified channel, in the range MRF_FIRST_CHANNEL to MRF_LAST_CHANNEL.
Parameters
channel Channel to change to.
Definition at line 100 of file mrf24j40.c.
References current_channel, Delayus(), mrf24j40_long_addr_write(), mrf24j40_short_addr_write(), RFCON0, and RFCTL.
Referenced by init_zigbee(), and mrf24j40_scan_for_lowest_channel_ed().
{
    current_channel = _channel;
    _channel = _channel - 11;
    _channel = 0x02 + 0x10 * _channel;
    
    mrf24j40_long_addr_write(RFCON0, _channel); // Set channel
    mrf24j40_short_addr_write(RFCTL, 0x04); // RFCTL (0x36) = 0x04 – Reset
       RF state machine.
    mrf24j40_short_addr_write(RFCTL, 0x00); // RFCTL (0x36) = 0x00
        
    #ifndef __PIC32MX__
            delay_us(200); // Delay at least 192us
    #endif
    #ifdef __PIC32MX__
            Delayus(200);
    #endif
}
void mrf24j40_set_extended_address (uns8 * _extended_address)
Set IEEE 802.15.4 extended address.
Set extended address.
Pass a pointer to an 8 byte uns8 array with the address embedded as MSB leftmost byte and LSB rightmost byte, eg
uns8 EA_3[8] = { 0, 0, 0, 0, 0, 0, 0, 3 };
Set extended address to 0x0000000000000003 (64 bit address) mrf24j40_set_extended_address(&EA_3);
Sets the 64 bit extended address of the module. Pass a pointer to an 8 byte uns8 array containing the address.
Set IEEE 802.15.4 extended address.
Sets the 64 bit extended address of the module. Pass a pointer to an 8 byte uns8 array containing the address.
Definition at line 303 of file mrf24j40.c.
References EADR7, extended_address, and mrf24j40_short_addr_write().
                                                            {
    uns8 count;
    uns8 mem_pos = EADR7;
    #ifndef __PIC32MX__
            serial_print_str("Setting EA to: ");
    #endif
    for (count = 0; count < 8; count++) {
        extended_address[count] = _extended_address[count];
        mrf24j40_short_addr_write(mem_pos--,
      extended_address[count]);
        #ifndef __PIC32MX__
                serial_print_int_hex(extended_address[count]);
                serial_putc(' ');
        #endif
    }
    #ifndef __PIC32MX__
            serial_print_nl();
    #endif
}
void mrf24j40_set_pan_id (uns16 _pan_id)
Set PAN id.
Sets the 16 bit PAN id of the module.
Definition at line 296 of file mrf24j40.c.
References mrf24j40_short_addr_write(), pan_id, PANIDH, and PANIDL.
Referenced by init_zigbee().
{
    pan_id = _pan_id;
    mrf24j40_short_addr_write(PANIDL, pan_id & 0xff);
    mrf24j40_short_addr_write(PANIDH, pan_id >> 8);
}
void mrf24j40_set_short_address (uns16 _short_address)
Set short address.
Sets the 16 bit short address of the module.
Definition at line 322 of file mrf24j40.c.
References mrf24j40_short_addr_write(), SADRH, SADRL, and short_address.
Referenced by init_zigbee().
{
    // Keep hold of the short address
    short_address = _short_address;
    
    // Tell the mrf about it
    mrf24j40_short_addr_write(SADRL, short_address & 0xff);
    mrf24j40_short_addr_write(SADRH, short_address >> 8);
}
void mrf24j40_setup_io ()
Setup ports/pins as inputs/outputs ready for use.
Sets int pin as input and cs pin as output.
Definition at line 924 of file mrf24j40.c.
References Delayms(), and SPI_init().
Referenced by init_zigbee().
                         {
        #ifndef __PIC32MX__
            make_input(mrf24j40_int_port, mrf24j40_int_pin);
            set_pin(mrf24j40_cs_port, mrf24j40_cs_pin); // keep high
            make_output(mrf24j40_cs_port, mrf24j40_cs_pin);
        #endif
        #ifdef __PIC32MX__
            SPI_init(); // init SPI default (2 on PIC32-PINGUINO)
                                // only called here for test
                                // will be called later in main32.c
            #ifndef PIC32_PINGUINO_220
                //pinmode(13,OUTPUT); // CLK
                //pinmode(11,OUTPUT); // SDO
                //pinmode(12,INPUT); // SDI
                ZIGRESETOUT; // macro for RESET
                ZIGCSOUT; // macro for CS
                ZIGINTIN; // interrupt (not yet implemented)
            #else
                ZIGRESETOUT; // macro for RESET
                ZIGCSOUT; // macro for CS
            #endif
            ZIGRESET=0;
            ZIGCS=1;
            ZIGRESET=1;
            Delayms(100);
        #endif
}
uns8 mrf24j40_short_addr_read (uns8 addr)
Read data from short address of memory location in mrf24j40.
Returns the value in the memory location specified.
Parameters
addr Short address memory location (see mrf24h40_defines.h)
Definition at line 826 of file mrf24j40.c.
References SPI_read(), and SPI_write().
Referenced by mrf24j40_flush_receive_buffer(), mrf24j40_handle_isr(), mrf24j40_init(), mrf24j40_init_coordinator(), mrf24j40_scan_for_lowest_channel_ed(), mrf24j40_transmit(), mrf24j40_transmit_to_extended_address(), mrf24j40_transmit_to_short_address(), and ZIGgets().
{
        #ifndef __PIC32MX__
            clear_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
            addr = addr & 0b00111111; // <5:0> bits
            addr = addr << 1; // LSB = 0, means read
            spi_hw_transmit(addr);
            uns8 result = spi_hw_receive();
            set_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
        #endif
        #ifdef __PIC32MX__
            addr = (addr << 1) & 0x7E;
            ZIGCS=0; // CS must be held low while communicationg with MRF24J40
            SPI_write(addr);
            u8 result = SPI_read();
            ZIGCS=1; // end of communication
        #endif
    return result;
}
void mrf24j40_short_addr_write (uns8 addr, uns8 data)
Write data to short address memory location.
Sets the memory location to the value specified
Parameters
addr Short address memory location (see mrf24h40_defines.h)
data Value that the memory location should be set to
Definition at line 846 of file mrf24j40.c.
References SPI_write().
Referenced by mrf24j40_flush_receive_buffer(), mrf24j40_init(), mrf24j40_init_coordinator(), mrf24j40_receive(), mrf24j40_scan_for_lowest_channel_ed(), mrf24j40_set_channel(), mrf24j40_set_extended_address(), mrf24j40_set_pan_id(), mrf24j40_set_short_address(), mrf24j40_transmit(), mrf24j40_transmit_to_extended_address(), and mrf24j40_transmit_to_short_address().
{
        #ifndef __PIC32MX__
            clear_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
            addr = addr & 0b00111111; // <5:0> bits
            addr = addr << 1; // LSB = 0, means read
            set_bit(addr, 0); // write
            spi_hw_transmit(addr);
            spi_hw_transmit(data);
            set_pin(mrf24j40_cs_port, mrf24j40_cs_pin);
        #endif
        #ifdef __PIC32MX__
            addr=((addr<<1)&0x7F)|1;
            ZIGCS=0;
            SPI_write(addr);
            SPI_write(data);
            ZIGCS=1;
        #endif
}
void mrf24j40_transmit (uns8 * data, uns8 bytes_to_transmit)
Transmit raw data.
Transmit a raw packet - this assumes you have already created an 802.15.4 compatible packet. Normally you would use transmit_to_extended_adddress or transmit_to_short_address instead.
Definition at line 549 of file mrf24j40.c.
References data_sequence_number, mrf24j40_long_addr_write(), mrf24j40_short_addr_read(), mrf24j40_short_addr_write(), TXNCON, and TXNCON_TXNTRIG.
                                                           {
    
    uns8 fc_lsb = 0b01000001;
    uns8 fc_msb = 0b00000000;
        #ifdef __PIC32MX__
                u8 count=0;
        #endif
    
    data_sequence_number++;
    uns8 header_length = 3; // Just two bytes of frame control + sequence number, no addrs
    uns8 frame_length = header_length + bytes_to_transmit;
    
    mrf24j40_long_addr_write(0x00, header_length);
    mrf24j40_long_addr_write(0x01, frame_length);
    mrf24j40_long_addr_write(0x02, fc_lsb);
    mrf24j40_long_addr_write(0x03, fc_msb);
    mrf24j40_long_addr_write(0x04, data_sequence_number);
    
    #ifndef __PIC32MX__
            for (uns8 count=0; count < bytes_to_transmit; count++) { // check format here
                mrf24j40_long_addr_write(count+header_length+2, data[count]);
        #endif
        #ifdef __PIC32MX__
            for (count=0; count < bytes_to_transmit; count++) { // check format here
                mrf24j40_long_addr_write(count+header_length+2, data[count]);
        #endif
    }
    
    uns8 txncon = mrf24j40_short_addr_read(TXNCON);
    set_bit(txncon, TXNCON_TXNTRIG);
    mrf24j40_short_addr_write(TXNCON, txncon);
}
void mrf24j40_transmit_callback (uns8 status, uns8 retries, uns8 channel_busy)
Callback is actioned when mrf24j40 has finished transmitting a packet, or failed to do so.
Callback indicating the mrf24j40 has finished the transmission sequence.
Parameters
status Set to 0 for success or 1 for failure
retries Set to the number of retries
channel_busy Set to 1 if failure was due to the channel being busy.
Definition at line 60 of file __zigbee.c.
Referenced by mrf24j40_handle_isr().
{
    Nop();
}
void mrf24j40_transmit_to_extended_address (uns8 frame_type, uns16 dest_pan_id, uns8 * dest_extended_address, uns8 * data, uns8 data_length, uns8 ack)
Transmit packet to extended address.
Requests that the mrf24j40 transmit the packet to the specified extended address
Parameters
frame_type 802.15.4 frame type
dest_pan_id PAN id of destination
dest_extended_address Pointer to uns8 array indicating extended address of destination
data Pointer to uns8 array of bytes to transmit
bytes_to_transmit
ack Either MRF_ACK or MRF_NO_ACK depending if you want hardware acknowledgement
Definition at line 414 of file mrf24j40.c.
References data_sequence_number, extended_address, mrf24j40_long_addr_write(), mrf24j40_short_addr_read(), mrf24j40_short_addr_write(), pan_id, TXNCON, TXNCON_TXNACKREQ, and TXNCON_TXNTRIG.
                                                                                   {
    
    // See notes below on frame control bytes format:
    uns8 fc_msb = 0b11001100; // 64 bit dest (10,11) 64 bit src (14,15)
    uns8 fc_lsb = 0b00000000 | frame_type; // pan id compression=0, data
        #ifdef __PIC32MX__
                u8 count=0;
        #endif
    if (ack) {
        set_bit(fc_lsb, 5); // ack bit
    }
    
    data_sequence_number++;
    
    uns8 header_length = 3+8+8+2+2;
    uns8 frame_length = header_length + data_length;
    
    // Write out data to mrf
        
    mrf24j40_long_addr_write(0x00, header_length);
    mrf24j40_long_addr_write(0x01, frame_length);
    
    mrf24j40_long_addr_write(0x02, fc_lsb);
    mrf24j40_long_addr_write(0x03, fc_msb);
    mrf24j40_long_addr_write(0x04, data_sequence_number);
    
    mrf24j40_long_addr_write(0x05, dest_pan_id & 0xff); // dest pan id LSB
    mrf24j40_long_addr_write(0x06, dest_pan_id >> 8); // MSB
    mrf24j40_long_addr_write(0x07, dest_extended_address[7]); // LSB
    mrf24j40_long_addr_write(0x08, dest_extended_address[6]);
    mrf24j40_long_addr_write(0x09, dest_extended_address[5]);
    mrf24j40_long_addr_write(0x0a, dest_extended_address[4]);
    mrf24j40_long_addr_write(0x0b, dest_extended_address[3]);
    mrf24j40_long_addr_write(0x0c, dest_extended_address[2]);
    mrf24j40_long_addr_write(0x0d, dest_extended_address[1]);
    mrf24j40_long_addr_write(0x0e, dest_extended_address[0]); // MSB
    
    mrf24j40_long_addr_write(0x0f, pan_id & 0xff); // src pan id LSB
    mrf24j40_long_addr_write(0x10, pan_id >> 8); // MSB
    
    mrf24j40_long_addr_write(0x11, extended_address[7]); // LSB
    mrf24j40_long_addr_write(0x12, extended_address[6]);
    mrf24j40_long_addr_write(0x13, extended_address[5]);
    mrf24j40_long_addr_write(0x14, extended_address[4]);
    mrf24j40_long_addr_write(0x15, extended_address[3]);
    mrf24j40_long_addr_write(0x16, extended_address[2]);
    mrf24j40_long_addr_write(0x17, extended_address[1]);
    mrf24j40_long_addr_write(0x18, extended_address[0]); // MSB
    #ifndef __PIC32MX__
            for (uns8 count=0; count < data_length; count++) {
                mrf24j40_long_addr_write(count+header_length+2, data[count]);
        #endif
        #ifdef __PIC32MX__
            for (count=0; count < data_length; count++) {
                mrf24j40_long_addr_write(count+header_length+2, data[count]);
        #endif
    }
    
    uns8 txncon = mrf24j40_short_addr_read(TXNCON);
    
    set_bit(txncon, TXNCON_TXNTRIG);
    if (ack) {
        set_bit(txncon, TXNCON_TXNACKREQ);
    }
    mrf24j40_short_addr_write(TXNCON, txncon);
    
}
void mrf24j40_transmit_to_short_address (uns8 frame_type, uns16 dest_pan_id, uns16 dest_short_address, uns8 * data, uns8 bytes_to_transmit, uns8 ack)
Transmit packet to short address.
Requests that the mrf24j40 transmit the packet to the specified short address
Parameters
frame_type 802.15.4 frame type
dest_pan_id PAN id of destination
dest_short_address 16 bit short address of destination
data Pointer to uns8 array of bytes to transmit
bytes_to_transmit
ack Either MRF_ACK or MRF_NO_ACK depending if you want hardware acknowledgement
Definition at line 488 of file mrf24j40.c.
References data_sequence_number, mrf24j40_long_addr_write(), mrf24j40_short_addr_read(), mrf24j40_short_addr_write(), pan_id, short_address, TXNCON, TXNCON_TXNACKREQ, and TXNCON_TXNTRIG.
Referenced by ZIGputs().
                                                                                                           
                                               {
    
    uns8 fc_msb = 0b10001000; // short dest (10,11) short src (14,15)
    uns8 fc_lsb = 0b00000000 | frame_type; // data, pan id compression (only have dest pan id)
        #ifdef __PIC32MX__
                u8 count=0;
        #endif
    // To do:
    // Not smart enough for this yet:
    //if (dest_pan_id == pan_id) {
    // set_bit(fc_lsb, 6); // pan compression
    //}
    if (ack) {
        set_bit(fc_lsb, 5); // ack bit
    }
    
    data_sequence_number++;
    
    uns8 header_length = 3+2+2+2+2;
    uns8 frame_length = header_length + bytes_to_transmit;
        
    mrf24j40_long_addr_write(0x00, header_length);
    mrf24j40_long_addr_write(0x01, frame_length);
    
    mrf24j40_long_addr_write(0x02, fc_lsb);
    mrf24j40_long_addr_write(0x03, fc_msb);
    mrf24j40_long_addr_write(0x04, data_sequence_number);
    
    mrf24j40_long_addr_write(0x05, dest_pan_id & 0xff); // dest pan id LSB
    mrf24j40_long_addr_write(0x06, dest_pan_id >> 8); // MSB
    
    mrf24j40_long_addr_write(0x07, dest_short_address & 0xff); // LSB
    mrf24j40_long_addr_write(0x08, dest_short_address >> 8); // MSB
    mrf24j40_long_addr_write(0x09, pan_id & 0xff); // src pan id (=ours)
       LSB
    mrf24j40_long_addr_write(0x0a, pan_id >> 8); // MSB
    
    mrf24j40_long_addr_write(0x0b, short_address & 0xff); // LSB
    mrf24j40_long_addr_write(0x0c, short_address >> 8);
        #ifndef __PIC32MX__
    for (uns8 count=0; count < bytes_to_transmit; count++) { // check format here
    #endif
    #ifdef __PIC32MX__
    for (count=0; count < bytes_to_transmit; count++) {
    #endif
        mrf24j40_long_addr_write(count+header_length+2, data[count]);
    }
    
    uns8 txncon = mrf24j40_short_addr_read(TXNCON);
    set_bit(txncon, TXNCON_TXNTRIG);
    if (ack) {
        set_bit(txncon, TXNCON_TXNACKREQ);
    }
    mrf24j40_short_addr_write(TXNCON, txncon);
    
}