/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/oscillator.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
Macros
#define __OSCILLATOR_C
#define CRYSTAL 8000000L
#define System_setExtOsc() do { OSCCONbits.SCS = 0b00; } while (0)
#define System_setTimer1Osc() do { OSCCONbits.SCS = 0b01; } while (0)
#define SystemGetInstructionClock() System_getPeripheralFrequency()
Functions
u32 System_getCpuFrequency ()
u32 System_getPeripheralFrequency ()
Variables
u32 _cpu_clock_
Macro Definition Documentation
#define __OSCILLATOR_C
Definition at line 30 of file oscillator.c.
#define CRYSTAL 8000000L
Definition at line 39 of file oscillator.c.
Referenced by System_getCpuFrequency().
#define System_setExtOsc() do { OSCCONbits.SCS = 0b00; } while (0)
Definition at line 115 of file oscillator.c.
#define System_setTimer1Osc() do { OSCCONbits.SCS = 0b01; } while (0)
Definition at line 121 of file oscillator.c.
#define SystemGetInstructionClock() System_getPeripheralFrequency()
Definition at line 251 of file oscillator.c.
Function Documentation
u32 System_getCpuFrequency ()
Definition at line 161 of file oscillator.c.
References CRYSTAL.
Referenced by Serial_begin(), and System_getPeripheralFrequency().
{
    u8 CPUDIV;
    #if defined(__18f2455) || defined(__18f4455) || \
        defined(__18f2550) || defined(__18f4550)
    u8 fosc, CPUDIV_XTAL;
    #endif
    switch (OSCCONbits.SCS)
    {
        case 0: // primary osc. (internal or external / CPUDIV)
            #if defined(__18f25k50) || defined(__18f45k50)
            if (OSCCON2bits.PLLEN)
            {
                return 48000000L;
            }
            else
            {
                return CRYSTAL;
            }
            
            #endif
            // CPUDIV ?
            
            #if defined(__18f2455) || defined(__18f4455) || \
                defined(__18f2550) || defined(__18f4550)
            CPUDIV = (System_readFlashMemory(__CONFIG1L) & 0b00011000) >> 3;
            CPUDIV_XTAL = cpudiv_xtal[CPUDIV];
            fosc = System_readFlashMemory(__CONFIG1H) & 0b00001111;
            #else // xxJ5x
            CPUDIV = System_readFlashMemory(__CONFIG1H) & 0b00000011;
            #endif
            CPUDIV = cpudiv[CPUDIV];
            
            // PLL ?
            
            #if defined(__18f2455) || defined(__18f4455) || \
                defined(__18f2550) || defined(__18f4550)
            fosc >>=1;
            if((fosc==0) || (fosc==2) || (fosc==6))
            {
                return CRYSTAL / CPUDIV_XTAL;
            }
            else
            {
                return 96000000UL / CPUDIV;
            }
            
            #elif defined(__18f26j50) || defined(__18f46j50) || \
                  defined(__18f26j53) || defined(__18f46j53) || \
                  defined(__18f27j53) || defined(__18f47j53)
            if (OSCTUNEbits.PLLEN)
            {
                return 48000000UL / CPUDIV;
            }
            else
            {
                return CRYSTAL / CPUDIV;
            }
            
            #endif
        case 1: // secondary osc. (timer 1, most of the time 32768 Hz)
            return 32768;
            
        case 2: // reserved or postscaled internal clock
        case 3: // postscaled internal clock (IRCF)
            return ircf[OSCCONbits.IRCF];
    }
}
u32 System_getPeripheralFrequency ()
Definition at line 253 of file oscillator.c.
References System_getCpuFrequency().
Referenced by millis_init(), PWM_setFrequency(), Stepper_setSpeed(), and updateMillisReloadValue().
{
    return System_getCpuFrequency() >> 2;
}
Variable Documentation
u32 _cpu_clock_
Definition at line 42 of file oscillator.c.