/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/output.c File Reference
#include <serial.c>
*
#include <string.h>
*
Macros
#define __OUTPUT_C__
#define SERIAL 1
#define SERIAL1 1
#define SERIAL2 2
Functions
int * sbrk (int nbbytes)
int open (const char *name, int flags, int mode)
int close (int file)
int fstat (int file, void *st)
int isatty (int file)
int lseek (int file, int ptr, int dir)
int read (int file, char *ptr, int len)
int write (char file, char *ptr, int len)
Variables
int * heap_ptr
int _heap
Macro Definition Documentation
#define __OUTPUT_C__
Definition at line 25 of file output.c.
#define SERIAL 1
Definition at line 27 of file output.c.
#define SERIAL1 1
Definition at line 28 of file output.c.
#define SERIAL2 2
Definition at line 29 of file output.c.
Function Documentation
int close (int file)
Definition at line 84 of file output.c.
{
    return -1;
    // TODO clear interrupt for some stream
}
int fstat (int file, void * st)
Definition at line 99 of file output.c.
{
    return 0;
}
int isatty (int file)
Definition at line 109 of file output.c.
{
    return 1;
}
int lseek (int file, int ptr, int dir)
Definition at line 119 of file output.c.
{
    return 0;
}
int open (const char * name, int flags, int mode)
Definition at line 60 of file output.c.
References SerialConfigure(), UART1, UART2, UART_ENABLE, and UART_RX_TX_ENABLED.
{
    if (!strcmp(name,"SERIAL1"))
    {
        SerialConfigure(UART1, UART_ENABLE,
      UART_RX_TX_ENABLED, 9600);
        return(1);
    }
    if (!strcmp(name,"SERIAL2"))
    {
        SerialConfigure(UART2, UART_ENABLE,
      UART_RX_TX_ENABLED, 9600);
        return(2);
    }
    
// TODO LCD, SPI etc.....
// TODO define a flag to know if the stream is opened
    
    return -1;
}
int read (int file, char * ptr, int len)
Definition at line 129 of file output.c.
References SerialRead(), and UART1.
Referenced by I2C_requestFrom().
{
    int caractere=0;
    int nbchar=0;
    
    switch (file)
    {
        case 0:
            while (caractere!=-1) // stdin
            {
                caractere=SerialRead(UART1);
                if (caractere!=-1)
                {
                    *ptr++=caractere;
                    nbchar++;
                }
            }
            if (nbchar!=0)
                return(nbchar);
            else
                return(-1);
            break;
    }
    return -1;
}
int* sbrk (int nbbytes)
Definition at line 44 of file output.c.
References _heap, and heap_ptr.
{
    int *base;
    
    if (!heap_ptr)
        heap_ptr=(int *)&_heap; // _heap is defined in the linker script
    base=heap_ptr; // on Pinguino32 heap is 8192 bytes
    heap_ptr += nbbytes;
    return base;
}
int write (char file, char * ptr, int len)
Definition at line 161 of file output.c.
References SerialUART1WriteChar(), and SerialUART2WriteChar().
{
    int todo;
    switch (file)
    {
        case 1:
            for (todo = 0; todo < len; todo++)
                SerialUART1WriteChar(*ptr++); // stdout
            return len;
            break;
        case 2:
            for (todo = 0; todo < len; todo++)
                SerialUART2WriteChar(*ptr++); // stdout
            return len;
            break;
        default:
            return(-1);
            break;
    }
    
    return -1;
}
Variable Documentation
int _heap
Referenced by sbrk().
int* heap_ptr
Definition at line 41 of file output.c.
Referenced by sbrk().