/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/rtcc.c File Reference
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <system.c>
*
#include <interrupt.c>
*
#include <bcd.c>
*
Data Structures
union rtccTime
union rtccDate
Macros
#define __RTCC__
#define RTCC_ALARM_EVERY_HALF_SECOND 0b0000
#define RTCC_ALARM_EVERY_SECOND 0b0001
#define RTCC_ALARM_EVERY_TEN_SECONDS 0b0010
#define RTCC_ALARM_EVERY_MINUTE 0b0011
#define RTCC_ALARM_EVERY_TEN_MINUTES 0b0100
#define RTCC_ALARM_EVERY_HOUR 0b0101
#define RTCC_ALARM_EVERY_DAY 0b0110
#define RTCC_ALARM_EVERY_WEEK 0b0111
#define RTCC_ALARM_EVERY_MONTH 0b1000
#define RTCC_ALARM_EVERY_YEAR 0b1001
Typedefs
typedef void(* callback)(void)
Enumerations
enum rtccRes {
*
RTCC_SOSC_ON,
RTCC_SOSC_NRDY,
RTCC_CLK_NRDY,
RTCC_WR_DSBL,
*
RTCC_SOSC_ON,
RTCC_SOSC_NRDY,
RTCC_CLK_NRDY,
RTCC_WR_DSBL
 }
Functions
rtccTime RTCC_ConvertTime (rtccTime *)
rtccDate RTCC_ConvertDate (rtccDate *)
void RTCC_SetWriteEnable (void)
void RTCC_SetWriteDisable (void)
int RTCC_GetWriteEnable (void)
void RTCC_Enable (void)
void RTCC_Disable (void)
int RTCC_GetEnable (void)
rtccRes RTCC_GetSOSCstatus (void)
void RTCC_SOSCenable (void)
void RTCC_SOSCdisable (void)
void RTCC_SetTime (unsigned long)
rtccTime RTCC_GetTime (void)
void RTCC_SetDate (unsigned long)
rtccDate RTCC_GetDate (void)
void RTCC_SetTimeDate (unsigned long, unsigned long)
void RTCC_GetTimeDate (rtccTime *, rtccDate *)
void RTCC_SetCalibration (int)
int RTCC_GetCalibration (void)
void RTCC_SetAlarmEnable (int)
void RTCC_AlarmEnable (void)
void RTCC_AlarmDisable (void)
int RTCC_GetAlarmEnable (void)
void RTCC_SetChimeEnable (int)
void RTCC_ChimeEnable (void)
void RTCC_ChimeDisable (void)
int RTCC_GetChimeEnable (void)
void RTCC_SetAlarmRepeat (int)
void RTCC_AlarmEveryHalfSecond (void)
void RTCC_AlarmEverySecond (void)
void RTCC_AlarmEveryTenSeconds (void)
void RTCC_AlarmEveryMinute (void)
void RTCC_AlarmEveryTenMinutes (void)
void RTCC_AlarmEveryHour (void)
void RTCC_AlarmEveryDay (void)
void RTCC_AlarmEveryWeek (void)
void RTCC_AlarmEveryMonth (void)
void RTCC_AlarmEveryYear (void)
int RTCC_GetAlarmRepeat (void)
void RTCC_SetAlarmRepeatCount (char)
char RTCC_GetAlarmRepeatCount (void)
void RTCC_SetAlarmTime (unsigned long)
rtccTime RTCC_GetAlarmTime (void)
void RTCC_SetAlarmDate (unsigned long)
rtccDate RTCC_GetAlarmDate (void)
void RTCC_SetAlarmTimeDate (unsigned long, unsigned long)
void RTCC_GetAlarmTimeDate (rtccTime *, rtccDate *)
void RTCC_SetSync (int)
int RTCC_GetSync (void)
void RTCC_SetAlarmSync (int)
int RTCC_GetAlarmSync (void)
int RTCC_GetHalfSecond (void)
void RTCC_SecondsPulseOutput (void)
void RTCC_AlarmPulseOutput (void)
void RTCC_SetAlarmInitialPulse (int)
void RTCC_AlarmInitialPulseHigh (void)
void RTCC_AlarmInitialPulseLow (void)
int RTCC_GetAlarmInitialPulse (void)
void RTCC_AlarmInitialPulseToggle (void)
void RTCC_SetOutputEnable (int)
void RTCC_OutputEnable (void)
void RTCC_OutputDisable (void)
int RTCC_GetOutputEnable (void)
void RTCC_SetAlarmIntEnable (int)
void RTCC_AlarmIntEnable (void)
void RTCC_AlarmIntDisable (void)
void OnRTCC (callback)
void RTCCInterrupt (void)
void RTCC_init (void)
void RTCC_Shutdown (void)
rtccRes RTCC_Open (unsigned long, unsigned long, int)
Macro Definition Documentation
#define __RTCC__
Definition at line 27 of file rtcc.c.
#define RTCC_ALARM_EVERY_DAY 0b0110
Definition at line 87 of file rtcc.c.
Referenced by RTCC_AlarmEveryDay().
#define RTCC_ALARM_EVERY_HALF_SECOND 0b0000
Definition at line 81 of file rtcc.c.
Referenced by RTCC_AlarmEveryHalfSecond().
#define RTCC_ALARM_EVERY_HOUR 0b0101
Definition at line 86 of file rtcc.c.
Referenced by RTCC_AlarmEveryHour().
#define RTCC_ALARM_EVERY_MINUTE 0b0011
Definition at line 84 of file rtcc.c.
Referenced by RTCC_AlarmEveryMinute().
#define RTCC_ALARM_EVERY_MONTH 0b1000
Definition at line 89 of file rtcc.c.
Referenced by RTCC_AlarmEveryMonth().
#define RTCC_ALARM_EVERY_SECOND 0b0001
Definition at line 82 of file rtcc.c.
Referenced by RTCC_AlarmEverySecond().
#define RTCC_ALARM_EVERY_TEN_MINUTES 0b0100
Definition at line 85 of file rtcc.c.
Referenced by RTCC_AlarmEveryTenMinutes().
#define RTCC_ALARM_EVERY_TEN_SECONDS 0b0010
Definition at line 83 of file rtcc.c.
Referenced by RTCC_AlarmEveryTenSeconds().
#define RTCC_ALARM_EVERY_WEEK 0b0111
Definition at line 88 of file rtcc.c.
Referenced by RTCC_AlarmEveryWeek().
#define RTCC_ALARM_EVERY_YEAR 0b1001
Definition at line 90 of file rtcc.c.
Referenced by RTCC_AlarmEveryYear().
Typedef Documentation
typedef void(* callback)(void)
Definition at line 38 of file rtcc.c.
Enumeration Type Documentation
enum rtccRes
Enumerator
RTCC_SOSC_ON
RTCC_SOSC_NRDY
RTCC_CLK_NRDY
RTCC_WR_DSBL
RTCC_SOSC_ON
RTCC_SOSC_NRDY
RTCC_CLK_NRDY
RTCC_WR_DSBL
Definition at line 72 of file rtcc.c.
{
    RTCC_SOSC_ON, // success, SOSC is running
    RTCC_SOSC_NRDY, // SOSC not running
    RTCC_CLK_NRDY, // RTCC clock not running
    RTCC_WR_DSBL, // WR is disabled
}rtccRes;
Function Documentation
void OnRTCC (callback userfunc)
Definition at line 909 of file rtcc.c.
{
    intFunction = userfunc;
}
void RTCC_AlarmDisable (void)
Definition at line 514 of file rtcc.c.
References False, and RTCC_SetAlarmEnable().
Referenced by RTCC_init(), RTCC_Open(), and RTCC_Shutdown().
{
    RTCC_SetAlarmEnable(False);
}
void RTCC_AlarmEnable (void)
Definition at line 509 of file rtcc.c.
References RTCC_SetAlarmEnable(), and True.
{
    RTCC_SetAlarmEnable(True);
}
void RTCC_AlarmEveryDay (void)
Definition at line 605 of file rtcc.c.
References RTCC_ALARM_EVERY_DAY, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_DAY);
}
void RTCC_AlarmEveryHalfSecond (void)
Definition at line 581 of file rtcc.c.
References RTCC_ALARM_EVERY_HALF_SECOND, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_HALF_SECOND);
}
void RTCC_AlarmEveryHour (void)
Definition at line 601 of file rtcc.c.
References RTCC_ALARM_EVERY_HOUR, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_HOUR);
}
void RTCC_AlarmEveryMinute (void)
Definition at line 593 of file rtcc.c.
References RTCC_ALARM_EVERY_MINUTE, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_MINUTE);
}
void RTCC_AlarmEveryMonth (void)
Definition at line 613 of file rtcc.c.
References RTCC_ALARM_EVERY_MONTH, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_MONTH);
}
void RTCC_AlarmEverySecond (void)
Definition at line 585 of file rtcc.c.
References RTCC_ALARM_EVERY_SECOND, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_SECOND);
}
void RTCC_AlarmEveryTenMinutes (void)
Definition at line 597 of file rtcc.c.
References RTCC_ALARM_EVERY_TEN_MINUTES, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_TEN_MINUTES);
}
void RTCC_AlarmEveryTenSeconds (void)
Definition at line 589 of file rtcc.c.
References RTCC_ALARM_EVERY_TEN_SECONDS, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_TEN_SECONDS);
}
void RTCC_AlarmEveryWeek (void)
Definition at line 609 of file rtcc.c.
References RTCC_ALARM_EVERY_WEEK, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_WEEK);
}
void RTCC_AlarmEveryYear (void)
Definition at line 617 of file rtcc.c.
References RTCC_ALARM_EVERY_YEAR, and RTCC_SetAlarmRepeat().
{
    RTCC_SetAlarmRepeat(RTCC_ALARM_EVERY_YEAR);
}
void RTCC_AlarmInitialPulseHigh (void)
Definition at line 826 of file rtcc.c.
References HIGH, and RTCC_SetAlarmInitialPulse().
{
    RTCC_SetAlarmInitialPulse(HIGH);
}
void RTCC_AlarmInitialPulseLow (void)
Definition at line 831 of file rtcc.c.
References LOW, and RTCC_SetAlarmInitialPulse().
{
    RTCC_SetAlarmInitialPulse(LOW);
}
void RTCC_AlarmInitialPulseToggle (void)
Definition at line 841 of file rtcc.c.
References HIGH, LOW, RTCC_GetAlarmInitialPulse(), and RTCC_SetAlarmInitialPulse().
{
    if (RTCC_GetAlarmInitialPulse())
        RTCC_SetAlarmInitialPulse(LOW);
    else
        RTCC_SetAlarmInitialPulse(HIGH);
}
void RTCC_AlarmIntDisable (void)
Definition at line 904 of file rtcc.c.
References False, and RTCC_SetAlarmIntEnable().
{
    RTCC_SetAlarmIntEnable(False);
}
void RTCC_AlarmIntEnable (void)
Definition at line 899 of file rtcc.c.
References RTCC_SetAlarmIntEnable(), and True.
{
    RTCC_SetAlarmIntEnable(True);
}
void RTCC_AlarmPulseOutput (void)
Definition at line 793 of file rtcc.c.
{
        RTCCONbits.RTSECSEL = 0; // RTCC Alarm Pulse is selected for the RTCC pin
}
void RTCC_ChimeDisable (void)
Definition at line 554 of file rtcc.c.
References False, and RTCC_SetChimeEnable().
{
    RTCC_SetChimeEnable(False);
}
void RTCC_ChimeEnable (void)
Definition at line 549 of file rtcc.c.
References RTCC_SetChimeEnable(), and True.
{
    RTCC_SetChimeEnable(True);
}
rtccDate RTCC_ConvertDate (rtccDate * pDt)
Definition at line 190 of file rtcc.c.
References bcd2bin(), rtccDate::dayofmonth, rtccDate::dayofweek, rtccDate::month, and rtccDate::year.
{
    rtccDate d0;
    
    d0.dayofweek = bcd2bin(pDt->dayofweek);
    d0.dayofmonth = bcd2bin(pDt->dayofmonth);
    d0.month = bcd2bin(pDt->month);
    d0.year = bcd2bin(pDt->year);
    return d0;
}
rtccTime RTCC_ConvertTime (rtccTime * pTm)
Definition at line 180 of file rtcc.c.
References bcd2bin(), rtccTime::hours, rtccTime::minutes, and rtccTime::seconds.
{
    rtccTime t0;
    
    t0.hours = bcd2bin(pTm->hours);
    t0.minutes = bcd2bin(pTm->minutes);
    t0.seconds = bcd2bin(pTm->seconds);
    return t0;
}
void RTCC_Disable (void)
Definition at line 263 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
{
    RTCC_SetWriteEnable();
    //RTCCON |= !(1 << 15);
    RTCCONCLR = 0x8000; // turn off the RTCC
    // TODO: RTCCON.RTCSYNC, RTCCON.HALFSEC and RTCCON.RTCOE
    while (RTCCON & 0x40); // wait for clock to be turned off
    // bit 6 RTCCLKON: RTCC Clock Enable Status bit
    RTCC_SetWriteDisable();
}
void RTCC_Enable (void)
Definition at line 247 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
{
    RTCC_SetWriteEnable();
    //RTCCON |= (1 << 15);
    RTCCONSET = 0x8000; // turn on the RTCC
    while (!(RTCCON & 0x40)); // wait for clock to be turned on
    RTCC_SetWriteDisable();
}
rtccDate RTCC_GetAlarmDate (void)
Definition at line 705 of file rtcc.c.
References rtccDate::l.
{
    rtccDate d0;
    d0.l = ALRMDATE;
    return d0;
}
int RTCC_GetAlarmEnable (void)
Definition at line 519 of file rtcc.c.
{
    int isAlrm0, isAlrm1;
    do
    {
        isAlrm0=RTCALRMbits.ALRMEN;
        isAlrm1=RTCALRMbits.ALRMEN;
    } while (isAlrm0 != isAlrm1);
    return isAlrm0;
}
int RTCC_GetAlarmInitialPulse (void)
Definition at line 836 of file rtcc.c.
Referenced by RTCC_AlarmInitialPulseToggle().
{
    return RTCALRMbits.PIV!=0;
}
int RTCC_GetAlarmRepeat (void)
Definition at line 625 of file rtcc.c.
{
    int r0, r1;
    do
    {
        r0 = RTCALRMbits.AMASK;
        r1 = RTCALRMbits.AMASK;
    }while (r0 != r1);
    return r0;
}
char RTCC_GetAlarmRepeatCount (void)
Definition at line 657 of file rtcc.c.
{
    char rpt0, rpt1;
    do
    {
        rpt0 = RTCALRMbits.ARPT;
        rpt1 = RTCALRMbits.ARPT;
    } while (rpt0 != rpt1);
    return rpt0;
}
int RTCC_GetAlarmSync (void)
Definition at line 762 of file rtcc.c.
{
    return RTCALRMbits.ALRMSYNC!=0;
}
rtccTime RTCC_GetAlarmTime (void)
Definition at line 685 of file rtcc.c.
References rtccTime::l.
{
    rtccTime t0;
    t0.l = ALRMTIME;
    return t0;
}
void RTCC_GetAlarmTimeDate (rtccTime * pTm, rtccDate * pDt)
Definition at line 726 of file rtcc.c.
References rtccTime::l, and rtccDate::l.
{
    pTm->l = ALRMTIME;
    pDt->l = ALRMDATE;
}
int RTCC_GetCalibration (void)
Definition at line 484 of file rtcc.c.
{
     return RTCCONbits.CAL;
}
int RTCC_GetChimeEnable (void)
Definition at line 559 of file rtcc.c.
{
    int ch0, ch1;
    do
    {
        ch0 = RTCALRMbits.CHIME;
        ch1 = RTCALRMbits.CHIME;
    }while (ch0 != ch1);
    return ch0;
}
rtccDate RTCC_GetDate (void)
Definition at line 404 of file rtcc.c.
References rtccDate::l.
{
    rtccDate d0, d1;
    do
    {
        d0.l = RTCDATE;
        d1.l = RTCDATE;
    } while (d0.l != d1.l);
    return d0;
}
int RTCC_GetEnable (void)
Definition at line 278 of file rtcc.c.
{
    if (RTCCON & 0x8000)
        return 1;
    else
        return 0;
}
int RTCC_GetHalfSecond (void)
Definition at line 776 of file rtcc.c.
{
     return RTCCONbits.HALFSEC!=0;
}
int RTCC_GetOutputEnable (void)
Definition at line 875 of file rtcc.c.
{
     return RTCCONbits.RTCOE!=0;
}
rtccRes RTCC_GetSOSCstatus (void)
Definition at line 290 of file rtcc.c.
References RTCC_SOSC_NRDY, and RTCC_SOSC_ON.
Referenced by RTCC_SOSCenable().
{
    // 01-01-2012 bug fixed by Mark Harper
    if ((!(OSCCONbits.SOSCEN)) || (!(OSCCONbits.SOSCRDY)))
        return RTCC_SOSC_NRDY;
    /*
    else if (!(RTCCONbits.RTCCLKON)) // At start up RTCC Clock is not enabled so this
                                        // test will ALWAYS fail.
                                        // It is NOT related to SOSC running or not running
    return RTCC_CLK_NRDY;
    */
    return RTCC_SOSC_ON;
}
int RTCC_GetSync (void)
Definition at line 749 of file rtcc.c.
{
     return RTCCONbits.RTCSYNC!=0;
}
rtccTime RTCC_GetTime (void)
Definition at line 367 of file rtcc.c.
References rtccTime::l.
Referenced by RTCC_SetCalibration().
{
    rtccTime t0, t1;
    do
    {
        t0.l = RTCTIME;
        t1.l = RTCTIME;
    } while (t0.l != t1.l);
    return t0;
}
void RTCC_GetTimeDate (rtccTime * pTm, rtccDate * pDt)
Definition at line 442 of file rtcc.c.
References rtccTime::l, and rtccDate::l.
Referenced by get_fattime().
{
    rtccTime t0;
    rtccDate d0;
    do
    {
        d0.l = RTCDATE;
        t0.l = RTCTIME;
        pTm->l = RTCTIME;
        pDt->l = RTCDATE;
    } while ((d0.l != pDt->l) || (t0.l != pTm->l)); // update the user requested data
}
int RTCC_GetWriteEnable (void)
Definition at line 236 of file rtcc.c.
{
     return RTCCONbits.RTCWREN!=0;
}
void RTCC_init (void)
Definition at line 937 of file rtcc.c.
References INT_REAL_TIME_CLOCK, IntClearFlag(), RTCC_AlarmDisable(), RTCC_Enable(), RTCC_OutputDisable(), RTCC_SetWriteDisable(), and RTCC_SOSCenable().
{
    RTCC_SOSCenable();
    RTCC_Enable();
    RTCC_SetWriteDisable();
    RTCC_AlarmDisable();
    RTCC_OutputDisable();
    IntClearFlag(INT_REAL_TIME_CLOCK);
}
rtccRes RTCC_Open (unsigned long tm, unsigned long dt, int drift)
Definition at line 976 of file rtcc.c.
References INT_REAL_TIME_CLOCK, IntClearFlag(), RTCC_AlarmDisable(), RTCC_Enable(), RTCC_OutputDisable(), RTCC_SetCalibration(), RTCC_SetDate(), RTCC_SetTime(), RTCC_SetWriteDisable(), and RTCC_SOSCenable().
{
    RTCC_SOSCenable();
    RTCC_SetTime(tm);
    RTCC_SetDate(dt);
    RTCC_SetCalibration(drift);
    RTCC_Enable();
    RTCC_AlarmDisable();
    RTCC_OutputDisable();
    RTCC_SetWriteDisable();
    IntClearFlag(INT_REAL_TIME_CLOCK);
}
void RTCC_OutputDisable (void)
Definition at line 870 of file rtcc.c.
References False, and RTCC_SetOutputEnable().
Referenced by RTCC_init(), RTCC_Open(), and RTCC_Shutdown().
{
    RTCC_SetOutputEnable(False);
}
void RTCC_OutputEnable (void)
Definition at line 865 of file rtcc.c.
References RTCC_SetOutputEnable(), and True.
{
    RTCC_SetOutputEnable(True);
}
void RTCC_SecondsPulseOutput (void)
Definition at line 788 of file rtcc.c.
{
        RTCCONbits.RTSECSEL = 1; // RTCC Seconds Clock is selected for the RTCC pin
}
void RTCC_SetAlarmDate (unsigned long alDate)
Definition at line 695 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMCLR = 0xCFFF; // clear the ALRMEN, CHIME, AMASK and ARPT;
    ALRMDATE = alDate;
}
void RTCC_SetAlarmEnable (int enable)
Definition at line 498 of file rtcc.c.
References RTCC_Disable(), and RTCC_Enable().
Referenced by RTCC_AlarmDisable(), RTCC_AlarmEnable(), and RTCC_SetAlarmInitialPulse().
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCC_Disable();
    if (enable)
        RTCALRMbits.ALRMEN = 1; // Alarm is enabled
    else
        RTCALRMbits.ALRMEN = 0; // Alarm is disabled
    RTCC_Enable();
}
void RTCC_SetAlarmInitialPulse (int enable)
Definition at line 805 of file rtcc.c.
References False, RTCC_Disable(), RTCC_Enable(), RTCC_SetAlarmEnable(), and True.
Referenced by RTCC_AlarmInitialPulseHigh(), RTCC_AlarmInitialPulseLow(), and RTCC_AlarmInitialPulseToggle().
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCC_Disable(); //
    RTCC_SetAlarmEnable(False);// Alarm is disabled, PIV is writable
    if (enable)
        RTCALRMbits.PIV = 1; // the initial value of the Alarm Pulse is high
    else
        RTCALRMbits.PIV = 0; // the initial value of the Alarm Pulse is low
    RTCC_SetAlarmEnable(True); // Alarm is enabled
    RTCC_Enable(); //
}
void RTCC_SetAlarmIntEnable (int enable)
Definition at line 884 of file rtcc.c.
References INT_PRIORITY_3, INT_REAL_TIME_CLOCK, INT_RTCC_VECTOR, INT_SUBPRIORITY_1, INT_SYSTEM_CONFIG_MULT_VECTOR, IntClearFlag(), IntConfigureSystem(), IntDisable(), IntEnable(), and IntSetVectorPriority().
Referenced by RTCC_AlarmIntDisable(), and RTCC_AlarmIntEnable().
{
    if (enable)
    {
        IntConfigureSystem(INT_SYSTEM_CONFIG_MULT_VECTOR);
        IntSetVectorPriority(INT_RTCC_VECTOR,
      INT_PRIORITY_3, INT_SUBPRIORITY_1);
        IntClearFlag(INT_REAL_TIME_CLOCK);
        IntEnable(INT_REAL_TIME_CLOCK);
    }
    else
    {
        IntDisable(INT_REAL_TIME_CLOCK);
    }
}
void RTCC_SetAlarmRepeat (int rpt)
Definition at line 575 of file rtcc.c.
Referenced by RTCC_AlarmEveryDay(), RTCC_AlarmEveryHalfSecond(), RTCC_AlarmEveryHour(), RTCC_AlarmEveryMinute(), RTCC_AlarmEveryMonth(), RTCC_AlarmEverySecond(), RTCC_AlarmEveryTenMinutes(), RTCC_AlarmEveryTenSeconds(), RTCC_AlarmEveryWeek(), and RTCC_AlarmEveryYear().
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMbits.AMASK = rpt;
}
void RTCC_SetAlarmRepeatCount (char rptCnt)
Definition at line 645 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMbits.ARPT = rptCnt;
}
void RTCC_SetAlarmSync (int sync)
Definition at line 754 of file rtcc.c.
{
    if (sync)
        RTCALRMbits.ALRMSYNC = 1;
    else
        RTCALRMbits.ALRMSYNC = 0;
}
void RTCC_SetAlarmTime (unsigned long alTime)
Definition at line 675 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMCLR = 0xCFFF; // clear the ALRMEN, CHIME, AMASK and ARPT;
    ALRMTIME = alTime;
}
void RTCC_SetAlarmTimeDate (unsigned long alTime, unsigned long alDate)
Definition at line 715 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMCLR = 0xCFFF; // clear the ALRMEN, CHIME, AMASK and ARPT;
    ALRMTIME = alTime;
    ALRMDATE = alDate;
}
void RTCC_SetCalibration (int cal)
Definition at line 462 of file rtcc.c.
References RTCC_GetTime(), RTCC_SetWriteDisable(), RTCC_SetWriteEnable(), and rtccTime::seconds.
Referenced by RTCC_Open().
{
    rtccTime t0;
    if (cal < -512) cal = -512;
    if (cal > 511) cal = 511;
    if (RTCCON & 0x8000) // if RTCC is ON
    {
        t0 = RTCC_GetTime();
        if ((t0.seconds & 0xFF) == 00) // we're at second 00, wait auto-adjust to be
       performed
            while(!(RTCCON & 0x2)); // wait until second half...
    }
    RTCC_SetWriteEnable();
    RTCCONCLR = 0x03FF0000; // clear the calibration
    RTCCONbits.CAL = cal;
    RTCC_SetWriteDisable();
}
void RTCC_SetChimeEnable (int enable)
Definition at line 538 of file rtcc.c.
Referenced by RTCC_ChimeDisable(), and RTCC_ChimeEnable().
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    //RTCC_Disable();
    if (enable)
        RTCALRMbits.CHIME = 1; // chime is on
    else
        RTCALRMbits.CHIME = 0; // chime is off
    //RTCC_Enable();
}
void RTCC_SetDate (unsigned long dt)
Definition at line 388 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
Referenced by RTCC_Open().
{
    RTCC_SetWriteEnable();
    RTCCONCLR = 0x8000; // turn off the RTCC
    //Delayus(50);
    while (RTCCON & 0x40); // wait for clock to be turned off
    RTCDATE = dt; // Set date
    RTCCONSET = 0x8000; // turn on the RTCC
    //Delayus(50);
    while (!(RTCCON & 0x40)); // wait for clock to be turned on
    RTCC_SetWriteDisable();
}
void RTCC_SetOutputEnable (int enable)
Definition at line 857 of file rtcc.c.
Referenced by RTCC_OutputDisable(), and RTCC_OutputEnable().
{
    if(enable)
        RTCCONbits.RTCOE = 1;
    else
        RTCCONbits.RTCOE = 0;
}
void RTCC_SetSync (int sync)
Definition at line 741 of file rtcc.c.
{
    if (sync)
        RTCCONbits.RTCSYNC = 1;
    else
        RTCCONbits.RTCSYNC = 0;
}
void RTCC_SetTime (unsigned long tm)
Definition at line 351 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
Referenced by RTCC_Open().
{
    RTCC_SetWriteEnable();
    RTCCONCLR = 0x8000; // turn off the RTCC
    //Delayus(50);
    while (RTCCON & 0x40); // wait for clock to be turned off
    RTCTIME = tm; // Set time
    RTCCONSET = 0x8000; // turn on the RTCC
    //Delayus(50);
    while (!(RTCCON & 0x40)); // wait for clock to be turned on
    RTCC_SetWriteDisable();
}
void RTCC_SetTimeDate (unsigned long tm, unsigned long dt)
Definition at line 425 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
{
    RTCC_SetWriteEnable();
    RTCCONCLR = 0x8000; // turn off the RTCC
    //Delayus(50);
    while (RTCCON & 0x40); // wait for clock to be turned off
    RTCTIME = tm; // Set time
    RTCDATE = dt; // Set date
    RTCCONSET = 0x8000; // turn on the RTCC
    //Delayus(50);
    while (!(RTCCON & 0x40)); // wait for clock to be turned on
    RTCC_SetWriteDisable();
}
void RTCC_SetWriteDisable (void)
Definition at line 220 of file rtcc.c.
References SystemLock(), and SystemUnlock().
{
    // assume interrupts are disabled
    // assume the DMA controller is suspended
    // assume the device is locked
    SystemUnlock();
    RTCCONCLR = 0x8; // clear RTCWREN (bit 3) in RTCCON
    SystemLock();
    // re-enable interrupts
    // re-enable the DMA controller
}
void RTCC_SetWriteEnable (void)
Definition at line 208 of file rtcc.c.
References SystemLock(), and SystemUnlock().
{
    // assume interrupts are disabled
    // assume the DMA controller is suspended
    // assume the device is locked
    SystemUnlock();
    RTCCONSET = 0x8; // set RTCWREN (bit 3) in RTCCON
    SystemLock();
    // re-enable interrupts
    // re-enable the DMA controller
}
void RTCC_Shutdown (void)
Definition at line 956 of file rtcc.c.
References INT_REAL_TIME_CLOCK, IntClearFlag(), RTCC_AlarmDisable(), RTCC_Disable(), RTCC_OutputDisable(), RTCC_SetWriteDisable(), and RTCC_SOSCdisable().
{
    RTCC_SOSCdisable();
    RTCC_Disable();
    RTCC_SetWriteDisable();
    RTCC_AlarmDisable();
    RTCC_OutputDisable();
    IntClearFlag(INT_REAL_TIME_CLOCK);
}
void RTCC_SOSCdisable (void)
Definition at line 334 of file rtcc.c.
References SystemLock(), and SystemUnlock().
Referenced by RTCC_Shutdown().
{
    SystemUnlock();
    OSCCONbits.SOSCEN = 0;
    SystemLock();
}
void RTCC_SOSCenable (void)
Definition at line 314 of file rtcc.c.
References RTCC_GetSOSCstatus(), RTCC_SOSC_ON, SystemLock(), and SystemUnlock().
Referenced by RTCC_init(), and RTCC_Open().
{
    SystemUnlock();
    OSCCONbits.SOSCEN = 1;
    SystemLock();
    // Wait for stable SOCSC oscillator output before enabling the RTCC.
    // This typically requires a 32 ms delay between enabling the SOSC and enabling the RTCC.
    // 1st option
    // Delayms(50);
    // 2nd option
    // Wait for the SOSC to run
    while (RTCC_GetSOSCstatus() != RTCC_SOSC_ON);
}
void RTCCInterrupt (void)
Definition at line 919 of file rtcc.c.
References INT_REAL_TIME_CLOCK, IntClearFlag(), and IntGetFlag().
{
    if (IntGetFlag(INT_REAL_TIME_CLOCK))
    {
        IntClearFlag(INT_REAL_TIME_CLOCK);
        intFunction();
    }
}