/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/sd/sdmmc.c File Reference
#include <system.c>
*
#include <digitalw.c>
*
#include <spi.c>
*
#include <sd/sdmmc.h>
*
#include <sd/diskio.h>
*
#include <sd/ff.h>
*
Macros
#define __SDMMC_C__
#define readSPI() writeSPI(0xFF)
#define clockSPI() writeSPI(0xFF)
Functions
unsigned char writeSPI (unsigned char b)
void initSD (void)
void disableSD (void)
void enableSD (void)
int sendSDCmd (unsigned char c, unsigned a)
int initMedia (void)
int readSECTOR (LBA a, char *p)
int writeSECTOR (LBA a, char *p)
int getCD (void)
int getWP (void)
Macro Definition Documentation
#define __SDMMC_C__
Definition at line 15 of file sdmmc.c.
#define clockSPI() writeSPI(0xFF)
Definition at line 53 of file sdmmc.c.
Referenced by disableSD(), initMedia(), and writeSECTOR().
#define readSPI() writeSPI(0xFF)
Definition at line 52 of file sdmmc.c.
Referenced by readSECTOR(), sendSDCmd(), and writeSECTOR().
Function Documentation
void disableSD (void)
Definition at line 55 of file sdmmc.c.
References clockSPI, digitalwrite(), HIGH, and SDCS.
{
    digitalwrite(SDCS, HIGH); // Deselected = SDCS high
    clockSPI();
}
void enableSD (void)
Definition at line 61 of file sdmmc.c.
References digitalwrite(), LOW, and SDCS.
{
    digitalwrite(SDCS, LOW); // Selected = SDCS low
}
int getCD (void)
Definition at line 250 of file sdmmc.c.
References TRUE.
{
// 07 May 2012 ** Added specific support for PIC32 Pinguino and Micro
#if defined (PIC32_PINGUINO) || defined (PIC32_PINGUINO_OTG) || defined (PIC32_PINGUINO_MICRO) || defined
       (EMPEROR460)
    return TRUE;
#else
    return (SDCD);
#endif
}
int getWP (void)
Definition at line 263 of file sdmmc.c.
References FALSE.
{
// 07 May 2012 ** Added specific support for PIC32 Pinguino and Micro
#if defined (PIC32_PINGUINO) || defined (PIC32_PINGUINO_OTG) || defined (PIC32_PINGUINO_MICRO) ||
       defined(EMPEROR460)
    return FALSE;
#else
    return (SDWP);
#endif
}
int initMedia (void)
Definition at line 116 of file sdmmc.c.
References clockSPI, disableSD(), E_COMMAND_ACK, E_INIT_TIMEOUT, enableSD(), I_TIMEOUT, INIT, RESET, and sendSDCmd().
{
    int i, r;
    // 1. with the card NOT selected
    // Set DI and CS high
    disableSD();
    // 2. send 74 or more clock cycles to start up
    // apply 74 or more clock pulses to SCLK.
    // The card will enter its native operating mode and go ready to accept native commands.
    for (i=0; i<10; i++)
        clockSPI();
    // 3. now select the card
    enableSD();
    //card detection is now in disk_initialize()
    return 0;
} // init media
void initSD (void)
Definition at line 37 of file sdmmc.c.
References digitalwrite(), GetPeripheralClock(), HIGH, INPUT, OUTPUT, pinmode(), and SDCS.
{
    digitalwrite(SDCS, HIGH); // initially keep the SD card disabled
    pinmode(SDCS, OUTPUT); // make Card select an output pin
    // init the spi module for a slow (safe) clock speed first
/*
    SPI2CON = 0x8120; // ON (0x8000), CKE=1 (0x100), CKP=0, Master mode (0x20)
    SPI2BRG = (GetPeripheralClock() / (2 * 250000)) - 1;
*/
    SPICONF = 0x8120; // ON (0x8000), CKE=1 (0x100), CKP=0, Master mode (0x20)
    CLKSPD = (GetPeripheralClock() / (2 * 250000)) - 1;
} // initSD
int readSECTOR (LBA a, char * p)
Definition at line 142 of file sdmmc.c.
References DATA_START, digitalwrite(), disableSD(), R_TIMEOUT, READ_SINGLE, readSPI, and sendSDCmd().
{
    int r, i;
    #ifdef READ_LED
    digitalwrite(READ_LED, 0);
    #endif
    // 1. send READ command
    r = sendSDCmd(READ_SINGLE, (a << 9));
    if (r == 0) // check if command was accepted
    {
    // 2. wait for a response
    for(i=0; i<R_TIMEOUT; i++)
    {
    r = readSPI();
    if (r == DATA_START)
    break;
    }
    // 3. if it did not timeout, read 512 byte of data
    if (i != R_TIMEOUT)
    {
        i = 512;
        do{
            *p++ = readSPI();
        } while (--i>0);
        // 4. ignore CRC
        readSPI();
        readSPI();
    } // data arrived
    } // command accepted
    // 5. remember to disable the card
    disableSD();
    #ifdef READLED
    digital(READ_LED, 1);
    #endif
    return (r == DATA_START); // return TRUE if successful
} // readSECTOR
int sendSDCmd (unsigned char c, unsigned a)
Definition at line 68 of file sdmmc.c.
References enableSD(), readSPI, and writeSPI().
{
    int i, r;
    // enable SD card
    // CS low
    enableSD();
    // send a comand packet (6 bytes)
    writeSPI(c | 0x40); // send command
    writeSPI(a>>24); // msb of the address
    writeSPI(a>>16);
    writeSPI(a>>8);
    writeSPI(a); // lsb
    writeSPI(0x95); // send CMD0 CRC
    // now wait for a response, allow for up to 8 bytes delay
    for(i=0; i<8; i++)
    {
        r = readSPI();
        if (r != 0xFF)
            break;
    }
    return (r);
    /* return response
    FF - timeout
    00 - command accepted
    01 - command received, card in idle state after RESET
    other codes:
    bit 0 = Idle state
    bit 1 = Erase Reset
    bit 2 = Illegal command
    bit 3 = Communication CRC error
    bit 4 = Erase sequence error
    bit 5 = Address error
    bit 6 = Parameter error
    bit 7 = Always 0
    */
    // NOTE CSCD is still low!
} // sendSDCmd
int writeSECTOR (LBA a, char * p)
Definition at line 192 of file sdmmc.c.
References clockSPI, DATA_ACCEPT, DATA_START, digitalwrite(), disableSD(), FAIL, getWP(), readSPI, sendSDCmd(), W_TIMEOUT, WRITE_SINGLE, and writeSPI().
{
    unsigned r, i;
    // 0. check Write Protect
    if (getWP())
        return FAIL;
    // 1. send WRITE command
    r = sendSDCmd(WRITE_SINGLE, (a << 9));
    if (r == 0) // check if command was accepted
    {
        // 2. send data
        writeSPI(DATA_START);
        // send 512 bytes of data
        for(i=0; i<512; i++)
        writeSPI(*p++);
        // 3. send dummy CRC
        clockSPI();
        clockSPI();
        // 4. check if data accepted
        r = readSPI();
        if ((r & 0xf) == DATA_ACCEPT)
        {
            #ifdef WRITE_LED
            digitalwrite(WRITE_LED, 0);
            #endif
            // 5. wait for write completion
            for(i=0; i<W_TIMEOUT; i++)
            {
                r = readSPI();
                if (r != 0)
                    break;
            }
            #ifdef WRITE_LED
            digitalwrite(WRITE_LED, 1);
            #endif
        } // accepted
        else
        {
            r = FAIL;
        }
    } // command accepted
    // 6. disable the card
    disableSD();
    return (r); // return TRUE if successful
} // writeSECTOR
unsigned char writeSPI (unsigned char b)
Definition at line 25 of file sdmmc.c.
{
/*
    SPI2BUF = b;
    while(!SPI2STATbits.SPIRBF); // wait transfer complete
    return SPI2BUF; // read the received value
*/
    BUFFER = b; // write to buffer for TX
    while (!STATRX); // wait until cycle complete
    return BUFFER; // return with byte read
} // writeSPI