/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/dcf77.c File Reference
#include <typedef.h>
*
#include <digitalw.c>
*
#include <interrupt.c>
*
#include <dcf77.h>
*
#include <bcd.c>
*
Macros
#define _DCF77_C_
#define DCF_Discr_150ms (150 / 20)
#define DCF_Sync_1500ms (1500 / 20)
Functions
void DCF77_appendSignal (u8 signal)
u8 Parity_Even (u32 Bits)
void Decode_Buffer (void)
void DCF77_scanSignal (void)
void Update_Time (void)
void DCF77_start (u8 dcfPin)
void ISR_wrapper_vector_4 (void)
void Timer1Interrupt (void)
void Disp_Input_Binary (u32 Bits1, u32 Bits2)
Variables
u8 SignalPin
u8 PrevSignal
u8 BuffPntr
u8 Cntr_sec
u8 Nosync
u16 PrevFlank
u32 Buff1
u32 Buff2
u32 Cntr_20ms
Macro Definition Documentation
#define _DCF77_C_
Definition at line 35 of file dcf77.c.
#define DCF_Discr_150ms (150 / 20)
Definition at line 51 of file dcf77.c.
Referenced by DCF77_scanSignal().
#define DCF_Sync_1500ms (1500 / 20)
Definition at line 57 of file dcf77.c.
Referenced by DCF77_scanSignal().
Function Documentation
void DCF77_appendSignal (u8 signal)
Definition at line 71 of file dcf77.c.
References Buff1, Buff2, and BuffPntr.
{
// serial1printf("BuffPntr: %02d ", BuffPntr);
    if ((signal > 0) && (BuffPntr < 32))
        Buff1 = Buff1 | (1 << BuffPntr);
    if ((signal > 0) && (BuffPntr > 31))
        Buff2 = Buff2 | (1 << (BuffPntr - 32));
// serial1printf("Append Buff: %08x %08x \r\n", DCF77.Buff1, DCF77.Buff2);
    BuffPntr++;
    if (BuffPntr > 59)
    {
        BuffPntr = 0;
        Buff1 = 0;
        Buff2 = 0;
    }
}
void DCF77_scanSignal (void)
Definition at line 180 of file dcf77.c.
References Cntr_20ms, DCF77_appendSignal(), DCF_Discr_150ms, DCF_Sync_1500ms, Decode_Buffer(), digitalread(), PrevFlank, PrevSignal, and SignalPin.
{
  u16 LengthPulse;
  u16 CurrFlank;
  u8 CurrSignal ;
    CurrSignal = digitalread(SignalPin);
    if (CurrSignal != PrevSignal)
    {
        if (CurrSignal == 1)
        {
// digitalwrite(GREENLED, HIGH);
            /* At a raising flank */
            CurrFlank = Cntr_20ms;
            if ((CurrFlank - PrevFlank) > DCF_Sync_1500ms)
                Decode_Buffer();
            PrevFlank = CurrFlank;
        }
        else
        {
// digitalwrite(GREENLED, LOW);
            /* At a falling flank */
            LengthPulse = Cntr_20ms - PrevFlank;
            if (LengthPulse < DCF_Discr_150ms)
                DCF77_appendSignal(0);
            else
                DCF77_appendSignal(1);
        }
        PrevSignal = CurrSignal;
    }
}
void DCF77_start (u8 dcfPin)
Definition at line 257 of file dcf77.c.
References Buff1, Buff2, BuffPntr, Time_Date_Format::dayofmonth, Time_Date_Format::dayofweek, Time_Date_Format::hours, INPUT, INT_ENABLE, INT_HIGH_PRIORITY, INT_SYSTEM_CONFIG_MULT_VECTOR, INT_TIMER1_VECTOR, IntConfigureSystem(), Time_Date_Format::minutes, Time_Date_Format::month, Time_Date_Format::nosync, Nosync, pinmode(), PrevFlank, PrevSignal, RTClock, Time_Date_Format::seconds, SignalPin, T3_ON, T3_PS_1_8, TMR_PRELOADH, TMR_PRELOADL, and Time_Date_Format::year.
{
    SignalPin = dcfPin;
    pinmode(SignalPin, INPUT);
    PrevSignal = 0;
    PrevFlank = 0;
    BuffPntr = 0;
    Buff1 = 0;
    Buff2 = 0;
    Nosync = 1;
/* Timer1 Configuration
       The timer clock prescale (TCKPS) is 1:64
       The TMR1 Count register increments on every PBCLK clock cycle
       PBCLK = CPUCLK / 2 = 40MHz => TMR1 inc. every 64/40MHZ = 1,6 us
       20 ms = 20000 us => 20000 / 1.6 = 12500 cycles
*/
    IntConfigureSystem(INT_SYSTEM_CONFIG_MULT_VECTOR);
    T1CON = 0x20; // prescaler 1:64, internal peripheral clock
    TMR1 = 0; // clear timer register
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    PR1 = 6250; // load period register
    #else
    PR1 = 12500; // load period register
    #endif
    IPC1SET = 7; // select interrupt priority and sub-priority
    IFS0CLR = 1 << INT_TIMER1_VECTOR; // clear interrupt flag
    IEC0SET = 1 << INT_TIMER1_VECTOR; // enable timer 1 interrupt
    T1CONSET = 0x8000; // start timer 1
}
void Decode_Buffer (void)
Definition at line 104 of file dcf77.c.
References bcd2bin(), Buff1, Buff2, BuffPntr, Time_Date_Format::dayofmonth, Time_Date_Format::dayofweek, DCF77, Time_Date_Format::hours, Time_Date_Format::minutes, Time_Date_Format::month, Nosync, Parity_Even(), RTClock, Time_Date_Format::seconds, and Time_Date_Format::year.
{
  u32 Code;
  u8 Par, Par1, Par2, Par3;
// Disp_Input_Binary(Buff1, Buff2);
    if (BuffPntr == 59)
    {
        // Minutes
        Code = (Buff1 >> 21) & 0x7F;
        Par = Parity_Even(Code);
        Par1 = (Buff1 >> 28) & 1;
// serial1printf("Par= %d Par1= %d\r\n", Par, Par1);
        if (Par == Par1)
        {
            Par1 = 11;
            DCF77.minutes = bcd2bin(Code);
// serial1printf("mm= %02d \r\n", DCF77.mm);
        }
        // Hours
        Code = ((Buff1 >> 29) & 0x7) | ((Buff2 & 0x7) << 3);
        Par = Parity_Even(Code);
        Par2 = (Buff2 >> 3) & 1;
// serial1printf("Par= %d Par2= %d\r\n", Par, Par2);
        if (Par == Par2)
        {
            Par2 = 12;
            DCF77.hours = bcd2bin(Code);
// serial1printf("hh= %02d \r\n", DCF77.hh);
        }
        Code = (Buff2 >> 4) & 0x3FFFFF;
        Par = Parity_Even(Code);
        Par3 = (Buff2 >> 26) & 1;
// serial1printf("Par= %d Par3= %d\r\n", Par, Par3);
        if (Par == Par3)
        {
            Par3 = 13;
            Code = (Buff2 >> 10) & 0x7;
            DCF77.dayofweek = bcd2bin(Code);
// serial1printf("dw= %02d \r\n", DCF77.dw);
            Code = (Buff2 >> 4) & 0x3F;
            DCF77.dayofmonth = bcd2bin(Code);
// serial1printf("da= %02d \r\n", DCF77.da);
            Code = (Buff2 >> 13) & 0x1F;
            DCF77.month = bcd2bin(Code);
// serial1printf("mo= %02d \r\n", DCF77.mo);
            Code = (Buff2 >> 18) & 0xFF;
            DCF77.year = bcd2bin(Code);
// serial1printf("yr= %02d \r\n", DCF77.yr);
        }
// Part = Par1 + Par2 + Par3;
// serial1printf("Part= %d\r\n", Part);
        if (Par1 + Par2 + Par3 == 36)
        {
            DCF77.seconds = 0;
            Nosync = 0;
// serial1printf("Tim= %d:%02d \r\n", DCF77.hh, DCF77.mm);
// serial1printf("Dat=: %02d-%02d-%02d %1d\r\n", DCF77.da, DCF77.mo, DCF77.yr, DCF77.dw);
            RTClock = DCF77;
        }
    }
    // Reset Inputbuffer
    BuffPntr = 0;
    Buff1 = 0;
    Buff2 = 0;
}
void Disp_Input_Binary (u32 Bits1, u32 Bits2)
Definition at line 323 of file dcf77.c.
References serial1write().
{
  u8 BitC;
    serial1printf("Bits= %08x %08x \r\n", Bits1, Bits2);
    for (BitC = 32; BitC > 0; BitC--)
    {
        if ((Bits2 & (1 << (BitC-1))) > 0)
            serial1write('1');
        else
            serial1write('0');
    }
    for (BitC = 32; BitC > 0; BitC--)
    {
        if ((Bits1 & (1 << (BitC-1))) > 0)
            serial1write('1');
        else
            serial1write('0');
    }
    serial1println(" ");
}
void ISR_wrapper_vector_4 (void)
Definition at line 293 of file dcf77.c.
References Timer1Interrupt().
                                { Timer1Interrupt(); }
u8 Parity_Even (u32 Bits)
Definition at line 91 of file dcf77.c.
{
  u8 i;
  u8 p = 0;
    for (i = 0; i < 32; i++)
        if ((Bits & (1 << i)) > 0)
            p = !p;
    return p;
}
void Timer1Interrupt (void)
Definition at line 299 of file dcf77.c.
References Cntr_20ms, Cntr_sec, DCF77_scanSignal(), INT_TIMER1, IntClearFlag(), IntGetFlag(), and Update_Time().
Referenced by ISR_wrapper_vector_4().
{
    // is this an TMR1 interrupt ?
    if (IntGetFlag(INT_TIMER1))
    {
        // Update time every second
        Cntr_20ms++;
        Cntr_sec++;
        if (Cntr_sec > 49)
        {
            Cntr_sec = 0;
            Update_Time();
        }
        DCF77_scanSignal();
        IntClearFlag(INT_TIMER1);
    }
}
void Update_Time (void)
Definition at line 214 of file dcf77.c.
References Time_Date_Format::dayofmonth, Time_Date_Format::dayofweek, Time_Date_Format::hours, Time_Date_Format::minutes, Time_Date_Format::month, Time_Date_Format::nosync, Nosync, RTClock, Time_Date_Format::seconds, and Time_Date_Format::year.
{
  u8 Mnth[12] = {31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    if (RTClock.seconds == 0)
        RTClock.nosync = Nosync;
    RTClock.seconds++; // Seconds
    if (RTClock.seconds > 59)
    {
        Nosync++;
        RTClock.seconds = 0;
        RTClock.minutes++; // Minutes
        if (RTClock.minutes > 59)
        {
            RTClock.minutes = 0;
            RTClock.hours++; // Hours
            if (RTClock.hours > 23)
            {
                RTClock.hours = 0;
                RTClock.dayofweek++; // Day of Week
                if (RTClock.dayofweek > 7)
                    RTClock.dayofweek = 1;
                RTClock.dayofmonth++; // Date
                if (RTClock.dayofmonth > Mnth[RTClock.
      month-1])
                {
                    RTClock.dayofmonth = 1;
                    RTClock.month++; // Month
                    if (RTClock.month > 12)
                    {
                        RTClock.month = 1;
                        RTClock.year++; // Year
                        if (RTClock.year > 99)
                            RTClock.year = 0;
                    }
                }
            }
        }
    }
}
Variable Documentation
u32 Buff1
Definition at line 65 of file dcf77.c.
u32 Buff2
Definition at line 65 of file dcf77.c.
u8 BuffPntr
Definition at line 63 of file dcf77.c.
u32 Cntr_20ms
Definition at line 66 of file dcf77.c.
Referenced by DCF77_scanSignal(), and Timer1Interrupt().
u8 Cntr_sec
Definition at line 63 of file dcf77.c.
u8 Nosync
Definition at line 63 of file dcf77.c.
u16 PrevFlank
Definition at line 64 of file dcf77.c.
u8 PrevSignal
Definition at line 63 of file dcf77.c.
u8 SignalPin
Definition at line 63 of file dcf77.c.