/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/SSD1306.h File Reference
#include <typedef.h>
*
Data Structures
struct coord_t
struct font_t
struct color_t
struct rect_t
union word_t
struct lcd_t
Macros
#define SSD1306_PMP 1<<0
#define SSD1306_I2C 1<<1
#define SSD1306_6800 1<<2
#define SSD1306_8080 1<<3
#define SSD1306_SPI3 1<<4
#define SSD1306_SPI4 1<<5
#define SSD1306_128X32 1<<6
#define SSD1306_128X64 1<<7
#define SSD1306_SETCONTRAST 0x81
#define SSD1306_DISPLAYALLON_RESUME 0xA4
#define SSD1306_DISPLAYALLON 0xA5
#define SSD1306_NORMALDISPLAY 0xA6
#define SSD1306_INVERTDISPLAY 0xA7
#define SSD1306_DISPLAYOFF 0xAE
#define SSD1306_DISPLAYON 0xAF
#define SSD1306_SETDISPLAYOFFSET 0xD3
#define SSD1306_SETCOMPINS 0xDA
#define SSD1306_SETVCOMDETECT 0xDB
#define SSD1306_SETDISPLAYCLOCKDIV 0xD5
#define SSD1306_SETPRECHARGE 0xD9
#define SSD1306_SETMULTIPLEX 0xA8
#define SSD1306_SETLOWCOLUMN 0x00
#define SSD1306_SETHIGHCOLUMN 0x10
#define SSD1306_SETSTARTLINE 0x40
#define SSD1306_MEMORYMODE 0x20
#define SSD1306_COMSCANINC 0xC0
#define SSD1306_COMSCANDEC 0xC8
#define SSD1306_SEGREMAP 0xA0
#define SSD1306_SEGREMAPINV 0xA1
#define SSD1306_CHARGEPUMP 0x8D
#define SSD1306_EXTERNALVCC 0x1
#define SSD1306_SWITCHCAPVCC 0x2
#define SSD1306_ACTIVATE_SCROLL 0x2F
#define SSD1306_DEACTIVATE_SCROLL 0x2E
#define SSD1306_SET_VERTICAL_SCROLL_AREA 0xA3
#define SSD1306_RIGHT_HORIZONTAL_SCROLL 0x26
#define SSD1306_LEFT_HORIZONTAL_SCROLL 0x27
#define SSD1306_VERTICAL_AND_RIGHT_HORIZONTAL_SCROLL 0x29
#define SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL 0x2A
#define DISPLAY_WIDTH 128
#define DISPLAY_WIDTH_BITS 7
#define DISPLAY_WIDTH_MASK 0x7f
#define DISPLAY_ROWS 4
#define DISPLAY_ROW_BITS 2
#define DISPLAY_ROW_MASK 0x03
#define DISPLAY_HEIGHT (DISPLAY_ROWS * 8)
#define DISPLAY_SIZE (DISPLAY_WIDTH * DISPLAY_ROWS)
#define PORTRAIT 100
#define LANDSCAPE 101
#define Blue 0x001F
#define Yellow 0xFFE0
#define SSD1306_getFontWidth() (SSD1306.font.width)
#define SSD1306_getFontHeight() (SSD1306.font.height)
#define SSD1306_invertDisplay() SSD1306_sendCommand(SSD1306_INVERTDISPLAY)
#define SSD1306_normalDisplay() SSD1306_sendCommand(SSD1306_NORMALDISPLAY)
Functions
void SSD1306_sendCommand (u8 _cmd)
void SSD1306_sendData (u8 _data)
void SSD1306_displayOff ()
void SSD1306_displayOn ()
void SSD1306_sleep ()
void SSD1306_wake ()
void SSD1306_setInverse (u8 value)
void SSD1306_setDisplayOffset (u8 value)
void SSD1306_setContrast (u8 value)
void SSD1306_setDisplayStartLine (u8 value)
void SSD1306_setSegmentRemap (u8 value)
void SSD1306_setMultiplexRatio (u8 value)
void SSD1306_setComOutputScanDirection (u8 value)
void SSD1306_setComPinsHardwareConfiguration (u8 sequential, u8 lr_remap)
void SSD1306_startHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval)
void SSD1306_startVerticalAndHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval, u8 vertical_offset)
void SSD1306_stopScroll ()
void SSD1306_pamSetStartAddress (u8 address)
void SSD1306_setMemoryAddressingMode (u8 mode)
void SSD1306_hvSetColumnAddress (u8 start, u8 end)
void SSD1306_hvSetPageAddress (u8 start, u8 end)
void SSD1306_pamSetPageStart (u8 address)
void SSD1306_setDisplayClockRatioAndFrequency (u8 ratio, u8 frequency)
void SSD1306_setPrechargePeriod (u8 phase1, u8 phase2)
void SSD1306_setVcomhDeselectLevel (u8 level)
void SSD1306_nop ()
void SSD1306_setChargePumpEnable (u8 enable)
void SSD1306_init ()
void SSD1306_refresh ()
void SSD1306_clearScreen (void)
void SSD1306_scrollRight ()
void SSD1306_scrollLeft ()
void SSD1306_scrollUp ()
void SSD1306_scrollDown ()
void SSD1306_setFont (const u8 *font)
void SSD1306_printChar (u8 c)
void SSD1306_print (u8 *string)
void SSD1306_println (u8 *string)
void SSD1306_printNumber (long value, u8 base)
void SSD1306_printFloat (float number, u8 digits)
void SSD1306_printf (const u8 *fmt,...)
void SSD1306_setCursor (u8 x, u8 y)
void SSD1306_drawPixel (u8 x, u8 y)
void SSD1306_clearPixel (u8 x, u8 y)
u8 SSD1306_getColor (u8 x, u8 y)
void SSD1306_drawBitmap (u16 x, u16 y, u16 w, u16 h, u16 *bitmap)
void drawPixel (u16 x, u16 y)
void SSD1306_drawCircle (u16 x, u16 y, u16 radius)
void SSD1306_fillCircle (u16 x, u16 y, u16 radius)
void SSD1306_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Variables
lcd_t SSD1306
u8 * SSD1306_bufferptr
Macro Definition Documentation
#define Blue 0x001F
Definition at line 125 of file SSD1306.h.
#define DISPLAY_HEIGHT (DISPLAY_ROWS * 8)
Definition at line 119 of file SSD1306.h.
#define DISPLAY_ROW_BITS 2
Definition at line 115 of file SSD1306.h.
#define DISPLAY_ROW_MASK 0x03
Definition at line 116 of file SSD1306.h.
#define DISPLAY_ROWS 4
Definition at line 114 of file SSD1306.h.
#define DISPLAY_SIZE (DISPLAY_WIDTH * DISPLAY_ROWS)
Definition at line 120 of file SSD1306.h.
#define DISPLAY_WIDTH 128
Display constants
Definition at line 105 of file SSD1306.h.
#define DISPLAY_WIDTH_BITS 7
Definition at line 106 of file SSD1306.h.
#define DISPLAY_WIDTH_MASK 0x7f
Definition at line 107 of file SSD1306.h.
#define LANDSCAPE 101
Definition at line 122 of file SSD1306.h.
#define PORTRAIT 100
Definition at line 121 of file SSD1306.h.
#define SSD1306_128X32 1<<6
Display sizes
Definition at line 49 of file SSD1306.h.
#define SSD1306_128X64 1<<7
Definition at line 50 of file SSD1306.h.
#define SSD1306_6800 1<<2
Definition at line 40 of file SSD1306.h.
#define SSD1306_8080 1<<3
Definition at line 41 of file SSD1306.h.
#define SSD1306_ACTIVATE_SCROLL 0x2F
Definition at line 93 of file SSD1306.h.
#define SSD1306_CHARGEPUMP 0x8D
Definition at line 87 of file SSD1306.h.
#define SSD1306_COMSCANDEC 0xC8
Definition at line 82 of file SSD1306.h.
#define SSD1306_COMSCANINC 0xC0
Definition at line 81 of file SSD1306.h.
#define SSD1306_DEACTIVATE_SCROLL 0x2E
Definition at line 94 of file SSD1306.h.
#define SSD1306_DISPLAYALLON 0xA5
Definition at line 58 of file SSD1306.h.
#define SSD1306_DISPLAYALLON_RESUME 0xA4
Definition at line 57 of file SSD1306.h.
#define SSD1306_DISPLAYOFF 0xAE
Definition at line 61 of file SSD1306.h.
#define SSD1306_DISPLAYON 0xAF
Definition at line 62 of file SSD1306.h.
#define SSD1306_EXTERNALVCC 0x1
Definition at line 89 of file SSD1306.h.
#define SSD1306_getFontHeight() (SSD1306.font.height)
Definition at line 240 of file SSD1306.h.
#define SSD1306_getFontWidth() (SSD1306.font.width)
Definition at line 239 of file SSD1306.h.
#define SSD1306_I2C 1<<1
Definition at line 39 of file SSD1306.h.
#define SSD1306_INVERTDISPLAY 0xA7
Definition at line 60 of file SSD1306.h.
#define SSD1306_invertDisplay() SSD1306_sendCommand(SSD1306_INVERTDISPLAY)
Definition at line 241 of file SSD1306.h.
#define SSD1306_LEFT_HORIZONTAL_SCROLL 0x27
Definition at line 97 of file SSD1306.h.
#define SSD1306_MEMORYMODE 0x20
Definition at line 79 of file SSD1306.h.
#define SSD1306_NORMALDISPLAY 0xA6
Definition at line 59 of file SSD1306.h.
#define SSD1306_normalDisplay() SSD1306_sendCommand(SSD1306_NORMALDISPLAY)
Definition at line 242 of file SSD1306.h.
#define SSD1306_PMP 1<<0
Display interfaces
Definition at line 37 of file SSD1306.h.
#define SSD1306_RIGHT_HORIZONTAL_SCROLL 0x26
Definition at line 96 of file SSD1306.h.
#define SSD1306_SEGREMAP 0xA0
Definition at line 84 of file SSD1306.h.
#define SSD1306_SEGREMAPINV 0xA1
Definition at line 85 of file SSD1306.h.
#define SSD1306_SET_VERTICAL_SCROLL_AREA 0xA3
Definition at line 95 of file SSD1306.h.
#define SSD1306_SETCOMPINS 0xDA
Definition at line 65 of file SSD1306.h.
#define SSD1306_SETCONTRAST 0x81
Display commands
Definition at line 56 of file SSD1306.h.
#define SSD1306_SETDISPLAYCLOCKDIV 0xD5
Definition at line 69 of file SSD1306.h.
#define SSD1306_SETDISPLAYOFFSET 0xD3
Definition at line 64 of file SSD1306.h.
#define SSD1306_SETHIGHCOLUMN 0x10
Definition at line 75 of file SSD1306.h.
#define SSD1306_SETLOWCOLUMN 0x00
Definition at line 74 of file SSD1306.h.
#define SSD1306_SETMULTIPLEX 0xA8
Definition at line 72 of file SSD1306.h.
#define SSD1306_SETPRECHARGE 0xD9
Definition at line 70 of file SSD1306.h.
#define SSD1306_SETSTARTLINE 0x40
Definition at line 77 of file SSD1306.h.
#define SSD1306_SETVCOMDETECT 0xDB
Definition at line 67 of file SSD1306.h.
#define SSD1306_SPI3 1<<4
Definition at line 42 of file SSD1306.h.
#define SSD1306_SPI4 1<<5
Definition at line 43 of file SSD1306.h.
#define SSD1306_SWITCHCAPVCC 0x2
Definition at line 90 of file SSD1306.h.
#define SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL 0x2A
Definition at line 99 of file SSD1306.h.
#define SSD1306_VERTICAL_AND_RIGHT_HORIZONTAL_SCROLL 0x29
Definition at line 98 of file SSD1306.h.
#define Yellow 0xFFE0
Definition at line 126 of file SSD1306.h.
Function Documentation
void drawPixel (u16 x, u16 y)
Definition at line 960 of file ili9325.c.
References ILI9325_drawPixel(), and SSD1306_drawPixel().
{
    ILI9325_drawPixel(x, y);
}
void SSD1306_clearPixel (u8 x, u8 y)
Definition at line 883 of file SSD1306.c.
References DISPLAY_HEIGHT, DISPLAY_ROWS, DISPLAY_WIDTH, and SSD1306_buffer.
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    
    SSD1306_buffer[x + (y / DISPLAY_ROWS) *
      DISPLAY_WIDTH] &= ~(1 << (y % DISPLAY_ROWS));
}
void SSD1306_clearScreen (void)
Clear the display
Definition at line 500 of file SSD1306.c.
References lcd_t::cursor, DISPLAY_SIZE, coord_t::page, SSD1306, SSD1306_buffer, coord_t::x, and coord_t::y.
{
    u16 i;
    for (i = 0; i < DISPLAY_SIZE; i++)
        SSD1306_buffer[i] = 0;
        
    SSD1306.cursor.x = 0;
    SSD1306.cursor.y = 0;
    SSD1306.cursor.page = 0;
}
void SSD1306_displayOff ()
Basic functions (TODO : replace functions with #define)
Definition at line 239 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xAE);
}
void SSD1306_displayOn ()
Definition at line 244 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xAF);
}
void SSD1306_drawBitmap (u16 x, u16 y, u16 w, u16 h, u16 * bitmap)
void SSD1306_drawCircle (u16 x, u16 y, u16 radius)
Definition at line 948 of file SSD1306.c.
References drawCircle().
{
    drawCircle(x, y, radius);
}
void SSD1306_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Definition at line 958 of file SSD1306.c.
References drawLine().
{
    drawLine(x0, y0, x1, y1);
}
void SSD1306_drawPixel (u8 x, u8 y)
Definition at line 876 of file SSD1306.c.
References DISPLAY_HEIGHT, DISPLAY_ROW_BITS, DISPLAY_ROWS, DISPLAY_WIDTH, and SSD1306_buffer.
Referenced by drawPixel().
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    SSD1306_buffer[x + (y / DISPLAY_ROWS) *
      DISPLAY_WIDTH] |= 1 << (y % DISPLAY_ROWS);
}
void SSD1306_fillCircle (u16 x, u16 y, u16 radius)
Definition at line 953 of file SSD1306.c.
References fillCircle().
{
    fillCircle(x, y, radius);
}
u8 SSD1306_getColor (u8 x, u8 y)
Definition at line 900 of file SSD1306.c.
References DISPLAY_ROW_BITS, DISPLAY_ROW_MASK, DISPLAY_WIDTH_BITS, DISPLAY_WIDTH_MASK, page, and SSD1306_bufferptr.
{
    u8 column,temp,bit_mask;//page;
    unsigned int page;
    u8* GDptr = SSD1306_bufferptr;
   
    // Convert coordinates
    column = x & DISPLAY_WIDTH_MASK; // 0-128
    //page = (y>>DISPLAY_ROW_BITS)&DISPLAY_ROW_MASK; // 0-8
    temp = y & DISPLAY_ROW_MASK;
    bit_mask = 1<<temp;
    //GDptr+= column+(DISPLAY_WIDTH*page);
    // Optimise
    page = (y << (DISPLAY_WIDTH_BITS - DISPLAY_ROW_BITS)); // 0-8 * 128
    GDptr += column+page;
    // Set the bit
    if (*GDptr & bit_mask) // Pixel on
    {
            return 1;
    }
    else // Pixel off
    {
            return 0;
    }
}
void SSD1306_hvSetColumnAddress (u8 start, u8 end)
Definition at line 318 of file SSD1306.c.
References DISPLAY_WIDTH_MASK, and SSD1306_sendCommand().
Referenced by SSD1306_init(), and SSD1306_refresh().
{
    SSD1306_sendCommand(0x21);
    SSD1306_sendCommand(start & DISPLAY_WIDTH_MASK);
    SSD1306_sendCommand(end & DISPLAY_WIDTH_MASK);
}
void SSD1306_hvSetPageAddress (u8 start, u8 end)
Definition at line 325 of file SSD1306.c.
References DISPLAY_ROW_MASK, and SSD1306_sendCommand().
Referenced by SSD1306_init(), and SSD1306_refresh().
{
    SSD1306_sendCommand(0x22);
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
}
void SSD1306_init ()
reset device When RES input is low, the chip is initialized with the following status:
Display is OFF.
128x64 MUX Display Mode.
Normal segment and display data column address and row address mapping (SEG0 mapped to address 00h and COM0 mapped to address 00h).
Shift register data clear in serial interface.
Display start line is set at display RAM address 0.
Column address counter is set at 0.
Normal scan direction of the COM outputs.
Contrast control register is set at 7Fh.
Normal display mode (Equivalent to A4h command)
Definition at line 357 of file SSD1306.c.
References lcd_t::cursor, Delayms(), Delayus(), DISPLAY_HEIGHT, DISPLAY_WIDTH, rect_t::endx, rect_t::endy, rect_t::height, coord_t::page, PMA1, PMP_ACTIVE_LOW, PMP_autoIncrement(), PMP_init(), PMP_MODE_8BIT, PMP_MODE_MASTER1, PMP_MODE_MASTER2, PMP_MUX_OFF, PMP_setAddress(), PMP_setControl(), PMP_setMode(), PMP_setMux(), PMP_setPolarity(), PMP_setWaitStates(), PMP_setWidth(), PMRD, lcd_t::screen, SSD1306, SSD1306_displayOff(), SSD1306_displayOn(), SSD1306_hvSetColumnAddress(), SSD1306_hvSetPageAddress(), SSD1306_pamSetPageStart(), SSD1306_pamSetStartAddress(), SSD1306_setChargePumpEnable(), SSD1306_setComOutputScanDirection(), SSD1306_setComPinsHardwareConfiguration(), SSD1306_setContrast(), SSD1306_setDisplayClockRatioAndFrequency(), SSD1306_setDisplayOffset(), SSD1306_setDisplayStartLine(), SSD1306_setInverse(), SSD1306_setMemoryAddressingMode(), SSD1306_setMultiplexRatio(), SSD1306_setPrechargePeriod(), SSD1306_setSegmentRemap(), SSD1306_setVcomhDeselectLevel(), SSD1306_wake(), rect_t::startx, rect_t::starty, rect_t::width, coord_t::x, and coord_t::y.
{
    #if (DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080)
        #if (DISPLAY & SSD1306_PMP)
            High(RST);
            Output(RST);
            #if (DISPLAY & SSD1306_6800)
            PMP_setMode(PMP_MODE_MASTER1); // Master mode 1 : PMCS1,
       PMRD/PMWR, PMENB
            #elif (DISPLAY & SSD1306_8080)
            PMP_setMode(PMP_MODE_MASTER2); // Master mode 2 : PMCS1, PMRD,
       PMWR
            #endif
            PMP_setWidth(PMP_MODE_8BIT); // PMD<7:0>
            PMP_setMux(PMP_MUX_OFF); // PMA and PMD on separate lines
            PMP_setPolarity(PMP_ACTIVE_LOW);
            PMP_setAddress(PMA1); // PMA1 as DC
            PMP_autoIncrement(0);
            PMP_setControl(PMRD); // PMRD as WR
            PMP_setWaitStates(4, 16, 4); // WR strobe must be at least 60ns
            PMP_init();
        #else
            dDATA = 0x00; // output
            dCMD = 0x00; // output
            DATA = 0x00;
            CMD = 0xFF; // every pin HIGH
        #endif
    #elif (DISPLAY & SSD1306_SPI3) || (DISPLAY & SSD1306_SPI4)
        // TODO
    #elif (DISPLAY & SSD1306_I2C)
        // TODO
    #endif
    // default Screen Values
    //SSD1306.orientation = PORTRAIT;
    SSD1306.cursor.x = 0;
    SSD1306.cursor.y = 0;
    SSD1306.cursor.page = 0;
    SSD1306.screen.startx = 0;
    SSD1306.screen.starty = 0;
    SSD1306.screen.endx = DISPLAY_WIDTH - 1;
    SSD1306.screen.endy = DISPLAY_HEIGHT - 1;
    SSD1306.screen.width = DISPLAY_WIDTH;
    SSD1306.screen.height = DISPLAY_HEIGHT;
    Low(RST); // initialized the chip
    Delayus(50); // for at least 3us
    High(RST);
    SSD1306_displayOn();
    Delayms(100); // wait for SEG/COM to be ON
    SSD1306_displayOff();
    SSD1306_setDisplayClockRatioAndFrequency(0, 8);
    SSD1306_setMultiplexRatio(0x3F); // 1/64 duty
    SSD1306_setPrechargePeriod(0xF, 0x01);
    SSD1306_setDisplayOffset(0);
    SSD1306_setDisplayStartLine(0);
    SSD1306_setChargePumpEnable(1);
    SSD1306_setMemoryAddressingMode(0); // horizontal addressing mode;
       across then down
    SSD1306_setSegmentRemap(1);
    SSD1306_setComOutputScanDirection(1);
    SSD1306_setComPinsHardwareConfiguration(1, 0);
    SSD1306_setContrast(0xFF);
    SSD1306_setVcomhDeselectLevel(1);
    SSD1306_wake();
    SSD1306_setInverse(0);
    SSD1306_hvSetColumnAddress(0, 127);
    SSD1306_hvSetPageAddress(0, 7);
    SSD1306_pamSetStartAddress(0);
    SSD1306_pamSetPageStart(0);
    // SSD1306_setPrechargePeriod(2, 2);
}
void SSD1306_nop ()
Definition at line 355 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xE3);
}
void SSD1306_pamSetPageStart (u8 address)
Definition at line 332 of file SSD1306.c.
References DISPLAY_ROW_MASK, and SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xB0 | (address & DISPLAY_ROW_MASK));
}
void SSD1306_pamSetStartAddress (u8 address)
Definition at line 303 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    // "Set Lower Column Start Address for Page Addressing Mode"
    SSD1306_sendCommand(address & 0x0F);
    // "Set Higher Column Start Address for Page Addressing Mode"
    SSD1306_sendCommand((address << 4) & 0x0F);
}
void SSD1306_print (u8 * string)
void SSD1306_printChar (u8 c)
Definition at line 662 of file SSD1306.c.
References font_t::address, lcd_t::cursor, DISPLAY_WIDTH, lcd_t::font, SSD1306, SSD1306_buffer, SSD1306_scrollUp(), font_t::width, coord_t::x, and coord_t::y.
{
    u8 b;
    while (SSD1306.cursor.x >= (DISPLAY_WIDTH /
      SSD1306.font.width))
    {
        SSD1306.cursor.x -= (DISPLAY_WIDTH / SSD1306.
      font.width);
        SSD1306.cursor.y++;
    }
    while (SSD1306.cursor.y > 7) // replace by SSD1306.font.height ???
    {
        SSD1306_scrollUp();
    }
    switch (c)
    {
        case '\n':
            SSD1306.cursor.y++;
            break;
            
        case '\r':
            SSD1306.cursor.x = 0;
            break;
            
        case '\t':
            SSD1306.cursor.x = (SSD1306.cursor.x + 4) % 4;
            break;
            
        default:
            for (b = 0; b < SSD1306.font.width; b++)
            {
                SSD1306_buffer[SSD1306.cursor.x *
      SSD1306.font.width + SSD1306.cursor.y * 128 + b] =
                    SSD1306.font.address[2 + (c - 32) *
      SSD1306.font.width + b];
            }
        
        SSD1306.cursor.x++;
    }
}
void SSD1306_printf (const u8 * fmt, ...)
void SSD1306_printFloat (float number, u8 digits)
void SSD1306_println (u8 * string)
void SSD1306_printNumber (long value, u8 base)
void SSD1306_refresh ()
Update the display
Definition at line 485 of file SSD1306.c.
References DISPLAY_ROWS, DISPLAY_SIZE, DISPLAY_WIDTH, SSD1306_buffer, SSD1306_hvSetColumnAddress(), SSD1306_hvSetPageAddress(), and SSD1306_sendData().
{
    u16 i;
    SSD1306_hvSetColumnAddress(0, DISPLAY_WIDTH-1);
    SSD1306_hvSetPageAddress(0, DISPLAY_ROWS-1);
    for (i = 0; i < DISPLAY_SIZE; i++)
        SSD1306_sendData(SSD1306_buffer[i]);
}
void SSD1306_scrollDown ()
Definition at line 635 of file SSD1306.c.
References SSD1306_startVerticalAndHorizontalScroll(), and SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL.
{
    SSD1306_startVerticalAndHorizontalScroll(
      SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL, 0, 64, 0, 1);
}
void SSD1306_scrollLeft ()
Definition at line 606 of file SSD1306.c.
References SSD1306_LEFT_HORIZONTAL_SCROLL, and SSD1306_startHorizontalScroll().
{
    SSD1306_startHorizontalScroll(
      SSD1306_LEFT_HORIZONTAL_SCROLL, 0, 7, 2);
}
void SSD1306_scrollRight ()
Definition at line 599 of file SSD1306.c.
References SSD1306_RIGHT_HORIZONTAL_SCROLL, and SSD1306_startHorizontalScroll().
{
    SSD1306_startHorizontalScroll(
      SSD1306_RIGHT_HORIZONTAL_SCROLL, 0, 7, 2);
}
void SSD1306_scrollUp ()
Definition at line 613 of file SSD1306.c.
References lcd_t::cursor, SSD1306, SSD1306_buffer, x, coord_t::y, and y.
Referenced by SSD1306_printChar().
{
    u8 x, y;
    for (y = 1; y <= 7; y++)
    {
        for (x = 0; x < 128; x++)
        {
            SSD1306_buffer[x + 128 * (y - 1)] = SSD1306_buffer[x + 128 * y];
        }
    }
    for (x = 0; x < 128; x++)
    {
        SSD1306_buffer[x + 128 * 7] = 0;
    }
    SSD1306.cursor.y--;
}
void SSD1306_sendCommand (u8 val)
Prototypes
Core functions
The parallel 6800-series interface consists of : 8 bi-directional data pins (D[7:0]) R/W#, D/C#, E and CS#. A LOW in R/W# indicates WRITE operation A HIGH in R/W# indicates READ operation. A LOW in D/C# indicates COMMAND read/write A HIGH in D/C# indicates DATA read/write. The E input serves as data latch signal while CS# is LOW. Data is latched at the falling edge of E signal.
The parallel 8080-series interface consists of : 8 bi-directional data pins (DB[7:0]) RD#, WR#, DC# and CS#. A LOW in DC# indicates COMMAND read/write A HIGH in DC# indicates DATA read/write. A rising edge of RD# input serves as a data READ latch signal while CS# is kept LOW. A rising edge of WR# input serves as a data/command WRITE latch signal while CS# is kept LOW.
Globals
Core functions
The parallel 6800-series interface consists of : 8 bi-directional data pins (D[7:0]) R/W#, D/C#, E and CS#. A LOW in R/W# indicates WRITE operation A HIGH in R/W# indicates READ operation. A LOW in D/C# indicates COMMAND read/write A HIGH in D/C# indicates DATA read/write. The E input serves as data latch signal while CS# is LOW. Data is latched at the falling edge of E signal.
The parallel 8080-series interface consists of : 8 bi-directional data pins (DB[7:0]) RD#, WR#, DC# and CS#. A LOW in DC# indicates COMMAND read/write A HIGH in DC# indicates DATA read/write. A rising edge of RD# input serves as a data READ latch signal while CS# is kept LOW. A rising edge of WR# input serves as a data/command WRITE latch signal while CS# is kept LOW.
Definition at line 135 of file SSD1306.c.
References E, and PMP_wait.
Referenced by SSD1306_displayOff(), SSD1306_displayOn(), SSD1306_hvSetColumnAddress(), SSD1306_hvSetPageAddress(), SSD1306_nop(), SSD1306_pamSetPageStart(), SSD1306_pamSetStartAddress(), SSD1306_setChargePumpEnable(), SSD1306_setComOutputScanDirection(), SSD1306_setComPinsHardwareConfiguration(), SSD1306_setContrast(), SSD1306_setDisplayClockRatioAndFrequency(), SSD1306_setDisplayOffset(), SSD1306_setDisplayStartLine(), SSD1306_setInverse(), SSD1306_setMemoryAddressingMode(), SSD1306_setMultiplexRatio(), SSD1306_setPrechargePeriod(), SSD1306_setSegmentRemap(), SSD1306_setVcomhDeselectLevel(), SSD1306_sleep(), SSD1306_startHorizontalScroll(), SSD1306_startVerticalAndHorizontalScroll(), SSD1306_stopScroll(), and SSD1306_wake().
{
    #if (DISPLAY & SSD1306_PMP)
        #if ((DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080))
            PMP_wait(); // wait for PMP to be available
            PMADDRH = 0;
            PMADDRL = 0;
            PMDIN1L = val;
            
        #else
            #error " --------------------------------------- "
            #error " The Parallel Port can only drive the "
            #error " 6800 or 8080 parallel interface. "
            #error " --------------------------------------- "
        #endif
    #else
        #if (DISPLAY & SSD1306_8080)
            Low(CS); // Chip select
            Low(DC); // COMMAND read/write
            Low(WR);
            DATA = val; // WR should stay low at least 60ns
            High(WR); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #elif (DISPLAY & SSD1306_6800)
            Low(CS); // Chip select
            Low(WR); // WRITE
            Low(DC); // COMMAND
            High(E);
            DATA = val; // WR should stay low at least 60ns
            Low(E); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #endif
    #endif
}
void SSD1306_sendData (u8 _data)
Definition at line 185 of file SSD1306.c.
References E, and PMP_wait.
Referenced by SSD1306_refresh().
{
    #if (DISPLAY & SSD1306_PMP)
        #if ((DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080))
            PMP_wait(); // wait for PMP to be available
            PMADDRH = 0; // High8(DC);
            PMADDRL = DC; // low8(DC);
            PMDIN1L = val;
            
        #else
            #error " --------------------------------------- "
            #error " The Parallel Port can only drive the "
            #error " 6800 or 8080 parallel interface. "
            #error " --------------------------------------- "
        #endif
    #else
        #if (DISPLAY & SSD1306_8080)
            Low(CS); // Chip select
            High(DC); // DATA read/write
            Low(WR);
            DATA = val; // WR should stay low at least 60ns
            High(WR); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #elif (DISPLAY & SSD1306_6800)
            Low(CS); // Chip select
            Low(WR); // WRITE
            High(DC); // DATA
            High(E);
            DATA = val; // WR should stay low at least 60ns
            Low(E); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #endif
    #endif
}
void SSD1306_setChargePumpEnable (u8 enable)
Definition at line 360 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x8D);
    SSD1306_sendCommand(enable ? 0x14 : 0x10);
}
void SSD1306_setComOutputScanDirection (u8 value)
Definition at line 292 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(value ? 0xC8 : 0xC0);
}
void SSD1306_setComPinsHardwareConfiguration (u8 sequential, u8 lr_remap)
Definition at line 297 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xDA);
    SSD1306_sendCommand(0x02 | ((sequential & 1) << 4) | ((lr_remap & 1) << 5));
}
void SSD1306_setContrast (u8 value)
Definition at line 270 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x81);
    SSD1306_sendCommand(value);
}
void SSD1306_setCursor (u8 x, u8 y)
Graphic functions
Definition at line 858 of file SSD1306.c.
References lcd_t::cursor, DISPLAY_HEIGHT, DISPLAY_ROW_MASK, DISPLAY_WIDTH, coord_t::page, SSD1306, coord_t::x, x, coord_t::y, and y.
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    SSD1306.cursor.x = x;
    SSD1306.cursor.y = y;
    SSD1306.cursor.page = x & DISPLAY_ROW_MASK; // current page
}
void SSD1306_setDisplayClockRatioAndFrequency (u8 ratio, u8 frequency)
Definition at line 337 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xD5);
    SSD1306_sendCommand((ratio & 0x0F) | ((frequency & 0x0F) << 4));
}
void SSD1306_setDisplayOffset (u8 value)
Definition at line 264 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xD3);
    SSD1306_sendCommand(value & 0x3F);
}
void SSD1306_setDisplayStartLine (u8 value)
Definition at line 276 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x40 | value);
}
void SSD1306_setFont (const u8 * font)
Print functions
Definition at line 625 of file SSD1306.c.
References font_t::address, font, lcd_t::font, font_t::height, SSD1306, and font_t::width.
{
    SSD1306.font.address = font;
    //SSD1306.font.width = SSD1306_getFontWidth()+1;
    //SSD1306.font.height = SSD1306_getFontHeight();
    SSD1306.font.width = font[0];
    SSD1306.font.height = font[1];
}
void SSD1306_setInverse (u8 value)
Definition at line 259 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(value ? 0xA7 : 0xA6);
}
void SSD1306_setMemoryAddressingMode (u8 mode)
Definition at line 312 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x20);
    SSD1306_sendCommand(mode & 0x3);
}
void SSD1306_setMultiplexRatio (u8 value)
Definition at line 286 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xA8);
    SSD1306_sendCommand(value & 0x3F);
}
void SSD1306_setPrechargePeriod (u8 phase1, u8 phase2)
Definition at line 343 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xD9);
    SSD1306_sendCommand((phase1 & 0x0F) | ((phase2 & 0x0F) << 4));
}
void SSD1306_setSegmentRemap (u8 value)
Definition at line 281 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(value ? 0xA1 : 0xA0);
}
void SSD1306_setVcomhDeselectLevel (u8 level)
Definition at line 349 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xDB);
    SSD1306_sendCommand((level & 0x03) << 4);
}
void SSD1306_sleep ()
Definition at line 249 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xAE);
}
void SSD1306_startHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval)
Scroll functions
Definition at line 516 of file SSD1306.c.
References DISPLAY_ROW_MASK, SSD1306_ACTIVATE_SCROLL, and SSD1306_sendCommand().
Referenced by SSD1306_scrollLeft(), and SSD1306_scrollRight().
{
    // Before issuing this command the horizontal scroll must be deactivated (2Eh).
    // Otherwise, RAM content may be corrupted.
    // RB : this datasheet recommandation doesn't work
    //SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
    SSD1306_sendCommand(direction);// ? 0x27 : 0x26);
    // Dummy byte (???)
    SSD1306_sendCommand(0x00);
    // Start page
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    // Time interval between each scroll step
    switch (interval)
    {
        case 2: SSD1306_sendCommand(0x07); break; // 111b
        case 3: SSD1306_sendCommand(0x04); break; // 100b
        case 4: SSD1306_sendCommand(0x05); break; // 101b
        case 5: SSD1306_sendCommand(0x00); break; // 000b
        case 25: SSD1306_sendCommand(0x06); break; // 110b
        case 64: SSD1306_sendCommand(0x01); break; // 001b
        case 128: SSD1306_sendCommand(0x02); break; // 010b
        case 256: SSD1306_sendCommand(0x03); break; // 011b
        default: SSD1306_sendCommand(0x07); break; // default to 2 frame interval
    }
    
    // End page
    //SSD1306_sendCommand(0x00);
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
    // ???
    SSD1306_sendCommand(0x00);
    SSD1306_sendCommand(0xFF);
    // activate scroll
    SSD1306_sendCommand(SSD1306_ACTIVATE_SCROLL);
}
void SSD1306_startVerticalAndHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval, u8 vertical_offset)
Definition at line 555 of file SSD1306.c.
References DISPLAY_ROW_MASK, SSD1306_ACTIVATE_SCROLL, and SSD1306_sendCommand().
Referenced by SSD1306_scrollDown().
{
    // Before issuing this command the horizontal scroll must be deactivated (2Eh).
    // Otherwise, RAM content may be corrupted.
    // RB : this datasheet recommandation doesn't work
    //SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
    SSD1306_sendCommand(direction); // ? 0x2A : 0x29);
    // Dummy byte (???)
    SSD1306_sendCommand(0x00);
    // Start page
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    // Time interval between each scroll step
    switch (interval)
    {
        case 2: SSD1306_sendCommand(0x07); break; // 111b
        case 3: SSD1306_sendCommand(0x04); break; // 100b
        case 4: SSD1306_sendCommand(0x05); break; // 101b
        case 5: SSD1306_sendCommand(0x00); break; // 000b
        case 25: SSD1306_sendCommand(0x06); break; // 110b
        case 64: SSD1306_sendCommand(0x01); break; // 001b
        case 128: SSD1306_sendCommand(0x02); break; // 010b
        case 256: SSD1306_sendCommand(0x03); break; // 011b
        default: SSD1306_sendCommand(0x07); break; // default to 2 frame interval
    }
    // End page
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
    SSD1306_sendCommand(vertical_offset);
    // activate scroll
    SSD1306_sendCommand(SSD1306_ACTIVATE_SCROLL);
}
void SSD1306_stopScroll ()
Definition at line 591 of file SSD1306.c.
References SSD1306_DEACTIVATE_SCROLL, and SSD1306_sendCommand().
{
    // all scroll configurations are removed from the display when executing this command.
    SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
}
void SSD1306_wake ()
Definition at line 254 of file SSD1306.c.
References SSD1306_sendCommand().
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xAF);
}
Variable Documentation
lcd_t SSD1306
Globals
Definition at line 248 of file SSD1306.h.
u8* SSD1306_bufferptr
Definition at line 251 of file SSD1306.h.