/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/SSD1306.c File Reference
#include <SSD1306.h>
*
#include <pinguino128x32.h>
*
#include <digitalw.c>
*
#include <typedef.h>
*
#include <macro.h>
*
#include <delay.c>
*
#include <string.h>
*
#include <graphics.c>
*
Macros
#define __SSD1306_C
Functions
void SSD1306_sendCommand (u8 val)
void SSD1306_sendData (u8 val)
void SSD1306_displayOff ()
void SSD1306_displayOn ()
void SSD1306_sleep ()
void SSD1306_wake ()
void SSD1306_setInverse (u8 value)
void SSD1306_setDisplayOffset (u8 value)
void SSD1306_setContrast (u8 value)
void SSD1306_setDisplayStartLine (u8 value)
void SSD1306_setSegmentRemap (u8 value)
void SSD1306_setMultiplexRatio (u8 value)
void SSD1306_setComOutputScanDirection (u8 value)
void SSD1306_setComPinsHardwareConfiguration (u8 sequential, u8 lr_remap)
void SSD1306_pamSetStartAddress (u8 address)
void SSD1306_setMemoryAddressingMode (u8 mode)
void SSD1306_hvSetColumnAddress (u8 start, u8 end)
void SSD1306_hvSetPageAddress (u8 start, u8 end)
void SSD1306_pamSetPageStart (u8 address)
void SSD1306_setDisplayClockRatioAndFrequency (u8 ratio, u8 frequency)
void SSD1306_setPrechargePeriod (u8 phase1, u8 phase2)
void SSD1306_setVcomhDeselectLevel (u8 level)
void SSD1306_nop ()
void SSD1306_setChargePumpEnable (u8 enable)
void SSD1306_init ()
void SSD1306_refresh ()
void SSD1306_clearScreen (void)
void SSD1306_startHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval)
void SSD1306_startVerticalAndHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval, u8 vertical_offset)
void SSD1306_stopScroll ()
void SSD1306_scrollRight ()
void SSD1306_scrollLeft ()
void SSD1306_scrollUp ()
void SSD1306_scrollDown ()
void SSD1306_setFont (const u8 *font)
void SSD1306_printChar (u8 c)
void SSD1306_setCursor (u8 x, u8 y)
void SSD1306_drawPixel (u8 x, u8 y)
void SSD1306_clearPixel (u8 x, u8 y)
u8 SSD1306_getColor (u8 x, u8 y)
void drawPixel (u16 x, u16 y)
void SSD1306_drawCircle (u16 x, u16 y, u16 radius)
void SSD1306_fillCircle (u16 x, u16 y, u16 radius)
void SSD1306_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Macro Definition Documentation
#define __SSD1306_C
Pin Assignment
1 VCC | 2 GND 3 CS | 4 RES 5 D/C | 6 R/W 7 E/RD | 8 D0 9 D1 | 10 D2 11 D3 | 12 D4 13 D5 | 14 D6 15 D7 | 16 NC Bus Interface
    I2C     6800    8080    4-SPI   3-SPI
 BS0 0 0 0 0 1 BS1 1 0 1 0 0 BS2 0 1 1 0 0
Definition at line 55 of file SSD1306.c.
Function Documentation
void drawPixel (u16 x, u16 y)
Definition at line 919 of file SSD1306.c.
References ILI9325_drawPixel(), and SSD1306_drawPixel().
Referenced by drawBitmap(), drawCircle(), drawLine(), and fillCircle().
{
    SSD1306_drawPixel(x, y);
}
void SSD1306_clearPixel (u8 x, u8 y)
Definition at line 865 of file SSD1306.c.
References DISPLAY_HEIGHT, DISPLAY_ROWS, DISPLAY_WIDTH, and SSD1306_buffer.
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    
    SSD1306_buffer[x + (y / DISPLAY_ROWS) *
      DISPLAY_WIDTH] &= ~(1 << (y % DISPLAY_ROWS));
}
void SSD1306_clearScreen (void)
Clear the display
Definition at line 478 of file SSD1306.c.
References lcd_t::cursor, DISPLAY_SIZE, coord_t::page, SSD1306, SSD1306_buffer, coord_t::x, and coord_t::y.
{
    u16 i;
/*
    for (i = 0; i < DISPLAY_SIZE; i++)
        SSD1306_buffer[i] = 0;
*/
    memset(SSD1306_buffer, 0, DISPLAY_SIZE);
    SSD1306.cursor.x = 0;
    SSD1306.cursor.y = 0;
    SSD1306.cursor.page = 0;
}
void SSD1306_displayOff ()
Basic functions (TODO : replace functions with #define)
Definition at line 221 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xAE);
}
void SSD1306_displayOn ()
Definition at line 226 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xAF);
}
void SSD1306_drawCircle (u16 x, u16 y, u16 radius)
Definition at line 924 of file SSD1306.c.
References drawCircle().
{
    drawCircle(x, y, radius);
}
void SSD1306_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Definition at line 934 of file SSD1306.c.
References drawLine().
{
    drawLine(x0, y0, x1, y1);
}
void SSD1306_drawPixel (u8 x, u8 y)
Definition at line 857 of file SSD1306.c.
References DISPLAY_HEIGHT, DISPLAY_ROW_BITS, DISPLAY_ROWS, DISPLAY_WIDTH, and SSD1306_buffer.
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    SSD1306_buffer[x + (y>>DISPLAY_ROW_BITS) *
      DISPLAY_WIDTH] |= 1 << (y % DISPLAY_ROWS);
    //SSD1306_buffer[x + (y / DISPLAY_ROWS) * DISPLAY_WIDTH] |= 1 << (y % DISPLAY_ROWS);
}
void SSD1306_fillCircle (u16 x, u16 y, u16 radius)
Definition at line 929 of file SSD1306.c.
References fillCircle().
{
    fillCircle(x, y, radius);
}
u8 SSD1306_getColor (u8 x, u8 y)
Definition at line 882 of file SSD1306.c.
References DISPLAY_ROW_BITS, DISPLAY_ROW_MASK, DISPLAY_WIDTH_BITS, DISPLAY_WIDTH_MASK, page, and SSD1306_bufferptr.
{
    u8 column,temp,bit_mask;//page;
    unsigned int page;
    u8* GDptr = SSD1306_bufferptr;
   
    // Convert coordinates
    column = x & DISPLAY_WIDTH_MASK; // 0-128
    //page = (y>>DISPLAY_ROW_BITS)&DISPLAY_ROW_MASK; // 0-8
    temp = y & DISPLAY_ROW_MASK;
    bit_mask = 1<<temp;
    //GDptr+= column+(DISPLAY_WIDTH*page);
    // Optimise
    page = (y << (DISPLAY_WIDTH_BITS - DISPLAY_ROW_BITS)); // 0-8 * 128
    GDptr += column+page;
    // Set the bit
    if (*GDptr & bit_mask) // Pixel on
    {
            return 1;
    }
    else // Pixel off
    {
            return 0;
    }
}
void SSD1306_hvSetColumnAddress (u8 start, u8 end)
Definition at line 300 of file SSD1306.c.
References DISPLAY_WIDTH_MASK, and SSD1306_sendCommand().
{
    SSD1306_sendCommand(0x21);
    SSD1306_sendCommand(start & DISPLAY_WIDTH_MASK);
    SSD1306_sendCommand(end & DISPLAY_WIDTH_MASK);
}
void SSD1306_hvSetPageAddress (u8 start, u8 end)
Definition at line 307 of file SSD1306.c.
References DISPLAY_ROW_MASK, and SSD1306_sendCommand().
{
    SSD1306_sendCommand(0x22);
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
}
void SSD1306_init ()
reset device When RES input is low, the chip is initialized with the following status:
Display is OFF.
128x64 MUX Display Mode.
Normal segment and display data column address and row address mapping (SEG0 mapped to address 00h and COM0 mapped to address 00h).
Shift register data clear in serial interface.
Display start line is set at display RAM address 0.
Column address counter is set at 0.
Normal scan direction of the COM outputs.
Contrast control register is set at 7Fh.
Normal display mode (Equivalent to A4h command)
Definition at line 357 of file SSD1306.c.
References lcd_t::cursor, Delayms(), Delayus(), DISPLAY_HEIGHT, DISPLAY_WIDTH, rect_t::endx, rect_t::endy, rect_t::height, coord_t::page, PMA1, PMP_ACTIVE_LOW, PMP_autoIncrement(), PMP_init(), PMP_MODE_8BIT, PMP_MODE_MASTER1, PMP_MODE_MASTER2, PMP_MUX_OFF, PMP_setAddress(), PMP_setControl(), PMP_setMode(), PMP_setMux(), PMP_setPolarity(), PMP_setWaitStates(), PMP_setWidth(), PMRD, lcd_t::screen, SSD1306, SSD1306_displayOff(), SSD1306_displayOn(), SSD1306_hvSetColumnAddress(), SSD1306_hvSetPageAddress(), SSD1306_pamSetPageStart(), SSD1306_pamSetStartAddress(), SSD1306_setChargePumpEnable(), SSD1306_setComOutputScanDirection(), SSD1306_setComPinsHardwareConfiguration(), SSD1306_setContrast(), SSD1306_setDisplayClockRatioAndFrequency(), SSD1306_setDisplayOffset(), SSD1306_setDisplayStartLine(), SSD1306_setInverse(), SSD1306_setMemoryAddressingMode(), SSD1306_setMultiplexRatio(), SSD1306_setPrechargePeriod(), SSD1306_setSegmentRemap(), SSD1306_setVcomhDeselectLevel(), SSD1306_wake(), rect_t::startx, rect_t::starty, rect_t::width, coord_t::x, and coord_t::y.
{
    #if (DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080)
        #if (DISPLAY & SSD1306_PMP)
            High(RST);
            Output(RST);
            #if (DISPLAY & SSD1306_6800)
            PMP_setMode(PMP_MODE_MASTER1); // Master mode 1 : PMCS1,
       PMRD/PMWR, PMENB
            #elif (DISPLAY & SSD1306_8080)
            PMP_setMode(PMP_MODE_MASTER2); // Master mode 2 : PMCS1, PMRD,
       PMWR
            #endif
            PMP_setWidth(PMP_MODE_8BIT); // PMD<7:0>
            PMP_setMux(PMP_MUX_OFF); // PMA and PMD on separate lines
            PMP_setPolarity(PMP_ACTIVE_LOW);
            PMP_setAddress(PMA1); // PMA1 as DC
            PMP_autoIncrement(0);
            PMP_setControl(PMRD); // PMRD as WR
            PMP_setWaitStates(4, 16, 4); // WR strobe must be at least 60ns
            PMP_init();
        #else
            dDATA = 0x00; // output
            dCMD = 0x00; // output
            DATA = 0x00;
            CMD = 0xFF; // every pin HIGH
        #endif
    #elif (DISPLAY & SSD1306_SPI3) || (DISPLAY & SSD1306_SPI4)
        // TODO
    #elif (DISPLAY & SSD1306_I2C)
        // TODO
    #endif
    // default Screen Values
    //SSD1306.orientation = PORTRAIT;
    SSD1306.cursor.x = 0;
    SSD1306.cursor.y = 0;
    SSD1306.cursor.page = 0;
    SSD1306.screen.startx = 0;
    SSD1306.screen.starty = 0;
    SSD1306.screen.endx = DISPLAY_WIDTH - 1;
    SSD1306.screen.endy = DISPLAY_HEIGHT - 1;
    SSD1306.screen.width = DISPLAY_WIDTH;
    SSD1306.screen.height = DISPLAY_HEIGHT;
    Low(RST); // initialized the chip
    Delayus(50); // for at least 3us
    High(RST);
    SSD1306_displayOn();
    Delayms(100); // wait for SEG/COM to be ON
    SSD1306_displayOff();
    SSD1306_setDisplayClockRatioAndFrequency(0, 8);
    SSD1306_setMultiplexRatio(0x3F); // 1/64 duty
    SSD1306_setPrechargePeriod(0xF, 0x01);
    SSD1306_setDisplayOffset(0);
    SSD1306_setDisplayStartLine(0);
    SSD1306_setChargePumpEnable(1);
    SSD1306_setMemoryAddressingMode(0); // horizontal addressing mode;
       across then down
    SSD1306_setSegmentRemap(1);
    SSD1306_setComOutputScanDirection(1);
    SSD1306_setComPinsHardwareConfiguration(1, 0);
    SSD1306_setContrast(0xFF);
    SSD1306_setVcomhDeselectLevel(1);
    SSD1306_wake();
    SSD1306_setInverse(0);
    SSD1306_hvSetColumnAddress(0, 127);
    SSD1306_hvSetPageAddress(0, 7);
    SSD1306_pamSetStartAddress(0);
    SSD1306_pamSetPageStart(0);
    // SSD1306_setPrechargePeriod(2, 2);
}
void SSD1306_nop ()
Definition at line 337 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xE3);
}
void SSD1306_pamSetPageStart (u8 address)
Definition at line 314 of file SSD1306.c.
References DISPLAY_ROW_MASK, and SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xB0 | (address & DISPLAY_ROW_MASK));
}
void SSD1306_pamSetStartAddress (u8 address)
Definition at line 285 of file SSD1306.c.
References SSD1306_sendCommand().
{
    // "Set Lower Column Start Address for Page Addressing Mode"
    SSD1306_sendCommand(address & 0x0F);
    // "Set Higher Column Start Address for Page Addressing Mode"
    SSD1306_sendCommand((address << 4) & 0x0F);
}
void SSD1306_printChar (u8 c)
Definition at line 643 of file SSD1306.c.
References font_t::address, lcd_t::cursor, DISPLAY_WIDTH, lcd_t::font, SSD1306, SSD1306_buffer, SSD1306_scrollUp(), font_t::width, coord_t::x, and coord_t::y.
{
    u8 b;
    while (SSD1306.cursor.x >= (DISPLAY_WIDTH /
      SSD1306.font.width))
    {
        SSD1306.cursor.x -= (DISPLAY_WIDTH / SSD1306.
      font.width);
        SSD1306.cursor.y++;
    }
    while (SSD1306.cursor.y > 7)
    {
        SSD1306_scrollUp();
    }
    switch (c)
    {
        case '\n':
            SSD1306.cursor.y++;
            break;
            
        case '\r':
            SSD1306.cursor.x = 0;
            break;
            
        case '\t':
            SSD1306.cursor.x = (SSD1306.cursor.x + 4) % 4;
            break;
            
        default:
            for (b = 0; b < SSD1306.font.width; b++)
            {
                SSD1306_buffer[SSD1306.cursor.x *
      SSD1306.font.width + SSD1306.cursor.y * 128 + b] =
                    SSD1306.font.address[2 + (c - 32) *
      SSD1306.font.width + b];
            }
        
        SSD1306.cursor.x++;
    }
}
void SSD1306_refresh ()
Update the display
Definition at line 463 of file SSD1306.c.
References DISPLAY_ROWS, DISPLAY_SIZE, DISPLAY_WIDTH, SSD1306_buffer, SSD1306_hvSetColumnAddress(), SSD1306_hvSetPageAddress(), and SSD1306_sendData().
{
    u16 i;
    SSD1306_hvSetColumnAddress(0, DISPLAY_WIDTH-1);
    SSD1306_hvSetPageAddress(0, DISPLAY_ROWS-1);
    for (i = 0; i < DISPLAY_SIZE; i++)
        SSD1306_sendData(SSD1306_buffer[i]);
}
void SSD1306_scrollDown ()
Definition at line 616 of file SSD1306.c.
References SSD1306_startVerticalAndHorizontalScroll(), and SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL.
{
    SSD1306_startVerticalAndHorizontalScroll(
      SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL, 0, 64, 0, 1);
}
void SSD1306_scrollLeft ()
Definition at line 586 of file SSD1306.c.
References SSD1306_LEFT_HORIZONTAL_SCROLL, and SSD1306_startHorizontalScroll().
{
    SSD1306_startHorizontalScroll(
      SSD1306_LEFT_HORIZONTAL_SCROLL, 0, 7, 2);
}
void SSD1306_scrollRight ()
Definition at line 579 of file SSD1306.c.
References SSD1306_RIGHT_HORIZONTAL_SCROLL, and SSD1306_startHorizontalScroll().
{
    SSD1306_startHorizontalScroll(
      SSD1306_RIGHT_HORIZONTAL_SCROLL, 0, 7, 2);
}
void SSD1306_scrollUp ()
Definition at line 593 of file SSD1306.c.
References lcd_t::cursor, SSD1306, SSD1306_buffer, x, coord_t::y, and y.
{
    u8 x, y;
    for (y = 1; y <= 7; y++)
    {
        for (x = 0; x < 128; x++)
        {
            SSD1306_buffer[x + 128 * (y - 1)] = SSD1306_buffer[x + 128 * y];
        }
    }
    // memset ?
    for (x = 0; x < 128; x++)
    {
        SSD1306_buffer[x + 128 * 7] = 0;
    }
    SSD1306.cursor.y--;
}
void SSD1306_sendCommand (u8 val)
Globals
Core functions
The parallel 6800-series interface consists of : 8 bi-directional data pins (D[7:0]) R/W#, D/C#, E and CS#. A LOW in R/W# indicates WRITE operation A HIGH in R/W# indicates READ operation. A LOW in D/C# indicates COMMAND read/write A HIGH in D/C# indicates DATA read/write. The E input serves as data latch signal while CS# is LOW. Data is latched at the falling edge of E signal.
The parallel 8080-series interface consists of : 8 bi-directional data pins (DB[7:0]) RD#, WR#, DC# and CS#. A LOW in DC# indicates COMMAND read/write A HIGH in DC# indicates DATA read/write. A rising edge of RD# input serves as a data READ latch signal while CS# is kept LOW. A rising edge of WR# input serves as a data/command WRITE latch signal while CS# is kept LOW.
Definition at line 133 of file SSD1306.c.
References E, and PMP_wait.
{
    #if (DISPLAY & SSD1306_PMP)
        #if ((DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080))
            PMP_wait(); // wait for PMP to be available
            PMADDR = 0;
            PMDIN = val;
        #endif
    #else
        #if (DISPLAY & SSD1306_8080)
            Low(CS); // Chip select
            Low(DC); // COMMAND read/write
            Low(WR);
            DATA = val; // WR should stay low at least 60ns
            High(WR); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #elif (DISPLAY & SSD1306_6800)
            Low(CS); // Chip select
            Low(WR); // WRITE
            Low(DC); // COMMAND
            High(E);
            DATA = val; // WR should stay low at least 60ns
            Low(E); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #endif
    #endif
}
void SSD1306_sendData (u8 val)
Definition at line 175 of file SSD1306.c.
References E, and PMP_wait.
{
    #if (DISPLAY & SSD1306_PMP)
        #if ((DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080))
            PMP_wait(); // wait for PMP to be available
            PMADDR = DC;
            PMDIN = val;
        #endif
    #else
        #if (DISPLAY & SSD1306_8080)
            Low(CS); // Chip select
            High(DC); // DATA read/write
            Low(WR);
            DATA = val; // WR should stay low at least 60ns
            High(WR); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #elif (DISPLAY & SSD1306_6800)
            Low(CS); // Chip select
            Low(WR); // WRITE
            High(DC); // DATA
            High(E);
            DATA = val; // WR should stay low at least 60ns
            Low(E); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #endif
    #endif
}
void SSD1306_setChargePumpEnable (u8 enable)
Definition at line 342 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0x8D);
    SSD1306_sendCommand(enable ? 0x14 : 0x10);
}
void SSD1306_setComOutputScanDirection (u8 value)
Definition at line 274 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(value ? 0xC8 : 0xC0);
}
void SSD1306_setComPinsHardwareConfiguration (u8 sequential, u8 lr_remap)
Definition at line 279 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xDA);
    SSD1306_sendCommand(0x02 | ((sequential & 1) << 4) | ((lr_remap & 1) << 5));
}
void SSD1306_setContrast (u8 value)
Definition at line 252 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0x81);
    SSD1306_sendCommand(value);
}
void SSD1306_setCursor (u8 x, u8 y)
Graphic functions
Definition at line 839 of file SSD1306.c.
References lcd_t::cursor, DISPLAY_HEIGHT, DISPLAY_ROW_MASK, DISPLAY_WIDTH, coord_t::page, SSD1306, coord_t::x, x, coord_t::y, and y.
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    SSD1306.cursor.x = x;
    SSD1306.cursor.y = y;
    SSD1306.cursor.page = x & DISPLAY_ROW_MASK; // current page
}
void SSD1306_setDisplayClockRatioAndFrequency (u8 ratio, u8 frequency)
Definition at line 319 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xD5);
    SSD1306_sendCommand((ratio & 0x0F) | ((frequency & 0x0F) << 4));
}
void SSD1306_setDisplayOffset (u8 value)
Definition at line 246 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xD3);
    SSD1306_sendCommand(value & 0x3F);
}
void SSD1306_setDisplayStartLine (u8 value)
Definition at line 258 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0x40 | value);
}
void SSD1306_setFont (const u8 * font)
Print functions
Definition at line 625 of file SSD1306.c.
References font_t::address, font, lcd_t::font, font_t::height, SSD1306, and font_t::width.
{
    SSD1306.font.address = font;
    //SSD1306.font.width = SSD1306_getFontWidth()+1;
    //SSD1306.font.height = SSD1306_getFontHeight();
    SSD1306.font.width = font[0];
    SSD1306.font.height = font[1];
}
void SSD1306_setInverse (u8 value)
Definition at line 241 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(value ? 0xA7 : 0xA6);
}
void SSD1306_setMemoryAddressingMode (u8 mode)
Definition at line 294 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0x20);
    SSD1306_sendCommand(mode & 0x3);
}
void SSD1306_setMultiplexRatio (u8 value)
Definition at line 268 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xA8);
    SSD1306_sendCommand(value & 0x3F);
}
void SSD1306_setPrechargePeriod (u8 phase1, u8 phase2)
Definition at line 325 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xD9);
    SSD1306_sendCommand((phase1 & 0x0F) | ((phase2 & 0x0F) << 4));
}
void SSD1306_setSegmentRemap (u8 value)
Definition at line 263 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(value ? 0xA1 : 0xA0);
}
void SSD1306_setVcomhDeselectLevel (u8 level)
Definition at line 331 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xDB);
    SSD1306_sendCommand((level & 0x03) << 4);
}
void SSD1306_sleep ()
Definition at line 231 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xAE);
}
void SSD1306_startHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval)
Scroll functions
Definition at line 496 of file SSD1306.c.
References DISPLAY_ROW_MASK, SSD1306_ACTIVATE_SCROLL, and SSD1306_sendCommand().
{
    // Before issuing this command the horizontal scroll must be deactivated (2Eh).
    // Otherwise, RAM content may be corrupted.
    // RB : this datasheet recommandation doesn't work
    //SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
    SSD1306_sendCommand(direction);// ? 0x27 : 0x26);
    // Dummy byte (???)
    SSD1306_sendCommand(0x00);
    // Start page
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    // Time interval between each scroll step
    switch (interval)
    {
        case 2: SSD1306_sendCommand(0x07); break; // 111b
        case 3: SSD1306_sendCommand(0x04); break; // 100b
        case 4: SSD1306_sendCommand(0x05); break; // 101b
        case 5: SSD1306_sendCommand(0x00); break; // 000b
        case 25: SSD1306_sendCommand(0x06); break; // 110b
        case 64: SSD1306_sendCommand(0x01); break; // 001b
        case 128: SSD1306_sendCommand(0x02); break; // 010b
        case 256: SSD1306_sendCommand(0x03); break; // 011b
        default: SSD1306_sendCommand(0x07); break; // default to 2 frame interval
    }
    
    // End page
    //SSD1306_sendCommand(0x00);
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
    // ???
    SSD1306_sendCommand(0x00);
    SSD1306_sendCommand(0xFF);
    // activate scroll
    SSD1306_sendCommand(SSD1306_ACTIVATE_SCROLL);
}
void SSD1306_startVerticalAndHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval, u8 vertical_offset)
Definition at line 535 of file SSD1306.c.
References DISPLAY_ROW_MASK, SSD1306_ACTIVATE_SCROLL, and SSD1306_sendCommand().
{
    // Before issuing this command the horizontal scroll must be deactivated (2Eh).
    // Otherwise, RAM content may be corrupted.
    // RB : this datasheet recommandation doesn't work
    //SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
    SSD1306_sendCommand(direction); // ? 0x2A : 0x29);
    // Dummy byte (???)
    SSD1306_sendCommand(0x00);
    // Start page
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    // Time interval between each scroll step
    switch (interval)
    {
        case 2: SSD1306_sendCommand(0x07); break; // 111b
        case 3: SSD1306_sendCommand(0x04); break; // 100b
        case 4: SSD1306_sendCommand(0x05); break; // 101b
        case 5: SSD1306_sendCommand(0x00); break; // 000b
        case 25: SSD1306_sendCommand(0x06); break; // 110b
        case 64: SSD1306_sendCommand(0x01); break; // 001b
        case 128: SSD1306_sendCommand(0x02); break; // 010b
        case 256: SSD1306_sendCommand(0x03); break; // 011b
        default: SSD1306_sendCommand(0x07); break; // default to 2 frame interval
    }
    // End page
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
    SSD1306_sendCommand(vertical_offset);
    // activate scroll
    SSD1306_sendCommand(SSD1306_ACTIVATE_SCROLL);
}
void SSD1306_stopScroll ()
Definition at line 571 of file SSD1306.c.
References SSD1306_DEACTIVATE_SCROLL, and SSD1306_sendCommand().
{
    // all scroll configurations are removed from the display when executing this command.
    SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
}
void SSD1306_wake ()
Definition at line 236 of file SSD1306.c.
References SSD1306_sendCommand().
{
    SSD1306_sendCommand(0xAF);
}