/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/sd/fileio.h File Reference
#include `sdmmc.h`
*
#include `ff.h`
*
Data Structures
struct DIRTABLE
Macros
#define FE_IDE_ERROR 1
#define FE_NOT_PRESENT 2
#define FE_PARTITION_TYPE 3
#define FE_INVALID_MBR 4
#define FE_INVALID_BR 5
#define FE_MEDIA_NOT_MNTD 6
#define FE_FILE_NOT_FOUND 7
#define FE_INVALID_FILE 8
#define FE_FAT_EOF 9
#define FE_EOF 10
#define FE_INVALID_CLUSTER 11
#define FE_DIR_FULL 12
#define FE_MEDIA_FULL 13
#define FE_FILE_OVERWRITE 14
#define FE_CANNOT_INIT 15
#define FE_CANNOT_READ_MBR 16
#define FE_MALLOC_FAILED 17
#define FE_INVALID_MODE 18
#define FE_FIND_ERROR 19
#define ATT_RO 1
#define ATT_HIDE 2
#define ATT_SYS 4
#define ATT_VOL 8
#define ATT_DIR 0x10
#define ATT_ARC 0x20
#define ATT_LFN 0x0f
#define FOUND 2
#define NOT_FOUND 1
#define DW_CHAR sizeof(char)
#define DW_SHORT sizeof(short)
#define DW_LONG sizeof(long)
#define ReadW(a, f) *(unsigned short*)(a+f)
#define ReadL(a, f)
#define ReadOddW(a, f) (*(a+f) + (*(a+f+1) << 8))
Functions
char mount (unsigned char)
void unmount (void)
char isReadOnly (FILINFO file)
char isHidden (FILINFO file)
char isSystem (FILINFO file)
char isArchive (FILINFO file)
unsigned listTYPE (DIRTABLE *list, int max, const char *ext)
unsigned listDir (const char *path)
Variables
char SDCS
char FError
FATFS * Fat
DWORD AccSize
PF_WORD AccFiles
PF_WORD AccDirs
FILINFO Finfo
Macro Definition Documentation
#define ATT_ARC 0x20
Definition at line 74 of file fileio.h.
#define ATT_DIR 0x10
Definition at line 73 of file fileio.h.
#define ATT_HIDE 2
Definition at line 70 of file fileio.h.
#define ATT_LFN 0x0f
Definition at line 75 of file fileio.h.
#define ATT_RO 1
Definition at line 69 of file fileio.h.
#define ATT_SYS 4
Definition at line 71 of file fileio.h.
#define ATT_VOL 8
Definition at line 72 of file fileio.h.
#define DW_CHAR sizeof(char)
Definition at line 79 of file fileio.h.
#define DW_LONG sizeof(long)
Definition at line 81 of file fileio.h.
#define DW_SHORT sizeof(short)
Definition at line 80 of file fileio.h.
#define FE_CANNOT_INIT 15
Definition at line 36 of file fileio.h.
#define FE_CANNOT_READ_MBR 16
Definition at line 37 of file fileio.h.
#define FE_DIR_FULL 12
Definition at line 33 of file fileio.h.
#define FE_EOF 10
Definition at line 31 of file fileio.h.
#define FE_FAT_EOF 9
Definition at line 30 of file fileio.h.
#define FE_FILE_NOT_FOUND 7
Definition at line 28 of file fileio.h.
#define FE_FILE_OVERWRITE 14
Definition at line 35 of file fileio.h.
#define FE_FIND_ERROR 19
Definition at line 40 of file fileio.h.
#define FE_IDE_ERROR 1
Definition at line 22 of file fileio.h.
#define FE_INVALID_BR 5
Definition at line 26 of file fileio.h.
#define FE_INVALID_CLUSTER 11
Definition at line 32 of file fileio.h.
#define FE_INVALID_FILE 8
Definition at line 29 of file fileio.h.
#define FE_INVALID_MBR 4
Definition at line 25 of file fileio.h.
#define FE_INVALID_MODE 18
Definition at line 39 of file fileio.h.
#define FE_MALLOC_FAILED 17
Definition at line 38 of file fileio.h.
#define FE_MEDIA_FULL 13
Definition at line 34 of file fileio.h.
#define FE_MEDIA_NOT_MNTD 6
Definition at line 27 of file fileio.h.
#define FE_NOT_PRESENT 2
Definition at line 23 of file fileio.h.
#define FE_PARTITION_TYPE 3
Definition at line 24 of file fileio.h.
#define FOUND 2
Definition at line 76 of file fileio.h.
#define NOT_FOUND 1
Definition at line 77 of file fileio.h.
#define ReadL(a, f)
Value:
*(unsigned short*)(a+f) + \
((*(unsigned short*)(a+f+2))<<16)
Definition at line 87 of file fileio.h.
#define ReadOddW(a, f) (*(a+f) + (*(a+f+1) << 8))
Definition at line 92 of file fileio.h.
#define ReadW(a, f) *(unsigned short*)(a+f)
Definition at line 86 of file fileio.h.
Function Documentation
char isArchive (FILINFO file)
Definition at line 250 of file fileio.c.
References AM_ARC, False, FILINFO::fattrib, and True.
                             {
    if (file.fattrib & AM_ARC) {
        return True;
    } else {
        return False;
    }
}
char isHidden (FILINFO file)
Definition at line 234 of file fileio.c.
References AM_HID, False, FILINFO::fattrib, and True.
                            {
    if (file.fattrib & AM_HID) {
        return True;
    } else {
        return False;
    }
}
char isReadOnly (FILINFO file)
Definition at line 226 of file fileio.c.
References AM_RDO, False, FILINFO::fattrib, and True.
                              {
    if (file.fattrib & AM_RDO) {
        return True;
    } else {
        return False;
    }
}
char isSystem (FILINFO file)
Definition at line 242 of file fileio.c.
References AM_SYS, False, FILINFO::fattrib, and True.
                            {
    if (file.fattrib & AM_SYS) {
        return True;
    } else {
        return False;
    }
}
unsigned listDir (const char * path)
Definition at line 165 of file fileio.c.
References AM_DIR, dir, f_opendir(), f_readdir(), FILINFO::fattrib, Finfo, FILINFO::fname, FR_OK, FILINFO::fsize, and res.
                                   {
    //TODO: remove all CDC references
    long p1;
    PF_BYTE res, b;
    UINT s1, s2;
    DIR dir; /* Directory object */
    res = f_opendir(&dir, "/");
#ifdef SD_DEBUG
    CDCprintf("f_opendir? ");
    put_rc(res);
#endif
    p1 = s1 = s2 = 0;
    CDCprintln("\nf_readdir('%s'): ", path);
    for (;;) {
        res = f_readdir(&dir, &Finfo);
#ifdef SD_DEBUG
        put_rc(res);
#endif
        if ((res != FR_OK) || !Finfo.fname[0]) {
            break;
        }
        if (Finfo.fattrib & AM_DIR) {
            s2++;
        } else {
            s1++;
            p1 += Finfo.fsize;
        }
/* what about other outputs ?
        CDCprintf("%c%c%c%c%c ",
                (Finfo.fattrib & AM_DIR) ? 'D' : '-',
                (Finfo.fattrib & AM_RDO) ? 'R' : '-',
                (Finfo.fattrib & AM_HID) ? 'H' : '-',
                (Finfo.fattrib & AM_SYS) ? 'S' : '-',
                (Finfo.fattrib & AM_ARC) ? 'A' : '-');
        CDCprintf("%u/%02u/%02u %02u:%02u ",
                (Finfo.fdate >> 9) + 1980,
                (Finfo.fdate >> 5) & 15, Finfo.fdate & 31, (Finfo.ftime >> 11),
                (Finfo.ftime >> 5) & 63);
        CDCprintf(" %9u ", Finfo.fsize);
        CDCprintln(" %-12s %s", Finfo.fname,
#if _USE_LFN
                Lfname);
#else
                "");
#endif
*/
    }
    return s1;
} // listDir
unsigned listTYPE (DIRTABLE * list, int max, const char * ext)
Definition at line 1007 of file fileio.c.
References ATT_DIR, ATT_HIDE, MFILE::buffer, D, DIR_ATTRIB, DIR_DEL, DIR_EMPTY, DIR_EXT, DIR_NAME, DIR_SIZE, DIRTABLE::ext, FE_FIND_ERROR, FE_MALLOC_FAILED, FE_MEDIA_NOT_MNTD, FError, DIRTABLE::filename, MEDIA::maxroot, MFILE::mda, NULL, readDIR(), DIRTABLE::size, TRUE, and x.
{
    unsigned eCount; // current entry counter
    unsigned eOffs; // current entry offset in buffer
    unsigned x, a, r;
    MFILE *fp;
    unsigned char *b;
    x = 0;
    r = 0;
    // 1. check if storage device is mounted
    if (D == NULL) // unmounted
    {
        FError = FE_MEDIA_NOT_MNTD;
        return 0;
    }
    // 2. allocate a buffer (blocks of 512 bytes) for the file
    b = (unsigned char*)malloc(512);
    if (b == NULL)
    {
        FError = FE_MALLOC_FAILED;
        return 0;
    }
    // 3. allocate a MFILE structure on the heap
    fp = (MFILE *) malloc(sizeof(MFILE));
    if (fp == NULL)
    {
        FError = FE_MALLOC_FAILED;
        free(b);
        return 0;
    }
    // 4. set pointers to the MEDIA structure and buffer
    fp->mda = D;
    fp->buffer = b;
    // 5. start from first entry, load first sector from root
    eCount = 0;
    eOffs = 0;
    if (!readDIR(fp, eCount))
    { //report error
        FError = FE_FIND_ERROR;
        goto ListExit;
    }
    readDIR(fp, eCount);
    // 6. loop until you reach the end of the root directory
    while (TRUE)
    {
        // 6.1 read the first char of the file name
        a = fp->buffer[eOffs + DIR_NAME];
        // 6.2 terminate if it is empty (end of the list)
        if (a == DIR_EMPTY) // 0
            break;
        // 6.3
        if (a != DIR_DEL) // 229
        {
            // if not hidden, print the file name and size
            a = fp->buffer[eOffs + DIR_ATTRIB];
            if (!(a & (ATT_HIDE|ATT_DIR)))
            { // check the file extension
                if (!memcmp(&fp->buffer[eOffs+DIR_EXT], ext, 3))
                {
                    // copy file name in playlist
                    memcpy(&list[x].filename, &fp->buffer[eOffs+DIR_NAME], 8);
                    list[x].filename[8] = '\0';
                    // copy file ext in playlist
                    memcpy(&list[x].ext, &fp->buffer[eOffs+DIR_EXT], 3);
                    list[x].ext[3] = '\0';
                    // copy file size in playlist
                    list[x].size = fp->buffer[eOffs+DIR_SIZE];
                    if (++x >= max)
                        break;
                }
            } // file
        } // not deleted or hidden
        // 6.4 get the next entry
        // exit the loop if reached the end or error
        eCount++;
        if (eCount > fp->mda->maxroot)
            break; // last entry reached
        eOffs += 32;
        if (eOffs >= 512)
        {
            eOffs = 0;
            if (!readDIR(fp, eCount))
            {
                FError = FE_FIND_ERROR;
                goto ListExit;
            }
        }
    }// while
    // 7. return the number of files found
    r = x;
    ListExit:
    // 8. free buffers and return
    free(fp->buffer);
    free(fp);
    return r;
} // listTYPE
char mount (unsigned char)
Definition at line 65 of file fileio.c.
References BR_FAT_CPY, BR_FAT_SIZE, BR_MAX_ROOT, BR_RES, BR_SXC, D, MEDIA::data, f_mount(), False, MEDIA::fat, Fat, MEDIA::fatcopy, MEDIA::fatsize, FE_CANNOT_READ_MBR, FE_INVALID_BR, FE_INVALID_MBR, FE_MALLOC_FAILED, FE_NOT_PRESENT, FE_PARTITION_TYPE, FError, FO_FIRST_SECT, FO_FIRST_SIZE, FO_FIRST_TYPE, FO_MBR, FO_SIGN, FR_OK, getCD(), initMedia(), initSD(), MEDIA::maxcls, MEDIA::maxroot, NULL, ReadL, ReadOddW, readSECTOR(), ReadW, MEDIA::root, SDCS, MEDIA::sxc, True, and unmount().
Referenced by SD_present().
{
    LBA psize; // number of sectors in partition
    LBA firsts; // first sector inside the first partition
    int flag, i;
    unsigned char *buffer;
    // 0. init the I/Os
    SDCS = pin;
    initSD();
    // 1. check if the card is in the slot
    if (!getCD())
    {
        FError = FE_NOT_PRESENT;
        return NULL;
    }
    // 2. initialize the card
    if ((flag=initMedia()))
    {
        FError = flag;
        //FError = FE_CANNOT_INIT;
        return NULL;
    }
    // 3. allocate space for a MEDIA structure
    D = (MEDIA *) malloc(sizeof(MEDIA));
    if (D == NULL) // report an error
    {
        FError = FE_MALLOC_FAILED;
        return NULL;
    }
    // 4. allocate space for a temp sector buffer
    buffer = (unsigned char *) malloc(512);
    if (buffer == NULL) // report an error
    {
        FError = FE_MALLOC_FAILED;
        free((unsigned char *)D);
        return NULL;
    }
    // 5. get the Master Boot Record
    if (!readSECTOR(FO_MBR, buffer))
    {
        FError = FE_CANNOT_READ_MBR;
        free((unsigned char *)D);
        free(buffer);
        return NULL;
    }
    // 6. check if the MBR sector is valid
    // verify the signature word
    if ((buffer[FO_SIGN] != 0x55) || (buffer[FO_SIGN +1] != 0xAA))
    {
        FError = FE_INVALID_MBR;
        free((unsigned char *)D);
        free(buffer);
        return NULL;
    }
    // Valid Master Boot Record Loaded
    // 7. read the number of sectors in partition
    psize = ReadL(buffer, FO_FIRST_SIZE);
    // 8. check if the partition type is acceptable
    i = buffer[FO_FIRST_TYPE];
    switch (i)
    {
        case 0x04:
        case 0x06:
        case 0x0E:
            // valid FAT16 options
            break;
        default:
            FError = FE_PARTITION_TYPE;
            free((unsigned char *)D);
            free(buffer);
            return NULL;
    } // switch
    // 9. get the first partition first sector -> Boot Record
    // get the 32 bit offset to the first partition
    firsts = ReadL(buffer, FO_FIRST_SECT);
    // assuming FO_MBR == 0
    // 10. get the sector loaded (boot record)
    if (!readSECTOR(firsts, buffer))
    {
        free((unsigned char *)D);
        free(buffer);
        return NULL;
    }
    // 11. check if the boot record is valid
    // verify the signature word
    if ((buffer[FO_SIGN] != 0x55) || (buffer[FO_SIGN +1] != 0xAA))
    {
        FError = FE_INVALID_BR;
        free((unsigned char *)D);
        free(buffer);
        return NULL;
    }
    // Valid Partition Boot Record Loaded
    // get the full partition/drive layout
    // 12. determine the size of a cluster
    D->sxc = buffer[BR_SXC];
    // this will also act as flag that the disk is mounted
    // 13. determine fat, root and data LBAs
    // FAT = first sector in partition
    // (boot record) + reserved records
    D->fat = firsts + ReadW(buffer, BR_RES);
    D->fatsize = ReadW(buffer, BR_FAT_SIZE);
    D->fatcopy = buffer[BR_FAT_CPY];
    // 14. ROOT = FAT + (sectors per FAT * copies of FAT)
    D->root = D->fat + (D->fatsize * D->fatcopy);
    // 15. MAX ROOT is the maximum number of entries
    // in the root directory
    D->maxroot = ReadOddW(buffer, BR_MAX_ROOT) ;
    // 16. DATA = ROOT + (MAXIMUM ROOT *32 / 512)
    D->data = D->root + (D->maxroot >> 4);
    // assuming maxroot % 16 == 0!!!
    // 17. max clusters in this partition
    // = (tot sectors - sys sectors)/sxc
    D->maxcls = (psize - (D->data - firsts)) / D->sxc;
    // 18. free up the temporary buffer
    free(buffer);
    return D;
} // mount
void unmount (void)
Definition at line 210 of file fileio.c.
References D, f_mount(), and NULL.
Referenced by mount(), and SD_present().
{
    free((unsigned char *)D);
} // unmount
Variable Documentation
PF_WORD AccDirs
Definition at line 65 of file fileio.h.
Referenced by scan_files(), and sd_status().
PF_WORD AccFiles
Definition at line 65 of file fileio.h.
Referenced by scan_files(), and sd_status().
DWORD AccSize
Definition at line 64 of file fileio.h.
Referenced by scan_files(), and sd_status().
FATFS* Fat
Definition at line 62 of file fileio.h.
Referenced by mount(), and sd_status().
char FError
Definition at line 61 of file fileio.h.
FILINFO Finfo
Definition at line 66 of file fileio.h.
Referenced by listDir(), and scan_files().
char SDCS
Definition at line 59 of file fileio.h.