/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/system.c File Reference
#include <p32xxxx.h>
*
#include <const.h>
*
#include <typedef.h>
*
Data Structures
struct SystemClocksSettingsStruct
Macros
#define __SYSTEM_C
#define CPUCOREMAXFREQUENCY 80000000L
#define CRYSTALFREQUENCY 8000000L
#define FLASHACCESSTIME 50
#define FIRCOSCDIV 0b111
#define FIRCOSCDIV16 0b110
#define LPIRCOSC 0b101
#define SOSC 0b100
#define POSCPLL 0b011
#define POSC 0b010
#define FRCOSCPLL 0b001
#define FRCOSC 0b000
#define PLLODIV256 0b111
#define PLLODIV64 0b110
#define PLLODIV32 0b101
#define PLLODIV16 0b100
#define PLLODIV8 0b011
#define PLLODIV4 0b010
#define PLLODIV2 0b001
#define PLLODIV1 0b000
#define FRCDIV256 0b111
#define FRCDIV64 0b110
#define FRCDIV32 0b101
#define FRCDIV16 0b100
#define FRCDIV8 0b011
#define FRCDIV4 0b010
#define FRCDIV2 0b001
#define FRCDIV1 0b000
#define PBDIV8 0b11
#define PBDIV4 0b10
#define PBDIV2 0b01
#define PBDIV1 0b00
#define PLLMULT24 0b111
#define PLLMULT21 0b110
#define PLLMULT20 0b101
#define PLLMULT19 0b100
#define PLLMULT18 0b011
#define PLLMULT17 0b010
#define PLLMULT16 0b001
#define PLLMULT15 0b000
Typedefs
typedef enum SystemClocksErrorEnum SystemClocksError
typedef struct
*
SystemClocksSettingsStruct SystemClocksSettings
Enumerations
enum SystemClocksErrorEnum { Error_None = 0,
Error_RequestedFrequencyTooHigh = 1,
Error_NoCombinationFound = 2
 }
Functions
void SystemUnlock ()
void SystemLock ()
void SystemClocksReadSettings (SystemClocksSettings *s)
uint32_t SystemClocksGetCpuFrequency (const SystemClocksSettings *s)
uint32_t SystemClocksGetPeripheralFrequency (const SystemClocksSettings *s)
void SystemClocksCalcCpuClockSettings (SystemClocksSettings *s, uint32_t cpuFrequency)
void SystemClocksCalcPeripheralClockSettings (SystemClocksSettings *s, uint32_t peripheralFrequency)
u32 GetSystemClock (void)
u32 GetPeripheralClock ()
void SetFlashWaitStates_old ()
void SystemSetSystemClock (u32 cpuCoreFrequency)
void SystemSetPeripheralClock (u32 peripheralFrequency)
void SystemConfig (u32 cpuCoreFrequency)
u32 MIPS32 GetCP0Count ()
void MIPS32 SetCP0Count (u32 count)
Macro Definition Documentation
#define __SYSTEM_C
Definition at line 31 of file system.c.
#define CPUCOREMAXFREQUENCY 80000000L
Definition at line 40 of file system.c.
Referenced by SystemClocksCalcCpuClockSettings(), and SystemClocksCalcPeripheralClockSettings().
#define CRYSTALFREQUENCY 8000000L
Definition at line 43 of file system.c.
Referenced by SystemClocksCalcCpuClockSettings(), and SystemClocksGetCpuFrequency().
#define FIRCOSCDIV 0b111
Definition at line 48 of file system.c.
#define FIRCOSCDIV16 0b110
Definition at line 49 of file system.c.
#define FLASHACCESSTIME 50
Definition at line 44 of file system.c.
#define FRCDIV1 0b000
Definition at line 75 of file system.c.
#define FRCDIV16 0b100
Definition at line 71 of file system.c.
#define FRCDIV2 0b001
Definition at line 74 of file system.c.
#define FRCDIV256 0b111
Definition at line 68 of file system.c.
#define FRCDIV32 0b101
Definition at line 70 of file system.c.
#define FRCDIV4 0b010
Definition at line 73 of file system.c.
#define FRCDIV64 0b110
Definition at line 69 of file system.c.
#define FRCDIV8 0b011
Definition at line 72 of file system.c.
#define FRCOSC 0b000
Definition at line 55 of file system.c.
#define FRCOSCPLL 0b001
Definition at line 54 of file system.c.
#define LPIRCOSC 0b101
Definition at line 50 of file system.c.
#define PBDIV1 0b00
Definition at line 81 of file system.c.
Referenced by SystemClocksCalcPeripheralClockSettings().
#define PBDIV2 0b01
Definition at line 80 of file system.c.
#define PBDIV4 0b10
Definition at line 79 of file system.c.
#define PBDIV8 0b11
Definition at line 78 of file system.c.
#define PLLMULT15 0b000
Definition at line 91 of file system.c.
#define PLLMULT16 0b001
Definition at line 90 of file system.c.
#define PLLMULT17 0b010
Definition at line 89 of file system.c.
#define PLLMULT18 0b011
Definition at line 88 of file system.c.
#define PLLMULT19 0b100
Definition at line 87 of file system.c.
#define PLLMULT20 0b101
Definition at line 86 of file system.c.
Referenced by SystemClocksCalcCpuClockSettings().
#define PLLMULT21 0b110
Definition at line 85 of file system.c.
#define PLLMULT24 0b111
Definition at line 84 of file system.c.
#define PLLODIV1 0b000
Definition at line 65 of file system.c.
Referenced by SystemClocksCalcCpuClockSettings().
#define PLLODIV16 0b100
Definition at line 61 of file system.c.
#define PLLODIV2 0b001
Definition at line 64 of file system.c.
Referenced by SystemClocksCalcCpuClockSettings().
#define PLLODIV256 0b111
Definition at line 58 of file system.c.
#define PLLODIV32 0b101
Definition at line 60 of file system.c.
#define PLLODIV4 0b010
Definition at line 63 of file system.c.
#define PLLODIV64 0b110
Definition at line 59 of file system.c.
#define PLLODIV8 0b011
Definition at line 62 of file system.c.
#define POSC 0b010
Definition at line 53 of file system.c.
#define POSCPLL 0b011
Definition at line 52 of file system.c.
#define SOSC 0b100
Definition at line 51 of file system.c.
Typedef Documentation
typedef enum SystemClocksErrorEnum SystemClocksError
Error state, only used by the test cases
typedef struct SystemClocksSettingsStruct SystemClocksSettings
This struct is used to store the results after reading in the current settings, and to calculate new clock settings in memory.
Each function gets a pointer to this struct as the first parameter.
If we used C++, this struct would be the class; and all functions in this file would be member functions.
Enumeration Type Documentation
enum SystemClocksErrorEnum
Error state, only used by the test cases
Enumerator
Error_None
Error_RequestedFrequencyTooHigh
Error_NoCombinationFound
Definition at line 133 of file system.c.
                                   {
  Error_None = 0,
  Error_RequestedFrequencyTooHigh = 1,
  Error_NoCombinationFound = 2,
} SystemClocksError;
Function Documentation
u32 MIPS32 GetCP0Count ()
Definition at line 529 of file system.c.
Referenced by Delayus().
{
    //u32 count;
    //asm("di"); // Disable all interrupts
    //count = _CP0_GET_COUNT();
    //asm("ei"); // Enable all interrupts
    //return count;
    return _CP0_GET_COUNT();
}
u32 GetPeripheralClock ()
Definition at line 462 of file system.c.
References SystemClocksGetPeripheralFrequency(), and SystemClocksReadSettings().
Referenced by I2C_init(), initSD(), millis_init(), PWM_set_frequency(), SerialGetDataRate(), SerialSetDataRate(), SPI_setClock(), and Stepper_step().
{
    SystemClocksSettings s;
    SystemClocksReadSettings(&s);
    return SystemClocksGetPeripheralFrequency(&s);
}
u32 GetSystemClock (void)
Definition at line 451 of file system.c.
References SystemClocksGetCpuFrequency(), and SystemClocksReadSettings().
Referenced by Delayus(), and SetFlashWaitStates_old().
{
    SystemClocksSettings s;
    SystemClocksReadSettings(&s);
    return SystemClocksGetCpuFrequency(&s);
}
void MIPS32 SetCP0Count (u32 count)
Definition at line 543 of file system.c.
{
    //asm("di"); // Disable all interrupts
    _CP0_SET_COUNT(count);
    //asm("ei"); // Enable all interrupts
}
void SetFlashWaitStates_old ()
Definition at line 473 of file system.c.
References GetSystemClock(), SystemLock(), and SystemUnlock().
{
    SystemUnlock();
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    //PMMODEbits.WAITB = 0b00; // Data wait of 1 TPB
    #else
    CHECON = (GetSystemClock() / 20) - 1; // FlashWaitStates
    #endif
    SystemLock();
}
void SystemClocksCalcCpuClockSettings (SystemClocksSettings * s, uint32_t cpuFrequency)
Calculate the necessary values in order to have the CPU running at the desired frequency.
See Also
system.c::SystemConfig()
Returns
Nothing (the result is put into the struct)
Definition at line 260 of file system.c.
References CPUCOREMAXFREQUENCY, CRYSTALFREQUENCY, Error_NoCombinationFound, Error_None, Error_RequestedFrequencyTooHigh, SystemClocksSettingsStruct::PLLIDIV, SystemClocksSettingsStruct::PLLMULT, PLLMULT20, SystemClocksSettingsStruct::PLLODIV, PLLODIV1, and PLLODIV2.
Referenced by SystemConfig(), and SystemSetSystemClock().
{
    if (cpuFrequency <= CPUCOREMAXFREQUENCY)
    {
      #ifdef EXTENDED_TEST_CASE
        s->error = Error_None;
      #endif
    }
    else
    {
      cpuFrequency = CPUCOREMAXFREQUENCY;
      #ifdef EXTENDED_TEST_CASE
        s->error = Error_RequestedFrequencyTooHigh;
      #endif
    }
    uint8_t pllOutputDivIndex;
    for (pllOutputDivIndex = 0;
       pllOutputDivIndex < pllOutputDivsCount;
       pllOutputDivIndex++)
    {
      uint8_t pllMulIndex;
      for (pllMulIndex = 0; pllMulIndex < pllMulsCount; pllMulIndex++)
    {
      if ((cpuFrequency
        * pllInputDivs[s->PLLIDIV]
        * pllOutputDivs[pllOutputDivIndex])
           == (CRYSTALFREQUENCY * pllMuls[pllMulIndex]))
        {
          s->PLLODIV = pllOutputDivIndex;
          s->PLLMULT = pllMulIndex;
          // Match found
          return;
        }
    }
    }
    /*
    * No combination found -> try to get max CPU frequency. This
    * depends from pllInputDiv.
    *
    * The selected values will result in the max CPU frequency, if
    * the pllInputDiv is 1 or 2.
    *
    * With pllInputDiv > 2 we cannot reach the max frequency.
    */
    if (pllInputDivs[s->PLLIDIV] >= 2)
    {
      s->PLLODIV = PLLODIV1; // /1
      #ifdef EXTENDED_TEST_CASE
        s->error = Error_NoCombinationFound;
      #endif
    }
    else
    {
      s->PLLODIV = PLLODIV2; // /2
      #ifdef EXTENDED_TEST_CASE
        s->error = Error_NoCombinationFound;
      #endif
    }
    s->PLLMULT = PLLMULT20; // x20
}
void SystemClocksCalcPeripheralClockSettings (SystemClocksSettings * s, uint32_t peripheralFrequency)
Calculate the necessary values in order to have the peripheral clock running at the desired frequency. As this value is only a divider, this normally requires a call to SystemClocksCalcCpuClockSettings() before, because the CPU frequency is needed to find the divider value.
See Also
system.c::SystemConfig()
Returns
Nothing (the result is put into the struct)
Definition at line 339 of file system.c.
References CPUCOREMAXFREQUENCY, Error_NoCombinationFound, Error_None, Error_RequestedFrequencyTooHigh, SystemClocksSettingsStruct::PBDIV, PBDIV1, and SystemClocksGetCpuFrequency().
Referenced by SystemConfig(), and SystemSetPeripheralClock().
{
    #ifdef EXTENDED_TEST_CASE
    s->error = Error_None;
    #endif
    if (peripheralFrequency > CPUCOREMAXFREQUENCY)
    {
      peripheralFrequency = CPUCOREMAXFREQUENCY;
      #ifdef EXTENDED_TEST_CASE
        s->error = Error_RequestedFrequencyTooHigh;
      #endif
    }
    const uint32_t cpuFrequency = SystemClocksGetCpuFrequency(s);
    uint8_t i;
    for (i = 0; i < pbDivsCount; i++)
    {
      if (cpuFrequency == peripheralFrequency * pbDivs[i])
    {
      s->PBDIV = i;
      // Match found
      return;
    }
    }
    // No match: Use default value
    s->PBDIV = PBDIV1; // /1
    #ifdef EXTENDED_TEST_CASE
    s->error = Error_NoCombinationFound;
    #endif
}
uint32_t SystemClocksGetCpuFrequency (const SystemClocksSettings * s)
Calculates the CPU frequency based on the values which are passed in. This normally requires a call to SystemClocksReadSettings() before.
See Also
system.c::GetSystemClock()
Returns
The CPU frequency
Definition at line 229 of file system.c.
References CRYSTALFREQUENCY, SystemClocksSettingsStruct::PLLIDIV, SystemClocksSettingsStruct::PLLMULT, and SystemClocksSettingsStruct::PLLODIV.
Referenced by GetSystemClock(), SystemClocksCalcPeripheralClockSettings(), and SystemClocksGetPeripheralFrequency().
{
  return
    CRYSTALFREQUENCY
    / pllInputDivs [s->PLLIDIV]
    / pllOutputDivs[s->PLLODIV]
    * pllMuls [s->PLLMULT];
}
uint32_t SystemClocksGetPeripheralFrequency (const SystemClocksSettings * s)
Calculates the peripheral clock frequency based on the values which are passed in. This normally requires a call to SystemClocksReadSettings() before.
See Also
system.c::GetPeripheralClock()
Returns
The peripheral clock frequency
Definition at line 247 of file system.c.
References SystemClocksSettingsStruct::PBDIV, and SystemClocksGetCpuFrequency().
Referenced by GetPeripheralClock().
{
  return SystemClocksGetCpuFrequency(s) / pbDivs[s->
      PBDIV];
}
void SystemClocksReadSettings (SystemClocksSettings * s)
Read in all relevant clock settings
See Also
system.c::GetSystemClock()
Returns
Nothing (the result is put into the struct)
Definition at line 211 of file system.c.
References SystemClocksSettingsStruct::PBDIV, SystemClocksSettingsStruct::PLLIDIV, SystemClocksSettingsStruct::PLLMULT, and SystemClocksSettingsStruct::PLLODIV.
Referenced by GetPeripheralClock(), GetSystemClock(), SystemConfig(), SystemSetPeripheralClock(), and SystemSetSystemClock().
{
  s->PLLIDIV = DEVCFG2bits.FPLLIDIV;
  
  s->PLLODIV = OSCCONbits.PLLODIV;
  s->PLLMULT = OSCCONbits.PLLMULT;
  s->PBDIV = OSCCONbits.PBDIV;
}
void SystemConfig (u32 cpuCoreFrequency)
Definition at line 512 of file system.c.
References SystemClocksCalcCpuClockSettings(), SystemClocksCalcPeripheralClockSettings(), and SystemClocksReadSettings().
{
    SystemClocksSettings s;
    SystemClocksReadSettings(&s);
    SystemClocksCalcCpuClockSettings(&s, cpuCoreFrequency);
    SystemClocksCalcPeripheralClockSettings(&s, cpuCoreFrequency / 2
      );
    SystemClocksWriteSettings(&s);
    //RB2014 : already defined in io.c / IOsetDigital()
    //DDPCONbits.JTAGEN=0; // PORTA is used as digital instead of JTAG
    //CFGCONbits.JTAGEN=0; // Disable the JTAG port
}
void SystemLock ()
Definition at line 175 of file system.c.
Referenced by IOsetRemap(), RTCC_SetWriteDisable(), RTCC_SetWriteEnable(), RTCC_SOSCdisable(), RTCC_SOSCenable(), and SetFlashWaitStates_old().
{
    SYSKEY = 0x12345678; // Write any value other than Key1 or Key2
}
void SystemSetPeripheralClock (u32 peripheralFrequency)
Definition at line 500 of file system.c.
References SystemClocksCalcPeripheralClockSettings(), and SystemClocksReadSettings().
{
    SystemClocksSettings s;
    SystemClocksReadSettings(&s);
    SystemClocksCalcPeripheralClockSettings(&s, peripheralFrequency)
      ;
    SystemClocksWriteSettings(&s);
}
void SystemSetSystemClock (u32 cpuCoreFrequency)
Definition at line 488 of file system.c.
References SystemClocksCalcCpuClockSettings(), and SystemClocksReadSettings().
{
    SystemClocksSettings s;
    SystemClocksReadSettings(&s);
    SystemClocksCalcCpuClockSettings(&s, cpuCoreFrequency);
    SystemClocksWriteSettings(&s);
}
void SystemUnlock ()
Definition at line 164 of file system.c.
Referenced by IOsetRemap(), RTCC_SetWriteDisable(), RTCC_SetWriteEnable(), RTCC_SOSCdisable(), RTCC_SOSCenable(), and SetFlashWaitStates_old().
{
    SYSKEY = 0; // ensure OSCCON is locked
    SYSKEY = 0xAA996655; // Write Key1 to SYSKEY
    SYSKEY = 0x556699AA; // Write Key2 to SYSKEY
}