/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pmp.h File Reference
#include <typedef.h>
*
Macros
#define PMP_wait() while(PMMODEbits.BUSY)
#define PMP_MODE_IRQ_OFF 0b00
#define PMP_MODE_BUF_IRQ 0b10
#define PMP_MODE_CY_IRQ 0b01
#define PMP_MODE_INC_BUFFER 0b11
#define PMP_MODE_DEC_ADDR 0b10
#define PMP_MODE_INC_ADDR 0b01
#define PMP_MODE_INC_OFF 0b00
#define PMP_MODE_8BIT 0
#define PMP_MODE_16BIT 1
#define PMP_MODE_MASTER1 0b11
#define PMP_MODE_MASTER2 0b10
#define PMP_MODE_ESLAVE 0b01
#define PMP_MODE_SLAVE 0b00
#define PMP_MUX_16X16 0b11
#define PMP_MUX_16X8 0b10
#define PMP_MUX_8X16 0b01
#define PMP_MUX_OFF 0b00
#define PMP_CS1CS2 0b10
#define PMP_CS2 0b01
#define PMP_CS_OFF 0b00
#define PMP_ACTIVE_LOW 0
#define PMP_ACTIVE_HIGH 1
#define PMA0 1<<0
#define PMA1 1<<1
#define PMA2 1<<2
#define PMA3 1<<3
#define PMA4 1<<4
#define PMA5 1<<5
#define PMA6 1<<6
#define PMA7 1<<7
#define PMA8 1<<8
#define PMA9 1<<9
#define PMA10 1<<10
#define PMA11 1<<11
#define PMA12 1<<12
#define PMA13 1<<13
#define PMA14 1<<14
#define PMA15 1<<15
#define PMCS 1<<14
#define PMCS1 1<<14
#define PMCS2 1<<15
#define PMRD 1<<13
#define PMRD_PMWR 1<<13
#define PMWR 1<<12
#define PMENB 1<<12
#define PMBE 1<<11
Functions
void PMP_setMode (u8)
void PMP_setAddress (u16)
void PMP_setControl (u16)
void PMP_setPolarity (u8)
void PMP_setMux (u8)
void PMP_setWidth (u8)
void PMP_setWaitStates (u8 beg, u8 mid, u8 end)
void PMP_autoIncrement (s8 inc)
void PMP_init ()
void PMP_sendAddress (u16)
void PMP_write (u16)
u16 PMP_read ()
Macro Definition Documentation
#define PMA0 1<<0
Definition at line 82 of file pmp.h.
#define PMA1 1<<1
Definition at line 83 of file pmp.h.
#define PMA10 1<<10
Definition at line 92 of file pmp.h.
#define PMA11 1<<11
Definition at line 93 of file pmp.h.
#define PMA12 1<<12
Definition at line 94 of file pmp.h.
#define PMA13 1<<13
Definition at line 95 of file pmp.h.
#define PMA14 1<<14
Definition at line 96 of file pmp.h.
#define PMA15 1<<15
Definition at line 97 of file pmp.h.
#define PMA2 1<<2
Definition at line 84 of file pmp.h.
#define PMA3 1<<3
Definition at line 85 of file pmp.h.
#define PMA4 1<<4
Definition at line 86 of file pmp.h.
#define PMA5 1<<5
Definition at line 87 of file pmp.h.
#define PMA6 1<<6
Definition at line 88 of file pmp.h.
#define PMA7 1<<7
Definition at line 89 of file pmp.h.
#define PMA8 1<<8
Definition at line 90 of file pmp.h.
#define PMA9 1<<9
Definition at line 91 of file pmp.h.
#define PMBE 1<<11
Definition at line 106 of file pmp.h.
#define PMCS 1<<14
Definition at line 99 of file pmp.h.
#define PMCS1 1<<14
Definition at line 100 of file pmp.h.
#define PMCS2 1<<15
Definition at line 101 of file pmp.h.
#define PMENB 1<<12
Definition at line 105 of file pmp.h.
#define PMP_ACTIVE_HIGH 1
Definition at line 80 of file pmp.h.
#define PMP_ACTIVE_LOW 0
Definition at line 79 of file pmp.h.
#define PMP_CS1CS2 0b10
Definition at line 74 of file pmp.h.
Referenced by PMP_init().
#define PMP_CS2 0b01
Definition at line 75 of file pmp.h.
Referenced by PMP_init().
#define PMP_CS_OFF 0b00
Definition at line 76 of file pmp.h.
#define PMP_MODE_16BIT 1
Definition at line 51 of file pmp.h.
#define PMP_MODE_8BIT 0
Definition at line 50 of file pmp.h.
#define PMP_MODE_BUF_IRQ 0b10
Definition at line 42 of file pmp.h.
#define PMP_MODE_CY_IRQ 0b01
Definition at line 43 of file pmp.h.
#define PMP_MODE_DEC_ADDR 0b10
Definition at line 46 of file pmp.h.
#define PMP_MODE_ESLAVE 0b01
Definition at line 55 of file pmp.h.
#define PMP_MODE_INC_ADDR 0b01
Definition at line 47 of file pmp.h.
#define PMP_MODE_INC_BUFFER 0b11
Definition at line 45 of file pmp.h.
#define PMP_MODE_INC_OFF 0b00
Definition at line 48 of file pmp.h.
#define PMP_MODE_IRQ_OFF 0b00
Definition at line 41 of file pmp.h.
#define PMP_MODE_MASTER1 0b11
Definition at line 53 of file pmp.h.
#define PMP_MODE_MASTER2 0b10
Definition at line 54 of file pmp.h.
#define PMP_MODE_SLAVE 0b00
Definition at line 56 of file pmp.h.
#define PMP_MUX_16X16 0b11
Definition at line 64 of file pmp.h.
#define PMP_MUX_16X8 0b10
Definition at line 65 of file pmp.h.
#define PMP_MUX_8X16 0b01
Definition at line 66 of file pmp.h.
#define PMP_MUX_OFF 0b00
Definition at line 67 of file pmp.h.
#define PMP_wait() while(PMMODEbits.BUSY)
Definition at line 38 of file pmp.h.
#define PMRD 1<<13
Definition at line 102 of file pmp.h.
#define PMRD_PMWR 1<<13
Definition at line 103 of file pmp.h.
#define PMWR 1<<12
Definition at line 104 of file pmp.h.
Function Documentation
void PMP_autoIncrement (s8 inc)
Definition at line 144 of file pmp.c.
References _pmp_inc, PMP_MODE_DEC_ADDR, PMP_MODE_INC_ADDR, and PMP_MODE_INC_BUFFER.
Referenced by SSD1306_init().
{
    if (inc==1 || inc==PMP_MODE_INC_BUFFER || inc==
      PMP_MODE_INC_ADDR)
        _pmp_inc = 1;
    else if (inc==-1 || inc==PMP_MODE_DEC_ADDR)
        _pmp_inc = -1;
    
    else //if (inc==0 || inc==PMP_MODE_INC_OFF)
        _pmp_inc = 0;
}
void PMP_init ()
Disable the PMP interrupt
Stop and reset the PMP module
Configure Mode
Configure Control
Enable/Disable PMA<15:0> Address pins
If interrupts are used:
Enable the PMP master port
Disable the PMP interrupt
Stop and reset the PMP module
Configure Mode
Configure Control
Enable/Disable PMA<15:0> Address pins
If interrupts are used
Enable the PMP master port
Definition at line 195 of file pmp.c.
References _pmp_address, _pmp_control, _pmp_inc, _pmp_mode, _pmp_mux, _pmp_polarity, _pmp_waitB, _pmp_waitE, _pmp_waitM, _pmp_width, Delayms(), high8, low8, PMBE, PMCS1, PMCS2, PMP_CS1CS2, PMP_CS2, PMP_CS_OFF, PMP_CS_ON, PMP_MODE_DEC_ADDR, PMP_MODE_ESLAVE, PMP_MODE_INC_ADDR, PMP_MODE_INC_BUFFER, PMP_MODE_INC_OFF, PMP_MODE_IRQ_OFF, PMP_MODE_SLAVE, PMRD, and PMWR.
Referenced by SSD1306_init().
{
    //IntDisable(PMPINT);
    PMCONHbits.PMPEN = 0;//Bit(15);
    PMCONH = 0;
    PMCONL = 0;
    PMMODEH = 0;
    PMMODEL = 0;
    PMEH = 0;
    PMEL = 0;
    // Enable Interrupt Request mode: IRQM<1:0> bits (PMMODE<14:13>).
    PMMODEHbits.IRQM = PMP_MODE_IRQ_OFF;
    
    // Select auto address increment: INCM<1:0> bits (PMMODE<12:11>).
    if (_pmp_mode==PMP_MODE_ESLAVE || _pmp_mode==
      PMP_MODE_SLAVE)
    {
        if (_pmp_inc==1)
            PMMODEHbits.INCM = PMP_MODE_INC_BUFFER;
        else
            PMMODEHbits.INCM = PMP_MODE_INC_OFF;
    }
    else // master mode 1 or 2
    {
        if (_pmp_inc==1)
            PMMODEHbits.INCM = PMP_MODE_INC_ADDR;
        if (_pmp_inc==-1)
            PMMODEHbits.INCM = PMP_MODE_DEC_ADDR;
        
        if (_pmp_inc==0)
            PMMODEHbits.INCM = PMP_MODE_INC_OFF;
    }
    
    // Select 8- or 16-bit Data mode: MODE16 bit (PMMODE<10>).
    PMMODEHbits.MODE16 = _pmp_width;
    
    // Select Master mode : MODE<1:0> bits (PMMODE<9:8>).
    // In Master mode 1, read and write strobe are combined into a
    // single control line, PMRD/PMWR;
    // a second control line, PMENB, determines when a read or write
    // action is to be taken.
    // In Master mode 2, read and write strobes (PMRD and PMWR)
    // are supplied on separate pins.
    PMMODEH |= _pmp_mode;
    // Select 4 wait cycles before the PMRD/PMWR strobe
    PMMODELbits.WAITB = _pmp_waitB;
    // Wait cycles for a Read/Write strobe
    PMMODELbits.WAITM = _pmp_waitM;
    // Wait cycles for data hold
    PMMODELbits.WAITE = _pmp_waitE;
    //SIDL: Stop in Idle Mode bi
    //1 = Discontinue module operation when device enters Idle mode
    //0 = Continue module operation in Idle mode
    PMCONHbits.PSIDL = 0; // PMP idle when MCU idle
    // Select multiplexed addressing: ADRMUX<1:0> bits (PMCON<12:11>).
    PMCONHbits.ADRMUX = _pmp_mux; // Address and data appear on separate pins
    
    //PMPTTL: PMP Module TTL Input Buffer Select bit
    //1 = PMP module uses TTL input buffers
    //0 = PMP module uses Schmitt Trigger input buffer
    PADCFG1bits.PMPTTL = 0;
/*
    if (_pmp_mode == PMP_MODE_MASTER1)
    {
        // Enable PMBE strobe: PTWREN bit (PMCON<9>)
        if (_pmp_control & PMENB)
            PMCONHbits.PTWREN = 1; // PMP write strobe enable
        else
            PMCONHbits.PTWREN = 0; // PMP write strobe disable
        // Enable PMRD/PMWR strobe: PTRDEN bit (PMCON<8>)
        if (_pmp_control & PMRD_PMWR)
            PMCONHbits.PTRDEN = 1; // PMP read strobe enable
        else
            PMCONHbits.PTRDEN = 0; // PMP read strobe disable
        // To differentiate data bytes, the byte enable control strobe,
        // PMBE, is used to signal when the Most Significant Byte(MSB)
        // of data is being presented on the data lines
        // Enable bit : PTBEEN bit (PMCONH<2>)
        if (_pmp_control & PMBE)
            PMCONHbits.PTBEEN = 1; // PMP Enable strobe enable
        else
            PMCONHbits.PTBEEN = 0; // PMP Enable strobe disable
    }
    else if (_pmp_mode == PMP_MODE_MASTER2)
    {
*/
        // Enable PMWR strobe: PTWREN bit (PMCON<9>)
        if (_pmp_control & PMWR)
            PMCONHbits.PTWREN = 1; // PMP write strobe enable
        else
            PMCONHbits.PTWREN = 0; // PMP write strobe disable
        
        // Enable PMRD strobe: PTRDEN bit (PMCON<8>)
        if (_pmp_control & PMRD)
            PMCONHbits.PTRDEN = 1; // PMP read strobe enable
        else
            PMCONHbits.PTRDEN = 0; // PMP read strobe disable
        if (_pmp_control & PMBE)
            PMCONHbits.PTBEEN = 1; // PMP Enable strobe enable
        else
            PMCONHbits.PTBEEN = 0; // PMP Enable strobe disable
// }
    
    // Enable PMCS1 Chip Selects: CSF<1:0> bits (PMCON<7:6>)
    if ((_pmp_control & PMCS1) || (_pmp_control &
      PMCS2))
        PMCONLbits.CSF = PMP_CS_ON;
    else
        PMCONLbits.CSF = PMP_CS_OFF;
    // Address Latch Polarity bit
    PMCONLbits.ALP = _pmp_polarity;
    
    // Select PMCS2, PMCS1 active-low pin polarity: CS2P bit (PMCON<4>) = 0 and CS1P bit (PMCON<3>) = 0.
    PMCONLbits.CS1P = _pmp_polarity;
    // Byte Enable priority bit
    PMCONLbits.BEP = _pmp_polarity;
    // Select PMWR active-low pin polarity: WRSP bit (PMCON<1>) = 0.
    PMCONLbits.WRSP = _pmp_polarity;
    // Select PMRD active-low pin polarity: RDSP bit (PMCON<0>) = 0.
    PMCONLbits.RDSP = _pmp_polarity;
    
    PMEH = high8(_pmp_address);
    PMEL = low8(_pmp_address);
    if (_pmp_control & PMCS1)
    {
        PMEHbits.PTEN14 = 1; //address 14 or PMCS1
        //PMEH |= PMCS1;
    }
    
    if (_pmp_control & PMCS2)
    {
        PMEHbits.PTEN15 = 1; //address 15 or PMCS2
        //PMEH |= PMCS2;
    }
    
/*
    // 6.1. Clear the interrupt flag bit, PMPIF (IFS1<2>) = 0.
    IntClearFlag(INT_PARALLEL_MASTER_PORT);
    // 6.2. Configure the PMP interrupt priority bits
    IntSetVectorPriority(INT_PARALLEL_MASTER_PORT_VECTOR, 7, 3);
    // 6.3. Enable the PMP interrupt by setting the interrupt enable bit, PMPIE = 1.
    IntEnable(INT_PARALLEL_MASTER_PORT);
*/
    PMCONHbits.PMPEN = 1;//Bit(15);
    // wait for >30 ms
    Delayms(50);
}
u16 PMP_read ()
Definition at line 417 of file pmp.c.
References _pmp_width, make16, PMP_MODE_16BIT, and PMP_wait.
{
    u16 dummy;
    
    if (_pmp_width == PMP_MODE_16BIT)
    {
        PMP_wait(); // wait for PMP to be available
        dummy = PMDIN1L; // init read cycle, dummy read
        PMP_wait(); // wait for PMP to be available
        return (make16(PMDIN1L, PMDIN1H));
    }
    
    else
    {
        PMP_wait(); // wait for PMP to be available
        dummy = PMDIN1L; // dummy read
        PMP_wait(); // wait for PMP to be available
        return (PMDIN1L); // real read
    }
}
void PMP_sendAddress (u16)
Definition at line 445 of file pmp.c.
References high8, low8, and PMP_wait.
{
    PMP_wait(); // wait for PMP to be available
    PMADDRH = high8(addr);
    PMADDRL = low8(addr);
}
void PMP_setAddress (u16)
Definition at line 104 of file pmp.c.
References _pmp_address.
Referenced by SSD1306_init().
{
    _pmp_address = addr;
}
void PMP_setControl (u16)
Definition at line 117 of file pmp.c.
References _pmp_control.
Referenced by SSD1306_init().
{
    _pmp_control = control;
}
void PMP_setMode (u8)
Prototypes
Definition at line 75 of file pmp.c.
References _pmp_mode.
Referenced by SSD1306_init().
{
    _pmp_mode = mode;
}
void PMP_setMux (u8)
Definition at line 164 of file pmp.c.
References _pmp_mux.
Referenced by SSD1306_init().
{
    _pmp_mux = mux;
}
void PMP_setPolarity (u8)
Definition at line 130 of file pmp.c.
References _pmp_polarity.
Referenced by SSD1306_init().
{
    _pmp_polarity = polarity;
}
void PMP_setWaitStates (u8 beg, u8 mid, u8 end)
Definition at line 177 of file pmp.c.
References _pmp_waitB, _pmp_waitE, and _pmp_waitM.
Referenced by SSD1306_init().
{
    if (beg>=4) beg=4;
    _pmp_waitB = beg-1;
    if (mid>=16) mid=16;
    _pmp_waitM = mid-1;
    if (end>=4) end=4;
    _pmp_waitE = end-1;
}
void PMP_setWidth (u8)
Definition at line 88 of file pmp.c.
References _pmp_width, PMP_MODE_16BIT, and PMP_MODE_8BIT.
Referenced by SSD1306_init().
{
    if ((width==16) || (width==PMP_MODE_16BIT))
        _pmp_width = PMP_MODE_16BIT;
    else
        _pmp_width = PMP_MODE_8BIT;
}
void PMP_write (u16)
Definition at line 391 of file pmp.c.
References _pmp_width, high8, low8, PMP_MODE_16BIT, and PMP_wait.
{
    if (_pmp_width == PMP_MODE_16BIT)
    {
        PMP_wait(); // wait for PMP to be available
        PMDIN1L = low8(value);
        PMP_wait(); // wait for PMP to be available
        PMDIN1H = high8(value);
    }
    
    else
    {
        PMP_wait(); // wait for PMP to be available
        PMDIN1L = low8(value);
    }
}