/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/lcdi2c.c File Reference
#include <lcdi2c.h>
*
#include <pcf8574.h>
*
#include <stdarg.h>
*
#include <delay.c>
*
#include <i2c.c>
*
#include <printf.c>
*
Macros
#define __LCDI2C_C
Functions
void lcdi2c_backlight ()
void lcdi2c_noBacklight ()
void lcdi2c_clear ()
void lcdi2c_home ()
void lcdi2c_noAutoscroll ()
void lcdi2c_autoscroll ()
void lcdi2c_rightToLeft ()
void lcdi2c_leftToRight ()
void lcdi2c_scrollDisplayRight ()
void lcdi2c_scrollDisplayLeft ()
void lcdi2c_blink ()
void lcdi2c_noBlink ()
void lcdi2c_cursor ()
void lcdi2c_noCursor ()
void lcdi2c_display ()
void lcdi2c_noDisplay ()
void lcdi2c_setCursor (u8 col, u8 line)
void lcdi2c_clearLine (u8 line)
void lcdi2c_write (char c)
void lcdi2c_printf (char *fmt,...)
void lcdi2c_newchar (const u8 *c, u8 char_code)
void lcdi2c_newpattern ()
void lcdi2c_init (u8 numcol, u8 numline, u8 i2c_address)
Variables
const u8 car0 [8]
const u8 car1 [8]
const u8 car2 [8]
const u8 car3 [8]
const u8 car4 [8]
const u8 car5 [8]
const u8 car6 [8]
const u8 car7 [8]
const u8 car8 [8]
const u8 car9 [8]
const u8 car10 [8]
const u8 car11 [8]
const u8 car12 [8]
u8 numcolmax
u8 numlinemax
u8 Backlight = 0
VARIABLES GLOBALES.
u8 PCF8574_address
PCF8574_t PCF8574_data
Macro Definition Documentation
#define __LCDI2C_C
Definition at line 73 of file lcdi2c.c.
Function Documentation
void lcdi2c_autoscroll ()
Definition at line 342 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYSHIFTINCREMENT.
{
    lcdi2c_send8(LCD_ENTRYSHIFTINCREMENT, LCD_CMD);
}
void lcdi2c_backlight ()
Definition at line 291 of file lcdi2c.c.
References Backlight, I2C1, I2C_send(), LCD_BL, PCF8574_address, and PCF8574_t::val.
Referenced by lcdi2c_init().
{
    Backlight = 1; // 0 = ON since PCF8574 is logical inverted
    LCD_BL = Backlight;
    I2C_send(I2C1, PCF8574_address, PCF8574_data.
      val);
}
void lcdi2c_blink ()
Definition at line 387 of file lcdi2c.c.
References LCD_BLINKON, and LCD_CMD.
{
    lcdi2c_send8(LCD_BLINKON, LCD_CMD);
}
void lcdi2c_clear ()
Definition at line 313 of file lcdi2c.c.
References Delayms(), LCD_CMD, and LCD_DISPLAY_CLEAR.
Referenced by lcdi2c_init().
{
    lcdi2c_send8(LCD_DISPLAY_CLEAR, LCD_CMD);
    Delayms(2); // Wait for more than 1.64ms
}
void lcdi2c_clearLine (u8 line)
Definition at line 458 of file lcdi2c.c.
References ESPACE, lcdi2c_setCursor(), lcdi2c_write(), and numcolmax.
{
    u8 i;
    lcdi2c_setCursor(0, line);
    for (i = 0; i < numcolmax; i++)
        lcdi2c_write(ESPACE); // affiche des espaces
}
void lcdi2c_cursor ()
Definition at line 405 of file lcdi2c.c.
References LCD_CMD, and LCD_CURSORON.
{
    lcdi2c_send8(LCD_CURSORON, LCD_CMD);
}
void lcdi2c_display ()
Definition at line 423 of file lcdi2c.c.
References LCD_CMD, and LCD_DISPLAYON.
{
    lcdi2c_send8(LCD_DISPLAYON, LCD_CMD);
}
void lcdi2c_home ()
Definition at line 323 of file lcdi2c.c.
References Delayms(), LCD_CMD, and LCD_CURSOR_HOME.
Referenced by lcdi2c_init().
{
    lcdi2c_send8(LCD_CURSOR_HOME, LCD_CMD);
    Delayms(2); // Wait for more than 1.64ms
}
void lcdi2c_init (u8 numcol, u8 numline, u8 i2c_address)
Definition at line 553 of file lcdi2c.c.
References Delayms(), Delayus(), I2C1, I2C_100KHZ, I2C_1MHZ, I2C_init(), I2C_MASTER_MODE, LCD_CMD, LCD_DISPLAY_CLEAR, LCD_DISPLAY_ON, LCD_ENTRY_MODE_SET, LCD_SYSTEM_SET_4BITS, lcdi2c_backlight(), lcdi2c_clear(), lcdi2c_home(), numcolmax, numlinemax, PCF8574_address, PCF8574_t::val, and _Byte_::val.
{
    numcolmax = numcol - 1;
    numlinemax = numline - 1;
    PCF8574_address = 0b01001110 | i2c_address;
    PCF8574_data.val = 0;
    //I2C_init(I2C1, I2C_MASTER_MODE, I2C_100KHZ);
    //I2C_init(I2C1, I2C_MASTER_MODE, I2C_400KHZ);
    I2C_init(I2C1, I2C_MASTER_MODE, I2C_1MHZ);
    Delayms(15); // Wait more than 15 ms after VDD rises to 4.5V
    lcdi2c_send4(0x30, LCD_CMD); // 0x30 - Mode 8 bits
    Delayms(5); // Wait for more than 4.1 ms
    lcdi2c_send4(0x30, LCD_CMD); // 0x30 - Mode 8 bits
    Delayus(100); // Wait more than 100 μs
    lcdi2c_send4(0x30, LCD_CMD); // 0x30 - Mode 8 bits
    Delayus(100); // Wait more than 100 μs
    lcdi2c_send4(0x20, LCD_CMD); // 0x20 - Mode 4 bits
    lcdi2c_send8(LCD_SYSTEM_SET_4BITS, LCD_CMD);// 0x28 - Mode 4 bits - 2 Lignes
       - 5x8
    lcdi2c_send8(LCD_ENTRY_MODE_SET, LCD_CMD); // 0x06 - Increment + Display not
       shifted (Déplacement automatique du curseur)
    lcdi2c_backlight(); // backlight on
/*
    lcdi2c_display();
    lcdi2c_noBlink();
    lcdi2c_noCursor();
    lcdi2c_noAutoscroll();
    lcdi2c_setCursor(0, 0);
*/
    lcdi2c_clear();
    lcdi2c_home();
    #ifndef __32MX220F032D__
    //lcdi2c_newpattern(); // Implante les nouveaux caracteres
    #endif
}
void lcdi2c_leftToRight ()
Definition at line 360 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYLEFT.
{
    lcdi2c_send8(LCD_ENTRYLEFT, LCD_CMD);
}
void lcdi2c_newchar (const u8 * c, u8 char_code)
Definition at line 503 of file lcdi2c.c.
References LCD_ADRESS_CGRAM, LCD_CMD, and LCD_DATA.
Referenced by lcdi2c_newpattern().
{
    u8 i, a;
    // les caractères sont logés dans le CGRAM du LCD à partir de l'adresse 0x40.
    a = (char_code << 3) | LCD_ADRESS_CGRAM;
    for(i=0; i<8; i++)
    {
        lcdi2c_send8(a, LCD_CMD);
        lcdi2c_send8(c[i], LCD_DATA);
        a++;
    };
}
void lcdi2c_newpattern ()
Definition at line 521 of file lcdi2c.c.
References ACIRC, AGRAVE, car0, car1, car2, car3, car4, car5, car6, car7, CCEDIL, EACUTE, ECIRC, EGRAVE, ETREMA, EURO, and lcdi2c_newchar().
{
    lcdi2c_newchar(car0, ACIRC); // â
    lcdi2c_newchar(car1, AGRAVE); // à
    lcdi2c_newchar(car2, CCEDIL); // ç
    lcdi2c_newchar(car3, EACUTE); // é
    lcdi2c_newchar(car4, EGRAVE); // è
    lcdi2c_newchar(car5, ECIRC); // ê
    lcdi2c_newchar(car6, ETREMA); // ë
    lcdi2c_newchar(car7, EURO); // €
    //lcdi2c_newchar(car8, ICIRC); // î
    //lcdi2c_newchar(car9, ITREMA); // ï
    //lcdi2c_newchar(car10, OCIRC); // ô
    //lcdi2c_newchar(car11, UGRAVE); // ù
    //lcdi2c_newchar(car12, UCIRC); // û
}
void lcdi2c_noAutoscroll ()
Definition at line 333 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYSHIFTDECREMENT.
{
    lcdi2c_send8(LCD_ENTRYSHIFTDECREMENT, LCD_CMD);
}
void lcdi2c_noBacklight ()
Definition at line 302 of file lcdi2c.c.
References Backlight, I2C1, I2C_send(), LCD_BL, PCF8574_address, and PCF8574_t::val.
{
    Backlight = 0; // 1 = OFF since PCF8574 is logical inverted
    LCD_BL = Backlight;
    I2C_send(I2C1, PCF8574_address, PCF8574_data.
      val);
}
void lcdi2c_noBlink ()
Definition at line 396 of file lcdi2c.c.
References LCD_BLINKOFF, and LCD_CMD.
{
    lcdi2c_send8(LCD_BLINKOFF, LCD_CMD);
}
void lcdi2c_noCursor ()
Definition at line 414 of file lcdi2c.c.
References LCD_CMD, and LCD_CURSOROFF.
{
    lcdi2c_send8(LCD_CURSOROFF, LCD_CMD);
}
void lcdi2c_noDisplay ()
Definition at line 432 of file lcdi2c.c.
References LCD_CMD, and LCD_DISPLAYOFF.
{
    lcdi2c_send8(LCD_DISPLAYOFF, LCD_CMD);
}
void lcdi2c_printf (char * fmt, ...)
Definition at line 483 of file lcdi2c.c.
References lcdi2c_write(), and pprintf().
{
    va_list args;
    va_start(args, fmt);
    pprintf(lcdi2c_write, fmt, args);
    va_end(args);
}
void lcdi2c_rightToLeft ()
Definition at line 351 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYRIGHT.
{
    lcdi2c_send8(LCD_ENTRYRIGHT, LCD_CMD);
}
void lcdi2c_scrollDisplayLeft ()
Definition at line 378 of file lcdi2c.c.
References LCD_CMD, LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVELEFT.
{
    lcdi2c_send8(LCD_CURSORSHIFT | LCD_DISPLAYMOVE |
      LCD_MOVELEFT, LCD_CMD);
}
void lcdi2c_scrollDisplayRight ()
Definition at line 369 of file lcdi2c.c.
References LCD_CMD, LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVERIGHT.
{
    lcdi2c_send8(LCD_CURSORSHIFT | LCD_DISPLAYMOVE |
      LCD_MOVERIGHT, LCD_CMD);
}
void lcdi2c_setCursor (u8 col, u8 line)
Definition at line 443 of file lcdi2c.c.
References LCD_CMD, LCD_SETDDRAMADDR, numcolmax, and numlinemax.
Referenced by lcdi2c_clearLine().
{
    int row_offsets[] = { 0x00, 0x40, 0x14, 0x54 };
    if (line > numlinemax)
        line = numlinemax - 1; // we count rows starting w/0
    if (col > numcolmax)
        col = numcolmax - 1; // we count rows starting w/0
    lcdi2c_send8(LCD_SETDDRAMADDR | (col + row_offsets[line]),
      LCD_CMD);
}
void lcdi2c_write (char c)
Definition at line 473 of file lcdi2c.c.
References LCD_DATA.
{
    lcdi2c_send8(c, LCD_DATA);
}
Variable Documentation
u8 Backlight = 0
VARIABLES GLOBALES.
Definition at line 229 of file lcdi2c.c.
Referenced by lcdi2c_backlight(), and lcdi2c_noBacklight().
const u8 car0[8]
Initial value:
={
        0b00000100,
        0b00001010,
        0b00001110,
        0b00000001,
        0b00001111,
        0b00010001,
        0b00001111,
        0b00000000
    }
Definition at line 91 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car1[8]
Initial value:
={
        0b00000100,
        0b00000010,
        0b00001110,
        0b00000001,
        0b00001111,
        0b00010001,
        0b00001111,
        0b00000000
    }
Definition at line 101 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car10[8]
Initial value:
={
        0b00000100,
        0b00001010,
        0b00001110,
        0b00010001,
        0b00010001,
        0b00010001,
        0b00001110,
        0b00000000
    }
Definition at line 191 of file lcdi2c.c.
const u8 car11[8]
Initial value:
={
        0b00000100,
        0b00000010,
        0b00010001,
        0b00010001,
        0b00010001,
        0b00010011,
        0b00001101,
        0b00000000
    }
Definition at line 201 of file lcdi2c.c.
const u8 car12[8]
Initial value:
={
        0b00000100,
        0b00001010,
        0b00010001,
        0b00010001,
        0b00010001,
        0b00010011,
        0b00001101,
        0b00000000
    }
Definition at line 211 of file lcdi2c.c.
const u8 car2[8]
Initial value:
={
        0b00001110,
        0b00010000,
        0b00010000,
        0b00010001,
        0b00001110,
        0b00000100,
        0b00001100,
        0b00000000
    }
Definition at line 111 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car3[8]
Initial value:
={
        0b00000100,
        0b00001000,
        0b00001110,
        0b00010001,
        0b00011111,
        0b00010000,
        0b00001110,
        0b00000000
    }
Definition at line 121 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car4[8]
Initial value:
={
        0b00000100,
        0b00000010,
        0b00001110,
        0b00010001,
        0b00011111,
        0b00010000,
        0b00001110,
        0b00000000
    }
Definition at line 131 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car5[8]
Initial value:
={
        0b00000100,
        0b00001010,
        0b00001110,
        0b00010001,
        0b00011111,
        0b00010000,
        0b00001110,
        0b00000000
    }
Definition at line 141 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car6[8]
Initial value:
={
        0b00001010,
        0b00000000,
        0b00001110,
        0b00010001,
        0b00011111,
        0b00010000,
        0b00001110,
        0b00000000
    }
Definition at line 151 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car7[8]
Initial value:
={
        0b00000111,
        0b00001000,
        0b00011110,
        0b00001000,
        0b00011110,
        0b00001000,
        0b00000111,
        0b00000000
    }
Definition at line 161 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car8[8]
Initial value:
={
        0b00000100,
        0b00001010,
        0b00001100,
        0b00000100,
        0b00000100,
        0b00000100,
        0b00001110,
        0b00000000
    }
Definition at line 171 of file lcdi2c.c.
const u8 car9[8]
Initial value:
={
        0b00001010,
        0b00000000,
        0b00001100,
        0b00000100,
        0b00000100,
        0b00000100,
        0b00001110,
        0b00000000
    }
Definition at line 181 of file lcdi2c.c.
u8 numcolmax
Definition at line 227 of file lcdi2c.c.
u8 numlinemax
Definition at line 228 of file lcdi2c.c.
u8 PCF8574_address
Definition at line 230 of file lcdi2c.c.
PCF8574_t PCF8574_data
Definition at line 231 of file lcdi2c.c.