/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/debug.c File Reference
#include <stdarg.h>
*
Macros
#define __DEBUG_C
Functions
void debug (const char *format,...)
Macro Definition Documentation
#define __DEBUG_C
Definition at line 10 of file debug.c.
Function Documentation
void debug (const char * format, ...)
Definition at line 14 of file debug.c.
References serial1init(), serial2init(), and serial2printf().
{
    va_list args;
    va_start(args, format);
    #ifdef NODEBUG
    #endif
    #ifdef USBCDCDEBUG
        #include <__cdc.c>
        CDCprintf("debug: ");
        CDCprintf(format, args);
        CDCprintf("\r\n");
    #endif
    #ifdef UART1DEBUG
        #include <serial.c>
        serial1init(9600);
        serial1printf("debug: ");
        serial1printf(format, args);
        serial1printf("\r\n");
    #endif
    #ifdef UART2DEBUG
        #include <serial.c>
        serial2init(9600);
        serial2printf("debug: ");
        serial2printf(format, args);
        serial2printf("\r\n");
    #endif
    va_end(args);
}