/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/stepper.c File Reference
#include <system.c>
*
#include <digitalw.c>
*
#include <pwm.c>
*
#include <interrupt.c>
*
Macros
#define __STEPPER_C
#define __STEPPER__
#define TABLE_DEPTH 32
#define INDEX_MASK TABLE_DEPTH - 1
Functions
void Stepper_init (int, int, int, int, int)
int Stepper_step (int, int, int)
void Stepper_stepMotor (int)
void ISR_wrapper_vector_4 (void)
void stepper_interrupt (void)
Variables
int this_direction
int this_steps_per_rev
int this_number_of_steps
volatile int this_current_step
int this_number_of_microsteps
volatile int this_steps_left
int this_pin_count
int this_jump
int this_motor_pin_A
int this_motor_pin_B
int this_motor_pin_C
int this_motor_pin_D
int wave_table [4]
int steps_table [8]
int sine_table [TABLE_DEPTH+1]
Macro Definition Documentation
#define __STEPPER__
Definition at line 101 of file stepper.c.
#define __STEPPER_C
Definition at line 99 of file stepper.c.
#define INDEX_MASK TABLE_DEPTH - 1
Definition at line 143 of file stepper.c.
Referenced by Stepper_stepMotor().
#define TABLE_DEPTH 32
Definition at line 142 of file stepper.c.
Referenced by Stepper_step().
Function Documentation
void ISR_wrapper_vector_4 (void)
Definition at line 534 of file stepper.c.
References stepper_interrupt().
                                { stepper_interrupt(); }
void Stepper_init (int number_of_steps, int motor_pin_A, int motor_pin_B, int motor_pin_C, int motor_pin_D)
Definition at line 177 of file stepper.c.
References OUTPUT, pinmode(), this_current_step, this_direction, this_jump, this_motor_pin_A, this_motor_pin_B, this_motor_pin_C, this_motor_pin_D, this_number_of_microsteps, this_pin_count, this_steps_left, and this_steps_per_rev.
{
    if ((motor_pin_C + motor_pin_D) == 0)
    {
        // Pinguino pins for the motor control connection:
        this_motor_pin_A = motor_pin_A;
        this_motor_pin_B = motor_pin_B;
        // setup the pins on the microcontroller:
        pinmode(this_motor_pin_A, OUTPUT);
        pinmode(this_motor_pin_B, OUTPUT);
        // When there are only 2 pins, set the other two to 0:
        this_motor_pin_C = 0;
        this_motor_pin_D = 0;
        // pin_count is used by the stepMotor() method:
        this_pin_count = 2;
    }
    else
    {
        // Pinguino pins for the motor control connection:
        this_motor_pin_A = motor_pin_A;
        this_motor_pin_B = motor_pin_B;
        this_motor_pin_C = motor_pin_C;
        this_motor_pin_D = motor_pin_D;
        // setup the pins on the microcontroller:
        pinmode(this_motor_pin_A, OUTPUT);
        pinmode(this_motor_pin_B, OUTPUT);
        pinmode(this_motor_pin_C, OUTPUT);
        pinmode(this_motor_pin_D, OUTPUT);
        // pin_count is used by the stepMotor() method:
        this_pin_count = 4;
    }
    this_steps_per_rev = number_of_steps;// total number of steps for this motor
    this_current_step = 0; // which step the motor is on
    this_direction = 0; // motor direction
    //this_last_step_time = 0; // time stamp in ms of the last step taken
    this_number_of_microsteps = 1; // full steps per default
    this_jump = 1;
    this_steps_left = 0;
}
void stepper_interrupt (void)
Definition at line 538 of file stepper.c.
References INT_TIMER1, IntClearFlag(), IntGetFlag(), Stepper_stepMotor(), this_current_step, this_direction, this_number_of_steps, and this_steps_left.
{
    // is this an TMR1 interrupt ?
    //if (IFS0bits.T1IF)
    if (IntGetFlag(INT_TIMER1))
    {
        if (this_steps_left > 0)
        {
            // increment the step number,
            if (this_direction == 1)
            {
                this_current_step += 1;
                if (this_current_step == this_number_of_steps)
                    this_current_step = 0;
            }
            // decrement the step number,
            else
            {
                if (this_current_step == 0)
                    this_current_step = this_number_of_steps;
                this_current_step -= 1;
            }
            
            // decrement the steps left:
            this_steps_left -= 1;
            // step the motor
            Stepper_stepMotor(this_current_step);
        }
        IntClearFlag(INT_TIMER1);
        //IFS0CLR = 1 << 4;
    }
}
int Stepper_step (int steps_to_move, int microsteps, int revolutionPerMinute)
Definition at line 306 of file stepper.c.
References cycles_per_step, GetPeripheralClock(), INT_SYSTEM_CONFIG_MULT_VECTOR, INT_TIMER1, INT_TIMER1_VECTOR, IntClearFlag(), IntConfigureSystem(), IntEnable(), IntSetVectorPriority(), PWM_init(), PWM_set_frequency(), TABLE_DEPTH, this_direction, this_jump, this_number_of_microsteps, this_number_of_steps, this_steps_left, and this_steps_per_rev.
{
    int delay_us_per_step; // delay between 2 steps
    int delay_ms_per_move; // delay for the whole move
    int cycles_per_step; // number of cycles between 2 steps
    int prescaler = 0; // 0 = 1:1 default prescale value
                                        // 1 = 1:8 prescale value
                                        // 2 = 1:64 prescale value
                                        // 3 = 1:256 prescale value
    // wait previous command to be finished
    while (this_steps_left > 0);
    switch (microsteps)
    {
        case 0:
            // wave steps todo
            this_number_of_microsteps = 1;
            break;
        case 1:
            this_number_of_microsteps = 1;
            break;
    
        default:
            if ((microsteps % 2) == 1) // odd ?
                this_number_of_microsteps = microsteps + 1;
            else
                this_number_of_microsteps = microsteps;
            if (this_number_of_microsteps > 32)
                this_number_of_microsteps = 32;
            if (this_number_of_microsteps < 2)
                this_number_of_microsteps = 2;
            break;
    }
    
    // determine direction based on whether steps_to_move is + or -:
    if (steps_to_move > 0) this_direction = 1;
    if (steps_to_move < 0) this_direction = 0;
    // change number of steps
    this_number_of_steps = this_steps_per_rev *
      this_number_of_microsteps;
    steps_to_move = this_number_of_steps;
    // how many steps to take ?
    this_steps_left = steps_to_move > 0 ? steps_to_move : -steps_to_move;
    // microsteps ?
    if (this_number_of_microsteps > 2)
    {
        PWM_init(); // Timer3
        PWM_set_frequency(100000); // 40KHz
        this_jump = (TABLE_DEPTH / this_number_of_microsteps);
    }
    
    // delay between 2 steps (1 mn = 60 * 1000 * 1000 us)
    delay_us_per_step = 60 * 1000 * 1000 / revolutionPerMinute /
      this_number_of_steps;
    delay_ms_per_move = delay_us_per_step * steps_to_move / 1000;
    cycles_per_step = delay_us_per_step * (GetPeripheralClock() / 1000 / 1000);
    
    while (cycles_per_step > 0xFFFF)
    {
        prescaler += 1;
        if (prescaler > 2)
        {
            prescaler = 3;
            cycles_per_step /= 4;
        }
        else
        {
            cycles_per_step /= 8;
        }
    }
    // Timer1 Configuration
    IntConfigureSystem(INT_SYSTEM_CONFIG_MULT_VECTOR);
    //INTCONSET = 0x1000;
    T1CON = prescaler << 4; // prescaler, internal peripheral clock
    TMR1 = 0x00; // clear timer register
    PR1 = cycles_per_step; // load period register
    IntSetVectorPriority(INT_TIMER1_VECTOR, 7, 3);
    //IPC1SET = 7; // select interrupt priority and sub-priority
    IntClearFlag(INT_TIMER1);
    //IFS0CLR = 1 << 4; //INT_TIMER1_VECTOR; // clear interrupt flag
    IntEnable(INT_TIMER1);
    //IEC0SET = 1 << 4; //INT_TIMER1_VECTOR; // enable timer 1 interrupt
    T1CONSET = 0x8000; // start timer 1
    // return time (ms) to revolve the whole steps to move
    return (delay_ms_per_move);
}
void Stepper_stepMotor (int thisStep)
In practice, the current in one winding is kept constant over half of the complete step and current in the other winding is varied as a function of sinθ to maximize the motor torque.
Definition at line 404 of file stepper.c.
References analogwrite(), digitalwrite(), INDEX_MASK, sine_table, steps_table, this_jump, this_motor_pin_A, this_motor_pin_B, this_motor_pin_C, this_motor_pin_D, this_number_of_microsteps, this_pin_count, and wave_table.
{
    int index;
    int current_microstep;
    int t, inc, dec;
    // wave-step
    if (this_number_of_microsteps == 0)
    {
        // step the motor to step number 0, 1, 2, or 3:
        t = wave_table [ (thisStep % 4) ];
        // Winding A
        digitalwrite(this_motor_pin_A, t >> 0 & 1); // bit 0
        digitalwrite(this_motor_pin_B, t >> 1 & 1); // bit 1
        // Winding B
        if (this_pin_count == 4)
        {
            digitalwrite(this_motor_pin_C, t >> 2 & 1); // bit 2
            digitalwrite(this_motor_pin_D, t >> 3 & 1); // bit 3
        }
    }
    // full-step
    else if (this_number_of_microsteps == 1)
    {
        // step the motor to step number 0, 1, 2, or 3:
        t = steps_table [ (thisStep % 4) * 2 ];
        // Winding A
        digitalwrite(this_motor_pin_A, t >> 0 & 1); // bit 0
        digitalwrite(this_motor_pin_B, t >> 1 & 1); // bit 1
        // Winding B
        if (this_pin_count == 4)
        {
            digitalwrite(this_motor_pin_C, t >> 2 & 1); // bit 2
            digitalwrite(this_motor_pin_D, t >> 3 & 1); // bit 3
        }
    }
    // half-step
    else if (this_number_of_microsteps == 2)
    {
        // step the motor to step number 0, 1, 2, 3, 4, 5, 6 or 7
        t = steps_table [ thisStep % 8 ];
        // Winding A
        digitalwrite(this_motor_pin_A, t >> 0 & 1); // bit 0
        digitalwrite(this_motor_pin_B, t >> 1 & 1); // bit 1
        // Winding B
        if (this_pin_count == 4)
        {
            digitalwrite(this_motor_pin_C, t >> 2 & 1); // bit 2
            digitalwrite(this_motor_pin_D, t >> 3 & 1); // bit 3
        }
    }
    
    // microstepping (4, 8, 16 or 32 microsteps / step)
    //#ifdef __MICROSTEPPING__
    else if (this_number_of_microsteps > 2)
    {
        // from 0 to total number of microsteps - 1
        current_microstep = (thisStep % this_number_of_microsteps);// + 1;
        
        // table index is function of total microsteps number
        // this_jump = (TABLE_DEPTH / this_number_of_microsteps);
        index = current_microstep * this_jump;
        // from 0 to 90 degrees (from 0 to 1023)
        // increase current in next active coil
        inc = sine_table[ index & INDEX_MASK ];
        // from 90 to 0 degrees (from 1023 to 0)
        // decrease current in active coil
        dec = sine_table[ INDEX_MASK - (index & INDEX_MASK) ];
        switch ((thisStep / this_number_of_microsteps) % 4)
        {
            case 0: // from A to C
                analogwrite(this_motor_pin_A, (u16) dec);
                analogwrite(this_motor_pin_B, (u16) 0);
                analogwrite(this_motor_pin_C, (u16) inc);
                analogwrite(this_motor_pin_D, (u16) 0);
                break;
            case 1: // from C to B
                analogwrite(this_motor_pin_A, (u16) 0);
                analogwrite(this_motor_pin_B, (u16) inc);
                analogwrite(this_motor_pin_C, (u16) dec);
                analogwrite(this_motor_pin_D, (u16) 0);
                break;
            case 2: // from B to D
                analogwrite(this_motor_pin_A, (u16) 0);
                analogwrite(this_motor_pin_B, (u16) dec);
                analogwrite(this_motor_pin_C, (u16) 0);
                analogwrite(this_motor_pin_D, (u16) inc);
                break;
            case 3: // from D to A
                analogwrite(this_motor_pin_A, (u16) inc);
                analogwrite(this_motor_pin_B, (u16) 0);
                analogwrite(this_motor_pin_C, (u16) 0);
                analogwrite(this_motor_pin_D, (u16) dec);
                break;
        }
    }
    //#endif
}
Variable Documentation
int sine_table[TABLE_DEPTH+1]
Initial value:
= {
    50,100,150,200,249,297,345,391,437,482,526,568,609,649,687,723,
    758,791,822,851,877,902,925,945,963,979,992,1003,1012,1018,1022,1023
    }
Definition at line 146 of file stepper.c.
Referenced by Stepper_stepMotor().
int steps_table[8]
Initial value:
= {
    0b1010, 0b0010, 0b0110, 0b0100, 0b0101, 0b0001, 0b1001, 0b1000
    }
Definition at line 132 of file stepper.c.
volatile int this_current_step
Definition at line 114 of file stepper.c.
int this_direction
Definition at line 111 of file stepper.c.
int this_jump
Definition at line 118 of file stepper.c.
int this_motor_pin_A
Definition at line 122 of file stepper.c.
int this_motor_pin_B
Definition at line 123 of file stepper.c.
int this_motor_pin_C
Definition at line 124 of file stepper.c.
int this_motor_pin_D
Definition at line 125 of file stepper.c.
int this_number_of_microsteps
Definition at line 115 of file stepper.c.
int this_number_of_steps
Definition at line 113 of file stepper.c.
int this_pin_count
Definition at line 117 of file stepper.c.
volatile int this_steps_left
Definition at line 116 of file stepper.c.
int this_steps_per_rev
Definition at line 112 of file stepper.c.
int wave_table[4]
Initial value:
= {
    0b1000, 0b0010, 0b0100, 0b0001
    }
Definition at line 128 of file stepper.c.