/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/graphics.c File Reference
Macros
#define __GRAPHIC_C
#define _abs_(a) (((a)> 0) ? (a) : -(a))
Functions
void drawPixel (u16 x, u16 y)
void drawCircle (u16 x, u16 y, u16 radius)
void fillCircle (u16 x, u16 y, u16 radius)
void drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
void drawBitmap (u16 xo, u16 yo, u16 w, u16 h, const u16 *bitmap)
Macro Definition Documentation
#define __GRAPHIC_C
Definition at line 51 of file graphics.c.
#define _abs_(a) (((a)> 0) ? (a) : -(a))
Definition at line 53 of file graphics.c.
Referenced by drawLine().
Function Documentation
void drawBitmap (u16 xo, u16 yo, u16 w, u16 h, const u16 * bitmap)
Definition at line 532 of file graphics.c.
References drawPixel(), and h.
Referenced by ILI9325_drawBitmap().
{
    u16 i, j;
    for (j=0; j<h; j++)
    {
        for (i=0; i<w; i++)
        {
            //setColor(bitmap[j * w + i + 2]);
            drawPixel(xo+i, yo+j);
            /*
            ILI9325_write(WriteDatatoGRAM, bitmap[ (j * w) + i + 2]);
            ILI9325_write(GRAMHorizontalAddressSet, xo + i);
            ILI9325_write(GRAMVerticalAddressSet, yo + j);
            */
        }
    }
}
void drawCircle (u16 x, u16 y, u16 radius)
Definition at line 62 of file graphics.c.
References drawPixel().
{
    s16 f = 1 - radius;
    s16 ddF_x = 1;
    s16 ddF_y = -2 * radius;
    s16 x1 = 0;
    s16 y1 = radius;
    drawPixel(x, y + radius);
    drawPixel(x, y - radius);
    drawPixel(x + radius, y);
    drawPixel(x - radius, y);
    while(x1 < y1)
    {
        if(f >= 0)
        {
            y1--;
            ddF_y += 2;
            f += ddF_y;
        }
        x1++;
        ddF_x += 2;
        f += ddF_x;
        drawPixel(x + x1, y + y1);
        drawPixel(x - x1, y + y1);
        drawPixel(x + x1, y - y1);
        drawPixel(x - x1, y - y1);
        drawPixel(x + y1, y + x1);
        drawPixel(x - y1, y + x1);
        drawPixel(x + y1, y - x1);
        drawPixel(x - y1, y - x1);
    }
}
void drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Definition at line 106 of file graphics.c.
References _abs_, drawPixel(), x, and y.
{
    s16 steep, t;
    s16 deltax, deltay, error;
    s16 x, y;
    s16 ystep;
    
    // simple clipping is done in the drawPixel routine
/*
    if ((x0 < 0) || (x0 > HRES)) return;
    if ((x1 < 0) || (x1 > HRES)) return;
    if ((y0 < 0) || (y0 > VRES)) return;
    if ((y1 < 0) || (y1 > VRES)) return;
*/
    
    steep = _abs_(y1 - y0) > _abs_(x1 - x0);
    if (steep)
    { // swap x and y
        t = x0; x0 = y0; y0 = t;
        t = x1; x1 = y1; y1 = t;
    }
    if (x0 > x1)
    { // swap ends
        t = x0; x0 = x1; x1 = t;
        t = y0; y0 = y1; y1 = t;
    }
    deltax = x1 - x0;
    deltay = _abs_(y1 - y0);
    error = 0;
    y = y0;
    if (y0 < y1) ystep = 1; else ystep = -1;
    for (x = x0; x < x1; x++)
    {
        if (steep)
            drawPixel(y,x);
        else
            drawPixel(x,y);
            
        error += deltay;
        if ((error<<1) >= deltax)
        {
            y += ystep;
            error -= deltax;
        }
    }
}
void drawPixel (u16 x, u16 y)
Definition at line 960 of file ili9325.c.
{
    ILI9325_drawPixel(x, y);
}
void fillCircle (u16 x, u16 y, u16 radius)
Definition at line 97 of file graphics.c.
References drawPixel().
{
    s16 x1, y1;
    for(y1=-radius; y1<=radius; y1++)
        for(x1=-radius; x1<=radius; x1++)
            if(x1*x1+y1*y1 <= radius*radius)
                drawPixel(x+x1, y+y1);
}