/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/millis.c File Reference
#include <interrupt.c>
*
#include <system.c>
*
Macros
#define __MILLIS__
Functions
void millis_init (void)
u32 millis ()
u32 micros ()
void Tmr2Interrupt ()
Variables
volatile u32 _millis
volatile u32 _micros
Macro Definition Documentation
#define __MILLIS__
Definition at line 29 of file millis.c.
Function Documentation
u32 micros ()
Definition at line 77 of file millis.c.
References _micros, and _millis.
{
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        // The code for the 220 has not been tested!
       // return 1000*_millis + (1000*(65535-TMR2))/_tmr2; // Tested but gives more microsseconds
       _micros = 1000*_millis + (1000*(TMR2 - _tmr2))/_tmr2; // working good micros()
       return _micros;
    #else
        return 1000*_millis + (1000*TMR2)/PR2;
    #endif
}
u32 millis ()
Definition at line 72 of file millis.c.
References _millis.
{
    return(_millis);
}
void millis_init (void)
Definition at line 46 of file millis.c.
References _millis, GetPeripheralClock(), INT_SYSTEM_CONFIG_MULT_VECTOR, and IntConfigureSystem().
{
    u32 pf; // peripheral bus frequency
    pf = GetPeripheralClock();
    IntConfigureSystem(INT_SYSTEM_CONFIG_MULT_VECTOR);
    T2CON=0;
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    _tmr2 = pf / 1000 / 2; // 27 - 08- 2013: preserve this for the micros() function
    TMR2 = 65535 - _tmr2;
   _tmr2_upd= TMR2; // 26-02-2013 : correction : we will need to refresh in the interrupt with 65535 -
       _tmr2 to give the 1mS in the next interrupts
    IPC2bits.T2IP=1;
    IPC2bits.T2IS=1;
    IFS0bits.T2IF=0;
    IEC0bits.T2IE=1;
    #else
    TMR2=0x00;
    PR2 = pf / 1000 / 2; //0x4E00;
    IPC2SET = 0x0000000D;
    IFS0CLR = 0x00000100;
    IEC0SET = 0x00000100;
    #endif
    T2CONSET = 0x8010; // prescale=1/2
    _millis = 0;
}
void Tmr2Interrupt ()
Definition at line 94 of file millis.c.
References _millis, INT_TIMER2, IntClearFlag(), and IntGetFlag().
{
    // is this an TMR2 interrupt ?
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    TMR2 = _tmr2_upd; // 0xD910; // because PR2 don't work on PIC32MX220F032D
    if (IFS0bits.T2IF)
    #else
    if (IntGetFlag(INT_TIMER2)) // TODO : add PIC32_PINGUINO_220 support
    #endif
    {
        #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        IFS0bits.T2IF=0;
        #else
        //IFS0CLR=0x00000100;
        IntClearFlag(INT_TIMER2);
        #endif
        _millis++;
    }
}
Variable Documentation
volatile u32 _micros
Definition at line 39 of file millis.c.
Referenced by micros().
volatile u32 _millis
This variable is accessed both by the ISR and `normal` code. It must be declared as `volatile` to prevent caching.
Definition at line 38 of file millis.c.