/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/spi.c File Reference
#include <system.c>
*
#include <interrupt.c>
*
Macros
#define __SPI__
#define SPIx 1
#define SPI_MASTER 1
#define SPI_MASTER8 1
#define SPI_MASTER16 2
#define SPI_MASTER32 3
#define SPI_SLAVE 0
#define SPI_LSBFIRST 0
#define SPI_MSBFIRST 1
#define SPI_SMPMID 0
#define SPI_SMPEND 1
#define SPI_PBCLOCK_DIV2 2
#define SPI_PBCLOCK_DIV4 4
#define SPI_PBCLOCK_DIV8 8
#define SPI_PBCLOCK_DIV16 16
#define SPI_PBCLOCK_DIV32 32
#define SPI_PBCLOCK_DIV64 64
#define SPI_MODE0 0
#define SPI_MODE1 1
#define SPI_MODE2 2
#define SPI_MODE3 3
Functions
void SPI_setBitOrder (u8 bitorder)
void SPI_setDataMode (u8 mode)
void SPI_setMode (u8 mode)
u32 SPI_setClock (u32 speed)
void SPI_setClockDivider (u8 clock)
void SPI_close ()
void SPI_begin ()
Prototypes.
unsigned char SPI_write (unsigned char data_out)
unsigned char SPI_read (void)
void SPIxInterrupt (void)
Variables
u32 this_mode = SPI_MODE0
u32 this_clock = SPI_PBCLOCK_DIV64
u32 this_role = SPI_MASTER
u32 this_bitorder = SPI_MSBFIRST
u32 this_phase = SPI_SMPEND
Macro Definition Documentation
#define __SPI__
Microchip making changes to SPI SFR numbers and changing 2A to 3, and 3A to 4 but it needs a new processor.o and updated compiler libraries, not released at this time.
MX440 and MX460 have only 2 SPI ports
Definition at line 44 of file spi.c.
#define SPI_LSBFIRST 0
Definition at line 151 of file spi.c.
#define SPI_MASTER 1
Definition at line 145 of file spi.c.
#define SPI_MASTER16 2
Definition at line 147 of file spi.c.
#define SPI_MASTER32 3
Definition at line 148 of file spi.c.
#define SPI_MASTER8 1
Definition at line 146 of file spi.c.
#define SPI_MODE0 0
Definition at line 164 of file spi.c.
Referenced by SPI_begin().
#define SPI_MODE1 1
Definition at line 165 of file spi.c.
Referenced by SPI_begin().
#define SPI_MODE2 2
Definition at line 166 of file spi.c.
Referenced by SPI_begin().
#define SPI_MODE3 3
Definition at line 167 of file spi.c.
Referenced by SPI_begin().
#define SPI_MSBFIRST 1
Definition at line 152 of file spi.c.
#define SPI_PBCLOCK_DIV16 16
Definition at line 160 of file spi.c.
#define SPI_PBCLOCK_DIV2 2
Definition at line 157 of file spi.c.
#define SPI_PBCLOCK_DIV32 32
Definition at line 161 of file spi.c.
#define SPI_PBCLOCK_DIV4 4
Definition at line 158 of file spi.c.
#define SPI_PBCLOCK_DIV64 64
Definition at line 162 of file spi.c.
#define SPI_PBCLOCK_DIV8 8
Definition at line 159 of file spi.c.
#define SPI_SLAVE 0
Definition at line 149 of file spi.c.
Referenced by SPI_begin().
#define SPI_SMPEND 1
Definition at line 155 of file spi.c.
Referenced by SPI_begin().
#define SPI_SMPMID 0
Definition at line 154 of file spi.c.
#define SPIx 1
Definition at line 55 of file spi.c.
Function Documentation
void SPI_begin ()
Prototypes.
The following code assumes that none of the SPIx input pins are shared with an analog input. If so, the AD1PCFG and corresponding TRIS registers have to be properly configured.
Perform the following steps to set up the SPI module for the Master mode operation:
Disable the SPI interrupts in the respective IEC0/1 register.
Stop and reset the SPI module by clearing the ON bit.
Clear the receive buffer.
Clear the ENHBUF bit (SPIxCON<16>) if using Standard Buffer mode or set the bit if using Enhanced Buffer mode.
If SPI interrupts are not going to be used, skip this step and continue to step 5. Otherwise the following additional steps are performed: a) Clear the SPIx interrupt flags/events in the respective IFS0/1 register. b) Set the SPIx interrupt enable bits in the respective IEC0/1 register. c) Write the SPIx interrupt priority and subpriority bits in the respective IPC5/7 register.
Write the Baud Rate register, SPIxBRG.
Clear the SPIROV bit (SPIxSTAT<6>).
Write the desired settings to the SPIxCON register with MSTEN (SPIxCON<5>) = 1.
Enable SPI operation by setting the ON bit (SPIxCON<15>).
Definition at line 366 of file spi.c.
References Delayms(), DESELECT, IntDisable(), SPI_MODE0, SPI_MODE1, SPI_MODE2, SPI_MODE3, SPI_SLAVE, SPI_SLAVE_SS, SPI_SMPEND, this_clock, this_mode, this_phase, and this_role.
{
    unsigned char rData;
    // 1. Disable the SPI interrupts in the respective IEC0/1 register.
    IntDisable(INTFAULT);
    IntDisable(INTTXDONE);
    IntDisable(INTRXDONE);
    // 2. Stop and reset the SPI module by clearing the ON bit.
    SPICONF = 0;
    // 3. Clear the receive buffer.
    rData = BUFFER;
    // 4. Clear the ENHBUF bit (SPIxCON<16>) if using Standard Buffer mode.
    // This bit can only be written when the ON bit = 0
    // SPIENHBUF = 0; // not available on all devices
    // 5. If SPI interrupts are not going to be used, skip this step and
    // continue to step 6. Otherwise the following additional steps are performed:
    // a) Clear the SPIx interrupt flags/events in the respective IFS0/1 register.
/*
    IntClearFlag(INTFAULT);
    IntClearFlag(INTTXDONE);
    IntClearFlag(INTRXDONE);
    // b) Set the SPIx interrupt enable bits in the respective IEC0/1 register.
    IntEnable(INTFAULT);
    IntEnable(INTTXDONE);
    IntEnable(INTRXDONE);
    // c) Write the SPIx interrupt priority and subpriority bits in the respective IPC5/7 register.
    IntSetVectorPriority(INTVECTOR, 3, 1);
*/
    // 6. Write the Baud Rate register, SPIxBRG.
    CLKSPD = this_clock; // Default SPI_PBCLOCK_DIV64
    
    // 7. Clear the SPIROV bit (SPIxSTAT<6>).
    STATUS = 0; // clear the Overflow
    // 8. Write the desired settings to the SPIxCON register.
    switch (this_mode)
    {
        case SPI_MODE0: // SPI bus mode 0,0
          CKP = 0;
          CKE = 0; // data transmitted on falling edge
          break;
        case SPI_MODE1: // default SPI bus mode 0,1
          CKP = 0;
          CKE = 1; // data transmitted on falling edge
          break;
        case SPI_MODE2: // SPI bus mode 1,0
          CKP = 1; // clock idle state high
          CKE = 0; // data transmitted on rising edge
          break;
        case SPI_MODE3: // SPI bus mode 1,1
          CKP = 1; // clock idle state high
          CKE = 1; // data transmitted on falling edge
          break;
    }
    
    SMP = this_phase; // Input data sampled at end of middle of data output
       time
    MSTEN = this_role; // Master or Slave mode
    
    // The SSx pin is not driven by the SPI Master.
    // User have to drive the bit himself and pulse it before the SPI
    // transmission takes place.
    // He can therefore use any other I/O pin for that purpose,
    // but we provide one ;-)
    if (this_role != SPI_SLAVE)
    {
        #if defined(PINGUINO32MX250) || defined(PINGUINO32MX220)
            TRISBCLR = 1<<7; // RB7 is defined as SS1 pin (cf. io.c)
        #endif
    }
    // 9. Enable SPI operation by setting the ON bit (SPIxCON<15>).
    SPICONSET = 0x8000; // Set bit 15
}
void SPI_close ()
Disable all SPIx interrupts Stops and resets the SPIx Clears the receive buffer
Definition at line 329 of file spi.c.
References IntDisable().
{
    unsigned char rData;
    // Disable all SPIx interrupts
    IntDisable(INTFAULT);
    IntDisable(INTTXDONE);
    IntDisable(INTRXDONE);
    // Stops and resets the SPIx
    SPICONF = 0;
    // clears the receive buffer
    rData=BUFFER;
}
unsigned char SPI_read (void)
Definition at line 462 of file spi.c.
Referenced by disk_initialize().
{
    // return SPI_write(0);
    BUFFER = 0x00; // dummy byte to capture the response
    while (!STATRX); // wait until cycle complete
    return BUFFER; // return with byte read
}
void SPI_setBitOrder (u8 bitorder)
This function sets the order of the bits shifted out of and into the SPI bus, either LSBFIRST (least-significant bit first) or MSBFIRST (most-significant bit first).
Definition at line 187 of file spi.c.
References this_bitorder.
{
    this_bitorder = bitorder;
}
u32 SPI_setClock (u32 speed)
Baud Rate generation Fsck = Fpb / (2 * (SPIxBRG + 1) Therefore, the maximum baud rate possible is Fpb/2 (SPIxBRG = 0), and the minimum baud rate possible is Fpb/1024. SPIxBRG = (Fpb / (2 * Fsck)) - 1 speed must be in bauds
Definition at line 278 of file spi.c.
References GetPeripheralClock(), and this_clock.
{
    u32 Fpb;
    u16 clk;
    Fpb = GetPeripheralClock();
    if (speed > (Fpb / 2))
    {
        this_clock = 0; // use the maximum baud rate possible
        return (Fpb / 2); // and return the real speed
    }
    else
    {
        clk = (Fpb / (2 * speed)) - 1;
        
        if (clk > 511)
        {
            this_clock = 511; // use the minimum baud rate possible
            return (Fpb / 1024); // and return the real speed
        }
        else // ** fix for bug identified by dk=KiloOne
        {
            this_clock = clk; // use calculated divider-baud rate
            return (Fpb / (2*clk+1)); // and return the real speed
        }
    }
    //SPI_begin();
}
void SPI_setClockDivider (u8 clock)
This function sets the SPI clock divider relative to the peripheral clock. The dividers available are 2, 4, 8, 16, 32 and 64. The default setting is SPI_PBCLOCK_DIV64, which sets the SPI clock to 1/64 of the frequency of the peripheral clock.
Definition at line 316 of file spi.c.
References this_clock, and this_role.
{
    this_clock = clock/2 - 1;
    //SPI_begin();
}
void SPI_setDataMode (u8 mode)
This function sets the order of the bits shifted out of and into the SPI bus, either SPI_LSBFIRST (least-significant bit first) or SPI_MSBFIRST (most-significant bit first). This function sets the SPI data mode (clock polarity and phase) Bits CKP (SPIxCON<6>) and CKE (SPIxCON<8>) determine on which edge of the clock data transmission occurs. Modes available are SPI_MODE0, SPI_MODE1, SPI_MODE2, or SPI_MODE3 Mode CKP CKE 0 0 0 1 0 1 2 1 0 3 1 1
Definition at line 250 of file spi.c.
References this_mode.
{
    this_mode = mode;
    //SPI_begin();
}
void SPI_setMode (u8 mode)
This function sets the SPI mode. Possible values are SPI_MASTER or SPI_SLAVE. The default setting is SPI_MASTER.
Definition at line 263 of file spi.c.
References this_clock, and this_role.
{
    this_role = mode;
    //SPI_begin();
}
unsigned char SPI_write (unsigned char data_out)
Write the data to be transmitted to the SPIxBUF register. Transmission (and reception) will start as soon as data is written to the SPIxBUF register.
Definition at line 455 of file spi.c.
Referenced by disk_initialize().
{
    BUFFER = data_out; // write to buffer for TX
    while (!STATRX); // wait for the receive flag (transfer complete)
    return BUFFER;
}
void SPIxInterrupt (void)
SPIInterrupt TODO: move this to interrupt library and add it to main32.c ?
Definition at line 475 of file spi.c.
References IntClearFlag(), and IntGetFlag().
{
    unsigned char rData;
    // Is this an RX interrupt ?
    if (IntGetFlag(INTRXDONE))
    {
        rData = BUFFER; // Read SPI data buffer
        IntClearFlag(INTRXDONE);
    }
    // Is this an TX interrupt ?
    if (IntGetFlag(INTTXDONE))
    {
        IntClearFlag(INTTXDONE);
    }
}
Variable Documentation
u32 this_bitorder = SPI_MSBFIRST
Definition at line 182 of file spi.c.
u32 this_clock = SPI_PBCLOCK_DIV64
Definition at line 180 of file spi.c.
u32 this_mode = SPI_MODE0
Definition at line 179 of file spi.c.
u32 this_phase = SPI_SMPEND
Definition at line 183 of file spi.c.
u32 this_role = SPI_MASTER
Definition at line 181 of file spi.c.