/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/sd/fileio.c File Reference
#include <ctype.h>
*
#include <string.h>
*
#include <sd/fileio.h>
*
#include <sd/sdmmc.c>
*
#include `ff.c`
*
#include `diskio.c`
*
Macros
#define __FILEIO_C__
Functions
char mount (unsigned char pin)
void unmount (void)
char SD_present (unsigned char pin)
unsigned listTYPE (DIRTABLE *list, int max, const char *ext)
unsigned listDir (const char *path)
char isDirectory (FILINFO file)
char isReadOnly (FILINFO file)
char isHidden (FILINFO file)
char isSystem (FILINFO file)
char isArchive (FILINFO file)
Macro Definition Documentation
#define __FILEIO_C__
Definition at line 21 of file fileio.c.
Function Documentation
char isArchive (FILINFO file)
Definition at line 250 of file fileio.c.
References AM_ARC, False, FILINFO::fattrib, and True.
                             {
    if (file.fattrib & AM_ARC) {
        return True;
    } else {
        return False;
    }
}
char isDirectory (FILINFO file)
Definition at line 218 of file fileio.c.
References AM_DIR, False, FILINFO::fattrib, and True.
                               {
    if (file.fattrib & AM_DIR) {
        return True;
    } else {
        return False;
    }
}
char isHidden (FILINFO file)
Definition at line 234 of file fileio.c.
References AM_HID, False, FILINFO::fattrib, and True.
                            {
    if (file.fattrib & AM_HID) {
        return True;
    } else {
        return False;
    }
}
char isReadOnly (FILINFO file)
Definition at line 226 of file fileio.c.
References AM_RDO, False, FILINFO::fattrib, and True.
                              {
    if (file.fattrib & AM_RDO) {
        return True;
    } else {
        return False;
    }
}
char isSystem (FILINFO file)
Definition at line 242 of file fileio.c.
References AM_SYS, False, FILINFO::fattrib, and True.
                            {
    if (file.fattrib & AM_SYS) {
        return True;
    } else {
        return False;
    }
}
unsigned listDir (const char * path)
Definition at line 165 of file fileio.c.
References AM_DIR, dir, f_opendir(), f_readdir(), FILINFO::fattrib, Finfo, FILINFO::fname, FR_OK, FILINFO::fsize, and res.
                                   {
    //TODO: remove all CDC references
    long p1;
    PF_BYTE res, b;
    UINT s1, s2;
    DIR dir; /* Directory object */
    res = f_opendir(&dir, "/");
#ifdef SD_DEBUG
    CDCprintf("f_opendir? ");
    put_rc(res);
#endif
    p1 = s1 = s2 = 0;
    CDCprintln("\nf_readdir('%s'): ", path);
    for (;;) {
        res = f_readdir(&dir, &Finfo);
#ifdef SD_DEBUG
        put_rc(res);
#endif
        if ((res != FR_OK) || !Finfo.fname[0]) {
            break;
        }
        if (Finfo.fattrib & AM_DIR) {
            s2++;
        } else {
            s1++;
            p1 += Finfo.fsize;
        }
/* what about other outputs ?
        CDCprintf("%c%c%c%c%c ",
                (Finfo.fattrib & AM_DIR) ? 'D' : '-',
                (Finfo.fattrib & AM_RDO) ? 'R' : '-',
                (Finfo.fattrib & AM_HID) ? 'H' : '-',
                (Finfo.fattrib & AM_SYS) ? 'S' : '-',
                (Finfo.fattrib & AM_ARC) ? 'A' : '-');
        CDCprintf("%u/%02u/%02u %02u:%02u ",
                (Finfo.fdate >> 9) + 1980,
                (Finfo.fdate >> 5) & 15, Finfo.fdate & 31, (Finfo.ftime >> 11),
                (Finfo.ftime >> 5) & 63);
        CDCprintf(" %9u ", Finfo.fsize);
        CDCprintln(" %-12s %s", Finfo.fname,
#if _USE_LFN
                Lfname);
#else
                "");
#endif
*/
    }
    return s1;
} // listDir
unsigned listTYPE (DIRTABLE * list, int max, const char * ext)
Definition at line 156 of file fileio.c.
References ATT_DIR, ATT_HIDE, MFILE::buffer, D, DIR_ATTRIB, DIR_DEL, DIR_EMPTY, DIR_EXT, DIR_NAME, DIR_SIZE, DIRTABLE::ext, FE_FIND_ERROR, FE_MALLOC_FAILED, FE_MEDIA_NOT_MNTD, FError, DIRTABLE::filename, MEDIA::maxroot, MFILE::mda, NULL, readDIR(), DIRTABLE::size, TRUE, and x.
{
    //TODO: implement
    return 0;
} // listTYPE
char mount (unsigned char pin)
Definition at line 47 of file fileio.c.
References BR_FAT_CPY, BR_FAT_SIZE, BR_MAX_ROOT, BR_RES, BR_SXC, D, MEDIA::data, f_mount(), False, MEDIA::fat, Fat, MEDIA::fatcopy, MEDIA::fatsize, FE_CANNOT_READ_MBR, FE_INVALID_BR, FE_INVALID_MBR, FE_MALLOC_FAILED, FE_NOT_PRESENT, FE_PARTITION_TYPE, FError, FO_FIRST_SECT, FO_FIRST_SIZE, FO_FIRST_TYPE, FO_MBR, FO_SIGN, FR_OK, getCD(), initMedia(), initSD(), MEDIA::maxcls, MEDIA::maxroot, NULL, ReadL, ReadOddW, readSECTOR(), ReadW, MEDIA::root, SDCS, MEDIA::sxc, True, and unmount().
                              {
    int flag, i;
    FRESULT r;
    SDCS = pin;
    // 0. init the I/Os
#ifdef SD_DEBUG
    CDCprintln("Initializing I/Os... ");
#endif
    initSD();
#ifdef SD_DEBUG
    CDCprintf("Looking for SD slot... ");
#endif
    // 1. check if the card is in the slot
    if (!getCD()) {
        FError = FE_NOT_PRESENT;
#ifdef SD_DEBUG
        CDCprintln("Failed!");
#endif
        return False;
    }
#ifdef SD_DEBUG
    CDCprintln("OK");
#endif
    // 2. initialize the card
#ifdef SD_DEBUG
    CDCprintf("Initializing SD card... ");
#endif
    initMedia();
    // We're skipping the old step 3 because there's no need for malloc
    // This takes 6k off the code size if malloc is not used elsewhere.
    // Instead, just point it to our _Fat var.
    // The FATFS struct takes only 560 bytes of mem.
    Fat = &_Fat;
    // Mount media
#ifdef SD_DEBUG
    CDCprintf("Mounting FAT filesystem... ");
#endif
    r = f_mount(0, Fat);
    if (r != FR_OK) {
        FError = r;
#ifdef SD_DEBUG
        CDCprintln("Failed!");
#endif
        //free(Fat);
        return False;
    }
#ifdef SD_DEBUG
    CDCprintln("OK");
#endif
#ifdef SD_DEBUG
    CDCprintf("Checking FAT filesystem... ");
#endif
    const TCHAR * pth = "/";
    r = chk_mounted(&pth, &Fat, 0);
    if (r != FR_OK) {
        FError = r;
#ifdef SD_DEBUG
        CDCprintln("Failed!");
        put_rc(r);
#endif
        unmount();
        return False;
    }
#ifdef SD_DEBUG
    CDCprintln("OK");
#endif
    return True;
} // mount
char SD_present (unsigned char pin)
Definition at line 138 of file fileio.c.
References False, mount(), True, and unmount().
                                   {
    if (mount(pin)) {
        unmount();
        return True;
    } else {
        return False;
    }
}
void unmount (void)
Definition at line 128 of file fileio.c.
References D, f_mount(), and NULL.
                   {
    f_mount(0, NULL);
    //free(Fat);
    SPI2CONCLR = 0x8000; // SPI2 OFF
} // unmount