/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/sd/sdmmc.h File Reference
Macros
#define FAIL FALSE
#define RESET 0
#define INIT 1
#define READ_SINGLE 17
#define WRITE_SINGLE 24
#define SEND_CSD 9
#define SEND_CID 10
#define SET_BLEN 16
#define APP_CMD 55
#define SEND_APP_OP 41
#define DATA_START 0xFE
#define DATA_ACCEPT 0x05
#define I_TIMEOUT 20000
#define R_TIMEOUT 25000
#define W_TIMEOUT 250000
#define E_COMMAND_ACK 0x80
#define E_INIT_TIMEOUT 0x81
Typedefs
typedef unsigned LBA
Functions
unsigned char writeSPI (unsigned char)
void initSD (void)
void disableSD (void)
void enableSD (void)
int sendSDCmd (unsigned char, unsigned)
int initMedia (void)
int readSECTOR (LBA, char *)
int writeSECTOR (LBA, char *)
int getCD ()
int getWP ()
Macro Definition Documentation
#define APP_CMD 55
Definition at line 69 of file sdmmc.h.
#define DATA_ACCEPT 0x05
Definition at line 74 of file sdmmc.h.
#define DATA_START 0xFE
Definition at line 73 of file sdmmc.h.
#define E_COMMAND_ACK 0x80
Definition at line 82 of file sdmmc.h.
#define E_INIT_TIMEOUT 0x81
Definition at line 83 of file sdmmc.h.
#define FAIL FALSE
Definition at line 25 of file sdmmc.h.
#define I_TIMEOUT 20000
Definition at line 77 of file sdmmc.h.
#define INIT 1
Definition at line 61 of file sdmmc.h.
#define R_TIMEOUT 25000
Definition at line 78 of file sdmmc.h.
#define READ_SINGLE 17
Definition at line 62 of file sdmmc.h.
#define RESET 0
Definition at line 60 of file sdmmc.h.
#define SEND_APP_OP 41
Definition at line 70 of file sdmmc.h.
#define SEND_CID 10
Definition at line 67 of file sdmmc.h.
#define SEND_CSD 9
Definition at line 66 of file sdmmc.h.
#define SET_BLEN 16
Definition at line 68 of file sdmmc.h.
#define W_TIMEOUT 250000
Definition at line 79 of file sdmmc.h.
#define WRITE_SINGLE 24
Definition at line 63 of file sdmmc.h.
Typedef Documentation
typedef unsigned LBA
Definition at line 85 of file sdmmc.h.
Function Documentation
void disableSD (void)
Definition at line 46 of file sdmmc.c.
References clockSPI, digitalwrite(), HIGH, and SDCS.
Referenced by initMedia(), readSECTOR(), and writeSECTOR().
{
    digitalwrite(SDCS, HIGH); // Deselected = SDCS high
    clockSPI();
}
void enableSD (void)
Definition at line 52 of file sdmmc.c.
References digitalwrite(), LOW, and SDCS.
Referenced by initMedia(), and sendSDCmd().
{
    digitalwrite(SDCS, LOW); // Selected = SDCS low
}
int getCD ()
Definition at line 262 of file sdmmc.c.
References TRUE.
Referenced by disk_timerproc(), and mount().
{
    return TRUE;
    //return (SDCD);
}
int getWP ()
Definition at line 271 of file sdmmc.c.
References FALSE.
Referenced by disk_timerproc(), and writeSECTOR().
{
    return FALSE;
    //return (SDWP);
}
int initMedia (void)
Definition at line 107 of file sdmmc.c.
References clockSPI, disableSD(), E_COMMAND_ACK, E_INIT_TIMEOUT, enableSD(), I_TIMEOUT, INIT, RESET, and sendSDCmd().
Referenced by mount().
{
    int i, r;
    // 1. with the card NOT selected
    // Set DI and CS high
    disableSD();
    // 2. send 74 or more clock cycles to start up
    // apply 74 or more clock pulses to SCLK.
    // The card will enter its native operating mode and go ready to accept native commands.
    for (i=0; i<10; i++)
        clockSPI();
    // 3. now select the card
    enableSD();
    // 4. send a single RESET command
    // Send a CMD0 with CS low to reset the card.
    r = sendSDCmd(RESET, 0);
    disableSD();
    if (r != 1) // must return Idle
        return E_COMMAND_ACK; // comand rejected
    // 5. send repeatedly INIT until Idle terminates
    for (i=0; i<I_TIMEOUT; i++)
    {
        r = sendSDCmd(INIT, 0);
        disableSD();
        if (!r)
            break;
    }
    if (i == I_TIMEOUT)
        return E_INIT_TIMEOUT; // init timed out
    // 6. increase speed
    SSPCON1bits.SSPEN = 0; // Disable SPI
    SSPCON1 = SSPCON1 & 0b11110000; // SSPM<3:0> = 0000 = SPI Master mode, clock = FOSC/4
    SSPCON1bits.SSPEN = 1; // Enable SPI
    return 0;
} // init media
void initSD (void)
Definition at line 26 of file sdmmc.c.
References digitalwrite(), GetPeripheralClock(), HIGH, INPUT, OUTPUT, pinmode(), and SDCS.
Referenced by mount().
{
    digitalwrite(SDCS, HIGH); // initially keep the SD card disabled
    pinmode(SDCS, OUTPUT); // make Card select an output pin
    // SPI pin names are declared in pins.h
    pinmode(SCK, OUTPUT); // Master Mode : clock is output
    pinmode(SDI, INPUT);
    pinmode(SDO, OUTPUT);
    // init the SPI module for a slow (safe) clock speed first
    SSPCON1bits.CKP = 0; // Idle state for clock is a low level
    SSPSTATbits.CKE = 1; // Transmit occurs on transition from active to Idle clock state
    SSPCON1 = SSPCON1 & 0b11110010; // SSPM<3:0> = 0010 = SPI Master mode, clock = FOSC/64
    SSPCON1bits.SSPEN = 1; // Enables serial port and configures SCK, SDO, SDI and SS as serial port pins;
} // initSD
int readSECTOR (LBA , char *)
Definition at line 154 of file sdmmc.c.
References DATA_START, digitalwrite(), disableSD(), R_TIMEOUT, READ_SINGLE, readSPI, and sendSDCmd().
Referenced by mount(), readDATA(), readDIR(), and readFAT().
{
    int r, i;
    #ifdef READ_LED
    digitalwrite(READ_LED, 0);
    #endif
    // 1. send READ command
    r = sendSDCmd(READ_SINGLE, (a << 9));
    if (r == 0) // check if command was accepted
    {
    // 2. wait for a response
    for(i=0; i<R_TIMEOUT; i++)
    {
    r = readSPI();
    if (r == DATA_START)
    break;
    }
    // 3. if it did not timeout, read 512 byte of data
    if (i != R_TIMEOUT)
    {
        i = 512;
        do{
            *p++ = readSPI();
        } while (--i>0);
        // 4. ignore CRC
        readSPI();
        readSPI();
    } // data arrived
    } // command accepted
    // 5. remember to disable the card
    disableSD();
    #ifdef READLED
    digital(READ_LED, 1);
    #endif
    return (r == DATA_START); // return TRUE if successful
} // readSECTOR
int sendSDCmd (unsigned char, unsigned)
Definition at line 59 of file sdmmc.c.
References enableSD(), readSPI, and writeSPI().
Referenced by initMedia(), readSECTOR(), and writeSECTOR().
{
    int i, r;
    // enable SD card
    // CS low
    enableSD();
    // send a comand packet (6 bytes)
    writeSPI(c | 0x40); // send command
    writeSPI(a>>24); // msb of the address
    writeSPI(a>>16);
    writeSPI(a>>8);
    writeSPI(a); // lsb
    writeSPI(0x95); // send CMD0 CRC
    // now wait for a response, allow for up to 8 bytes delay
    for(i=0; i<8; i++)
    {
        r = readSPI();
        if (r != 0xFF)
            break;
    }
    return (r);
    /* return response
    FF - timeout
    00 - command accepted
    01 - command received, card in idle state after RESET
    other codes:
    bit 0 = Idle state
    bit 1 = Erase Reset
    bit 2 = Illegal command
    bit 3 = Communication CRC error
    bit 4 = Erase sequence error
    bit 5 = Address error
    bit 6 = Parameter error
    bit 7 = Always 0
    */
    // NOTE CSCD is still low!
} // sendSDCmd
int writeSECTOR (LBA , char *)
Definition at line 204 of file sdmmc.c.
References clockSPI, DATA_ACCEPT, DATA_START, digitalwrite(), disableSD(), FAIL, getWP(), readSPI, sendSDCmd(), W_TIMEOUT, WRITE_SINGLE, and writeSPI().
Referenced by writeDATA(), writeDIR(), and writeFAT().
{
    unsigned r, i;
    // 0. check Write Protect
    if (getWP())
        return FAIL;
    // 1. send WRITE command
    r = sendSDCmd(WRITE_SINGLE, (a << 9));
    if (r == 0) // check if command was accepted
    {
        // 2. send data
        writeSPI(DATA_START);
        // send 512 bytes of data
        for(i=0; i<512; i++)
        writeSPI(*p++);
        // 3. send dummy CRC
        clockSPI();
        clockSPI();
        // 4. check if data accepted
        r = readSPI();
        if ((r & 0xf) == DATA_ACCEPT)
        {
            #ifdef WRITE_LED
            digitalwrite(WRITE_LED, 0);
            #endif
            // 5. wait for write completion
            for(i=0; i<W_TIMEOUT; i++)
            {
                r = readSPI();
                if (r != 0)
                    break;
            }
            #ifdef WRITE_LED
            digitalwrite(WRITE_LED, 1);
            #endif
        } // accepted
        else
        {
            r = FAIL;
        }
    } // command accepted
    // 6. disable the card
    disableSD();
    return (r); // return TRUE if successful
} // writeSECTOR
unsigned char writeSPI (unsigned char)
Definition at line 19 of file sdmmc.c.
Referenced by sendSDCmd(), and writeSECTOR().
{
    SSPBUF = b; // write to buffer for TX
    while(!SSPSTATbits.BF); // wait transfer complete
    return SSPBUF; // read the received value
} // writeSPI