/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/__cdc.c File Reference
#include <stdarg.h>
*
#include <typedef.h>
*
#include <system.c>
*
#include <interrupt.c>
*
#include <delay.c>
*
Macros
#define __USBCDC
#define USBCDCisConfigured() (USBDeviceState == 0x20)
#define mUSBUSARTIsTxTrfReady() (cdc_trf_state==0)
#define USBGetDeviceState() (USBDeviceState)
#define _CDCBUFFERLENGTH_ 64
#define CDCClearDTR() (control_signal_bitmap &= 0xfe)
Enumerations
enum USB_EVENT {
*
EVENT_NONE = 0,
EVENT_DEVICE_STACK_BASE = 1,
EVENT_HOST_STACK_BASE = 100,
EVENT_HUB_ATTACH,
*
EVENT_STALL,
EVENT_VBUS_SES_REQUEST,
EVENT_VBUS_OVERCURRENT,
EVENT_VBUS_REQUEST_POWER,
*
EVENT_VBUS_RELEASE_POWER,
EVENT_VBUS_POWER_AVAILABLE,
EVENT_UNSUPPORTED_DEVICE,
EVENT_CANNOT_ENUMERATE,
*
EVENT_CLIENT_INIT_ERROR,
EVENT_OUT_OF_MEMORY,
EVENT_UNSPECIFIED_ERROR,
EVENT_DETACH,
*
EVENT_TRANSFER,
EVENT_SOF,
EVENT_RESUME,
EVENT_SUSPEND,
*
EVENT_RESET,
EVENT_DATA_ISOC_READ,
EVENT_DATA_ISOC_WRITE,
EVENT_GENERIC_BASE = 400,
*
EVENT_MSD_BASE = 500,
EVENT_HID_BASE = 600,
EVENT_PRINTER_BASE = 700,
EVENT_CDC_BASE = 800,
*
EVENT_CHARGER_BASE = 900,
EVENT_AUDIO_BASE = 1000,
EVENT_USER_BASE = 10000,
EVENT_BUS_ERROR = 2^31-1
 }
enum USB_DEVICE_STACK_EVENTS {
*
EVENT_CONFIGURED = EVENT_DEVICE_STACK_BASE,
EVENT_SET_DESCRIPTOR,
EVENT_EP0_REQUEST,
EVENT_ATTACH,
*
EVENT_TRANSFER_TERMINATED
 }
Functions
void USBCheckCDCRequest ()
void CDCInitEP ()
void USBTask ()
void USBDeviceInit ()
void USBDeviceAttach ()
void putUSBUSART (char *, char)
char getsUSBUSART (char *, char)
void CDCTxService ()
void INTEnableSystemMultiVectoredInt ()
void INTEnableInterrupts ()
void mySetLineCodingHandler ()
void USER_USB_CALLBACK_EVENT_HANDLER (USB_EVENT event_usb)
void CDC_init ()
void CDCputs (u8 *buffer, u8 length)
u8 CDCgets (u8 *buffer)
BOOL CDCUSBIsConnected (void)
BOOL CDCDTRIsReady (void)
Variables
unsigned char cdc_trf_state
u8 USBDeviceState
u8 _cdc_buffer [_CDCBUFFERLENGTH_]
BOOL CDCUSBNotConnected = false
u8 control_signal_bitmap
Macro Definition Documentation
#define __USBCDC
Definition at line 13 of file __cdc.c.
#define _CDCBUFFERLENGTH_ 64
Definition at line 102 of file __cdc.c.
#define CDCClearDTR() (control_signal_bitmap &= 0xfe)
Definition at line 587 of file __cdc.c.
Referenced by CDCDTRIsReady().
#define mUSBUSARTIsTxTrfReady() (cdc_trf_state==0)
Definition at line 38 of file __cdc.c.
Referenced by CDCputs().
#define USBCDCisConfigured() (USBDeviceState == 0x20)
Definition at line 37 of file __cdc.c.
#define USBGetDeviceState() (USBDeviceState)
Definition at line 39 of file __cdc.c.
Enumeration Type Documentation
enum USB_DEVICE_STACK_EVENTS
Enumerator
EVENT_CONFIGURED
EVENT_SET_DESCRIPTOR
EVENT_EP0_REQUEST
EVENT_ATTACH
EVENT_TRANSFER_TERMINATED
Definition at line 91 of file __cdc.c.
{
    EVENT_CONFIGURED = EVENT_DEVICE_STACK_BASE,
    EVENT_SET_DESCRIPTOR,
    EVENT_EP0_REQUEST,
    EVENT_ATTACH,
    EVENT_TRANSFER_TERMINATED
} USB_DEVICE_STACK_EVENTS;
enum USB_EVENT
Enumerator
EVENT_NONE
EVENT_DEVICE_STACK_BASE
EVENT_HOST_STACK_BASE
EVENT_HUB_ATTACH
EVENT_STALL
EVENT_VBUS_SES_REQUEST
EVENT_VBUS_OVERCURRENT
EVENT_VBUS_REQUEST_POWER
EVENT_VBUS_RELEASE_POWER
EVENT_VBUS_POWER_AVAILABLE
EVENT_UNSUPPORTED_DEVICE
EVENT_CANNOT_ENUMERATE
EVENT_CLIENT_INIT_ERROR
EVENT_OUT_OF_MEMORY
EVENT_UNSPECIFIED_ERROR
EVENT_DETACH
EVENT_TRANSFER
EVENT_SOF
EVENT_RESUME
EVENT_SUSPEND
EVENT_RESET
EVENT_DATA_ISOC_READ
EVENT_DATA_ISOC_WRITE
EVENT_GENERIC_BASE
EVENT_MSD_BASE
EVENT_HID_BASE
EVENT_PRINTER_BASE
EVENT_CDC_BASE
EVENT_CHARGER_BASE
EVENT_AUDIO_BASE
EVENT_USER_BASE
EVENT_BUS_ERROR
Definition at line 55 of file __cdc.c.
{
    EVENT_NONE = 0,
    EVENT_DEVICE_STACK_BASE = 1,
    EVENT_HOST_STACK_BASE = 100,
    EVENT_HUB_ATTACH,
    EVENT_STALL,
    EVENT_VBUS_SES_REQUEST,
    EVENT_VBUS_OVERCURRENT,
    EVENT_VBUS_REQUEST_POWER,
    EVENT_VBUS_RELEASE_POWER,
    EVENT_VBUS_POWER_AVAILABLE,
    EVENT_UNSUPPORTED_DEVICE,
    EVENT_CANNOT_ENUMERATE,
    EVENT_CLIENT_INIT_ERROR,
    EVENT_OUT_OF_MEMORY,
    EVENT_UNSPECIFIED_ERROR,
    EVENT_DETACH,
    EVENT_TRANSFER,
    EVENT_SOF,
    EVENT_RESUME,
    EVENT_SUSPEND,
    EVENT_RESET,
    EVENT_DATA_ISOC_READ,
    EVENT_DATA_ISOC_WRITE,
    EVENT_GENERIC_BASE = 400,
    EVENT_MSD_BASE = 500,
    EVENT_HID_BASE = 600,
    EVENT_PRINTER_BASE = 700,
    EVENT_CDC_BASE = 800,
    EVENT_CHARGER_BASE = 900,
    EVENT_AUDIO_BASE = 1000,
    EVENT_USER_BASE = 10000,
    EVENT_BUS_ERROR = 2^31-1
} USB_EVENT;
Function Documentation
void CDC_init (void)
Definition at line 185 of file __cdc.c.
References Delayms(), USBDeviceAttach(), and USBDeviceInit().
{
    USBDeviceInit(); // Initializes USB module SFRs and firmware
    #if defined(__32MX220F032D__)||defined(__32MX250F128B__)||defined(__32MX220F032B__)
        // nothing to do
    #else
        USBDeviceAttach();
    #endif
    Delayms(1500);
}
BOOL CDCDTRIsReady (void)
Definition at line 589 of file __cdc.c.
References CDCClearDTR, and CDCUSBIsConnected().
{
    if (CDCUSBIsConnected() == true)
    {
        //if(control_signal_bitmap.DTE_PRESENT == 1)
        if((control_signal_bitmap & 0x01) == 0x01)
            return (true);
        else
            return (false);
    }
    else
    {
        //control_signal_bitmap &= 0xfe; // !0x01
        CDCClearDTR();
        return (false);
    }
}
u8 CDCgets (u8 * buffer)
Definition at line 232 of file __cdc.c.
References CDCTxService(), and getsUSBUSART().
{
    u8 numBytesRead;
        
    #if defined(__32MX220F032D__)||defined(__32MX250F128B__)||defined(__32MX220F032B__)
        USB_Service();
        numBytesRead = USB_Service_CDC_GetString(buffer);
    #else
        CDCTxService();
        numBytesRead = getsUSBUSART(buffer, 64);
    #endif
        return numBytesRead;
/*
    if (mUSBUSARTIsTxTrfReady())
    {
        CDCTxService();
        numBytesRead = getsUSBUSART(buffer, 64);
        CDCTxService();
        return numBytesRead;
    }
*/
}
void CDCInitEP ()
Referenced by USER_USB_CALLBACK_EVENT_HANDLER().
void CDCputs (u8 * buffer, u8 length)
Definition at line 202 of file __cdc.c.
References CDCTxService(), mUSBUSARTIsTxTrfReady, and putUSBUSART().
{
    u16 i;
    for (i = 1000; i > 0; --i)
    {
        if (mUSBUSARTIsTxTrfReady())
            break;
        #if defined(__32MX220F032D__)||defined(__32MX250F128B__)||defined(__32MX220F032B__)
            USB_Service();
        #else
            CDCTxService();
        #endif
    }
    if (i > 0)
    {
        putUSBUSART(buffer, length);
        #if defined(__32MX220F032D__)||defined(__32MX250F128B__)||defined(__32MX220F032B__)
            USB_Service();
        #else
            CDCTxService();
        #endif
    }
}
void CDCTxService ()
Referenced by CDCgets(), and CDCputs().
BOOL CDCUSBIsConnected (void)
Definition at line 553 of file __cdc.c.
References CDC_init().
Referenced by CDCDTRIsReady().
{
    if ((U1OTGSTATbits.VBUSVD != 0) && (U1OTGSTATbits.SESVD != 0))
    {
        if (CDCUSBNotConnected == true)
        {
            CDC_init();
            CDCUSBNotConnected = false;
        }
        return(true);
    }
    else
    {
        CDCUSBNotConnected = true;
        return (false);
    }
}
char getsUSBUSART (char * , char)
Referenced by CDCgets().
void INTEnableInterrupts ()
Definition at line 118 of file __cdc.c.
References INT_USB, and IntEnable().
{
    IntEnable(INT_USB);
}
void INTEnableSystemMultiVectoredInt ()
Definition at line 110 of file __cdc.c.
References INT_SYSTEM_CONFIG_MULT_VECTOR, and IntConfigureSystem().
{
    IntConfigureSystem(INT_SYSTEM_CONFIG_MULT_VECTOR);
}
void mySetLineCodingHandler ()
Definition at line 126 of file __cdc.c.
{
/*
    //If the request is not in a valid range
    if(cdc_notice.GetLineCoding.dwDTERate.Val > 115200)
    {
        //NOTE: There are two ways that an unsupported baud rate could be
        //handled. The first is just to ignore the request and don't change
        //the values. That is what is currently implemented in this function.
        //The second possible method is to stall the STATUS stage of the request.
        //STALLing the STATUS stage will cause an exception to be thrown in the
        //requesting application. Some programs, like HyperTerminal, handle the
        //exception properly and give a pop-up box indicating that the request
        //settings are not valid. Any application that does not handle the
        //exception correctly will likely crash when this requiest fails. For
        //the sake of example the code required to STALL the status stage of the
        //request is provided below. It has been left out so that this demo
        //does not cause applications without the required exception handling
        //to crash.
        //---------------------------------------
        //USBStallEndpoint(0,1);
    }
    else
    {
        u32 dwBaud;
        //Update the baudrate info in the CDC driver
        CDCSetBaudRate(cdc_notice.GetLineCoding.dwDTERate.Val);
        //Update the baudrate of the UART
        U2BRG = ((GetPeripheralClock()+(BRG_DIV2/2*line_coding.dwDTERate.Val))/BRG_DIV2/
      line_coding.dwDTERate.Val-1);
        //U2MODE = 0;
        U2MODEbits.BRGH = BRGH2;
        //U2STA = 0;
    }
*/
}
void putUSBUSART (char * , char)
Referenced by CDCputs().
void USBCheckCDCRequest ()
Referenced by USER_USB_CALLBACK_EVENT_HANDLER().
void USBDeviceAttach ()
Referenced by CDC_init().
void USBDeviceInit ()
Referenced by CDC_init().
void USBTask ()
void USER_USB_CALLBACK_EVENT_HANDLER (USB_EVENT event_usb)
Definition at line 165 of file __cdc.c.
References CDCInitEP(), EVENT_CONFIGURED, EVENT_EP0_REQUEST, and USBCheckCDCRequest().
{
    switch(event_usb)
    {
        case EVENT_EP0_REQUEST:
            USBCheckCDCRequest();
            break;
        case EVENT_CONFIGURED:
            CDCInitEP();
            break;
    }
}
Variable Documentation
u8 _cdc_buffer[_CDCBUFFERLENGTH_]
Definition at line 105 of file __cdc.c.
unsigned char cdc_trf_state
BOOL CDCUSBNotConnected = false
Definition at line 551 of file __cdc.c.
u8 control_signal_bitmap
u8 USBDeviceState