/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/analog.c File Reference
Macros
#define __ANALOG__
#define pA 0
#define pB 1
#define pC 2
#define pD 3
#define pE 4
#define pF 5
#define pG 6
#define _0 1<<0
#define _1 1<<1
#define _2 1<<2
#define _3 1<<3
#define _4 1<<4
#define _5 1<<5
#define _6 1<<6
#define _7 1<<7
#define _8 1<<8
#define _9 1<<9
#define _10 1<<10
#define _11 1<<11
#define _12 1<<12
#define _13 1<<13
#define _14 1<<14
#define _15 1<<15
#define nil 1<<16
Functions
void SetAnalog (u8 pin)
u8 IsDigital (u8 pin)
void analog_init (void)
u16 analogRead (u8 pin)
Macro Definition Documentation
#define _0 1<<0
Definition at line 42 of file analog.c.
#define _1 1<<1
Definition at line 43 of file analog.c.
#define _10 1<<10
Definition at line 52 of file analog.c.
#define _11 1<<11
Definition at line 53 of file analog.c.
#define _12 1<<12
Definition at line 54 of file analog.c.
#define _13 1<<13
Definition at line 55 of file analog.c.
#define _14 1<<14
Definition at line 56 of file analog.c.
#define _15 1<<15
Definition at line 57 of file analog.c.
#define _2 1<<2
Definition at line 44 of file analog.c.
#define _3 1<<3
Definition at line 45 of file analog.c.
#define _4 1<<4
Definition at line 46 of file analog.c.
#define _5 1<<5
Definition at line 47 of file analog.c.
#define _6 1<<6
Definition at line 48 of file analog.c.
#define _7 1<<7
Definition at line 49 of file analog.c.
#define _8 1<<8
Definition at line 50 of file analog.c.
#define _9 1<<9
Definition at line 51 of file analog.c.
#define __ANALOG__
Definition at line 32 of file analog.c.
#define nil 1<<16
Definition at line 58 of file analog.c.
#define pA 0
Definition at line 34 of file analog.c.
#define pB 1
Definition at line 35 of file analog.c.
#define pC 2
Definition at line 36 of file analog.c.
#define pD 3
Definition at line 37 of file analog.c.
#define pE 4
Definition at line 38 of file analog.c.
#define pF 5
Definition at line 39 of file analog.c.
#define pG 6
Definition at line 40 of file analog.c.
Function Documentation
void analog_init (void)
Definition at line 214 of file analog.c.
{
    AD1CSSL = 0;
    AD1CON1=0x00E0;
    AD1CON2=0;
    AD1CON3 = 0x8F00;
    AD1CON1bits.ADON = 1;
}
u16 analogRead (u8 pin)
Definition at line 223 of file analog.c.
References IsDigital(), and SetAnalog().
{
    
    AD1CON1bits.ADON = 0; // stop analogic converter
    if (IsDigital(pin)) SetAnalog(pin); // set analog
    AD1CHS=(__bufmask[pin]/4)<<16; // select channel
    AD1CON1bits.ADON = 1; // start analogic converter
    AD1CON1bits.SAMP=1; // start sampling
    while (!AD1CON1bits.DONE); // wait for conversion
    return(ADC1BUF0+(8*(AD1CON2bits.BUFS&0x01))); // return result
}
u8 IsDigital (u8 pin)
Definition at line 191 of file analog.c.
Referenced by analogRead().
{
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        #if defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
            if (ANSELB&__analogmask[pin]) return 1;
            else return 0;
        #else
            switch (__portanalogmask[pin])
                {
                case 1: if (ANSELB&__analogmask[pin]) return 1;
                        else return 0;
                        break;
                case 2: if (ANSELC&__analogmask[pin]) return 1;
                        else return 0;
                        break;
                }
        #endif
    #else
    if ((AD1PCFG&__analogmask[pin])!=0) return 1;
    else return 0;
    #endif
}
void SetAnalog (u8 pin)
Definition at line 164 of file analog.c.
Referenced by analogRead().
{
    #if defined(PIC32_PINGUINO) || defined(PIC32_PINGUINO_OTG)
    if ((pin==4)||(pin==18)) TRISDbits.TRISD9=1; // analog input 18 is shared with I2C
    if ((pin==5)||(pin==19)) TRISDbits.TRISD10=1; // analog input 19 is shared with I2C
    #endif
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        #if defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
            ANSELBSET=__analogmask[pin];
            TRISBSET=__analogmask[pin];
        #else
            switch (__portanalogmask[pin])
                {
                case 1: ANSELBSET=__analogmask[pin];
                        TRISBSET=__analogmask[pin];
                        break;
                case 2: ANSELCSET=__analogmask[pin];
                        TRISCSET=__analogmask[pin];
                        break;
                }
        #endif
    #else
    TRISBSET=__analogmask[pin];
    AD1PCFGCLR=__analogmask[pin];
    #endif
}