/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/lcdlib.c File Reference
#include <delay.c>
*
#include <digitalw.c>
*
#include <typedef.h>
*
#include <printf.c>
*
#include <stdarg.h>
*
#include <lcdlib.h>
*
Macros
#define __LCDLIB_C__
Functions
void _lcd_pulseEnable (void)
void _lcd_write4bits (u8 value)
void _lcd_write8bits (u8 value)
void _lcd_send (u8 value, u8 mode)
void _lcd_write (u8 value)
void _lcd_command (u8 value)
void _lcd_setCursor (u8 col, u8 row)
void _lcd_print (char *string)
void _lcd_printf (char *fmt,...)
void _lcd_printNumber (u32 n, u8 base)
void _lcd_printFloat (float number, u8 digits)
void _lcd_home ()
void _lcd_clear ()
void _lcd_noDisplay ()
void _lcd_display ()
void _lcd_noCursor ()
void _lcd_cursor ()
void _lcd_noBlink ()
void _lcd_blink ()
void _lcd_scrollDisplayLeft (void)
void _lcd_scrollDisplayRight (void)
void _lcd_leftToRight (void)
void _lcd_rightToLeft (void)
void _lcd_autoscroll (void)
void _lcd_noAutoscroll (void)
void _lcd_begin (u8 lines, u8 dotsize)
void _lcd_init (u8 fourbitmode, u8 rs, u8 rw, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
void _lcd_pins (u8 rs, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
Macro Definition Documentation
#define __LCDLIB_C__
Definition at line 31 of file lcdlib.c.
Function Documentation
void _lcd_autoscroll (void)
This will 'right justify' text from the cursor
Definition at line 257 of file lcdlib.c.
References _displaymode, _lcd_command(), LCD_ENTRYMODESET, and LCD_ENTRYSHIFTINCREMENT.
                           {
  _displaymode |= LCD_ENTRYSHIFTINCREMENT;
  _lcd_command(LCD_ENTRYMODESET | _displaymode);
}
void _lcd_begin (u8 lines, u8 dotsize)
Initial Display settings!
Definition at line 269 of file lcdlib.c.
References _currline, _displaycontrol, _displayfunction, _displaymode, _enable_pin, _lcd_clear(), _lcd_command(), _lcd_display(), _lcd_write4bits(), _numlines, _rs_pin, Delayus(), digitalwrite(), LCD_2LINE, LCD_5x10DOTS, LCD_8BITMODE, LCD_BLINKOFF, LCD_CURSOROFF, LCD_DISPLAYON, LCD_ENTRYLEFT, LCD_ENTRYMODESET, LCD_ENTRYSHIFTDECREMENT, LCD_FUNCTIONSET, and LOW.
                                      {
  if (lines > 1) {
    _displayfunction |= LCD_2LINE;
  }
  _numlines = lines;
  _currline = 0;
  // Some one line displays can select 10 pixel high font
  if ((dotsize != 0) && (lines == 1)) {
    _displayfunction |= LCD_5x10DOTS;
  }
  Delayus(15); //Pinguino needs it? long delay on startup time!
  // Now we pull both RS and R/W low to begin commands
  digitalwrite(_rs_pin, LOW);
  digitalwrite(_enable_pin, LOW);
  
  //put the LCD into 4 bit or 8 bit mode
  if (! (_displayfunction & LCD_8BITMODE)) {
    // this is according to the hitachi HD44780 datasheet
    // figure 24, pg 46
    // we start in 8bit mode, try to set 4 bit mode
    _lcd_write4bits(0x03);
    Delayus(4500); // wait min 4.1ms
    // second try
    _lcd_write4bits(0x03);
    Delayus(4500); // wait min 4.1ms
    
    // third go!
    _lcd_write4bits(0x03);
    Delayus(150);
    // finally, set to 8-bit interface
    _lcd_write4bits(0x02);
  } else {
    // this is according to the hitachi HD44780 datasheet
    // page 45 figure 23
    // Send function set command sequence
    _lcd_command(LCD_FUNCTIONSET | _displayfunction);
    Delayus(4500); // wait more than 4.1ms
    // second try
    _lcd_command(LCD_FUNCTIONSET | _displayfunction);
    Delayus(150);
    // third go
    _lcd_command(LCD_FUNCTIONSET | _displayfunction);
  }
  // finally, set # lines, font size, etc.
  _lcd_command(LCD_FUNCTIONSET | _displayfunction);
  // turn the display on with no cursor or blinking default
  _displaycontrol = LCD_DISPLAYON | LCD_CURSOROFF |
      LCD_BLINKOFF;
  _lcd_display();
  // clear it off
  _lcd_clear();
  // Initialize to default text direction (for romance languages)
  _displaymode = LCD_ENTRYLEFT |
      LCD_ENTRYSHIFTDECREMENT;
  // set the entry mode
  _lcd_command(LCD_ENTRYMODESET | _displaymode);
}
void _lcd_blink ()
Definition at line 231 of file lcdlib.c.
References _displaycontrol, _lcd_command(), LCD_BLINKON, and LCD_DISPLAYCONTROL.
                  {
  _displaycontrol |= LCD_BLINKON;
  _lcd_command(LCD_DISPLAYCONTROL |
      _displaycontrol);
}
void _lcd_clear ()
Clear LCD
Definition at line 201 of file lcdlib.c.
References _lcd_command(), Delayus(), and LCD_CLEARDISPLAY.
Referenced by _lcd_begin().
                  {
  _lcd_command(LCD_CLEARDISPLAY); // clear display, set cursor position to
       zero
  Delayus(2000); // this command takes a long time!
}
void _lcd_command (u8 value)
Write a control command on LCD
Definition at line 89 of file lcdlib.c.
References _lcd_send(), and LOW.
Referenced by _lcd_autoscroll(), _lcd_begin(), _lcd_blink(), _lcd_clear(), _lcd_cursor(), _lcd_display(), _lcd_home(), _lcd_leftToRight(), _lcd_noAutoscroll(), _lcd_noBlink(), _lcd_noCursor(), _lcd_noDisplay(), _lcd_rightToLeft(), _lcd_scrollDisplayLeft(), _lcd_scrollDisplayRight(), and _lcd_setCursor().
                            {
    _lcd_send(value, LOW);
}
void _lcd_cursor ()
Definition at line 221 of file lcdlib.c.
References _displaycontrol, _lcd_command(), LCD_CURSORON, and LCD_DISPLAYCONTROL.
                   {
  _displaycontrol |= LCD_CURSORON;
  _lcd_command(LCD_DISPLAYCONTROL |
      _displaycontrol);
}
void _lcd_display ()
Definition at line 211 of file lcdlib.c.
References _displaycontrol, _lcd_command(), LCD_DISPLAYCONTROL, and LCD_DISPLAYON.
Referenced by _lcd_begin().
                    {
  _displaycontrol |= LCD_DISPLAYON;
  _lcd_command(LCD_DISPLAYCONTROL |
      _displaycontrol);
}
void _lcd_home ()
Move cursor to Home position
Definition at line 195 of file lcdlib.c.
References _lcd_command(), Delayus(), and LCD_RETURNHOME.
                {
    _lcd_command(LCD_RETURNHOME);
    Delayus(2000);
}
void _lcd_init (u8 fourbitmode, u8 rs, u8 rw, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
Init LCD mode => 1 => 4 bits // 0 => 8 bits rs , rw, enable pins => D0 ~ D7.
Definition at line 343 of file lcdlib.c.
References _data_pins, _displayfunction, _enable_pin, _rs_pin, _rw_pin, LCD_1LINE, LCD_4BITMODE, LCD_5x8DOTS, LCD_8BITMODE, OUTPUT, and pinmode().
Referenced by _lcd_pins().
                                       {
  int i;
  _rs_pin = rs;
  _rw_pin = rw;
  _enable_pin = enable;
  
  _data_pins[0] = d0;
  _data_pins[1] = d1;
  _data_pins[2] = d2;
  _data_pins[3] = d3;
  _data_pins[4] = d4;
  _data_pins[5] = d5;
  _data_pins[6] = d6;
  _data_pins[7] = d7;
  pinmode(_rs_pin, OUTPUT);
  
  pinmode(_enable_pin, OUTPUT);
  
  if (fourbitmode){
    _displayfunction = LCD_4BITMODE | LCD_1LINE |
      LCD_5x8DOTS;
    for (i = 0; i < 4; i++) {
        pinmode(_data_pins[i], OUTPUT);
        }
  }
  else {
    _displayfunction = LCD_8BITMODE | LCD_1LINE |
      LCD_5x8DOTS;
    for (i = 0; i < 8; i++) {
        pinmode(_data_pins[i], OUTPUT);
    }
  }
  
}
void _lcd_leftToRight (void)
This is for text that flows Left to Right
Definition at line 245 of file lcdlib.c.
References _displaymode, _lcd_command(), LCD_ENTRYLEFT, and LCD_ENTRYMODESET.
                            {
  _displaymode |= LCD_ENTRYLEFT;
  _lcd_command(LCD_ENTRYMODESET | _displaymode);
}
void _lcd_noAutoscroll (void)
This will 'left justify' text from the cursor
Definition at line 263 of file lcdlib.c.
References _displaymode, _lcd_command(), LCD_ENTRYMODESET, and LCD_ENTRYSHIFTINCREMENT.
                             {
  _displaymode &= ~LCD_ENTRYSHIFTINCREMENT;
  _lcd_command(LCD_ENTRYMODESET | _displaymode);
}
void _lcd_noBlink ()
Turn on and off the blinking cursor
Definition at line 227 of file lcdlib.c.
References _displaycontrol, _lcd_command(), LCD_BLINKON, and LCD_DISPLAYCONTROL.
                    {
  _displaycontrol &= ~LCD_BLINKON;
  _lcd_command(LCD_DISPLAYCONTROL |
      _displaycontrol);
}
void _lcd_noCursor ()
Turns the underline cursor on/off
Definition at line 217 of file lcdlib.c.
References _displaycontrol, _lcd_command(), LCD_CURSORON, and LCD_DISPLAYCONTROL.
                     {
  _displaycontrol &= ~LCD_CURSORON;
  _lcd_command(LCD_DISPLAYCONTROL |
      _displaycontrol);
}
void _lcd_noDisplay ()
Turn the display on/off (quickly)
Definition at line 207 of file lcdlib.c.
References _displaycontrol, _lcd_command(), LCD_DISPLAYCONTROL, and LCD_DISPLAYON.
                      {
  _displaycontrol &= ~LCD_DISPLAYON;
  _lcd_command(LCD_DISPLAYCONTROL |
      _displaycontrol);
}
void _lcd_pins (u8 rs, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
LCD 8 bits mode
Definition at line 380 of file lcdlib.c.
References _lcd_init().
                                        {
    
    _lcd_init(((d4 + d5 + d6 + d7)==0), rs, 99, enable, d0, d1, d2, d3, d4, d5, d6, d7);
    
}
void _lcd_print (char * string)
Print a string on LCD
Definition at line 117 of file lcdlib.c.
References _lcd_write().
                              {
    int i;
    for(i=0; string[i]; i++) {
        _lcd_write(string[i]);
    }
}
void _lcd_printf (char * fmt, ...)
Write formated string on LCD
Definition at line 126 of file lcdlib.c.
References _lcd_write(), and pprintf().
{
    va_list args;
    va_start(args, fmt);
    pprintf(_lcd_write, fmt, args);
    va_end(args);
}
void _lcd_printFloat (float number, u8 digits)
Print a float number to LCD
Definition at line 157 of file lcdlib.c.
References _lcd_printNumber(), and _lcd_write().
                                              {
  u8 i, toPrint;
  u32 int_part;
  float rounding, remainder;
  
  // Handle negative numbers
  if (number < 0.0) {
     _lcd_write('-');
     number = -number;
  }
  // Round correctly so that print(1.999, 2) prints as "2.00"
  rounding = 0.5;
  for (i=0; i<digits; ++i)
    rounding /= 10.0;
  
  number += rounding;
  // Extract the integer part of the number and print it
  int_part = (u32)number;
  remainder = number - (float)int_part;
  _lcd_printNumber(int_part, 10);
  // Print the decimal point, but only if there are digits beyond
  if (digits > 0)
    _lcd_write('.');
  // Extract digits from the remainder one at a time
  while (digits-- > 0) {
    remainder *= 10.0;
    toPrint = (u16)remainder; //Integer part without use of math.h lib,
                                //I think better! (Fazzi)
    _lcd_printNumber(toPrint, 10);
    remainder -= toPrint;
  }
}
void _lcd_printNumber (u32 n, u8 base)
Print a number on LCD
Definition at line 136 of file lcdlib.c.
References _lcd_write().
Referenced by _lcd_printFloat().
                                      {
  u8 buf[8 * sizeof(long)]; // Assumes 8-bit chars.
  u32 i = 0;
  if (n == 0) {
    _lcd_write('0');
    return;
  }
  while (n > 0) {
    buf[i++] = n % base;
    n /= base;
  }
  for (; i > 0; i--)
    _lcd_write((char) (buf[i - 1] < 10 ?
      '0' + buf[i - 1] :
      'A' + buf[i - 1] - 10));
}
void _lcd_pulseEnable (void)
Positive pulse on E
Definition at line 44 of file lcdlib.c.
References _enable_pin, Delayus(), digitalwrite(), HIGH, and LOW.
Referenced by _lcd_write4bits(), and _lcd_write8bits().
                            {
  digitalwrite(_enable_pin, LOW);
  Delayus(1);
  digitalwrite(_enable_pin, HIGH);
  Delayus(1); // enable pulse must be >450ns
  digitalwrite(_enable_pin, LOW);
  Delayus(50); // commands need > 37us to settle
}
void _lcd_rightToLeft (void)
This is for text that flows Right to Left
Definition at line 251 of file lcdlib.c.
References _displaymode, _lcd_command(), LCD_ENTRYLEFT, and LCD_ENTRYMODESET.
                            {
  _displaymode &= ~LCD_ENTRYLEFT;
  _lcd_command(LCD_ENTRYMODESET | _displaymode);
}
void _lcd_scrollDisplayLeft (void)
These commands scroll the display without changing the RAM
Definition at line 237 of file lcdlib.c.
References _lcd_command(), LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVELEFT.
                                  {
  _lcd_command(LCD_CURSORSHIFT | LCD_DISPLAYMOVE |
      LCD_MOVELEFT);
}
void _lcd_scrollDisplayRight (void)
Definition at line 240 of file lcdlib.c.
References _lcd_command(), LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVERIGHT.
                                   {
  _lcd_command(LCD_CURSORSHIFT | LCD_DISPLAYMOVE |
      LCD_MOVERIGHT);
}
void _lcd_send (u8 value, u8 mode)
Send data to LCD 8 or 4 bits
Definition at line 72 of file lcdlib.c.
References _displayfunction, _lcd_write4bits(), _lcd_write8bits(), _rs_pin, digitalwrite(), and LCD_8BITMODE.
Referenced by _lcd_command(), and _lcd_write().
                                  {
    digitalwrite(_rs_pin, mode);
    if (_displayfunction & LCD_8BITMODE) {
        _lcd_write8bits(value);
    } else {
        _lcd_write4bits(value>>4);
        _lcd_write4bits(value);
    }
}
void _lcd_setCursor (u8 col, u8 row)
Setup line x column on LCD
Definition at line 94 of file lcdlib.c.
References _lcd_command(), _numlines, and LCD_SETDDRAMADDR.
                                    {
    int row_offsets[] = { 0x00, 0x40, 0x14, 0x54 };
    /* Added 01 May 2012 by MFH
        sets row_offsets for a single line display so that
        80 column space divided in 4 equal 20 column sections.
        This means that if an n x 4 display is set to behave as
        a single line display lines 1 and 2 are displayed and
        lines 3 and 4 are 20 characters to the right.*/
    if (_numlines==1) {
        row_offsets[1] = 0x14;
        row_offsets[2] = 0x28;
        row_offsets[3] = 0x3C;
        }
    /* Removed 01 May 2012 by MFH as did not treat row
        starts consistently for n x 2 and n x 4 displays
    if (row > _numlines) {
        row = _numlines-1; // we count rows starting w/0
    }
*/
    _lcd_command(LCD_SETDDRAMADDR | (col + row_offsets[row]));
}
void _lcd_write (u8 value)
Write a data character on LCD
Definition at line 83 of file lcdlib.c.
References _lcd_send(), and HIGH.
Referenced by _lcd_print(), _lcd_printf(), _lcd_printFloat(), and _lcd_printNumber().
                          {
    _lcd_send(value, HIGH);
}
void _lcd_write4bits (u8 value)
Write using 4bits mode
Definition at line 54 of file lcdlib.c.
References _data_pins, _lcd_pulseEnable(), and digitalwrite().
Referenced by _lcd_begin(), and _lcd_send().
                               {
    int i;
    for (i = 0; i < 4; i++) {
        digitalwrite(_data_pins[i], (value >> i) & 0x01);
    }
    _lcd_pulseEnable();
}
void _lcd_write8bits (u8 value)
Write using 8bits mode
Definition at line 63 of file lcdlib.c.
References _data_pins, _lcd_pulseEnable(), and digitalwrite().
Referenced by _lcd_send().
                               {
    int i;
    for (i = 0; i < 8; i++) {
        digitalwrite(_data_pins[i], (value >> i) & 0x01);
    }
    _lcd_pulseEnable();
}