/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/pcf8574.c File Reference
#include <typedef.h>
*
#include <macro.h>
*
#include <pinguinoi2c.c>
*
#include <pcf8574.h>
*
Macros
#define __PCF8574_C
Functions
void PCF8574_init (void)
u8 PCF8574_write (u8 address, u8 value)
Variables
PCF8574_t PCF8574_data
Macro Definition Documentation
#define __PCF8574_C
Definition at line 57 of file pcf8574.c.
Function Documentation
void PCF8574_init (void)
---------- PCF8574_init
---------- RAZ de la variable d'echange entre Pic et PCF8574
Definition at line 76 of file pcf8574.c.
References I2C_100KHZ, I2C_init(), I2C_MASTER_MODE, and PCF8574_t::val.
{
    PCF8574_data.val = 0;
}
u8 PCF8574_write (u8 address, u8 value)
---------- PCF8574_write
---------- Ecriture d'un octet sur le port du PCF8574 via le bus I2C In Master Transmitter mode, the first byte transmitted contains the slave address of the receiving device (seven bits) and the Read/Write (R/W) bit. In this case, the R/W bit will be logic ‘0’. Serial data is transmitted eight bits at a time. After each byte is transmitted, an Acknowledge bit is received. Start and Stop conditions are output to indicate the beginning and the end of a serial transfer.
Definition at line 87 of file pcf8574.c.
References I2C_start(), I2C_stop(), I2C_WRITE, I2C_write(), and I2C_writechar().
{
    u8 bRet = 0x00;
    I2C_start();
    I2C_write(address | I2C_WRITE);
    if (SSPCON2bits.ACKSTAT) //Si AckStat == 1, on n'a pas reçu d'acquittement
    {
        I2C_stop();
        return bRet;
    }
    I2C_write(value);
    if (!SSPCON2bits.ACKSTAT) //Si on reçoit un acquitement, on retourne 1
    {
        bRet = 0x01;
    }
    I2C_stop();
    return bRet;
}
Variable Documentation
PCF8574_t PCF8574_data
---------- Globales
Definition at line 68 of file pcf8574.c.