/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/PCD8544.c File Reference
#include <PCD8544.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <typedef.h>
*
#include <delay.c>
*
#include <string.h>
*
#include <graphics.c>
*
#include <digitalw.c>
*
Macros
#define __PCD8544_C
#define DIGITALWRITE
#define PINMODE
Functions
void PCD8544_shiftOut (u8 c)
void PCD8544_command (u8 c)
void PCD8544_data (u8 c)
if (PCD8544._rst > 0)
PCD8544_command (PCD8544_FUNCTIONSET|PCD8544_EXTENDEDINSTRUCTION)
PCD8544_command (PCD8544_SETBIAS|0x05)
PCD8544_command (PCD8544_SETVOP|0x7F)
PCD8544_command (PCD8544_FUNCTIONSET)
PCD8544_command (PCD8544_DISPLAYCONTROL|PCD8544_DISPLAYNORMAL)
PCD8544_refresh ()
void PCD8544_clearScreen ()
void PCD8544_setContrast (u8 val)
void PCD8544_scrollUp ()
void PCD8544_setFont (const u8 *font)
void PCD8544_printChar (u8 c)
Variables
PCD8544 screen height = DISPLAY_HEIGHT
PCD8544 orientation = PORTRAIT
PCD8544 cursor y = 0
PCD8544 cursor x = 0
PCD8544 textsize = 1
PCD8544 color c = BLACK
Macro Definition Documentation
#define __PCD8544_C
Definition at line 46 of file PCD8544.c.
#define DIGITALWRITE
Definition at line 57 of file PCD8544.c.
#define PINMODE
Definition at line 58 of file PCD8544.c.
Function Documentation
if (PCD8544. _rst, 0)
Definition at line 256 of file PCD8544.c.
References lcd_t::_rst, Delayms(), digitalwrite(), HIGH, LOW, and PCD8544.
        {
            digitalwrite(PCD8544._rst, LOW);
            Delayms(30);
            digitalwrite(PCD8544._rst, HIGH);
        }
void PCD8544_clearScreen ()
Definition at line 351 of file PCD8544.c.
References lcd_t::cursor, DISPLAY_HEIGHT, DISPLAY_SIZE, DISPLAY_WIDTH, PCD8544, PCD8544_buffer, coord_t::x, and coord_t::y.
{
    memset(PCD8544_buffer, 0, DISPLAY_SIZE);
    #ifdef enablePartialUpdate
    PCD8544_updateBoundingBox(0, 0, DISPLAY_WIDTH-1, DISPLAY_HEIGHT-1);
    #endif
    PCD8544.cursor.y = 0;
    PCD8544.cursor.x = 0;
}
void PCD8544_command (u8 c)
Definition at line 109 of file PCD8544.c.
References lcd_t::_cs, lcd_t::_dc, DESELECT, digitalwrite(), HIGH, LOW, PCD8544, PCD8544_shiftOut(), SELECT, and SPI_write().
{
    #if (PCD8544_INTERFACE & PCD8544_SPISW)
        #if (PCD8544_INTERFACE & PCD8544_PORTB)
            Low(PCD8544_DC);
            Low(PCD8544_SCE);
            PCD8544_shiftOut(c);
            High(PCD8544_SCE);
        #else
            // DC = LOW => COMMAND
            digitalwrite(PCD8544._dc, LOW);
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, LOW);
                
            PCD8544_shiftOut(c);
            
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, HIGH);
        #endif
    #elif (PCD8544_INTERFACE & PCD8544_SPIHW)
        // DC = LOW => COMMAND
        digitalwrite(PCD8544._dc, LOW);
        SPI_select();
        SPI_write(c);
        SPI_deselect();
    #endif
}
PCD8544_command (PCD8544_FUNCTIONSET| PCD8544_EXTENDEDINSTRUCTION)
PCD8544_command (PCD8544_SETBIAS| 0x05)
PCD8544_command (PCD8544_SETVOP| 0x7F)
PCD8544_command (PCD8544_FUNCTIONSET)
PCD8544_command (PCD8544_DISPLAYCONTROL| PCD8544_DISPLAYNORMAL)
void PCD8544_data (u8 c)
Definition at line 137 of file PCD8544.c.
References lcd_t::_cs, lcd_t::_dc, DESELECT, digitalwrite(), HIGH, LOW, PCD8544, PCD8544_shiftOut(), SELECT, and SPI_write().
{
    #if (PCD8544_INTERFACE & PCD8544_SPISW)
        #if (PCD8544_INTERFACE & PCD8544_PORTB)
            High(PCD8544_DC);
            Low(PCD8544_SCE);
            PCD8544_shiftOut(c);
            High(PCD8544_SCE);
        #else
            // DC = HIGH => DATA
            digitalwrite(PCD8544._dc, HIGH);
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, LOW);
                
            PCD8544_shiftOut(c);
            
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, HIGH);
        #endif
    #elif (PCD8544_INTERFACE & PCD8544_SPIHW)
        // DC = HIGH => DATA
        digitalwrite(PCD8544._dc, HIGH);
        SPI_select();
        SPI_write(c);
        SPI_deselect();
    #endif
}
void PCD8544_printChar (u8 c)
Definition at line 422 of file PCD8544.c.
References font_t::address, lcd_t::cursor, DISPLAY_ROWS, lcd_t::font, PCD8544, PCD8544_buffer, PCD8544_scrollUp(), lcd_t::screen, font_t::width, rect_t::width, coord_t::x, and coord_t::y.
{
    u8 b;
    while (PCD8544.cursor.x >= (PCD8544.screen.width /
      PCD8544.font.width))
    {
        PCD8544.cursor.x -= (PCD8544.screen.width /
      PCD8544.font.width);
        PCD8544.cursor.y++;
    }
    while (PCD8544.cursor.y > DISPLAY_ROWS)
    {
        PCD8544_scrollUp();
    }
    switch (c)
    {
        case '\n':
            PCD8544.cursor.y++;
            break;
            
        case '\r':
            PCD8544.cursor.x = 0;
            break;
            
        case '\t':
            PCD8544.cursor.x = (PCD8544.cursor.x + 4) % 4;
            break;
            
        default:
            for (b = 0; b < PCD8544.font.width; b++)
            {
                PCD8544_buffer[PCD8544.cursor.x *
      PCD8544.font.width + PCD8544.cursor.y * PCD8544.
      screen.width + b] =
                    PCD8544.font.address[2 + (c - 32) *
      PCD8544.font.width + b];
            }
        
        PCD8544.cursor.x++;
    }
}
PCD8544_refresh ()
Definition at line 289 of file PCD8544.c.
References lcd_t::_cs, lcd_t::_dc, DESELECT, digitalwrite(), DISPLAY_HEIGHT, DISPLAY_ROWS, DISPLAY_WIDTH, HIGH, LOW, PCD8544, PCD8544_buffer, PCD8544_command(), PCD8544_SETXADDR, PCD8544_SETYADDR, PCD8544_shiftOut(), SELECT, and SPI_write().
{
    u8 col, p;
    u16 t = 0;
     
    #if (PCD8544_INTERFACE & PCD8544_SPISW)
        #if (PCD8544_INTERFACE & PCD8544_PORTB)
            for(p = 0; p <= DISPLAY_ROWS; p++)
            {
                col = 0;
                PCD8544_command(PCD8544_SETYADDR | p);
                PCD8544_command(PCD8544_SETXADDR | col);
                // send data in DDRAM
                High(PCD8544_DC);
                Low(PCD8544_SCE);
                for(; col < DISPLAY_WIDTH; col++)
                    PCD8544_shiftOut(PCD8544_buffer[(DISPLAY_WIDTH*p)+col]);
                High(PCD8544_SCE);
            }
        #else
            for(p = 0; p <= DISPLAY_ROWS; p++)
            {
                col = 0;
                PCD8544_command(PCD8544_SETYADDR | p);
                PCD8544_command(PCD8544_SETXADDR | col);
                // send data in DDRAM
                digitalwrite(PCD8544._dc, HIGH);
                if (PCD8544._cs > 0)
                    digitalwrite(PCD8544._cs, LOW);
                for(; col < DISPLAY_WIDTH; col++)
                    PCD8544_shiftOut(PCD8544_buffer[(DISPLAY_WIDTH*p)+col]);
                if (PCD8544._cs > 0)
                    digitalwrite(PCD8544._cs, HIGH);
            }
        #endif
    #elif (PCD8544_INTERFACE & PCD8544_SPIHW)
        for(p = 0; p <= DISPLAY_ROWS; p++)
        {
            col = 0;
            PCD8544_command(PCD8544_SETYADDR | p);
            PCD8544_command(PCD8544_SETXADDR | col);
            // send data in DDRAM
            digitalwrite(PCD8544._dc, HIGH);
            SPI_select();
            for(; col < DISPLAY_WIDTH; col++)
                SPI_write(PCD8544_buffer[t+col]);
            SPI_deselect();
            t += DISPLAY_WIDTH;
        }
    #endif
    // no idea why this is necessary but it is to finish the last byte?
    //PCD8544_command(PCD8544_SETYADDR);
    #ifdef enablePartialUpdate
      xUpdateMin = DISPLAY_WIDTH - 1;
      xUpdateMax = 0;
      yUpdateMin = DISPLAY_HEIGHT-1;
      yUpdateMax = 0;
    #endif
}
void PCD8544_scrollUp ()
Scroll functions
Definition at line 388 of file PCD8544.c.
References lcd_t::cursor, DISPLAY_ROWS, DISPLAY_WIDTH, PCD8544, PCD8544_buffer, x, coord_t::y, and y.
{
    u8 x, y;
    // copy line y to line y-1
    for (y = 1; y <= DISPLAY_ROWS; y++)
    {
        for (x = 0; x < DISPLAY_WIDTH; x++)
        {
            PCD8544_buffer[x + DISPLAY_WIDTH * (y - 1)] =
            PCD8544_buffer[x + DISPLAY_WIDTH * y];
        }
    }
    // clear last line
    for (x = 0; x < DISPLAY_WIDTH; x++)
    {
        PCD8544_buffer[x + DISPLAY_WIDTH * DISPLAY_ROWS] = 0;
    }
    PCD8544.cursor.y--;
}
void PCD8544_setContrast (u8 val)
Definition at line 377 of file PCD8544.c.
References PCD8544_command(), PCD8544_EXTENDEDINSTRUCTION, PCD8544_FUNCTIONSET, and PCD8544_SETVOP.
{
    PCD8544_command(PCD8544_FUNCTIONSET |
      PCD8544_EXTENDEDINSTRUCTION);
    PCD8544_command(PCD8544_SETVOP | (val & 0x7F));
    PCD8544_command(PCD8544_FUNCTIONSET);
}
void PCD8544_setFont (const u8 * font)
Print functions
Definition at line 415 of file PCD8544.c.
References font_t::address, font, lcd_t::font, font_t::height, PCD8544, and font_t::width.
{
    PCD8544.font.address = font;
    PCD8544.font.width = font[0];
    PCD8544.font.height = font[1];
}
void PCD8544_shiftOut (u8 c)
Core functions
Definition at line 84 of file PCD8544.c.
References lcd_t::_din, lcd_t::_sclk, digitalwrite(), HIGH, LOW, and PCD8544.
{
    u8 i;
    for (i = 0; i < 8; i++)
    {
        #if (PCD8544_INTERFACE & PCD8544_SPISW)
            #if (PCD8544_INTERFACE & PCD8544_PORTB)
                if (c & 0x80)
                    High(PCD8544_SDIN);
                else
                    Low(PCD8544_SDIN);
                High(PCD8544_SCLK);
                Low(PCD8544_SCLK);
            #else
                digitalwrite(PCD8544._din, (c & 0x80) ?
      HIGH : LOW);
                digitalwrite(PCD8544._sclk, HIGH);
                digitalwrite(PCD8544._sclk, LOW);
            #endif
            c <<= 1;
        #endif
    }
}
Variable Documentation
PCD8544 bcolor c = BLACK
Definition at line 212 of file PCD8544.c.
PCD8544 screen height = DISPLAY_HEIGHT
Display functions
Definition at line 207 of file PCD8544.c.
PCD8544 orientation = PORTRAIT
Definition at line 208 of file PCD8544.c.
PCD8544 textsize = 1
Definition at line 211 of file PCD8544.c.
PCD8544 cursor x = 0
Definition at line 210 of file PCD8544.c.
PCD8544 cursor y = 0
Definition at line 209 of file PCD8544.c.