/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/lcdi2c.h File Reference
#include <pcf8574.h>
*
Macros
#define LCD_MASK 0b11110000
#define LCD_BL PCF8574_data.bits.P0
#define LCD_RS PCF8574_data.bits.P1
#define LCD_RW PCF8574_data.bits.P2
#define LCD_EN PCF8574_data.bits.P3
#define LCD_D4 PCF8574_data.bits.P4
#define LCD_D5 PCF8574_data.bits.P5
#define LCD_D6 PCF8574_data.bits.P6
#define LCD_D7 PCF8574_data.bits.P7
#define LCD_WRITE 0
#define LCD_READ 1
#define LCD_DATA 1
#define LCD_CMD 0
#define LCD_DISPLAY_CLEAR 0b00000001
#define LCD_CURSOR_HOME 0b00000010
#define LCD_ENTRY_MODE_SET 0b00000110
#define LCD_DISPLAY_ON 0b00001100
#define LCD_DISPLAY_OFF 0b00001000
#define LCD_SYSTEM_SET_4BITS 0b00101000
#define LCD_SYSTEM_SET_8BITS 0b00111000
#define LCD_ADRESS_LINE1 0b10000000
#define LCD_ADRESS_LINE2 0b11000000
#define LCD_ADRESS_NUMBER 0b00110000
#define LCD_ADRESS_CGRAM 0b01000000
#define LCD_CLEARDISPLAY 0x01
#define LCD_RETURNHOME 0x02
#define LCD_ENTRYMODESET 0x04
#define LCD_DISPLAYCONTROL 0x08
#define LCD_CURSORSHIFT 0x10
#define LCD_FUNCTIONSET 0x20
#define LCD_SETCGRAMADDR 0x40
#define LCD_SETDDRAMADDR 0x80
#define LCD_ENTRYRIGHT 0x00
#define LCD_ENTRYLEFT 0x02
#define LCD_ENTRYSHIFTINCREMENT 0x01
#define LCD_ENTRYSHIFTDECREMENT 0x00
#define LCD_DISPLAYON 0x04
#define LCD_DISPLAYOFF 0x00
#define LCD_CURSORON 0x02
#define LCD_CURSOROFF 0x00
#define LCD_BLINKON 0x01
#define LCD_BLINKOFF 0x00
#define LCD_DISPLAYMOVE 0x08
#define LCD_CURSORMOVE 0x00
#define LCD_MOVERIGHT 0x04
#define LCD_MOVELEFT 0x00
#define LCD_8BITMODE 0x10
#define LCD_4BITMODE 0x00
#define LCD_2LINE 0x08
#define LCD_1LINE 0x00
#define LCD_5x10DOTS 0x04
#define LCD_5x8DOTS 0x00
#define LCD_CENTER 101
#define LCD_RIGHT 102
#define LCD_LEFT 103
#define DEGRE 0b11011111
#define SIGMA 0b11100101
#define MICRO 0b11100100
#define INFINI 0b11110011
#define ESPACE 0x20
#define HEXADECIMAL 16
#define DECIMAL 10
#define OCTAL 8
#define BINAIRE 2
#define ACIRC 0
#define AGRAVE 1
#define CCEDIL 2
#define EACUTE 3
#define EGRAVE 4
#define ECIRC 5
#define ETREMA 6
#define EURO 7
#define ICIRC 8
#define ITREMA 9
#define OCIRC 10
#define UGRAVE 11
#define UCIRC 12
Functions
void lcdi2c_init (u8, u8, u8)
void lcdi2c_backlight ()
void lcdi2c_noBacklight ()
void lcdi2c_clear ()
void lcdi2c_clearLine (u8)
void lcdi2c_home ()
void lcdi2c_noAutoscroll ()
void lcdi2c_autoscroll ()
void lcdi2c_rightToLeft ()
void lcdi2c_leftToRight ()
void lcdi2c_scrollDisplayRight ()
void lcdi2c_scrollDisplayLeft ()
void lcdi2c_blink ()
void lcdi2c_noBlink ()
void lcdi2c_cursor ()
void lcdi2c_noCursor ()
void lcdi2c_display ()
void lcdi2c_noDisplay ()
void lcdi2c_setCursor (u8, u8)
void lcdi2c_write (char)
void lcdi2c_printf (char *,...)
void lcdi2c_newchar (const u8 *, u8)
void lcdi2c_newpattern ()
Variables
u8 Backlight
VARIABLES GLOBALES.
const u8 car0 [8]
const u8 car1 [8]
const u8 car2 [8]
const u8 car3 [8]
const u8 car4 [8]
const u8 car5 [8]
const u8 car6 [8]
const u8 car7 [8]
const u8 car8 [8]
const u8 car9 [8]
const u8 car10 [8]
const u8 car11 [8]
const u8 car12 [8]
Macro Definition Documentation
#define ACIRC 0
Definition at line 159 of file lcdi2c.h.
#define AGRAVE 1
Definition at line 160 of file lcdi2c.h.
#define BINAIRE 2
Definition at line 157 of file lcdi2c.h.
#define CCEDIL 2
Definition at line 162 of file lcdi2c.h.
#define DECIMAL 10
Definition at line 155 of file lcdi2c.h.
#define DEGRE 0b11011111
Definition at line 148 of file lcdi2c.h.
#define EACUTE 3
Definition at line 164 of file lcdi2c.h.
#define ECIRC 5
Definition at line 166 of file lcdi2c.h.
#define EGRAVE 4
Definition at line 165 of file lcdi2c.h.
#define ESPACE 0x20
Definition at line 152 of file lcdi2c.h.
Referenced by lcdi2c_clearLine().
#define ETREMA 6
Definition at line 167 of file lcdi2c.h.
#define EURO 7
Definition at line 168 of file lcdi2c.h.
#define HEXADECIMAL 16
Definition at line 154 of file lcdi2c.h.
#define ICIRC 8
Definition at line 170 of file lcdi2c.h.
#define INFINI 0b11110011
Definition at line 151 of file lcdi2c.h.
#define ITREMA 9
Definition at line 171 of file lcdi2c.h.
#define LCD_1LINE 0x00
Definition at line 140 of file lcdi2c.h.
#define LCD_2LINE 0x08
Definition at line 139 of file lcdi2c.h.
#define LCD_4BITMODE 0x00
Definition at line 138 of file lcdi2c.h.
#define LCD_5x10DOTS 0x04
Definition at line 141 of file lcdi2c.h.
#define LCD_5x8DOTS 0x00
Definition at line 142 of file lcdi2c.h.
#define LCD_8BITMODE 0x10
Definition at line 137 of file lcdi2c.h.
#define LCD_ADRESS_CGRAM 0b01000000
Definition at line 104 of file lcdi2c.h.
#define LCD_ADRESS_LINE1 0b10000000
Definition at line 101 of file lcdi2c.h.
#define LCD_ADRESS_LINE2 0b11000000
Definition at line 102 of file lcdi2c.h.
#define LCD_ADRESS_NUMBER 0b00110000
Definition at line 103 of file lcdi2c.h.
#define LCD_BL PCF8574_data.bits.P0
Definition at line 79 of file lcdi2c.h.
#define LCD_BLINKOFF 0x00
Definition at line 128 of file lcdi2c.h.
#define LCD_BLINKON 0x01
Definition at line 127 of file lcdi2c.h.
#define LCD_CENTER 101
Definition at line 144 of file lcdi2c.h.
#define LCD_CLEARDISPLAY 0x01
Definition at line 107 of file lcdi2c.h.
#define LCD_CMD 0
Definition at line 91 of file lcdi2c.h.
#define LCD_CURSOR_HOME 0b00000010
Definition at line 94 of file lcdi2c.h.
#define LCD_CURSORMOVE 0x00
Definition at line 132 of file lcdi2c.h.
#define LCD_CURSOROFF 0x00
Definition at line 126 of file lcdi2c.h.
#define LCD_CURSORON 0x02
Definition at line 125 of file lcdi2c.h.
#define LCD_CURSORSHIFT 0x10
Definition at line 111 of file lcdi2c.h.
#define LCD_D4 PCF8574_data.bits.P4
Definition at line 83 of file lcdi2c.h.
#define LCD_D5 PCF8574_data.bits.P5
Definition at line 84 of file lcdi2c.h.
#define LCD_D6 PCF8574_data.bits.P6
Definition at line 85 of file lcdi2c.h.
#define LCD_D7 PCF8574_data.bits.P7
Definition at line 86 of file lcdi2c.h.
#define LCD_DATA 1
Definition at line 90 of file lcdi2c.h.
#define LCD_DISPLAY_CLEAR 0b00000001
Definition at line 93 of file lcdi2c.h.
#define LCD_DISPLAY_OFF 0b00001000
Definition at line 98 of file lcdi2c.h.
#define LCD_DISPLAY_ON 0b00001100
Definition at line 97 of file lcdi2c.h.
#define LCD_DISPLAYCONTROL 0x08
Definition at line 110 of file lcdi2c.h.
#define LCD_DISPLAYMOVE 0x08
Definition at line 131 of file lcdi2c.h.
#define LCD_DISPLAYOFF 0x00
Definition at line 124 of file lcdi2c.h.
#define LCD_DISPLAYON 0x04
Definition at line 123 of file lcdi2c.h.
#define LCD_EN PCF8574_data.bits.P3
Definition at line 82 of file lcdi2c.h.
#define LCD_ENTRY_MODE_SET 0b00000110
Definition at line 95 of file lcdi2c.h.
#define LCD_ENTRYLEFT 0x02
Definition at line 118 of file lcdi2c.h.
#define LCD_ENTRYMODESET 0x04
Definition at line 109 of file lcdi2c.h.
#define LCD_ENTRYRIGHT 0x00
Definition at line 117 of file lcdi2c.h.
#define LCD_ENTRYSHIFTDECREMENT 0x00
Definition at line 120 of file lcdi2c.h.
#define LCD_ENTRYSHIFTINCREMENT 0x01
Definition at line 119 of file lcdi2c.h.
#define LCD_FUNCTIONSET 0x20
Definition at line 112 of file lcdi2c.h.
#define LCD_LEFT 103
Definition at line 146 of file lcdi2c.h.
#define LCD_MASK 0b11110000
Definition at line 77 of file lcdi2c.h.
#define LCD_MOVELEFT 0x00
Definition at line 134 of file lcdi2c.h.
#define LCD_MOVERIGHT 0x04
Definition at line 133 of file lcdi2c.h.
#define LCD_READ 1
Definition at line 89 of file lcdi2c.h.
#define LCD_RETURNHOME 0x02
Definition at line 108 of file lcdi2c.h.
#define LCD_RIGHT 102
Definition at line 145 of file lcdi2c.h.
#define LCD_RS PCF8574_data.bits.P1
Definition at line 80 of file lcdi2c.h.
#define LCD_RW PCF8574_data.bits.P2
Definition at line 81 of file lcdi2c.h.
#define LCD_SETCGRAMADDR 0x40
Definition at line 113 of file lcdi2c.h.
#define LCD_SETDDRAMADDR 0x80
Definition at line 114 of file lcdi2c.h.
#define LCD_SYSTEM_SET_4BITS 0b00101000
Definition at line 99 of file lcdi2c.h.
#define LCD_SYSTEM_SET_8BITS 0b00111000
Definition at line 100 of file lcdi2c.h.
#define LCD_WRITE 0
Definition at line 88 of file lcdi2c.h.
#define MICRO 0b11100100
Definition at line 150 of file lcdi2c.h.
#define OCIRC 10
Definition at line 173 of file lcdi2c.h.
#define OCTAL 8
Definition at line 156 of file lcdi2c.h.
#define SIGMA 0b11100101
Definition at line 149 of file lcdi2c.h.
#define UCIRC 12
Definition at line 176 of file lcdi2c.h.
#define UGRAVE 11
Definition at line 175 of file lcdi2c.h.
Function Documentation
void lcdi2c_autoscroll ()
Definition at line 342 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYSHIFTINCREMENT.
{
    lcdi2c_send8(LCD_ENTRYSHIFTINCREMENT, LCD_CMD);
}
void lcdi2c_backlight ()
Definition at line 291 of file lcdi2c.c.
References Backlight, I2C1, I2C_send(), LCD_BL, PCF8574_address, and PCF8574_t::val.
Referenced by lcdi2c_init().
{
    Backlight = 1; // 0 = ON since PCF8574 is logical inverted
    LCD_BL = Backlight;
    I2C_send(I2C1, PCF8574_address, PCF8574_data.
      val);
}
void lcdi2c_blink ()
Definition at line 387 of file lcdi2c.c.
References LCD_BLINKON, and LCD_CMD.
{
    lcdi2c_send8(LCD_BLINKON, LCD_CMD);
}
void lcdi2c_clear ()
Definition at line 313 of file lcdi2c.c.
References Delayms(), LCD_CMD, and LCD_DISPLAY_CLEAR.
Referenced by lcdi2c_init().
{
    lcdi2c_send8(LCD_DISPLAY_CLEAR, LCD_CMD);
    Delayms(2); // Wait for more than 1.64ms
}
void lcdi2c_clearLine (u8)
Definition at line 458 of file lcdi2c.c.
References ESPACE, lcdi2c_setCursor(), lcdi2c_write(), and numcolmax.
{
    u8 i;
    lcdi2c_setCursor(0, line);
    for (i = 0; i < numcolmax; i++)
        lcdi2c_write(ESPACE); // affiche des espaces
}
void lcdi2c_cursor ()
Definition at line 405 of file lcdi2c.c.
References LCD_CMD, and LCD_CURSORON.
{
    lcdi2c_send8(LCD_CURSORON, LCD_CMD);
}
void lcdi2c_display ()
Definition at line 423 of file lcdi2c.c.
References LCD_CMD, and LCD_DISPLAYON.
{
    lcdi2c_send8(LCD_DISPLAYON, LCD_CMD);
}
void lcdi2c_home ()
Definition at line 323 of file lcdi2c.c.
References Delayms(), LCD_CMD, and LCD_CURSOR_HOME.
Referenced by lcdi2c_init().
{
    lcdi2c_send8(LCD_CURSOR_HOME, LCD_CMD);
    Delayms(2); // Wait for more than 1.64ms
}
void lcdi2c_init (u8 , u8 , u8)
Definition at line 444 of file lcdi2c.c.
References Delayms(), Delayus(), I2C1, I2C_100KHZ, I2C_1MHZ, I2C_init(), I2C_MASTER_MODE, LCD_CMD, LCD_DISPLAY_CLEAR, LCD_DISPLAY_ON, LCD_ENTRY_MODE_SET, LCD_SYSTEM_SET_4BITS, lcdi2c_backlight(), lcdi2c_clear(), lcdi2c_home(), numcolmax, numlinemax, PCF8574_address, PCF8574_t::val, and _Byte_::val.
{
    numcolmax = numcol - 1;
    numlinemax = numline - 1;
    //PCF8574_address = 0b01001110 | i2c_address;
    PCF8574_address = i2c_address;
    PCF8574_data.val = 0;
    I2C_init(I2C_MASTER_MODE, I2C_100KHZ);
    //Delayms(15); // Wait more than 15 ms after VDD rises to 4.5V
    lcdi2c_send4(0x30, LCD_CMD); // 0x30 - Mode 8 bits
    //Delayms(5); // Wait for more than 4.1 ms
    lcdi2c_send4(0x30, LCD_CMD); // 0x30 - Mode 8 bits
    //Delayus(100); // Wait more than 100 s
    lcdi2c_send4(0x30, LCD_CMD); // 0x30 - Mode 8 bits
    //Delayus(100); // Wait more than 100 s
    lcdi2c_send4(0x20, LCD_CMD); // 0x20 - Mode 4 bits
    lcdi2c_send8(LCD_SYSTEM_SET_4BITS, LCD_CMD); // 0x28 - Mode 4 bits - 2
       Lignes - 5x8
    //Delayus(4); // Wait more than 40 ns
    lcdi2c_send8(LCD_DISPLAY_ON, LCD_CMD); // 0x0C - Display ON + Cursor OFF +
       Blinking OFF
    //Delayus(4); // Wait more than 40 ns
    lcdi2c_send8(LCD_DISPLAY_CLEAR, LCD_CMD); // 0x01 - Efface l'affichage +
       init. DDRAM
    Delayms(2); // le temps d'execution de Display Clear > 1.64ms
    lcdi2c_send8(LCD_ENTRY_MODE_SET, LCD_CMD); // 0x06 - Increment + Display
       not shifted (Dplacement automatique du curseur)
    //Delayus(4); // Wait more than 40 ns
    //lcdi2c_newpattern(); // Implante les nouveaux caracteres
}
void lcdi2c_leftToRight ()
Definition at line 360 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYLEFT.
{
    lcdi2c_send8(LCD_ENTRYLEFT, LCD_CMD);
}
void lcdi2c_newchar (const u8 * , u8)
Definition at line 503 of file lcdi2c.c.
References LCD_ADRESS_CGRAM, LCD_CMD, and LCD_DATA.
Referenced by lcdi2c_newpattern().
{
    u8 i, a;
    // les caractres sont logs dans le CGRAM du LCD partir de l'adresse 0x40.
    a = (char_code << 3) | LCD_ADRESS_CGRAM;
    for(i=0; i<8; i++)
    {
        lcdi2c_send8(a, LCD_CMD);
        lcdi2c_send8(c[i], LCD_DATA);
        a++;
    };
}
void lcdi2c_newpattern ()
Definition at line 521 of file lcdi2c.c.
References ACIRC, AGRAVE, car0, car1, car2, car3, car4, car5, car6, car7, CCEDIL, EACUTE, ECIRC, EGRAVE, ETREMA, EURO, and lcdi2c_newchar().
{
    lcdi2c_newchar(car0, ACIRC); //
    lcdi2c_newchar(car1, AGRAVE); //
    lcdi2c_newchar(car2, CCEDIL); //
    lcdi2c_newchar(car3, EACUTE); //
    lcdi2c_newchar(car4, EGRAVE); //
    lcdi2c_newchar(car5, ECIRC); //
    lcdi2c_newchar(car6, ETREMA); //
    lcdi2c_newchar(car7, EURO); //
    //lcdi2c_newchar(car8, ICIRC); //
    //lcdi2c_newchar(car9, ITREMA); //
    //lcdi2c_newchar(car10, OCIRC); //
    //lcdi2c_newchar(car11, UGRAVE); //
    //lcdi2c_newchar(car12, UCIRC); //
}
void lcdi2c_noAutoscroll ()
Definition at line 333 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYSHIFTDECREMENT.
{
    lcdi2c_send8(LCD_ENTRYSHIFTDECREMENT, LCD_CMD);
}
void lcdi2c_noBacklight ()
Definition at line 302 of file lcdi2c.c.
References Backlight, I2C1, I2C_send(), LCD_BL, PCF8574_address, and PCF8574_t::val.
{
    Backlight = 0; // 1 = OFF since PCF8574 is logical inverted
    LCD_BL = Backlight;
    I2C_send(I2C1, PCF8574_address, PCF8574_data.
      val);
}
void lcdi2c_noBlink ()
Definition at line 396 of file lcdi2c.c.
References LCD_BLINKOFF, and LCD_CMD.
{
    lcdi2c_send8(LCD_BLINKOFF, LCD_CMD);
}
void lcdi2c_noCursor ()
Definition at line 414 of file lcdi2c.c.
References LCD_CMD, and LCD_CURSOROFF.
{
    lcdi2c_send8(LCD_CURSOROFF, LCD_CMD);
}
void lcdi2c_noDisplay ()
Definition at line 432 of file lcdi2c.c.
References LCD_CMD, and LCD_DISPLAYOFF.
{
    lcdi2c_send8(LCD_DISPLAYOFF, LCD_CMD);
}
void lcdi2c_printf (char * , ...)
Definition at line 483 of file lcdi2c.c.
References lcdi2c_write(), and pprintf().
{
    va_list args;
    va_start(args, fmt);
    pprintf(lcdi2c_write, fmt, args);
    va_end(args);
}
void lcdi2c_rightToLeft ()
Definition at line 351 of file lcdi2c.c.
References LCD_CMD, and LCD_ENTRYRIGHT.
{
    lcdi2c_send8(LCD_ENTRYRIGHT, LCD_CMD);
}
void lcdi2c_scrollDisplayLeft ()
Definition at line 378 of file lcdi2c.c.
References LCD_CMD, LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVELEFT.
{
    lcdi2c_send8(LCD_CURSORSHIFT | LCD_DISPLAYMOVE |
      LCD_MOVELEFT, LCD_CMD);
}
void lcdi2c_scrollDisplayRight ()
Definition at line 369 of file lcdi2c.c.
References LCD_CMD, LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVERIGHT.
{
    lcdi2c_send8(LCD_CURSORSHIFT | LCD_DISPLAYMOVE |
      LCD_MOVERIGHT, LCD_CMD);
}
void lcdi2c_setCursor (u8 , u8)
Definition at line 443 of file lcdi2c.c.
References LCD_CMD, LCD_SETDDRAMADDR, numcolmax, and numlinemax.
Referenced by lcdi2c_clearLine().
{
    int row_offsets[] = { 0x00, 0x40, 0x14, 0x54 };
    if (line > numlinemax)
        line = numlinemax - 1; // we count rows starting w/0
    if (col > numcolmax)
        col = numcolmax - 1; // we count rows starting w/0
    lcdi2c_send8(LCD_SETDDRAMADDR | (col + row_offsets[line]),
      LCD_CMD);
}
void lcdi2c_write (char)
Definition at line 473 of file lcdi2c.c.
References LCD_DATA.
{
    lcdi2c_send8(c, LCD_DATA);
}
Variable Documentation
u8 Backlight
VARIABLES GLOBALES.
Definition at line 229 of file lcdi2c.c.
Referenced by lcdi2c_backlight(), and lcdi2c_noBacklight().
const u8 car0[8]
Definition at line 91 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car1[8]
Definition at line 101 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car10[8]
Definition at line 191 of file lcdi2c.c.
const u8 car11[8]
Definition at line 201 of file lcdi2c.c.
const u8 car12[8]
Definition at line 211 of file lcdi2c.c.
const u8 car2[8]
Definition at line 111 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car3[8]
Definition at line 121 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car4[8]
Definition at line 131 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car5[8]
Definition at line 141 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car6[8]
Definition at line 151 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car7[8]
Definition at line 161 of file lcdi2c.c.
Referenced by lcdi2c_newpattern().
const u8 car8[8]
Definition at line 171 of file lcdi2c.c.
const u8 car9[8]
Definition at line 181 of file lcdi2c.c.