/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/DS1306.h File Reference
Data Structures
struct ds1306time
struct ds1306alarm
Macros
#define DS1306_DATETIME 0x00
#define DS1306_ALARM0 0x07
#define DS1306_ALARM1 0x0B
#define DS1306_CR 0x0F
#define DS1306_SR 0x10
#define DS1306_TCR 0x11
#define DS1306_USER_START 0x20
#define DS1306_USER_END 0x7F
#define DS1306_SIZE_DATETIME 7
#define DS1306_SIZE_ALARM 4
#define DS1306_CR_WP 6
#define DS1306_CR_1HZ 2
#define DS1306_CR_AIE1 1
#define DS1306_CR_AIE0 0
#define DS1306_SR_IRQF1 1
#define DS1306_SR_IRQF0 0
#define DS1306_TCR_TCS 7
#define DS1306_TCR_DS 3
#define DS1306_TCR_RS 1
#define DS1306_SUNDAY 1
#define DS1306_MONDAY 2
#define DS1306_TUESDAY 3
#define DS1306_WEDNESDAY 4
#define DS1306_THURSDAY 5
#define DS1306_FRIDAY 6
#define DS1306_SATURDAY 7
#define DS1306_ANY 0x80
#define DS1306_WRITE_OFFSET 0x80
Functions
void DS1306_Init (u8 LocalSPI, u8 LoCE, u8 LoSCK, u8 LoSDO, u8 LoSDI)
void DS1306_Hours24 (BOOL Hours24)
void DS1306_setTime (const ds1306time *time)
void DS1306_getTime (ds1306time *time)
void DS1306_setAlarm (int alarm, const ds1306alarm *time)
void DS1306_getAlarm (int alarm, ds1306alarm *time)
BOOL DS1306_getAlarmState (unsigned int alarm)
void DS1306_getAlarmBothState (BOOL *state1, BOOL *state2)
void DS1306_clearAlarmState (unsigned int alarm)
void DS1306_clearAlarmBothState ()
BOOL DS1306_getAlarmEnabled (unsigned int alarm)
void DS1306_getAlarmBothEnabled (BOOL *enabled1, BOOL *enabled2)
void DS1306_enableAlarm (unsigned int alarm)
void DS1306_disableAlarm (unsigned int alarm)
void DS1306_enableBothAlarms ()
void DS1306_disableBothAlarms ()
BOOL DS1306_get1HzState ()
void DS1306_set1HzState (BOOL enabled)
BOOL DS1306_enableTrickleCharge (unsigned char numDiodes, unsigned char kRes)
void DS1306_disableTrickleCharge ()
BOOL DS1306_getTrickleChargeState (unsigned char *numDiodes, unsigned char *kRes)
BOOL DS1306_writeUser (unsigned char addr, const char *buf, int num)
BOOL DS1306_readUser (unsigned char addr, char *buf, int num)
BOOL DS1306_isWriteProtected ()
void DS1306_setWriteProtection (BOOL on)
void DS1306_readn (unsigned char address, unsigned char *data, int len)
unsigned char DS1306_read (unsigned char address)
void DS1306_writen (unsigned char address, const unsigned char *data, int len)
void DS1306_write (unsigned char address, const unsigned char value)
void DS1306_encodeTimePacket (unsigned char *buf, const ds1306time *time)
void DS1306_encodeAlarmPacket (unsigned char *buf, const ds1306alarm *alarm)
void DS1306_decodeTimePacket (const unsigned char *buf, ds1306time *time)
void DS1306_decodeAlarmPacket (const unsigned char *buf, ds1306alarm *alarm)
void DS1306_decodeHourByte (unsigned char hourByte, unsigned char *hour24, unsigned char *hour12, char *ampm)
unsigned char DS1306_encodeHourByte (unsigned char hour24, unsigned char hour12, char ampm)
unsigned char DS1306_encodeBCD7 (unsigned char value)
unsigned char DS1306_encodeBCD7M (unsigned char value, unsigned char mask)
unsigned char DS1306_encodeBCD8 (unsigned char value)
unsigned char DS1306_decodeBCD7 (unsigned char value)
unsigned char DS1306_decodeBCD7M (unsigned char value, unsigned char mask)
unsigned char DS1306_decodeBCD8 (unsigned char value)
Macro Definition Documentation
#define DS1306_ALARM0 0x07
Definition at line 27 of file DS1306.h.
#define DS1306_ALARM1 0x0B
Definition at line 28 of file DS1306.h.
#define DS1306_ANY 0x80
Definition at line 64 of file DS1306.h.
#define DS1306_CR 0x0F
Definition at line 29 of file DS1306.h.
#define DS1306_CR_1HZ 2
Definition at line 41 of file DS1306.h.
#define DS1306_CR_AIE0 0
Definition at line 43 of file DS1306.h.
#define DS1306_CR_AIE1 1
Definition at line 42 of file DS1306.h.
#define DS1306_CR_WP 6
Definition at line 40 of file DS1306.h.
#define DS1306_DATETIME 0x00
Definition at line 26 of file DS1306.h.
#define DS1306_FRIDAY 6
Definition at line 60 of file DS1306.h.
#define DS1306_MONDAY 2
Definition at line 56 of file DS1306.h.
#define DS1306_SATURDAY 7
Definition at line 61 of file DS1306.h.
#define DS1306_SIZE_ALARM 4
Definition at line 37 of file DS1306.h.
#define DS1306_SIZE_DATETIME 7
Definition at line 36 of file DS1306.h.
#define DS1306_SR 0x10
Definition at line 30 of file DS1306.h.
#define DS1306_SR_IRQF0 0
Definition at line 47 of file DS1306.h.
#define DS1306_SR_IRQF1 1
Definition at line 46 of file DS1306.h.
#define DS1306_SUNDAY 1
Definition at line 55 of file DS1306.h.
#define DS1306_TCR 0x11
Definition at line 31 of file DS1306.h.
#define DS1306_TCR_DS 3
Definition at line 51 of file DS1306.h.
#define DS1306_TCR_RS 1
Definition at line 52 of file DS1306.h.
#define DS1306_TCR_TCS 7
Definition at line 50 of file DS1306.h.
#define DS1306_THURSDAY 5
Definition at line 59 of file DS1306.h.
#define DS1306_TUESDAY 3
Definition at line 57 of file DS1306.h.
#define DS1306_USER_END 0x7F
Definition at line 33 of file DS1306.h.
#define DS1306_USER_START 0x20
Definition at line 32 of file DS1306.h.
#define DS1306_WEDNESDAY 4
Definition at line 58 of file DS1306.h.
#define DS1306_WRITE_OFFSET 0x80
Definition at line 67 of file DS1306.h.
Function Documentation
void DS1306_clearAlarmBothState ()
Definition at line 377 of file DS1306.c.
References DS1306_SR, and DS1306_write().
{
    DS1306_write(DS1306_SR, 0);
}
void DS1306_clearAlarmState (unsigned int alarm)
Definition at line 369 of file DS1306.c.
References DS1306_read(), DS1306_SR, and DS1306_write().
{
    if (alarm > 1) return;
    DS1306_write(DS1306_SR, DS1306_read(
      DS1306_SR) & ~ (1 << alarm));
}
void DS1306_decodeAlarmPacket (const unsigned char * buf, ds1306alarm * alarm)
Definition at line 243 of file DS1306.c.
References ds1306alarm::ampm, ds1306alarm::dow, DS1306_decodeBCD7M(), DS1306_decodeHourByte(), ds1306alarm::hours, ds1306alarm::hours12, ds1306alarm::minutes, and ds1306alarm::seconds.
Referenced by DS1306_getAlarm().
{
    alarm->seconds = DS1306_decodeBCD7M(buf[0], 0x7F);
    alarm->minutes = DS1306_decodeBCD7M(buf[1], 0x7F);
    DS1306_decodeHourByte(buf[2], &(alarm->hours), &(alarm->
      hours12), &(alarm->ampm));
    alarm->dow = DS1306_decodeBCD7M(buf[3], 0x07);
}
unsigned char DS1306_decodeBCD7 (unsigned char value)
Definition at line 188 of file DS1306.c.
References DS1306_ANY.
Referenced by DS1306_decodeBCD7M().
{
    return ((value & DS1306_ANY) ? DS1306_ANY : ((((value & 0xF0) >> 4) * 10) + (value & 0x0F)));
}
unsigned char DS1306_decodeBCD7M (unsigned char value, unsigned char mask)
Definition at line 193 of file DS1306.c.
References DS1306_ANY, and DS1306_decodeBCD7().
Referenced by DS1306_decodeAlarmPacket(), DS1306_decodeHourByte(), and DS1306_decodeTimePacket().
{
    return ((value & DS1306_ANY) ? DS1306_ANY : DS1306_decodeBCD7(value & mask))
      ;
}
unsigned char DS1306_decodeBCD8 (unsigned char value)
Definition at line 200 of file DS1306.c.
Referenced by DS1306_decodeTimePacket().
{
    return ((((value & 0xF0) >> 4) * 10) + (value & 0x0F));
}
void DS1306_decodeHourByte (unsigned char hourByte, unsigned char * hour24, unsigned char * hour12, char * ampm)
Definition at line 267 of file DS1306.c.
References DS1306_ANY, and DS1306_decodeBCD7M().
Referenced by DS1306_decodeAlarmPacket(), and DS1306_decodeTimePacket().
{
    if (hourByte & DS1306_ANY) {
        *hour12 = DS1306_ANY;
        *hour24 = DS1306_ANY;
        *ampm = 0;
    } else {
        if (hourByte & 0x40) {
            // 12 hour mode
            *hour12 = DS1306_decodeBCD7M(hourByte, 0x1F);
            if (hourByte & 0x20) {
                // PM
                if (*hour12 == 12) {
                    *hour24 = 12;
                } else {
                    *hour24 = 12 + *hour12;
                }
                *ampm = 'P';
            } else {
                // AM
                *hour24 = (*hour12 == 12) ? 0 : *hour12;
                *ampm = 'A';
            }
        } else {
            // 24 hour mode
            *hour24 = DS1306_decodeBCD7M(hourByte, 0x3F);
            if (*hour24 == 0) {
                *hour12 = 12;
                *ampm = 'A';
            } else if (*hour24 == 12) {
                *hour12 = 12;
                *ampm = 'P';
            } else if (*hour24 < 12) {
                *ampm = 'A';
                *hour12 = *hour24;
            } else {
                *ampm = 'P';
                *hour12 = *hour24 - 12;
            }
        }
    }
}
void DS1306_decodeTimePacket (const unsigned char * buf, ds1306time * time)
Definition at line 231 of file DS1306.c.
References ds1306time::ampm, ds1306time::day, ds1306time::dow, DS1306_decodeBCD7M(), DS1306_decodeBCD8(), DS1306_decodeHourByte(), ds1306time::hours, ds1306time::hours12, ds1306time::minutes, ds1306time::month, ds1306time::seconds, and ds1306time::year.
Referenced by DS1306_getTime().
{
    time->seconds = DS1306_decodeBCD7M(buf[0], 0x7F);
    time->minutes = DS1306_decodeBCD7M(buf[1], 0x7F);
    DS1306_decodeHourByte(buf[2], &(time->hours), &(time->
      hours12), &(time->ampm));
    time->dow = DS1306_decodeBCD7M(buf[3], 0x07);
    time->day = DS1306_decodeBCD7M(buf[4], 0x3F);
    time->month = DS1306_decodeBCD7M(buf[5], 0x3F);
    time->year = DS1306_decodeBCD8(buf[6]);
}
void DS1306_disableAlarm (unsigned int alarm)
Definition at line 406 of file DS1306.c.
References DS1306_CR, DS1306_read(), and DS1306_write().
{
    if (alarm > 1) return;
    DS1306_write(DS1306_CR, DS1306_read(
      DS1306_CR) & ~ (1 << alarm));
}
void DS1306_disableBothAlarms ()
Definition at line 419 of file DS1306.c.
References DS1306_CR, DS1306_read(), and DS1306_write().
{
    DS1306_write(DS1306_CR, DS1306_read(
      DS1306_CR) & ~ 0x03);
}
void DS1306_disableTrickleCharge ()
Definition at line 446 of file DS1306.c.
References DS1306_TCR, and DS1306_writen().
{
    unsigned char b = 0;
    DS1306_writen(DS1306_TCR, &b, 1);
}
void DS1306_enableAlarm (unsigned int alarm)
Definition at line 399 of file DS1306.c.
References DS1306_CR, DS1306_read(), and DS1306_write().
{
    if (alarm > 1) return;
    DS1306_write(DS1306_CR, DS1306_read(
      DS1306_CR) | (1 << alarm));
}
void DS1306_enableBothAlarms ()
Definition at line 413 of file DS1306.c.
References DS1306_CR, DS1306_read(), and DS1306_write().
{
    DS1306_write(DS1306_CR, DS1306_read(
      DS1306_CR) | 0x03);
}
BOOL DS1306_enableTrickleCharge (unsigned char numDiodes, unsigned char kRes)
Definition at line 428 of file DS1306.c.
References DS1306_TCR, and DS1306_writen().
{
    unsigned char b;
    if (numDiodes < 1 || numDiodes > 2) return false;
    
    b = 0xA0 | (numDiodes << 2);
    switch(kRes) {
        case 2 : b |= 0x01; break;
        case 4 : b |= 0x02; break;
        case 8 : b |= 0x03; break;
        default : return false;
    }
    DS1306_writen(DS1306_TCR, &b, 1);
}
void DS1306_encodeAlarmPacket (unsigned char * buf, const ds1306alarm * alarm)
Definition at line 222 of file DS1306.c.
References ds1306alarm::ampm, ds1306alarm::dow, DS1306_encodeBCD7M(), DS1306_encodeHourByte(), ds1306alarm::hours, ds1306alarm::hours12, ds1306alarm::minutes, and ds1306alarm::seconds.
Referenced by DS1306_setAlarm().
{
    buf[0] = DS1306_encodeBCD7M(alarm->seconds, 0x7F);
    buf[1] = DS1306_encodeBCD7M(alarm->minutes, 0x7F);
    buf[2] = DS1306_encodeHourByte(alarm->hours, alarm->
      hours12, alarm->ampm);
    buf[3] = DS1306_encodeBCD7M(alarm->dow, 0x07);
}
unsigned char DS1306_encodeBCD7 (unsigned char value)
Definition at line 170 of file DS1306.c.
References DS1306_ANY.
{
    return ((value & DS1306_ANY) ? DS1306_ANY : (((value / 10) << 4) | (value % 10)));
}
unsigned char DS1306_encodeBCD7M (unsigned char value, unsigned char mask)
Definition at line 176 of file DS1306.c.
References DS1306_ANY.
Referenced by DS1306_encodeAlarmPacket(), DS1306_encodeHourByte(), and DS1306_encodeTimePacket().
{
    return ((value & DS1306_ANY) ? DS1306_ANY : (((value / 10) << 4) | (value % 10)) & mask);
}
unsigned char DS1306_encodeBCD8 (unsigned char value)
Definition at line 182 of file DS1306.c.
Referenced by DS1306_encodeTimePacket().
{
    return (((value / 10) << 4) | (value % 10));
}
unsigned char DS1306_encodeHourByte (unsigned char hour24, unsigned char hour12, char ampm)
Definition at line 252 of file DS1306.c.
References DS1306_ANY, DS1306_encodeBCD7M(), and DS1306_writeHours24.
Referenced by DS1306_encodeAlarmPacket(), and DS1306_encodeTimePacket().
{
    if ((DS1306_writeHours24 && ((hour24 & DS1306_ANY))) || (!
      DS1306_writeHours24 && (hour12 & DS1306_ANY))) {
        return DS1306_ANY;
    } else {
        if (DS1306_writeHours24) {
            // Writing 24 hour format times
            return DS1306_encodeBCD7M(hour24, 0x3F);
        } else {
            return (DS1306_encodeBCD7M(hour12, 0x1F) | 0x40 | (ampm == 'P' ? 0x20 : 0x00)
      );
        }
    }
}
void DS1306_encodeTimePacket (unsigned char * buf, const ds1306time * time)
Definition at line 209 of file DS1306.c.
References ds1306time::ampm, ds1306time::day, ds1306time::dow, DS1306_encodeBCD7M(), DS1306_encodeBCD8(), DS1306_encodeHourByte(), ds1306time::hours, ds1306time::hours12, ds1306time::minutes, ds1306time::month, ds1306time::seconds, and ds1306time::year.
Referenced by DS1306_setTime().
{
    buf[0] = DS1306_encodeBCD7M(time->seconds, 0x7F);
    buf[1] = DS1306_encodeBCD7M(time->minutes, 0x7F);
    buf[2] = DS1306_encodeHourByte(time->hours, time->
      hours12, time->ampm);
    buf[3] = DS1306_encodeBCD7M(time->dow, 0x07);
    buf[4] = DS1306_encodeBCD7M(time->day, 0x3F);
    buf[5] = DS1306_encodeBCD7M(time->month, 0x3F);
    buf[6] = DS1306_encodeBCD8(time->year);
}
BOOL DS1306_get1HzState ()
Definition at line 525 of file DS1306.c.
References DS1306_CR, DS1306_CR_1HZ, and DS1306_read().
{
    unsigned char cr = DS1306_read(DS1306_CR);
    return ((cr & (1 << DS1306_CR_1HZ)) ? true : false);
}
void DS1306_getAlarm (int alarm, ds1306alarm * time)
Definition at line 340 of file DS1306.c.
References DS1306_ALARM0, DS1306_ALARM1, DS1306_decodeAlarmPacket(), DS1306_readn(), and DS1306_SIZE_ALARM.
{
    memset((__data *)time, 0, sizeof(ds1306time));
    if (alarm < 2) {
        unsigned char buf[DS1306_SIZE_ALARM];
        DS1306_readn(alarm == 0 ? DS1306_ALARM0 :
      DS1306_ALARM1, buf, DS1306_SIZE_ALARM);
        DS1306_decodeAlarmPacket(buf, time);
    }
}
void DS1306_getAlarmBothEnabled (BOOL * enabled1, BOOL * enabled2)
Definition at line 391 of file DS1306.c.
References DS1306_CR, and DS1306_read().
{
    unsigned char cr = DS1306_read(DS1306_CR);
    *enabled1 = (cr & 0x01) ? true : false;
    *enabled2 = (cr & 0x01) ? true : false;
}
void DS1306_getAlarmBothState (BOOL * state1, BOOL * state2)
Definition at line 361 of file DS1306.c.
References DS1306_read(), and DS1306_SR.
{
    unsigned char sr = DS1306_read(DS1306_SR);
    *state1 = (sr & 0x01) ? true : false;
    *state2 = (sr & 0x02) ? true : false;
}
BOOL DS1306_getAlarmEnabled (unsigned int alarm)
Definition at line 384 of file DS1306.c.
References DS1306_CR, and DS1306_read().
{
    if (alarm > 1) return false;
    return((DS1306_read(DS1306_CR) & (1 << alarm)) ? true : false);
}
BOOL DS1306_getAlarmState (unsigned int alarm)
Definition at line 353 of file DS1306.c.
References DS1306_read(), and DS1306_SR.
{
    if (alarm > 1) return false;
    return ((DS1306_read(DS1306_SR) & (1 << alarm)) ? true : false);
}
void DS1306_getTime (ds1306time * time)
Definition at line 313 of file DS1306.c.
References DS1306_DATETIME, DS1306_decodeTimePacket(), DS1306_readn(), and DS1306_SIZE_DATETIME.
{
    unsigned char buf[DS1306_SIZE_DATETIME];
    memset((__data *)time, 0, sizeof(ds1306time));
    DS1306_readn(DS1306_DATETIME, buf,
      DS1306_SIZE_DATETIME);
    DS1306_decodeTimePacket(buf, time);
}
BOOL DS1306_getTrickleChargeState (unsigned char * numDiodes, unsigned char * kRes)
Definition at line 456 of file DS1306.c.
References DS1306_readn(), and DS1306_TCR.
{
    unsigned char b;
    DS1306_readn(DS1306_TCR, &b, 1);
    *numDiodes = 0;
    *kRes = 0;
    if ((b & 0xF0) != 0xA0) return false; // TCR disabled
    switch(b & 0x03) {
        case 0x01 : *kRes = 2; break;
        case 0x02 : *kRes = 4; break;
        case 0x03 : *kRes = 8; break;
        default : return false;
    }
    // TCR is enabled if we got this far
    *numDiodes = (b & 0x0C) >> 2;
    return true;
}
void DS1306_Hours24 (BOOL Hours24)
Definition at line 80 of file DS1306.c.
References DS1306_writeHours24.
{
 DS1306_writeHours24 = Hours24;
}
void DS1306_Init (u8 LocalSPI, u8 LoCE, u8 LoSCK, u8 LoSDO, u8 LoSDI)
Definition at line 36 of file DS1306.c.
References SPI_Loc_Conf::CPHA, SPI_Loc_Conf::CPOL, SPI_Loc_Conf::DelayuS, digitalwrite(), DS1306_CE, DS1306_CR, DS1306_CR_WP, DS1306_LocalSPI, DS1306_read(), DS1306_write(), FALSE, SPI_Loc_Conf::LoSCK, SPI_Loc_Conf::LoSDI, SPI_Loc_Conf::LoSDO, LOW, OUTPUT, pinmode(), SPI_init(), SPILoc_Init(), and TRUE.
{
    unsigned char cr;
    // Initialize SPI Bus
  DS1306_CE = LoCE;
  DS1306_LocalSPI = LocalSPI;
    // Initialize the chip enable, LOW
    pinmode(DS1306_CE, OUTPUT);
    digitalwrite(DS1306_CE, LOW);
  
  
  switch (DS1306_LocalSPI)
   {
    case 0:
     DS1306_SPILoc.CPOL = FALSE; // Clock Polarity
     DS1306_SPILoc.CPHA = TRUE; // Sample position
     DS1306_SPILoc.DelayuS = 0; // Delay Clock uS
     DS1306_SPILoc.LoSCK = LoSCK;
     DS1306_SPILoc.LoSDO = LoSDO;
     DS1306_SPILoc.LoSDI = LoSDI;
     SPILoc_Init (&DS1306_SPILoc);
    break;
    case 1:
    case 2:
     SPI_init();
     break;
   }
    // digitalread control register
    cr = DS1306_read(DS1306_CR);
    // Rewrite control register, disabling write protect
    // disabling write protect
    cr = cr & ~ (1 << DS1306_CR_WP);
    DS1306_write(DS1306_CR, cr);
}
BOOL DS1306_isWriteProtected ()
Definition at line 507 of file DS1306.c.
References DS1306_CR, DS1306_CR_WP, and DS1306_read().
{
    return ((DS1306_read(DS1306_CR) & (1 << DS1306_CR_WP)) ? true : false);
}
unsigned char DS1306_read (unsigned char address)
Definition at line 127 of file DS1306.c.
References DS1306_readn().
Referenced by DS1306_clearAlarmState(), DS1306_disableAlarm(), DS1306_disableBothAlarms(), DS1306_enableAlarm(), DS1306_enableBothAlarms(), DS1306_get1HzState(), DS1306_getAlarmBothEnabled(), DS1306_getAlarmBothState(), DS1306_getAlarmEnabled(), DS1306_getAlarmState(), DS1306_init(), DS1306_Init(), DS1306_isWriteProtected(), DS1306_set1HzState(), and DS1306_setWriteProtection().
{
    unsigned char buf;
    DS1306_readn(address, &buf, 1);
    return buf;
}
void DS1306_readn (unsigned char address, unsigned char * data, int len)
Definition at line 100 of file DS1306.c.
References digitalwrite(), DS1306_CE, DS1306_LocalSPI, HIGH, LOW, SPI_read(), SPI_write(), SPILoc_Read(), and SPILoc_Write().
Referenced by DS1306_getAlarm(), DS1306_getTime(), DS1306_getTrickleChargeState(), DS1306_read(), and DS1306_readUser().
{
 int i;
    // Select the DS1306 by raising it's chip enable line
    digitalwrite(DS1306_CE, HIGH);
 switch (DS1306_LocalSPI)
  {
   case 0:
    SPILoc_Write(&DS1306_SPILoc, address);
     for (i = 0; i < len; i++)
     data[i] = SPILoc_Read(&DS1306_SPILoc);
    break;
   case 1:
   case 2:
    SPI_write(address);
     for (i = 0; i < len; i++)
     data[i] = SPI_read();
    break;
  }
 digitalwrite(DS1306_CE, LOW);
}
BOOL DS1306_readUser (unsigned char addr, char * buf, int num)
Definition at line 495 of file DS1306.c.
References DS1306_readn(), DS1306_USER_END, and DS1306_USER_START.
{
    memset((__data *)buf, 0, num);
    if (addr >= DS1306_USER_START && addr < DS1306_USER_END && (addr + num
      - 1) <= DS1306_USER_END) {
        DS1306_readn(addr, (unsigned char *) buf, num);
        return true;
    } else {
        return false;
    }
}
void DS1306_set1HzState (BOOL enabled)
Definition at line 532 of file DS1306.c.
References DS1306_CR, DS1306_CR_1HZ, DS1306_read(), and DS1306_write().
{
    unsigned char cr = DS1306_read(DS1306_CR);
    if (enabled) {
        cr |= (1 << DS1306_CR_1HZ);
    } else {
        cr &= ~ (1 << DS1306_CR_1HZ);
    }
    DS1306_write(DS1306_CR, cr);
}
void DS1306_setAlarm (int alarm, const ds1306alarm * time)
Definition at line 327 of file DS1306.c.
References DS1306_ALARM0, DS1306_ALARM1, DS1306_encodeAlarmPacket(), DS1306_SIZE_ALARM, and DS1306_writen().
{
    if (alarm < 2) {
        unsigned char buf[DS1306_SIZE_ALARM];
        DS1306_encodeAlarmPacket(buf, time);
        DS1306_writen(alarm == 0 ? DS1306_ALARM0 :
      DS1306_ALARM1, buf, DS1306_SIZE_ALARM);
    }
}
void DS1306_setTime (const ds1306time * time)
Definition at line 89 of file DS1306.c.
References DS1306_DATETIME, DS1306_encodeTimePacket(), DS1306_SIZE_DATETIME, and DS1306_writen().
{
    unsigned char buf[DS1306_SIZE_DATETIME];
    DS1306_encodeTimePacket(buf, time);
    DS1306_writen(DS1306_DATETIME, buf,
      DS1306_SIZE_DATETIME);
}
void DS1306_setWriteProtection (BOOL on)
Definition at line 513 of file DS1306.c.
References DS1306_CR, DS1306_CR_WP, DS1306_read(), and DS1306_write().
{
    unsigned char cr = DS1306_read(DS1306_CR);
    if (on) {
        cr |= (1 << DS1306_CR_WP);
    } else {
        cr &= ~ (1 << DS1306_CR_WP);
    }
    DS1306_write(DS1306_CR, cr);
}
void DS1306_write (unsigned char address, const unsigned char value)
Definition at line 160 of file DS1306.c.
References DS1306_writen().
Referenced by DS1306_clearAlarmBothState(), DS1306_clearAlarmState(), DS1306_disableAlarm(), DS1306_disableBothAlarms(), DS1306_enableAlarm(), DS1306_enableBothAlarms(), DS1306_init(), DS1306_Init(), DS1306_set1HzState(), and DS1306_setWriteProtection().
{
    DS1306_writen(address, &value, 1);
}
void DS1306_writen (unsigned char address, const unsigned char * data, int len)
Definition at line 136 of file DS1306.c.
References digitalwrite(), DS1306_CE, DS1306_LocalSPI, DS1306_WRITE_OFFSET, HIGH, LOW, SPI_write(), and SPILoc_Write().
Referenced by DS1306_disableTrickleCharge(), DS1306_enableTrickleCharge(), DS1306_setAlarm(), DS1306_setTime(), DS1306_write(), and DS1306_writeUser().
{
 int i;
    digitalwrite(DS1306_CE, HIGH);
 switch (DS1306_LocalSPI)
  {
   case 0:
    SPILoc_Write(&DS1306_SPILoc, address |
      DS1306_WRITE_OFFSET);
    for (i = 0; i < len; i++)
     SPILoc_Write(&DS1306_SPILoc, data[i]);
    break;
   case 1:
   case 2:
    SPI_write(address | DS1306_WRITE_OFFSET);
    for (i = 0; i < len; i++)
     SPI_write(data[i]);
    break;
  }
    digitalwrite(DS1306_CE, LOW);
}
BOOL DS1306_writeUser (unsigned char addr, const char * buf, int num)
Definition at line 482 of file DS1306.c.
References DS1306_USER_END, DS1306_USER_START, and DS1306_writen().
{
    if (addr >= DS1306_USER_START && addr < DS1306_USER_END && (addr + num
      - 1) <= DS1306_USER_END) {
        DS1306_writen(addr, (const unsigned char *) buf, num);
        return true;
    } else {
        return false;
    }
}