/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/serial.c File Reference
#include <typedef.h>
*
#include <system.c>
*
#include <interrupt.c>
*
#include <digitalw.c>
*
#include <printf.c>
*
Macros
#define __SERIAL__
#define UART1 1
#define UART2 2
#define UART_DISABLE 0x0000
#define UART_ENABLE 0x8000
#define UART_ENABLE_STOP_ON_IDLE 0x2000
#define UART_ENABLE_IRDA 0x1000
#define UART_RTS_WHEN_RX_NOT_FULL 0x000
#define UART_RTS_WHEN_TX_NOT_EMPTY 0x800
#define UART_ENABLE_PINS_BIT_CLOCK 0x300
#define UART_ENABLE_PINS_CTS_RTS 0x200
#define UART_ENABLE_PINS_RTS 0x100
#define UART_ENABLE_PINS_TX_RX_ONLY 0x000
#define UART_ENABLE_WAKE_ON_START 0x80
#define UART_ENABLE_LOOPBACK 0x40
#define UART_INVERT_RECEIVE_POLARITY 0x10
#define UART_ENABLE_HIGH_SPEED 1
#define UART_ENABLE_STANDARD_SPEED 0
#define UART_9_BITS_NO_PARITY 0x06
#define UART_8_BITS_ODD_PARITY 0x04
#define UART_8_BITS_EVEN_PARITY 0x02
#define UART_8_BITS_NO_PARITY 0x00
#define UART_STOP_BITS_2 0x01
#define UART_STOP_BITS_1 0x00
#define UART_INTERRUPT_ON_TX_BUFFER_EMPTY 0x8000
#define UART_INTERRUPT_ON_TX_DONE 0x4000
#define UART_INTERRUPT_ON_TX_NOT_FULL 0x0000
#define UART_INVERT_TRANSMIT_POLARITY 0x2000
#define UART_RX_ENABLED 0x1000
#define UART_RX_DISABLED 0x0000
#define UART_TX_ENABLED 0x400
#define UART_TX_DISABLED 0x000
#define UART_RX_TX_ENABLED 0x1400
#define UART_INTERRUPT_ON_RX_FULL 0xC0
#define UART_INTERRUPT_ON_RX_HALF_FULL 0x40
#define UART_INTERRUPT_ON_RX_NOT_EMPTY 0x00
#define UART_SUPPORT_IEEE_485 0x00000900
#define UART_TRANSMITTER_NOT_FULL 0x00000200
#define UART_TRANSMITTER_EMPTY 0x00000100
#define UART_RECEIVER_IDLE 0x00000010
#define UART_PARITY_ERROR 0x00000008
#define UART_FRAMING_ERROR 0x00000004
#define UART_OVERRUN_ERROR 0x00000002
#define UART_DATA_READY 0x00000001
#define SERIAL_BUFFERLENGTH 128
Functions
void SerialSetDataRate (u8 port, u32 baudrate)
u32 SerialGetDataRate (u8 port)
void SerialEnable (u8 port, u32 config)
void SerialSetLineControl (u8 port, u32 config)
void SerialFlush (u8 port)
void SerialPinConfigure (u8 port)
void SerialIntConfigure (u8 port, u8 priority, u8 subpriority)
void SerialConfigure (u8 port, u32 config, u32 enable, u32 baudrate)
void SerialUART1WriteChar (char c)
void SerialUART2WriteChar (char c)
void SerialPutChar (u8 port, char c)
char SerialAvailable (u8 port)
int SerialRead (u8 port)
char SerialGetKey (u8 port)
char * SerialGetString (u8 port)
void SerialGetDataBuffer (u8 port)
void Serial1Interrupt (void)
void Serial2Interrupt (void)
BOOL ClearRxError (u8 port)
Variables
volatile unsigned char UART1SerialBuffer [SERIAL_BUFFERLENGTH]
volatile unsigned char UART2SerialBuffer [SERIAL_BUFFERLENGTH]
volatile long UART1wpointer
volatile long UART1rpointer
volatile long UART2wpointer
volatile long UART2rpointer
Macro Definition Documentation
#define __SERIAL__
Definition at line 32 of file serial.c.
#define SERIAL_BUFFERLENGTH 128
Definition at line 157 of file serial.c.
Referenced by SerialGetDataBuffer(), and SerialRead().
#define UART1 1
Definition at line 40 of file serial.c.
Referenced by ClearRxError(), open(), read(), serial1available(), serial1clearrxerror(), serial1flush(), serial1getkey(), serial1getstring(), serial1init(), Serial1Interrupt(), serial1read(), serial2available(), serial2clearrxerror(), serial2flush(), serial2getkey(), serial2getstring(), serial2init(), serial2read(), SerialAvailable(), SerialEnable(), SerialFlush(), SerialGetDataBuffer(), SerialGetDataRate(), SerialIntConfigure(), SerialPinConfigure(), SerialPutChar(), SerialRead(), SerialSetDataRate(), and SerialSetLineControl().
#define UART2 2
Definition at line 41 of file serial.c.
Referenced by ClearRxError(), open(), serial1available(), serial1clearrxerror(), serial1flush(), serial1getkey(), serial1getstring(), serial1init(), serial1read(), serial2available(), serial2clearrxerror(), serial2flush(), serial2getkey(), serial2getstring(), serial2init(), Serial2Interrupt(), serial2read(), SerialAvailable(), SerialEnable(), SerialFlush(), SerialGetDataBuffer(), SerialGetDataRate(), SerialIntConfigure(), SerialPinConfigure(), SerialPutChar(), SerialRead(), SerialSetDataRate(), and SerialSetLineControl().
#define UART_8_BITS_EVEN_PARITY 0x02
Definition at line 104 of file serial.c.
#define UART_8_BITS_NO_PARITY 0x00
Definition at line 105 of file serial.c.
#define UART_8_BITS_ODD_PARITY 0x04
Definition at line 103 of file serial.c.
#define UART_9_BITS_NO_PARITY 0x06
Definition at line 102 of file serial.c.
#define UART_DATA_READY 0x00000001
Definition at line 154 of file serial.c.
#define UART_DISABLE 0x0000
Definition at line 61 of file serial.c.
#define UART_ENABLE 0x8000
Definition at line 62 of file serial.c.
Referenced by BT_init(), open(), serial1init(), serial2init(), serial3init(), serial4init(), serial5init(), and serial6init().
#define UART_ENABLE_HIGH_SPEED 1
Definition at line 97 of file serial.c.
Referenced by SerialGetDataRate(), and SerialSetDataRate().
#define UART_ENABLE_IRDA 0x1000
Definition at line 72 of file serial.c.
#define UART_ENABLE_LOOPBACK 0x40
Definition at line 88 of file serial.c.
#define UART_ENABLE_PINS_BIT_CLOCK 0x300
Definition at line 79 of file serial.c.
#define UART_ENABLE_PINS_CTS_RTS 0x200
Definition at line 80 of file serial.c.
#define UART_ENABLE_PINS_RTS 0x100
Definition at line 81 of file serial.c.
#define UART_ENABLE_PINS_TX_RX_ONLY 0x000
Definition at line 82 of file serial.c.
#define UART_ENABLE_STANDARD_SPEED 0
Definition at line 98 of file serial.c.
#define UART_ENABLE_STOP_ON_IDLE 0x2000
Definition at line 69 of file serial.c.
#define UART_ENABLE_WAKE_ON_START 0x80
Definition at line 85 of file serial.c.
#define UART_FRAMING_ERROR 0x00000004
Definition at line 152 of file serial.c.
#define UART_INTERRUPT_ON_RX_FULL 0xC0
Definition at line 138 of file serial.c.
#define UART_INTERRUPT_ON_RX_HALF_FULL 0x40
Definition at line 139 of file serial.c.
#define UART_INTERRUPT_ON_RX_NOT_EMPTY 0x00
Definition at line 140 of file serial.c.
#define UART_INTERRUPT_ON_TX_BUFFER_EMPTY 0x8000
Definition at line 118 of file serial.c.
#define UART_INTERRUPT_ON_TX_DONE 0x4000
Definition at line 119 of file serial.c.
#define UART_INTERRUPT_ON_TX_NOT_FULL 0x0000
Definition at line 120 of file serial.c.
#define UART_INVERT_RECEIVE_POLARITY 0x10
Definition at line 93 of file serial.c.
#define UART_INVERT_TRANSMIT_POLARITY 0x2000
Definition at line 123 of file serial.c.
#define UART_OVERRUN_ERROR 0x00000002
Definition at line 153 of file serial.c.
#define UART_PARITY_ERROR 0x00000008
Definition at line 151 of file serial.c.
#define UART_RECEIVER_IDLE 0x00000010
Definition at line 150 of file serial.c.
#define UART_RTS_WHEN_RX_NOT_FULL 0x000
Definition at line 75 of file serial.c.
#define UART_RTS_WHEN_TX_NOT_EMPTY 0x800
Definition at line 76 of file serial.c.
#define UART_RX_DISABLED 0x0000
Definition at line 127 of file serial.c.
#define UART_RX_ENABLED 0x1000
Definition at line 126 of file serial.c.
#define UART_RX_TX_ENABLED 0x1400
Definition at line 135 of file serial.c.
Referenced by BT_init(), open(), serial1init(), serial2init(), serial3init(), serial4init(), serial5init(), and serial6init().
#define UART_STOP_BITS_1 0x00
Definition at line 109 of file serial.c.
#define UART_STOP_BITS_2 0x01
Definition at line 108 of file serial.c.
#define UART_SUPPORT_IEEE_485 0x00000900
Definition at line 145 of file serial.c.
#define UART_TRANSMITTER_EMPTY 0x00000100
Definition at line 149 of file serial.c.
#define UART_TRANSMITTER_NOT_FULL 0x00000200
Definition at line 148 of file serial.c.
#define UART_TX_DISABLED 0x000
Definition at line 133 of file serial.c.
#define UART_TX_ENABLED 0x400
Definition at line 132 of file serial.c.
Function Documentation
BOOL ClearRxError (u8 port)
Definition at line 1368 of file serial.c.
References FALSE, TRUE, UART1, and UART2.
Referenced by serial1clearrxerror(), serial2clearrxerror(), serial3clearrxerror(), serial4clearrxerror(), serial5clearrxerror(), and serial6clearrxerror().
{
    switch (port)
    {
        case UART1:
    if (U1STAbits.OERR != 0)
     {
      U1STAbits.OERR = 0;
      return(FALSE);
     }
    break;
        case UART2:
    if (U2STAbits.OERR != 0)
     {
      U2STAbits.OERR = 0;
      return(FALSE);
     }
        break;
#ifdef ENABLE_UART3
        case UART3:
    if (U3STAbits.OERR != 0)
     {
      U3STAbits.OERR = 0;
      return(FALSE);
     }
        break;
#endif
#ifdef ENABLE_UART4
        case UART4:
    if (U4STAbits.OERR != 0)
     {
      U4STAbits.OERR = 0;
      return(FALSE);
     }
        break;
#endif
#ifdef ENABLE_UART5
        case UART5:
    if (U5STAbits.OERR != 0)
     {
      U5STAbits.OERR = 0;
      return(FALSE);
     }
        break;
#endif
#ifdef ENABLE_UART6
        case UART6:
    if (U6STAbits.OERR != 0)
     {
      U6STAbits.OERR = 0;
      return(FALSE);
     }
        break;
#endif
    }
 return(TRUE);
}
void Serial1Interrupt (void)
Definition at line 1121 of file serial.c.
References INT_UART1_ERROR, INT_UART1_RECEIVER, INT_UART1_TRANSMITTER, IntClearFlag(), IntGetFlag(), SerialGetDataBuffer(), and UART1.
{
    char Dummy;
    // Is this an RX interrupt from UART1 ?
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    if (IFS1bits.U1RXIF)
    #else
    if (IntGetFlag(INT_UART1_RECEIVER))
    #endif
    {
   if (U1STAbits.OERR != 0)
    U1STAbits.OERR = 0;
   else
         do
     {
      if ((U1STAbits.FERR != 0) || (U1STAbits.PERR != 0))
       Dummy = U1RXREG;
      else
       SerialGetDataBuffer(UART1);
     }
    while (U1STAbits.URXDA != 0);
        #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        IFS1bits.U1RXIF=0;
        #else
        IntClearFlag(INT_UART1_RECEIVER);
        #endif
    }
    // Is this an TX interrupt from UART1 ?
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    if (IFS1bits.U1TXIF)
    #else
    if (IntGetFlag(INT_UART1_TRANSMITTER))
    #endif
    {
        #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        IFS1bits.U1TXIF=0;
        #else
        IntClearFlag(INT_UART1_TRANSMITTER);
        #endif
    }
    // Is this an ERROR interrupt from UART1 ?
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    if (IFS1bits.U1EIF)
    #else
    if (IntGetFlag(INT_UART1_ERROR))
    #endif
    {
        #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        IFS1bits.U1EIF=0;
        #else
        IntClearFlag(INT_UART1_ERROR);
        #endif
    }
}
void Serial2Interrupt (void)
Definition at line 1181 of file serial.c.
References INT_UART2_ERROR, INT_UART2_RECEIVER, INT_UART2_TRANSMITTER, IntClearFlag(), IntGetFlag(), SerialGetDataBuffer(), and UART2.
{
    char Dummy;
    // Is this an RX interrupt from UART2 ?
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    if (IFS1bits.U2RXIF)
    #else
    if (IntGetFlag(INT_UART2_RECEIVER))
    #endif
    {
   if (U2STAbits.OERR != 0)
    U2STAbits.OERR = 0;
   else
         do
     {
      if ((U2STAbits.FERR != 0) || (U2STAbits.PERR != 0))
       Dummy = U2RXREG;
      else
       SerialGetDataBuffer(UART2);
     }
    while (U2STAbits.URXDA != 0);
        //Toggle(REDLED); // Toggle LED to indicate UART activity
        #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        IFS1bits.U2RXIF=0;
        #else
        IntClearFlag(INT_UART2_RECEIVER);
        #endif
    }
    // Is this an TX interrupt from UART2 ?
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    if (IFS1bits.U2TXIF)
    #else
    if (IntGetFlag(INT_UART2_TRANSMITTER))
    #endif
    {
        #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        IFS1bits.U2TXIF=0;
        #else
        IntClearFlag(INT_UART2_TRANSMITTER);
        #endif
    }
    // Is this an ERROR interrupt from UART2 ?
    #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
    if (IFS1bits.U2EIF)
    #else
    if (IntGetFlag(INT_UART2_ERROR))
    #endif
    {
        #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
        IFS1bits.U2EIF=0;
        #else
        IntClearFlag(INT_UART2_ERROR);
        #endif
    }
}
char SerialAvailable (u8 port)
Definition at line 884 of file serial.c.
References UART1, UART1rpointer, UART1wpointer, UART2, UART2rpointer, and UART2wpointer.
Referenced by BT_getBuffer(), serial1available(), serial2available(), serial3available(), serial4available(), serial5available(), serial6available(), SerialGetKey(), and SerialRead().
{
    switch (port)
    {
        case UART1: return (UART1wpointer != UART1rpointer); break;
        case UART2: return (UART2wpointer != UART2rpointer); break;
        #ifdef ENABLE_UART3
        case UART3: return (UART3wpointer != UART3rpointer); break;
        #endif
        #ifdef ENABLE_UART4
        case UART4: return (UART4wpointer != UART4rpointer); break;
        #endif
        #ifdef ENABLE_UART5
        case UART5: return (UART5wpointer != UART5rpointer); break;
        #endif
        #ifdef ENABLE_UART6
        case UART6: return (UART6wpointer != UART6rpointer); break;
        #endif
    }
}
void SerialConfigure (u8 port, u32 config, u32 enable, u32 baudrate)
Definition at line 598 of file serial.c.
References INT_PRIORITY_3, INT_SUBPRIORITY_3, SerialEnable(), SerialFlush(), SerialIntConfigure(), SerialPinConfigure(), SerialSetDataRate(), and SerialSetLineControl().
Referenced by BT_init(), open(), serial1init(), serial2init(), serial3init(), serial4init(), serial5init(), and serial6init().
{
    SerialPinConfigure(port);
    SerialSetDataRate(port, baudrate); // UxBRG
    SerialSetLineControl(port, config); // UxMODE
    SerialEnable(port, enable); // UxSTA
    SerialIntConfigure(port, INT_PRIORITY_3,
      INT_SUBPRIORITY_3);
    SerialFlush(port);
}
void SerialEnable (u8 port, u32 config)
Definition at line 368 of file serial.c.
References UART1, and UART2.
Referenced by SerialConfigure().
{
    switch (port)
    {
        case UART1: U1STASET = config; break;
        case UART2: U2STASET = config; break;
#ifdef ENABLE_UART3
        case UART3: U2ASTASET = config; break;
#endif
#ifdef ENABLE_UART4
        case UART4: U1BSTASET = config; break;
#endif
#ifdef ENABLE_UART5
        case UART5: U3BSTASET = config; break;
#endif
#ifdef ENABLE_UART6
        case UART6: U2BSTASET = config; break;
#endif
    }
}
void SerialFlush (u8 port)
Definition at line 420 of file serial.c.
References UART1, UART1rpointer, UART1wpointer, UART2, UART2rpointer, and UART2wpointer.
Referenced by BT_sendCommand(), serial1flush(), serial2flush(), serial3flush(), serial4flush(), serial5flush(), serial6flush(), SerialConfigure(), and SerialGetKey().
{
    switch (port)
    {
        case UART1:
            UART1wpointer = 1;
            UART1rpointer = 1;
            break;
        case UART2:
            UART2wpointer = 1;
            UART2rpointer = 1;
            break;
        #ifdef ENABLE_UART3
        case UART3:
            UART3wpointer = 1;
            UART3rpointer = 1;
            break;
        #endif
        #ifdef ENABLE_UART4
        case UART4:
            UART4wpointer = 1;
            UART4rpointer = 1;
            break;
        #endif
        #ifdef ENABLE_UART5
        case UART5:
            UART5wpointer = 1;
            UART5rpointer = 1;
            break;
        #endif
        #ifdef ENABLE_UART6
        case UART6:
            UART6wpointer = 1;
            UART6rpointer = 1;
            break;
        #endif
    }
}
void SerialGetDataBuffer (u8 port)
Definition at line 1005 of file serial.c.
References SERIAL_BUFFERLENGTH, UART1, UART1rpointer, UART1SerialBuffer, UART1wpointer, UART2, UART2rpointer, UART2SerialBuffer, and UART2wpointer.
Referenced by Serial1Interrupt(), and Serial2Interrupt().
{
    unsigned char caractere;
    long newwp;
    switch (port)
    {
        case UART1:
            caractere = U1RXREG; // read received char
            if (UART1wpointer != SERIAL_BUFFERLENGTH - 1) // if not last
       place in buffer
                newwp = UART1wpointer + 1; // place=place+1
            else
                newwp = 1; // else place=1
            if (UART1rpointer != newwp) // if read pointer!=write
       pointer
                UART1SerialBuffer[UART1wpointer++] = caractere; // store
       received char
            if (UART1wpointer == SERIAL_BUFFERLENGTH) // if write
       pointer=length buffer
                UART1wpointer = 1; // write pointer = 1
            //return UART1SerialBuffer;
            break;
        case UART2:
            caractere = U2RXREG; // read received char
            if (UART2wpointer != SERIAL_BUFFERLENGTH - 1) // if not last
       place in buffer
                newwp = UART2wpointer + 1; // place=place+1
            else
                newwp = 1; // else place=1
            if (UART2rpointer != newwp) // if read pointer!=write
       pointer
                UART2SerialBuffer[UART2wpointer++] = caractere; // store
       received char
            if (UART2wpointer == SERIAL_BUFFERLENGTH) // if write
       pointer=length buffer
                UART2wpointer = 1; // write pointer = 1
            //return UART2SerialBuffer;
            break;
        #ifdef ENABLE_UART3
        case UART3:
            caractere = U2ARXREG; // read received char
            if (UART3wpointer != SERIAL_BUFFERLENGTH - 1) // if not last place in
       buffer
                newwp = UART3wpointer + 1; // place=place+1
            else
                newwp = 1; // else place=1
            if (UART3rpointer != newwp) // if read pointer!=write pointer
                UART3SerialBuffer[UART3wpointer++] = caractere; // store received char
            if (UART3wpointer == SERIAL_BUFFERLENGTH) // if write pointer=length
       buffer
                UART3wpointer = 1; // write pointer = 1
            //return UART3SerialBuffer;
            break;
        #endif
        #ifdef ENABLE_UART4
        case UART4:
            caractere = U1BRXREG; // read received char
            if (UART4wpointer != SERIAL_BUFFERLENGTH - 1) // if not last place in
       buffer
                newwp = UART4wpointer + 1; // place=place+1
            else
                newwp = 1; // else place=1
            if (UART4rpointer != newwp) // if read pointer!=write pointer
                UART4SerialBuffer[UART4wpointer++] = caractere; // store received char
            if (UART4wpointer == SERIAL_BUFFERLENGTH) // if write pointer=length
       buffer
                UART4wpointer = 1; // write pointer = 1
            //return UART4SerialBuffer;
            break;
        #endif
        #ifdef ENABLE_UART5
        case UART5:
            caractere = U3BRXREG; // read received char
            if (UART5wpointer != SERIAL_BUFFERLENGTH - 1) // if not last place in
       buffer
                newwp = UART5wpointer + 1; // place=place+1
            else
                newwp = 1; // else place=1
            if (UART5rpointer != newwp) // if read pointer!=write pointer
                UART5SerialBuffer[UART5wpointer++] = caractere; // store received char
            if (UART5wpointer == SERIAL_BUFFERLENGTH) // if write pointer=length
       buffer
                UART5wpointer = 1; // write pointer = 1
            //return UART5SerialBuffer;
            break;
        #endif
        #ifdef ENABLE_UART6
        case UART6:
            caractere = U2BRXREG; // read received char
            if (UART6wpointer != SERIAL_BUFFERLENGTH - 1) // if not last place in
       buffer
                newwp = UART6wpointer + 1; // place=place+1
            else
                newwp = 1; // else place=1
            if (UART6rpointer != newwp) // if read pointer!=write pointer
                UART6SerialBuffer[UART6wpointer++] = caractere; // store received char
            if (UART6wpointer == SERIAL_BUFFERLENGTH) // if write pointer=length
       buffer
                UART6wpointer = 1; // write pointer = 1
            //return UART3SerialBuffer;
            break;
        #endif
    }
}
u32 SerialGetDataRate (u8 port)
Definition at line 294 of file serial.c.
References GetPeripheralClock(), UART1, UART2, and UART_ENABLE_HIGH_SPEED.
{
    u8 speed;
    u32 baudrate;
    u32 pbclock;
    pbclock = GetPeripheralClock();
    switch (port)
    {
        case UART1:
            speed = U1MODEbits.BRGH;
            if (speed == UART_ENABLE_HIGH_SPEED)
                baudrate = pbclock / (4 * (U1BRG + 1));
            else
                baudrate = pbclock / (16 * (U1BRG + 1));
            break;
        case UART2:
            speed = U2MODEbits.BRGH;
            if (speed == UART_ENABLE_HIGH_SPEED)
                baudrate = pbclock / (4 * (U2BRG + 1));
            else
                baudrate = pbclock / (16 * (U2BRG + 1));
            break;
#ifdef ENABLE_UART3
        case UART3:
            speed = U2AMODEbits.BRGH;
            if (speed == UART_ENABLE_HIGH_SPEED)
                baudrate = pbclock / (4 * (U2ABRG + 1));
            else
                baudrate = pbclock / (16 * (U2ABRG + 1));
            break;
#endif
#ifdef ENABLE_UART4
        case UART4:
            speed = U1BMODEbits.BRGH;
            if (speed == UART_ENABLE_HIGH_SPEED)
                baudrate = pbclock / (4 * (U1BBRG + 1));
            else
                baudrate = pbclock / (16 * (U1BBRG + 1));
            break;
#endif
#ifdef ENABLE_UART5
        case UART5:
            speed = U3BMODEbits.BRGH;
            if (speed == UART_ENABLE_HIGH_SPEED)
                baudrate = pbclock / (4 * (U3BBRG + 1));
            else
                baudrate = pbclock / (16 * (U3BBRG + 1));
            break;
#endif
#ifdef ENABLE_UART6
        case UART6:
            speed = U2BMODEbits.BRGH;
            if (speed == UART_ENABLE_HIGH_SPEED)
                baudrate = pbclock / (4 * (U2BBRG + 1));
            else
                baudrate = pbclock / (16 * (U2BBRG + 1));
            break;
#endif
        default:
            baudrate = 0;
    }
    return baudrate;
}
char SerialGetKey (u8 port)
Definition at line 970 of file serial.c.
References c, SerialAvailable(), SerialFlush(), and SerialRead().
Referenced by serial1getkey(), serial2getkey(), serial3getkey(), serial4getkey(), serial5getkey(), serial6getkey(), and SerialGetString().
{
    char c;
    while (!(SerialAvailable(port)));
    c = SerialRead(port);
    SerialFlush(port);
    return (c);
}
char* SerialGetString (u8 port)
Definition at line 985 of file serial.c.
References c, and SerialGetKey().
Referenced by serial1getstring(), serial2getstring(), serial3getstring(), serial4getstring(), serial5getstring(), and serial6getstring().
{
    u8 i = 0;
    char c;
    static char buffer[80];
    
    do {
        c = SerialGetKey(port);
        SerialPrintf(port, "%c", c);
        buffer[i++] = c;
    } while (c != '\r');
    buffer[i] = '\0';
    return (buffer);
}
void SerialIntConfigure (u8 port, u8 priority, u8 subpriority)
Definition at line 537 of file serial.c.
References INT_SYSTEM_CONFIG_MULT_VECTOR, INT_UART1_RECEIVER, INT_UART1_VECTOR, INT_UART2_RECEIVER, INT_UART2_VECTOR, IntConfigureSystem(), IntEnable(), IntSetVectorPriority(), UART1, and UART2.
Referenced by SerialConfigure().
{
    IntConfigureSystem(INT_SYSTEM_CONFIG_MULT_VECTOR);
    
    switch (port)
    {
        case UART1:
            #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
                IPC8bits.U1IP = priority;
                IPC8bits.U1IS = subpriority;
                IEC1bits.U1RXIE=1;
            #else
            IntSetVectorPriority(INT_UART1_VECTOR, priority,
      subpriority);
            IntEnable(INT_UART1_RECEIVER);
            #endif
            break;
        case UART2:
            #if defined(PIC32_PINGUINO_220)||defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
                IPC9bits.U2IP = priority;
                IPC9bits.U2IS = subpriority;
                IEC1bits.U2RXIE=1;
            #else
            IntSetVectorPriority(INT_UART2_VECTOR, priority,
      subpriority);
            IntEnable(INT_UART2_RECEIVER);
            #endif
            break;
        #ifdef ENABLE_UART3
        case UART3:
            IntSetVectorPriority(INT_UART3_VECTOR, priority, subpriority);
            IntEnable(INT_UART3_RECEIVER);
            break;
        #endif
        #ifdef ENABLE_UART4
        case UART4:
            IntSetVectorPriority(INT_UART4_VECTOR, priority, subpriority);
            IntEnable(INT_UART4_RECEIVER);
            break;
        #endif
        #ifdef ENABLE_UART5
        case UART5:
            IntSetVectorPriority(INT_UART5_VECTOR, priority, subpriority);
            IntEnable(INT_UART5_RECEIVER);
            break;
        #endif
        #ifdef ENABLE_UART6
        case UART6:
            IntSetVectorPriority(INT_UART6_VECTOR, priority, subpriority);
            IntEnable(INT_UART6_RECEIVER);
            break;
        #endif
    }
}
void SerialPinConfigure (u8 port)
Definition at line 463 of file serial.c.
References INPUT, OUTPUT, UART1, and UART2.
Referenced by SerialConfigure().
{
    switch (port)
    {
        case UART1:
        #ifdef __32MX460F512L__
            TRISFbits.TRISF8 = OUTPUT; // RF8 / U1TX output
            TRISFbits.TRISF2 = INPUT; // RF2 / U1RX input
        #endif
        #ifdef __32MX440F256H__
            TRISDbits.TRISD3 = OUTPUT; // RD3 / U1TX output
            TRISDbits.TRISD2 = INPUT; // RD2 / U1RX input
        #endif
        #ifdef PIC32_PINGUINO_220
            TRISBbits.TRISB4 = OUTPUT; // RB4 / U1TX output
            TRISAbits.TRISA4 = INPUT; // RA4 / U1RX input
        #endif
        #if defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
            TRISBbits.TRISB2=INPUT; // RB2 is input (RX)
            TRISBbits.TRISB3=OUTPUT; // RB3 is output (TX)
        #endif
            break;
        case UART2:
        #ifdef PIC32_PINGUINO_220
            TRISCbits.TRISC9 = OUTPUT; // RC9 / U2TX output
            TRISCbits.TRISC8 = INPUT; // RC8 / U2RX input
        #else
            #if defined(PINGUINO32MX250)||defined(PINGUINO32MX220)
            TRISBbits.TRISB1=INPUT; // RB1 is input (RX)
            TRISBbits.TRISB0=OUTPUT; // RB0 is output (TX)
            #else
            TRISFbits.TRISF5 = OUTPUT; // RF5 / U2TX output
            TRISFbits.TRISF4 = INPUT; // RF4 / U2RX input
            #endif
        #endif
            break;
        //32MX4xx not have UART3,4,5 AND 6
        #ifdef ENABLE_UART3
        case UART3:
            TRISGbits.TRISG8 = OUTPUT; // RG8 / U3TX output
            TRISGbits.TRISG7 = INPUT; // RG7 / U3RX input
            break;
        #endif
        #ifdef ENABLE_UART4
        case UART4:
            TRISDbits.TRISD15 = OUTPUT; // RD15 / U4TX output
            TRISDbits.TRISD14 = INPUT; // RD14 / U4RX input
            break;
        #endif
        #ifdef ENABLE_UART5
            #ifndef __32MX220F032D__
            case UART5:
                TRISFbits.TRISF13 = OUTPUT; // RF13 / U5TX output
                TRISFbits.TRISF12 = INPUT; // RF12 / U5RX input
                break;
            #endif
        #endif
        #ifdef ENABLE_UART6
        case UART6:
            TRISGbits.TRISG6 = OUTPUT; // RG6 / U6TX output
            TRISGbits.TRISG9 = INPUT; // RG9 / U6RX input
            break;
        #endif
    }
}
void SerialPutChar (u8 port, char c)
Definition at line 676 of file serial.c.
References SerialUART1WriteChar(), SerialUART2WriteChar(), UART1, and UART2.
{
    switch (port)
    {
        case UART1:
            SerialUART1WriteChar(c);
            break;
        case UART2:
            SerialUART2WriteChar(c);
            break;
        #ifdef ENABLE_UART3
        case UART3:
            SerialUART3WriteChar(c);
            break;
        #endif
        #ifdef ENABLE_UART4
        case UART4:
            SerialUART4WriteChar(c);
            break;
        #endif
        #ifdef ENABLE_UART5
        case UART5:
            SerialUART5WriteChar(c);
            break;
        #endif
        #ifdef ENABLE_UART6
        case UART6:
            SerialUART6WriteChar(c);
            break;
        #endif
    }
}
int SerialRead (u8 port)
Definition at line 909 of file serial.c.
References SERIAL_BUFFERLENGTH, SerialAvailable(), UART1, UART1rpointer, UART1SerialBuffer, UART2, UART2rpointer, and UART2SerialBuffer.
Referenced by BT_getBuffer(), BT_ok(), read(), serial1read(), serial2read(), serial3read(), serial4read(), serial5read(), serial6read(), and SerialGetKey().
{
    int c = 0;
    if (SerialAvailable(port))
    {
        switch (port)
        {
            case UART1:
                c = UART1SerialBuffer[UART1rpointer++];
                if (UART1rpointer == SERIAL_BUFFERLENGTH)
                    UART1rpointer=1;
                return(c);
                break;
            case UART2:
                c = UART2SerialBuffer[UART2rpointer++];
                if (UART2rpointer == SERIAL_BUFFERLENGTH)
                    UART2rpointer=1;
                return(c);
                break;
        #ifdef ENABLE_UART3
            case UART3:
                c = UART3SerialBuffer[UART3rpointer++];
                if (UART3rpointer == SERIAL_BUFFERLENGTH)
                    UART3rpointer=1;
                return(c);
                break;
        #endif
        #ifdef ENABLE_UART4
            case UART4:
                c = UART4SerialBuffer[UART4rpointer++];
                if (UART4rpointer == SERIAL_BUFFERLENGTH)
                    UART4rpointer=1;
                return(c);
                break;
        #endif
        #ifdef ENABLE_UART5
            case UART5:
                c = UART5SerialBuffer[UART5rpointer++];
                if (UART5rpointer == SERIAL_BUFFERLENGTH)
                    UART5rpointer=1;
                return(c);
                break;
        #endif
        #ifdef ENABLE_UART6
            case UART6:
                c = UART6SerialBuffer[UART6rpointer++];
                if (UART6rpointer == SERIAL_BUFFERLENGTH)
                    UART6rpointer=1;
                return(c);
                break;
        #endif
        }
    }
    return(-1);
}
void SerialSetDataRate (u8 port, u32 baudrate)
Definition at line 203 of file serial.c.
References GetPeripheralClock(), max, UART1, UART2, and UART_ENABLE_HIGH_SPEED.
Referenced by SerialConfigure().
{
    u8 speed;
    u32 max, max1, max2;
    u32 min1, min2;
    u32 pbclock;
    pbclock = GetPeripheralClock();
    max1 = pbclock / 4;
    min1 = max1 / 65536;
    max2 = pbclock / 16;
    min2 = max2 / 65536;
    if (baudrate > max1) baudrate = max1;
    if (baudrate < min2) baudrate = min2;
    max = (min1 + max2) / 2;
    //if (baudrate > min2 && baudrate < max) speed = UART_ENABLE_STANDARD_SPEED;
    if (baudrate > max && baudrate < max1) speed = UART_ENABLE_HIGH_SPEED;
    switch (port)
    {
        case UART1:
            if (speed == UART_ENABLE_HIGH_SPEED)
            {
                U1MODEbits.BRGH = UART_ENABLE_HIGH_SPEED;
                U1BRG = ((pbclock / baudrate) / 4) - 1;
            }
            else
                U1BRG = ((pbclock / baudrate) / 16) - 1;
            break;
        case UART2:
            if (speed == UART_ENABLE_HIGH_SPEED)
            {
                U2MODEbits.BRGH = UART_ENABLE_HIGH_SPEED;
                U2BRG = ((pbclock / baudrate) / 4) - 1;
            }
            else
                U2BRG = ((pbclock / baudrate) / 16) - 1;
            break;
#ifdef ENABLE_UART3
        case UART3:
            if (speed == UART_ENABLE_HIGH_SPEED)
            {
                U2AMODEbits.BRGH = UART_ENABLE_HIGH_SPEED;
                U2ABRG = ((pbclock / baudrate) / 4) - 1;
            }
            else
                U2ABRG = ((pbclock / baudrate) / 16) - 1;
            break;
#endif
#ifdef ENABLE_UART4
        case UART4:
            if (speed == UART_ENABLE_HIGH_SPEED)
            {
                U1BMODEbits.BRGH = UART_ENABLE_HIGH_SPEED;
                U1BBRG = ((pbclock / baudrate) / 4) - 1;
            }
            else
                U1BBRG = ((pbclock / baudrate) / 16) - 1;
            break;
#endif
#ifdef ENABLE_UART5
        case UART5:
            if (speed == UART_ENABLE_HIGH_SPEED)
            {
                U3BMODEbits.BRGH = UART_ENABLE_HIGH_SPEED;
                U3BBRG = ((pbclock / baudrate) / 4) - 1;
            }
            else
                U3BBRG = ((pbclock / baudrate) / 16) - 1;
            break;
#endif
#ifdef ENABLE_UART6
        case UART6:
            if (speed == UART_ENABLE_HIGH_SPEED)
            {
                U2BMODEbits.BRGH = UART_ENABLE_HIGH_SPEED;
                U2BBRG = ((pbclock / baudrate) / 4) - 1;
            }
            else
                U2BBRG = ((pbclock / baudrate) / 16) - 1;
            break;
#endif
    }
}
void SerialSetLineControl (u8 port, u32 config)
Definition at line 395 of file serial.c.
References UART1, and UART2.
Referenced by SerialConfigure().
{
    switch (port)
    {
        case UART1: U1MODESET = config; break;
        case UART2: U2MODESET = config; break;
#ifdef ENABLE_UART3
        case UART3: U2AMODESET = config; break;
#endif
#ifdef ENABLE_UART4
        case UART4: U1BMODESET = config; break;
#endif
#ifdef ENABLE_UART5
        case UART5: U3BMODESET = config; break;
#endif
#ifdef ENABLE_UART6
        case UART6: U2BMODESET = config; break;
#endif
    }
}
void SerialUART1WriteChar (char c)
Definition at line 612 of file serial.c.
References c.
Referenced by serial1write(), serial2printf(), serial2write(), SerialPutChar(), and write().
{
    while (!U1STAbits.TRMT); // wait transmitter is ready
    U1TXREG = c;
}
void SerialUART2WriteChar (char c)
Definition at line 622 of file serial.c.
References c.
Referenced by serial1write(), serial2printf(), serial2write(), SerialPutChar(), and write().
{
    while (!U2STAbits.TRMT); // wait transmission has completed
    U2TXREG = c;
}
Variable Documentation
volatile long UART1rpointer
Definition at line 175 of file serial.c.
Referenced by SerialAvailable(), SerialFlush(), SerialGetDataBuffer(), and SerialRead().
volatile unsigned char UART1SerialBuffer[SERIAL_BUFFERLENGTH]
Definition at line 160 of file serial.c.
Referenced by SerialGetDataBuffer(), and SerialRead().
volatile long UART1wpointer
Definition at line 175 of file serial.c.
Referenced by SerialAvailable(), SerialFlush(), and SerialGetDataBuffer().
volatile long UART2rpointer
Definition at line 176 of file serial.c.
Referenced by SerialAvailable(), SerialFlush(), SerialGetDataBuffer(), and SerialRead().
volatile unsigned char UART2SerialBuffer[SERIAL_BUFFERLENGTH]
Definition at line 161 of file serial.c.
Referenced by SerialGetDataBuffer(), and SerialRead().
volatile long UART2wpointer
Definition at line 176 of file serial.c.
Referenced by SerialAvailable(), SerialFlush(), and SerialGetDataBuffer().