/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/i2c.c File Reference
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <system.c>
*
#include <interrupt.c>
*
Macros
#define __I2C_C
#define I2C_WRITE 0
#define I2C_READ 1
#define I2C_MASTER_MODE 0
#define I2C_SLAVE_MODE 1
#define I2C_MULTIMASTER_MODE 2
#define I2C_SLEW_OFF 0
#define I2C_SLEW_ON 1
#define I2C_100KHZ 0
#define I2C_400KHZ 1
#define I2C_1MHZ 2
#define I2C_TIMEOUT 4000
#define I2C1 1
#define I2C2 2
Functions
void I2C_init (u8, u8, u8)
PROTOTYPES.
u8 I2C_send (u8, u8, u8)
u8 I2C_get (u8, u16)
void I2C_sendID (u8, u16, u8)
u8 I2C_writechar (u8, u8)
u8 I2C_readchar (u8, u8)
void I2C_wait (u8)
void I2C_start (u8)
void I2C_stop (u8)
void I2C_restart (u8)
void I2C_sendNack (u8)
void I2C_sendAck (u8)
Macro Definition Documentation
#define __I2C_C
Definition at line 37 of file i2c.c.
#define I2C1 1
Definition at line 61 of file i2c.c.
Referenced by I2C_init(), I2C_readchar(), I2C_restart(), I2C_sendAck(), I2C_sendID(), I2C_sendNack(), I2C_start(), I2C_stop(), I2C_wait(), and I2C_writechar().
#define I2C2 2
Definition at line 62 of file i2c.c.
Referenced by I2C_init(), I2C_readchar(), I2C_restart(), I2C_sendAck(), I2C_sendID(), I2C_sendNack(), I2C_start(), I2C_stop(), I2C_wait(), and I2C_writechar().
#define I2C_100KHZ 0
Definition at line 55 of file i2c.c.
Referenced by I2C_init().
#define I2C_1MHZ 2
Definition at line 57 of file i2c.c.
Referenced by I2C_init().
#define I2C_400KHZ 1
Definition at line 56 of file i2c.c.
Referenced by I2C_init().
#define I2C_MASTER_MODE 0
Definition at line 48 of file i2c.c.
Referenced by I2C_init().
#define I2C_MULTIMASTER_MODE 2
Definition at line 50 of file i2c.c.
Referenced by I2C_init().
#define I2C_READ 1
Definition at line 47 of file i2c.c.
Referenced by I2C_get().
#define I2C_SLAVE_MODE 1
Definition at line 49 of file i2c.c.
Referenced by I2C_init().
#define I2C_SLEW_OFF 0
Definition at line 51 of file i2c.c.
#define I2C_SLEW_ON 1
Definition at line 52 of file i2c.c.
#define I2C_TIMEOUT 4000
Definition at line 58 of file i2c.c.
#define I2C_WRITE 0
Definition at line 46 of file i2c.c.
Referenced by I2C_send().
Function Documentation
u8 I2C_get (u8 module, u16 adress)
Definition at line 233 of file i2c.c.
References I2C_READ, I2C_readchar(), I2C_restart(), I2C_sendID(), I2C_sendNack(), I2C_stop(), and I2C_writechar().
Referenced by I2C1_get(), I2C2_get(), and PCF8574_read().
void I2C_init (u8 module, u8 mode, u8 speed)
PROTOTYPES.
Definition at line 90 of file i2c.c.
References GetPeripheralClock(), I2C1, I2C2, I2C_100KHZ, I2C_1MHZ, I2C_400KHZ, I2C_MASTER_MODE, I2C_MULTIMASTER_MODE, and I2C_SLAVE_MODE.
u8 I2C_readchar (u8 module, u8 last)
Definition at line 368 of file i2c.c.
References I2C1, I2C2, and I2C_wait().
Referenced by I2C1_readchar(), I2C1_readcharAck(), I2C2_readchar(), I2C2_readcharAck(), and I2C_get().
void I2C_restart (u8 module)
Definition at line 501 of file i2c.c.
References I2C1, I2C2, and I2C_wait().
u8 I2C_send (u8 module, u8 address, u8 value)
Definition at line 209 of file i2c.c.
References I2C_start(), I2C_stop(), I2C_WRITE, and I2C_writechar().
Referenced by I2C1_send(), I2C2_send(), lcdi2c_backlight(), and lcdi2c_noBacklight().
void I2C_sendAck (u8 module)
Definition at line 558 of file i2c.c.
References I2C1, I2C2, and I2C_wait().
void I2C_sendID (u8 module, u16 DeviceID, u8 rw)
Definition at line 265 of file i2c.c.
References I2C1, I2C2, I2C_restart(), I2C_start(), and I2C_writechar().
Referenced by I2C1_sendID(), I2C2_sendID(), and I2C_get().
void I2C_sendNack (u8 module)
Definition at line 534 of file i2c.c.
References I2C1, I2C2, and I2C_wait().
void I2C_start (u8 module)
Definition at line 443 of file i2c.c.
References I2C1, I2C2, and I2C_wait().
void I2C_stop (u8 module)
Definition at line 472 of file i2c.c.
References I2C1, I2C2, and I2C_wait().
void I2C_wait (u8 module)
Definition at line 415 of file i2c.c.
References I2C1, and I2C2.
u8 I2C_writechar (u8 module, u8 value)
Definition at line 323 of file i2c.c.
References I2C1, I2C2, and I2C_wait().
Referenced by I2C1_writechar(), I2C2_writechar(), I2C_get(), I2C_send(), I2C_sendID(), and PCF8574_write().