/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/libraries/PCD8544.h File Reference
#include <typedef.h>
*
#include <macro.h>
*
#include <logo/pinguino84x48.h>
*
Data Structures
struct coord_t
struct font_t
struct color_t
struct rect_t
union word_t
struct lcd_t
Macros
#define PCD8544_SPIHW 1<<0
#define PCD8544_SPISW 1<<1
#define PCD8544_PORTB 1<<2
#define PCD8544_INTERFACE PCD8544_SPISW
#define DISPLAY_WIDTH 84
#define DISPLAY_HEIGHT 48
#define DISPLAY_SIZE (DISPLAY_WIDTH * DISPLAY_HEIGHT / 8)
#define DISPLAY_ROWS ((DISPLAY_HEIGHT / 8) - 1)
#define PCD8544_POWERDOWN 0x04
#define PCD8544_ENTRYMODE 0x02
#define PCD8544_EXTENDEDINSTRUCTION 0x01
#define PCD8544_DISPLAYBLANK 0x0
#define PCD8544_DISPLAYNORMAL 0x4
#define PCD8544_DISPLAYALLON 0x1
#define PCD8544_DISPLAYINVERTED 0x5
#define PCD8544_FUNCTIONSET 0x20
#define PCD8544_DISPLAYCONTROL 0x08
#define PCD8544_SETYADDR 0x40
#define PCD8544_SETXADDR 0x80
#define PCD8544_SETTEMP 0x04
#define PCD8544_SETBIAS 0x10
#define PCD8544_SETVOP 0x80
#define BLACK 1
#define WHITE 0
#define PORTRAIT 1
#define LANDSCAPE 0
#define PCD8544_getFontWidth() (PCD8544.font.width)
#define PCD8544_getFontHeight() (PCD8544.font.height)
Functions
void PCD8544_init (u8 SCLK, u8 DIN, u8 DC, u8 CS, u8 RST)
void PCD8544_command (u8 c)
void PCD8544_data (u8 c)
void PCD8544_setContrast (u8 val)
void PCD8544_clearScreen ()
void PCD8544_refresh ()
void PCD8544_drawPixel (u8 x, u8 y)
void PCD8544_clearPixel (u8 x, u8 y)
u8 PCD8544_getPixel (u8 x, u8 y)
void PCD8544_setCursor (u8 x, u8 y)
void PCD8544_shiftOut (u8 c)
void PCD8544_printChar (u8 c)
void PCD8544_print (u8 *string)
void PCD8544_println (u8 *string)
void PCD8544_printf (const u8 *fmt,...)
void PCD8544_printNumber (long value, u8 base)
void PCD8544_printFloat (float number, u8 digits)
Variables
lcd_t PCD8544
u8 * PCD8544_buffer = logo
Macro Definition Documentation
#define BLACK 1
Definition at line 108 of file PCD8544.h.
#define DISPLAY_HEIGHT 48
Definition at line 79 of file PCD8544.h.
#define DISPLAY_ROWS ((DISPLAY_HEIGHT / 8) - 1)
Definition at line 81 of file PCD8544.h.
#define DISPLAY_SIZE (DISPLAY_WIDTH * DISPLAY_HEIGHT / 8)
Definition at line 80 of file PCD8544.h.
#define DISPLAY_WIDTH 84
Display sizes
Definition at line 78 of file PCD8544.h.
#define LANDSCAPE 0
Definition at line 113 of file PCD8544.h.
#define PCD8544_DISPLAYALLON 0x1
Definition at line 93 of file PCD8544.h.
#define PCD8544_DISPLAYBLANK 0x0
Definition at line 91 of file PCD8544.h.
#define PCD8544_DISPLAYCONTROL 0x08
Definition at line 98 of file PCD8544.h.
#define PCD8544_DISPLAYINVERTED 0x5
Definition at line 94 of file PCD8544.h.
#define PCD8544_DISPLAYNORMAL 0x4
Definition at line 92 of file PCD8544.h.
#define PCD8544_ENTRYMODE 0x02
Definition at line 88 of file PCD8544.h.
#define PCD8544_EXTENDEDINSTRUCTION 0x01
Definition at line 89 of file PCD8544.h.
#define PCD8544_FUNCTIONSET 0x20
Definition at line 97 of file PCD8544.h.
#define PCD8544_getFontHeight() (PCD8544.font.height)
Definition at line 285 of file PCD8544.h.
#define PCD8544_getFontWidth() (PCD8544.font.width)
Definition at line 284 of file PCD8544.h.
#define PCD8544_INTERFACE PCD8544_SPISW
Definition at line 60 of file PCD8544.h.
#define PCD8544_PORTB 1<<2
Definition at line 58 of file PCD8544.h.
#define PCD8544_POWERDOWN 0x04
Display commands
Definition at line 87 of file PCD8544.h.
#define PCD8544_SETBIAS 0x10
Definition at line 104 of file PCD8544.h.
#define PCD8544_SETTEMP 0x04
Definition at line 103 of file PCD8544.h.
#define PCD8544_SETVOP 0x80
Definition at line 105 of file PCD8544.h.
#define PCD8544_SETXADDR 0x80
Definition at line 100 of file PCD8544.h.
#define PCD8544_SETYADDR 0x40
Definition at line 99 of file PCD8544.h.
#define PCD8544_SPIHW 1<<0
Display interfaces
Definition at line 56 of file PCD8544.h.
#define PCD8544_SPISW 1<<1
Definition at line 57 of file PCD8544.h.
#define PORTRAIT 1
Definition at line 112 of file PCD8544.h.
#define WHITE 0
Definition at line 109 of file PCD8544.h.
Function Documentation
void PCD8544_clearPixel (u8 x, u8 y)
void PCD8544_clearScreen ()
Definition at line 369 of file PCD8544.c.
References lcd_t::cursor, DISPLAY_HEIGHT, DISPLAY_SIZE, DISPLAY_WIDTH, PCD8544, PCD8544_buffer, coord_t::x, and coord_t::y.
{
    //memset(PCD8544_buffer, 0, DISPLAY_SIZE);
    u16 i;
    for (i = 0; i < DISPLAY_SIZE; i++)
        PCD8544_buffer[i] = 0;
    #ifdef enablePartialUpdate
    PCD8544_updateBoundingBox(0, 0, DISPLAY_WIDTH-1, DISPLAY_HEIGHT-1);
    #endif
    PCD8544.cursor.y = 0;
    PCD8544.cursor.x = 0;
}
void PCD8544_command (u8 c)
Definition at line 131 of file PCD8544.c.
References lcd_t::_cs, lcd_t::_dc, DESELECT, digitalwrite(), HIGH, LOW, PCD8544, PCD8544_shiftOut(), SELECT, and SPI_write().
Referenced by PCD8544_refresh(), and PCD8544_setContrast().
{
    #if (PCD8544_INTERFACE & PCD8544_SPISW)
        #if (PCD8544_INTERFACE & PCD8544_PORTB)
            Low(PCD8544_DC);
            Low(PCD8544_SCE);
            PCD8544_shiftOut(c);
            High(PCD8544_SCE);
        #else
            // DC = LOW => COMMAND
            digitalwrite(PCD8544._dc, LOW);
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, LOW);
                
            PCD8544_shiftOut(c);
            
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, HIGH);
        #endif
    #elif (PCD8544_INTERFACE & PCD8544_SPIHW)
        // DC = LOW => COMMAND
        digitalwrite(PCD8544._dc, LOW);
        SELECT();
        SPI_write(c);
        DESELECT();
    #endif
}
void PCD8544_data (u8 c)
Definition at line 159 of file PCD8544.c.
References lcd_t::_cs, lcd_t::_dc, DESELECT, digitalwrite(), HIGH, LOW, PCD8544, PCD8544_shiftOut(), SELECT, and SPI_write().
{
    #if (PCD8544_INTERFACE & PCD8544_SPISW)
        #if (PCD8544_INTERFACE & PCD8544_PORTB)
            High(PCD8544_DC);
            Low(PCD8544_SCE);
            PCD8544_shiftOut(c);
            High(PCD8544_SCE);
        #else
            // DC = HIGH => DATA
            digitalwrite(PCD8544._dc, HIGH);
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, LOW);
                
            PCD8544_shiftOut(c);
            
            if (PCD8544._cs > 0)
                digitalwrite(PCD8544._cs, HIGH);
        #endif
    #elif (PCD8544_INTERFACE & PCD8544_SPIHW)
        // DC = HIGH => DATA
        digitalwrite(PCD8544._dc, HIGH);
        SELECT();
        SPI_write(c);
        DESELECT();
    #endif
}
void PCD8544_drawPixel (u8 x, u8 y)
u8 PCD8544_getPixel (u8 x, u8 y)
void PCD8544_init (u8 SCLK, u8 DIN, u8 DC, u8 CS, u8 RST)
Prototypes
void PCD8544_print (u8 * string)
void PCD8544_printChar (u8 c)
Definition at line 446 of file PCD8544.c.
References font_t::address, lcd_t::cursor, DISPLAY_ROWS, lcd_t::font, PCD8544, PCD8544_buffer, PCD8544_scrollUp(), lcd_t::screen, font_t::width, rect_t::width, coord_t::x, and coord_t::y.
{
    u8 b;
    while (PCD8544.cursor.x >= (PCD8544.screen.width /
      PCD8544.font.width))
    {
        PCD8544.cursor.x -= (PCD8544.screen.width /
      PCD8544.font.width);
        PCD8544.cursor.y++;
    }
    while (PCD8544.cursor.y > DISPLAY_ROWS)
    {
        PCD8544_scrollUp();
    }
    switch (c)
    {
        case '\n':
            PCD8544.cursor.y++;
            break;
            
        case '\r':
            PCD8544.cursor.x = 0;
            break;
            
        case '\t':
            PCD8544.cursor.x = (PCD8544.cursor.x + 4) % 4;
            break;
            
        default:
            for (b = 0; b < PCD8544.font.width; b++)
            {
                PCD8544_buffer[PCD8544.cursor.x *
      PCD8544.font.width + PCD8544.cursor.y * PCD8544.
      screen.width + b] =
                    PCD8544.font.address[2 + (c - 32) *
      PCD8544.font.width + b];
            }
        
        PCD8544.cursor.x++;
    }
}
void PCD8544_printf (const u8 * fmt, ...)
void PCD8544_printFloat (float number, u8 digits)
void PCD8544_println (u8 * string)
void PCD8544_printNumber (long value, u8 base)
void PCD8544_refresh ()
Definition at line 309 of file PCD8544.c.
References lcd_t::_cs, lcd_t::_dc, DESELECT, digitalwrite(), DISPLAY_HEIGHT, DISPLAY_ROWS, DISPLAY_WIDTH, HIGH, LOW, PCD8544, PCD8544_buffer, PCD8544_command(), PCD8544_SETXADDR, PCD8544_SETYADDR, PCD8544_shiftOut(), SELECT, and SPI_write().
{
    u8 col, p;
     
    #if (PCD8544_INTERFACE & PCD8544_SPISW)
        #if (PCD8544_INTERFACE & PCD8544_PORTB)
            for(p = 0; p <= DISPLAY_ROWS; p++)
            {
                col = 0;
                PCD8544_command(PCD8544_SETYADDR | p);
                PCD8544_command(PCD8544_SETXADDR | col);
                // send data in DDRAM
                High(PCD8544_DC);
                Low(PCD8544_SCE);
                for(; col < DISPLAY_WIDTH; col++)
                    PCD8544_shiftOut(PCD8544_buffer[(DISPLAY_WIDTH*p)+col]);
                High(PCD8544_SCE);
            }
        #else
            for(p = 0; p <= DISPLAY_ROWS; p++)
            {
                col = 0;
                PCD8544_command(PCD8544_SETYADDR | p);
                PCD8544_command(PCD8544_SETXADDR | col);
                // send data in DDRAM
                digitalwrite(PCD8544._dc, HIGH);
                if (PCD8544._cs > 0)
                    digitalwrite(PCD8544._cs, LOW);
                for(; col < DISPLAY_WIDTH; col++)
                    PCD8544_shiftOut(PCD8544_buffer[(DISPLAY_WIDTH*p)+col]);
                if (PCD8544._cs > 0)
                    digitalwrite(PCD8544._cs, HIGH);
            }
        #endif
    #elif (PCD8544_INTERFACE & PCD8544_SPIHW)
        for(p = 0; p <= DISPLAY_ROWS; p++)
        {
            col = 0;
            PCD8544_command(PCD8544_SETYADDR | p);
            PCD8544_command(PCD8544_SETXADDR | col);
            // send data in DDRAM
            digitalwrite(PCD8544._dc, HIGH);
            SELECT();
            for(; col < DISPLAY_WIDTH; col++)
                SPI_write(PCD8544_buffer[(DISPLAY_WIDTH*p)+col]);
            DESELECT();
        }
    #endif
    // no idea why this is necessary but it is to finish the last byte?
    PCD8544_command(PCD8544_SETYADDR);
    #ifdef enablePartialUpdate
      xUpdateMin = DISPLAY_WIDTH - 1;
      xUpdateMax = 0;
      yUpdateMin = DISPLAY_HEIGHT-1;
      yUpdateMax = 0;
    #endif
}
void PCD8544_setContrast (u8 val)
Definition at line 401 of file PCD8544.c.
References PCD8544_command(), PCD8544_EXTENDEDINSTRUCTION, PCD8544_FUNCTIONSET, and PCD8544_SETVOP.
{
    PCD8544_command(PCD8544_FUNCTIONSET |
      PCD8544_EXTENDEDINSTRUCTION);
    PCD8544_command(PCD8544_SETVOP | (val & 0x7F));
    PCD8544_command(PCD8544_FUNCTIONSET);
}
void PCD8544_setCursor (u8 x, u8 y)
void PCD8544_shiftOut (u8 c)
Core functions
Definition at line 106 of file PCD8544.c.
References lcd_t::_din, lcd_t::_sclk, digitalwrite(), HIGH, LOW, and PCD8544.
Referenced by PCD8544_command(), PCD8544_data(), and PCD8544_refresh().
{
    u8 i;
    for (i = 0; i < 8; i++)
    {
        #if (PCD8544_INTERFACE & PCD8544_SPISW)
            #if (PCD8544_INTERFACE & PCD8544_PORTB)
                if (c & 0x80)
                    High(PCD8544_SDIN);
                else
                    Low(PCD8544_SDIN);
                High(PCD8544_SCLK);
                Low(PCD8544_SCLK);
            #else
                digitalwrite(PCD8544._din, (c & 0x80) ?
      HIGH : LOW);
                digitalwrite(PCD8544._sclk, HIGH);
                digitalwrite(PCD8544._sclk, LOW);
            #endif
            c <<= 1;
        #endif
    }
}
Variable Documentation
lcd_t PCD8544
Globals
Definition at line 199 of file PCD8544.h.
u8* PCD8544_buffer = logo
Definition at line 200 of file PCD8544.h.