/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/lcdlib.c File Reference
#include <delayms.c>
*
#include <delayus.c>
*
#include <digitalw.c>
*
#include <digitalp.c>
*
#include <const.h>
*
#include <lcdlib.h>
*
Macros
#define __LCDLIB_C__
Functions
void lcd_pulseEnable (void)
void lcd_write4bits (u8 value)
void lcd_write8bits (u8 value)
void lcd_send (u8 value, u8 mode)
void lcd_write (u8 value)
void lcd_command (u8 value)
void lcd_begin (u8 lines, u8 dotsize)
void lcd_init (u8 fourbitmode, u8 rs, u8 rw, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
void lcd_pins (u8 rs, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
Macro Definition Documentation
#define __LCDLIB_C__
Definition at line 24 of file lcdlib.c.
Function Documentation
void lcd_begin (u8 lines, u8 dotsize)
Setup line x column on LCD Print a string on LCD Write formated string on LCD Print a number on LCD Print a float number to LCD Move cursor to Home position Clear LCD Turn the display on/off (quickly) Turns the underline cursor on/off Turn on and off the blinking cursor These commands scroll the display without changing the RAM This is for text that flows Left to Right This is for text that flows Right to Left This will 'right justify' text from the cursor This will 'left justify' text from the cursor Initial Display settings!
Definition at line 330 of file lcdlib.c.
References _currline, _displaycontrol, _displayfunction, _displaymode, _enable_pin, _numlines, _rs_pin, Delayms(), Delayus(), digitalwrite(), LCD_2LINE, LCD_5x10DOTS, LCD_8BITMODE, LCD_BLINKOFF, LCD_CLEARDISPLAY, lcd_command(), LCD_CURSOROFF, LCD_DISPLAYCONTROL, LCD_DISPLAYON, LCD_ENTRYLEFT, LCD_ENTRYMODESET, LCD_ENTRYSHIFTDECREMENT, LCD_FUNCTIONSET, lcd_write4bits(), and LOW.
{
    if (lines > 1)
        _displayfunction |= LCD_2LINE;
    _numlines = lines;
    _currline = 0;
    // Some one line displays can select 10 pixel high font
    if ((dotsize != 0) && (lines == 1))
        _displayfunction |= LCD_5x10DOTS;
    Delayms(15); // Wait more than 15 ms after VDD rises to 4.5V
    // Now we pull both RS and R/W low to begin commands
    digitalwrite(_rs_pin, LOW);
    digitalwrite(_enable_pin, LOW);
    //put the LCD into 4 bit mode
    if (! (_displayfunction & LCD_8BITMODE))
    {
        // this is according to the hitachi HD44780 datasheet p46, figure 24
        // we start in 8bit mode, try to set 4 bit mode
        lcd_write4bits(0x03);
        Delayms(5); // Wait for more than 4.1 ms
        // second try
        lcd_write4bits(0x03);
        Delayus(150); // Wait more than 100 μs
        // third go!
        lcd_write4bits(0x03);
        Delayus(150); // Wait more than 100 μs
        // finally, set to 8-bit interface
        lcd_write4bits(0x02);
    }
    //put the LCD into 8 bit mode
    else
    {
        // this is according to the hitachi HD44780 datasheet p45, figure 23
        // Send function set command sequence
        lcd_command(LCD_FUNCTIONSET | _displayfunction);
        Delayms(5); // Wait for more than 4.1 ms
        // second try
        lcd_command(LCD_FUNCTIONSET | _displayfunction);
        Delayms(5); // Wait for more than 4.1 ms
        // Delayus(150);
        // third go
        lcd_command(LCD_FUNCTIONSET | _displayfunction);
    }
    // finally, set # lines, font size, etc.
    lcd_command(LCD_FUNCTIONSET | _displayfunction);
    // turn the display on with no cursor or blinking default
    _displaycontrol = LCD_DISPLAYON | LCD_CURSOROFF |
      LCD_BLINKOFF;
    lcd_command(LCD_DISPLAYCONTROL |
      _displaycontrol);
    // clear it off
    lcd_command(LCD_CLEARDISPLAY); // clear display, set cursor position to
       zero
    Delayms(2);
    // Initialize to default text direction (for romance languages)
    _displaymode = LCD_ENTRYLEFT |
      LCD_ENTRYSHIFTDECREMENT;
    // set the entry mode
    lcd_command(LCD_ENTRYMODESET | _displaymode);
}
void lcd_command (u8 value)
Write a control command on LCD
Definition at line 90 of file lcdlib.c.
References lcd_send(), and LOW.
Referenced by lcd_begin().
{
    lcd_send(value, LOW);
}
void lcd_init (u8 fourbitmode, u8 rs, u8 rw, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
Init LCD mode => 1 => 4 bits // 0 => 8 bits rs , rw, enable pins => D0 ~ D7.
Definition at line 405 of file lcdlib.c.
References _data_pins, _displayfunction, _enable_pin, _rs_pin, _rw_pin, LCD_1LINE, LCD_4BITMODE, LCD_5x8DOTS, LCD_8BITMODE, OUTPUT, and pinmode().
Referenced by lcd_pins().
{
    u8 i;
    _rs_pin = rs;
    _rw_pin = rw;
    _enable_pin = enable;
    _data_pins[0] = d0;
    _data_pins[1] = d1;
    _data_pins[2] = d2;
    _data_pins[3] = d3;
    _data_pins[4] = d4;
    _data_pins[5] = d5;
    _data_pins[6] = d6;
    _data_pins[7] = d7;
    pinmode(_rs_pin, OUTPUT);
    pinmode(_enable_pin, OUTPUT);
    if (fourbitmode)
    {
        _displayfunction = LCD_4BITMODE | LCD_1LINE |
      LCD_5x8DOTS;
        for (i = 0; i < 4; i++)
            pinmode(_data_pins[i], OUTPUT);
    }
    else
    {
        _displayfunction = LCD_8BITMODE | LCD_1LINE |
      LCD_5x8DOTS;
        for (i = 0; i < 8; i++)
            pinmode(_data_pins[i], OUTPUT);
    }
}
void lcd_pins (u8 rs, u8 enable, u8 d0, u8 d1, u8 d2, u8 d3, u8 d4, u8 d5, u8 d6, u8 d7)
LCD 8 bits mode
Definition at line 443 of file lcdlib.c.
References lcd_init().
{
    lcd_init(((d4 + d5 + d6 + d7)==0), rs, -1, enable, d0, d1, d2, d3, d4, d5, d6, d7);
}
void lcd_pulseEnable (void)
Positive pulse on E
Definition at line 39 of file lcdlib.c.
References _enable_pin, digitalwrite(), HIGH, and LOW.
Referenced by lcd_write4bits(), and lcd_write8bits().
{
    //digitalwrite(_enable_pin, LOW);
// Delayus(1);
    digitalwrite(_enable_pin, HIGH);
// Delayus(1); // enable pulse must be >450ns
    digitalwrite(_enable_pin, LOW);
// Delayus(100); // commands need > 37us to settle
}
void lcd_send (u8 value, u8 mode)
Send data to LCD 8 or 4 bits
Definition at line 68 of file lcdlib.c.
References _displayfunction, _rs_pin, digitalwrite(), LCD_8BITMODE, lcd_write4bits(), and lcd_write8bits().
Referenced by lcd_command(), and lcd_write().
{
    digitalwrite(_rs_pin, mode);
  
    if (_displayfunction & LCD_8BITMODE)
    {
        lcd_write8bits(value);
    }
    else
    {
        lcd_write4bits(value >> 4); // Upper 4 bits first
        lcd_write4bits(value); // Lower 4 bits second
    }
}
void lcd_write (u8 value)
Write a data character on LCD
Definition at line 84 of file lcdlib.c.
References HIGH, and lcd_send().
{
    lcd_send(value, HIGH);
}
void lcd_write4bits (u8 value)
Write using 4bits mode
Definition at line 50 of file lcdlib.c.
References _data_pins, digitalwrite(), and lcd_pulseEnable().
Referenced by lcd_begin(), and lcd_send().
{
    u8 i;
    for (i = 0; i < 4; i++)
        digitalwrite(_data_pins[i], (value >> i) & 0x01);
    lcd_pulseEnable();
}
void lcd_write8bits (u8 value)
Write using 8bits mode
Definition at line 59 of file lcdlib.c.
References _data_pins, digitalwrite(), and lcd_pulseEnable().
Referenced by lcd_send().
{
    u8 i;
    for (i = 0; i < 8; i++)
        digitalwrite(_data_pins[i], (value >> i) & 0x01);
    lcd_pulseEnable();
}