/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/sound.c File Reference
#include <typedef.h>
*
#include <delayms.c>
*
#include <digitalw.c>
*
#include <pwm.c>
*
Macros
#define __MYSOUND_C
#define C 1
#define Cs 2
#define D 3
#define Ds 4
#define E 5
#define F 6
#define Fs 7
#define G 8
#define Gs 9
#define A 10
#define As 11
#define B 12
#define C_ 13
#define DO 1
#define DOd 2
#define RE 3
#define REd 4
#define MI 5
#define FA 6
#define FAd 7
#define SOL 8
#define SOLd 9
#define LA 10
#define LAd 11
#define SI 12
#define DO_ 13
#define R4 8
#define R2 7
#define R1 6
#define R1_2 5
#define R1_4 4
#define R1_8 3
#define R1_16 2
#define R1_32 1
#define R1_64 0
Functions
void noTone (u8 pin)
void Tone (u8 pin, u16 freq, u16 duration)
void Sound (u8 pin, u8 note, u16 duration, u8 vol)
void Play (u8 pin, const u8 *partition, u8 volume)
Macro Definition Documentation
#define __MYSOUND_C
Definition at line 21 of file sound.c.
#define A 10
Definition at line 35 of file sound.c.
#define As 11
Definition at line 36 of file sound.c.
#define B 12
Definition at line 37 of file sound.c.
Referenced by sine().
#define C 1
Definition at line 26 of file sound.c.
Referenced by sine().
#define C_ 13
Definition at line 38 of file sound.c.
#define Cs 2
Definition at line 27 of file sound.c.
#define D 3
Definition at line 28 of file sound.c.
#define DO 1
Definition at line 41 of file sound.c.
#define DO_ 13
Definition at line 53 of file sound.c.
#define DOd 2
Definition at line 42 of file sound.c.
#define Ds 4
Definition at line 29 of file sound.c.
#define E 5
Definition at line 30 of file sound.c.
Referenced by SSD1306_sendCommand(), and SSD1306_sendData().
#define F 6
Definition at line 31 of file sound.c.
#define FA 6
Definition at line 46 of file sound.c.
#define FAd 7
Definition at line 47 of file sound.c.
#define Fs 7
Definition at line 32 of file sound.c.
#define G 8
Definition at line 33 of file sound.c.
#define Gs 9
Definition at line 34 of file sound.c.
#define LA 10
Definition at line 50 of file sound.c.
#define LAd 11
Definition at line 51 of file sound.c.
#define MI 5
Definition at line 45 of file sound.c.
#define R1 6
Definition at line 58 of file sound.c.
#define R1_16 2
Definition at line 62 of file sound.c.
#define R1_2 5
Definition at line 59 of file sound.c.
#define R1_32 1
Definition at line 63 of file sound.c.
#define R1_4 4
Definition at line 60 of file sound.c.
#define R1_64 0
Definition at line 64 of file sound.c.
#define R1_8 3
Definition at line 61 of file sound.c.
#define R2 7
Definition at line 57 of file sound.c.
#define R4 8
Definition at line 56 of file sound.c.
#define RE 3
Definition at line 43 of file sound.c.
#define REd 4
Definition at line 44 of file sound.c.
#define SI 12
Definition at line 52 of file sound.c.
#define SOL 8
Definition at line 48 of file sound.c.
#define SOLd 9
Definition at line 49 of file sound.c.
Function Documentation
void noTone (u8 pin)
Definition at line 71 of file sound.c.
References PWM_setFrequency(), and PWM_setPercentDutyCycle().
Referenced by Tone().
    {
        PWM_setFrequency(0); // note (range 1..14)
        PWM_setPercentDutyCycle(pin, 0); // silence
        //pinmode(pin, INPUT);
        //CCP1CON = 0; // stop sound = stop pwm
        //T2CONbits.TMR2ON = OFF; // disable Timer2 = stop pwm = stop sound
    }
void Play (u8 pin, const u8 * partition, u8 volume)
Definition at line 134 of file sound.c.
References Sound().
    {
        u8 i = 0;
        u8 exp;
        while (partition[i] != 0)
        {
            exp = partition[i+1];
            Sound(pin, partition[i], (8 << exp), volume);
            i = i + 2;
        }
    }
void Sound (u8 pin, u8 note, u16 duration, u8 vol)
Definition at line 106 of file sound.c.
References Tone().
Referenced by Play().
    {
        // Frequency table in French : http://fr.wikipedia.org/wiki/Note_de_musique
        // and in English http://liutaiomottola.com/formulae/freqtab.htm
        // freq. must be > 3000Hz so notes are taken from the 8th octave
        //const u16 freq[] = {2093,2217,2349,2489,2637,2793,2959,3135,3322,3520,3729,3951,4186};
        //const u16 freq[] = {4186,4434,4698,4978,5274,5587,5919,6271,6644,7040,7458,7902,8372};
        const u16 freq[] = {4189,4437,4687,4966,5281,5597,5905,6250,6637,7075,7425,7894,8333};
        if (vol > 10)
        {
            vol = 10; // max. volume is 10
        }
        vol = vol * 5; // max. volume is reach for 50% duty
        Tone(pin, freq[note-1], duration);
    }
void Tone (u8 pin, u16 freq, u16 duration)
Definition at line 80 of file sound.c.
References Delayms(), noTone(), PWM_setFrequency(), and PWM_setPercentDutyCycle().
Referenced by Sound().
    {
        PWM_setFrequency(freq);
        PWM_setPercentDutyCycle(pin, 50);
        Delayms(duration); // length of sound in ms
        noTone(pin);
    }