/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/ledcontrol.c File Reference
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <ledcontrol.h>
*
#include <string.h>
*
#include <digitalw.c>
*
#include <digitalp.c>
*
#include <delayms.c>
*
Macros
#define LEDCONTROL_C
#define OP_NOOP 0
#define OP_DIGIT0 1
#define OP_DIGIT1 2
#define OP_DIGIT2 3
#define OP_DIGIT3 4
#define OP_DIGIT4 5
#define OP_DIGIT5 6
#define OP_DIGIT6 7
#define OP_DIGIT7 8
#define OP_DECODEMODE 9
#define OP_INTENSITY 10
#define OP_SCANLIMIT 11
#define OP_SHUTDOWN 12
#define OP_DISPLAYTEST 15
Functions
void LedControl_init (u8 dataPin, u8 clkPin, u8 csPin, u8 numDevices)
public:
u8 LedControl_getDeviceCount ()
void LedControl_shutdown (u8 matrix, boolean b)
void LedControl_setScanLimit (u8 matrix, u8 limit)
void LedControl_setIntensity (u8 matrix, u8 intensity)
void LedControl_clearDisplay (u8 matrix)
void LedControl_clearAll ()
void LedControl_setLed (u8 matrix, u8 row, u8 column, boolean state)
void LedControl_setRow (u8 matrix, u8 row, u8 value)
void LedControl_setColumn (u8 matrix, u8 col, u8 value)
void shiftOut (u8 dataPin, u8 clockPin, u8 bitOrder, u8 val)
void LedControl_spiTransfer (u8 matrix, volatile u8 opcode, volatile u8 data)
Macro Definition Documentation
#define LEDCONTROL_C
Definition at line 31 of file ledcontrol.c.
#define OP_DECODEMODE 9
Definition at line 53 of file ledcontrol.c.
Referenced by LedControl_init().
#define OP_DIGIT0 1
Definition at line 45 of file ledcontrol.c.
#define OP_DIGIT1 2
Definition at line 46 of file ledcontrol.c.
#define OP_DIGIT2 3
Definition at line 47 of file ledcontrol.c.
#define OP_DIGIT3 4
Definition at line 48 of file ledcontrol.c.
#define OP_DIGIT4 5
Definition at line 49 of file ledcontrol.c.
#define OP_DIGIT5 6
Definition at line 50 of file ledcontrol.c.
#define OP_DIGIT6 7
Definition at line 51 of file ledcontrol.c.
#define OP_DIGIT7 8
Definition at line 52 of file ledcontrol.c.
#define OP_DISPLAYTEST 15
Definition at line 57 of file ledcontrol.c.
Referenced by LedControl_init().
#define OP_INTENSITY 10
Definition at line 54 of file ledcontrol.c.
Referenced by LedControl_setIntensity().
#define OP_NOOP 0
Definition at line 44 of file ledcontrol.c.
#define OP_SCANLIMIT 11
Definition at line 55 of file ledcontrol.c.
Referenced by LedControl_setScanLimit().
#define OP_SHUTDOWN 12
Definition at line 56 of file ledcontrol.c.
Referenced by LedControl_shutdown().
Function Documentation
void LedControl_clearAll ()
Definition at line 134 of file ledcontrol.c.
{
    u8 i;
    
    for (i=0;i<maxDevices;i++)
        LedControl_clearDisplay(i);
}
void LedControl_clearDisplay (u8 matrix)
Definition at line 119 of file ledcontrol.c.
Referenced by LedControl_clearAll(), and LedControl_init().
{
    u8 offset;
    u8 i;
    
    if(matrix<0 || matrix>=maxDevices)
        return;
    offset=matrix*8;
    for(i=0;i<8;i++)
    {
        status[offset+i]=0;
        LedControl_spiTransfer(matrix, i+1,status[offset+i]);
    }
}
u8 LedControl_getDeviceCount ()
Definition at line 89 of file ledcontrol.c.
                               {
    return maxDevices;
}
void LedControl_init (u8 dataPin, u8 clkPin, u8 csPin, u8 numDevices)
public:
Definition at line 59 of file ledcontrol.c.
{
    u8 i;
    
    LEDCONTROL_SPI_MOSI = dataPin;
    LEDCONTROL_SPI_CLK = clkPin;
    LEDCONTROL_SPI_CS = csPin;
    if(numDevices<=0 || numDevices>8)
        numDevices=8;
    maxDevices=numDevices;
    pinmode(LEDCONTROL_SPI_MOSI,OUTPUT);
    pinmode(LEDCONTROL_SPI_CLK,OUTPUT);
    pinmode(LEDCONTROL_SPI_CS,OUTPUT);
    digitalwrite(LEDCONTROL_SPI_CS,HIGH);
    LEDCONTROL_SPI_MOSI=dataPin;
    for(i=0;i<64;i++)
        status[i]=0x00;
    for(i=0;i<maxDevices;i++)
    {
        LedControl_spiTransfer(i,OP_DISPLAYTEST,0);
        //scanlimit is set to max on startup
        LedControl_setScanLimit(i,7);
        //decode is done in source
        LedControl_spiTransfer(i,OP_DECODEMODE,0);
        LedControl_clearDisplay(i);
        //we go into shutdown-mode on startup
        LedControl_shutdown(i,true);
    }
}
void LedControl_setColumn (u8 matrix, u8 col, u8 value)
Definition at line 176 of file ledcontrol.c.
{
    u8 val;
    u8 row;
    if(matrix<0 || matrix>=maxDevices)
        return;
    if(col<0 || col>7)
        return;
    for(row=0;row<8;row++)
    {
        //val=value >> (7-row);
        val=value >> row;
        val=val & 0x01;
        LedControl_setLed(matrix,row,col,val);
    }
}
void LedControl_setIntensity (u8 matrix, u8 intensity)
Definition at line 111 of file ledcontrol.c.
{
    if(matrix<0 || matrix>=maxDevices)
        return;
    if(intensity>=0 || intensity<16)
        LedControl_spiTransfer(matrix, OP_INTENSITY,intensity);
}
void LedControl_setLed (u8 matrix, u8 row, u8 column, boolean state)
Definition at line 142 of file ledcontrol.c.
Referenced by LedControl_setColumn().
{
    u8 offset;
    u8 val=0x00;
    if(matrix<0 || matrix>=maxDevices)
        return;
    if(row<0 || row>7 || column<0 || column>7)
        return;
    offset=matrix*8;
    val=0b10000000 >> column;
    if(state)
        status[offset+row]=status[offset+row]|val;
    else
    {
        val=~val;
        status[offset+row]=status[offset+row]&val;
    }
    LedControl_spiTransfer(matrix, row+1,status[offset+row]);
}
void LedControl_setRow (u8 matrix, u8 row, u8 value)
Definition at line 163 of file ledcontrol.c.
{
    u8 offset;
    
    if(matrix<0 || matrix>=maxDevices)
        return;
    if(row<0 || row>7)
        return;
    offset=matrix*8;
    status[offset+row]=value;
    LedControl_spiTransfer(matrix, row+1,status[offset+row]);
}
void LedControl_setScanLimit (u8 matrix, u8 limit)
Definition at line 103 of file ledcontrol.c.
Referenced by LedControl_init().
{
    if(matrix<0 || matrix>=maxDevices)
        return;
    if(limit>=0 || limit<8)
        LedControl_spiTransfer(matrix, OP_SCANLIMIT,limit);
}
void LedControl_shutdown (u8 matrix, boolean b)
Definition at line 93 of file ledcontrol.c.
Referenced by LedControl_init().
{
    if(matrix<0 || matrix>=maxDevices)
        return;
    if(b)
        LedControl_spiTransfer(matrix, OP_SHUTDOWN,0);
    else
        LedControl_spiTransfer(matrix, OP_SHUTDOWN,1);
}
void LedControl_spiTransfer (u8 matrix, volatile u8 opcode, volatile u8 data)
Definition at line 256 of file ledcontrol.c.
Referenced by LedControl_clearDisplay(), LedControl_init(), LedControl_setIntensity(), LedControl_setLed(), LedControl_setRow(), LedControl_setScanLimit(), and LedControl_shutdown().
{
    //Create an array with the data to shift out
    u8 offset=matrix*2;
    u8 maxbytes=maxDevices*2;
    u8 i;
    
    for(i=0;i<maxbytes;i++)
        spidata[i]=(u8)0;
    //put our device data into the array
    spidata[offset+1]=opcode;
    spidata[offset]=data;
    //enable the line
    digitalwrite(LEDCONTROL_SPI_CS,LOW);
    //Now shift out the data
    for(i=maxbytes;i>0;i--)
        shiftOut(LEDCONTROL_SPI_MOSI,
      LEDCONTROL_SPI_CLK,MSBFIRST,spidata[i-1]);
    //latch the data onto the display
    digitalwrite(LEDCONTROL_SPI_CS,HIGH);
}
void shiftOut (u8 dataPin, u8 clockPin, u8 bitOrder, u8 val)
Definition at line 238 of file ledcontrol.c.
References digitalwrite(), HIGH, LOW, and LSBFIRST.
Referenced by LedControl_spiTransfer().
{
    u8 i;
    u8 bitMask;
    for (i = 0; i < 8; i++)
    {
        if (bitOrder == LSBFIRST)
            bitMask = (1 << i);
        else
            bitMask = (1 << (7 - i));
        digitalwrite(dataPin, (val & bitMask) ? HIGH : LOW);
        digitalwrite(clockPin, HIGH);
        digitalwrite(clockPin, LOW);
    }
}