/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/pwm.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <pin.h>
*
#include <digitalp.c>
*
#include <oscillator.c>
*
Macros
#define __PWM__
Functions
void PWM_setFrequency (u32 freq)
void PWM_setDutyCycle (u8 pin, u16 duty)
void PWM_setPercentDutyCycle (u8 pin, u8 percent)
Variables
u16 _pr2_plus1 = 256
u8 _t2con
Macro Definition Documentation
#define __PWM__
Definition at line 34 of file pwm.c.
Function Documentation
void PWM_setDutyCycle (u8 pin, u16 duty)
Definition at line 113 of file pwm.c.
References _pr2_plus1, _t2con, OUTPUT, and pinmode().
Referenced by PWM_setPercentDutyCycle().
{
    if (duty > 1023) duty = 1023; // upper limit (10-bit)
    // 1- Set the PWM period by writing to the PR2 (PR4) register.
    PR2 = _pr2_plus1 - 1; // set PWM period
    #if defined(__18f26j53) || defined(__18f46j53) || \
        defined(__18f27j53) || defined(__18f47j53)
    CCPTMRS1 = 0; // assign Timer2 to all CCP pins
    CCPTMRS2 = 0;
    #endif
    // 2- Set the PWM duty cycle by writing to the CCPRxL register and
    // CCPxCON<5:4> bits.
    switch (pin)
    {
        #if defined(__18f26j53) || defined(__18f46j53) || \
            defined(__18f27j53) || defined(__18f47j53)
        case CCP4:
            CCP4CON = 0b00001100;
            CCPR4L = (duty >> 2) & 0xFF; // 8 LSB
            CCP4CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        case CCP5:
            CCP5CON = 0b00001100;
            CCPR5L = (duty >> 2) & 0xFF; // 8 LSB
            CCP5CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        case CCP6:
            CCP6CON = 0b00001100;
            CCPR6L = (duty >> 2) & 0xFF; // 8 LSB
            CCP6CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        case CCP7:
            CCP7CON = 0b00001100;
            CCPR7L = (duty >> 2) & 0xFF; // 8 LSB
            CCP7CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        case CCP8:
            CCP8CON = 0b00001100;
            CCPR8L = (duty >> 2) & 0xFF; // 8 LSB
            CCP8CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        case CCP9:
            CCP9CON = 0b00001100;
            CCPR9L = (duty >> 2) & 0xFF; // 8 LSB
            CCP9CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        case CCP10:
            CCP10CON = 0b00001100;
            CCPR10L = (duty >> 2) & 0xFF; // 8 LSB
            CCP10CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        #else
        case CCP1:
            CCP1CON = 0b00001100;
            CCPR1L = (duty >> 2) & 0xFF; // 8 LSB
            CCP1CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        case CCP2:
            CCP2CON = 0b00001100;
            CCPR2L = (duty >> 2) & 0xFF; // 8 LSB
            CCP1CON |= (duty & 0x300) >> 4; // 2 MSB in <5:4>
            break;
        #endif
        default:
            #ifdef DEBUG
                #error "Invalid CCPx Pin"
            #endif
    }
    // 3- Make the CCPx pin an output by clearing the appropriate TRIS bit.
    pinmode(pin, OUTPUT); // PWM pin as OUTPUT
    // 4- Set the TMR2 prescale value, then enable Timer2 by writing to T2CON
    T2CON = _t2con; // Timer2 prescaler + ON
    // 5- Configure the CCPx module for PWM operation
    //PIR1bits.TMR2IF = 0; // Reset interrupt flag
}
void PWM_setFrequency (u32 freq)
Definition at line 66 of file pwm.c.
References _pr2_plus1, _t2con, and System_getPeripheralFrequency().
Referenced by noTone(), and Tone().
{
    // PR2+1 calculation
    _pr2_plus1 = System_getPeripheralFrequency() / freq; // FOSC /
       (4 * PWM Frequency)
    // Timer2 prescaler calculation
    // PR2 max value is 255, so PR2+1 max value is 256
    // highest prescaler value is 16
    // 16 * 256 = 4096 so :
    if (_pr2_plus1 <= 4096) // check if it's not too high
    {
        if (_pr2_plus1 <= 256) // no needs of any prescaler
        {
            _t2con = 0b00000100; // prescaler is 1, Timer2 On
        }
        else if (_pr2_plus1 <= 1024) // needs prescaler 1:4
        {
            _pr2_plus1 = _pr2_plus1 >> 2; // divided by 4
            _t2con = 0b00000101; // prescaler is 4, Timer2 On
        }
        else // needs prescaler 1:6
        {
            _pr2_plus1 = _pr2_plus1 >> 4; // divided by 16
            _t2con = 0b00000110; // prescaler is 16, Timer2 On
        }
    }
}
void PWM_setPercentDutyCycle (u8 pin, u8 percent)
Definition at line 225 of file pwm.c.
References _pr2_plus1, and PWM_setDutyCycle().
Referenced by IRsend_mark(), IRsend_space(), noTone(), and Tone().
{
    u16 duty;
    if (percent == 0)
        duty = 0;
    else if (percent >= 100)
        duty = _pr2_plus1 - 1;
    else
        duty = percent * (_pr2_plus1 / 4) / 25; // (factor PR2/100)
    PWM_setDutyCycle(pin, duty << 2);
}
Variable Documentation
u16 _pr2_plus1 = 256
Definition at line 47 of file pwm.c.
Referenced by PWM_setDutyCycle(), PWM_setFrequency(), and PWM_setPercentDutyCycle().
u8 _t2con
Definition at line 48 of file pwm.c.
Referenced by PWM_setDutyCycle(), and PWM_setFrequency().