/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/18b20.c File Reference
#include <const.h>
*
#include <macro.h>
*
#include <typedef.h>
*
#include <1wire.c>
*
Data Structures
struct DS18B20_Temperature
Macros
#define __DS18B20_C
#define SEARCHROM 0xF0
DS18B20 ROM COMMANDS.
#define READROM 0x33
#define MATCHROM 0x55
#define SKIPROM 0xCC
#define ALARM_SEARCH 0xEC
#define CONVERT_T 0x44
DS18B20 FUNCTION COMMANDS.
#define WRITE_SCRATCHPAD 0x4E
#define READ_SCRATCHPAD 0xBE
#define COPY_SCRATCHPAD 0x48
#define RECALL_E2 0xB8
#define READ_POWER_SUPPLY 0xB4
#define RES12BIT 1
MODES.
#define RES11BIT 2
#define RES10BIT 3
#define RES9BIT 4
Functions
u8 DS18B20Read (u8, u8, u8, DS18B20_Temperature *)
PROTOTYPES.
u8 DS18B20MatchRom (u8, u8)
void DS18B20ReadRom (u8, u8 *)
u8 DS18B20Configure (u8, u8, u8, u8, u8)
void DS18B20Find (u8)
u8 DS18B20GetFirst (u8)
u8 DS18B20GetNext (u8)
u8 DS18B20_crc (u8)
u8 DS18B20StartMeasure (u8 pin, u8 rom, u8 resolution)
u8 DS18B20ReadMeasure (u8 pin, u8 rom, DS18B20_Temperature *t)
Variables
u8 DS18B20Rom [6][8]
u8 ROM [8]
u8 lastDiscrep = 0
u8 doneFlag = 0
u8 numROMs
u8 dowcrc
Macro Definition Documentation
#define __DS18B20_C
Definition at line 37 of file 18b20.c.
#define ALARM_SEARCH 0xEC
Definition at line 88 of file 18b20.c.
#define CONVERT_T 0x44
DS18B20 FUNCTION COMMANDS.
Definition at line 92 of file 18b20.c.
Referenced by DS18B20Read(), and DS18B20StartMeasure().
#define COPY_SCRATCHPAD 0x48
Definition at line 95 of file 18b20.c.
#define MATCHROM 0x55
Definition at line 86 of file 18b20.c.
Referenced by DS18B20MatchRom().
#define READ_POWER_SUPPLY 0xB4
Definition at line 97 of file 18b20.c.
#define READ_SCRATCHPAD 0xBE
Definition at line 94 of file 18b20.c.
Referenced by DS18B20Read(), and DS18B20ReadMeasure().
#define READROM 0x33
Definition at line 85 of file 18b20.c.
Referenced by DS18B20ReadRom().
#define RECALL_E2 0xB8
Definition at line 96 of file 18b20.c.
#define RES10BIT 3
Definition at line 103 of file 18b20.c.
Referenced by DS18B20Read(), and DS18B20StartMeasure().
#define RES11BIT 2
Definition at line 102 of file 18b20.c.
Referenced by DS18B20Read(), and DS18B20StartMeasure().
#define RES12BIT 1
MODES.
Definition at line 101 of file 18b20.c.
Referenced by DS18B20Read(), and DS18B20StartMeasure().
#define RES9BIT 4
Definition at line 104 of file 18b20.c.
Referenced by DS18B20Read(), and DS18B20StartMeasure().
#define SEARCHROM 0xF0
DS18B20 ROM COMMANDS.
Definition at line 84 of file 18b20.c.
Referenced by DS18B20GetNext().
#define SKIPROM 0xCC
Definition at line 87 of file 18b20.c.
Referenced by DS18B20Configure(), DS18B20Read(), DS18B20ReadMeasure(), and DS18B20StartMeasure().
#define WRITE_SCRATCHPAD 0x4E
Definition at line 93 of file 18b20.c.
Referenced by DS18B20Configure().
Function Documentation
u8 DS18B20_crc (u8 x)
Definition at line 493 of file 18b20.c.
References dowcrc.
Referenced by DS18B20GetNext(), and DS18B20Read().
    {
        u8 i = (x ^ dowcrc) & 0xff;
        dowcrc = 0;
        if (i & 0x01) dowcrc ^= 0x5e;
        if (i & 0x02) dowcrc ^= 0xbc;
        if (i & 0x04) dowcrc ^= 0x61;
        if (i & 0x08) dowcrc ^= 0xc2;
        if (i & 0x10) dowcrc ^= 0x9d;
        if (i & 0x20) dowcrc ^= 0x23;
        if (i & 0x40) dowcrc ^= 0x46;
        if (i & 0x80) dowcrc ^= 0x8c;
        return dowcrc;
    }
u8 DS18B20Configure (u8 pin, u8 rom, u8 TH, u8 TL, u8 config)
Definition at line 258 of file 18b20.c.
References DS18B20MatchRom(), OneWireReset(), OneWireWrite(), SKIPROM, and WRITE_SCRATCHPAD.
Referenced by DS18B20Read(), and DS18B20StartMeasure().
    {
        if (OneWireReset(pin)) return false;
        if (rom == SKIPROM)
        {
            // Skip ROM, address all devices
            OneWireWrite(pin, SKIPROM);
        }
        else
        {
            // Talk to a particular device
            DS18B20MatchRom(pin, rom);
        }
        OneWireWrite(pin, WRITE_SCRATCHPAD); // Allows the master to write 3
       bytes of data to the scratchpad
        OneWireWrite(pin, TH); // The first data byte is written into the TH
       register (byte 2 of the scratchpad)
        OneWireWrite(pin, TL); // The second byte is written into the TL register
       (byte 3)
        OneWireWrite(pin, config); // The third byte is written into the configuration
       register (byte 4)
        return true;
    }
void DS18B20Find (u8 pin)
Definition at line 333 of file 18b20.c.
References DS18B20GetFirst(), DS18B20GetNext(), DS18B20Rom, numROMs, OneWireReset(), and ROM.
    {
        u8 m;
        if (!OneWireReset(pin)) // Detects presence of devices
        {
            if (DS18B20GetFirst(pin)) // Begins when at least one part is found
            {
                numROMs=0;
                do {
                    numROMs++;
                    // serialprint("Device #");
                    for(m = 0; m < 8; m++)
                    {
                        // Identifies ROM number on found device
                        DS18B20Rom[numROMs][m] = ROM[m];
                    }
                //Continues until no additional devices are found
                } while (DS18B20GetNext(pin)&&(numROMs<10));
            }
        }
    }
u8 DS18B20GetFirst (u8 pin)
Definition at line 364 of file 18b20.c.
References doneFlag, DS18B20GetNext(), and lastDiscrep.
Referenced by DS18B20Find().
    {
        lastDiscrep = 0; // reset the rom search last discrepancy global
        doneFlag = false;
        return DS18B20GetNext(pin); // call Next and return its return value
    }
u8 DS18B20GetNext (u8 pin)
Definition at line 379 of file 18b20.c.
References doneFlag, dowcrc, DS18B20_crc(), lastDiscrep, OneWireReadBit(), OneWireReset(), OneWireWrite(), OneWireWriteBit(), ROM, SEARCHROM, and x.
Referenced by DS18B20Find(), and DS18B20GetFirst().
    {
        u8 m = 1; // ROM Bit index
        u8 n = 0; // ROM Byte index
        u8 k = 1; // bit mask
        u8 x = 0;
        u8 discrepMarker = 0; // discrepancy marker
        u8 g; // Output bit
        u8 nxt; // return value
        int flag;
        nxt = false; // set the next flag to false
        dowcrc = 0; // reset the dowcrc
        flag = OneWireReset(pin); // reset the 1-wire
        if(flag||doneFlag) // no parts -> return false
        {
            lastDiscrep = 0; // reset the search
            return false;
        }
        // send SearchROM command for all eight bytes
        OneWireWrite(pin, SEARCHROM);
        do {
            x = 0;
            if(OneWireReadBit(pin) == 1) x = 2;
            //myDelay_10us(12);
            if(OneWireReadBit(pin) == 1) x |= 1;
            if(x == 3)
                break;
            else
            {
                if(x > 0) // all devices coupled have 0 or 1
                    g = x >> 1; // bit write value for search
                else
                {
                    // if this discrepancy is before the last
                    // discrepancy on a previous Next then pick
                    // the same as last time
                    if(m < lastDiscrep)
                        g = ((ROM[n] & k) > 0);
                    else // if equal to last pick 1
                        g = (m == lastDiscrep); // if not then pick 0
                        // if 0 was picked then record position with mask k
                        if (g == 0) discrepMarker = m;
                }
                if (g == 1) // isolate bit in ROM[n] with mask k
                    ROM[n] |= k;
                else
                    ROM[n] &= ~k;
                OneWireWriteBit(pin, g); // ROM search write
                m++; // increment bit counter m
                k = k << 1; // and shift the bit mask k
                if(k == 0) // if the mask is 0 then go to new ROM
                { // byte n and reset mask
                    DS18B20_crc(ROM[n]); // accumulate the CRC
                    n++;
                    k++;
                }
            }
        } while (n < 8); // loop until through all ROM bytes 0-7
        if(m < 65 || dowcrc) // if search was unsuccessful then
            lastDiscrep=0; // reset the last discrepancy to 0
        else // search was successful, so set lastDiscrep, lastOne,
       nxt
        {
            lastDiscrep = discrepMarker;
            doneFlag = (lastDiscrep == 0);
            nxt = true; // indicates search is not complete yet, more parts
       remain
        }
        return nxt;
    }
u8 DS18B20MatchRom (u8 pin, u8 rom)
Definition at line 292 of file 18b20.c.
References DS18B20Rom, MATCHROM, OneWireReset(), and OneWireWrite().
Referenced by DS18B20Configure(), DS18B20Read(), DS18B20ReadMeasure(), and DS18B20StartMeasure().
    {
        u8 i;
        if (OneWireReset(pin)) return false;
        OneWireWrite(pin, MATCHROM); // Match Rom
        for (i = 0; i < 8; i++) // Send the Address ROM Code.
            OneWireWrite(pin, DS18B20Rom[rom][i]);
        return true;
    }
u8 DS18B20Read (u8 pin, u8 rom, u8 resolution, DS18B20_Temperature * t)
PROTOTYPES.
NB: The power-up default of these bits is R0 = 1 and R1 = 1 (12-bit resolution)
Definition at line 129 of file 18b20.c.
References c, CONVERT_T, dowcrc, DS18B20_crc(), DS18B20Configure(), DS18B20MatchRom(), DS18B20_Temperature::fraction, DS18B20_Temperature::integer, LOW, OneWireRead(), OneWireReset(), OneWireWrite(), READ_SCRATCHPAD, res, RES10BIT, RES11BIT, RES12BIT, RES9BIT, DS18B20_Temperature::sign, and SKIPROM.
    {
        u8 res, busy = LOW;
        u8 temp_lsb, temp_msb;
        u8 c, crc_flag = 0;
        u8 buffer[];
        u16 temp;
        switch (resolution)
        {
            case RES12BIT: res = 0b01100000; break; // 12-bit resolution
            case RES11BIT: res = 0b01000000; break; // 11-bit resolution
            case RES10BIT: res = 0b00100000; break; // 10-bit resolution
            case RES9BIT: res = 0b00000000; break; // 9-bit resolution
            default: res = 0b00000000; break; // 9-bit resolution
        }
        
        if (!DS18B20Configure(pin, rom, 0, 0, res)) return false; // no alarm
        // read temperature until crc is valid
        while (crc_flag == 0)
        {
            if (OneWireReset(pin)) return false;
            if (rom == SKIPROM)
            {
                // Skip ROM, address all devices
                OneWireWrite(pin, SKIPROM);
            }
            else
            {
                // Talk to a particular device
                if (!DS18B20MatchRom(pin, rom)) return false;
            }
            OneWireWrite(pin, CONVERT_T); // Start temperature conversion
            while (busy == LOW) // Wait while busy (= bus is low)
                busy = OneWireRead(pin);
            if (OneWireReset(pin)) return false;
            if (rom == SKIPROM)
            {
                // Skip ROM, address all devices
                OneWireWrite(pin, SKIPROM);
            }
            else
            {
                // Talk to a particular device
                if (!DS18B20MatchRom(pin, rom)) return false;
            }
            OneWireWrite(pin, READ_SCRATCHPAD); // Read scratchpad
            for (c = 0; c < 8; c++)
            {
                buffer[c] = OneWireRead(pin); // Receive 8 bytes from DS18B20
                DS18B20_crc(buffer[c]);
            }
            buffer[8] = OneWireRead(pin); // Receive the 9th byte [CRC] from
       DS18B20
            
            if (dowcrc == buffer[8]) // Compare calculated CRC with the 9th byte
       received
            {
                temp_lsb = buffer[0]; // byte 0 of scratchpad : temperature lsb
                temp_msb = buffer[1]; // byte 1 of scratchpad : temperature msb
                //temp_lsb = OneWireRead(pin); // byte 0 of scratchpad : temperature lsb
                //temp_msb = OneWireRead(pin); // byte 1 of scratchpad : temperature msb
                //if (OneWireReset(pin)) return false;
                // Calculation
                // ---------------------------------------------------------------------
                // Temperature Register Format
                // BIT7 BIT6 BIT5 BIT4 BIT3 BIT2 BIT1 BIT0
                // LS BYTE 2^3 2^2 2^1 2^0 2^-1 2^-2 2^-3 2^-4
                // BIT15 BIT14 BIT13 BIT12 BIT11 BIT10 BIT9 BIT8
                // MS BYTE S S S S S 2^6 2^5 2^4
                // S = SIGN
                temp = temp_msb;
                temp = (temp << 8) + temp_lsb; // combine msb & lsb into 16 bit variable
                
                if (temp_msb & 0b11111000) // test if sign is set, i.e. negative
                {
                    t->sign = 1;
                    temp = (temp ^ 0xFFFF) + 1; // 2's complement conversion
                }
                else
                {
                    t->sign = 0;
                }
                t->integer = (temp >> 4) & 0x7F; // fractional part is removed, leaving only integer
       part
                /*
                t->fraction = 0; // fractional part
                if (BitRead(temp, 0)) t->fraction += 625;
                if (BitRead(temp, 1)) t->fraction += 1250;
                if (BitRead(temp, 2)) t->fraction += 2500;
                if (BitRead(temp, 3)) t->fraction += 5000;
                */
                t->fraction = (temp & 0x0F) * 625;
                t->fraction /= 100; // two digits after decimal
                crc_flag = 1; // Flag for good CRC: this will exit the while
       statement
            }
            dowcrc = 0;
        }
        return true;
    }
u8 DS18B20ReadMeasure (u8 pin, u8 rom, DS18B20_Temperature * t)
Definition at line 567 of file 18b20.c.
References DS18B20MatchRom(), FALSE, DS18B20_Temperature::fraction, DS18B20_Temperature::integer, LOW, OneWireRead(), OneWireReset(), OneWireWrite(), READ_SCRATCHPAD, res, DS18B20_Temperature::sign, SKIPROM, and TRUE.
    {
        u8 res, busy = LOW;
        u8 temp_lsb, temp_msb;
        u16 temp;
        if (OneWireReset(pin)) return FALSE;
        if (rom == SKIPROM)
        {
            // Skip ROM, address all devices
            OneWireWrite(pin, SKIPROM);
        }
        else
        {
            // Talk to a particular device
            if (!DS18B20MatchRom(pin, rom)) return FALSE;
        }
        OneWireWrite(pin, READ_SCRATCHPAD);// Read scratchpad
        temp_lsb = OneWireRead(pin); // byte 0 of scratchpad : temperature lsb
        temp_msb = OneWireRead(pin); // byte 1 of scratchpad : temperature msb
        if (OneWireReset(pin)) return FALSE;
        // Calculation
        // ---------------------------------------------------------------------
        // Temperature Register Format
        // BIT7 BIT6 BIT5 BIT4 BIT3 BIT2 BIT1 BIT0
        // LS BYTE 2^3 2^2 2^1 2^0 2^-1 2^-2 2^-3 2^-4
        // BIT15 BIT14 BIT13 BIT12 BIT11 BIT10 BIT9 BIT8
        // MS BYTE S S S S S 2^6 2^5 2^4
        // S = SIGN
        temp = temp_msb;
        temp = (temp << 8) + temp_lsb; // combine msb & lsb into 16 bit variable
        
        if (temp_msb & 0b11111000) // test if sign is set, i.e. negative
        {
            t->sign = 1;
            temp = (temp ^ 0xFFFF) + 1; // 2's complement conversion
        }
        else
        {
            t->sign = 0;
        }
        t->integer = (temp >> 4) & 0x7F; // fractional part is removed, leaving only integer part
/*
        t->fraction = 0; // fractional part
        if (BitRead(temp, 0)) t->fraction += 625;
        if (BitRead(temp, 1)) t->fraction += 1250;
        if (BitRead(temp, 2)) t->fraction += 2500;
        if (BitRead(temp, 3)) t->fraction += 5000;
*/
        t->fraction = (temp & 0x0F) * 625;
        t->fraction /= 100; // two digits after decimal
        return TRUE;
    }
void DS18B20ReadRom (u8 pin, u8 * romcode)
Definition at line 315 of file 18b20.c.
References OneWireRead(), OneWireReset(), OneWireWrite(), and READROM.
    {
        u8 i;
        if (!OneWireReset(pin))
        {
            OneWireWrite(pin, READROM);
            for (i = 0; i < 8; i++) // Reads the ROM Code from a device
                romcode[i] = OneWireRead(pin);
        }
    }
u8 DS18B20StartMeasure (u8 pin, u8 rom, u8 resolution)
NB: The power-up default of these bits is R0 = 1 and R1 = 1 (12-bit resolution)
Definition at line 522 of file 18b20.c.
References CONVERT_T, DS18B20Configure(), DS18B20MatchRom(), FALSE, LOW, OneWireReset(), OneWireWrite(), res, RES10BIT, RES11BIT, RES12BIT, RES9BIT, SKIPROM, and TRUE.
    {
        u8 res, busy = LOW;
        u8 temp_lsb, temp_msb;
        u16 temp;
        switch (resolution)
        {
            case RES12BIT: res = 0b01100000; break; // 12-bit resolution
            case RES11BIT: res = 0b01000000; break; // 11-bit resolution
            case RES10BIT: res = 0b00100000; break; // 10-bit resolution
            case RES9BIT: res = 0b00000000; break; // 9-bit resolution
            default: res = 0b00000000; break; // 9-bit resolution
        }
        
        if (!DS18B20Configure(pin, rom, 0, 0, res)) return FALSE; // no alarm
        if (OneWireReset(pin)) return FALSE;
        if (rom == SKIPROM)
        {
            // Skip ROM, address all devices
            OneWireWrite(pin, SKIPROM);
        }
        else
        {
            // Talk to a particular device
            if (!DS18B20MatchRom(pin, rom)) return FALSE;
        }
        OneWireWrite(pin, CONVERT_T); // Start temperature conversion
        return TRUE;
    }
Variable Documentation
u8 doneFlag = 0
Definition at line 58 of file 18b20.c.
Referenced by DS18B20GetFirst(), and DS18B20GetNext().
u8 dowcrc
Definition at line 60 of file 18b20.c.
Referenced by DS18B20_crc(), DS18B20GetNext(), and DS18B20Read().
u8 DS18B20Rom[6][8]
Definition at line 55 of file 18b20.c.
Referenced by DS18B20Find(), and DS18B20MatchRom().
u8 lastDiscrep = 0
Definition at line 57 of file 18b20.c.
Referenced by DS18B20GetFirst(), and DS18B20GetNext().
u8 numROMs
Definition at line 59 of file 18b20.c.
Referenced by DS18B20Find().
u8 ROM[8]
Definition at line 56 of file 18b20.c.
Referenced by DS18B20Find(), and DS18B20GetNext().