/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/sd/diskio.c File Reference
#include <sd/diskio.h>
*
#include <spi.c>
*
#include <delayms.c>
*
#include <serial.c>
*
Macros
#define _DISKIOC
#define CMD0 (0x40+0)	/* GO_IDLE_STATE */
#define CMD1 (0x40+1)	/* SEND_OP_COND (MMC) */
#define ACMD41 (0xC0+41)	/* SEND_OP_COND (SDC) */
#define CMD8 (0x40+8)	/* SEND_IF_COND */
#define CMD9 (0x40+9)	/* SEND_CSD */
#define CMD10 (0x40+10)	/* SEND_CID */
#define CMD12 (0x40+12)	/* STOP_TRANSMISSION */
#define ACMD13 (0xC0+13)	/* SD_STATUS (SDC) */
#define CMD16 (0x40+16)	/* SET_BLOCKLEN */
#define CMD17 (0x40+17)	/* READ_SINGLE_BLOCK */
#define CMD18 (0x40+18)	/* READ_MULTIPLE_BLOCK */
#define CMD23 (0x40+23)	/* SET_BLOCK_COUNT (MMC) */
#define ACMD23 (0xC0+23)	/* SET_WR_BLK_ERASE_COUNT (SDC) */
#define CMD24 (0x40+24)	/* WRITE_BLOCK */
#define CMD25 (0x40+25)	/* WRITE_MULTIPLE_BLOCK */
#define CMD55 (0x40+55)	/* APP_CMD */
#define CMD58 (0x40+58)	/* READ_OCR */
#define CS_LOW() SD_CS = 0	/* MMC CS = L */
#define CS_HIGH() SD_CS = 1	/* MMC CS = H */
#define SELECT() SD_CS = 0	/* MMC CS = Low */
#define DESELECT() SD_CS = 1	/* MMC CS = High */
#define FCLK_SLOW() (CONFIG = 0x22)	/* Set slow clock (100k-400k) */
#define FCLK_FAST() (CONFIG = 0x21)	/* Set fast clock (depends on the CSD) */
#define NCR_TIMEOUT (u8)20
#define WRITE_TIMEOUT (u32)0xA0000
Functions
void SPI_init (u8 sync_mode, u8 bus_mode, u8 smp_phase)
u8 SPI_write (u8 datax)
u8 SPI_read ()
DSTATUS disk_initialize (void)
Macro Definition Documentation
#define _DISKIOC
Definition at line 5 of file diskio.c.
#define ACMD13 (0xC0+13)	/* SD_STATUS (SDC) */
Definition at line 19 of file diskio.c.
#define ACMD23 (0xC0+23)	/* SET_WR_BLK_ERASE_COUNT (SDC) */
Definition at line 24 of file diskio.c.
#define ACMD41 (0xC0+41)	/* SEND_OP_COND (SDC) */
Definition at line 14 of file diskio.c.
Referenced by disk_initialize().
#define CMD0 (0x40+0)	/* GO_IDLE_STATE */
Definition at line 12 of file diskio.c.
Referenced by disk_initialize().
#define CMD1 (0x40+1)	/* SEND_OP_COND (MMC) */
Definition at line 13 of file diskio.c.
Referenced by disk_initialize().
#define CMD10 (0x40+10)	/* SEND_CID */
Definition at line 17 of file diskio.c.
#define CMD12 (0x40+12)	/* STOP_TRANSMISSION */
Definition at line 18 of file diskio.c.
Referenced by disk_initialize().
#define CMD16 (0x40+16)	/* SET_BLOCKLEN */
Definition at line 20 of file diskio.c.
Referenced by disk_initialize().
#define CMD17 (0x40+17)	/* READ_SINGLE_BLOCK */
Definition at line 21 of file diskio.c.
#define CMD18 (0x40+18)	/* READ_MULTIPLE_BLOCK */
Definition at line 22 of file diskio.c.
#define CMD23 (0x40+23)	/* SET_BLOCK_COUNT (MMC) */
Definition at line 23 of file diskio.c.
#define CMD24 (0x40+24)	/* WRITE_BLOCK */
Definition at line 25 of file diskio.c.
#define CMD25 (0x40+25)	/* WRITE_MULTIPLE_BLOCK */
Definition at line 26 of file diskio.c.
#define CMD55 (0x40+55)	/* APP_CMD */
Definition at line 27 of file diskio.c.
#define CMD58 (0x40+58)	/* READ_OCR */
Definition at line 28 of file diskio.c.
Referenced by disk_initialize().
#define CMD8 (0x40+8)	/* SEND_IF_COND */
Definition at line 15 of file diskio.c.
Referenced by disk_initialize().
#define CMD9 (0x40+9)	/* SEND_CSD */
Definition at line 16 of file diskio.c.
#define CS_HIGH() SD_CS = 1	/* MMC CS = H */
Definition at line 32 of file diskio.c.
#define CS_LOW() SD_CS = 0	/* MMC CS = L */
Definition at line 31 of file diskio.c.
#define DESELECT() SD_CS = 1	/* MMC CS = High */
Definition at line 36 of file diskio.c.
Referenced by disk_initialize().
#define FCLK_FAST() (CONFIG = 0x21)	/* Set fast clock (depends on the CSD) */
Definition at line 39 of file diskio.c.
Referenced by disk_initialize().
#define FCLK_SLOW() (CONFIG = 0x22)	/* Set slow clock (100k-400k) */
Definition at line 38 of file diskio.c.
#define NCR_TIMEOUT (u8)20
Definition at line 41 of file diskio.c.
#define SELECT() SD_CS = 0	/* MMC CS = Low */
Definition at line 35 of file diskio.c.
Referenced by disk_initialize().
#define WRITE_TIMEOUT (u32)0xA0000
Definition at line 42 of file diskio.c.
Function Documentation
DSTATUS disk_initialize (void)
Definition at line 178 of file diskio.c.
References ACMD41, CMD0, CMD1, CMD12, CMD16, CMD58, CMD8, CT_BLOCK, CT_MMC, CT_SD1, CT_SD2, DESELECT, FCLK_FAST, SELECT, SPI_init(), SPI_read(), SPI_write(), STA_NODISK, and STA_NOINIT.
Referenced by pf_mount().
{
    u8 n, cmd, ty, ocr[4], rep, timeout;
    u16 tmr;
    if (Stat & STA_NODISK) return Stat; /* No card in the socket */
    SPI_init(2,0,0); /* Force socket power on */
    for (n = 10; n; n--) SPI_write(0xFF); /* Dummy clocks */
    ty = 0;
    timeout=100;
// Trying to enter Idle state
    do {
        DESELECT();
        SPI_write(0xFF);
        SELECT();
        rep = send_cmd(CMD0,0);
    } while ((rep != 1) && (--timeout));
    if(timeout == 0)
    {
        DESELECT();
        SPI_write(0xFF);
        SELECT();
        rep = send_cmd(CMD12,0);
        rep = send_cmd(CMD0,0);
        if (rep != 1) return STA_NOINIT;
    }
    rep = send_cmd(CMD8, 0x1AA);
    if (rep == 1) { /* SDHC */
        for (n = 0; n < 4; n++) ocr[n] = SPI_read(); /* Get trailing return value of R7 resp
       */
        if (ocr[2] == 0x01 && ocr[3] == 0xAA) { /* The card can work at vdd range of 2.7-3.6V
      */
            for (tmr = 25000; tmr && send_cmd(ACMD41, 1UL << 30); tmr--) ; /* Wait for leaving
       idle state (ACMD41 with HCS bit) */
            if (tmr && send_cmd(CMD58, 0) == 0) { /* Check CCS bit in the OCR */
                for (n = 0; n < 4; n++) ocr[n] = SPI_read();
                ty = (ocr[0] & 0x40) ? CT_SD2 | CT_BLOCK : CT_SD2; /* SDv2 */
            }
        }
    } else { /* SDSC or MMC */
        if (send_cmd(ACMD41, 0) <= 1) {
            ty = CT_SD1; cmd = ACMD41; /* SDv1 */
        } else {
            ty = CT_MMC; cmd = CMD1; /* MMCv3 */
        }
        for (tmr = 25000; tmr && send_cmd(cmd, 0); tmr--) ; /* Wait for leaving idle state */
        if (!tmr || send_cmd(CMD16, 512) != 0) /* Set R/W block length to 512 */
            ty = 0;
    }
    CardType = ty;
    release_spi();
    if (ty) { /* Initialization succeded */
        Stat &= ~STA_NOINIT; /* Clear STA_NOINIT */
        FCLK_FAST();
    } else { /* Initialization failed */
        power_off();
    }
    return Stat;
}
void SPI_init (u8 sync_mode, u8 bus_mode, u8 smp_phase)
Referenced by disk_initialize().
u8 SPI_read ()
Definition at line 254 of file spi.c.
Referenced by disk_initialize(), DS1306_readn(), enc28j60ReadBuffer(), enc28j60ReadOp(), MCP23S17_read_A(), MCP23S17_read_B(), MCP23S17_read_W(), mrf24j40_long_addr_read(), and mrf24j40_short_addr_read().
                  {
    u8 clear;
    clear = BUFFER; //clear BF
    FLAG = 0;
    BUFFER = 0xFF; // Initiate bus cycle
    while (!FLAG);
    return(BUFFER);
}
u8 SPI_write (unsigned char data_out)
Write the data to be transmitted to the SPIxBUF register. Transmission (and reception) will start as soon as data is written to the SPIxBUF register.
Write the data to be transmitted to the SPIxBUF register. Transmission (and reception) will start as soon as data is written to the SPIxBUF register.
Definition at line 238 of file spi.c.
Referenced by disk_initialize(), DS1306_readn(), DS1306_writen(), enc28j60ReadBuffer(), enc28j60ReadOp(), enc28j60WriteBuffer(), enc28j60WriteOp(), MCP23S17_read_A(), MCP23S17_read_B(), MCP23S17_read_W(), MCP23S17_write_A(), MCP23S17_write_B(), MCP23S17_write_W(), mrf24j40_long_addr_read(), mrf24j40_long_addr_write(), mrf24j40_short_addr_read(), mrf24j40_short_addr_write(), PCD8544_command(), PCD8544_data(), and PCD8544_refresh().
                       {
    u8 clear;
    clear = BUFFER; // clear BF
    FLAG = 0; // enable SPI2 interrupt
    WCOL = 0;
    BUFFER = datax; // send data
    if (WCOL)
        return (1);
    else
        while (!FLAG);
    return(0);
}