/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/1wire.c File Reference
#include <typedef.h>
*
#include <macro.h>
*
#include <delayus.c>
*
#include <digitalp.c>
*
#include <digitalw.c>
*
#include <digitalr.c>
*
Macros
#define __ONEWIRE_C
Functions
u8 OneWireReset (u8)
u8 OneWireReadBit (u8)
void OneWireWriteBit (u8, u8)
u8 OneWireReadByte (u8)
void OneWireWriteByte (u8, u8)
u8 OneWireRead (u8 DQpin)
void OneWireWrite (u8 DQpin, u8 val)
Macro Definition Documentation
#define __ONEWIRE_C
Definition at line 29 of file 1wire.c.
Function Documentation
u8 OneWireRead (u8 DQpin)
Definition at line 109 of file 1wire.c.
References OneWireReadBit().
Referenced by DS18B20Read(), DS18B20ReadMeasure(), and DS18B20ReadRom().
    {
        u8 i, value = 0;
        for (i=0; i<8; i++)
        {
            if (OneWireReadBit(DQpin)) // reads byte in, one bit at a time
            {
                value |= 0x01 << i; // and then shifts it left
            }
        }
        return(value);
    }
u8 OneWireReadBit (u8 DQpin)
Definition at line 92 of file 1wire.c.
References Delayus(), and digitalread().
Referenced by DS18B20GetNext(), and OneWireRead().
    {
        u8 dq;
        OneWireLow(DQpin); // pull DQ line low to start time slot
        //myDelay_us(1); // 1us
        OneWireHigh(DQpin); // allow line to return high
        //myDelay_us(5); // Read within 15uS from start of time slot
        dq = digitalread(DQpin); // get presence signal
        Delayus(50); // wait for rest of timeslot
        return (dq); // return value of DQ line
    }
u8 OneWireReadByte (u8)
u8 OneWireReset (u8 DQpin)
Definition at line 75 of file 1wire.c.
References Delayus(), and digitalread().
Referenced by DS18B20Configure(), DS18B20Find(), DS18B20GetNext(), DS18B20MatchRom(), DS18B20Read(), DS18B20ReadMeasure(), DS18B20ReadRom(), and DS18B20StartMeasure().
    {
        u8 presence;
        OneWireLow(DQpin); // pull DQ line low
        Delayus(480); // leave it low for min. 480us
        OneWireHigh(DQpin); // allow line to return high
        Delayus(60); // takes 15 to 60 us
        presence = digitalread(DQpin); // get presence signal
        Delayus(420); // wait for end of timeslot (960-480-60=420)
        return (presence);
    }
void OneWireWrite (u8 DQpin, u8 val)
Definition at line 147 of file 1wire.c.
References OneWireWriteBit().
Referenced by DS18B20Configure(), DS18B20GetNext(), DS18B20MatchRom(), DS18B20Read(), DS18B20ReadMeasure(), DS18B20ReadRom(), and DS18B20StartMeasure().
    {
        u8 i, temp;
        for (i=0; i<8; i++) // writes byte, one bit at a time
        {
            temp = val >> i; // shifts val right 'i' spaces
            temp &= 0x01; // copy that bit to temp
            OneWireWriteBit(DQpin, temp); // write bit in temp into
        }
    }
void OneWireWriteBit (u8 DQpin, u8 bitval)
Definition at line 126 of file 1wire.c.
References Delayus().
Referenced by DS18B20GetNext(), and OneWireWrite().
    {
        if(bitval == 1)
        {
            OneWireLow(DQpin); // pull DQ line low
            //myDelay_us(5); // for max. 15us
            OneWireHigh(DQpin); // allow line to return high
            Delayus(60);
        }
        else
        {
            OneWireLow(DQpin); // pull DQ line low
            Delayus(60); // for the whole time slot
            OneWireHigh(DQpin); // allow line to return high
        }
    }
void OneWireWriteByte (u8 , u8)