/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/rtcc.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <rtcc.h>
*
#include <bcd.c>
*
#include <system.c>
*
Macros
#define __RTCC__
#define RTCC_Wait() while (RTCCFGbits.RTCSYNC);
Functions
void RTCC_ConvertTime (rtccTime *pTm)
void RTCC_ConvertDate (rtccDate *pDt)
void RTCC_SetWriteEnable (void)
void RTCC_SetWriteDisable (void)
u8 RTCC_IsWriteEnable (void)
void RTCC_Enable (void)
void RTCC_Disable (void)
u8 RTCC_IsEnable (void)
void RTCC_Shutdown (void)
Macro Definition Documentation
#define __RTCC__
Definition at line 31 of file rtcc.c.
#define RTCC_Wait(void) while (RTCCFGbits.RTCSYNC);
Definition at line 56 of file rtcc.c.
Function Documentation
rtccDate RTCC_ConvertDate (rtccDate * pDt)
Definition at line 69 of file rtcc.c.
Referenced by get_fattime().
{
    pDt->dayofweek = bcd2bin(pDt->dayofweek);
    pDt->dayofmonth = bcd2bin(pDt->dayofmonth);
    pDt->month = bcd2bin(pDt->month);
    pDt->year = bcd2bin(pDt->year);
}
rtccTime RTCC_ConvertTime (rtccTime * pTm)
Definition at line 62 of file rtcc.c.
Referenced by get_fattime().
{
    pTm->hours = bcd2bin(pTm->hours);
    pTm->minutes = bcd2bin(pTm->minutes);
    pTm->seconds = bcd2bin(pTm->seconds);
}
void RTCC_Disable (void)
Definition at line 129 of file rtcc.c.
Referenced by RTCC_SetAlarmEnable(), RTCC_SetAlarmInitialPulse(), and RTCC_Shutdown().
{
    RTCC_SetWriteEnable();
    RTCCFGbits.RTCEN = 0;
    RTCC_SetWriteDisable();
}
void RTCC_Enable (void)
Definition at line 116 of file rtcc.c.
Referenced by RTCC_init(), RTCC_Open(), RTCC_SetAlarmEnable(), and RTCC_SetAlarmInitialPulse().
{
    RTCC_SetWriteEnable();
    RTCCFGbits.RTCEN = 1;
    RTCC_SetWriteDisable();
    PIR3bits.RTCCIF = 0;
}
u8 RTCC_IsEnable (void)
Definition at line 140 of file rtcc.c.
{
    return RTCCFGbits.RTCEN != 0;
}
u8 RTCC_IsWriteEnable (void)
Definition at line 105 of file rtcc.c.
{
    return RTCCFGbits.RTCWREN != 0;
}
void RTCC_SetWriteDisable (void)
Definition at line 92 of file rtcc.c.
Referenced by RTCC_Disable(), RTCC_Enable(), RTCC_init(), RTCC_Open(), RTCC_SetCalibration(), RTCC_SetDate(), RTCC_SetTime(), RTCC_SetTimeDate(), and RTCC_Shutdown().
{
// SystemUnlock();
    EECON2 = 0x55; // magic sequence
    EECON2 = 0xAA;
    RTCCFGbits.RTCWREN = 0; // disable write
// SystemLock();
}
void RTCC_SetWriteEnable (void)
Definition at line 83 of file rtcc.c.
Referenced by RTCC_Disable(), RTCC_Enable(), RTCC_SetCalibration(), RTCC_SetDate(), RTCC_SetTime(), and RTCC_SetTimeDate().
{
// SystemUnlock();
    EECON2 = 0x55; // magic sequence
    EECON2 = 0xAA;
    RTCCFGbits.RTCWREN = 1; // enable write
// SystemLock();
}
void RTCC_Shutdown (void)
Definition at line 153 of file rtcc.c.
{
    RTCC_Disable();
    PIR3bits.RTCCIF = 0;
}