/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/graphics.c File Reference
#include <mathlib.c>
*
Macros
#define __GRAPHICS_C
Functions
void drawPixel (u16 x, u16 y)
void drawCircle (u16 x, u16 y, u16 radius)
void fillCircle (u16 x, u16 y, u16 radius)
void drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Macro Definition Documentation
#define __GRAPHICS_C
Definition at line 51 of file graphics.c.
Function Documentation
void drawCircle (u16 x, u16 y, u16 radius)
Definition at line 62 of file graphics.c.
References drawPixel().
Referenced by ILI9325_drawCircle(), and SSD1306_drawCircle().
{
    s16 f = 1 - radius;
    s16 ddF_x = 1;
    s16 ddF_y = -2 * radius;
    s16 x1 = 0;
    s16 y1 = radius;
    drawPixel(x, y + radius);
    drawPixel(x, y - radius);
    drawPixel(x + radius, y);
    drawPixel(x - radius, y);
    while(x1 < y1)
    {
        if(f >= 0)
        {
            y1--;
            ddF_y += 2;
            f += ddF_y;
        }
        x1++;
        ddF_x += 2;
        f += ddF_x;
        drawPixel(x + x1, y + y1);
        drawPixel(x - x1, y + y1);
        drawPixel(x + x1, y - y1);
        drawPixel(x - x1, y - y1);
        drawPixel(x + y1, y + x1);
        drawPixel(x - y1, y + x1);
        drawPixel(x + y1, y - x1);
        drawPixel(x - y1, y - x1);
    }
}
void drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Definition at line 106 of file graphics.c.
References abs(), drawPixel(), swap, x, and y.
Referenced by ILI9325_drawLine(), and SSD1306_drawLine().
{
    s16 steep, t;
    s16 deltax, deltay, error;
    s16 x, y;
    s16 ystep;
    
    // simple clipping
/*
    if ((x0 < 0) || (x0 > HRES)) return;
    if ((x1 < 0) || (x1 > HRES)) return;
    if ((y0 < 0) || (y0 > VRES)) return;
    if ((y1 < 0) || (y1 > VRES)) return;
*/
    
    steep = abs(y1 - y0) > abs(x1 - x0);
    if (steep)
    {
        swap(x0, y0);
        swap(x1, y1);
    }
    if (x0 > x1)
    {
        swap(x0, x1);
        swap(y0, y1);
    }
    deltax = x1 - x0;
    deltay = abs(y1 - y0);
    error = 0;
    y = y0;
    if (y0 < y1) ystep = 1; else ystep = -1;
    for (x = x0; x < x1; x++)
    {
        if (steep)
            drawPixel(y,x);
        else
            drawPixel(x,y);
            
        error += deltay;
        if ((error<<1) >= deltax)
        {
            y += ystep;
            error -= deltax;
        }
    }
}
void drawPixel (u16 x, u16 y)
Definition at line 960 of file ili9325.c.
Referenced by drawBitmap(), drawCircle(), drawLine(), and fillCircle().
{
    ILI9325_drawPixel(x, y);
}
void fillCircle (u16 x, u16 y, u16 radius)
Definition at line 97 of file graphics.c.
References drawPixel().
Referenced by ILI9325_fillCircle(), and SSD1306_fillCircle().
{
    s16 x1, y1;
    for(y1=-radius; y1<=radius; y1++)
        for(x1=-radius; x1<=radius; x1++)
            if(x1*x1+y1*y1 <= radius*radius)
                drawPixel(x+x1, y+y1);
}