/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/__cdc.c File Reference
#include <pic18fregs.h>
*
#include <usb/usb_cdc.h>
*
#include <usb/usb_config.c>
*
#include <usb/picUSB.c>
*
#include <usb/usb_cdc.c>
*
#include <typedef.h>
*
Macros
#define __USBCDC
#define USB_USE_CDC
#define _CDCBUFFERLENGTH_ 64
#define CDCwrite(c) CDCputs(c, 1)
Functions
void CDC_init (void)
void CDC_interrupt (void)
Variables
u8 _cdc_buffer [_CDCBUFFERLENGTH_]
Macro Definition Documentation
#define __USBCDC
Definition at line 21 of file __cdc.c.
#define _CDCBUFFERLENGTH_ 64
Definition at line 43 of file __cdc.c.
#define CDCwrite(c) CDCputs(c, 1)
Definition at line 109 of file __cdc.c.
#define USB_USE_CDC
Definition at line 23 of file __cdc.c.
Function Documentation
void CDC_init (void)
Definition at line 53 of file __cdc.c.
References CONFIGURED, currentConfiguration, Delayms(), DETACHED, deviceState, EnableUSBModule(), ProcessUSBTransactions(), and remoteWakeup.
Referenced by CDCUSBIsConnected().
{
    // Init
    //INTCON=0; // Disable global HP interrupts
    INTCONbits.GIEH = 0;
    INTCONbits.GIEL = 0;
    //INTCON2=0xC0; // set RBPU and INTEDG0 ???
    #ifdef boot2
    UCON=0;
    UCFG=0;
    UEP0=0;UEP1=0;UEP2=0;UEP3=0;UEP4=0;UEP5=0;
    UEP6=0;UEP7=0;UEP8=0;UEP9=0;UEP10=0;UEP11=0;
    UEP12=0;UEP13=0;UEP14=0;UEP15=0;
    
    // and wait 2 seconds
    Delayms(2000);
    #endif
    // Initialize USB for CDC
    UCFG = 0x14; // Enable pullup resistors; full speed mode
    deviceState = DETACHED;
    remoteWakeup = 0x00;
    currentConfiguration = 0x00;
    // Enable USB module
    while(deviceState != CONFIGURED)
    {
      EnableUSBModule();
      ProcessUSBTransactions();
    }
    // Enable Interrupt
    #if defined(__18f25k50) || defined(__18f45k50)
        PIR3bits.USBIF = 0; // clear usb interrupt flag
        PIE3bits.USBIE = 1; // enable usb interrupt
        IPR3bits.USBIP = 1; // high priority interrupt
    #else
        PIR2bits.USBIF = 0; // clear usb interrupt flag
        PIE2bits.USBIE = 1; // enable usb interrupt
        IPR2bits.USBIP = 1; // high priority interrupt
    #endif
    INTCONbits.GIEH = 1; // Enable global HP interrupts
    INTCONbits.GIEL = 1; // Enable global LP interrupts
}
void CDC_interrupt (void)
Definition at line 314 of file __cdc.c.
References ProcessUSBTransactions().
{
    #if defined(__18f25k50) || defined(__18f45k50)
    if(PIR3bits.USBIF)
    {
        PIR3bits.USBIF = 0;
    #else
    if(PIR2bits.USBIF)
    {
        PIR2bits.USBIF = 0;
    #endif
        ProcessUSBTransactions();
        UIRbits.SOFIF = 0;
        UIRbits.URSTIF = 0;
        UEIR = 0;
    }
}
Variable Documentation
u8 _cdc_buffer[_CDCBUFFERLENGTH_]
Definition at line 46 of file __cdc.c.