/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/digitalw.c File Reference
#include <pic18fregs.h>
*
#include <pin.h>
*
#include <digital.h>
*
Macros
#define __DIGITALW__
Functions
void digitalwrite (unsigned char pin, unsigned char state)
Macro Definition Documentation
#define __DIGITALW__
Definition at line 38 of file digitalw.c.
Function Documentation
void digitalwrite (unsigned char pin, unsigned char state)
Definition at line 48 of file digitalw.c.
References pA, pB, pC, pD, pE, and PWM_close().
Referenced by _lcd_begin(), _lcd_pulseEnable(), _lcd_send(), _lcd_write4bits(), _lcd_write8bits(), disableSD(), DS1306_init(), DS1306_Init(), DS1306_readn(), DS1306_writen(), enableSD(), if(), initSD(), Keypad_getKey(), Keypad_initializePins(), lcd_begin(), lcd_pulseEnable(), lcd_send(), lcd_write4bits(), lcd_write8bits(), LedControl_init(), LedControl_spiTransfer(), MCP23S17_init(), MCP23S17_read_A(), MCP23S17_read_B(), MCP23S17_read_W(), MCP23S17_write_A(), MCP23S17_write_B(), MCP23S17_write_W(), modbuss_configure(), modbuss_sendPacket(), Led::off(), Led::on(), PCD8544_command(), PCD8544_data(), PCD8544_refresh(), PCD8544_shiftOut(), readSECTOR(), shiftOut(), SPILoc_Init(), SPILoc_Read(), SPILoc_Write(), ST7565_command(), ST7565_data(), ST7565_init(), ST7565_shiftOut(), Stepper_stepMotor(), Led::toggle(), toggle(), touch_initTouch(), touch_read(), touch_readData(), touch_writeData(), and writeSECTOR().
{
    #if defined(ANALOGWRITE) || defined(__PWM__)
    PWM_close(pin);
    #endif
    switch (port[pin])
    {
        case pA:
            if (state) LATA=LATA | mask[pin];
            else LATA=LATA & (255-mask[pin]);
            break;
        case pB:
            if (state) LATB=LATB | mask[pin];
            else LATB=LATB & (255-mask[pin]);
            break;
        case pC:
            if (state) LATC=LATC | mask[pin];
            else LATC=LATC & (255-mask[pin]);
            break;
        #if defined(PINGUINO4455) || defined(PINGUINO4550) || \
            defined(PINGUINO45K50) || defined(PINGUINO46J50) || \
            defined(PINGUINO47J53A) || defined(PICUNO_EQUO)
        case pD:
            if (state) LATD=LATD | mask[pin];
            else LATD=LATD & (255-mask[pin]);
            break;
        case pE:
            if (state) LATE=LATE | mask[pin];
            else LATE=LATE & (255-mask[pin]);
            break;
        #endif
    }
}