/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/millis.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <oscillator.c>
*
Macros
#define _MILLIS_C_
Functions
void updateMillisReloadValue (void)
void millis_init (void)
u32 millis ()
void millis_interrupt (void)
Variables
volatile u32 _millis
volatile u32 _reload_val
Macro Definition Documentation
#define _MILLIS_C_
Definition at line 8 of file millis.c.
Function Documentation
u32 millis ()
Definition at line 57 of file millis.c.
References _millis.
Referenced by Keypad_getKey(), MCP342x_loop(), MCP342x_startCh(), PID_Compute(), and PID_init().
{
    u32 temp;
    /* Atomic operation for multibyte value */
    INTCONbits.TMR0IE = 0;//INT_DISABLE;
    temp = _millis;
    INTCONbits.TMR0IE = 1;//INT_ENABLE;
    return(temp);
}
void millis_init (void)
Definition at line 27 of file millis.c.
References _millis, _reload_val, high8, low8, and System_getPeripheralFrequency().
{
// intUsed[INT_TMR0] = INT_USED;
    /*
    T0CON = 0x80; // TMR0 on, 16 bits counter, prescaler=2
    INTCON |= 0xA0; // set GIE and TMR0IE
    */
    
    // if Fosc = 48 MHz then Fosc/4 = 12MHz
    // which means 12.E-06 cycles/sec = 12.000 cycles/ms
    // if TMR0 is loaded with 65536 - 12000
    // overload will occur after 12.000 cycles = 1ms
    
    INTCONbits.GIEH = 0; // Disable global HP interrupts
    INTCONbits.GIEL = 0; // Disable global LP interrupts
    T0CON = 0b00001000;//T0_OFF | T0_16BIT | T0_SOURCE_INT | T0_PS_OFF;
    _reload_val = 0xFFFF - System_getPeripheralFrequency() / 1000 ;
    TMR0H = high8(_reload_val);
    TMR0L = low8(_reload_val);
    INTCON2bits.TMR0IP = 1;//INT_HIGH_PRIORITY;
    INTCONbits.TMR0IF = 0;
    INTCONbits.TMR0IE = 1;//INT_ENABLE;
    T0CONbits.TMR0ON = 1;
    INTCONbits.GIEH = 1; // Enable global HP interrupts
    INTCONbits.GIEL = 1; // Enable global LP interrupts
    _millis = 0;
}
void millis_interrupt (void)
Definition at line 68 of file millis.c.
References _millis, _reload_val, high8, and low8.
{
    if (INTCONbits.TMR0IF)
    {
        INTCONbits.TMR0IF = 0;
        TMR0H = high8(_reload_val);
        TMR0L = low8(_reload_val);
        _millis++;
    }
}
void updateMillisReloadValue (void)
Definition at line 19 of file millis.c.
References _reload_val, and System_getPeripheralFrequency().
{
    /* Atomic operation */
    INTCONbits.TMR0IE = 0;//INT_DISABLE;
    _reload_val = 0xFFFF - System_getPeripheralFrequency() / 1000 ;
    INTCONbits.TMR0IE = 1;//INT_ENABLE;
}
Variable Documentation
volatile u32 _millis
Definition at line 16 of file millis.c.
Referenced by micros(), millis(), millis_init(), millis_interrupt(), and Tmr2Interrupt().
volatile u32 _reload_val
Definition at line 17 of file millis.c.
Referenced by millis_init(), millis_interrupt(), and updateMillisReloadValue().