/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/pcf8574.h File Reference
#include <typedef.h>
*
#include <macro.h>
*
Functions
void PCF8574_init ()
u8 PCF8574_write (u8, u8)
u8 PCF8574_read (u8)
Function Documentation
void PCF8574_init (void)
Init. I2C bus
---------- PCF8574_init
---------- RAZ de la variable d'echange entre Pic et PCF8574
Definition at line 69 of file pcf8574.c.
References I2C_100KHZ, I2C_init(), I2C_MASTER_MODE, and PCF8574_t::val.
{
    // PCF8574 SCL clock frequency = 100 kHz max.
    I2C_init(I2C_MASTER_MODE, I2C_100KHZ);
}
u8 PCF8574_read (u8 address)
Read a byte from the PCF8574
Definition at line 100 of file pcf8574.c.
References I2C_get().
{
    return I2C_get(address);
}
u8 PCF8574_write (u8 address, u8 value)
Write a byte on the PCF8574
---------- PCF8574_write
---------- Ecriture d'un octet sur le port du PCF8574 via le bus I2C In Master Transmitter mode, the first byte transmitted contains the slave address of the receiving device (seven bits) and the Read/Write (R/W) bit. In this case, the R/W bit will be logic ‘0’. Serial data is transmitted eight bits at a time. After each byte is transmitted, an Acknowledge bit is received. Start and Stop conditions are output to indicate the beginning and the end of a serial transfer.
Definition at line 80 of file pcf8574.c.
References I2C_start(), I2C_stop(), I2C_WRITE, I2C_write(), and I2C_writechar().
{
    u8 r=0;
    I2C_start();
    if (I2C_writechar(address | I2C_WRITE))
    {
        r = I2C_writechar(value);
    }
    I2C_stop();
    return r;
    //return I2C_send(address, value);
}