/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/SSD1306.c File Reference
#include <SSD1306.h>
*
#include <logo/pinguino128x32.h>
*
#include <digitalw.c>
*
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <delayms.c>
*
#include <delayus.c>
*
#include <graphics.c>
*
Macros
#define __SSD1306_C
Functions
void SSD1306_sendCommand (u8 val)
void SSD1306_sendData (u8 val)
void SSD1306_displayOff ()
void SSD1306_displayOn ()
void SSD1306_sleep ()
void SSD1306_wake ()
void SSD1306_setInverse (u8 value)
void SSD1306_setDisplayOffset (u8 value)
void SSD1306_setContrast (u8 value)
void SSD1306_setDisplayStartLine (u8 value)
void SSD1306_setSegmentRemap (u8 value)
void SSD1306_setMultiplexRatio (u8 value)
void SSD1306_setComOutputScanDirection (u8 value)
void SSD1306_setComPinsHardwareConfiguration (u8 sequential, u8 lr_remap)
void SSD1306_pamSetStartAddress (u8 address)
void SSD1306_setMemoryAddressingMode (u8 mode)
void SSD1306_hvSetColumnAddress (u8 start, u8 end)
void SSD1306_hvSetPageAddress (u8 start, u8 end)
void SSD1306_pamSetPageStart (u8 address)
void SSD1306_setDisplayClockRatioAndFrequency (u8 ratio, u8 frequency)
void SSD1306_setPrechargePeriod (u8 phase1, u8 phase2)
void SSD1306_setVcomhDeselectLevel (u8 level)
void SSD1306_nop ()
void SSD1306_setChargePumpEnable (u8 enable)
digitalwrite (res, LOW)
Delayus (50)
digitalwrite (res, HIGH)
Delayms (100)
SSD1306_setDisplayClockRatioAndFrequency (0, 8)
SSD1306_setMultiplexRatio (0x3F)
SSD1306_setPrechargePeriod (0xF, 0x01)
SSD1306_setDisplayOffset (0)
SSD1306_setDisplayStartLine (0)
SSD1306_setChargePumpEnable (1)
SSD1306_setMemoryAddressingMode (0)
SSD1306_setSegmentRemap (1)
SSD1306_setComOutputScanDirection (1)
SSD1306_setComPinsHardwareConfiguration (1, 0)
SSD1306_setContrast (0xFF)
SSD1306_setVcomhDeselectLevel (1)
SSD1306_setInverse (0)
SSD1306_hvSetColumnAddress (0, 127)
SSD1306_hvSetPageAddress (0, 7)
SSD1306_pamSetStartAddress (0)
SSD1306_pamSetPageStart (0)
void SSD1306_refresh ()
void SSD1306_clearScreen (void)
void SSD1306_startHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval)
void SSD1306_startVerticalAndHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval, u8 vertical_offset)
void SSD1306_stopScroll ()
void SSD1306_scrollRight ()
void SSD1306_scrollLeft ()
void SSD1306_scrollUp ()
void SSD1306_scrollDown ()
void SSD1306_setFont (u8 *font)
void SSD1306_printChar (u8 c)
void SSD1306_setCursor (u8 x, u8 y)
void SSD1306_drawPixel (u8 x, u8 y)
void SSD1306_clearPixel (u8 x, u8 y)
u8 SSD1306_getColor (u8 x, u8 y)
void drawPixel (u16 x, u16 y)
void SSD1306_drawCircle (u16 x, u16 y, u16 radius)
void SSD1306_fillCircle (u16 x, u16 y, u16 radius)
void SSD1306_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Variables
u8 * SSD1306_buffer = logo
SSD1306 cursor x = 0
SSD1306 cursor y = 0
SSD1306 cursor page = 0
SSD1306 screen startx = 0
SSD1306 screen starty = 0
SSD1306 screen endx = DISPLAY_WIDTH - 1
SSD1306 screen endy = DISPLAY_HEIGHT - 1
SSD1306 screen width = DISPLAY_WIDTH
SSD1306 screen height = DISPLAY_HEIGHT
Macro Definition Documentation
#define __SSD1306_C
Pin Assignment
1 VCC | 2 GND 3 CS | 4 RES 5 D/C | 6 R/W 7 E/RD | 8 D0 9 D1 | 10 D2 11 D3 | 12 D4 13 D5 | 14 D6 15 D7 | 16 NC Bus Interface
    I2C     6800    8080    4-SPI   3-SPI
 BS0 0 0 0 0 1 BS1 1 0 1 0 0 BS2 0 1 1 0 0
Definition at line 55 of file SSD1306.c.
Function Documentation
Delayms (100)
Referenced by SSD1306_init().
Delayus (50)
Referenced by SSD1306_init().
digitalwrite (res , LOW)
reset device When RES input is low, the chip is initialized with the following status:
Display is OFF.
128x64 MUX Display Mode.
Normal segment and display data column address and row address mapping (SEG0 mapped to address 00h and COM0 mapped to address 00h).
Shift register data clear in serial interface.
Display start line is set at display RAM address 0.
Column address counter is set at 0.
Normal scan direction of the COM outputs.
Contrast control register is set at 7Fh.
Normal display mode (Equivalent to A4h command)
digitalwrite (res , HIGH)
void drawPixel (u16 x, u16 y)
Definition at line 943 of file SSD1306.c.
References SSD1306_drawPixel().
{
    SSD1306_drawPixel(x, y);
}
void SSD1306_clearPixel (u8 x, u8 y)
Definition at line 883 of file SSD1306.c.
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    
    SSD1306_buffer[x + (y / DISPLAY_ROWS) *
      DISPLAY_WIDTH] &= ~(1 << (y % DISPLAY_ROWS));
}
void SSD1306_clearScreen (void)
Clear the display
Definition at line 500 of file SSD1306.c.
{
    u16 i;
    for (i = 0; i < DISPLAY_SIZE; i++)
        SSD1306_buffer[i] = 0;
        
    SSD1306.cursor.x = 0;
    SSD1306.cursor.y = 0;
    SSD1306.cursor.page = 0;
}
SSD1306_displayOff ()
Basic functions (TODO : replace functions with #define)
Definition at line 239 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xAE);
}
SSD1306_displayOn ()
Definition at line 244 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xAF);
}
void SSD1306_drawCircle (u16 x, u16 y, u16 radius)
Definition at line 948 of file SSD1306.c.
{
    drawCircle(x, y, radius);
}
void SSD1306_drawLine (u16 x0, u16 y0, u16 x1, u16 y1)
Definition at line 958 of file SSD1306.c.
{
    drawLine(x0, y0, x1, y1);
}
void SSD1306_drawPixel (u8 x, u8 y)
Definition at line 876 of file SSD1306.c.
Referenced by drawPixel().
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    SSD1306_buffer[x + (y / DISPLAY_ROWS) *
      DISPLAY_WIDTH] |= 1 << (y % DISPLAY_ROWS);
}
void SSD1306_fillCircle (u16 x, u16 y, u16 radius)
Definition at line 953 of file SSD1306.c.
{
    fillCircle(x, y, radius);
}
u8 SSD1306_getColor (u8 x, u8 y)
Definition at line 900 of file SSD1306.c.
{
    u8 column,temp,bit_mask;//page;
    unsigned int page;
    u8* GDptr = SSD1306_bufferptr;
   
    // Convert coordinates
    column = x & DISPLAY_WIDTH_MASK; // 0-128
    //page = (y>>DISPLAY_ROW_BITS)&DISPLAY_ROW_MASK; // 0-8
    temp = y & DISPLAY_ROW_MASK;
    bit_mask = 1<<temp;
    //GDptr+= column+(DISPLAY_WIDTH*page);
    // Optimise
    page = (y << (DISPLAY_WIDTH_BITS - DISPLAY_ROW_BITS)); // 0-8 * 128
    GDptr += column+page;
    // Set the bit
    if (*GDptr & bit_mask) // Pixel on
    {
            return 1;
    }
    else // Pixel off
    {
            return 0;
    }
}
void SSD1306_hvSetColumnAddress (u8 start, u8 end)
Definition at line 318 of file SSD1306.c.
Referenced by SSD1306_init(), and SSD1306_refresh().
{
    SSD1306_sendCommand(0x21);
    SSD1306_sendCommand(start & DISPLAY_WIDTH_MASK);
    SSD1306_sendCommand(end & DISPLAY_WIDTH_MASK);
}
SSD1306_hvSetColumnAddress (0 , 127)
void SSD1306_hvSetPageAddress (u8 start, u8 end)
Definition at line 325 of file SSD1306.c.
Referenced by SSD1306_init(), and SSD1306_refresh().
{
    SSD1306_sendCommand(0x22);
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
}
SSD1306_hvSetPageAddress (0 , 7)
void SSD1306_nop ()
Definition at line 355 of file SSD1306.c.
{
    SSD1306_sendCommand(0xE3);
}
void SSD1306_pamSetPageStart (u8 address)
Definition at line 332 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xB0 | (address & DISPLAY_ROW_MASK));
}
SSD1306_pamSetPageStart (0)
void SSD1306_pamSetStartAddress (u8 address)
Definition at line 303 of file SSD1306.c.
Referenced by SSD1306_init().
{
    // "Set Lower Column Start Address for Page Addressing Mode"
    SSD1306_sendCommand(address & 0x0F);
    // "Set Higher Column Start Address for Page Addressing Mode"
    SSD1306_sendCommand((address << 4) & 0x0F);
}
SSD1306_pamSetStartAddress (0)
void SSD1306_printChar (u8 c)
Definition at line 662 of file SSD1306.c.
{
    u8 b;
    while (SSD1306.cursor.x >= (DISPLAY_WIDTH /
      SSD1306.font.width))
    {
        SSD1306.cursor.x -= (DISPLAY_WIDTH / SSD1306.
      font.width);
        SSD1306.cursor.y++;
    }
    while (SSD1306.cursor.y > 7) // replace by SSD1306.font.height ???
    {
        SSD1306_scrollUp();
    }
    switch (c)
    {
        case '\n':
            SSD1306.cursor.y++;
            break;
            
        case '\r':
            SSD1306.cursor.x = 0;
            break;
            
        case '\t':
            SSD1306.cursor.x = (SSD1306.cursor.x + 4) % 4;
            break;
            
        default:
            for (b = 0; b < SSD1306.font.width; b++)
            {
                SSD1306_buffer[SSD1306.cursor.x *
      SSD1306.font.width + SSD1306.cursor.y * 128 + b] =
                    SSD1306.font.address[2 + (c - 32) *
      SSD1306.font.width + b];
            }
        
        SSD1306.cursor.x++;
    }
}
void SSD1306_refresh ()
Update the display
Definition at line 485 of file SSD1306.c.
{
    u16 i;
    SSD1306_hvSetColumnAddress(0, DISPLAY_WIDTH-1);
    SSD1306_hvSetPageAddress(0, DISPLAY_ROWS-1);
    for (i = 0; i < DISPLAY_SIZE; i++)
        SSD1306_sendData(SSD1306_buffer[i]);
}
void SSD1306_scrollDown ()
Definition at line 635 of file SSD1306.c.
{
    SSD1306_startVerticalAndHorizontalScroll(
      SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL, 0, 64, 0, 1);
}
void SSD1306_scrollLeft ()
Definition at line 606 of file SSD1306.c.
{
    SSD1306_startHorizontalScroll(
      SSD1306_LEFT_HORIZONTAL_SCROLL, 0, 7, 2);
}
void SSD1306_scrollRight ()
Definition at line 599 of file SSD1306.c.
{
    SSD1306_startHorizontalScroll(
      SSD1306_RIGHT_HORIZONTAL_SCROLL, 0, 7, 2);
}
void SSD1306_scrollUp ()
Definition at line 613 of file SSD1306.c.
Referenced by SSD1306_printChar().
{
    u8 x, y;
    for (y = 1; y <= 7; y++)
    {
        for (x = 0; x < 128; x++)
        {
            SSD1306_buffer[x + 128 * (y - 1)] = SSD1306_buffer[x + 128 * y];
        }
    }
    for (x = 0; x < 128; x++)
    {
        SSD1306_buffer[x + 128 * 7] = 0;
    }
    SSD1306.cursor.y--;
}
void SSD1306_sendCommand (u8 val)
Core functions
The parallel 6800-series interface consists of : 8 bi-directional data pins (D[7:0]) R/W#, D/C#, E and CS#. A LOW in R/W# indicates WRITE operation A HIGH in R/W# indicates READ operation. A LOW in D/C# indicates COMMAND read/write A HIGH in D/C# indicates DATA read/write. The E input serves as data latch signal while CS# is LOW. Data is latched at the falling edge of E signal.
The parallel 8080-series interface consists of : 8 bi-directional data pins (DB[7:0]) RD#, WR#, DC# and CS#. A LOW in DC# indicates COMMAND read/write A HIGH in DC# indicates DATA read/write. A rising edge of RD# input serves as a data READ latch signal while CS# is kept LOW. A rising edge of WR# input serves as a data/command WRITE latch signal while CS# is kept LOW.
Definition at line 135 of file SSD1306.c.
Referenced by SSD1306_displayOff(), SSD1306_displayOn(), SSD1306_hvSetColumnAddress(), SSD1306_hvSetPageAddress(), SSD1306_nop(), SSD1306_pamSetPageStart(), SSD1306_pamSetStartAddress(), SSD1306_setChargePumpEnable(), SSD1306_setComOutputScanDirection(), SSD1306_setComPinsHardwareConfiguration(), SSD1306_setContrast(), SSD1306_setDisplayClockRatioAndFrequency(), SSD1306_setDisplayOffset(), SSD1306_setDisplayStartLine(), SSD1306_setInverse(), SSD1306_setMemoryAddressingMode(), SSD1306_setMultiplexRatio(), SSD1306_setPrechargePeriod(), SSD1306_setSegmentRemap(), SSD1306_setVcomhDeselectLevel(), SSD1306_sleep(), SSD1306_startHorizontalScroll(), SSD1306_startVerticalAndHorizontalScroll(), SSD1306_stopScroll(), and SSD1306_wake().
{
    #if (DISPLAY & SSD1306_PMP)
        #if ((DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080))
            PMP_wait(); // wait for PMP to be available
            PMADDRH = 0;
            PMADDRL = 0;
            PMDIN1L = val;
            
        #else
            #error " --------------------------------------- "
            #error " The Parallel Port can only drive the "
            #error " 6800 or 8080 parallel interface. "
            #error " --------------------------------------- "
        #endif
    #else
        #if (DISPLAY & SSD1306_8080)
            Low(CS); // Chip select
            Low(DC); // COMMAND read/write
            Low(WR);
            DATA = val; // WR should stay low at least 60ns
            High(WR); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #elif (DISPLAY & SSD1306_6800)
            Low(CS); // Chip select
            Low(WR); // WRITE
            Low(DC); // COMMAND
            High(E);
            DATA = val; // WR should stay low at least 60ns
            Low(E); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #endif
    #endif
}
void SSD1306_sendData (u8 val)
Definition at line 185 of file SSD1306.c.
Referenced by SSD1306_refresh().
{
    #if (DISPLAY & SSD1306_PMP)
        #if ((DISPLAY & SSD1306_6800) || (DISPLAY & SSD1306_8080))
            PMP_wait(); // wait for PMP to be available
            PMADDRH = 0; // High8(DC);
            PMADDRL = DC; // low8(DC);
            PMDIN1L = val;
            
        #else
            #error " --------------------------------------- "
            #error " The Parallel Port can only drive the "
            #error " 6800 or 8080 parallel interface. "
            #error " --------------------------------------- "
        #endif
    #else
        #if (DISPLAY & SSD1306_8080)
            Low(CS); // Chip select
            High(DC); // DATA read/write
            Low(WR);
            DATA = val; // WR should stay low at least 60ns
            High(WR); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #elif (DISPLAY & SSD1306_6800)
            Low(CS); // Chip select
            Low(WR); // WRITE
            High(DC); // DATA
            High(E);
            DATA = val; // WR should stay low at least 60ns
            Low(E); // A rising edge of WR enables Write mode
            High(CS); // Chip deselected
        #endif
    #endif
}
void SSD1306_setChargePumpEnable (u8 enable)
Definition at line 360 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x8D);
    SSD1306_sendCommand(enable ? 0x14 : 0x10);
}
SSD1306_setChargePumpEnable (1)
void SSD1306_setComOutputScanDirection (u8 value)
Definition at line 292 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(value ? 0xC8 : 0xC0);
}
SSD1306_setComOutputScanDirection (1)
void SSD1306_setComPinsHardwareConfiguration (u8 sequential, u8 lr_remap)
Definition at line 297 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xDA);
    SSD1306_sendCommand(0x02 | ((sequential & 1) << 4) | ((lr_remap & 1) << 5));
}
SSD1306_setComPinsHardwareConfiguration (1 , 0)
void SSD1306_setContrast (u8 value)
Definition at line 270 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x81);
    SSD1306_sendCommand(value);
}
SSD1306_setContrast (0xFF)
void SSD1306_setCursor (u8 x, u8 y)
Graphic functions
Definition at line 858 of file SSD1306.c.
{
    if (x >= DISPLAY_WIDTH || y >= (DISPLAY_HEIGHT)) return;
    SSD1306.cursor.x = x;
    SSD1306.cursor.y = y;
    SSD1306.cursor.page = x & DISPLAY_ROW_MASK; // current page
}
void SSD1306_setDisplayClockRatioAndFrequency (u8 ratio, u8 frequency)
Definition at line 337 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xD5);
    SSD1306_sendCommand((ratio & 0x0F) | ((frequency & 0x0F) << 4));
}
SSD1306_setDisplayClockRatioAndFrequency (0 , 8)
void SSD1306_setDisplayOffset (u8 value)
Definition at line 264 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xD3);
    SSD1306_sendCommand(value & 0x3F);
}
SSD1306_setDisplayOffset (0)
void SSD1306_setDisplayStartLine (u8 value)
Definition at line 276 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x40 | value);
}
SSD1306_setDisplayStartLine (0)
void SSD1306_setFont (u8 * font)
Print functions
Definition at line 644 of file SSD1306.c.
References font_t::address, font, lcd_t::font, font_t::height, SSD1306, and font_t::width.
{
    SSD1306.font.address = font;
    //SSD1306.font.width = SSD1306_getFontWidth()+1;
    //SSD1306.font.height = SSD1306_getFontHeight();
    SSD1306.font.width = font[0];
    SSD1306.font.height = font[1];
}
void SSD1306_setInverse (u8 value)
Definition at line 259 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(value ? 0xA7 : 0xA6);
}
SSD1306_setInverse (0)
void SSD1306_setMemoryAddressingMode (u8 mode)
Definition at line 312 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0x20);
    SSD1306_sendCommand(mode & 0x3);
}
SSD1306_setMemoryAddressingMode (0)
void SSD1306_setMultiplexRatio (u8 value)
Definition at line 286 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xA8);
    SSD1306_sendCommand(value & 0x3F);
}
SSD1306_setMultiplexRatio (0x3F)
void SSD1306_setPrechargePeriod (u8 phase1, u8 phase2)
Definition at line 343 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xD9);
    SSD1306_sendCommand((phase1 & 0x0F) | ((phase2 & 0x0F) << 4));
}
SSD1306_setPrechargePeriod (0xF , 0x01)
void SSD1306_setSegmentRemap (u8 value)
Definition at line 281 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(value ? 0xA1 : 0xA0);
}
SSD1306_setSegmentRemap (1)
void SSD1306_setVcomhDeselectLevel (u8 level)
Definition at line 349 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xDB);
    SSD1306_sendCommand((level & 0x03) << 4);
}
SSD1306_setVcomhDeselectLevel (1)
void SSD1306_sleep ()
Definition at line 249 of file SSD1306.c.
{
    SSD1306_sendCommand(0xAE);
}
void SSD1306_startHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval)
Scroll functions
Definition at line 516 of file SSD1306.c.
Referenced by SSD1306_scrollLeft(), and SSD1306_scrollRight().
{
    // Before issuing this command the horizontal scroll must be deactivated (2Eh).
    // Otherwise, RAM content may be corrupted.
    // RB : this datasheet recommandation doesn't work
    //SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
    SSD1306_sendCommand(direction);// ? 0x27 : 0x26);
    // Dummy byte (???)
    SSD1306_sendCommand(0x00);
    // Start page
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    // Time interval between each scroll step
    switch (interval)
    {
        case 2: SSD1306_sendCommand(0x07); break; // 111b
        case 3: SSD1306_sendCommand(0x04); break; // 100b
        case 4: SSD1306_sendCommand(0x05); break; // 101b
        case 5: SSD1306_sendCommand(0x00); break; // 000b
        case 25: SSD1306_sendCommand(0x06); break; // 110b
        case 64: SSD1306_sendCommand(0x01); break; // 001b
        case 128: SSD1306_sendCommand(0x02); break; // 010b
        case 256: SSD1306_sendCommand(0x03); break; // 011b
        default: SSD1306_sendCommand(0x07); break; // default to 2 frame interval
    }
    
    // End page
    //SSD1306_sendCommand(0x00);
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
    // ???
    SSD1306_sendCommand(0x00);
    SSD1306_sendCommand(0xFF);
    // activate scroll
    SSD1306_sendCommand(SSD1306_ACTIVATE_SCROLL);
}
void SSD1306_startVerticalAndHorizontalScroll (u8 direction, u8 start, u8 end, u16 interval, u8 vertical_offset)
Definition at line 555 of file SSD1306.c.
Referenced by SSD1306_scrollDown().
{
    // Before issuing this command the horizontal scroll must be deactivated (2Eh).
    // Otherwise, RAM content may be corrupted.
    // RB : this datasheet recommandation doesn't work
    //SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
    SSD1306_sendCommand(direction); // ? 0x2A : 0x29);
    // Dummy byte (???)
    SSD1306_sendCommand(0x00);
    // Start page
    SSD1306_sendCommand(start & DISPLAY_ROW_MASK);
    // Time interval between each scroll step
    switch (interval)
    {
        case 2: SSD1306_sendCommand(0x07); break; // 111b
        case 3: SSD1306_sendCommand(0x04); break; // 100b
        case 4: SSD1306_sendCommand(0x05); break; // 101b
        case 5: SSD1306_sendCommand(0x00); break; // 000b
        case 25: SSD1306_sendCommand(0x06); break; // 110b
        case 64: SSD1306_sendCommand(0x01); break; // 001b
        case 128: SSD1306_sendCommand(0x02); break; // 010b
        case 256: SSD1306_sendCommand(0x03); break; // 011b
        default: SSD1306_sendCommand(0x07); break; // default to 2 frame interval
    }
    // End page
    SSD1306_sendCommand(end & DISPLAY_ROW_MASK);
    SSD1306_sendCommand(vertical_offset);
    // activate scroll
    SSD1306_sendCommand(SSD1306_ACTIVATE_SCROLL);
}
void SSD1306_stopScroll ()
Definition at line 591 of file SSD1306.c.
{
    // all scroll configurations are removed from the display when executing this command.
    SSD1306_sendCommand(SSD1306_DEACTIVATE_SCROLL);
}
SSD1306_wake ()
Definition at line 254 of file SSD1306.c.
Referenced by SSD1306_init().
{
    SSD1306_sendCommand(0xAF);
}
Variable Documentation
SSD1306 screen endx = DISPLAY_WIDTH - 1
Definition at line 429 of file SSD1306.c.
SSD1306 screen endy = DISPLAY_HEIGHT - 1
Definition at line 430 of file SSD1306.c.
SSD1306 screen height = DISPLAY_HEIGHT
Definition at line 432 of file SSD1306.c.
SSD1306 cursor page = 0
Definition at line 426 of file SSD1306.c.
Referenced by ClearScreen(), PutChar(), and SSD1306_getColor().
u8* SSD1306_buffer = logo
Globals
Definition at line 108 of file SSD1306.c.
Referenced by SSD1306_clearPixel(), SSD1306_clearScreen(), SSD1306_drawPixel(), SSD1306_printChar(), SSD1306_refresh(), and SSD1306_scrollUp().
SSD1306 screen startx = 0
Definition at line 427 of file SSD1306.c.
SSD1306 screen starty = 0
Definition at line 428 of file SSD1306.c.
SSD1306 screen width = DISPLAY_WIDTH
Definition at line 431 of file SSD1306.c.
Referenced by CharWidth(), DrawBitmap(), FillRect(), InvertRect(), pulseIn(), PutChar(), and StringWidth().
SSD1306 cursor x = 0
Definition at line 424 of file SSD1306.c.
Referenced by SSD1306_scrollUp(), and SSD1306_setCursor().
SSD1306 cursor y = 0
Definition at line 425 of file SSD1306.c.
Referenced by SSD1306_scrollUp(), and SSD1306_setCursor().