/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/i2c.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <macro.h>
*
#include <const.h>
*
#include <stdio.c>
*
#include <stdarg.h>
*
Macros
#define __PINGUINO_I2C_C
#define __I2C__
#define I2C1 1
#define I2C2 2
#define I2C_WRITE 0
#define I2C_READ 1
#define I2C_MASTER_MODE 0
#define I2C_SLAVE_MODE 1
#define I2C_SLEW_OFF 0
#define I2C_SLEW_ON 1
#define I2C_100KHZ 100
#define I2C_400KHZ 400
#define I2C_1MHZ 1000
#define I2C_idle() while (((SSPCON2 & 0x1F) > 0) | (SSPSTATbits.R_W))
Functions
void I2C_master (u16)
PROTOTYPES.
void I2C_slave (u16)
void I2C_init (u8, u16)
u8 I2C_write (u8)
u8 I2C_read ()
void I2C_wait ()
void I2C_start ()
void I2C_stop ()
void I2C_restart ()
void I2C_sendNack ()
void I2C_sendAck ()
Macro Definition Documentation
#define __I2C__
Definition at line 53 of file i2c.c.
#define __PINGUINO_I2C_C
Definition at line 51 of file i2c.c.
#define I2C1 1
Definition at line 70 of file i2c.c.
Referenced by I2C1_get(), I2C1_init(), I2C1_readchar(), I2C1_readcharAck(), I2C1_restart(), I2C1_send(), I2C1_sendAck(), I2C1_sendID(), I2C1_sendNack(), I2C1_start(), I2C1_stop(), I2C1_wait(), I2C1_write(), I2C1_writechar(), lcdi2c_backlight(), lcdi2c_init(), and lcdi2c_noBacklight().
#define I2C2 2
Definition at line 71 of file i2c.c.
Referenced by I2C2_get(), I2C2_init(), I2C2_readchar(), I2C2_readcharAck(), I2C2_restart(), I2C2_send(), I2C2_sendAck(), I2C2_sendID(), I2C2_sendNack(), I2C2_start(), I2C2_stop(), I2C2_wait(), I2C2_write(), and I2C2_writechar().
#define I2C_100KHZ 100
Definition at line 82 of file i2c.c.
Referenced by I2C1_init(), I2C_init(), lcdi2c_init(), and PCF8574_init().
#define I2C_1MHZ 1000
Definition at line 84 of file i2c.c.
Referenced by I2C_init(), and lcdi2c_init().
#define I2C_400KHZ 400
Definition at line 83 of file i2c.c.
Referenced by I2C_init().
#define I2C_idle() while (((SSPCON2 & 0x1F) > 0) | (SSPSTATbits.R_W))
Definition at line 86 of file i2c.c.
Referenced by I2C_read(), I2C_restart(), I2C_sendAck(), I2C_sendNack(), I2C_start(), I2C_stop(), and I2C_write().
#define I2C_MASTER_MODE 0
Definition at line 76 of file i2c.c.
Referenced by I2C1_init(), I2C2_init(), I2C_init(), I2C_master(), lcdi2c_init(), and PCF8574_init().
#define I2C_READ 1
Definition at line 75 of file i2c.c.
#define I2C_SLAVE_MODE 1
Definition at line 77 of file i2c.c.
Referenced by I2C_init(), and I2C_slave().
#define I2C_SLEW_OFF 0
Definition at line 78 of file i2c.c.
Referenced by I2C2_init().
#define I2C_SLEW_ON 1
Definition at line 79 of file i2c.c.
#define I2C_WRITE 0
Definition at line 74 of file i2c.c.
Referenced by PCF8574_write().
Function Documentation
void I2C_init (u8 mode, u16 sora)
Definition at line 167 of file i2c.c.
References I2C_100KHZ, I2C_1MHZ, I2C_400KHZ, I2C_MASTER_MODE, I2C_SLAVE_MODE, and INPUT.
Referenced by I2C1_init(), I2C2_init(), I2C_master(), I2C_slave(), lcdi2c_init(), and PCF8574_init().
{
    // In Slave mode, the SCL and SDA pins must be configured as inputs
    #if defined(__18f26j50) || defined(__18f46j50) || \
        defined(__18f27j53) || defined(__18f47j53)
    TRISBbits.TRISB5 = INPUT; // SDA = INPUT
    TRISBbits.TRISB4 = INPUT; // SCL = INPUT
    #else
    TRISBbits.TRISB0 = INPUT; // SDA = INPUT
    TRISBbits.TRISB1 = INPUT; // SCL = INPUT
    #endif
    switch (mode)
    {
        case I2C_SLAVE_MODE:
            //intUsed[INT_SSP] = INT_USED;
            // Enabling interrupts (peripheral & general)
            //INTCONbits.PEIE=1;
            //INTCONbits.GIE=1;
            if (sora > 0x80)
                SSPCON1= 0b00101111; // Slave mode, 10-bit address with Start and Stop bit interrupts
       enabled
            else
                SSPCON1= 0b00101110; // 00101110Slave mode, 7-bit address with Start and Stop bit
       interrupts enabled
    /*------------------------------------------------------------------------*/
            SSPADD= sora; // Slave 7-bit address
            // TODO // Slave 10-bit address
    /*------------------------------------------------------------------------*/
            break;
        case I2C_MASTER_MODE:
        default:// I2C_MASTER_MODE
            SSPCON1= 0b00101000; // Master Mode, clock = FOSC/(4 * (SSPADD + 1))
            // datasheet p208
            switch (sora)
            {
                case I2C_1MHZ:
                    // SMP = 1 = Slew rate control disabled for Standard Speed mode (100 kHz and 1 MHz)
                    SSPSTATbits.SMP = 1; // Slew Mode Off
                    SSPADD= 11; // 1MHz = FOSC/(4 * (SSPADD + 1))
                    break; // SSPADD = 48 000 / (4*1000) - 1
                    
                case I2C_400KHZ:
                    // SMP = 0 = Slew rate control enabled for High-Speed mode (400 kHz)
                    SSPSTATbits.SMP = 0; // Slew Mode On
                    SSPADD= 29; // 400kHz = FOSC/(4 * (SSPADD + 1))
                    break; // SSPADD = 48 000 / (4*400) - 1
                case I2C_100KHZ:
                default:
                    // SMP = 1 = Slew rate control disabled for Standard Speed mode (100 kHz and 1 MHz)
                    SSPSTATbits.SMP = 1; // Slew Mode Off
                    SSPADD= 119; // 100kHz = FOSC/(4 * (SSPADD + 1))
                    break; // SSPADD = 48 000 / (4*100) - 1
            }
            break;
    }
    SSPCON2= 0;
    PIR1bits.SSPIF = 0; // MSSP Interrupt Flag
    PIR2bits.BCLIF = 0; // Bus Collision Interrupt Flag
    //Delayms(1000);
}
void I2C_master (u16 speed)
PROTOTYPES.
Definition at line 144 of file i2c.c.
References I2C_init(), and I2C_MASTER_MODE.
Referenced by I2C_begin().
{
    I2C_init(I2C_MASTER_MODE, speed);
}
u8 I2C_read ()
Definition at line 290 of file i2c.c.
References I2C_idle.
Referenced by I2C_readFrom().
{
//rz u8 r;
    
    I2C_idle(); // Wait the MSSP module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.RCEN = 1; // Initiate reception of byte
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
    PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    
//rz r = SSPBUF;
    
    while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
    PIR1bits.SSPIF=0; // ROlf clear SSPIF
//rz r = SSPBUF;
    PIR1bits.SSPIF=0; // ROlf clear SSPIF
    //while (!SSPSTATbits.BF); // Wait until buffer is full
    //while (SSPCON2bits.RCEN); // Wait until RCEN is cleared
//rz return r;
    return SSPBUF;
}
void I2C_restart ()
Definition at line 418 of file i2c.c.
References I2C_idle.
Referenced by I2C1_restart(), I2C2_restart(), I2C_get(), I2C_readFrom(), and I2C_sendID().
{
    I2C_idle(); // Wait module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.RSEN = 1; // Send restart bit
    while (SSPCON2bits.RSEN); // Wait until RSEN is cleared
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_sendAck ()
Definition at line 434 of file i2c.c.
References I2C_idle.
Referenced by I2C1_sendAck(), I2C2_sendAck(), and I2C_readFrom().
{
    I2C_idle(); // Wait module is inactive
    SSPCON2bits.ACKDT = 0; // We want an Ack
    PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.ACKEN = 1; // Send it now
    while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_sendNack ()
Definition at line 450 of file i2c.c.
References I2C_idle.
Referenced by I2C1_sendNack(), I2C2_sendNack(), I2C_get(), and I2C_readFrom().
{
    I2C_idle(); // Wait module is inactive
    SSPCON2bits.ACKDT = 1; // We want a No Ack
    PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.ACKEN = 1; // Send it now
    while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_slave (u16 DeviceID)
Definition at line 149 of file i2c.c.
References I2C_init(), and I2C_SLAVE_MODE.
{
    I2C_init(I2C_SLAVE_MODE, DeviceID);
}
void I2C_start ()
Definition at line 386 of file i2c.c.
References I2C_idle.
Referenced by I2C1_start(), I2C2_start(), I2C_readFrom(), I2C_send(), I2C_sendID(), I2C_writeTo(), and PCF8574_write().
{
    I2C_idle(); // Wait module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.SEN = 1; // Send start bit
    while (SSPCON2bits.SEN); // Wait until SEN is cleared
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_stop ()
Definition at line 403 of file i2c.c.
References I2C_idle.
Referenced by I2C1_stop(), I2C2_stop(), I2C_get(), I2C_readFrom(), I2C_send(), I2C_writeTo(), and PCF8574_write().
{
    I2C_idle(); // Wait module is inactive
    //PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
    SSPCON2bits.PEN = 1; // Send stop bit
    while (SSPCON2bits.PEN); // Wait until PEN is cleared
    //while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
}
void I2C_wait ()
Definition at line 330 of file i2c.c.
Referenced by I2C1_wait(), I2C2_wait(), I2C_readchar(), I2C_restart(), I2C_sendAck(), I2C_sendNack(), I2C_start(), I2C_stop(), and I2C_writechar().
{
    while (!PIR1bits.SSPIF); // Wait the interrupt flag is set
    PIR1bits.SSPIF = 0; // Clear SSP interrupt flag
}
u8 I2C_write (u8 value)
Definition at line 256 of file i2c.c.
References I2C_idle.
Referenced by I2C1_write(), I2C2_write(), I2C_readFrom(), I2C_writeTo(), and PCF8574_write().
{
    I2C_idle(); // Wait the MSSP module is inactive
    SSPBUF = value; // Write byte to SSPBUF (BF is set to 1)
    I2C_idle(); // Wait the MSSP module is inactive
/*
    while (SSPCON1bits.WCOL) // Send again if write collision occurred
    {
        LATCbits.LATC2 = 1;
        SSPCON1bits.WCOL = 0; // Must be cleared by software
        SSPBUF = value; // Write byte to SSPBUF (BF is set to 1)
    }
*/
// while (SSPSTATbits.BF); // Wait until buffer is empty (BF set to 0)
    // ACKSTAT can be returned now because it was loaded before BF was cleared
    return (!SSPCON2bits.ACKSTAT); // 1 if Ack, 0 if NAck
}