/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/bcd.c File Reference
#include <typedef.h>
*
Macros
#define __BCD_C
Functions
u8 bin2bcd (u8 dec)
u8 bcd2bin (u8 bcd)
Macro Definition Documentation
#define __BCD_C
Definition at line 25 of file bcd.c.
Function Documentation
u8 bcd2bin (u8 bcd)
Definition at line 42 of file bcd.c.
Referenced by Decode_Buffer(), RTCC_ConvertDate(), and RTCC_ConvertTime().
{
    return ((bcd >> 4) * 10) + bcd % 16;
}
u8 bin2bcd (u8 dec)
Definition at line 33 of file bcd.c.
{
    return ((dec/10) << 4) + (dec % 10);
}