/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/sd/pff.c File Reference
#include <sd/pff.h>
*
#include <sd/diskio.c>
*
#include <string.h>
*
#include <stdio.c>
*
Functions
FRESULT pf_mount (FATFS *fs)
FRESULT pf_open (const char *path)
FRESULT scan_files (char *path)
Function Documentation
FRESULT pf_mount (FATFS * fs)
Definition at line 470 of file pff.c.
References BPB_FATSz16, BPB_FATSz32, BPB_NumFATs, BPB_RootClus, BPB_RootEntCnt, BPB_RsvdSecCnt, BPB_SecPerClus, BPB_TotSec16, BPB_TotSec32, FATFS::csize, FATFS::database, FATFS::dirbase, disk_initialize(), disk_readp(), FATFS::fatbase, FR_DISK_ERR, FR_NO_FILESYSTEM, FR_NOT_READY, FR_OK, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, fsize, LD_DWORD, LD_WORD, FATFS::max_clust, MBR_Table, FATFS::n_rootdir, RES_OK, and STA_NOINIT.
{
    u8 fmt, buf[36];
    u32 bsect, fsize, tsect, mclst;
    DRESULT Dresult;
    Dresult = disk_initialize();
    if(Dresult != RES_OK)
        return FR_DISK_ERR;
    FatFs = 0;
    if (!fs) return FR_OK; /* Unregister fs object */
    if (disk_initialize() & STA_NOINIT){ /* Check if the drive is ready or not
      */
        return FR_NOT_READY;
    }
    /* Search FAT partition on the drive */
    bsect = 0;
    fmt = check_fs(buf, bsect); /* Check sector 0 as an SFD format */
    if (fmt == 1) { /* Not an FAT boot record, it may be FDISK format */
        /* Check a partition listed in top of the partition table */
        if (disk_readp(buf, bsect, MBR_Table, 16)) { /* 1st partition entry */
            fmt = 3;
        } else {
            if (buf[4]) { /* Is the partition existing? */
                bsect = LD_DWORD(&buf[8]); /* Partition offset in LBA */
                fmt = check_fs(buf, bsect); /* Check the partition */
            }
        }
    }
    if (fmt == 3) return FR_DISK_ERR;
    if (fmt) return FR_NO_FILESYSTEM; /* No valid FAT patition is found */
    /* Initialize the file system object */
    if (disk_readp(buf, bsect, 13, sizeof(buf))) return FR_DISK_ERR;
    fsize = LD_WORD(buf+BPB_FATSz16-13); /* Number of sectors per FAT */
    if (!fsize) fsize = LD_DWORD(buf+BPB_FATSz32-13);
    fsize *= buf[BPB_NumFATs-13]; /* Number of sectors in FAT area */
    fs->fatbase = bsect + LD_WORD(buf+BPB_RsvdSecCnt-13); /* FAT start sector
       (lba) */
    fs->csize = buf[BPB_SecPerClus-13]; /* Number of sectors per
       cluster */
    fs->n_rootdir = LD_WORD(buf+BPB_RootEntCnt-13); /* Nmuber of root
       directory entries */
    tsect = LD_WORD(buf+BPB_TotSec16-13); /* Number of sectors on the
       file system */
    if (!tsect) tsect = LD_DWORD(buf+BPB_TotSec32-13);
    mclst = (tsect /* Last cluster# + 1 */
        - LD_WORD(buf+BPB_RsvdSecCnt-13) - fsize - fs->
      n_rootdir / 16
        ) / fs->csize + 2;
    fs->max_clust = (CLUST)mclst;
    fmt = FS_FAT12; /* Determine the FAT sub type */
    if (mclst >= 0xFF7) fmt = FS_FAT16; /* Number of clusters >= 0xFF5 */
    if (mclst >= 0xFFF7) /* Number of clusters >= 0xFFF5 */
#if _FS_FAT32
        fmt = FS_FAT32;
#else
        return FR_NO_FILESYSTEM;
#endif
    fs->fs_type = fmt; /* FAT sub-type */
#if _FS_FAT32
    if (fmt == FS_FAT32)
        fs->dirbase = LD_DWORD(buf+(BPB_RootClus-13)); /* Root directory start
       cluster */
    else
#endif
        fs->dirbase = fs->fatbase + fsize; /* Root directory start sector
       (lba) */
    fs->database = fs->fatbase + fsize + fs->n_rootdir / 16; /* Data start
       sector (lba) */
    fs->flag = 0;
    FatFs = fs;
    return FR_OK;
}
FRESULT pf_open (const char * path)
Definition at line 550 of file pff.c.
References AM_DIR, dir, DIR_Attr, DIR_FileSize, DIR_FstClusHI, DIR_FstClusLO, dj, FA_OPENED, DIR::fn, FR_NO_FILE, FR_NOT_ENABLED, FR_OK, FATFS::fsize, LD_DWORD, LD_WORD, and res.
{
    FRESULT res;
    DIR dj;
    u8 sp[12], dir[32];
    FATFS *fs = FatFs;
    if (!fs) /* Check file system */
        return FR_NOT_ENABLED;
    fs->flag = 0;
    fs->buf = dir;
    dj.fn = sp;
    res = follow_path(&dj, path); /* Follow the file path */
    if (res != FR_OK) return res; /* Follow failed */
    if (!dir[0] || (dir[DIR_Attr] & AM_DIR)) /* It is a directory */
        return FR_NO_FILE;
    fs->org_clust = /* File start cluster */
#if _FS_FAT32
        ((u32)LD_WORD(dir+DIR_FstClusHI) << 16) |
#endif
        LD_WORD(dir+DIR_FstClusLO);
    fs->fsize = LD_DWORD(dir+DIR_FileSize); /* File size */
    fs->fptr = 0; /* File pointer */
    fs->flag = FA_OPENED;
    return FR_OK;
}
FRESULT scan_files (char * path)
Definition at line 870 of file pff.c.
Referenced by scan_files().
{
    FRESULT res;
    FILINFO fno;
    DIR dir;
    char bufpath[12];
    res = pf_opendir(&dir, path);
    if (res == FR_OK) {
        for (;;) {
            res = pf_readdir(&dir, &fno);
           if (res != FR_OK || fno.fname[0] == 0) break;
            if (fno.fattrib & AM_DIR) {
                psprintf(bufpath, "/%s", fno.fname);
                res = scan_files(bufpath);
                if (res != FR_OK) break;
            } else {
                #ifdef SERIAL_PRINT
                serial_printf("%s/", path);
                serial_printf("%s\r\n", fno.fname);
                #endif
                #ifdef CDC_PRINT
                CDCprintf("%s/", path);
                CDCprintf("%s\r\n", fno.fname);
                #endif
            }
        }
    }
    return res;
}