/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/usb/picUSB.c File Reference
#include <pic18fregs.h>
*
#include <string.h>
*
#include `picUSB.h`
*
#include `usb_config.h`
*
Macros
#define ALLOW_SUSPEND 0
#define USE_MEMCPY 0
#define DEVICE_DESCRIPTOR_SIZE 0x12
#define CONFIG_HEADER_SIZE 0x09
#define HID_DESCRIPTOR_SIZE 0x20
#define HID_HEADER_SIZE 0x09
#define SETUP_STAGE 0
#define DATA_OUT_STAGE 1
#define DATA_IN_STAGE 2
#define STATUS_STAGE 3
Functions
volatile BufferDescriptorTable __at (0x400)
void ProcessStandardRequest (void)
void InDataStage (unsigned char ep)
void OutDataStage (unsigned char ep)
void SetupStage (void)
void WaitForSetupStage (void)
void ProcessControlTransfer (void)
void EnableUSBModule (void)
void UnSuspend (void)
void StartOfFrame (void)
void Stall (void)
void Suspend (void)
void BusReset ()
void ProcessUSBTransactions (void)
Variables
u8 deviceState
u8 remoteWakeup
u8 deviceAddress
u8 selfPowered
u8 currentConfiguration
u8 ctrlTransferStage
u8 HIDPostProcess
u8 requestHandled
u8 * outPtr
u8 * inPtr
word wCount
u8 hidIdleRate
u8 hidProtocol
u8 hidRxLen
Macro Definition Documentation
#define ALLOW_SUSPEND 0
TODO:
Definition at line 37 of file picUSB.c.
#define CONFIG_HEADER_SIZE 0x09
Definition at line 47 of file picUSB.c.
#define DATA_IN_STAGE 2
Definition at line 61 of file picUSB.c.
Referenced by ProcessControlTransfer(), and SetupStage().
#define DATA_OUT_STAGE 1
Definition at line 60 of file picUSB.c.
Referenced by ProcessControlTransfer(), and SetupStage().
#define DEVICE_DESCRIPTOR_SIZE 0x12
Definition at line 46 of file picUSB.c.
#define HID_DESCRIPTOR_SIZE 0x20
Definition at line 48 of file picUSB.c.
#define HID_HEADER_SIZE 0x09
Definition at line 49 of file picUSB.c.
#define SETUP_STAGE 0
Definition at line 59 of file picUSB.c.
Referenced by SetupStage(), and WaitForSetupStage().
#define STATUS_STAGE 3
Definition at line 62 of file picUSB.c.
#define USE_MEMCPY 0
Definition at line 40 of file picUSB.c.
Function Documentation
volatile BufferDescriptorTable __at (0x400)
Buffer descriptors Table (see datasheet page 171) RAM Bank 4 (0x400 though 0x4ff) is used spEcifically for endpoint buffer control in a structure known as Buffer Descriptor Table (BDTZ). TODO: find something smarter to allocate the buffer, like in usbmmap.c of the microchip firmware. If not all endpoints are used the space in RAM is wasted.
Definition at line 95 of file picUSB.c.
{
    #ifdef DEBUG_PRINT
    printf("GetDescriptor\r\n");
    #endif
    if(SetupPacket.bmRequestType == 0x80)
    {
        u8 descriptorType = SetupPacket.wValue1;
        u8 descriptorIndex = SetupPacket.wValue0;
        if (descriptorType == DEVICE_DESCRIPTOR)
        {
        #ifdef DEBUG_PRINT
        printf("DEVICE_DESCRIPTOR (0x%ux)\r\n",(word)descriptorType);
        #endif
          requestHandled = 1;
          outPtr = (u8 *)&libdevice_descriptor;
          wCount = sizeof(USB_Device_Descriptor);
        }
        else if (descriptorType == CONFIGURATION_DESCRIPTOR)
        {
            #ifdef DEBUG_PRINT
            printf("CONFIGURATION_DESCRIPTOR (0x%ux): %d\r\n", (word)descriptorType, descriptorIndex);
            #endif
            requestHandled = 1;
            #if 0
            outPtr = (u8 *)&libconfiguration_descriptor;
            // wCount = *(outPtr + 2);
            wCount = CFSZ;
            #else
            // SDCC 2.5 makes bad code with the following two lines. The
            // unusual thing is that it is the first of the two lines that
            // is compiled incorrectly (outPtr gets the contents of
            // libconfiguration_descriptor rather than the address), even though it
            // is the second line that changes from above.
            outPtr = (u8 *)&libconfiguration_descriptor;
            //wCount = libconfiguration_descriptor.configHeader[2]; // Note: SDCC makes bad code with this
            wCount = libconfiguration_descriptor.Header.wTotalLength;
            #endif
            #ifdef DEBUG_PRINT
            printf("Total config size: %d\r\n", wCount);
            #endif
        }
        else if (descriptorType == STRING_DESCRIPTOR)
        {
            #ifdef DEBUG_PRINT
            printf("STRING_DESCRIPTOR: %d\r\n", (word)descriptorIndex);
            #endif
            requestHandled = 1;
            //outPtr = (u8 *)&libstring_descriptor[descriptorIndex];
            outPtr = libstring_descriptor[descriptorIndex];
            wCount = *outPtr;
        }
        else if (descriptorType == DEVICE_QUALIFIER_DESCRIPTOR)
        {
            #ifdef DEBUG_PRINT
            printf("DEVICE_QUALIFIER_DESCRIPTOR\r\n");
            #endif
            requestHandled = 1;
            // TODO: check if this is needed if not requestHandled is not set to 1 the device will
            // stall later when the linux kernel requests this descriptor
            //outPtr = (u8 *)&libconfiguration_descriptor;
            //wCount = sizeof();
        }
        else
        {
            #ifdef DEBUG_PRINT
            printf("Unknown Descriptor: 0x%ux\r\n", (word)descriptorType);
            #endif
        }
    }
}
void BusReset ()
Definition at line 793 of file picUSB.c.
References currentConfiguration, DEFAULT_STATUS, deviceState, EP_CTRL, HSHK_EN, remoteWakeup, selfPowered, and WaitForSetupStage().
Referenced by ProcessUSBTransactions().
                {
  UEIR = 0x00;
  UIR = 0x00;
  UEIE = 0x9f;
  UIE = 0x7b;
  UADDR = 0x00;
  // Set endpoint 0 as a control pipe
  UEP0 = EP_CTRL | HSHK_EN;
  // Flush any pending transactions
  while (UIRbits.TRNIF == 1)
    UIRbits.TRNIF = 0;
  // Enable packet processing
  UCONbits.PKTDIS = 0;
  // Prepare for the Setup stage of a control transfer
  WaitForSetupStage();
  remoteWakeup = 0; // Remote wakeup is off by default
  selfPowered = 0; // Self powered is off by default
  currentConfiguration = 0; // Clear active configuration
  deviceState = DEFAULT_STATUS;
}
void EnableUSBModule (void)
Definition at line 651 of file picUSB.c.
References ATTACHED, deviceState, and POWERED.
Referenced by CDC_init(), and init_CDC().
{
    // TBD: Check for voltage coming from the USB cable and use that
    // as an indication we are attached.
    if(UCONbits.USBEN == 0)
    {
        #ifdef DEBUG_PRINT
        printf("Enable the module\r\n");
        #endif
        UCON = 0;
        UIE = 0;
        UCONbits.USBEN = 1;
        deviceState = ATTACHED;
    }
    // If we are attached and no single-ended zero is detected, then
    // we can move to the Powered state.
    if ((deviceState == ATTACHED) && !UCONbits.SE0)
    {
        UIR = 0;
        UIE = 0;
        UIEbits.URSTIE = 1;
        UIEbits.IDLEIE = 1;
        deviceState = POWERED;
        #ifdef DEBUG_PRINT
        printf("Device powered\r\n");
        #endif
    }
}
void InDataStage (unsigned char ep)
Data stage for a Control Transfer that sends data to the host
Definition at line 394 of file picUSB.c.
References BDS_BC8, BDS_BC9, EP0_BUFFER_SIZE, EP_IN_BD, inPtr, outPtr, PTR16, and wCount.
Referenced by ProcessControlTransfer(), and SetupStage().
                                   {
#if !USE_MEMCPY
  u8 i;
#endif
  word bufferSize;
  // Determine how many bytes are going to the host
  if(wCount < EP0_BUFFER_SIZE)
    bufferSize = wCount;
  else
    bufferSize = EP0_BUFFER_SIZE;
#ifdef DEBUG_PRINT
  // printf("USBCtrlTrfTxService: %d\r\n", bufferSize);
#endif
  // Load the high two bits of the u8 count into BC8:BC9
  // Clear BC8 and BC9
  EP_IN_BD(ep).Stat.uc &= ~(BDS_BC8 | BDS_BC9);
  EP_IN_BD(ep).Stat.uc |= (u8)((bufferSize & 0x0300) >> 8);
  EP_IN_BD(ep).Cnt = (u8)(bufferSize & 0xFF);
  EP_IN_BD(ep).ADDR = PTR16(&controlTransferBuffer);
  // Update the number of bytes that still need to be sent. Getting
  // all the data back to the host can take multiple transactions, so
  // we need to track how far along we are.
  wCount = wCount - bufferSize;
  // Move data to the USB output buffer from wherever it sits now.
  inPtr = (u8 *)&controlTransferBuffer;
#if USE_MEMCPY
  memcpy(inPtr, outPtr, bufferSize);
#else
  for (i=0;i<bufferSize;i++) {
#ifdef DEBUG_PRINT
  //printf("0x%x = 0x%x (0x%uhx) ", PTR16(ramPtr), PTR16(romPtr), *romPtr);
#endif
    *inPtr++ = *outPtr++;
  }
#endif
}
void OutDataStage (unsigned char ep)
Data stage for a Control Transfer that reads data from the host
Definition at line 441 of file picUSB.c.
References EP_OUT_BD, inPtr, outPtr, and wCount.
Referenced by ProcessControlTransfer().
                                    {
  word i, bufferSize;
  bufferSize = ((0x03 & EP_OUT_BD(ep).Stat.uc) << 8) | EP_OUT_BD(ep).Cnt;
#ifdef DEBUG_PRINT
  // printf("OutDataStage: %d\r\n", bufferSize);
#endif
  // Accumulate total number of bytes read
  wCount = wCount + bufferSize;
  outPtr = (u8*)&controlTransferBuffer;
#if USE_MEMCPY
  memcpy(inPtr, outPtr, bufferSize);
#else
  for (i=0;i<bufferSize;i++) {
#ifdef DEBUG_PRINT
  // printf("0x%x = 0x%x (0x%uhx) ", PTR16(inPtr), PTR16(outPtr), *outPtr);
#endif
    *inPtr++ = *outPtr++;
  }
#ifdef DEBUG_PRINT
  // printf("\r\n");
#endif
#endif
}
void ProcessControlTransfer (void)
Definition at line 563 of file picUSB.c.
References ADDRESS, BDS_DTS, BDS_DTSEN, BDS_UOWN, ctrlTransferStage, DATA_IN_STAGE, DATA_OUT_STAGE, DEFAULT_STATUS, deviceState, EP_IN_BD, EP_OUT_BD, HIDPostProcess, IN, InDataStage(), OUT, OutDataStage(), SetupStage(), and WaitForSetupStage().
Referenced by ProcessUSBTransactions().
                                  {
#ifdef DEBUG_PRINT
    printf("Pct\n\r");
#endif
  if (USTATbits.DIR == OUT) {
  // Endpoint 0:out
  // Pull PID from middle of BD0STAT
    u8 PID = (EP_OUT_BD(0).Stat.uc & 0x3C) >> 2;
    if (PID == 0x0D)
  // SETUP PID - a transaction is starting
      SetupStage();
    else if (ctrlTransferStage == DATA_OUT_STAGE) {
  // Complete the data stage so that all information has
  // passed from host to device before servicing it.
      OutDataStage(0);
#ifdef USB_USE_HID
      if (HIDPostProcess) {
  // Determine which report is being set.
        u8 reportID = SetupPacket.wValue0;
  // Find out if an Output or Feature report has arrived on the control pipe.
  // Get the report type from the Setup packet.
        if (SetupPacket.wValue1 == 0x02) {
  // Output report
          SetOutputReport(reportID);
        }
        else if (SetupPacket.wValue1 == 0x03) {
  // Feature report
          SetFeatureReport(reportID);
        }
        else {
  // Unknown report type
        }
      }
#endif
  // Turn control over to the SIE and toggle the data bit
      if(EP_OUT_BD(0).Stat.DTS)
        EP_OUT_BD(0).Stat.uc = BDS_UOWN | BDS_DTSEN;
      else
        EP_OUT_BD(0).Stat.uc = BDS_UOWN | BDS_DTS |
      BDS_DTSEN;
    }
    else {
  // Prepare for the Setup stage of a control transfer
      WaitForSetupStage();
    }
  }
  else if(USTATbits.DIR == IN) {
  // Endpoint 0:in
    if ((UADDR == 0) && (deviceState == ADDRESS)) {
  // TBD: ensure that the new address matches the value of
  // "deviceAddress" (which came in through a SET_ADDRESS).
      UADDR = SetupPacket.wValue0;
#ifdef DEBUG_PRINT
      printf("UADDR = 0x%x\r\n", (word)UADDR);
#endif
      if(UADDR == 0)
  // If we get a reset after a SET_ADDRESS, then we need
  // to drop back to the Default state.
        deviceState = DEFAULT_STATUS;
    }
    if (ctrlTransferStage == DATA_IN_STAGE) {
  // Start (or continue) transmitting data
      InDataStage(0);
  // Turn control over to the SIE and toggle the data bit
      if(EP_IN_BD(0).Stat.DTS)
        EP_IN_BD(0).Stat.uc = BDS_UOWN | BDS_DTSEN;
      else
        EP_IN_BD(0).Stat.uc = BDS_UOWN | BDS_DTS |
      BDS_DTSEN;
    }
    else {
  // Prepare for the Setup stage of a control transfer
      WaitForSetupStage();
    }
  }
  else {
#ifdef DEBUG_PRINT
    printf("IN on EP %d\r\n", (USTAT >> 3) & 0x0f);
    printf("USTAT = 0x%uhx\r\n", USTAT);
#endif
  }
}
void ProcessStandardRequest (void)
Definition at line 283 of file picUSB.c.
References ADDRESS, CLEAR_FEATURE, CONFIGURED, currentConfiguration, deviceAddress, deviceState, GET_CONFIGURATION, GET_DESCRIPTOR, GET_INTERFACE, GET_STATUS, outPtr, requestHandled, SET_ADDRESS, SET_CONFIGURATION, SET_DESCRIPTOR, SET_FEATURE, SET_INTERFACE, SYNCH_FRAME, and wCount.
Referenced by SetupStage().
                                  {
  u8 request = SetupPacket.bRequest;
  if((SetupPacket.bmRequestType & 0x60) != 0x00)
  // Not a standard request - don't process here. Class or Vendor
  // requests have to be handled seperately.
    return;
  if (request == SET_ADDRESS) {
  // Set the address of the device. All future requests
  // will come to that address. Can't actually set UADDR
  // to the new address yet because the rest of the SET_ADDRESS
  // transaction uses address 0.
#ifdef DEBUG_PRINT
    printf("SET_ADDRESS: %uhx\r\n", SetupPacket.wValue0);
#endif
    requestHandled = 1;
    deviceState = ADDRESS;
    deviceAddress = SetupPacket.wValue0;
  }
  else if (request == GET_DESCRIPTOR) {
    GetDescriptor();
  }
  else if (request == SET_CONFIGURATION) {
#ifdef DEBUG_PRINT
    printf("SET_CONFIGURATION\r\n");
#endif
    requestHandled = 1;
    currentConfiguration = SetupPacket.wValue0;
  // TBD: ensure the new configuration value is one that
  // exists in the descriptor.
    if (currentConfiguration == 0)
  // If configuration value is zero, device is put in
  // address state (USB 2.0 - 9.4.7)
      deviceState = ADDRESS;
    else {
  // Set the configuration.
      deviceState = CONFIGURED;
  // Initialize the endpoints for all interfaces
#ifdef USB_USE_HID
      HIDInitEndpoint();
#endif
#ifdef USB_USE_UART
      UARTInitEndpoint();
#endif
#ifdef USB_USE_CDC
      CDCInitEndpoint();
#endif
#ifdef USB_USE_BULK
      BULKInitEndpoint();
#endif
  // TBD: Add initialization code here for any additional
  // interfaces beyond the one used for the HID
    }
  }
  else if (request == GET_CONFIGURATION) {
#ifdef DEBUG_PRINT
    printf("GET_CONFIGURATION\r\n");
#endif
    requestHandled = 1;
    outPtr = (u8*)&currentConfiguration;
    wCount = 1;
  }
  else if (request == GET_STATUS) {
    GetStatus();
  }
  else if ((request == CLEAR_FEATURE) ||
  (request == SET_FEATURE)) {
    SetFeature();
  }
  else if (request == GET_INTERFACE) {
  // No support for alternate interfaces. Send
  // zero back to the host.
#ifdef DEBUG_PRINT
    printf("GET_INTERFACE\r\n");
#endif
    requestHandled = 1;
    controlTransferBuffer[0] = 0;
    outPtr = (u8 *)&controlTransferBuffer;
    wCount = 1;
  }
  else if (request == SET_INTERFACE) {
  // No support for alternate interfaces - just ignore.
#ifdef DEBUG_PRINT
    printf("SET_INTERFACE\r\n");
#endif
    requestHandled = 1;
  }
  else if (request == SET_DESCRIPTOR) {
#ifdef DEBUG_PRINT
    printf("SET_DESCRIPTOR\r\n");
#endif
  }
  else if (request == SYNCH_FRAME) {
#ifdef DEBUG_PRINT
    printf("SYNCH_FRAME\r\n");
#endif
  }
  else {
#ifdef DEBUG_PRINT
    printf("Default Std Request\r\n");
#endif
  }
}
void ProcessUSBTransactions (void)
Definition at line 821 of file picUSB.c.
References BusReset(), DEFAULT_STATUS, DETACHED, deviceState, ProcessControlTransfer(), Stall(), StartOfFrame(), Suspend(), and UnSuspend().
Referenced by CDC_init(), CDC_interrupt(), and init_CDC().
{
  // See if the device is connected yet.
  if(deviceState == DETACHED)
    return;
  // If the USB became active then wake up from suspend
  if(UIRbits.ACTVIF && UIEbits.ACTVIE)
    UnSuspend();
  // If we are supposed to be suspended, then don't try performing any
  // processing.
  if(UCONbits.SUSPND == 1)
    return;
  // Process a bus reset
  if (UIRbits.URSTIF && UIEbits.URSTIE)
    BusReset();
  // No bus activity for a while - suspend the firmware
  if (UIRbits.IDLEIF && UIEbits.IDLEIE)
    Suspend();
  
  if (UIRbits.SOFIF && UIEbits.SOFIE)
    StartOfFrame();
  
  if (UIRbits.STALLIF && UIEbits.STALLIE)
    Stall();
  // TBD: See where the error came from.
  // Clear errors
  if (UIRbits.UERRIF && UIEbits.UERRIE)
    UIRbits.UERRIF = 0;
  // Unless we have been reset by the host, no need to keep processing
  if (deviceState < DEFAULT_STATUS)
    return;
  // A transaction has finished. Try default processing on endpoint 0.
  if(UIRbits.TRNIF && UIEbits.TRNIE)
  {
    ProcessControlTransfer();
    // Turn off interrupt
    UIRbits.TRNIF = 0;
  }
}
void SetupStage (void)
Process the Setup stage of a control transfer. This code initializes the flags that let the firmware know what to do during subsequent stages of the transfer. TODO: Only Ep0 is handled here.
Definition at line 477 of file picUSB.c.
References BDS_BSTALL, BDS_DTS, BDS_DTSEN, BDS_UOWN, ctrlTransferStage, DATA_IN_STAGE, DATA_OUT_STAGE, EP0_BUFFER_SIZE, EP_IN_BD, EP_OUT_BD, HIDPostProcess, InDataStage(), ProcessStandardRequest(), PTR16, requestHandled, SETUP_STAGE, USB_RECIP_INTERFACE, USB_RECIP_MASK, and wCount.
Referenced by ProcessControlTransfer().
                      {
  // Note: Microchip says to turn off the UOWN bit on the IN direction as
  // soon as possible after detecting that a SETUP has been received.
  EP_IN_BD(0).Stat.uc &= ~BDS_UOWN;
  EP_OUT_BD(0).Stat.uc &= ~BDS_UOWN;
  // Initialize the transfer process
  ctrlTransferStage = SETUP_STAGE;
  requestHandled = 0; // Default is that request hasn't been handled
  HIDPostProcess = 0; // Assume standard request until know otherwise
  wCount = 0; // No bytes transferred
  // See if this is a standard (as definded in USB chapter 9) request
  ProcessStandardRequest();
  // only Process CDC or HID if recipient is an interface
  // See if the HID class can do something with it.
#ifdef USB_USE_HID
  if ((SetupPacket.bmRequestType & USB_RECIP_MASK) ==
      USB_RECIP_INTERFACE)
    ProcessHIDRequest();
#endif
#ifdef USB_USE_CDC
  if ((SetupPacket.bmRequestType & USB_RECIP_MASK) ==
      USB_RECIP_INTERFACE)
    ProcessCDCRequest();
#endif
  // TBD: Add handlers for any other classes/interfaces in the device
  if (!requestHandled) {
  // If this service wasn't handled then stall endpoint 0
    EP_OUT_BD(0).Cnt = EP0_BUFFER_SIZE;
    EP_OUT_BD(0).ADDR = PTR16(&SetupPacket);
    EP_OUT_BD(0).Stat.uc = BDS_UOWN | BDS_BSTALL;
    EP_IN_BD(0).Stat.uc = BDS_UOWN | BDS_BSTALL;
  }
  else if (SetupPacket.bmRequestType & 0x80) {
  // Device-to-host
    if(SetupPacket.wLength < wCount)
      wCount = SetupPacket.wLength;
    InDataStage(0);
    ctrlTransferStage = DATA_IN_STAGE;
  // Reset the out buffer descriptor for endpoint 0
    EP_OUT_BD(0).Cnt = EP0_BUFFER_SIZE;
    EP_OUT_BD(0).ADDR = PTR16(&SetupPacket);
    EP_OUT_BD(0).Stat.uc = BDS_UOWN;
  // Set the in buffer descriptor on endpoint 0 to send data
    EP_IN_BD(0).ADDR = PTR16(&controlTransferBuffer);
  // Give to SIE, DATA1 packet, enable data toggle checks
    EP_IN_BD(0).Stat.uc = BDS_UOWN | BDS_DTS | BDS_DTSEN;
  }
  else {
  // Host-to-device
    ctrlTransferStage = DATA_OUT_STAGE;
  // Clear the input buffer descriptor
    EP_IN_BD(0).Cnt = 0;
    EP_IN_BD(0).Stat.uc = BDS_UOWN | BDS_DTS | BDS_DTSEN;
  // Set the out buffer descriptor on endpoint 0 to receive data
    EP_OUT_BD(0).Cnt = EP0_BUFFER_SIZE;
    EP_OUT_BD(0).ADDR = PTR16(&controlTransferBuffer);
  // Give to SIE, DATA1 packet, enable data toggle checks
    EP_OUT_BD(0).Stat.uc = BDS_UOWN | BDS_DTS |
      BDS_DTSEN;
  }
  // Enable SIE token and packet processing
  UCONbits.PKTDIS = 0;
}
void Stall (void)
Definition at line 704 of file picUSB.c.
References WaitForSetupStage().
Referenced by ProcessUSBTransactions().
{
    #ifdef DEBUG_PRINT
    printf("Stall\r\n");
    #endif
    if(UEP0bits.EPSTALL == 1)
    {
        // Prepare for the Setup stage of a control transfer
        WaitForSetupStage();
        UEP0bits.EPSTALL = 0;
    }
    UIRbits.STALLIF = 0;
}
void StartOfFrame (void)
Definition at line 697 of file picUSB.c.
Referenced by ProcessUSBTransactions().
{
      // TBD: Add a callback routine to do something
      UIRbits.SOFIF = 0;
}
void Suspend (void)
Definition at line 720 of file picUSB.c.
Referenced by ProcessUSBTransactions().
{
#ifdef ALLOW_SUSPEND
#ifdef DEBUG_PRINT
  printf("Suspend\r\n");
#endif
  UIEbits.ACTVIE = 1;
  UIRbits.IDLEIF = 0;
  UCONbits.SUSPND = 1;
  #if defined(__18f25k50) || defined(__18f45k50)
  PIR3bits.USBIF = 0;
  #else
  PIR2bits.USBIF = 0;
  #endif
  #if defined(__18f25k50) || defined(__18f45k50)
  INTCONbits.IOCIF = 0;
  #else
  INTCONbits.RBIF = 0;
  #endif
  #if defined(__18f25k50) || defined(__18f45k50)
  PIE3bits.USBIE = 1;
  #else
  PIE2bits.USBIE = 1;
  #endif
  #if defined(__18f25k50) || defined(__18f45k50)
  INTCONbits.IOCIE = 1;
  #else
  INTCONbits.RBIE = 1;
  #endif
  // disable the USART
#ifdef DEBUG_PRINT
  #if defined(__18f25k50) || defined(__18f45k50)
  RCSTA1bits.CREN = 0;
  TXSTA1bits.TXEN = 0;
  #else
  RCSTAbits.CREN = 0;
  TXSTAbits.TXEN = 0;
  #endif
#endif
  Sleep();
  // enable the USART
#ifdef DEBUG_PRINT
  #if defined(__18f25k50) || defined(__18f45k50)
  RCSTA1bits.CREN = 1;
  TXSTA1bits.TXEN = 1;
  #else
  RCSTAbits.CREN = 1;
  TXSTAbits.TXEN = 1;
  #endif
#endif
  #if defined(__18f25k50) || defined(__18f45k50)
  PIE3bits.USBIE = 0;
  #else
  PIE2bits.USBIE = 0;
  #endif
  #if defined(__18f25k50) || defined(__18f45k50)
  INTCONbits.IOCIE = 0;
  #else
  INTCONbits.RBIE = 0;
  #endif
#endif
}
void UnSuspend (void)
Definition at line 683 of file picUSB.c.
Referenced by ProcessUSBTransactions().
{
    #ifdef DEBUG_PRINT
    printf("UnSuspend\r\n");
    #endif
    UCONbits.SUSPND = 0;
    UIEbits.ACTVIE = 0;
    UIRbits.ACTVIF = 0;
}
void WaitForSetupStage (void)
Definition at line 549 of file picUSB.c.
References BDS_DTSEN, BDS_UOWN, ctrlTransferStage, EP0_BUFFER_SIZE, EP_IN_BD, EP_OUT_BD, PTR16, and SETUP_STAGE.
Referenced by BusReset(), ProcessControlTransfer(), and Stall().
                             {
  ctrlTransferStage = SETUP_STAGE;
  EP_OUT_BD(0).Cnt = EP0_BUFFER_SIZE;
  EP_OUT_BD(0).ADDR = PTR16(&SetupPacket);
  // Give to SIE, enable data toggle checks
  EP_OUT_BD(0).Stat.uc = BDS_UOWN | BDS_DTSEN;
  EP_IN_BD(0).Stat.uc = 0x00; // Give control to CPU
}
Variable Documentation
u8 ctrlTransferStage
Definition at line 64 of file picUSB.c.
Referenced by ProcessControlTransfer(), SetupStage(), and WaitForSetupStage().
u8 currentConfiguration
Definition at line 56 of file picUSB.c.
Referenced by BusReset(), CDC_init(), init_CDC(), and ProcessStandardRequest().
u8 deviceAddress
Definition at line 54 of file picUSB.c.
Referenced by ProcessStandardRequest().
u8 deviceState
Definition at line 52 of file picUSB.c.
Referenced by BusReset(), CDC_init(), EnableUSBModule(), init_CDC(), ProcessControlTransfer(), ProcessStandardRequest(), and ProcessUSBTransactions().
u8 hidIdleRate
Definition at line 74 of file picUSB.c.
u8 HIDPostProcess
Definition at line 66 of file picUSB.c.
Referenced by ProcessControlTransfer(), and SetupStage().
u8 hidProtocol
Definition at line 75 of file picUSB.c.
u8 hidRxLen
Definition at line 76 of file picUSB.c.
u8* inPtr
Definition at line 70 of file picUSB.c.
Referenced by InDataStage(), and OutDataStage().
u8* outPtr
Definition at line 69 of file picUSB.c.
Referenced by __at(), InDataStage(), OutDataStage(), and ProcessStandardRequest().
u8 remoteWakeup
Definition at line 53 of file picUSB.c.
Referenced by BusReset(), CDC_init(), and init_CDC().
u8 requestHandled
Definition at line 67 of file picUSB.c.
Referenced by __at(), ProcessStandardRequest(), and SetupStage().
u8 selfPowered
Definition at line 55 of file picUSB.c.
Referenced by BusReset().
word wCount
Definition at line 71 of file picUSB.c.
Referenced by __at(), InDataStage(), OutDataStage(), ProcessStandardRequest(), and SetupStage().