/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/pid.c File Reference
#include <typedef.h>
*
#include <pid.h>
*
#include <millis.c>
*
Macros
#define __PID_C
Functions
void PID_init (double *Input, double *Output, double *Setpoint, double Kp, double Ki, double Kd, int ControllerDirection)
void PID_Compute ()
void PID_SetTunings (double Kp, double Ki, double Kd)
void PID_SetSampleTime (int NewSampleTime)
void PID_SetOutputLimits (double Min, double Max)
void PID_SetMode (int Mode)
void PID_Initialize ()
void PID_SetControllerDirection (int Direction)
double PID_GetKp ()
double PID_GetKi ()
double PID_GetKd ()
int PID_GetMode ()
int PID_GetDirection ()
Macro Definition Documentation
#define __PID_C
Definition at line 9 of file pid.c.
Function Documentation
void PID_Compute ()
Definition at line 40 of file pid.c.
References inAuto, input(), ITerm, kd, ki, kp, lastInput, lastTime, millis(), myInput, myOutput, mySetpoint, outMax, outMin, output(), and SampleTime.
{
    unsigned long now, timeChange;
    double input, error, dInput, output;
    if(!inAuto) return;
    now = millis();
    timeChange = (now - lastTime);
    
    if(timeChange>=SampleTime)
    {
        /*Compute all the working error variables*/
        input = *myInput;
        error = *mySetpoint - input;
        ITerm+= (ki * error);
        if(ITerm > outMax) ITerm= outMax;
        else if(ITerm < outMin) ITerm= outMin;
        dInput = (input - lastInput);
        /*Compute PID Output*/
        output = kp * error + ITerm- kd * dInput;
        if(output > outMax) output = outMax;
          else if(output < outMin) output = outMin;
        *myOutput = output;
        /*Remember some variables for next time*/
        lastInput = input;
        lastTime = now;
    }
}
int PID_GetDirection ()
Definition at line 192 of file pid.c.
References controllerDirection.
{ return controllerDirection;}
double PID_GetKd ()
Definition at line 190 of file pid.c.
References dispKd.
{ return dispKd;}
double PID_GetKi ()
Definition at line 189 of file pid.c.
References dispKi.
{ return dispKi;}
double PID_GetKp ()
Definition at line 188 of file pid.c.
References dispKp.
{ return dispKp; }
int PID_GetMode ()
Definition at line 191 of file pid.c.
References AUTOMATIC, inAuto, and MANUAL.
{ return inAuto ? AUTOMATIC : MANUAL;}
void PID_init (double * Input, double * Output, double * Setpoint, double Kp, double Ki, double Kd, int ControllerDirection)
Definition at line 19 of file pid.c.
References inAuto, lastTime, millis(), myInput, myOutput, mySetpoint, PID_SetControllerDirection(), PID_SetOutputLimits(), PID_SetTunings(), and SampleTime.
{
    PID_SetOutputLimits(0, 255); //default output limit corresponds to the arduino pwm
       limits
    SampleTime = 100; //default Controller Sample Time is 0.1 seconds
    PID_SetControllerDirection(ControllerDirection);
    PID_SetTunings(Kp, Ki, Kd);
    lastTime = millis()-SampleTime;
    inAuto = false;
    myOutput = Output;
    myInput = Input;
    mySetpoint = Setpoint;
}
void PID_Initialize ()
Definition at line 158 of file pid.c.
References ITerm, lastInput, myInput, myOutput, outMax, and outMin.
Referenced by PID_SetMode().
{
   ITerm = *myOutput;
   lastInput = *myInput;
   if(ITerm > outMax) ITerm = outMax;
   else if(ITerm < outMin) ITerm = outMin;
}
void PID_SetControllerDirection (int Direction)
Definition at line 172 of file pid.c.
References controllerDirection, inAuto, kd, ki, and kp.
Referenced by PID_init().
{
   if(inAuto && Direction !=controllerDirection)
   {
kp = (0 - kp);
      ki = (0 - ki);
      kd = (0 - kd);
   }
   controllerDirection = Direction;
}
void PID_SetMode (int Mode)
Definition at line 144 of file pid.c.
References AUTOMATIC, inAuto, and PID_Initialize().
{
    u8 newAuto = (Mode == AUTOMATIC);
    if(newAuto == !inAuto)
    { /*we just went from manual to auto*/
        PID_Initialize();
    }
    inAuto = newAuto;
}
void PID_SetOutputLimits (double Min, double Max)
Definition at line 123 of file pid.c.
References inAuto, ITerm, myOutput, outMax, and outMin.
Referenced by PID_init().
{
   if(Min >= Max) return;
   outMin = Min;
   outMax = Max;
 
   if(inAuto)
   {
if(*myOutput > outMax) *myOutput = outMax;
else if(*myOutput < outMin) *myOutput = outMin;
if(ITerm > outMax) ITerm= outMax;
else if(ITerm < outMin) ITerm= outMin;
   }
}
void PID_SetSampleTime (int NewSampleTime)
Definition at line 103 of file pid.c.
References kd, ki, and SampleTime.
{
   if (NewSampleTime > 0)
   {
      double ratio = (double)NewSampleTime
                      / (double)SampleTime;
      ki *= ratio;
      kd /= ratio;
      SampleTime = (unsigned long)NewSampleTime;
   }
}
void PID_SetTunings (double Kp, double Ki, double Kd)
Definition at line 79 of file pid.c.
References controllerDirection, dispKd, dispKi, dispKp, kd, ki, kp, REVERSE, and SampleTime.
Referenced by PID_init().
{
    double SampleTimeInSec;
    if (Kp<0 || Ki<0 || Kd<0) return;
    dispKp = Kp; dispKi = Ki; dispKd = Kd;
    SampleTimeInSec = ((double)SampleTime)/1000;
    kp = Kp;
    ki = Ki * SampleTimeInSec;
    kd = Kd / SampleTimeInSec;
    if(controllerDirection ==REVERSE)
    {
        kp = (0 - kp);
        ki = (0 - ki);
        kd = (0 - kd);
    }
}