/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoserial1.c File Reference
#include <stdarg.h>
*
#include <printf.c>
*
#include <serial.c>
*
#include <typedef.h>
*
Macros
#define __PINGUINOSERIAL1_C
Functions
void serial1init (u32 speed)
void serial1write (char c)
char serial1getkey (void)
char * serial1getstring (void)
char serial1available (void)
char serial1read (void)
void serial1flush (void)
BOOL serial1clearrxerror (void)
Macro Definition Documentation
#define __PINGUINOSERIAL1_C
Definition at line 27 of file pinguinoserial1.c.
Function Documentation
char serial1available (void)
Definition at line 158 of file pinguinoserial1.c.
References SerialAvailable(), UART1, and UART2.
Referenced by modbuss_SerialAvailable().
{
#ifdef PIC32_PINGUINO_220
    return SerialAvailable(UART2);
#else
    return SerialAvailable(UART1);
#endif
}
BOOL serial1clearrxerror (void)
Definition at line 185 of file pinguinoserial1.c.
References ClearRxError(), UART1, and UART2.
Referenced by modbuss_SerialClearRxError().
{
#ifdef PIC32_PINGUINO_220
    return(ClearRxError(UART2));
#else
    return(ClearRxError(UART1));
#endif
}
void serial1flush (void)
Definition at line 176 of file pinguinoserial1.c.
References SerialFlush(), UART1, and UART2.
Referenced by modbuss_SerialFlush().
{
#ifdef PIC32_PINGUINO_220
    SerialFlush(UART2);
#else
    SerialFlush(UART1);
#endif
}
char serial1getkey (void)
Definition at line 140 of file pinguinoserial1.c.
References SerialGetKey(), UART1, and UART2.
{
#ifdef PIC32_PINGUINO_220
    return SerialGetKey(UART2);
#else
    return SerialGetKey(UART1);
#endif
}
char* serial1getstring (void)
Definition at line 149 of file pinguinoserial1.c.
References SerialGetString(), UART1, and UART2.
{
#ifdef PIC32_PINGUINO_220
    return SerialGetString(UART2);
#else
    return SerialGetString(UART1);
#endif
}
void serial1init (u32 speed)
Definition at line 34 of file pinguinoserial1.c.
References SerialConfigure(), UART1, UART2, UART_ENABLE, and UART_RX_TX_ENABLED.
Referenced by debug(), and modbuss_SerialBegin().
{
    #ifdef PIC32_PINGUINO_220
        SerialConfigure(UART2, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
    #else
        SerialConfigure(UART1, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
    #endif
}
char serial1read (void)
Definition at line 167 of file pinguinoserial1.c.
References SerialRead(), UART1, and UART2.
Referenced by modbuss_SerialRead().
{
#ifdef PIC32_PINGUINO_220
    return SerialRead(UART2);
#else
    return SerialRead(UART1);
#endif
}
void serial1write (char c)
Definition at line 131 of file pinguinoserial1.c.
References SerialUART1WriteChar(), and SerialUART2WriteChar().
Referenced by Disp_Input_Binary(), and modbuss_SerialWrite().
{
#ifdef PIC32_PINGUINO_220
    SerialUART2WriteChar(c);
#else
    SerialUART1WriteChar(c);
#endif
}