/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoserial6.c File Reference
#include <stdarg.h>
*
#include <printf.c>
*
#include <serial.c>
*
#include <typedef.h>
*
Macros
#define __PINGUINOSERIAL6_C
#define ENABLE_UART6
Functions
void serial6init (u32 speed)
void serial6printf (char *fmt,...)
void serial6println (char *fmt,...)
void serial6write (char c)
char serial6getkey (void)
char * serial6getstring (void)
char serial6available (void)
char serial6read (void)
void serial6flush (void)
BOOL serial6clearrxerror (void)
Macro Definition Documentation
#define __PINGUINOSERIAL6_C
Definition at line 26 of file pinguinoserial6.c.
#define ENABLE_UART6
Definition at line 29 of file pinguinoserial6.c.
Function Documentation
char serial6available (void)
Definition at line 103 of file pinguinoserial6.c.
References SerialAvailable().
{
    return SerialAvailable(UART6);
}
BOOL serial6clearrxerror (void)
Definition at line 118 of file pinguinoserial6.c.
References ClearRxError().
{
    return(ClearRxError(UART6));
}
void serial6flush (void)
Definition at line 113 of file pinguinoserial6.c.
References SerialFlush().
{
    SerialFlush(UART6);
}
char serial6getkey (void)
Definition at line 93 of file pinguinoserial6.c.
References SerialGetKey().
{
    return SerialGetKey(UART6);
}
char* serial6getstring (void)
Definition at line 98 of file pinguinoserial6.c.
References SerialGetString().
{
    return SerialGetString(UART6);
}
void serial6init (u32 speed)
Definition at line 37 of file pinguinoserial6.c.
References SerialConfigure(), UART_ENABLE, and UART_RX_TX_ENABLED.
{
    SerialConfigure(UART6, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
}
void serial6printf (char * fmt, ...)
Definition at line 42 of file pinguinoserial6.c.
References pprintf().
Referenced by serial6println().
{
    va_list args;
    va_start(args, fmt);
    pprintf(SerialUART6WriteChar, fmt, args);
    va_end(args);
}
void serial6println (char * fmt, ...)
Definition at line 82 of file pinguinoserial6.c.
References serial6printf().
{
    serial6printf(fmt);
    serial6printf("\n\r");
}
char serial6read (void)
Definition at line 108 of file pinguinoserial6.c.
References SerialRead().
{
    return SerialRead(UART6);
}
void serial6write (char c)
Definition at line 88 of file pinguinoserial6.c.
{
    SerialUART6WriteChar(c);
}