/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoserial5.c File Reference
#include <stdarg.h>
*
#include <printf.c>
*
#include <serial.c>
*
#include <typedef.h>
*
Macros
#define __PINGUINOSERIAL5_C
#define ENABLE_UART5
Functions
void serial5init (u32 speed)
void serial5printf (char *fmt,...)
void serial5println (char *fmt,...)
void serial5write (char c)
char serial5getkey (void)
char * serial5getstring (void)
char serial5available (void)
char serial5read (void)
void serial5flush (void)
BOOL serial5clearrxerror (void)
Macro Definition Documentation
#define __PINGUINOSERIAL5_C
Definition at line 26 of file pinguinoserial5.c.
#define ENABLE_UART5
Definition at line 29 of file pinguinoserial5.c.
Function Documentation
char serial5available (void)
Definition at line 103 of file pinguinoserial5.c.
References SerialAvailable().
{
    return SerialAvailable(UART5);
}
BOOL serial5clearrxerror (void)
Definition at line 118 of file pinguinoserial5.c.
References ClearRxError().
{
    return(ClearRxError(UART5));
}
void serial5flush (void)
Definition at line 113 of file pinguinoserial5.c.
References SerialFlush().
{
    SerialFlush(UART5);
}
char serial5getkey (void)
Definition at line 93 of file pinguinoserial5.c.
References SerialGetKey().
{
    return SerialGetKey(UART5);
}
char* serial5getstring (void)
Definition at line 98 of file pinguinoserial5.c.
References SerialGetString().
{
    return SerialGetString(UART5);
}
void serial5init (u32 speed)
Definition at line 37 of file pinguinoserial5.c.
References SerialConfigure(), UART_ENABLE, and UART_RX_TX_ENABLED.
{
    SerialConfigure(UART5, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
}
void serial5printf (char * fmt, ...)
Definition at line 42 of file pinguinoserial5.c.
References pprintf().
Referenced by serial5println().
{
    va_list args;
    va_start(args, fmt);
    pprintf(SerialUART5WriteChar, fmt, args);
    va_end(args);
}
void serial5println (char * fmt, ...)
Definition at line 82 of file pinguinoserial5.c.
References serial5printf().
{
    serial5printf(fmt);
    serial5printf("\n\r");
}
char serial5read (void)
Definition at line 108 of file pinguinoserial5.c.
References SerialRead().
{
    return SerialRead(UART5);
}
void serial5write (char c)
Definition at line 88 of file pinguinoserial5.c.
{
    SerialUART5WriteChar(c);
}