/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoserial4.c File Reference
#include <stdarg.h>
*
#include <printf.c>
*
#include <serial.c>
*
#include <typedef.h>
*
Macros
#define __PINGUINOSERIAL4_C
#define ENABLE_UART4
Functions
void serial4init (u32 speed)
void serial4printf (char *fmt,...)
void serial4println (char *fmt,...)
void serial4write (char c)
char serial4getkey (void)
char * serial4getstring (void)
char serial4available (void)
char serial4read (void)
void serial4flush (void)
BOOL serial4clearrxerror (void)
Macro Definition Documentation
#define __PINGUINOSERIAL4_C
Definition at line 26 of file pinguinoserial4.c.
#define ENABLE_UART4
Definition at line 29 of file pinguinoserial4.c.
Function Documentation
char serial4available (void)
Definition at line 103 of file pinguinoserial4.c.
References SerialAvailable().
{
    return SerialAvailable(UART4);
}
BOOL serial4clearrxerror (void)
Definition at line 119 of file pinguinoserial4.c.
References ClearRxError().
{
    return(ClearRxError(UART4));
}
void serial4flush (void)
Definition at line 113 of file pinguinoserial4.c.
References SerialFlush().
{
    SerialFlush(UART4);
}
char serial4getkey (void)
Definition at line 93 of file pinguinoserial4.c.
References SerialGetKey().
{
    return SerialGetKey(UART4);
}
char* serial4getstring (void)
Definition at line 98 of file pinguinoserial4.c.
References SerialGetString().
{
    return SerialGetString(UART4);
}
void serial4init (u32 speed)
Definition at line 37 of file pinguinoserial4.c.
References SerialConfigure(), UART_ENABLE, and UART_RX_TX_ENABLED.
{
    SerialConfigure(UART4, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
}
void serial4printf (char * fmt, ...)
Definition at line 42 of file pinguinoserial4.c.
References pprintf().
Referenced by serial4println().
{
    va_list args;
    va_start(args, fmt);
    pprintf(SerialUART4WriteChar, fmt, args);
    va_end(args);
}
void serial4println (char * fmt, ...)
Definition at line 82 of file pinguinoserial4.c.
References serial4printf().
{
    serial4printf(fmt);
    serial4printf("\n\r");
}
char serial4read (void)
Definition at line 108 of file pinguinoserial4.c.
References SerialRead().
{
    return SerialRead(UART4);
}
void serial4write (char c)
Definition at line 88 of file pinguinoserial4.c.
{
    SerialUART4WriteChar(c);
}