/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoi2c2.c File Reference
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <system.c>
*
#include <i2c.c>
*
Macros
#define __PINGUINOI2C2_C
#define NACK true
#define ACK false
Functions
void I2C2_init ()
PROTOTYPES.
u8 I2C2_write (u16, u8 *, u8)
u8 I2C2_send (u16, u8)
u8 I2C2_get (u16)
void I2C2_sendID (u16, u8)
u8 I2C2_writechar (u8)
u8 I2C2_readchar ()
u8 I2C2_readcharAck ()
void I2C2_wait ()
void I2C2_start ()
void I2C2_stop ()
void I2C2_restart ()
void I2C2_sendNack ()
void I2C2_sendAck ()
Macro Definition Documentation
#define __PINGUINOI2C2_C
Definition at line 30 of file pinguinoi2c2.c.
#define ACK false
Definition at line 39 of file pinguinoi2c2.c.
Referenced by I2C2_readcharAck().
#define NACK true
Definition at line 38 of file pinguinoi2c2.c.
Referenced by I2C2_readchar().
Function Documentation
u8 I2C2_get (u16 adress)
Definition at line 89 of file pinguinoi2c2.c.
References I2C2, and I2C_get().
{
    return I2C_get(I2C2, adress);
}
void I2C2_init ()
PROTOTYPES.
Definition at line 62 of file pinguinoi2c2.c.
References I2C2, I2C_init(), I2C_MASTER_MODE, and I2C_SLEW_OFF.
{
    I2C_init(I2C2, I2C_MASTER_MODE, I2C_SLEW_OFF);
}
u8 I2C2_readchar ()
Definition at line 116 of file pinguinoi2c2.c.
References I2C2, I2C_readchar(), and NACK.
{
    return I2C_readchar(I2C2, NACK);
}
u8 I2C2_readcharAck ()
Definition at line 125 of file pinguinoi2c2.c.
References ACK, I2C2, and I2C_readchar().
{
    return I2C_readchar(I2C2, ACK);
}
void I2C2_restart ()
Definition at line 164 of file pinguinoi2c2.c.
References I2C2, and I2C_restart().
{
    I2C_restart(I2C2);
}
u8 I2C2_send (u16 address, u8 byte)
Definition at line 80 of file pinguinoi2c2.c.
References I2C2, and I2C_send().
{
    return I2C_send(I2C2, address, byte);
}
void I2C2_sendAck ()
Definition at line 182 of file pinguinoi2c2.c.
References I2C2, and I2C_sendAck().
{
    I2C_sendAck(I2C2);
}
void I2C2_sendID (u16 DeviceID, u8 rw)
Definition at line 98 of file pinguinoi2c2.c.
References I2C2, and I2C_sendID().
{
    I2C_sendID(I2C2, DeviceID, rw);
}
void I2C2_sendNack ()
Definition at line 173 of file pinguinoi2c2.c.
References I2C2, and I2C_sendNack().
{
    I2C_sendNack(I2C2);
}
void I2C2_start ()
Definition at line 144 of file pinguinoi2c2.c.
References I2C2, and I2C_start().
{
    I2C_start(I2C2);
}
void I2C2_stop ()
Definition at line 154 of file pinguinoi2c2.c.
References I2C2, and I2C_stop().
{
    I2C_stop(I2C2);
}
void I2C2_wait ()
Definition at line 134 of file pinguinoi2c2.c.
References I2C2, and I2C_wait().
{
    I2C_wait(I2C2);
}
u8 I2C2_write (u16 adress, u8 * bytes, u8 length)
Definition at line 71 of file pinguinoi2c2.c.
References I2C2, and I2C_write().
{
    return I2C_write(I2C2, adress, bytes, length);
}
u8 I2C2_writechar (u8 byte)
Definition at line 107 of file pinguinoi2c2.c.
References I2C2, and I2C_writechar().
{
    return I2C_writechar(I2C2, byte);
}