/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoi2c1.c File Reference
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
#include <system.c>
*
#include <i2c.c>
*
Macros
#define __PINGUINOI2C1_C
#define NACK true
#define ACK false
Functions
void I2C1_init ()
PROTOTYPES.
u8 I2C1_write (u16, u8 *, u8)
u8 I2C1_send (u16, u8)
u8 I2C1_get (u16)
void I2C1_sendID (u16, u8)
u8 I2C1_writechar (u8)
u8 I2C1_readchar ()
u8 I2C1_readcharAck ()
void I2C1_wait ()
void I2C1_start ()
void I2C1_stop ()
void I2C1_restart ()
void I2C1_sendNack ()
void I2C1_sendAck ()
Macro Definition Documentation
#define __PINGUINOI2C1_C
Definition at line 30 of file pinguinoi2c1.c.
#define ACK false
Definition at line 39 of file pinguinoi2c1.c.
Referenced by I2C1_readcharAck().
#define NACK true
Definition at line 38 of file pinguinoi2c1.c.
Referenced by I2C1_readchar().
Function Documentation
u8 I2C1_get (u16 address)
Definition at line 93 of file pinguinoi2c1.c.
References I2C1, and I2C_get().
{
    return I2C_get(I2C1, address);
}
void I2C1_init ()
PROTOTYPES.
Definition at line 62 of file pinguinoi2c1.c.
References I2C1, I2C_100KHZ, I2C_init(), and I2C_MASTER_MODE.
Referenced by MCP23017_init(), and MCP342x_init().
{
    //I2C_init(I2C1, I2C_MASTER_MODE, I2C_SLEW_OFF);
    I2C_init(I2C1, I2C_MASTER_MODE, I2C_100KHZ);
}
u8 I2C1_readchar ()
Definition at line 120 of file pinguinoi2c1.c.
References I2C1, I2C_readchar(), and NACK.
Referenced by MCP23017_read_A(), MCP23017_read_B(), MCP23017_read_W(), and MCP342x_read_Data().
{
    return I2C_readchar(I2C1, NACK);
}
u8 I2C1_readcharAck ()
Definition at line 129 of file pinguinoi2c1.c.
References ACK, I2C1, and I2C_readchar().
Referenced by MCP23017_read_A(), MCP23017_read_W(), and MCP342x_read_Data().
{
    return I2C_readchar(I2C1, ACK);
}
void I2C1_restart ()
Definition at line 168 of file pinguinoi2c1.c.
References I2C1, and I2C_restart().
Referenced by MCP23017_read_A(), MCP23017_read_B(), and MCP23017_read_W().
{
    I2C_restart(I2C1);
}
u8 I2C1_send (u16 address, u8 byte)
Definition at line 84 of file pinguinoi2c1.c.
References I2C1, and I2C_send().
{
    return I2C_send(I2C1, address, byte);
}
void I2C1_sendAck ()
Definition at line 186 of file pinguinoi2c1.c.
References I2C1, and I2C_sendAck().
{
    I2C_sendAck(I2C1);
}
void I2C1_sendID (u16 DeviceID, u8 rw)
Definition at line 102 of file pinguinoi2c1.c.
References I2C1, and I2C_sendID().
{
    I2C_sendID(I2C1, DeviceID, rw);
}
void I2C1_sendNack ()
Definition at line 177 of file pinguinoi2c1.c.
References I2C1, and I2C_sendNack().
{
    I2C_sendNack(I2C1);
}
void I2C1_start ()
Definition at line 148 of file pinguinoi2c1.c.
References I2C1, and I2C_start().
Referenced by MCP23017_read_A(), MCP23017_read_B(), MCP23017_read_W(), MCP23017_write_A(), MCP23017_write_B(), MCP23017_write_W(), MCP342x_read_Data(), and MCP342x_write().
{
    I2C_start(I2C1);
}
void I2C1_stop ()
Definition at line 158 of file pinguinoi2c1.c.
References I2C1, and I2C_stop().
Referenced by MCP23017_Fault(), MCP23017_read_A(), MCP23017_read_B(), MCP23017_read_W(), MCP23017_write_A(), MCP23017_write_B(), MCP23017_write_W(), MCP342x_Fault(), MCP342x_read_Data(), and MCP342x_write().
{
    I2C_stop(I2C1);
}
void I2C1_wait ()
Definition at line 138 of file pinguinoi2c1.c.
References I2C1, and I2C_wait().
{
    I2C_wait(I2C1);
}
u8 I2C1_write (u16 address, u8 * bytes, u8 length)
Definition at line 72 of file pinguinoi2c1.c.
References I2C1, and I2C_write().
{
    u8 i, r;
    for (i=0; i<length; i++)
        r = I2C_write(I2C1, address, bytes++);
    return r;
}
u8 I2C1_writechar (u8 byte)
Definition at line 111 of file pinguinoi2c1.c.
References I2C1, and I2C_writechar().
Referenced by MCP23017_read_A(), MCP23017_read_B(), MCP23017_read_W(), MCP23017_write_A(), MCP23017_write_B(), MCP23017_write_W(), MCP342x_read_Data(), and MCP342x_write().
{
    return I2C_writechar(I2C1, byte);
}