/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoserial2.c File Reference
#include <stdarg.h>
*
#include <printf.c>
*
#include <serial.c>
*
#include <typedef.h>
*
Macros
#define __PINGUINOSERIAL2_C
Functions
void serial2init (u32 speed)
void serial2printf (char *fmt,...)
void serial2print (char *fmt,...)
void serial2println (char *fmt,...)
void serial2write (char c)
char serial2getkey (void)
char * serial2getstring (void)
char serial2available (void)
char serial2read (void)
void serial2flush (void)
BOOL serial2clearrxerror (void)
Macro Definition Documentation
#define __PINGUINOSERIAL2_C
Definition at line 27 of file pinguinoserial2.c.
Function Documentation
char serial2available (void)
Definition at line 161 of file pinguinoserial2.c.
References SerialAvailable(), UART1, and UART2.
Referenced by modbuss_SerialAvailable().
{
#ifdef PIC32_PINGUINO_220
    return SerialAvailable(UART1);
#else
    return SerialAvailable(UART2);
#endif
}
BOOL serial2clearrxerror (void)
Definition at line 188 of file pinguinoserial2.c.
References ClearRxError(), UART1, and UART2.
Referenced by modbuss_SerialClearRxError().
{
#ifdef PIC32_PINGUINO_220
    return(ClearRxError(UART1));
#else
    return(ClearRxError(UART2));
#endif
}
void serial2flush (void)
Definition at line 179 of file pinguinoserial2.c.
References SerialFlush(), UART1, and UART2.
Referenced by modbuss_SerialFlush().
{
#ifdef PIC32_PINGUINO_220
    SerialFlush(UART1);
#else
    SerialFlush(UART2);
#endif
}
char serial2getkey (void)
Definition at line 143 of file pinguinoserial2.c.
References SerialGetKey(), UART1, and UART2.
{
#ifdef PIC32_PINGUINO_220
    return SerialGetKey(UART1);
#else
    return SerialGetKey(UART2);
#endif
}
char* serial2getstring (void)
Definition at line 152 of file pinguinoserial2.c.
References SerialGetString(), UART1, and UART2.
{
#ifdef PIC32_PINGUINO_220
    return SerialGetString(UART1);
#else
    return SerialGetString(UART2);
#endif
}
void serial2init (u32 speed)
Definition at line 34 of file pinguinoserial2.c.
References SerialConfigure(), UART1, UART2, UART_ENABLE, and UART_RX_TX_ENABLED.
Referenced by debug(), and modbuss_SerialBegin().
{
    #ifdef PIC32_PINGUINO_220
        SerialConfigure(UART1, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
    #else
        SerialConfigure(UART2, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
    #endif
}
void serial2print (char * fmt, ...)
Definition at line 62 of file pinguinoserial2.c.
References BIN, DEC, HEX, OCT, and serial2printf().
{
    // unsigned char *s;
    unsigned char s;
    va_list args; // list of arguments
    va_start(args, fmt); // initialize the list
    // s = va_start(args, fmt);
    s = (unsigned char) va_arg(args, int); // get the first variable arg.
    //switch (*s)
    switch (s)
    {
        case DEC:
            serial2printf("%d",fmt);
            break;
        case HEX:
            serial2printf("%x",fmt);
            break;
        case BYTE:
            serial2printf("%d",fmt);
            break;
        case OCT:
            serial2printf("%o",fmt);
            break;
        case BIN:
            serial2printf("%b",fmt);
            break;
        default:
            serial2printf(fmt);
            break;
    }
}
void serial2printf (char * fmt, ...)
Definition at line 43 of file pinguinoserial2.c.
References pprintf(), SerialUART1WriteChar(), and SerialUART2WriteChar().
Referenced by debug(), serial2print(), and serial2println().
{
    va_list args;
    va_start(args, fmt);
    #ifdef PIC32_PINGUINO_220
        pprintf(SerialUART1WriteChar, fmt, args);
    #else
        pprintf(SerialUART2WriteChar, fmt, args);
    #endif
    va_end(args);
}
void serial2println (char * fmt, ...)
Definition at line 128 of file pinguinoserial2.c.
References serial2printf().
{
    serial2printf(fmt);
    serial2printf("\r\n");
}
char serial2read (void)
Definition at line 170 of file pinguinoserial2.c.
References SerialRead(), UART1, and UART2.
Referenced by modbuss_SerialRead().
{
#ifdef PIC32_PINGUINO_220
    return SerialRead(UART1);
#else
    return SerialRead(UART2);
#endif
}
void serial2write (char c)
Definition at line 134 of file pinguinoserial2.c.
References SerialUART1WriteChar(), and SerialUART2WriteChar().
Referenced by modbuss_SerialWrite().
{
#ifdef PIC32_PINGUINO_220
    SerialUART1WriteChar(c);
#else
    SerialUART2WriteChar(c);
#endif
}