/dvpt/pinguino/git/pinguino-libraries/p32/include/pinguino/core/pinguinoserial3.c File Reference
#include <stdarg.h>
*
#include <printf.c>
*
#include <serial.c>
*
#include <typedef.h>
*
Macros
#define __PINGUINOSERIAL3_C
#define ENABLE_UART3
Functions
void serial3init (u32 speed)
void serial3printf (char *fmt,...)
void serial3println (char *fmt,...)
void serial3write (char c)
char serial3getkey (void)
char * serial3getstring (void)
char serial3available (void)
char serial3read (void)
void serial3flush (void)
BOOL serial3clearrxerror (void)
Macro Definition Documentation
#define __PINGUINOSERIAL3_C
Definition at line 26 of file pinguinoserial3.c.
#define ENABLE_UART3
Definition at line 29 of file pinguinoserial3.c.
Function Documentation
char serial3available (void)
Definition at line 103 of file pinguinoserial3.c.
References SerialAvailable().
Referenced by modbuss_SerialAvailable().
{
    return SerialAvailable(UART3);
}
BOOL serial3clearrxerror (void)
Definition at line 118 of file pinguinoserial3.c.
References ClearRxError().
Referenced by modbuss_SerialClearRxError().
{
    return(ClearRxError(UART3));
}
void serial3flush (void)
Definition at line 113 of file pinguinoserial3.c.
References SerialFlush().
Referenced by modbuss_SerialFlush().
{
    SerialFlush(UART3);
}
char serial3getkey (void)
Definition at line 93 of file pinguinoserial3.c.
References SerialGetKey().
{
    return SerialGetKey(UART3);
}
char* serial3getstring (void)
Definition at line 98 of file pinguinoserial3.c.
References SerialGetString().
{
    return SerialGetString(UART3);
}
void serial3init (u32 speed)
Definition at line 37 of file pinguinoserial3.c.
References SerialConfigure(), UART_ENABLE, and UART_RX_TX_ENABLED.
Referenced by modbuss_SerialBegin().
{
    SerialConfigure(UART3, UART_ENABLE,
      UART_RX_TX_ENABLED, speed);
}
void serial3printf (char * fmt, ...)
Definition at line 42 of file pinguinoserial3.c.
References pprintf().
Referenced by serial3println().
{
    va_list args;
    va_start(args, fmt);
    pprintf(SerialUART3WriteChar, fmt, args);
    va_end(args);
}
void serial3println (char * fmt, ...)
Definition at line 82 of file pinguinoserial3.c.
References serial3printf().
{
    serial3printf(fmt);
    serial3printf("\n\r");
}
char serial3read (void)
Definition at line 108 of file pinguinoserial3.c.
References SerialRead().
Referenced by modbuss_SerialRead().
{
    return SerialRead(UART3);
}
void serial3write (char c)
Definition at line 88 of file pinguinoserial3.c.
Referenced by modbuss_SerialWrite().
{
    SerialUART3WriteChar(c);
}