/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/reset.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <const.h>
*
#include <macro.h>
*
Macros
#define __RESET_C
#define SystemIsConfigMismatchReset() !RCONbits.NOT_CM
#define SystemIsSleepInstructionReset() !RCONbits.NOT_PD
#define SystemIsResetInstructionReset() !RCONbits.NOT_RI
#define SystemIsStackFullReset() STKPTRbits.STKFUL
#define SystemIsStackUnderflowReset() STKPTRbits.STKUNF
Functions
char SystemIsPowerOnReset ()
char SystemIsBrownOutReset ()
char SystemIsWatchdogTimeoutReset ()
char SystemIsMclrReset (void)
Macro Definition Documentation
#define __RESET_C
Definition at line 27 of file reset.c.
#define SystemIsConfigMismatchReset() !RCONbits.NOT_CM
Definition at line 83 of file reset.c.
Referenced by SystemIsMclrReset().
#define SystemIsResetInstructionReset() !RCONbits.NOT_RI
Definition at line 114 of file reset.c.
Referenced by SystemIsMclrReset().
#define SystemIsSleepInstructionReset() !RCONbits.NOT_PD
Definition at line 89 of file reset.c.
Referenced by SystemIsMclrReset().
#define SystemIsStackFullReset() STKPTRbits.STKFUL
Definition at line 120 of file reset.c.
Referenced by SystemIsMclrReset().
#define SystemIsStackUnderflowReset() STKPTRbits.STKUNF
Definition at line 126 of file reset.c.
Referenced by SystemIsMclrReset().
Function Documentation
char SystemIsBrownOutReset ()
Definition at line 97 of file reset.c.
Referenced by SystemIsMclrReset().
{
    if (RCONbits.NOT_POR)
    {
        if (!RCONbits.NOT_BOR)
        {
            RCONbits.NOT_BOR = 1;
            return 1;
        }
    }
    return 0;
}
char SystemIsMclrReset (void)
Definition at line 148 of file reset.c.
References SystemIsBrownOutReset(), SystemIsConfigMismatchReset, SystemIsPowerOnReset(), SystemIsResetInstructionReset, SystemIsSleepInstructionReset, SystemIsStackFullReset, SystemIsStackUnderflowReset, and SystemIsWatchdogTimeoutReset().
{
    // power-on reset ?
    if (SystemIsPowerOnReset()) return 0;
    // config. mismatch reset ?
    if (SystemIsConfigMismatchReset()) return 0;
    // sleep instruction reset ?
    if (SystemIsSleepInstructionReset()) return 0;
    // brown-out reset ?
    if (SystemIsBrownOutReset()) return 0;
    // watchdog timeout reset ?
    if (SystemIsWatchdogTimeoutReset()) return 0;
    // reset instruction ?
    if (SystemIsResetInstructionReset()) return 0;
    // stack full reset ?
    if (SystemIsStackFullReset()) return 0;
    // stack underflow reset ?
    if (SystemIsStackUnderflowReset()) return 0;
    // then it's a MCLR-pin reset
    return 1;
}
char SystemIsPowerOnReset ()
An MCLR reset will not affect the TO, POR and BOR bits and can be detected by the absence of other reset causes indicated by these bits, if they were set appropriately before the reset.
A Power-On Reset will clear the POR bit and set the TO and PD bits. It is recommended that the POR bit be set after a Power-on Reset has been detected, so that subsequent Power-on Resets may be detected.
If a brown-out reset was enabled the BOR bit will be unknown. Brown-out Reset is said to have occurred when BOR is ‘0’ and POR is ‘1’ (assuming that POR was set to ‘1’ by software immediately after a Power-on Reset).
RCON <7:0> = IPEN | - | CM | RI | TO | PD | POR | BOR
IPEN = 1 : Enable priority levels on interrupts 0 CM = 1 : A Configuration Mismatch Reset has not occurred RI = 1 : The RESET instruction was not executed TO = 1 : Set by power-up, CLRWDT instruction or SLEEP instruction PD = 0 : 1 = Set by power-up or by the CLRWDT instruction 0 = Set by execution of the SLEEP instruction
POR = 0 : A Power-on Reset occurred (must be set in software after a Power-on Reset occurs) BOR = 0: A Brown-out Reset occurred (must be set in software after a Brown-out Reset occurs)
Definition at line 69 of file reset.c.
Referenced by SystemIsMclrReset().
{
    if (!RCONbits.NOT_POR)
    {
        RCONbits.NOT_POR = 1;
        return 1;
    }
    return 0;
}
char SystemIsWatchdogTimeoutReset ()
Definition at line 132 of file reset.c.
Referenced by SystemIsMclrReset().
{
    // checks if watchdog is enabled
    if (WDTCONbits.SWDTEN)
    {
        // watchdog timeout reset
        if (!RCONbits.NOT_TO)
            return 1;
    }
    return 0;
}