/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/rtcc.h File Reference
#include <typedef.h>
*
Data Structures
union rtccTime
union rtccDate
Macros
#define RTCC_ALARM_EVERY_HALF_SECOND 0b0000
#define RTCC_ALARM_EVERY_SECOND 0b0001
#define RTCC_ALARM_EVERY_TEN_SECONDS 0b0010
#define RTCC_ALARM_EVERY_MINUTE 0b0011
#define RTCC_ALARM_EVERY_TEN_MINUTES 0b0100
#define RTCC_ALARM_EVERY_HOUR 0b0101
#define RTCC_ALARM_EVERY_DAY 0b0110
#define RTCC_ALARM_EVERY_WEEK 0b0111
#define RTCC_ALARM_EVERY_MONTH 0b1000
#define RTCC_ALARM_EVERY_YEAR 0b1001
Enumerations
enum rtccRes {
*
RTCC_SOSC_ON,
RTCC_SOSC_NRDY,
RTCC_CLK_NRDY,
RTCC_WR_DSBL,
*
RTCC_SOSC_ON,
RTCC_SOSC_NRDY,
RTCC_CLK_NRDY,
RTCC_WR_DSBL
 }
Functions
void RTCC_ConvertTime (rtccTime *)
void RTCC_ConvertDate (rtccDate *)
void RTCC_SetWriteEnable (void)
void RTCC_SetWriteDisable (void)
u8 RTCC_IsWriteEnable (void)
void RTCC_Enable (void)
void RTCC_Disable (void)
u8 RTCC_IsEnable (void)
void RTCC_Wait (void)
void RTCC_Shutdown (void)
void RTCC_init (u32, u32, s16)
void RTCC_SetTime (u32)
void RTCC_SetDate (u32)
void RTCC_SetTimeDate (u32, u32)
void RTCC_GetTime (rtccTime *)
void RTCC_GetDate (rtccDate *)
void RTCC_GetTimeDate (rtccTime *, rtccDate *)
void RTCC_SetCalibration (s16)
s16 RTCC_GetCalibration (void)
u8 RTCC_IsAlarmEnable (void)
u8 RTCC_IsChimeEnable (void)
u8 RTCC_GetAlarmRepeat (void)
void RTCC_SetAlarmRepeatCount (char)
u8 RTCC_GetAlarmRepeatCount (void)
void RTCC_SetAlarmTime (u32)
void RTCC_GetAlarmTime (rtccTime *)
void RTCC_SetAlarmDate (u32)
void RTCC_GetAlarmDate (rtccDate *)
void RTCC_SetAlarmTimeDate (u32, u32)
void RTCC_GetAlarmTimeDate (rtccTime *, rtccDate *)
u8 RTCC_GetHalfSecond (void)
u8 RTCC_GetOutputEnable (void)
void RTCC_AlarmIntEnable (void)
Macro Definition Documentation
#define RTCC_ALARM_EVERY_DAY 0b0110
Definition at line 89 of file rtcc.h.
#define RTCC_ALARM_EVERY_HALF_SECOND 0b0000
Definition at line 83 of file rtcc.h.
#define RTCC_ALARM_EVERY_HOUR 0b0101
Definition at line 88 of file rtcc.h.
#define RTCC_ALARM_EVERY_MINUTE 0b0011
Definition at line 86 of file rtcc.h.
#define RTCC_ALARM_EVERY_MONTH 0b1000
Definition at line 91 of file rtcc.h.
#define RTCC_ALARM_EVERY_SECOND 0b0001
Definition at line 84 of file rtcc.h.
#define RTCC_ALARM_EVERY_TEN_MINUTES 0b0100
Definition at line 87 of file rtcc.h.
#define RTCC_ALARM_EVERY_TEN_SECONDS 0b0010
Definition at line 85 of file rtcc.h.
#define RTCC_ALARM_EVERY_WEEK 0b0111
Definition at line 90 of file rtcc.h.
#define RTCC_ALARM_EVERY_YEAR 0b1001
Definition at line 92 of file rtcc.h.
Enumeration Type Documentation
enum rtccRes
Enumerator
RTCC_SOSC_ON
RTCC_SOSC_NRDY
RTCC_CLK_NRDY
RTCC_WR_DSBL
RTCC_SOSC_ON
RTCC_SOSC_NRDY
RTCC_CLK_NRDY
RTCC_WR_DSBL
Definition at line 74 of file rtcc.h.
{
    RTCC_SOSC_ON, // success, SOSC is running
    RTCC_SOSC_NRDY, // SOSC not running
    RTCC_CLK_NRDY, // RTCC clock not running
    RTCC_WR_DSBL, // WR is disabled
}rtccRes;
Function Documentation
void RTCC_AlarmIntEnable (void)
Definition at line 899 of file rtcc.c.
References RTCC_SetAlarmIntEnable(), and True.
{
    RTCC_SetAlarmIntEnable(True);
}
void RTCC_ConvertDate (rtccDate *)
Definition at line 69 of file rtcc.c.
References bcd2bin(), rtccDate::dayofmonth, rtccDate::dayofweek, rtccDate::month, and rtccDate::year.
Referenced by get_fattime().
{
    pDt->dayofweek = bcd2bin(pDt->dayofweek);
    pDt->dayofmonth = bcd2bin(pDt->dayofmonth);
    pDt->month = bcd2bin(pDt->month);
    pDt->year = bcd2bin(pDt->year);
}
void RTCC_ConvertTime (rtccTime *)
Definition at line 62 of file rtcc.c.
References bcd2bin(), rtccTime::hours, rtccTime::minutes, and rtccTime::seconds.
Referenced by get_fattime().
{
    pTm->hours = bcd2bin(pTm->hours);
    pTm->minutes = bcd2bin(pTm->minutes);
    pTm->seconds = bcd2bin(pTm->seconds);
}
void RTCC_Disable (void)
Definition at line 129 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
Referenced by RTCC_SetAlarmEnable(), RTCC_SetAlarmInitialPulse(), and RTCC_Shutdown().
{
    RTCC_SetWriteEnable();
    RTCCFGbits.RTCEN = 0;
    RTCC_SetWriteDisable();
}
void RTCC_Enable (void)
Definition at line 116 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
Referenced by RTCC_init(), RTCC_Open(), RTCC_SetAlarmEnable(), and RTCC_SetAlarmInitialPulse().
{
    RTCC_SetWriteEnable();
    RTCCFGbits.RTCEN = 1;
    RTCC_SetWriteDisable();
    PIR3bits.RTCCIF = 0;
}
void RTCC_GetAlarmDate (rtccDate *)
int RTCC_GetAlarmRepeat (void)
Definition at line 625 of file rtcc.c.
{
    int r0, r1;
    do
    {
        r0 = RTCALRMbits.AMASK;
        r1 = RTCALRMbits.AMASK;
    }while (r0 != r1);
    return r0;
}
char RTCC_GetAlarmRepeatCount (void)
Definition at line 657 of file rtcc.c.
{
    char rpt0, rpt1;
    do
    {
        rpt0 = RTCALRMbits.ARPT;
        rpt1 = RTCALRMbits.ARPT;
    } while (rpt0 != rpt1);
    return rpt0;
}
void RTCC_GetAlarmTime (rtccTime *)
void RTCC_GetAlarmTimeDate (rtccTime * pTm, rtccDate * pDt)
Definition at line 726 of file rtcc.c.
References rtccTime::l, and rtccDate::l.
{
    pTm->l = ALRMTIME;
    pDt->l = ALRMDATE;
}
int RTCC_GetCalibration (void)
Definition at line 484 of file rtcc.c.
{
     return RTCCONbits.CAL;
}
void RTCC_GetDate (rtccDate *)
int RTCC_GetHalfSecond (void)
Definition at line 776 of file rtcc.c.
{
     return RTCCONbits.HALFSEC!=0;
}
int RTCC_GetOutputEnable (void)
Definition at line 875 of file rtcc.c.
{
     return RTCCONbits.RTCOE!=0;
}
void RTCC_GetTime (rtccTime *)
void RTCC_GetTimeDate (rtccTime * pTm, rtccDate * pDt)
Definition at line 442 of file rtcc.c.
References rtccTime::l, and rtccDate::l.
Referenced by get_fattime().
{
    rtccTime t0;
    rtccDate d0;
    do
    {
        d0.l = RTCDATE;
        t0.l = RTCTIME;
        pTm->l = RTCTIME;
        pDt->l = RTCDATE;
    } while ((d0.l != pDt->l) || (t0.l != pTm->l)); // update the user requested data
}
void RTCC_init (u32 , u32 , s16)
u8 RTCC_IsAlarmEnable (void)
u8 RTCC_IsChimeEnable (void)
u8 RTCC_IsEnable (void)
Definition at line 140 of file rtcc.c.
{
    return RTCCFGbits.RTCEN != 0;
}
u8 RTCC_IsWriteEnable (void)
Definition at line 105 of file rtcc.c.
{
    return RTCCFGbits.RTCWREN != 0;
}
void RTCC_SetAlarmDate (u32 alDate)
Definition at line 695 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMCLR = 0xCFFF; // clear the ALRMEN, CHIME, AMASK and ARPT;
    ALRMDATE = alDate;
}
void RTCC_SetAlarmRepeatCount (char rptCnt)
Definition at line 645 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMbits.ARPT = rptCnt;
}
void RTCC_SetAlarmTime (u32 alTime)
Definition at line 675 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMCLR = 0xCFFF; // clear the ALRMEN, CHIME, AMASK and ARPT;
    ALRMTIME = alTime;
}
void RTCC_SetAlarmTimeDate (u32 alTime, u32 alDate)
Definition at line 715 of file rtcc.c.
{
    while (RTCALRM & 0x1000); // wait ALRMSYNC to be off
    RTCALRMCLR = 0xCFFF; // clear the ALRMEN, CHIME, AMASK and ARPT;
    ALRMTIME = alTime;
    ALRMDATE = alDate;
}
void RTCC_SetCalibration (s16)
void RTCC_SetDate (u32 dt)
Definition at line 388 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
Referenced by RTCC_Open().
{
    RTCC_SetWriteEnable();
    RTCCONCLR = 0x8000; // turn off the RTCC
    //Delayus(50);
    while (RTCCON & 0x40); // wait for clock to be turned off
    RTCDATE = dt; // Set date
    RTCCONSET = 0x8000; // turn on the RTCC
    //Delayus(50);
    while (!(RTCCON & 0x40)); // wait for clock to be turned on
    RTCC_SetWriteDisable();
}
void RTCC_SetTime (u32 tm)
Definition at line 351 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
Referenced by RTCC_Open().
{
    RTCC_SetWriteEnable();
    RTCCONCLR = 0x8000; // turn off the RTCC
    //Delayus(50);
    while (RTCCON & 0x40); // wait for clock to be turned off
    RTCTIME = tm; // Set time
    RTCCONSET = 0x8000; // turn on the RTCC
    //Delayus(50);
    while (!(RTCCON & 0x40)); // wait for clock to be turned on
    RTCC_SetWriteDisable();
}
void RTCC_SetTimeDate (u32 tm, u32 dt)
Definition at line 425 of file rtcc.c.
References RTCC_SetWriteDisable(), and RTCC_SetWriteEnable().
{
    RTCC_SetWriteEnable();
    RTCCONCLR = 0x8000; // turn off the RTCC
    //Delayus(50);
    while (RTCCON & 0x40); // wait for clock to be turned off
    RTCTIME = tm; // Set time
    RTCDATE = dt; // Set date
    RTCCONSET = 0x8000; // turn on the RTCC
    //Delayus(50);
    while (!(RTCCON & 0x40)); // wait for clock to be turned on
    RTCC_SetWriteDisable();
}
void RTCC_SetWriteDisable (void)
Definition at line 92 of file rtcc.c.
References SystemLock(), and SystemUnlock().
Referenced by RTCC_Disable(), RTCC_Enable(), RTCC_init(), RTCC_Open(), RTCC_SetCalibration(), RTCC_SetDate(), RTCC_SetTime(), RTCC_SetTimeDate(), and RTCC_Shutdown().
{
// SystemUnlock();
    EECON2 = 0x55; // magic sequence
    EECON2 = 0xAA;
    RTCCFGbits.RTCWREN = 0; // disable write
// SystemLock();
}
void RTCC_SetWriteEnable (void)
Definition at line 83 of file rtcc.c.
References SystemLock(), and SystemUnlock().
Referenced by RTCC_Disable(), RTCC_Enable(), RTCC_SetCalibration(), RTCC_SetDate(), RTCC_SetTime(), and RTCC_SetTimeDate().
{
// SystemUnlock();
    EECON2 = 0x55; // magic sequence
    EECON2 = 0xAA;
    RTCCFGbits.RTCWREN = 1; // enable write
// SystemLock();
}
void RTCC_Shutdown (void)
Definition at line 153 of file rtcc.c.
References INT_REAL_TIME_CLOCK, IntClearFlag(), RTCC_AlarmDisable(), RTCC_Disable(), RTCC_OutputDisable(), RTCC_SetWriteDisable(), and RTCC_SOSCdisable().
{
    RTCC_Disable();
    PIR3bits.RTCCIF = 0;
}
void RTCC_Wait (void)