/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/spi.h File Reference
Macros
#define SPI_MASTER 0b0000
#define SPI_MASTER_FOSC_4 0b0000
#define SPI_MASTER_FOSC_8 0b1010
#define SPI_MASTER_FOSC_16 0b0001
#define SPI_MASTER_FOSC_64 0b0010
#define SPI_MASTER_FOSC_T2 0b0011
#define SPI_SLAVE_SS 0b0100
#define SPI_SLAVE 0b0101
#define SPI_CLOCK_DIV4 SPI_MASTER_FOSC_4
#define SPI_CLOCK_DIV8 SPI_MASTER_FOSC_8
#define SPI_CLOCK_DIV16 SPI_MASTER_FOSC_16
#define SPI_CLOCK_DIV64 SPI_MASTER_FOSC_64
#define SPI_CLOCK_TIMER2 SPI_MASTER_FOSC_T2
#define SPI_MODE0 0x00
#define SPI_MODE1 0x04
#define SPI_MODE2 0x08
#define SPI_MODE3 0x0C
#define SPI_FALLING_EDGE 0x00
#define SPI_RISING_EDGE 0x01
#define SPI_SMPEND 1<<7
#define SPI_LSBFIRST 0
#define SPI_MSBFIRST 1
Functions
void SPI_begin ()
Prototypes.
void SPI_init (u8 sync_mode, u8 bus_mode, u8 smp_phase)
void SPI_setMode (u8 mode)
void SPI_setBitOrder (u8 bitorder)
void SPI_setDataMode (u8 mode)
void SPI_setClockDivider (u8 clock)
u8 SPI_write (u8 datax)
u8 SPI_read (void)
void SPI_interrupt ()
Macro Definition Documentation
#define SPI_CLOCK_DIV16 SPI_MASTER_FOSC_16
Definition at line 106 of file spi.h.
#define SPI_CLOCK_DIV4 SPI_MASTER_FOSC_4
Definition at line 104 of file spi.h.
#define SPI_CLOCK_DIV64 SPI_MASTER_FOSC_64
Definition at line 107 of file spi.h.
#define SPI_CLOCK_DIV8 SPI_MASTER_FOSC_8
Definition at line 105 of file spi.h.
#define SPI_CLOCK_TIMER2 SPI_MASTER_FOSC_T2
Definition at line 108 of file spi.h.
#define SPI_FALLING_EDGE 0x00
Definition at line 116 of file spi.h.
#define SPI_LSBFIRST 0
Definition at line 121 of file spi.h.
#define SPI_MASTER 0b0000
SPI Hardware library for pinguino project
Author: Francisco J. Sánchez Rivas (FJ_Sanchez) fran [at] mipixel [dot] com
http://www.mipixel.com
Definition at line 95 of file spi.h.
#define SPI_MASTER_FOSC_16 0b0001
Definition at line 98 of file spi.h.
#define SPI_MASTER_FOSC_4 0b0000
Definition at line 96 of file spi.h.
#define SPI_MASTER_FOSC_64 0b0010
Definition at line 99 of file spi.h.
#define SPI_MASTER_FOSC_8 0b1010
Definition at line 97 of file spi.h.
#define SPI_MASTER_FOSC_T2 0b0011
Definition at line 100 of file spi.h.
#define SPI_MODE0 0x00
Definition at line 110 of file spi.h.
#define SPI_MODE1 0x04
Definition at line 111 of file spi.h.
#define SPI_MODE2 0x08
Definition at line 112 of file spi.h.
#define SPI_MODE3 0x0C
Definition at line 113 of file spi.h.
#define SPI_MSBFIRST 1
Definition at line 122 of file spi.h.
#define SPI_RISING_EDGE 0x01
Definition at line 117 of file spi.h.
#define SPI_SLAVE 0b0101
Definition at line 102 of file spi.h.
#define SPI_SLAVE_SS 0b0100
Definition at line 101 of file spi.h.
Referenced by SPI_begin().
#define SPI_SMPEND 1<<7
Definition at line 119 of file spi.h.
Function Documentation
void SPI_begin ()
Prototypes.
This function initializes the SPI hardware configuring polarity and edge of transition using Standard SPI Mode Terminology (datasheet Table 19-1 p206)
Mode0,Mode1 CKP CKE 0,0 0 1 0,1 0 0 1,0 1 1 1,1 1 0
Also is possible to use LOW or HIGH for mode0 to indicate the idle state clock level, and RISING or FALLING to indicate when the transmit should take place.
The sync_mode param could be any of SPI_MASTER, MASTER_FOSC_4, MASTER_FOSC_16, MASTER_FOSC_64, SLAVE_SS or SLAVE, where MASTER_FOSC_X indicates the SPI clock speed used. If you want to use the /SS pin in slave mode you should initialize the SPI using SPI_SLAVE_SS. sync_mode description 0 SPI_MASTER mode, clock = FOSC_4 1 SPI_MASTER, clock = FOSC_16 2 SPI_MASTER, clock = FOSC_64 3 SPI_MASTER, clock = TMR2 output/2 4 SPI_SLAVE mode, /SS pin enabled 5 SPI_SLAVE, /SS pin disabled smp_phase = Sample bit 0 in slave mode 0 in master mode : Input data sampled at middle of data output time 1 in master mode : Input data sampled at end of data output time Nota bene : enter 128 as decimal value or 0x80 as hexadecimal value for the below smp_phase parameter----------------------------------------------------------------- -----------------------------------------------------------------
The following code assumes that none of the SPIx input pins are shared with an analog input. If so, the AD1PCFG and corresponding TRIS registers have to be properly configured.
Perform the following steps to set up the SPI module for the Master mode operation:
Disable the SPI interrupts in the respective IEC0/1 register.
Stop and reset the SPI module by clearing the ON bit.
Clear the receive buffer.
Clear the ENHBUF bit (SPIxCON<16>) if using Standard Buffer mode or set the bit if using Enhanced Buffer mode.
If SPI interrupts are not going to be used, skip this step and continue to step 5. Otherwise the following additional steps are performed: a) Clear the SPIx interrupt flags/events in the respective IFS0/1 register. b) Set the SPIx interrupt enable bits in the respective IEC0/1 register. c) Write the SPIx interrupt priority and subpriority bits in the respective IPC5/7 register.
Write the Baud Rate register, SPIxBRG.
Clear the SPIROV bit (SPIxSTAT<6>).
Write the desired settings to the SPIxCON register with MSTEN (SPIxCON<5>) = 1.
Enable SPI operation by setting the ON bit (SPIxCON<15>).
The following code assumes that none of the SPIx input pins are shared with an analog input. If so, the AD1PCFG and corresponding TRIS registers have to be properly configured.
Perform the following steps to set up the SPI module for the Master mode operation:
Disable the SPI interrupts in the respective IEC0/1 register.
Stop and reset the SPI module by clearing the ON bit.
Clear the receive buffer.
Clear the ENHBUF bit (SPIxCON<16>) if using Standard Buffer mode or set the bit if using Enhanced Buffer mode.
If SPI interrupts are not going to be used, skip this step and continue to step 5. Otherwise the following additional steps are performed: a) Clear the SPIx interrupt flags/events in the respective IFS0/1 register. b) Set the SPIx interrupt enable bits in the respective IEC0/1 register. c) Write the SPIx interrupt priority and subpriority bits in the respective IPC5/7 register.
Write the Baud Rate register, SPIxBRG.
Clear the SPIROV bit (SPIxSTAT<6>).
Write the desired settings to the SPIxCON register with MSTEN (SPIxCON<5>) = 1.
Enable SPI operation by setting the ON bit (SPIxCON<15>).
Definition at line 118 of file spi.c.
References Delayms(), DESELECT, IntDisable(), SPI_MODE0, SPI_MODE1, SPI_MODE2, SPI_MODE3, SPI_SLAVE, SPI_SLAVE_SS, SPI_SMPEND, this_clock, this_mode, this_phase, and this_role.
Referenced by DS1306_init().
{
    DESELECT();
    ENABLE = 0;
    STATUS = 0x3F; // power on state (SMP=0)
    CONFIG = this_clock; // select serial mode
    if (this_phase == SPI_SMPEND)
        SMP = 1; // input data sampled at end of data output time
    switch(this_mode)
    {
        case SPI_MODE0: // SPI bus mode 0,0
          CKP = 0;
          CKE = 0; // data transmitted on falling edge
          break;
        case SPI_MODE1: // default SPI bus mode 0,1
          CKP = 0;
          CKE = 1; // data transmitted on falling edge
          break;
        case SPI_MODE2: // SPI bus mode 1,0
          CKP = 1; // clock idle state high
          CKE = 0; // data transmitted on rising edge
          break;
        case SPI_MODE3: // SPI bus mode 1,1
          CKP = 1; // clock idle state high
          CKE = 1; // data transmitted on falling edge
          break;
    }
    switch(this_role)
    {
        case SPI_SLAVE_SS: // slave mode w /SS enable
            SSPIN = 1; // define /SS pin as input
            SCKPIN = 1; // define clock pin as input
            break;
        case SPI_SLAVE: // slave mode w/o /SS enable
            SCKPIN = 1; // define clock pin as input
            break;
        default: // master mode, define clock en SS pin as output
            SSPIN = 0; // define SS pin as output
            SCKPIN = 0; // define clock pin as output
            break;
    }
    SDIPIN = 1; // define SDI pin as input
    SDOPIN = 0; // define SDO pin as output
    ENABLE = 1;
    Delayms(30);
    #ifdef SPIINT
        SSPIE = 1;
        INTCONbits.GIEH = 1;
        INTCONbits.GIEL = 1;
        INTCONbits.PEIE = 1;
        //SSPHPE = 1;
        FLAG = 0;
    #endif
}
void SPI_init (u8 sync_mode, u8 bus_mode, u8 smp_phase)
Referenced by DS1306_Init(), enc28j60Init(), MCP23S17_init(), and mrf24j40_setup_io().
void SPI_interrupt ()
Definition at line 264 of file spi.c.
References c.
{
u8 c;
   if (! FLAG)
      return;
   c = BUFFER;
   FLAG = 0;
   BUFFER = SPI_onEvent_func(c);
} // end of interrupt routine SPI_STC_vect
u8 SPI_read (void)
Definition at line 254 of file spi.c.
                  {
    u8 clear;
    clear = BUFFER; //clear BF
    FLAG = 0;
    BUFFER = 0xFF; // Initiate bus cycle
    while (!FLAG);
    return(BUFFER);
}
void SPI_setBitOrder (u8 bitorder)
This function sets the order of the bits shifted out of and into the SPI bus, either LSBFIRST (least-significant bit first) or MSBFIRST (most-significant bit first).
Definition at line 187 of file spi.c.
{
    this_bitorder = bitorder;
}
void SPI_setClockDivider (u8 clock)
This function sets the SPI clock divider relative to the system clock. The dividers available are 4, 8, 16, 64. The default setting is SPI_CLOCK_DIV4, which sets the SPI clock to one-quarter the frequency of the system clock.
This function sets the SPI clock divider relative to the peripheral clock. The dividers available are 2, 4, 8, 16, 32 and 64. The default setting is SPI_PBCLOCK_DIV64, which sets the SPI clock to 1/64 of the frequency of the peripheral clock.
This function sets the SPI clock divider relative to the peripheral clock. The dividers available are 2, 4, 8, 16, 32 and 64. The default setting is SPI_PBCLOCK_DIV64, which sets the SPI clock to 1/64 of the frequency of the peripheral clock.
Definition at line 226 of file spi.c.
References this_clock, and this_role.
{
    this_clock = clock;
    this_role = clock;
}
void SPI_setDataMode (u8 mode)
This function sets the SPI data mode (clock polarity and phase) Modes available are SPI_MODE0, SPI_MODE1, SPI_MODE2, or SPI_MODE3 Mode CKP CKE 0 0 0 1 0 1 2 1 0 3 1 1
This function sets the order of the bits shifted out of and into the SPI bus, either SPI_LSBFIRST (least-significant bit first) or SPI_MSBFIRST (most-significant bit first). This function sets the SPI data mode (clock polarity and phase) Bits CKP (SPIxCON<6>) and CKE (SPIxCON<8>) determine on which edge of the clock data transmission occurs. Modes available are SPI_MODE0, SPI_MODE1, SPI_MODE2, or SPI_MODE3 Mode CKP CKE 0 0 0 1 0 1 2 1 0 3 1 1
This function sets the order of the bits shifted out of and into the SPI bus, either SPI_LSBFIRST (least-significant bit first) or SPI_MSBFIRST (most-significant bit first). This function sets the SPI data mode (clock polarity and phase) Bits CKP (SPIxCON<6>) and CKE (SPIxCON<8>) determine on which edge of the clock data transmission occurs. Modes available are SPI_MODE0, SPI_MODE1, SPI_MODE2, or SPI_MODE3 Mode CKP CKE 0 0 0 1 0 1 2 1 0 3 1 1
Definition at line 204 of file spi.c.
References this_mode.
{
    this_mode = mode;
}
void SPI_setMode (u8 mode)
This function sets the SPI mode. Possible values are SPI_MASTER or SPI_SLAVE. The default setting is SPI_MASTER.
Definition at line 211 of file spi.c.
References this_clock, and this_role.
{
    this_role = mode;
    this_clock = mode;
}
u8 SPI_write (unsigned char data_out)
Write the data to be transmitted to the SPIxBUF register. Transmission (and reception) will start as soon as data is written to the SPIxBUF register.
Write the data to be transmitted to the SPIxBUF register. Transmission (and reception) will start as soon as data is written to the SPIxBUF register.
Definition at line 238 of file spi.c.
                       {
    u8 clear;
    clear = BUFFER; // clear BF
    FLAG = 0; // enable SPI2 interrupt
    WCOL = 0;
    BUFFER = datax; // send data
    if (WCOL)
        return (1);
    else
        while (!FLAG);
    return(0);
}