/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/spiloc.c File Reference
#include <delayus.c>
*
#include <digitalw.c>
*
#include <const.h>
*
#include <typedef.h>
*
Data Structures
struct SPI_Loc_Conf
Functions
BOOL SPILoc_Init (SPI_Loc_Conf *Conf)
void SPILoc_Write (SPI_Loc_Conf *Conf, volatile byte data)
u8 SPILoc_Read (SPI_Loc_Conf *Conf)
Function Documentation
BOOL SPILoc_Init (SPI_Loc_Conf * Conf)
Definition at line 34 of file spiloc.c.
References SPI_Loc_Conf::CPOL, digitalwrite(), FALSE, HIGH, INPUT, SPI_Loc_Conf::LoSCK, SPI_Loc_Conf::LoSDI, SPI_Loc_Conf::LoSDO, LOW, NULL, OUTPUT, and pinmode().
Referenced by DS1306_init(), DS1306_Init(), and MCP23S17_init().
 {
  if (Conf == NULL) return;
  pinmode(Conf->LoSCK, OUTPUT);
  if (Conf->CPOL == FALSE)
   digitalwrite(Conf->LoSCK,LOW);
  else
   digitalwrite(Conf->LoSCK,HIGH);
  pinmode(Conf->LoSDO, OUTPUT);
  digitalwrite(Conf->LoSDO,LOW);
  pinmode(Conf->LoSDI, INPUT);
 }
u8 SPILoc_Read (SPI_Loc_Conf * Conf)
Definition at line 98 of file spiloc.c.
References SPI_Loc_Conf::CPHA, SPI_Loc_Conf::CPOL, SPI_Loc_Conf::DelayuS, Delayus(), digitalread(), digitalwrite(), SPI_Loc_Conf::LoSCK, and SPI_Loc_Conf::LoSDI.
Referenced by DS1306_readn(), MCP23S17_read_A(), MCP23S17_read_B(), and MCP23S17_read_W().
{
 byte i;
 byte data = 0;
 
 if (Conf->DelayuS == 0)
  {
   for (i = 0; i < 8; i++)
    {
     if (Conf->CPHA)
      {
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
       data = data << 1;
       if (digitalread(Conf->LoSDI))
        data = data | 0x01;
      }
     else
      {
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       data = data << 1;
       if (digitalread(Conf->LoSDI))
        data = data | 0x01;
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
      }
    }
  }
 else
  {
   for (i = 0; i < 8; i++)
    {
     if (Conf->CPHA)
      {
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       Delayus(Conf->DelayuS);
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
       data = data << 1;
       if (digitalread(Conf->LoSDI))
        data = data | 0x01;
       Delayus(Conf->DelayuS);
      }
     else
      {
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       Delayus(Conf->DelayuS);
       data = data << 1;
       if (digitalread(Conf->LoSDI))
        data = data | 0x01;
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
       Delayus(Conf->DelayuS);
      }
    }
  }
 return(data);
}
void SPILoc_Write (SPI_Loc_Conf * Conf, volatile byte data)
Definition at line 47 of file spiloc.c.
References SPI_Loc_Conf::CPHA, SPI_Loc_Conf::CPOL, SPI_Loc_Conf::DelayuS, Delayus(), digitalwrite(), SPI_Loc_Conf::LoSCK, and SPI_Loc_Conf::LoSDO.
Referenced by DS1306_readn(), DS1306_writen(), MCP23S17_read_A(), MCP23S17_read_B(), MCP23S17_read_W(), MCP23S17_write_A(), MCP23S17_write_B(), and MCP23S17_write_W().
{
 byte i;
 
 if (Conf->DelayuS == 0)
  {
   for (i = 0; i < 8; i++)
    {
     if (Conf->CPHA)
      {
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       digitalwrite(Conf->LoSDO,(data & 0x80));
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
       data = data << 1;
      }
     else
      {
       digitalwrite(Conf->LoSDO,(data & 0x80));
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
       data = data << 1;
      }
    }
  }
 else
  {
   for (i = 0; i < 8; i++)
    {
     if (Conf->CPHA)
      {
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       digitalwrite(Conf->LoSDO,(data & 0x80));
       Delayus(Conf->DelayuS);
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
       Delayus(Conf->DelayuS);
       data = data << 1;
      }
     else
      {
       digitalwrite(Conf->LoSDO,(data & 0x80));
       Delayus(Conf->DelayuS);
       digitalwrite(Conf->LoSCK,(!Conf->CPOL));
       Delayus(Conf->DelayuS);
       digitalwrite(Conf->LoSCK,(Conf->CPOL));
       data = data << 1;
      }
    }
  }
 return;
}