/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/core/stdio.c File Reference
#include <stdarg.h>
*
#include <typedef.h>
*
Macros
#define __PRINTF_C
#define PRINTF_BUF_LEN 12
#define PAD_RIGHT 1
#define PAD_ZERO 2
Typedefs
typedef void(* funcout)(u8)
Functions
u8 pprintf (funcout func, const u8 *format, va_list args)
u8 psprintf2 (u8 *out, const u8 *format, va_list args)
u8 psprintf (u8 *out, const u8 *format,...)
Macro Definition Documentation
#define __PRINTF_C
Definition at line 28 of file stdio.c.
#define PAD_RIGHT 1
Definition at line 55 of file stdio.c.
#define PAD_ZERO 2
Definition at line 56 of file stdio.c.
#define PRINTF_BUF_LEN 12
Definition at line 33 of file stdio.c.
Typedef Documentation
typedef void(* funcout)(u8)
Definition at line 35 of file stdio.c.
Function Documentation
u8 pprintf (funcout func, const u8 * format, va_list args)
Definition at line 486 of file stdio.c.
Referenced by _lcd_printf(), lcdi2c_printf(), serial2printf(), serial3printf(), serial4printf(), serial5printf(), and serial6printf().
{
    //va_list args;
    
    pputchar = func;
    //va_start(args, format);
    return pprint(0, format, args);
}
u8 psprintf (u8 * out, const u8 * format, ...)
Definition at line 506 of file stdio.c.
Referenced by scan_files().
{
    va_list args;
    va_start(args, format);
    return pprint(&out, format, args);
}
u8 psprintf2 (u8 * out, const u8 * format, va_list args)
Definition at line 500 of file stdio.c.
Referenced by ILI9325_printf().
{
    return pprint(&out, format, args);
}