/dvpt/pinguino/git/pinguino-libraries/p8/pinguino/libraries/usb.c File Reference
#include <pic18fregs.h>
*
#include <typedef.h>
*
#include <usb.h>
*
Macros
#define __PINGUINOUSB
#define __USB__
#define EP1_BUFFER_SIZE 64
#define EP2_BUFFER_SIZE 64
#define USBRXSIZE 64
Functions
volatile BufferDescriptorTable __at (0x400)
u8 usbavailable (void)
void epapin_init (void)
void prepare_ep2_in (void)
void usbsend (u8 *txpointer, u8 length)
void epap_in (void)
u8 usbread ()
u8 usbreceive (u8 *rxpointer)
void epap_out (void)
void epapout_init (void)
void usb_interrupt (void)
void usbputs (u8 *txpointer, u8 length)
u8 usbgets (void)
Macro Definition Documentation
#define __PINGUINOUSB
Definition at line 9 of file usb.c.
#define __USB__
Definition at line 17 of file usb.c.
#define EP1_BUFFER_SIZE 64
Referenced by epap_out(), and epapout_init().
#define EP2_BUFFER_SIZE 64
Referenced by epap_in(), and prepare_ep2_in().
#define USBRXSIZE 64
Referenced by epap_out(), usbread(), and usbreceive().
Function Documentation
volatile BufferDescriptorTable __at (0x400)
Buffer descriptors Table (see datasheet page 171) RAM Bank 4 (0x400 though 0x4ff) is used spEcifically for endpoint buffer control in a structure known as Buffer Descriptor Table (BDTZ). TODO: find something smarter to allocate the buffer, like in usbmmap.c of the microchip firmware. If not all endpoints are used the space in RAM is wasted.
Definition at line 29 of file usb.c.
References CONFIGURATION_DESCRIPTOR, DEVICE_DESCRIPTOR, DEVICE_QUALIFIER_DESCRIPTOR, libconfiguration_descriptor, libdevice_descriptor, libstring_descriptor, outPtr, requestHandled, STRING_DESCRIPTOR, and wCount.
{
    // Enable Interrupt
    #if defined(__18f25k50) || defined(__18f45k50)
        PIR3bits.USBIF = 0; // clear usb interrupt flag
        PIE3bits.USBIE = 1; // enable usb interrupt
        IPR3bits.USBIP = 1; // high priority interrupt
    #else
        PIR2bits.USBIF = 0; // clear usb interrupt flag
        PIE2bits.USBIE = 1; // enable usb interrupt
        IPR2bits.USBIP = 1; // high priority interrupt
    #endif
    INTCONbits.GIEH = 1; // Enable global HP interrupts
    INTCONbits.GIEL = 1; // Enable global LP interrupts
}
void epap_in (void)
Definition at line 119 of file usb.c.
References BDS_DAT0, BDS_DAT1, BDS_DTSEN, BDS_USIE, EP2_BUFFER_SIZE, and EP_IN_BD.
{
    if((ep2_num_bytes_to_send == 0) && last_send_was_null)
    {
        return;
    }
    last_send_was_null = (ep2_num_bytes_to_send < EP2_BUFFER_SIZE);
    EP_IN_BD(2).Cnt = ep2_num_bytes_to_send;
    
    /* import this from bootloader v2.12 ? */
    fill_in_buffer(2, &ep2_source_data, EP2_BUFFER_SIZE, &ep2_num_bytes_to_send);
    
    if(EP_IN_BD(2).Stat.DTS == 0)
    {
        EP_IN_BD(2).Stat.uc = BDS_USIE | BDS_DAT1 |
      BDS_DTSEN;
    }
    else
    {
        EP_IN_BD(2).Stat.uc = BDS_USIE | BDS_DAT0 |
      BDS_DTSEN;
    }
}
void epap_out (void)
Definition at line 168 of file usb.c.
References BDS_BSTALL, BDS_DAT0, BDS_DAT1, BDS_DTSEN, BDS_USIE, EP1_BUFFER_SIZE, EP_OUT_BD, and USBRXSIZE.
{
    u8 cpt;
    u8 newusbwp;
    u8 caractere;
    if((EP_OUT_BD(1).Cnt >= 1) && (EP_OUT_BD(1).Cnt<
      EP1_BUFFER_SIZE))
    {
        for (cpt=0;cpt<EP_OUT_BD(1).Cnt;cpt++)
        {
            caractere=RXbuffer[cpt];
            if (usbwp!=USBRXSIZE-1) newusbwp=usbwp+1;
                else newusbwp=1;
            if (usbrp!=newusbwp) usbrx[usbwp++]=caractere;
                if (usbwp==USBRXSIZE) usbwp=1;
        }
        EP_OUT_BD(1).Cnt = EP1_BUFFER_SIZE;
        if(EP_OUT_BD(1).Stat.DTS == 0)
        {
            EP_OUT_BD(1).Stat.uc = BDS_USIE | BDS_DAT1 |
      BDS_DTSEN;
        }
        else
        {
            EP_OUT_BD(1).Stat.uc = BDS_USIE | BDS_DAT0 |
      BDS_DTSEN;
        }
    }
    else // Raise an error
    {
        EP_OUT_BD(1).Cnt = EP1_BUFFER_SIZE;
        EP_OUT_BD(1).ADR = (u8 __data *)&RXbuffer;
        EP_OUT_BD(1).Stat.uc = BDS_USIE | BDS_BSTALL;
    }
}
void epapin_init (void)
Definition at line 80 of file usb.c.
References BDS_DAT1, BDS_DTSEN, BDS_UCPU, EP_IN_BD, EPCONDIS_EN, EPHSHK_EN, and EPINEN_EN.
{
    EP_IN_BD(2).Stat.uc = BDS_UCPU | BDS_DAT1 |
      BDS_DTSEN;
    UEP2 = EPHSHK_EN | EPINEN_EN | EPCONDIS_EN;
}
void epapout_init (void)
Definition at line 202 of file usb.c.
References BDS_DAT0, BDS_DTSEN, BDS_USIE, EP1_BUFFER_SIZE, EP_OUT_BD, EPCONDIS_EN, EPHSHK_EN, and EPOUTEN_EN.
{
    EP_OUT_BD(1).Cnt = EP1_BUFFER_SIZE;
    EP_OUT_BD(1).ADR = (u8 __data *)&RXbuffer;
    EP_OUT_BD(1).Stat.uc = BDS_USIE | BDS_DAT0 |
      BDS_DTSEN;
    UEP1 = EPHSHK_EN | EPOUTEN_EN | EPCONDIS_EN; // Init EPAPPLI as
       an OUT EP
    usbwp=1; // init pointer for rx buffer pinguino
    usbrp=1;
}
void prepare_ep2_in (void)
Definition at line 86 of file usb.c.
References BDS_DAT0, BDS_DAT1, BDS_DTSEN, BDS_USIE, EP2_BUFFER_SIZE, and EP_IN_BD.
Referenced by usbsend().
{
    last_send_was_null = (ep2_num_bytes_to_send < EP2_BUFFER_SIZE);
    EP_IN_BD(2).Cnt = ep2_num_bytes_to_send;
    EP_IN_BD(2).ADR = (u8 __data *)&TXBuffer;
    fill_in_buffer(2, &ep2_source_data, EP2_BUFFER_SIZE, &ep2_num_bytes_to_send);
    if(EP_IN_BD(2).Stat.DTS == 0)
    {
        EP_IN_BD(2).Stat.uc = BDS_USIE | BDS_DAT1 |
      BDS_DTSEN;
    }
    else
    {
        EP_IN_BD(2).Stat.uc = BDS_USIE | BDS_DAT0 |
      BDS_DTSEN;
    }
}
void usb_interrupt (void)
Definition at line 212 of file usb.c.
{
    #if defined(__18f25k50) || defined(__18f45k50)
    if(PIR3bits.USBIF)
    #else
    if(PIR2bits.USBIF)
    #endif
    {
        dispatch_usb_event();
        UIRbits.SOFIF = 0;
        UIRbits.URSTIF = 0;
        PIR2bits.USBIF = 0;
        UEIR = 0;
    }
}
u8 usbavailable (void)
Definition at line 73 of file usb.c.
Referenced by usbread(), and usbreceive().
{
    return (usbwp!=usbrp);
}
u8 usbgets (void)
Definition at line 233 of file usb.c.
References usbread().
{
    return(usbread()); // one only character is returned
}
void usbputs (u8 * txpointer, u8 length)
Definition at line 228 of file usb.c.
References usbsend().
{
    usbsend(txpointer, length);
}
u8 usbread ()
Definition at line 143 of file usb.c.
References usbavailable(), and USBRXSIZE.
Referenced by usbgets().
{
    u8 caractere=0;
    if (usbavailable)
    {
        caractere=usbrx[usbrp++];
        if (usbrp==USBRXSIZE)
            usbrp=1;
    }
    return(caractere);
}
u8 usbreceive (u8 * rxpointer)
Definition at line 156 of file usb.c.
References usbavailable(), and USBRXSIZE.
{
    u8 rp = 0;
    while (usbavailable())
    {
        rxpointer[rp++]= usbrx[usbrp++];
        if (usbrp==USBRXSIZE)
            usbrp=1;
    }
    return(rp);
}
void usbsend (u8 * txpointer, u8 length)
Definition at line 102 of file usb.c.
References prepare_ep2_in().
Referenced by usbputs().
{
    ep2_source_data=txpointer;
    ep2_num_bytes_to_send=length;
    prepare_ep2_in();
}